"use client";

import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import AipServiceLearningDetailsV8 from "../components/AipServiceLearningDetailsV8";
import SharedServiceWalkthrough from "../components/SharedServiceWalkthrough";
import "../components/AzureLibrary.css";
import { assetUrl } from "../../lib/asset-url";

export const services = [
  { name: "AWS Config", file: "/el10/aws-config.webp", accent: "#7c3aed", summary: "Configuration history and continuous compliance" },
  { name: "Systems Manager", file: "/el10/systems-manager.webp", accent: "#db2777", summary: "Fleet operations, patching, secure access, and automation" },
  { name: "Audit Manager", file: "/el10/audit-manager.webp", accent: "#9333ea", summary: "Automated audit evidence collection and reporting" },
  { name: "AWS Organizations", file: "/el10/organizations.webp", accent: "#2563eb", summary: "Multi-account hierarchy, billing, and policy guardrails" },
  { name: "AWS Control Tower", file: "/el10/control-tower.webp", accent: "#ea580c", summary: "Governed multi-account landing zones" },
  { name: "AWS CloudFormation", file: "/el10/cloudformation.webp", accent: "#ec4899", summary: "Provision AWS infrastructure as code" },
  { name: "CloudFormation StackSets", file: "/el10/cloudformation-stacksets.webp", accent: "#db2777", summary: "Deploy stacks across accounts and Regions" },
  { name: "AWS CloudTrail", file: "/el10/cloudtrail.webp", accent: "#7c3aed", summary: "Record and investigate AWS API activity" },
  { name: "AWS Service Catalog", file: "/el10/service-catalog.webp", accent: "#2563eb", summary: "Govern approved cloud products and portfolios" },
  { name: "AWS Compute Optimizer", file: "/el10/compute-optimizer.webp", accent: "#16a34a", summary: "Rightsizing recommendations from utilization data" },
  { name: "Amazon EventBridge", file: "/el10/eventbridge-final.webp", accent: "#7c3aed", summary: "Event buses, rules, pipes, and serverless automation" },
  { name: "AWS Resource Explorer", file: "/el10/resource-explorer-final.webp", accent: "#2563eb", summary: "Search and discover resources across Regions and accounts" },
  { name: "AWS Auto Scaling", file: "/el10/auto-scaling.webp", accent: "#16a34a", summary: "Automatically adjust capacity to match demand" },
  { name: "AWS Trusted Advisor", file: "/el10/trusted-advisor.webp", accent: "#16a34a", summary: "Recommendations for cost, security, performance, and limits" },
  { name: "AWS Well-Architected Tool", file: "/el10/well-architected.webp", accent: "#7c3aed", summary: "Review workloads against the six pillars" },
  { name: "AWS Artifact", file: "/el10/artifact.webp", accent: "#7c3aed", summary: "Access AWS compliance reports and agreements" },
  { name: "AWS License Manager", file: "/el10/license-manager.webp", accent: "#2563eb", summary: "Track and govern software license usage" },
  { name: "AWS Resource Groups", file: "/el10/resource-groups.webp", accent: "#7c3aed", summary: "Organize related resources into logical groups" },
  { name: "AWS Service Quotas", file: "/el10/aws-service-quotas.webp", accent: "#2563eb", summary: "View limits and request quota increases" },
  { name: "AWS Health Dashboard", file: "/el10/health-dashboard.webp", accent: "#16a34a", summary: "Personalized visibility into AWS service events" },
  { name: "AWS User Notifications", file: "/el10/user-notifications.webp", accent: "#db2777", summary: "Route AWS notifications to the right channels" },
  { name: "AWS Account Management", file: "/el10/account-management.webp", accent: "#2563eb", summary: "Manage account profile, contacts, and Regions" },
  { name: "AWS Resource Access Manager (RAM)", file: "/el10/ram.webp", accent: "#7c3aed", summary: "Share resources securely across accounts and organizations" },
  { name: "AWS Billing and Cost Management", file: "/el10/billing-cost.webp", accent: "#2563eb", summary: "Understand, allocate, and optimize AWS spending" },
  { name: "AWS Budgets", file: "/el10/budgets.webp", accent: "#16a34a", summary: "Set thresholds, alerts, and automated cost actions" },
  { name: "AWS Cost Explorer", file: "/el10/cost-explorer.webp", accent: "#7c3aed", summary: "Analyze cost and usage with forecasts and reports" },
  { name: "AWS Service Management / AppRegistry", file: "/el10/appregistry.webp", accent: "#db2777", summary: "Register applications and connect operational metadata" },
  { name: "Amazon CloudWatch", file: "/el10/cloudwatch.webp", accent: "#db2777", summary: "Metrics, logs, alarms, traces, and dashboards" },
  { name: "AWS Console Mobile Application", file: "/el10/console-mobile.webp", accent: "#2563eb", summary: "Monitor and manage selected resources on mobile" },
  { name: "AWS Launch Wizard", file: "/el10/launch-wizard.webp", accent: "#7c3aed", summary: "Guided deployment for complex third-party workloads" },
  { name: "Amazon Managed Grafana", file: "/el10/managed-grafana.webp", accent: "#7c3aed", summary: "Managed operational dashboards and visualization" },
  { name: "Amazon Managed Service for Prometheus", file: "/el10/managed-prometheus.webp", accent: "#7c3aed", summary: "Managed Prometheus metrics and alerting" },
  { name: "AWS OpsWorks (Legacy)", file: "/el10/aws-opsworks.webp", accent: "#ea580c", summary: "Chef/Puppet operations; legacy maintenance mode" },
  { name: "Amazon Q Developer in chat applications", file: "/el10/q-developer-chat.webp", accent: "#7c3aed", summary: "ChatOps notifications and controlled AWS actions" },
  { name: "AWS IAM", file: "/el10/iam.webp", accent: "#7c3aed", summary: "Users, roles, policies, and permission boundaries" },
  { name: "AWS IAM Identity Center", file: "/el10/iam-identity-center.webp", accent: "#2563eb", summary: "Central workforce access to accounts and applications" },
  { name: "Amazon Cognito", file: "/el10/cognito.webp", accent: "#7c3aed", summary: "Customer identity, sign-in, and federation" },
  { name: "AWS Directory Service", file: "/el10/directory-service.webp", accent: "#2563eb", summary: "Managed Microsoft AD and directory integration" },
  { name: "AWS KMS", file: "/el10/kms.webp", accent: "#16a34a", summary: "Create and control encryption keys" },
  { name: "AWS CloudHSM", file: "/el10/cloudhsm.webp", accent: "#7c3aed", summary: "Dedicated hardware security modules" },
  { name: "AWS Certificate Manager", file: "/el10/acm.webp", accent: "#2563eb", summary: "Provision and manage TLS certificates" },
  { name: "AWS Secrets Manager", file: "/el10/secrets-manager.webp", accent: "#16a34a", summary: "Store, rotate, and retrieve secrets securely" },
  { name: "Amazon GuardDuty", file: "/el10/guardduty.webp", accent: "#dc2626", summary: "Continuous threat detection" },
  { name: "Amazon Inspector", file: "/el10/inspector.webp", accent: "#ea580c", summary: "Workload vulnerability and exposure scanning" },
  { name: "Amazon Macie", file: "/el10/macie.webp", accent: "#7c3aed", summary: "Discover and protect sensitive S3 data" },
  { name: "AWS Security Hub", file: "/el10/security-hub.webp", accent: "#dc2626", summary: "Aggregate and prioritize security findings" },
  { name: "AWS WAF", file: "/el10/waf.webp", accent: "#dc2626", summary: "Protect web applications and APIs" },
  { name: "AWS Shield", file: "/el10/shield.webp", accent: "#dc2626", summary: "Automatic and advanced DDoS protection" },
  { name: "AWS Firewall Manager", file: "/el10/firewall-manager.webp", accent: "#7c3aed", summary: "Central security policy enforcement" },
  { name: "AWS Network Firewall", file: "/el10/network-firewall.webp", accent: "#dc2626", summary: "Stateful and stateless VPC inspection" },
  { name: "Amazon Detective", file: "/el10/detective.webp", accent: "#7c3aed", summary: "Investigate findings and behavior relationships" },
  { name: "Amazon EC2", file: "/el10/compute/ec2.webp", accent: "#ea580c", summary: "Secure, resizable virtual servers" },
  { name: "Amazon ECS", file: "/el10/compute/ecs.webp", accent: "#ea580c", summary: "Managed container orchestration" },
  { name: "Amazon EKS", file: "/el10/compute/eks.webp", accent: "#2563eb", summary: "Managed Kubernetes on AWS" },
  { name: "Amazon ECR", file: "/el10/compute/ecr.webp", accent: "#ea580c", summary: "Managed container image registry" },
  { name: "AWS Fargate", file: "/el10/compute/fargate.webp", accent: "#ea580c", summary: "Serverless compute for containers" },
  { name: "AWS Lambda", file: "/el10/compute/lambda.webp", accent: "#ea580c", summary: "Run code without managing servers" },
  { name: "AWS Elastic Beanstalk", file: "/el10/compute/elastic-beanstalk.webp", accent: "#16a34a", summary: "Deploy and scale web applications" },
  { name: "AWS Batch", file: "/el10/compute/batch.webp", accent: "#7c3aed", summary: "Fully managed batch processing" },
  { name: "AWS App Runner", file: "/el10/compute/app-runner.webp", accent: "#ea580c", summary: "Build and run containerized applications" },
  { name: "Amazon Lightsail", file: "/el10/compute/lightsail.webp", accent: "#7c3aed", summary: "Simple virtual servers and applications" },
  { name: "Amazon ECS Anywhere", file: "/el10/compute/ecs-anywhere.webp", accent: "#ea580c", summary: "Run ECS tasks on customer infrastructure" },
  { name: "Amazon EKS Anywhere", file: "/el10/compute/eks-anywhere.webp", accent: "#2563eb", summary: "Run Kubernetes on your infrastructure" },
  { name: "AWS Serverless Application Repository", file: "/el10/compute/serverless-repository.webp", accent: "#7c3aed", summary: "Discover and deploy serverless applications" },
  { name: "AWS Outposts", file: "/el10/compute/outposts.webp", accent: "#7c3aed", summary: "AWS infrastructure on premises" },
  { name: "AWS Wavelength", file: "/el10/compute/wavelength.webp", accent: "#2563eb", summary: "Ultra-low-latency 5G edge compute" },
  { name: "AWS Local Zones", file: "/el10/compute/local-zones.webp", accent: "#2563eb", summary: "Compute near end users" },
  { name: "VMware Cloud on AWS", file: "/el10/compute/vmware-cloud.webp", accent: "#16a34a", summary: "Run vSphere workloads on AWS" },
  { name: "Amazon S3", file: "/el10/storage/s3.webp", accent: "#16a34a", summary: "Scalable object storage and data lakes" },
  { name: "Amazon EBS", file: "/el10/storage/ebs.webp", accent: "#16a34a", summary: "Persistent block storage for EC2" },
  { name: "Amazon EFS", file: "/el10/storage/efs.webp", accent: "#16a34a", summary: "Serverless shared NFS file storage" },
  { name: "Amazon FSx", file: "/el10/storage/fsx.webp", accent: "#16a34a", summary: "Managed file-system family overview" },
  { name: "AWS Backup", file: "/el10/storage/aws-backup.webp", accent: "#16a34a", summary: "Centralized policy-based data protection" },
  { name: "Amazon File Cache", file: "/el10/storage/file-cache.webp", accent: "#7c3aed", summary: "High-speed cache for distributed datasets" },
  { name: "Amazon FSx for Lustre", file: "/el10/storage/fsx-lustre.webp", accent: "#7c3aed", summary: "High-performance Lustre file storage" },
  { name: "Amazon FSx for NetApp ONTAP", file: "/el10/storage/fsx-ontap.webp", accent: "#16a34a", summary: "Managed enterprise ONTAP storage" },
  { name: "Amazon FSx for OpenZFS", file: "/el10/storage/fsx-openzfs.webp", accent: "#16a34a", summary: "Managed OpenZFS file storage" },
  { name: "Amazon FSx for Windows File Server", file: "/el10/storage/fsx-windows.webp", accent: "#16a34a", summary: "Managed Windows SMB file shares" },
  { name: "Amazon S3 Glacier", file: "/el10/storage/s3-glacier.webp", accent: "#7c3aed", summary: "Low-cost long-term archival storage" },
  { name: "AWS Elastic Disaster Recovery", file: "/el10/storage/elastic-disaster-recovery.webp", accent: "#7c3aed", summary: "Continuous replication and rapid recovery" },
  { name: "AWS Storage Gateway", file: "/el10/storage/storage-gateway.webp", accent: "#7c3aed", summary: "Hybrid access to AWS cloud storage" },
  { name: "AWS DataSync", file: "/el10/storage/datasync.webp", accent: "#0f766e", summary: "Accelerated online data transfer" },
  { name: "AWS Snowball Edge", file: "/el10/storage/snowball-edge.webp", accent: "#2563eb", summary: "Offline transfer and edge computing" },
  { name: "AWS Transfer Family", file: "/el10/storage/transfer-family.webp", accent: "#0f766e", summary: "Managed SFTP, FTPS, FTP and AS2" },
  { name: "Amazon RDS", file: "/el10/database/rds.webp", accent: "#2563eb", summary: "Managed relational databases with six engines" },
  { name: "Amazon Aurora", file: "/el10/database/aurora.webp", accent: "#7c3aed", summary: "Cloud-native MySQL and PostgreSQL-compatible database" },
  { name: "Amazon Aurora DSQL", file: "/el10/database/aurora-dsql.webp", accent: "#7c3aed", summary: "Serverless distributed SQL for global applications" },
  { name: "Amazon DynamoDB", file: "/el10/database/dynamodb.webp", accent: "#2563eb", summary: "Serverless key-value and document database" },
  { name: "Amazon DocumentDB", file: "/el10/database/documentdb.webp", accent: "#16a34a", summary: "Managed JSON document database" },
  { name: "Amazon ElastiCache", file: "/el10/database/elasticache.webp", accent: "#dc2626", summary: "Serverless and managed in-memory caching" },
  { name: "Amazon MemoryDB", file: "/el10/database/amazon-memorydb.webp", accent: "#7c3aed", summary: "Durable in-memory database" },
  { name: "Amazon Keyspaces", file: "/el10/database/keyspaces.webp", accent: "#7c3aed", summary: "Serverless Apache Cassandra-compatible database" },
  { name: "Amazon Neptune", file: "/el10/database/neptune.webp", accent: "#7c3aed", summary: "Managed graph database" },
  { name: "Amazon Neptune Analytics", file: "/el10/database/neptune-analytics.webp", accent: "#16a34a", summary: "High-performance graph analytics" },
  { name: "Amazon Timestream", file: "/el10/database/amazon-timestream.webp", accent: "#7c3aed", summary: "Purpose-built time-series databases" },
  { name: "AWS Database Migration Service", file: "/el10/database/dms.webp", accent: "#2563eb", summary: "Assess, convert, migrate and replicate data" },
  { name: "AWS Transform", file: "/el10/migration/aws-transform.webp", accent: "#7c3aed", summary: "Agentic AI for migration and modernization" },
  { name: "AWS Transform MGN", file: "/el10/migration/transform-mgn.webp", accent: "#ea580c", summary: "Rehost applications to AWS" },
  { name: "AWS Migration Hub", file: "/el10/migration/migration-hub.webp", accent: "#16a34a", summary: "Plan, track and govern application migrations" },
  { name: "AWS Application Discovery Service", file: "/el10/migration/aws-application-discovery-service.webp", accent: "#16a34a", summary: "Discover workloads for migration planning" },
  { name: "Amazon API Gateway", file: "/el10/networking/api-gateway.webp", accent: "#8b5cf6", summary: "Create, secure, and operate APIs at scale" },
  { name: "Amazon CloudFront", file: "/el10/networking/cloudfront.webp", accent: "#8b5cf6", summary: "Global content delivery and edge acceleration" },
  { name: "AWS Cloud Map", file: "/el10/networking/cloud-map.webp", accent: "#8b5cf6", summary: "Dynamic service discovery for cloud resources" },
  { name: "AWS Direct Connect", file: "/el10/networking/direct-connect.webp", accent: "#8b5cf6", summary: "Dedicated private connectivity to AWS" },
  { name: "Elastic Load Balancing", file: "/el10/networking/elastic-load-balancing.webp", accent: "#8b5cf6", summary: "Distribute traffic across healthy targets" },
  { name: "AWS Global Accelerator", file: "/el10/networking/global-accelerator.webp", accent: "#8b5cf6", summary: "Improve global application availability and performance" },
  { name: "AWS PrivateLink", file: "/el10/networking/privatelink.webp", accent: "#8b5cf6", summary: "Private service connectivity over the AWS network" },
  { name: "Amazon Route 53", file: "/el10/networking/route-53.webp", accent: "#8b5cf6", summary: "Highly available DNS and traffic routing" },
  { name: "AWS Transit Gateway", file: "/el10/networking/transit-gateway.webp", accent: "#8b5cf6", summary: "Hub connectivity for VPCs and on-premises networks" },
  { name: "AWS Verified Access", file: "/el10/networking/verified-access.webp", accent: "#8b5cf6", summary: "Zero-trust access to private applications" },
  { name: "Amazon VPC", file: "/el10/networking/vpc.webp", accent: "#8b5cf6", summary: "Isolated virtual networks in AWS" },
  { name: "Amazon VPC Lattice", file: "/el10/networking/vpc-lattice.webp", accent: "#8b5cf6", summary: "Application networking across services and VPCs" },
  { name: "AWS Site-to-Site VPN", file: "/el10/networking/site-to-site-vpn.webp", accent: "#8b5cf6", summary: "Encrypted connectivity between networks and AWS" },
  { name: "AWS Cloud WAN", file: "/el10/networking/cloud-wan.webp", accent: "#8b5cf6", summary: "Build and manage global wide-area networks" },
  { name: "AWS Client VPN", file: "/el10/networking/client-vpn.webp", accent: "#8b5cf6", summary: "Managed remote access to AWS and on-premises" },
  { name: "AWS Network Manager", file: "/el10/networking/network-manager.webp", accent: "#8b5cf6", summary: "Central network topology, health, and operations" },
  { name: "Amazon VPC IPAM", file: "/el10/networking/vpc-ipam.webp", accent: "#8b5cf6", summary: "Plan, track, and govern IP address space" },
  { name: "AWS Data Transfer Terminal", file: "/el10/networking/data-transfer-terminal.webp", accent: "#8b5cf6", summary: "High-speed transfer at secure AWS facilities" },
  { name: "Integrated Private Wireless on AWS", file: "/el10/networking/integrated-private-wireless.webp", accent: "#8b5cf6", summary: "AWS-validated private wireless partner solutions" },
  { name: "AWS Private 5G", file: "/el10/networking/private-5g.webp", accent: "#8b5cf6", summary: "Managed private cellular networking" },
  { name: "AWS Infrastructure Composer", file: "/el10/developer-tools/infrastructure-composer.webp", accent: "#f97316", summary: "Visually compose serverless applications" },
  { name: "AWS CloudShell", file: "/el10/developer-tools/cloudshell.webp", accent: "#f97316", summary: "Browser-based authenticated shell for AWS" },
  { name: "AWS CodeArtifact", file: "/el10/developer-tools/codeartifact.webp", accent: "#f97316", summary: "Secure package repositories for development teams" },
  { name: "AWS CodeBuild", file: "/el10/developer-tools/codebuild.webp", accent: "#f97316", summary: "Managed continuous integration build service" },
  { name: "AWS CodeCommit", file: "/el10/developer-tools/codecommit.webp", accent: "#f97316", summary: "Private Git repositories with lifecycle constraints" },
  { name: "AWS CodeDeploy", file: "/el10/developer-tools/codedeploy.webp", accent: "#f97316", summary: "Automated application deployments" },
  { name: "AWS CodePipeline", file: "/el10/developer-tools/codepipeline.webp", accent: "#f97316", summary: "Continuous delivery workflow orchestration" },
  { name: "AWS CodeConnections", file: "/el10/developer-tools/codeconnections.webp", accent: "#f97316", summary: "Connect AWS developer services to source providers" },
  { name: "Amazon Corretto", file: "/el10/developer-tools/corretto.webp", accent: "#f97316", summary: "AWS-supported OpenJDK distribution" },
  { name: "AWS Fault Injection Service", file: "/el10/aws-fault-injection-service.webp", accent: "#f97316", summary: "Controlled resilience experiments on AWS workloads" },
  { name: "Amazon Q Developer", file: "/el10/developer-tools/q-developer.webp", accent: "#f97316", summary: "Generative AI assistant for software development" },
  { name: "AWS X-Ray", file: "/el10/developer-tools/x-ray.webp", accent: "#f97316", summary: "Distributed tracing and service-map analysis" },
  { name: "Amazon Athena", file: "/el10/analytics/athena.webp", accent: "#ec4899", summary: "Serverless SQL analytics for data in Amazon S3" },
  { name: "Amazon DataZone", file: "/el10/analytics/datazone.webp", accent: "#ec4899", summary: "Governed data discovery, sharing, and collaboration" },
  { name: "Amazon EMR", file: "/el10/analytics/emr.webp", accent: "#ec4899", summary: "Managed big-data processing with open-source frameworks" },
  { name: "Amazon FinSpace", file: "/el10/analytics/finspace.webp", accent: "#ec4899", summary: "Financial data management and analytics" },
  { name: "Amazon Kinesis", file: "/el10/analytics/kinesis.webp", accent: "#ec4899", summary: "Real-time streaming services overview" },
  { name: "Amazon Data Firehose", file: "/el10/analytics/data-firehose.webp", accent: "#ec4899", summary: "Deliver streaming data to analytics destinations" },
  { name: "Amazon Kinesis Data Streams", file: "/el10/analytics/kinesis-data-streams.webp", accent: "#ec4899", summary: "Durable real-time data stream ingestion" },
  { name: "Amazon Kinesis Video Streams", file: "/el10/analytics/kinesis-video-streams.webp", accent: "#ec4899", summary: "Secure video streaming from connected devices" },
  { name: "Amazon Managed Service for Apache Flink", file: "/el10/analytics/managed-flink.webp", accent: "#ec4899", summary: "Real-time stream processing with Apache Flink" },
  { name: "Amazon Managed Streaming for Apache Kafka", file: "/el10/analytics/msk.webp", accent: "#ec4899", summary: "Managed Apache Kafka clusters and serverless streaming" },
  { name: "Amazon OpenSearch Service", file: "/el10/analytics/opensearch-service.webp", accent: "#ec4899", summary: "Managed search, log analytics, and observability" },
  { name: "Amazon OpenSearch Serverless", file: "/el10/analytics/opensearch-serverless.webp", accent: "#ec4899", summary: "Serverless search and analytics collections" },
  { name: "Amazon Redshift", file: "/el10/analytics/redshift.webp", accent: "#ec4899", summary: "Cloud data warehousing at scale" },
  { name: "Amazon Redshift Serverless", file: "/el10/analytics/redshift-serverless.webp", accent: "#ec4899", summary: "Serverless data warehouse capacity" },
  { name: "AWS Clean Rooms", file: "/el10/analytics/clean-rooms.webp", accent: "#ec4899", summary: "Collaborate on data without exposing raw records" },
  { name: "AWS Data Exchange", file: "/el10/analytics/data-exchange.webp", accent: "#ec4899", summary: "Discover, subscribe to, and deliver third-party data" },
  { name: "AWS Entity Resolution", file: "/el10/analytics/entity-resolution.webp", accent: "#ec4899", summary: "Match and link related records across datasets" },
  { name: "AWS Glue", file: "/el10/analytics/glue.webp", accent: "#ec4899", summary: "Serverless data integration and cataloging" },
  { name: "AWS Lake Formation", file: "/el10/analytics/lake-formation.webp", accent: "#ec4899", summary: "Build and govern secure data lakes" },
  { name: "AWS IoT Core", file: "/el10/iot/iot-core.webp", accent: "#14b8a6", summary: "Securely connect devices and route messages at scale" },
  { name: "AWS IoT Device Defender", file: "/el10/iot/device-defender.webp", accent: "#14b8a6", summary: "Audit and monitor IoT fleet security" },
  { name: "AWS IoT Device Management", file: "/el10/iot/device-management.webp", accent: "#14b8a6", summary: "Onboard, organize, monitor, and operate device fleets" },
  { name: "AWS IoT ExpressLink", file: "/el10/iot/expresslink.webp", accent: "#14b8a6", summary: "Secure cloud connectivity modules for products" },
  { name: "AWS IoT FleetWise", file: "/el10/iot/fleetwise.webp", accent: "#14b8a6", summary: "Collect and transform vehicle data in near real time" },
  { name: "AWS IoT Greengrass", file: "/el10/iot/greengrass.webp", accent: "#14b8a6", summary: "Run and manage software at the edge" },
  { name: "AWS IoT SiteWise", file: "/el10/iot/sitewise.webp", accent: "#14b8a6", summary: "Collect and analyze industrial equipment data" },
  { name: "AWS IoT TwinMaker", file: "/el10/iot/twinmaker.webp", accent: "#14b8a6", summary: "Build operational digital twins" },
  { name: "AWS Partner Device Catalog", file: "/el10/iot/partner-device-catalog.webp", accent: "#14b8a6", summary: "Find qualified devices compatible with AWS IoT" },
  { name: "FreeRTOS", file: "/el10/iot/freertos.webp", accent: "#14b8a6", summary: "Real-time operating system for microcontrollers" },
  { name: "Amazon Quick", file: "/el10/analytics/amazon-quick.webp", accent: "#a855f7", summary: "Enterprise business intelligence and AI assistance" },
  { name: "Amazon Augmented AI", file: "/el10/ai/augmented-ai.webp", accent: "#a855f7", summary: "Human review workflows for machine-learning predictions" },
  { name: "Amazon Bedrock", file: "/el10/ai/bedrock.webp", accent: "#a855f7", summary: "Build generative AI applications with foundation models" },
  { name: "Amazon Nova", file: "/el10/ai/nova.webp", accent: "#a855f7", summary: "AWS foundation models for multimodal generative AI" },
  { name: "Amazon Comprehend", file: "/el10/ai/comprehend.webp", accent: "#a855f7", summary: "Natural-language processing and text insights" },
  { name: "Amazon Comprehend Medical", file: "/el10/ai/comprehend-medical.webp", accent: "#a855f7", summary: "Extract structured insights from medical text" },
  { name: "Amazon Kendra", file: "/el10/ai/kendra.webp", accent: "#a855f7", summary: "Intelligent enterprise search powered by machine learning" },
  { name: "Amazon Lex", file: "/el10/ai/lex.webp", accent: "#a855f7", summary: "Conversational interfaces using voice and text" },
  { name: "Amazon PartyRock", file: "/el10/ai/partyrock.webp", accent: "#a855f7", summary: "Hands-on generative AI application playground" },
  { name: "Amazon Personalize", file: "/el10/ai/personalize.webp", accent: "#a855f7", summary: "Real-time personalized recommendations" },
  { name: "Amazon Polly", file: "/el10/ai/polly.webp", accent: "#a855f7", summary: "Natural-sounding text-to-speech" },
  { name: "Amazon Q Business", file: "/el10/ai/q-business.webp", accent: "#a855f7", summary: "Generative AI assistant for enterprise knowledge" },
  { name: "Amazon Rekognition", file: "/el10/ai/rekognition.webp", accent: "#a855f7", summary: "Image and video analysis with machine learning" },
  { name: "Amazon SageMaker AI", file: "/el10/ai/sagemaker-ai.webp", accent: "#a855f7", summary: "Build, train, and deploy machine-learning models" },
  { name: "Amazon Textract", file: "/el10/ai/textract.webp", accent: "#a855f7", summary: "Extract text, handwriting, tables, and forms" },
  { name: "Amazon Transcribe", file: "/el10/ai/transcribe.webp", accent: "#a855f7", summary: "Automatic speech recognition and transcription" },
  { name: "Amazon Translate", file: "/el10/ai/translate.webp", accent: "#a855f7", summary: "Neural machine translation" },
  { name: "AWS HealthLake", file: "/el10/ai/healthlake.webp", accent: "#a855f7", summary: "Store and analyze health data using FHIR" },
  { name: "AWS HealthScribe", file: "/el10/ai/healthscribe.webp", accent: "#a855f7", summary: "Generate clinical documentation from conversations" },
  { name: "Kiro", file: "/el10/ai/kiro.webp", accent: "#a855f7", summary: "Agentic IDE for spec-driven software development" },
  { name: "AWS AppSync", file: "/el10/appint-media/appsync.webp", accent: "#ec4899", summary: "Managed GraphQL and real-time APIs" },
  { name: "Amazon SNS", file: "/el10/appint-media/sns.webp", accent: "#ec4899", summary: "Pub/sub messaging and application notifications" },
  { name: "Amazon SQS", file: "/el10/appint-media/sqs.webp", accent: "#ec4899", summary: "Durable managed message queues" },
  { name: "Amazon MQ", file: "/el10/appint-media/mq.webp", accent: "#ec4899", summary: "Managed ActiveMQ and RabbitMQ brokers" },
  { name: "Amazon AppFlow", file: "/el10/appint-media/appflow.webp", accent: "#ec4899", summary: "Secure SaaS and AWS data flows" },
  { name: "AWS Step Functions", file: "/el10/appint-media/step-functions.webp", accent: "#ec4899", summary: "Visual workflow orchestration for distributed applications" },
  { name: "Amazon MWAA", file: "/el10/appint-media/mwaa.webp", accent: "#ec4899", summary: "Managed Apache Airflow workflow orchestration" },
  { name: "AWS B2B Data Interchange", file: "/el10/appint-media/b2b-data-interchange.webp", accent: "#ec4899", summary: "Automate business-to-business EDI workflows" },
  { name: "AWS Deadline Cloud", file: "/el10/appint-media/deadline-cloud.webp", accent: "#8b5cf6", summary: "Managed cloud render farms" },
  { name: "AWS Elemental MediaConnect", file: "/el10/appint-media/mediaconnect.webp", accent: "#8b5cf6", summary: "Reliable live video transport" },
  { name: "AWS Elemental MediaConvert", file: "/el10/appint-media/mediaconvert.webp", accent: "#8b5cf6", summary: "File-based video transcoding" },
  { name: "AWS Elemental MediaLive", file: "/el10/appint-media/medialive.webp", accent: "#8b5cf6", summary: "Broadcast-grade live video encoding" },
  { name: "AWS Elemental MediaPackage", file: "/el10/appint-media/mediapackage.webp", accent: "#8b5cf6", summary: "Package and protect live and on-demand video" },
  { name: "AWS Elemental MediaTailor", file: "/el10/appint-media/mediatailor.webp", accent: "#8b5cf6", summary: "Personalized ads and channel assembly" },
  { name: "Amazon Interactive Video Service", file: "/el10/appint-media/ivs.webp", accent: "#8b5cf6", summary: "Managed low-latency live streaming" },
  { name: "AWS AppFabric", file: "/el10/other-services/appfabric.webp", accent: "#14b8a6", summary: "Connect SaaS applications for security insights" },
  { name: "Amazon Chime SDK", file: "/el10/other-services/chime-sdk.webp", accent: "#14b8a6", summary: "Embed real-time voice, video, and messaging" },
  { name: "Amazon Connect Customer", file: "/el10/other-services/connect-customer.webp", accent: "#14b8a6", summary: "Customer engagement capabilities for Amazon Connect" },
  { name: "Amazon SES", file: "/el10/appint-media/amazon-ses.webp", accent: "#14b8a6", summary: "Scalable transactional and marketing email" },
  { name: "Amazon WorkMail", file: "/el10/other-services/workmail.webp", accent: "#14b8a6", summary: "Secure managed business email and calendars" },
  { name: "AWS Managed Services", file: "/el10/other-services/aws-managed-services.webp", accent: "#06b6d4", summary: "Operate AWS environments with managed controls" },
  { name: "AWS re:Post Private", file: "/el10/other-services/aws-repost-private.webp", accent: "#06b6d4", summary: "Private cloud knowledge and collaboration" },
  { name: "Amazon WorkSpaces Applications", file: "/el10/other-services/workspaces-applications.webp", accent: "#2563eb", summary: "Stream applications securely to users" },
  { name: "Amazon WorkSpaces", file: "/el10/other-services/amazon-workspaces.webp", accent: "#2563eb", summary: "Managed cloud desktops" },
  { name: "Amazon WorkSpaces Core", file: "/el10/other-services/workspaces-core.webp", accent: "#2563eb", summary: "Cloud desktop infrastructure for VDI solutions" },
  { name: "Amazon WorkSpaces Thin Client", file: "/el10/other-services/workspaces-thin-client.webp", accent: "#2563eb", summary: "Managed endpoint devices for virtual desktops" },
  { name: "Amazon WorkSpaces Secure Browser", file: "/el10/compute/amazon-workspaces-secure-browser.webp", accent: "#2563eb", summary: "Secure browser access to internal websites" },
  { name: "AWS Amplify", file: "/el10/other-services/aws-amplify.webp", accent: "#f43f5e", summary: "Build and deploy full-stack web and mobile applications" },
  { name: "AWS Device Farm", file: "/el10/other-services/aws-device-farm.webp", accent: "#f43f5e", summary: "Test applications on real devices and browsers" },
  { name: "Amazon Location Service", file: "/el10/other-services/amazon-location-service.webp", accent: "#f43f5e", summary: "Maps, places, routes, trackers, and geofences" },
  { name: "Amazon Managed Blockchain", file: "/el10/other-services/amazon-managed-blockchain.webp", accent: "#7c3aed", summary: "Managed blockchain networks and query access" },
  { name: "Amazon GameLift Servers", file: "/el10/other-services/amazon-gamelift-servers.webp", accent: "#7c3aed", summary: "Managed multiplayer game server hosting" },
  { name: "Amazon Braket", file: "/el10/other-services/amazon-braket.webp", accent: "#7c3aed", summary: "Explore quantum computing with simulators and QPUs" },
  { name: "AWS Ground Station", file: "/el10/other-services/aws-ground-station.webp", accent: "#2563eb", summary: "Managed satellite communications and data delivery" },
  { name: "AWS Billing Conductor", file: "/el10/backlog/billing-conductor.webp", accent: "#16a34a", summary: "Custom pricing and pro forma billing groups" },
  { name: "AWS Cost and Usage Reports", file: "/el10/Cloud Financial Management/aws-cost-and-usage-reports.webp", accent: "#16a34a", summary: "Detailed cost and usage data delivered to Amazon S3" },
  { name: "Amazon EC2 Image Builder", file: "/el10/compute/amazon-ec2-image-builder.webp", accent: "#f59e0b", summary: "Automate secure VM and container image pipelines" },
  { name: "AWS Parallel Computing Service", file: "/el10/backlog/parallel-computing-service.webp", accent: "#f59e0b", summary: "Managed Slurm clusters for HPC workloads" },
  { name: "Amazon Verified Permissions", file: "/el10/backlog/verified-permissions.webp", accent: "#60a5fa", summary: "Fine-grained application authorization with Cedar" },
  { name: "Amazon Security Lake", file: "/el10/backlog/security-lake.webp", accent: "#60a5fa", summary: "Centralize security data using OCSF" },
  { name: "AWS Payment Cryptography", file: "/el10/backlog/payment-cryptography.webp", accent: "#60a5fa", summary: "HSM-backed cryptography for payment workloads" },
  { name: "AWS Private CA", file: "/el10/backlog/private-ca.webp", accent: "#60a5fa", summary: "Create and operate private certificate authorities" },
  { name: "AWS Signer", file: "/el10/backlog/signer.webp", accent: "#60a5fa", summary: "Managed code signing for software artifacts" },
  { name: "IAM Access Analyzer", file: "/el10/backlog/iam-access-analyzer.webp", accent: "#60a5fa", summary: "Find unintended and unused access" },
  { name: "Amazon Simple Workflow Service", file: "/el10/backlog/swf.webp", accent: "#ec4899", summary: "Coordinate durable, long-running application workflows" },
  { name: "AWS App Studio", file: "/el10/backlog/app-studio.webp", accent: "#14b8a6", summary: "Build business applications with generative AI" },
  { name: "AWS Supply Chain", file: "/el10/backlog/supply-chain.webp", accent: "#14b8a6", summary: "Unify supply-chain data, planning and insights" },
  { name: "AWS Wickr", file: "/el10/backlog/wickr.webp", accent: "#14b8a6", summary: "End-to-end encrypted enterprise collaboration" },
  { name: "Amazon Bedrock AgentCore", file: "/el10/ai/bedrock-agentcore.webp", accent: "#a855f7", summary: "Build, deploy, and operate production AI agents" },
  { name: "Amazon Bedrock Knowledge Bases", file: "/el10/ai/bedrock-knowledge-bases.webp", accent: "#a855f7", summary: "Ground generative AI responses in enterprise data" },
  { name: "Amazon Bedrock Prompt Management", file: "/el10/ai/bedrock-prompt-management.webp", accent: "#a855f7", summary: "Create, test, version, and reuse prompts" },
  { name: "Amazon Bedrock Prompt Flows", file: "/el10/ai/bedrock-prompt-flows.webp", accent: "#a855f7", summary: "Visually orchestrate multi-step generative AI workflows" },
  { name: "Amazon SageMaker Clarify", file: "/el10/ai/sagemaker-clarify.webp", accent: "#a855f7", summary: "Detect bias and explain machine-learning predictions" },
  { name: "Amazon SageMaker Data Wrangler", file: "/el10/ai/sagemaker-data-wrangler.webp", accent: "#a855f7", summary: "Prepare and transform data for machine learning" },
  { name: "Amazon SageMaker Ground Truth", file: "/el10/ai/sagemaker-ground-truth.webp", accent: "#a855f7", summary: "Create high-quality labeled datasets" },
  { name: "Amazon SageMaker JumpStart", file: "/el10/ai/sagemaker-jumpstart.webp", accent: "#a855f7", summary: "Discover and deploy foundation and machine-learning models" },
  { name: "Amazon SageMaker Model Monitor", file: "/el10/ai/sagemaker-model-monitor.webp", accent: "#a855f7", summary: "Monitor model quality, bias, and data drift" },
  { name: "Amazon SageMaker Model Registry", file: "/el10/ai/sagemaker-model-registry.webp", accent: "#a855f7", summary: "Catalog, version, and govern machine-learning models" },
  { name: "Amazon SageMaker Neo", file: "/el10/ai/sagemaker-neo.webp", accent: "#a855f7", summary: "Optimize models to run efficiently on edge devices" },
  { name: "Amazon SageMaker Processing", file: "/el10/ai/sagemaker-processing.webp", accent: "#a855f7", summary: "Run data processing and evaluation jobs at scale" },
  { name: "Amazon SageMaker Unified Studio", file: "/el10/ai/sagemaker-unified-studio.webp", accent: "#a855f7", summary: "Unified environment for analytics and AI development" },
  { name: "Amazon Titan", file: "/el10/ai/titan.webp", accent: "#a855f7", summary: "Amazon foundation models for generative AI applications" },
  { name: "AWS CDK", file: "/el10/aws-cdk.webp", accent: "#f97316", summary: "Define AWS infrastructure using familiar programming languages" },
  { name: "AWS Cost Anomaly Detection", file: "/el10/Cloud Financial Management/aws-cost-anomaly-detection.webp", accent: "#16a34a", summary: "Detect unusual AWS spending with machine learning" },
  { name: "AWS Tools and SDKs", file: "/el10/aws-tools-sdk.webp", accent: "#f97316", summary: "Build and automate AWS workloads through tools and language SDKs" },
  { name: "AWS Security Token Service", file: "/el10/aws-sts.webp", accent: "#dc2626", summary: "Issue temporary credentials for secure AWS access" },
  { name: "AWS Schema Conversion Tool", file: "/el10/aws-schema-conversion-tool.webp", accent: "#14b8a6", summary: "Assess and convert database schemas and code for migration" },
  { name: "AWS Management Console", file: "/el10/aws-management-console.webp", accent: "#2563eb", summary: "Web interface for accessing and managing AWS services" },
  { name: "AWS CLI", file: "/el10/aws-cli.webp", accent: "#f97316", summary: "Unified command-line interface for AWS services" },
  { name: "AWS AppConfig", file: "/el10/appconfig.webp", accent: "#db2777", summary: "Safely deploy feature flags and dynamic application configuration" },
  { name: "Savings Plans", file: "/el10/savings-plans.webp", accent: "#16a34a", summary: "Commitment-based pricing for lower eligible AWS usage costs" },
  { name: "Amazon Elastic Transcoder", file: "/el10/amazon-elastic-transcoder.webp", accent: "#8b5cf6", summary: "Legacy cloud media transcoding service; migrate to MediaConvert" },
  { name: "Amazon Pinpoint", file: "/el10/amazon-pinpoint.webp", accent: "#ec4899", summary: "Customer engagement campaigns, journeys, and messaging analytics" },
  { name: "AWS IoT Things Graph", file: "/el10/aws-iot-things-graph.webp", accent: "#14b8a6", summary: "Discontinued visual IoT workflow orchestration service" },
  { name: "AWS IoT 1-Click", file: "/el10/aws-iot-1-click.webp", accent: "#14b8a6", summary: "Legacy button-triggered IoT actions service" },
  { name: "AWS Proton", file: "/el10/aws-proton.webp", accent: "#f97316", summary: "Managed platform engineering and self-service deployments" },
  { name: "Amazon CodeGuru", file: "/el10/developer-tools/codeguru.webp", accent: "#f97316", summary: "Automated code reviews and application performance profiling" },
  { name: "AWS IoT Events", file: "/el10/IoT/iot-events.webp", accent: "#14b8a6", summary: "Detect and respond to IoT equipment and operational events" },
  { name: "Amazon Fraud Detector", file: "/el10/ai/fraud-detector.webp", accent: "#a855f7", summary: "Legacy machine-learning fraud detection service" },
  { name: "Amazon RDS Proxy", file: "/el10/database/amazon-rds-proxy.webp", accent: "#2563eb", summary: "Managed connection pooling for RDS and Aurora" },
  { name: "Amazon DynamoDB Streams", file: "/el10/database/amazon-dynamodb-streams.webp", accent: "#2563eb", summary: "Ordered item-level change records for DynamoDB" },
  { name: "Amazon DynamoDB Accelerator (DAX)", file: "/el10/database/amazon-dynamodb-accelerator.webp", accent: "#2563eb", summary: "In-memory acceleration for DynamoDB reads" },
  { name: "AWS DevOps Agent", file: "/el10/developer-tools/aws-devops-agent.webp", accent: "#f97316", summary: "AI-assisted issue-to-change software delivery workflow" },
  { name: "AWS CodeStar (Legacy)", file: "/el10/developer-tools/aws-codestar.webp", accent: "#f97316", summary: "Legacy unified development project service" },
  { name: "AWS Application Migration Service", file: "/el10/migration/aws-application-migration-service.webp", accent: "#14b8a6", summary: "Automated lift-and-shift server migration to AWS" },
  { name: "AWS Snow Family", file: "/el10/migration/aws-snow-family.webp", accent: "#14b8a6", summary: "Physical devices for offline data transfer and edge computing" },
  { name: "AWS Glue DataBrew", file: "/el10/analytics/aws-glue-databrew.webp", accent: "#ec4899", summary: "Visual no-code data preparation" },
  { name: "Amazon Q", file: "/el10/ai/amazon-q.webp", accent: "#a855f7", summary: "Generative AI assistance for work and development" },
  { name: "Amazon Aurora Serverless", file: "/el10/database/amazon-aurora-serverless.webp", accent: "#8b5cf6", summary: "On-demand autoscaling Aurora database capacity" },
  { name: "Amazon AppStream 2.0", file: "/el10/compute/amazon-appstream-2.webp", accent: "#f59e0b", summary: "Stream desktop applications securely to browsers" },
  { name: "Amazon Q Developer in chat applications", file: "/el10/aws-chatbot.webp", accent: "#ec4899", summary: "AWS notifications and CLI actions in chat applications" },
  { name: "Amazon Application Recovery Controller", file: "/el10/networking/amazon-application-recovery-controller.webp", accent: "#8b5cf6", summary: "Controlled recovery and traffic shifting for resilient applications" },
  { name: "AWS Copilot", file: "/el10/developer-tools/aws-copilot.webp", accent: "#f97316", summary: "Deploy and operate containerized applications on AWS" },
  { name: "AWS App2Container", file: "/el10/developer-tools/aws-app2container.webp", accent: "#f97316", summary: "Containerize and migrate existing applications" },
  { name: "Amazon Managed Workflows for Apache Airflow", file: "/el10/analytics/amazon-mwaa.webp", accent: "#ec4899", summary: "Managed Apache Airflow orchestration" },
  { name: "AWS Marketplace", file: "/el10/aws-marketplace.webp", accent: "#2563eb", summary: "Discover, procure, and govern third-party cloud products" },
  { name: "AWS Support", file: "/el10/aws-support.webp", accent: "#2563eb", summary: "Technical support plans and AWS operational guidance" },
  { name: "AWS Health", file: "/el10/aws-health.webp", accent: "#2563eb", summary: "Personalized AWS service health and account events" },
  { name: "AWS Resilience Hub", file: "/el10/aws-resilience-hub.webp", accent: "#2563eb", summary: "Assess and improve application resiliency" },
  { name: "Migration Evaluator", file: "/el10/migration/migration-evaluator.webp", accent: "#2563eb", summary: "Migration readiness and modernization assessment" },
  { name: "Strands Agents", file: "/el10/developer-tools/strands-agents.webp", accent: "#14b8a6", summary: "Build AI agents with an open-source agent SDK" },
  { name: "Amazon Aurora Serverless v2", file: "/el10/database/amazon-aurora-serverless-v2.webp", accent: "#8b5cf6", summary: "On-demand, autoscaling relational database capacity" },
  { name: "Service Control Policies", file: "/el10/aws-service-control-policies.webp", accent: "#f59e0b", summary: "Organization-wide permission guardrails" },
  { name: "Amazon VPC IP Address Manager (IPAM)", file: "/el10/networking/amazon-vpc-ipam.webp", accent: "#8b5cf6", summary: "Plan, track, and govern VPC IP addresses" },
  { name: "Elastic IP Addresses", file: "/el10/networking/elastic-ip-addresses.webp", accent: "#22c55e", summary: "Static public IPv4 addresses for AWS resources" },
  { name: "Route 53 Resolver DNS Firewall", file: "/el10/networking/route53-resolver-dns-firewall.webp", accent: "#7c3aed", summary: "Filter and control outbound DNS queries" },
  { name: "VPC Endpoints", file: "/el10/networking/vpc-endpoints.webp", accent: "#2563eb", summary: "Private connectivity to AWS services and endpoints" },
  { name: "VPC Flow Logs", file: "/el10/networking/vpc-flow-logs.webp", accent: "#14b8a6", summary: "Capture metadata about VPC network traffic" },
  { name: "AWS Security Agent", file: "/el10/aws-security-agent.webp", accent: "#dc2626", summary: "AI-assisted security investigation and response" },
  { name: "Amazon S3 Tables", file: "/el10/storage/amazon-s3-tables.webp", accent: "#16a34a", summary: "Managed tabular data storage in Amazon S3" },
  { name: "AWS Glue Data Quality", file: "/el10/analytics/aws-glue-data-quality.webp", accent: "#ec4899", summary: "Automated data quality rules and monitoring" },
  { name: "Amazon DevOps Guru", file: "/el10/ai/amazon-devops-guru.webp", accent: "#a855f7", summary: "ML-powered operational anomaly detection" },
  { name: "Amazon Lookout for Equipment", file: "/el10/ai/amazon-lookout-for-equipment.webp", accent: "#a855f7", summary: "Predict equipment failures from sensor data" },
  { name: "Amazon Lookout for Metrics", file: "/el10/ai/amazon-lookout-for-metrics.webp", accent: "#a855f7", summary: "Detect anomalies in business metrics" },
  { name: "Amazon Lookout for Vision", file: "/el10/ai/amazon-lookout-for-vision.webp", accent: "#a855f7", summary: "Visual inspection with computer vision" },
  { name: "Amazon Mechanical Turk", file: "/el10/ai/amazon-mechanical-turk.webp", accent: "#a855f7", summary: "Human intelligence tasks at scale (legacy)" },
  { name: "Red Hat OpenShift Service on AWS (ROSA)", file: "/el10/compute/rosa.webp", accent: "#dc2626", summary: "Managed Red Hat OpenShift on AWS" },
  { name: "AWS SAM", file: "/el10/developer-tools/aws-sam.webp", accent: "#f97316", summary: "Framework for building serverless applications" },
  { name: "Amazon Data Lifecycle Manager", file: "/el10/storage/amazon-data-lifecycle-manager.webp", accent: "#22c55e", summary: "Automated EBS snapshot and AMI lifecycle policies" },
  { name: "Amazon CodeGuru Security", file: "/el10/ai/amazon-codeguru-security.webp", accent: "#a855f7", summary: "Static application security and secrets scanning" },
  { name: "Amazon MemoryDB for Redis", file: "/el10/database/amazon-memorydb-for-redis.webp", accent: "#8b5cf6", summary: "Durable Redis-compatible in-memory database" },
  { name: "AWS Network Access Analyzer", file: "/el10/networking/aws-network-access-analyzer.webp", accent: "#8b5cf6", summary: "Analyze unintended network access paths" },
  { name: "NAT gateways", file: "/el10/networking/nat-gateways.webp", accent: "#8b5cf6", summary: "Managed outbound IPv4 connectivity for private subnets" },
  { name: "Internet gateways", file: "/el10/networking/aws-internet-gateway.webp", accent: "#8b5cf6", summary: "VPC connectivity to the public internet" },
  { name: "Egress-only internet gateways", file: "/el10/networking/egress-only-internet-gateway.webp", accent: "#8b5cf6", summary: "Outbound-only IPv6 internet access" },
  { name: "Automated Forensics Orchestrator for Amazon EC2", file: "/el10/automated-forensics-orchestrator-ec2.webp", accent: "#dc2626", summary: "Automated EC2 incident evidence collection and response" },
  { name: "Amazon EC2 security groups", file: "/el10/networking/ec2-security-groups.webp", accent: "#8b5cf6", summary: "Stateful virtual firewalls for network interfaces" },
  { name: "AWS App Mesh", file: "/el10/appint-media/aws-app-mesh.webp", accent: "#ec4899", summary: "Service mesh for microservice traffic management" },
  { name: "AWS CloudFormation Guard", file: "/el10/developer-tools/aws-cloudformation-guard.webp", accent: "#f97316", summary: "Policy-as-code validation for CloudFormation templates" },
  { name: "Amazon CloudWatch Synthetics", file: "/el10/amazon-cloudwatch-synthetics.webp", accent: "#f05aa6", summary: "Proactive API and browser journey monitoring" },
  { name: "Amazon Q Business Apps", file: "/el10/ai/amazon-q-business-apps.webp", accent: "#a855f7", summary: "Build secure generative AI applications from enterprise data" },
  { name: "AWS CloudTrail Lake", file: "/el10/aws-cloudtrail-lake.webp", accent: "#f05aa6", summary: "Store, query, and analyze AWS activity" },
  { name: "Network ACLs", file: "/el10/networking/network-acls.webp", accent: "#8b5cf6", summary: "Stateless subnet-level traffic controls" },
  { name: "VPC Reachability Analyzer", file: "/el10/networking/vpc-reachability-analyzer.webp", accent: "#8b5cf6", summary: "Analyze network paths and connectivity" },
  { name: "Amazon EKS Distro", file: "/el10/compute/amazon-eks-distro.webp", accent: "#f59e0b", summary: "AWS-supported upstream Kubernetes distribution" },
  { name: "AWS Lambda@Edge", file: "/el10/appint-media/aws-lambda-at-edge.webp", accent: "#ec4899", summary: "Run Lambda functions at CloudFront edge locations" },
  { name: "VPC peering", file: "/el10/networking/vpc-peering.webp", accent: "#8b5cf6", summary: "Private point-to-point connectivity between VPCs" },
  { name: "AWS Private Certificate Authority", file: "/el10/aws-private-certificate-authority.webp", accent: "#60a5fa", summary: "Managed private PKI and certificate issuance" },
  { name: "AWS Shield Advanced", file: "/el10/aws-shield-advanced.webp", accent: "#60a5fa", summary: "Advanced managed DDoS protection" },
  { name: "Amazon Quick Sight", file: "/el10/ai/amazon-quick-sight.webp", accent: "#a855f7", summary: "Cloud business intelligence and data visualization" },
  { name: "Amazon EC2 Auto Scaling", file: "/el10/compute/amazon-ec2-auto-scaling.webp", accent: "#f59e0b", summary: "Automatically maintain EC2 capacity for application demand" },
];

const branches = [
  { title: "Management & Governance", start: 0, end: 34, accent: "#f05aa6", copies: [215, 216, 248, 250, 256, 266, 271, 272, 273, 274, 217, 283, 310, 312] },
  { title: "Cloud Financial Management", start: 0, end: 0, accent: "#16a34a", copies: [23, 24, 25, 9, 13, 215, 216, 244, 251] },
  { title: "Security, Identity & Compliance", start: 34, end: 51, accent: "#60a5fa", copies: [2, 3, 15, 22, 219, 220, 221, 222, 223, 224, 246, 289, 306, 318, 319] },
  { title: "Compute & Containers", start: 51, end: 68, accent: "#f59e0b", copies: [217, 218, 264, 265, 207, 297, 315, 321] },
  { title: "Storage", start: 68, end: 84, accent: "#22c55e", copies: [290, 299, 72] as number[] },
  { title: "Databases", start: 84, end: 96, accent: "#8b5cf6", copies: [260, 261, 262, 282, 301] },
  { title: "Migration & Transfer", start: 96, end: 100, accent: "#14b8a6", copies: [95, 81, 83, 82, 247, 99, 280] },
  { title: "Networking & Content Delivery", start: 100, end: 120, accent: "#8b5cf6", copies: [49, 267, 284, 285, 286, 287, 288, 302, 303, 304, 305, 307, 313, 314, 317] },
  { title: "Developer Tools", start: 120, end: 132, accent: "#f97316", copies: [180, 243, 245, 249, 257, 268, 263, 264, 281, 298, 309, 129] },
  { title: "Analytics", start: 132, end: 151, accent: "#ec4899", copies: [270, 291, 320] },
  { title: "Internet of Things", start: 151, end: 161, accent: "#14b8a6", copies: [254, 255, 258] },
  { title: "Machine Learning & AI", start: 161, end: 181, accent: "#a855f7", copies: [33, 130, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 259, 292, 293, 294, 295, 296, 300, 311, 161] },
  { title: "Application Integration & Media", start: 181, end: 196, accent: "#ec4899", copies: [100, 10, 225, 252, 253, 199, 308, 316] },
  { title: "Other Services", start: 196, end: 215, accent: "#14b8a6", copies: [181, 226, 227, 228] },
];


const normalize = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const catalog = branches.map((branch) => ({ ...branch, items: [...new Set([...Array.from({ length: branch.end - branch.start }, (_, i) => branch.start + i), ...branch.copies])].map((index) => ({ ...services[index], index })).filter((item) => item.name) }));
export default function ServicesLibrary() {
  const params = useSearchParams();
  const [selected, setSelected] = useState(0);
  const [branchIndex, setBranchIndex] = useState(0);
  const [query, setQuery] = useState("");
  const [openBranch, setOpenBranch] = useState<{ index: number; top: number } | null>(null);
  const [menuCollapsed, setMenuCollapsed] = useState(false);
  const [visualVisible, setVisualVisible] = useState(true);
  const [expanded, setExpanded] = useState(false);
  const service = services[selected];
  const results = useMemo(() => catalog.flatMap((branch, index) => branch.items.map((item) => ({ item, branch: branch.title, index }))).filter(({item,branch}) => query.trim() && `${item.name} ${item.summary} ${branch}`.toLowerCase().includes(query.toLowerCase())).slice(0, 16), [query]);
  useEffect(() => {
    const requested = params.get("service");
    if (!requested) return;
    const index = services.findIndex((item) => normalize(item.name) === normalize(requested));
    if (index >= 0) { setSelected(index); const owner = catalog.findIndex((branch) => branch.items.some((item) => item.index === index)); if (owner >= 0) setBranchIndex(owner); }
  }, [params]);
  useEffect(() => { const key = (event: KeyboardEvent) => { if (event.key === "Escape") setExpanded(false); }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); }, []);
  const choose = (index: number, branch: number) => { setSelected(index); setBranchIndex(branch); setQuery(""); setOpenBranch(null); setExpanded(false); setVisualVisible(true); };
  return <main className="workspace azure-workspace aws-services-library">
    <nav className="top-nav" aria-label="Primary navigation"><a className="brand-link" href="/">Visual Learning</a><div><a className="home-button" href="/">Home</a><a className="active" href="/services">AWS services</a><a href="/azure-services">Azure services</a></div></nav>
    <div className={"azure-shell" + (menuCollapsed ? " rail-collapsed" : "")}>
      <aside className={"azure-branch-rail" + (menuCollapsed ? " collapsed" : "")} aria-label="AWS service branches">
        <div className="azure-menu-heading"><span>AWS branches</span><button type="button" aria-label={menuCollapsed ? "Expand branch menu" : "Collapse branch menu"} onClick={() => setMenuCollapsed((value) => !value)}>{menuCollapsed ? "›" : "‹"}</button></div>
        {!menuCollapsed && <><div className="azure-branch-list">{catalog.map((branch, index) => <div className="azure-branch-menu-item" key={branch.title} onMouseEnter={(event) => { const maxHeight = Math.min(window.innerHeight * .76, 680); const top = event.currentTarget.getBoundingClientRect().top; setOpenBranch({ index, top: Math.max(12, Math.min(top, window.innerHeight - maxHeight - 12)) }); }}><button className="azure-branch-trigger" type="button" aria-haspopup="true" onClick={() => branch.items[0] && choose(branch.items[0].index, index)}><span>{branch.title}</span><small>{branch.items.length}</small></button></div>)}</div>
        {openBranch && <div className="azure-branch-popover" role="menu" style={{ top: openBranch.top }} onMouseLeave={() => setOpenBranch(null)}><div className="azure-dropdown-title">{catalog[openBranch.index].title}</div>{catalog[openBranch.index].items.map((item) => <button key={item.index} type="button" role="menuitem" onClick={() => choose(item.index, openBranch.index)}><span>{item.name}</span><small>{item.summary}</small></button>)}</div>}</>}
      </aside>
      <section className="azure-main-pane"><header className="azure-toolbar"><div className="service-search azure-search"><span>Search all AWS services</span><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search service or branch…" aria-label="Search AWS services and branches" />{results.length > 0 && <div className="search-results" role="listbox" aria-label="AWS search results">{results.map(({item,branch,index}) => <button type="button" key={`${branch}-${item.index}`} role="option" onClick={() => choose(item.index,index)}><span>{item.name}</span><small>{branch} · {item.summary}</small></button>)}</div>}</div><div className="progress"><strong>{new Set(services.map((item) => normalize(item.name))).size}</strong><span>unique services mapped</span></div></header>
        <article className="viewer azure-viewer" style={{ "--service-accent": service.accent } as React.CSSProperties}><div className="viewer-head"><div><p>Selected AWS service</p><h2>{service.name}</h2><small className="azure-branch-context">{catalog[branchIndex].title}</small></div><div className="azure-viewer-actions"><button type="button" className="visual-toggle" onClick={() => setVisualVisible((value) => !value)}>{visualVisible ? "Hide visual ↑" : "Show visual ↓"}</button></div></div>
          <section className="azure-el10-section" aria-label={`${service.name} EL10 visual`}><div className="azure-el10-heading"><div><p>EL10 SERVICE VISUAL</p><span>Click the visual to open a full-screen study view.</span></div></div>{visualVisible && <button className="image-link" type="button" onClick={() => setExpanded(true)} aria-label={`Open ${service.name} EL10 full view`}><img src={assetUrl(service.file)} onError={(event) => { event.currentTarget.onerror = null; event.currentTarget.src = service.file; }} alt={`${service.name} EL10 infographic`} /></button>}</section>
          <p className="viewer-note">Choose a branch or search globally to explore a service.</p><SharedServiceWalkthrough key={service.name} serviceName={service.name}/><AipServiceLearningDetailsV8 key={service.name} serviceName={service.name} summary={service.summary}/></article>
      </section>
    </div>
    {expanded && <div className="image-modal" role="dialog" aria-modal="true" aria-label={`${service.name} EL10 full view`} onClick={() => setExpanded(false)}><button className="modal-close" onClick={() => setExpanded(false)}>Close ×</button><img src={assetUrl(service.file)} alt={`${service.name} EL10 infographic full view`} onClick={(event) => event.stopPropagation()}/></div>}
  </main>;
}
