import type { AipArchitecture, AipArchitectureNode, AipArchitectureLayer } from "./AipArchitectureOverrides";

const P=(label:string,sub:string,kind:AipArchitectureNode["kind"]):AipArchitectureNode=>({label,sub,kind});
const W=(label:string,sub:string,icon?:string):AipArchitectureNode=>({label,sub,icon});
const L=(title:string,...nodes:AipArchitectureNode[]):AipArchitectureLayer=>({title,nodes});
const A=(title:string,note:string,reference:string,...layers:AipArchitectureLayer[]):AipArchitecture=>({title,note,reference,layers});
const ops=L("Operate & govern",W("Amazon CloudWatch","Metrics / logs"),W("AWS CloudTrail","API audit"),P("IAM controls","Least privilege","security"));

const overrides2:Record<string,AipArchitecture[]>={
"Amazon Bedrock Prompt Management":[
 A("Versioned prompt delivery","Prompt engineers iterate on draft prompts and variants, compare outputs, then publish an immutable version that applications invoke by identifier.","Amazon Bedrock Prompt management versions and variants",L("Author",P("Prompt engineer","Template + variables","user"),P("Evaluation inputs","Test set","file")),L("Prompt lifecycle",W("Amazon Bedrock Prompt Management","Draft + variants + versions","Amazon Bedrock")),L("Test",W("Amazon Bedrock","Model inference"),P("Variant comparison","Quality / latency / cost","monitor")),L("Publish",P("Prompt version","Immutable application target","app")),L("Runtime",W("AWS Lambda","Load version + variables"),P("Application","Invoke prompt","app")),ops),
 A("Controlled prompt promotion","The same tested prompt version moves through dev/test/prod configuration without copying prompt text into application code.","Bedrock Prompt management deployment workflow",L("Development",P("Draft prompt","Iterate","file")),L("Approval",P("Reviewer","Compare versions / sign off","user")),L("Prompt registry",W("Amazon Bedrock Prompt Management","Named versions","Amazon Bedrock")),L("Application config",W("AWS AppConfig","Selected prompt ARN/version")),L("Production",W("AWS Lambda","Runtime invocation"),W("Amazon Bedrock","Foundation model")),ops)
],
"Amazon Bedrock Prompt Flows":[
 A("Multi-step GenAI workflow","A flow connects prompt, knowledge-base, Lambda and condition nodes so branching/orchestration is explicit instead of hidden in application code.","Amazon Bedrock Prompt Flows node orchestration",L("Request",P("Application","Input variables","app")),L("Flow",W("Amazon Bedrock Prompt Flows","Flow graph")),L("AI + retrieval",W("Amazon Bedrock","Prompt/model node"),W("Amazon Bedrock Knowledge Bases","Retrieval node","Amazon Bedrock")),L("Tools / control",W("AWS Lambda","Function node"),P("Condition / iterator","Branching","message")),L("Result",P("Application response","Flow output","app")),ops),
 A("Test-to-production flow versioning","Teams test a draft flow, publish a version, create an alias and let applications invoke the stable alias while new drafts evolve separately.","Amazon Bedrock Prompt Flows version and alias lifecycle",L("Builder",P("Developer","Draft flow","user")),L("Test",W("Amazon Bedrock Prompt Flows","Draft execution")),L("Publish",P("Flow version","Immutable graph","file"),P("Alias","Stable runtime target","network")),L("Runtime",W("Amazon API Gateway","Application API"),W("AWS Lambda","Invoke flow alias")),L("Models / data",W("Amazon Bedrock","Inference"),W("Amazon S3","Flow data")),ops)
],
"AWS CodeArtifact":[
 A("Private package supply chain","Developers and CI clients authenticate to CodeArtifact, resolve approved dependencies from a private repository, and optionally use an upstream public repository through controlled caching.","AWS CodeArtifact repository and upstream pattern",L("Clients",P("Developer / build agent","npm / pip / Maven","user")),L("Auth",P("Temporary authorization token","IAM-backed access","security")),L("Package repository",W("AWS CodeArtifact","Private domains / repositories")),L("Upstream",P("Public package repository","Approved external packages","internet")),L("Build",W("AWS CodeBuild","Install dependencies"),P("Application artifact","Built output","file")),ops),
 A("Cross-account package sharing","A central platform account owns package repositories while workload accounts use resource policies and IAM roles to consume approved packages.","CodeArtifact cross-account repository access",L("Platform account",W("AWS CodeArtifact","Central packages")),L("Policy",P("Repository / domain policy","Allowed accounts","security")),L("Workload account",W("AWS CodeBuild","Consumer build"),P("Assumed role","Temporary access","security")),L("Artifact",W("Amazon S3","Build output")),L("Deploy",W("AWS CodePipeline","Release")),ops)
],
"AWS CodeBuild":[
 A("Ephemeral build stage","A pipeline starts an isolated CodeBuild environment that pulls source/dependencies, runs tests, produces artifacts and terminates when the job finishes.","AWS CodeBuild CI architecture",L("Source",P("Git repository","Commit","file")),L("Pipeline",W("AWS CodePipeline","Build stage")),L("Build",W("AWS CodeBuild","Ephemeral build container"),W("AWS CodeArtifact","Dependencies")),L("Outputs",W("Amazon S3","Build artifact"),W("Amazon ECR","Container image")),L("Quality",P("Tests / reports","Gate","monitor")),ops),
 A("Private VPC build","CodeBuild attaches to selected VPC subnets when build steps must reach private databases, package mirrors or internal services.","CodeBuild VPC build environment",L("Build request",W("AWS CodePipeline","Start build")),L("Build runtime",W("AWS CodeBuild","VPC-enabled build")),L("Private network",P("Private subnets","Security groups","network")),L("Dependencies",P("Internal artifact mirror","Private service","app"),W("Amazon RDS","Integration-test DB")),L("Output",W("Amazon ECR","Image"),W("Amazon S3","Artifact")),ops)
],
"AWS CodeDeploy":[
 A("Blue/green application deployment","CodeDeploy shifts traffic from an old target group to a new revision behind a load balancer and can roll back on failed validation or alarms.","AWS CodeDeploy blue/green deployment",L("Release",W("AWS CodePipeline","Approved artifact")),L("Deployment",W("AWS CodeDeploy","Blue/green orchestration")),L("Old environment",P("Blue targets","Current version","compute")),L("New environment",P("Green targets","New version","compute")),L("Traffic",W("Elastic Load Balancing","Listener / target groups"),W("Amazon CloudWatch","Rollback alarms")),ops),
 A("Lambda canary deployment","A Lambda revision is published and traffic is shifted gradually while validation hooks and alarms decide whether to continue or roll back.","CodeDeploy Lambda traffic shifting",L("Function",W("AWS Lambda","New version")),L("Deployment",W("AWS CodeDeploy","Canary / linear policy")),L("Alias",P("Lambda alias","Weighted traffic","network")),L("Validation",P("Pre/post hooks","Smoke tests","monitor"),W("Amazon CloudWatch","Error alarms")),L("Outcome",P("Promote or rollback","Release decision","app")))
],
"AWS CodePipeline":[
 A("Multi-stage application release","A source change moves through build, test, approval and deployment stages with artifacts passed explicitly between actions.","AWS CodePipeline continuous delivery architecture",L("Source",P("Git repository","Commit","file")),L("Build",W("AWS CodeBuild","Compile / test")),L("Artifact",W("Amazon S3","Versioned pipeline artifact")),L("Approval",P("Manual / automated gate","Release decision","user")),L("Deploy",W("AWS CodeDeploy","Application"),W("AWS CloudFormation","Infrastructure")),ops),
 A("Cross-account production promotion","A tooling account owns the pipeline and assumes deployment roles into target accounts so production permissions do not live in the build environment.","CodePipeline cross-account deployment pattern",L("Tooling account",W("AWS CodePipeline","Release orchestration"),W("AWS CodeBuild","Build once")),L("Artifact encryption",W("Amazon S3","Shared artifact"),W("AWS KMS","Cross-account key")),L("Assume role",P("Deployment role","Temporary target-account access","security")),L("Target accounts",P("Test","Pre-production","app"),P("Production","Restricted deployment","app")),L("Deploy",W("AWS CloudFormation","Stacks"),W("AWS CodeDeploy","Applications")))
],
"AWS CloudFormation":[
 A("Change-set infrastructure delivery","Teams version templates, create a change set, review the proposed resource changes and then execute the stack update.","CloudFormation change set workflow",L("Template",P("Git repository","YAML / JSON IaC","file")),L("Validate",W("AWS CodeBuild","Lint / test")),L("Plan",W("AWS CloudFormation","Change set")),L("Review",P("Platform / app owner","Inspect diff","user")),L("Execute",W("AWS CloudFormation","Stack update"),P("AWS resources","Network / compute / data","app")),ops),
 A("Multi-account StackSets rollout","An administrator account distributes a standard stack to selected accounts/Regions using delegated administration and controlled target selection.","CloudFormation StackSets multi-account pattern",L("Central template",P("Platform team","Approved baseline","user")),L("StackSet",W("AWS CloudFormation","StackSet + deployment targets")),L("Organization",P("Accounts / OUs","Target selection","security")),L("Regions",P("Region A","Stack instance","app"),P("Region B","Stack instance","app")),L("Audit",W("AWS CloudTrail","Deployment history")))
],
"AWS CDK":[
 A("Code-to-CloudFormation deployment","Developers model infrastructure in code, synthesize it into CloudFormation templates, inspect the diff and deploy through CloudFormation.","AWS CDK synth and deploy lifecycle",L("Author",P("Developer","CDK application","user")),L("Synthesize",W("AWS CDK","Construct tree → template")),L("Review",P("cdk diff","Proposed changes","monitor")),L("Provision",W("AWS CloudFormation","Stack deployment")),L("Resources",W("Amazon VPC","Network"),W("AWS Lambda","Compute"),W("Amazon DynamoDB","Data")),ops),
 A("CDK CI/CD pipeline","A source commit starts build/test and CDK synthesis; generated assets are published before deployment waves promote stacks across environments.","AWS CDK Pipelines architecture",L("Source",P("Git repository","CDK code","file")),L("CI",W("AWS CodeBuild","Test + synth")),L("Assets",W("Amazon S3","File assets"),W("Amazon ECR","Docker assets")),L("Pipeline",W("AWS CodePipeline","Stages / waves")),L("Environments",P("Test account","Stacks","app"),P("Prod account","Stacks","app")),ops)
],
"AWS CLI":[
 A("Interactive administration with SSO","An engineer signs in through IAM Identity Center, obtains temporary credentials and uses the CLI to issue signed AWS API requests that appear in CloudTrail.","AWS CLI IAM Identity Center authentication",L("Engineer",P("Terminal","aws commands","user")),L("SSO",W("IAM Identity Center","Login / account selection")),L("Credentials",P("Cached temporary session","Short-lived keys","security")),L("AWS CLI",W("AWS CLI","SigV4 API requests")),L("AWS services",W("Amazon S3","Objects"),W("Amazon EC2","Instances")),L("Audit",W("AWS CloudTrail","API events"))),
 A("Scripted operational workflow","A shell/PowerShell automation script chains AWS CLI calls, uses role-based credentials and stores durable results outside the local machine.","AWS CLI automation best practices",L("Automation",P("Shell / PowerShell","Script","file")),L("Identity",P("Assumed role","Temporary credentials","security")),L("CLI",W("AWS CLI","API calls")),L("Targets",W("AWS Systems Manager","Operate fleet"),W("Amazon S3","Read/write artifacts")),L("Results",W("Amazon CloudWatch Logs","Execution logs"),ops.nodes[1]))
],
"AWS Tools and SDKs":[
 A("Application SDK request path","Application code uses an AWS SDK credential provider chain, signs requests and calls service APIs with retries, timeouts and telemetry around each request.","AWS SDK credential-provider and request model",L("Application",P("Java / Python / JS / .NET","Business code","app")),L("Credentials",P("SDK provider chain","Role / SSO / environment","security")),L("Client",W("AWS Tools and SDKs","Service client + retries")),L("AWS API",W("Amazon DynamoDB","Data call"),W("Amazon S3","Object call")),L("Observe",W("AWS X-Ray","Trace"),W("Amazon CloudWatch","Metrics / logs"))),
 A("Local-to-cloud development","Developers use language SDKs locally with SSO profiles, then the same code runs in AWS using workload roles instead of local credentials.","AWS SDK local and workload credential pattern",L("Local dev",P("Developer laptop","SDK + SSO profile","user")),L("Identity",W("IAM Identity Center","Local temporary session")),L("Deployment",W("AWS CodePipeline","Build / deploy")),L("Runtime",W("AWS Lambda","Execution role"),W("Amazon ECS","Task role")),L("Services",W("Amazon Bedrock","Model API"),W("Amazon S3","Objects")),ops)
],
"Amazon Aurora":[
 A("Aurora cluster with writer/readers","Applications connect through cluster/reader endpoints to a shared distributed Aurora storage volume while reader instances scale read traffic independently.","Amazon Aurora DB cluster architecture",L("Applications",P("Web / services","SQL","app")),L("Connection",P("Cluster endpoint","Writer traffic","network"),P("Reader endpoint","Read balancing","network")),L("Compute",W("Amazon Aurora","Writer + reader DB instances")),L("Storage",P("Aurora cluster volume","Multi-AZ distributed storage","storage")),L("Protection",W("AWS Secrets Manager","Credentials"),P("Backups / snapshots","Recovery","storage")),ops),
 A("Global database read-local / DR","A primary Aurora cluster replicates storage changes to secondary Regions for low-latency reads and disaster recovery.","Amazon Aurora Global Database architecture",L("Primary Region",W("Amazon Aurora","Writer cluster")),L("Cross-Region replication",P("Aurora Global Database","Storage-based replication","network")),L("Secondary Region",W("Amazon Aurora","Read-only secondary cluster")),L("Users",P("Regional applications","Local reads","user")),L("Failover",P("Promote secondary","DR event","monitor")),ops)
],
"Amazon RDS":[
 A("Multi-AZ transactional database","A private RDS primary synchronously replicates to a standby in another AZ while applications use one stable DB endpoint.","Amazon RDS Multi-AZ deployment architecture",L("Application",W("Amazon ECS","Stateless service"),W("AWS Secrets Manager","DB secret")),L("DB endpoint",P("RDS endpoint","Stable connection","network")),L("Primary",W("Amazon RDS","Primary DB instance")),L("Standby AZ",W("Amazon RDS","Synchronous standby")),L("Recovery",P("Automatic failover","Endpoint remaps","monitor"),P("Automated backups","Point-in-time restore","storage")),ops),
 A("Read-replica scaling","Read-heavy traffic is directed to one or more asynchronous read replicas while writes stay on the primary instance.","Amazon RDS read replica architecture",L("Application",P("API / reporting","Read + write traffic","app")),L("Write path",W("Amazon RDS","Primary writer")),L("Replication",P("Asynchronous replication","Replica lag possible","network")),L("Read path",W("Amazon RDS","Read replica(s)")),L("Consumers",P("Reports / read APIs","Scale reads","user")),ops)
],
"Amazon DynamoDB Streams":[
 A("Change-data-capture trigger","Item mutations are written to DynamoDB and corresponding ordered change records appear in Streams for Lambda consumers to process asynchronously.","DynamoDB Streams and Lambda architecture",L("Writers",P("Application","Put / Update / Delete","app")),L("Table",W("Amazon DynamoDB","System of record")),L("Change log",W("Amazon DynamoDB Streams","Per-item ordered records")),L("Consumer",W("AWS Lambda","Event source mapping")),L("Targets",W("Amazon OpenSearch Service","Search index"),W("Amazon SNS","Notification")),ops),
 A("Materialized-view projection","A stream processor transforms table changes into a denormalized read model without coupling the original write request to projection latency.","DynamoDB Streams materialized-view pattern",L("Transactions",W("Amazon DynamoDB","Source table")),L("Stream",W("Amazon DynamoDB Streams","Change records")),L("Processor",W("AWS Lambda","Projection logic")),L("Read model",W("Amazon DynamoDB","Denormalized table"),P("Cache / search","Optional projection","data")),L("Readers",P("API / dashboard","Fast query model","user")),ops)
],
"AWS Encryption SDK":[
 A("Client-side envelope encryption","Application code asks a keyring for a unique data key, encrypts plaintext locally and stores ciphertext together with encrypted data-key metadata.","AWS Encryption SDK envelope encryption workflow",L("Application",P("Client code","Plaintext object","app")),L("Keyring",W("AWS Encryption SDK","Generate encryption materials")),L("Wrapping key",W("AWS KMS","Protect data key")),L("Local encryption",P("Unique data key","Encrypt plaintext then discard key","security")),L("Encrypted message",W("Amazon S3","Ciphertext + encrypted data key")),ops),
 A("Multi-keyring decryption flexibility","The same data key can be wrapped by multiple keys so authorized decryptors need access to any compatible wrapping key, not all of them.","AWS Encryption SDK multi-keyring pattern",L("Encryptor",W("AWS Encryption SDK","Multi-keyring")),L("Wrapping keys",W("AWS KMS","Primary KMS key"),P("Secondary wrapping key","Other trust boundary","security")),L("Encrypted message",P("Ciphertext + multiple encrypted data keys","Portable message","file")),L("Decryptor",W("AWS Encryption SDK","Compatible keyring")),L("Result",P("Plaintext in application memory","Decrypted data","app")),ops)
]
};

export function getAipArchitectureOverrides2(service:string,_category:string):AipArchitecture[]|undefined{return overrides2[service];}
