export type AipArchitectureNode={label:string;sub:string;kind?:"user"|"internet"|"app"|"data"|"security"|"file"|"network"|"storage"|"ai"|"message"|"monitor"|"compute";icon?:string};
export type AipArchitectureLayer={title:string;nodes:AipArchitectureNode[]};
export type AipArchitecture={title:string;note:string;layers:AipArchitectureLayer[];reference:string};

const P=(label:string,sub:string,kind:AipArchitectureNode["kind"]):AipArchitectureNode=>({label,sub,kind});
const W=(label:string,sub:string,icon?:string):AipArchitectureNode=>({label,sub,icon});
const L=(title:string,...nodes:AipArchitectureNode[]):AipArchitectureLayer=>({title,nodes});
const A=(title:string,note:string,reference:string,...layers:AipArchitectureLayer[]):AipArchitecture=>({title,note,reference,layers});

const ops=L("Operate & govern",W("Amazon CloudWatch","Metrics / logs"),W("AWS CloudTrail","API audit"),P("IAM controls","Least privilege","security"));

const overrides:Record<string,AipArchitecture[]>={
"AWS Glue":[
 A("Curated serverless data lake","Glue crawlers/catalog and ETL jobs turn raw S3 data into partitioned curated datasets consumed by Athena and downstream analytics.","AWS serverless data lake with Glue ETL and Data Catalog",L("Raw sources",P("Applications / SaaS","JSON / CSV / events","data"),W("Amazon S3","Raw zone")),L("Discover & catalog",W("AWS Glue","Crawler + Data Catalog")),L("Transform",W("AWS Glue","Spark ETL job"),P("Partitions / schema","Curated metadata","data")),L("Curated lake",W("Amazon S3","Parquet / ORC")),L("Consume",W("Amazon Athena","SQL analytics"),P("BI / ML","Queries / features","user")),ops),
 A("Event-driven ETL pipeline","New objects trigger orchestration that runs Glue transformations, validates output and publishes completion events.","AWS event-driven Glue ETL workflow",L("Ingest",W("Amazon S3","New object")),L("Trigger",W("Amazon EventBridge","Object event")),L("Orchestrate",W("AWS Step Functions","ETL workflow")),L("Transform",W("AWS Glue","Job / crawler")),L("Publish",W("Amazon S3","Curated output"),W("Amazon SNS","Completion / failure")),ops)
],
"Amazon Kinesis":[
 A("Real-time event fan-out","Producers write ordered records into shards while Lambda, KCL consumers and analytics applications read independently.","Kinesis Data Streams producer-consumer architecture",L("Producers",P("Web / devices","Events","app"),P("Services","Telemetry / business events","app")),L("Stream",W("Amazon Kinesis","Shards + retention")),L("Consumers",W("AWS Lambda","Event processing"),P("KCL application","Stateful consumer","compute"),W("Amazon Data Firehose","Delivery")),L("Destinations",W("Amazon S3","Lake"),W("Amazon OpenSearch Service","Search")),ops),
 A("Enhanced fan-out consumers","Registered consumers receive dedicated per-shard read throughput so multiple low-latency consumers do not compete with one another.","Kinesis enhanced fan-out consumer architecture",L("Producers",P("High-volume publishers","PutRecord(s)","app")),L("Stream",W("Amazon Kinesis","Sharded stream")),L("Enhanced fan-out",P("Consumer A","Dedicated shard pipe","message"),P("Consumer B","Dedicated shard pipe","message")),L("Processing",W("AWS Lambda","Realtime actions"),P("KCL workers","Analytics","compute")),ops)
],
"Amazon OpenSearch Service":[
 A("Private search and log analytics","Applications and ingestion pipelines index documents into a VPC-isolated OpenSearch domain while users access search or dashboards through controlled paths.","OpenSearch Service VPC architecture",L("Data sources",P("Applications","Documents / logs","app"),P("OpenTelemetry collectors","Logs / traces / metrics","monitor")),L("Ingestion",P("OpenSearch Ingestion","Filter / enrich / route","data")),L("Private domain",W("Amazon OpenSearch Service","Multi-AZ domain"),P("Security groups","Private ENIs","security")),L("Consumers",P("Search API","Application queries","app"),P("OpenSearch UI","Dashboards / investigation","user")),ops),
 A("Vector search for grounded AI","Documents are embedded and indexed in OpenSearch; a RAG application retrieves nearest-neighbor context before invoking a model.","OpenSearch vector search RAG pattern",L("Knowledge",W("Amazon S3","Documents")),L("Prepare",W("AWS Lambda","Chunk / normalize"),W("Amazon Bedrock","Embeddings")),L("Vector index",W("Amazon OpenSearch Service","k-NN / vector search")),L("RAG",W("Amazon Bedrock","Grounded generation")),L("Experience",P("Chat / search app","Cited answer","user")),ops)
],
"Amazon Quick Sight":[
 A("Serverless BI over a data lake","QuickSight authors query Athena-backed datasets, optionally import them into SPICE, and publish governed dashboards to readers.","QuickSight with Athena and SPICE architecture",L("Data lake",W("Amazon S3","Curated data"),W("AWS Glue","Catalog")),L("Query",W("Amazon Athena","SQL layer")),L("BI dataset",W("Amazon Quick","Direct query / SPICE","Amazon Quick")),L("Publish",P("Dashboards","Interactive visuals","app")),L("Consumers",P("Analysts / executives","Browser / embedded BI","user")),ops),
 A("Private-source enterprise BI","QuickSight reaches supported private VPC data sources through managed VPC connectivity while dashboard users remain separated from database credentials.","QuickSight VPC connection architecture",L("Enterprise data",W("Amazon RDS","Private database"),P("Warehouse / service","Private endpoint","data")),L("VPC connectivity",P("QuickSight VPC connection","ENIs + security groups","network")),L("BI service",W("Amazon Quick","Dataset + dashboard","Amazon Quick")),L("Users",P("Authors / readers","Federated access","user")),ops)
],
"Amazon Managed Streaming for Apache Kafka (Amazon MSK)":[
 A("Managed Kafka event backbone","Producers publish business events to MSK topics while independent consumer groups process data for applications, search and lakes.","Amazon MSK producer-consumer architecture",L("Producers",P("Microservices","Kafka producers","app"),P("On-prem apps","Private connectivity","network")),L("Kafka cluster",W("Amazon Managed Streaming for Apache Kafka","Brokers + topics")),L("Consumer groups",P("Payments consumer","Ordered events","compute"),P("Analytics consumer","Stream processing","compute")),L("Destinations",W("Amazon S3","Data lake"),W("Amazon OpenSearch Service","Search")),ops),
 A("MSK Connect integration","Managed Kafka Connect workers move data between MSK and external systems without running connector infrastructure yourself.","Amazon MSK Connect architecture",L("Sources",P("Database / SaaS","CDC / records","data")),L("Connector workers",P("MSK Connect","Managed connector runtime","compute")),L("Kafka",W("Amazon Managed Streaming for Apache Kafka","Topics")),L("Sinks",W("Amazon S3","Lake"),P("External system","Downstream sink","internet")),ops)
],
"AWS App Runner":[
 A("Source-to-service web deployment","A source repository or container image is built into an App Runner service that auto scales behind its managed HTTPS endpoint.","App Runner source/image service architecture",L("Source",P("Git repository","Application source","file"),W("Amazon ECR","Container image")),L("Managed service",W("AWS App Runner","Build / deploy / auto scale")),L("Ingress",P("HTTPS endpoint","Public service URL","internet")),L("Application",P("Web / API users","Requests","user")),L("Dependencies",W("AWS Secrets Manager","Secrets"),W("Amazon CloudWatch","Logs / metrics"))),
 A("App Runner with private VPC dependencies","The App Runner service stays managed while outbound traffic reaches private databases through a VPC connector.","App Runner VPC connector architecture",L("Clients",P("Internet users","HTTPS","user")),L("Managed runtime",W("AWS App Runner","Auto-scaled service")),L("VPC connector",P("VPC connector","Private egress","network")),L("Private services",W("Amazon RDS","Database"),W("Amazon ElastiCache","Cache"),W("AWS Secrets Manager","Credentials")),ops)
],
"Amazon EC2":[
 A("Load-balanced Auto Scaling web tier","An ALB distributes requests across an EC2 Auto Scaling group in multiple AZs while durable state remains in managed data services.","EC2 Auto Scaling with Application Load Balancer",L("Users",P("Internet clients","HTTPS","user")),L("Ingress",W("Amazon Route 53","DNS"),W("Elastic Load Balancing","ALB")),L("Compute",W("Amazon EC2","Auto Scaling group across AZs")),L("State",W("Amazon RDS","Database"),W("Amazon S3","Objects")),L("Operations",W("Amazon CloudWatch","Scaling / alarms"),P("Systems Manager","Patch / session","monitor"))),
 A("Private EC2 application fleet","Instances run only in private subnets, retrieve secrets at runtime and use NAT or VPC endpoints for controlled outbound access.","EC2 private-subnet application architecture",L("Entry",W("Elastic Load Balancing","Public or internal ALB")),L("Private compute",W("Amazon EC2","Instances in private subnets"),P("Security groups","Stateful access","security")),L("Service access",W("AWS PrivateLink","Interface endpoints"),P("NAT gateway","Internet egress","network")),L("Dependencies",W("AWS Secrets Manager","Secrets"),W("Amazon S3","Artifacts")),ops)
],
"AWS Outposts":[
 A("Local low-latency application","Workloads run on Outposts subnets close to on-premises systems while the service link keeps the Outpost connected to its parent AWS Region.","AWS Outposts hybrid application architecture",L("On premises",P("Factory / datacenter systems","Low-latency data","data")),L("Local gateway",P("Outposts local gateway","On-prem routing","network")),L("Outpost subnet",W("AWS Outposts","Local AWS infrastructure"),W("Amazon EC2","Local workload")),L("Region link",P("Service link","Control plane connectivity","network")),L("Regional services",W("Amazon S3","Regional data / backup"),W("Amazon CloudWatch","Monitoring"))),
 A("Private Outposts-to-Region path","A local gateway serves on-premises traffic while Direct Connect/private connectivity provides a private path back to regional AWS service endpoints.","Outposts local gateway and private connectivity",L("Local network",P("Corporate LAN","Users / systems","network")),L("Outposts routing",P("Local gateway route table","VPC + VIF group","network")),L("Outpost workloads",W("AWS Outposts","Outpost subnets"),W("Amazon EC2","Applications")),L("Private regional path",P("AWS Direct Connect","Private connectivity","network")),L("AWS Region",W("Amazon RDS","Regional data"),W("Amazon S3","Objects")),ops)
],
"AWS Wavelength":[
 A("5G edge application","Mobile traffic exits the carrier network into a Wavelength Zone so latency-sensitive compute runs close to users while regional services remain available through the parent Region.","AWS Wavelength 5G edge architecture",L("5G users",P("Mobile devices","Carrier 5G","user")),L("Carrier edge",P("Carrier gateway","Mobile network path","network")),L("Wavelength Zone",W("AWS Wavelength","Edge subnet"),W("Amazon EC2","Latency-sensitive app")),L("Regional backhaul",P("VPC connection","Parent Region","network")),L("Regional services",W("Amazon S3","Durable data"),W("Amazon RDS","Regional database")),ops),
 A("Edge inference with regional control plane","Inference runs at the 5G edge while models, logs and durable state are managed regionally.","Wavelength edge inference pattern",L("Devices",P("Cameras / mobiles","Realtime input","user")),L("Edge compute",W("AWS Wavelength","Wavelength subnet"),W("Amazon EC2","Inference service")),L("Local response",P("Application response","Low-latency action","app")),L("Regional management",W("Amazon S3","Model artifacts"),W("Amazon CloudWatch","Telemetry")),ops)
],
"AWS Amplify":[
 A("Full-stack web application","Amplify builds and hosts a frontend while Cognito, AppSync/API Gateway and managed backends provide identity, APIs and data.","AWS Amplify full-stack web application architecture",L("Source",P("Git repository","Frontend code","file")),L("Build & host",W("AWS Amplify","CI/CD + hosting")),L("Identity",W("Amazon Cognito","Sign-in")),L("API",W("AWS AppSync","GraphQL / realtime"),W("Amazon API Gateway","REST")),L("Data",W("Amazon DynamoDB","Application state"),W("Amazon S3","User content")),ops),
 A("Amplify-hosted GenAI experience","A static/SSR frontend authenticates users and calls a serverless API that invokes Bedrock while secrets and logs stay server-side.","Amplify + serverless GenAI application pattern",L("Users",P("Browser / mobile","HTTPS","user")),L("Frontend",W("AWS Amplify","Hosted application")),L("Auth + API",W("Amazon Cognito","Identity"),W("Amazon API Gateway","Protected API")),L("Compute / AI",W("AWS Lambda","Prompt logic"),W("Amazon Bedrock","Model inference")),ops)
],
"Kiro":[
 A("Agentic IDE development workflow","A developer uses Kiro against a local/repository workspace, reviews generated changes and then commits through normal source-control and CI processes.","AWS Kiro agentic development workflow",L("Developer",P("Engineer","Prompt / spec / task","user")),L("IDE agent",P("Kiro","Agentic coding + tools","ai")),L("Workspace",P("Repository","Code / tests / docs","file")),L("Review",P("Developer approval","Inspect diff / run tests","user")),L("Delivery",W("AWS CodePipeline","CI/CD"),W("AWS CodeBuild","Build / test")),ops),
 A("Kiro with governed AWS tooling","IDE automation uses short-lived AWS credentials or approved MCP/tool connections to inspect and modify cloud resources without embedding secrets in code.","Kiro governed cloud-development pattern",L("Developer",P("Kiro IDE","Task","app")),L("Identity",W("IAM Identity Center","Temporary access"),P("Assumed role","Least privilege","security")),L("Tools",P("MCP / CLI / SDK","Bounded actions","compute")),L("AWS targets",W("Amazon S3","Artifacts"),W("AWS Lambda","Functions"),W("Amazon Bedrock","AI APIs")),ops)
],
"Amazon Augmented AI":[
 A("Human review for low-confidence predictions","An ML or AI service produces a prediction; low-confidence results enter an A2I human review workflow before final output is accepted.","Amazon A2I human review workflow",L("Input",P("Business document / image","Reviewable item","file")),L("Machine prediction",W("Amazon Textract","Extraction"),P("Custom model","Prediction","ai")),L("Review decision",P("Confidence rule","Human loop trigger","security")),L("Human review",W("Amazon Augmented AI","Private / vendor workforce")),L("Final result",W("Amazon S3","Reviewed output"),P("Business system","Consume result","app")),ops),
 A("Custom model review loop","Application inference calls a custom model and routes uncertain outcomes through a task UI so reviewer corrections become audited training/evaluation data.","Amazon A2I custom human loop pattern",L("Application",P("API / batch job","Inference request","app")),L("Model",W("Amazon SageMaker AI","Endpoint")),L("Human loop",W("Amazon Augmented AI","Review task")),L("Reviewer",P("Domain expert","Approve / correct","user")),L("Feedback",W("Amazon S3","Reviewed labels"),P("Retraining pipeline","Future model update","ai")),ops)
],
"Amazon Comprehend":[
 A("Document NLP enrichment","Documents land in S3, Comprehend extracts sentiment/entities/key phrases, and structured results feed search or analytics.","Amazon Comprehend asynchronous document analysis",L("Documents",W("Amazon S3","Text corpus")),L("NLP analysis",W("Amazon Comprehend","Entities / sentiment / key phrases")),L("Output",W("Amazon S3","Structured results")),L("Consume",W("Amazon OpenSearch Service","Search"),W("Amazon Athena","Analytics")),ops),
 A("Near-real-time text classification","An application sends user text for synchronous classification and uses the result to route workflow or moderation decisions.","Amazon Comprehend real-time analysis pattern",L("Application",P("Chat / ticket system","Text","app")),L("NLP",W("Amazon Comprehend","Classification / PII / sentiment")),L("Decision",W("AWS Lambda","Business rules")),L("Actions",W("Amazon SQS","Route work"),P("Agent / workflow","Handle result","user")),ops)
],
"Amazon Comprehend Medical":[
 A("Clinical text entity extraction","Clinical notes are processed to identify medical entities and relationships before structured output is written to a protected analytics store.","Comprehend Medical clinical NLP workflow",L("Clinical notes",P("EHR export / notes","Protected health text","file")),L("Secure staging",W("Amazon S3","Encrypted input"),W("AWS KMS","Encryption")),L("Medical NLP",W("Amazon Comprehend Medical","Entities / traits / relations")),L("Structured output",W("Amazon S3","Encrypted results")),L("Consume",P("Clinical analytics","Search / review","user")),ops),
 A("Medical coding assistance","Extracted clinical concepts are normalized and passed to downstream coding/review workflows rather than directly making care decisions.","Comprehend Medical ontology linking workflow",L("Notes",P("Clinical documentation","Text","file")),L("Extraction",W("Amazon Comprehend Medical","Medical entities")),L("Normalization",P("ICD / RxNorm concepts","Ontology linkage","data")),L("Review",P("Coding specialist","Validate","user")),L("Systems",P("Billing / analytics","Accepted codes","app")),ops)
],
"Amazon Personalize":[
 A("Real-time recommendations","User/item interaction data trains a Personalize solution; applications request recommendations and record new events to improve future results.","Amazon Personalize real-time recommendation architecture",L("Behavior data",P("Clicks / purchases","Interactions","data"),P("User / item metadata","Features","data")),L("Training",W("Amazon Personalize","Dataset group + solution")),L("Serving",W("Amazon Personalize","Campaign / recommender")),L("Application",P("Web / mobile","GetRecommendations","app")),L("Feedback",P("Event tracker","New interactions","message")),ops),
 A("Batch recommendations for campaigns","Offline recommendation jobs produce ranked outputs in S3 for marketing, email or analytics workflows.","Amazon Personalize batch inference pattern",L("Datasets",W("Amazon S3","Users / items / interactions")),L("Model",W("Amazon Personalize","Trained solution")),L("Batch inference",P("Batch inference job","Ranked items","compute")),L("Output",W("Amazon S3","Recommendations")),L("Activation",P("Campaign / CRM","Use recommendations","app")),ops)
],
"Amazon Polly":[
 A("Text-to-speech application","An application generates text, invokes Polly for speech synthesis, and streams or stores audio for end users.","Amazon Polly text-to-speech architecture",L("Text source",P("Application / article","Text","app")),L("Synthesis",W("Amazon Polly","Voice + speech marks")),L("Delivery",P("Audio stream","Realtime playback","message"),W("Amazon S3","Generated audio")),L("Users",P("Web / mobile / IVR","Listen","user")),ops),
 A("Automated voice content pipeline","Events trigger serverless processing that converts new text content to audio and publishes it through CDN-backed storage.","Polly serverless content generation pattern",L("Content",W("Amazon S3","Text / SSML")),L("Trigger",W("Amazon EventBridge","New content")),L("Processing",W("AWS Lambda","Prepare request"),W("Amazon Polly","Synthesize")),L("Publish",W("Amazon S3","Audio objects"),W("Amazon CloudFront","Global delivery")),ops)
],
"Amazon Rekognition":[
 A("Image moderation pipeline","Uploaded images are scanned by Rekognition before approved content becomes visible to downstream applications.","Amazon Rekognition content moderation workflow",L("Upload",P("User image","Object","file"),W("Amazon S3","Quarantine bucket")),L("Trigger",W("AWS Lambda","Moderation request")),L("Vision analysis",W("Amazon Rekognition","Labels / moderation")),L("Decision",P("Threshold policy","Approve / review / reject","security")),L("Publish",W("Amazon S3","Approved content"),P("Moderator","Edge cases","user")),ops),
 A("Video analysis workflow","Video in S3 starts asynchronous Rekognition analysis; completion events trigger result processing and indexing.","Amazon Rekognition Video asynchronous analysis",L("Video",W("Amazon S3","Media object")),L("Analysis",W("Amazon Rekognition","Async video job")),L("Completion",W("Amazon SNS","Job notification")),L("Process",W("AWS Lambda","Fetch results")),L("Index",W("Amazon OpenSearch Service","Searchable metadata")),ops)
],
"Amazon Textract":[
 A("Intelligent document processing","Documents uploaded to S3 are analyzed by Textract and then enriched/validated before structured fields reach business systems.","Amazon Textract intelligent document processing",L("Documents",W("Amazon S3","PDF / image")),L("Extraction",W("Amazon Textract","Text / forms / tables / queries")),L("Orchestration",W("AWS Step Functions","Validate / branch")),L("Enrichment",W("Amazon Comprehend","Entities / classification"),P("Business rules","Validate fields","security")),L("Destination",W("Amazon DynamoDB","Structured data"),P("ERP / case system","Business process","app")),ops),
 A("Human-reviewed forms extraction","Low-confidence extracted fields are routed to human review before the final document record is committed.","Textract + A2I human review pattern",L("Forms",P("Invoice / claim","Document","file")),L("OCR",W("Amazon Textract","Field extraction")),L("Confidence gate",P("Thresholds","Accept or review","monitor")),L("Review",W("Amazon Augmented AI","Human loop")),L("Final record",W("Amazon DynamoDB","Validated fields")),ops)
],
"Amazon Transcribe":[
 A("Contact-center transcription","Audio is transcribed and the transcript is enriched for analytics, summarization and searchable archives.","Amazon Transcribe call analytics pattern",L("Audio",P("Call recording / stream","Speech","message")),L("Speech-to-text",W("Amazon Transcribe","Transcript + timestamps")),L("Enrichment",W("Amazon Comprehend","Sentiment / entities"),W("Amazon Bedrock","Summary")),L("Archive",W("Amazon S3","Audio + transcript")),L("Consume",P("Supervisor / QA","Review / search","user")),ops),
 A("Live captioning","Streaming audio is sent to Transcribe and partial/final transcripts are returned to a real-time application.","Amazon Transcribe streaming architecture",L("Speaker",P("Microphone / stream","Audio chunks","user")),L("Streaming client",P("Web / app","Bi-directional stream","app")),L("Transcription",W("Amazon Transcribe","Streaming ASR")),L("Display",P("Captions / transcript","Realtime text","app")),ops)
],
"Amazon Nova":[
 A("Multimodal GenAI application","A client sends text and media through an application layer to a Nova model in Bedrock and stores generated artifacts separately.","Amazon Nova multimodal application pattern",L("Users",P("Web / creative app","Prompt + media","user")),L("Application",W("AWS Lambda","Prompt / session logic"),W("Amazon S3","Input media")),L("Model",W("Amazon Nova","Multimodal generation","Amazon Nova")),L("Output",W("Amazon S3","Generated assets"),P("Application","Preview / edit","app")),ops),
 A("Nova grounded assistant","Enterprise context is retrieved before invoking Nova, with policy, session state and audit separated from the model call.","Amazon Nova RAG application pattern",L("User",P("Employee","Question","user")),L("Retrieval",W("Amazon Bedrock Knowledge Bases","Context","Amazon Bedrock")),L("Model",W("Amazon Nova","Reasoning / generation","Amazon Nova")),L("State",W("Amazon DynamoDB","Conversation state")),L("Response",P("Assistant UI","Grounded answer","app")),ops)
],
"Amazon Titan":[
 A("Embeddings for managed RAG","Titan Embeddings converts document chunks and user queries into vectors used by a retrieval store before generation.","Titan Embeddings RAG workflow",L("Documents",W("Amazon S3","Knowledge files")),L("Chunking",W("AWS Lambda","Prepare text")),L("Embeddings",W("Amazon Titan","Vector embeddings","Amazon Bedrock")),L("Vector store",W("Amazon OpenSearch Service","Nearest-neighbor search")),L("Generation",W("Amazon Bedrock","Grounded answer")),ops),
 A("Text generation through Bedrock","Applications invoke a Titan text model through Bedrock APIs while prompts, guardrails, logs and persistent state remain external.","Amazon Titan text generation pattern",L("Application",P("API / workflow","Prompt","app")),L("Orchestration",W("AWS Lambda","Prompt logic")),L("Model",W("Amazon Titan","Text generation","Amazon Bedrock")),L("Safety / state",P("Guardrails / validation","Policy checks","security"),W("Amazon DynamoDB","Session state")),ops)
],
"Amazon PartyRock":[
 A("No-code GenAI prototype","A builder composes prompt-powered widgets into a lightweight application to test an idea before production engineering begins.","PartyRock rapid prototyping workflow",L("Builder",P("Business user / developer","Idea + prompts","user")),L("Prototype",W("Amazon PartyRock","No-code app + widgets")),L("Models",W("Amazon Bedrock","Foundation models")),L("Output",P("Shared prototype","Validate UX / prompt","app")),L("Next step",P("Production team","Rebuild with governed AWS services","user"))),
 A("Prompt experiment workspace","Multiple widgets pass generated outputs between steps so users can compare prompt designs and model behavior quickly.","PartyRock multi-widget GenAI pattern",L("Input",P("User prompt","Task","user")),L("Widget chain",W("Amazon PartyRock","Prompt widget"),P("Generated text","Intermediate output","message"),W("Amazon PartyRock","Downstream widget")),L("Model access",W("Amazon Bedrock","Underlying models")),L("Review",P("User","Compare / iterate","user")))
],
"Amazon Q Business":[
 A("Permission-aware enterprise assistant","Connectors ingest enterprise content and ACLs into a Q index/retriever; IAM Identity Center users only receive answers from content they are allowed to access.","Application and Data Connectors for Amazon Q Business",L("Enterprise sources",P("SharePoint / Jira / ServiceNow","Documents + ACLs","internet"),W("Amazon S3","Enterprise files")),L("Ingestion",P("Q data-source connectors","Sync content + identities","data"),W("AWS Secrets Manager","Connector secrets")),L("Search layer",W("Amazon Q Business","Index + retriever","Amazon Q Business")),L("Identity",W("IAM Identity Center","User / group context")),L("Experience",P("Employee chat","Permission-filtered answer","user")),ops),
 A("Enterprise assistant with actions","Authenticated users ask questions and invoke bounded plugins/actions while Q preserves identity context and source permissions.","Amazon Q Business application actions pattern",L("Users",P("Employees","Question / task","user"),W("IAM Identity Center","Identity")),L("Assistant",W("Amazon Q Business","Conversation + retrieval","Amazon Q Business")),L("Knowledge",P("Connected sources","ACL-filtered context","data")),L("Actions",P("Plugin / API action","Create / update / lookup","app"),W("AWS Lambda","Custom integration")),L("Audit",W("Amazon CloudWatch","Application telemetry"),P("Business system","Action result","internet")))
],
"Amazon Q Business Apps":[
 A("No-code enterprise app from Q knowledge","A business user turns a Q Business conversation into a reusable app whose prompts and outputs remain grounded in governed enterprise sources.","Amazon Q Apps enterprise app workflow",L("Business user",P("Employee","Describe workflow","user")),L("App creation",W("Amazon Q Business Apps","Generate app / cards","Amazon Q Business Apps")),L("Enterprise context",W("Amazon Q Business","Permission-aware knowledge","Amazon Q Business")),L("Execution",P("Reusable business app","Collect / transform / summarize","app")),L("Collaboration",P("Team users","Run / share app","user")),ops),
 A("Human-in-the-loop business workflow","Q App cards collect inputs, call AI/knowledge steps, and present output for a user decision rather than hiding the workflow inside one prompt.","Amazon Q Apps card-based workflow",L("Inputs",P("User form / files","Task context","user")),L("App flow",W("Amazon Q Business Apps","Input + prompt + output cards","Amazon Q Business Apps")),L("Knowledge",W("Amazon Q Business","Enterprise retrieval","Amazon Q Business")),L("Review",P("Human approver","Inspect result","user")),L("Outcome",P("Business process","Copy / submit / share","app")))
],
"Amazon Q Developer":[
 A("IDE coding assistance","A developer uses Q in an IDE against the current codebase, reviews suggested changes and keeps normal tests/source-control gates before deployment.","Amazon Q Developer IDE workflow",L("Developer",P("Engineer","Chat / transform / explain","user")),L("IDE",W("Amazon Q Developer","Code-aware assistance","Amazon Q Developer")),L("Codebase",P("Repository / workspace","Project context","file")),L("Review",P("Developer","Inspect diff / tests","user")),L("Delivery",W("AWS CodeBuild","Build / test"),W("AWS CodePipeline","Deploy")),ops),
 A("AWS troubleshooting and CLI workflow","Q helps an operator understand AWS resources or generate commands while actual API calls still use IAM-authorized CLI/SDK credentials and remain auditable.","Amazon Q Developer AWS operations workflow",L("Operator",P("Developer / cloud engineer","Question / task","user")),L("Assistant",W("Amazon Q Developer","Explain / generate")),L("Execution",W("AWS CLI","Signed API call"),P("IAM role","Authorized permissions","security")),L("AWS services",W("Amazon EC2","Resource"),W("Amazon CloudWatch","Telemetry")),L("Audit",W("AWS CloudTrail","API history")))
],
"Amazon Quick":[
 A("AI-assisted BI analysis","Business users ask natural-language questions over governed datasets and receive generated summaries/visual insights without replacing the underlying BI data model.","Amazon Quick AI-assisted analytics pattern",L("Data",W("Amazon S3","Lake"),W("Amazon Athena","SQL"),W("Amazon RDS","Business data")),L("Semantic / BI layer",W("Amazon Quick","Dataset / semantic model","Amazon Quick")),L("AI experience",P("Natural-language analysis","Questions / summaries","ai")),L("Users",P("Analysts / business users","Explore / share","user")),ops),
 A("Embedded analytics experience","Applications embed governed Quick dashboards/insights for end users while dataset access remains controlled in the BI service.","Amazon Quick embedded analytics pattern",L("Application users",P("Customer / employee","App session","user")),L("Host application",P("Web portal","Authenticated UX","app")),L("Embedded BI",W("Amazon Quick","Dashboard / insight","Amazon Quick")),L("Data sources",W("Amazon Athena","Lake queries"),W("Amazon RDS","Operational data")),ops)
],
"Amazon SageMaker Data Wrangler":[
 A("Interactive feature preparation","A data scientist explores and transforms data in Data Wrangler, then exports the flow into repeatable processing/training workflows.","SageMaker Data Wrangler prepare-data workflow",L("Sources",W("Amazon S3","Raw datasets"),P("Data warehouse","Tabular source","data")),L("Interactive prep",W("Amazon SageMaker Data Wrangler","Explore / transform")),L("Export",W("Amazon SageMaker Processing","Repeatable processing job","Amazon SageMaker AI")),L("Train",W("Amazon SageMaker AI","Training job")),L("Artifacts",W("Amazon S3","Prepared features / flow")),ops),
 A("Productionized transformation flow","A reviewed Data Wrangler flow runs as scheduled/batch processing before model retraining.","Data Wrangler export to SageMaker Processing",L("New data",W("Amazon S3","Batch input")),L("Schedule",W("Amazon EventBridge","Retraining trigger")),L("Processing",W("Amazon SageMaker Data Wrangler","Exported flow"),W("Amazon SageMaker Processing","Managed job","Amazon SageMaker AI")),L("Training",W("Amazon SageMaker AI","Model training")),L("Registry",W("Amazon SageMaker Model Registry","Versioned model","Amazon SageMaker AI")))
],
"Amazon SageMaker Processing":[
 A("Managed preprocessing job","A processing container reads raw data from S3, performs feature engineering or validation, and writes deterministic outputs for training.","SageMaker Processing data preprocessing pattern",L("Input",W("Amazon S3","Raw dataset")),L("Job",W("Amazon SageMaker Processing","Managed container + compute","Amazon SageMaker AI")),L("Output",W("Amazon S3","Features / reports")),L("Training",W("Amazon SageMaker AI","Training job")),ops),
 A("Model evaluation pipeline","Processing jobs run evaluation code against a candidate model and test set before a registry approval decision.","SageMaker Processing model evaluation pattern",L("Candidate",W("Amazon S3","Model artifact"),W("Amazon S3","Evaluation data")),L("Evaluation",W("Amazon SageMaker Processing","Metrics / tests","Amazon SageMaker AI")),L("Decision",P("Quality gate","Threshold / approval","security")),L("Registry",W("Amazon SageMaker Model Registry","Approved / rejected","Amazon SageMaker AI")),ops)
],
"Amazon SageMaker Ground Truth":[
 A("Managed data labeling","Unlabeled S3 objects become labeling tasks assigned to a workforce, with completed annotations written back for training.","SageMaker Ground Truth labeling job",L("Dataset",W("Amazon S3","Unlabeled objects")),L("Labeling job",W("Amazon SageMaker Ground Truth","Task template + workflow","Amazon SageMaker AI")),L("Workforce",P("Private / vendor workers","Human labels","user")),L("Output",W("Amazon S3","Manifest + annotations")),L("Training",W("Amazon SageMaker AI","Model training")),ops),
 A("Active-learning labeling loop","Automation labels high-confidence items while uncertain examples are routed to human workers to reduce total labeling effort.","Ground Truth automated data labeling pattern",L("Unlabeled data",W("Amazon S3","Dataset")),L("Automatic labeling",W("Amazon SageMaker Ground Truth","Active learning","Amazon SageMaker AI")),L("Confidence split",P("High confidence","Auto label","ai"),P("Low confidence","Human task","message")),L("Workforce",P("Annotators","Review / label","user")),L("Final manifest",W("Amazon S3","Training labels")))
],
"Amazon SageMaker Clarify":[
 A("Bias and explainability processing","Clarify reads datasets/configuration from S3, optionally invokes a model endpoint, computes bias/SHAP analysis and writes reports back to S3.","SageMaker Clarify processing-job architecture",L("Inputs",W("Amazon S3","Dataset + analysis config")),L("Analysis",W("Amazon SageMaker Clarify","Processing container","Amazon SageMaker AI")),L("Optional model",W("Amazon SageMaker AI","Endpoint predictions")),L("Results",W("Amazon S3","Bias metrics / SHAP / report")),L("Review",P("Data scientist / risk","Interpret findings","user")),ops),
 A("Online explainability","A SageMaker endpoint serves predictions while Clarify explainer logic produces per-request explanations for selected inference traffic.","SageMaker Clarify online explainability",L("Client",P("Application","Inference request","app")),L("Endpoint",W("Amazon SageMaker AI","Hosted model")),L("Explainer",W("Amazon SageMaker Clarify","Feature attribution","Amazon SageMaker AI")),L("Response",P("Prediction + explanation","Application output","message")),L("Observe",W("Amazon CloudWatch","Endpoint metrics")))
],
"Amazon SageMaker Model Monitor":[
 A("Production data-quality monitoring","A real-time endpoint captures requests/responses to S3; scheduled Model Monitor jobs compare them with a baseline and emit violations/metrics.","SageMaker Model Monitor data-capture architecture",L("Inference",W("Amazon SageMaker AI","Realtime endpoint")),L("Capture",W("Amazon S3","Sampled inputs / outputs")),L("Baseline",W("Amazon S3","Constraints / statistics")),L("Monitor",W("Amazon SageMaker Model Monitor","Scheduled comparison","Amazon SageMaker AI")),L("Alert",W("Amazon CloudWatch","Violation metrics / alarms"),P("ML operator","Investigate","user"))),
 A("Model-quality monitoring with ground truth","Predictions are joined later with actual outcomes so scheduled monitoring can detect quality degradation rather than only input drift.","SageMaker Model Monitor model-quality workflow",L("Predictions",W("Amazon S3","Captured inference")),L("Ground truth",P("Business outcomes","Actual labels","data")),L("Join / evaluate",W("Amazon SageMaker Model Monitor","Quality metrics","Amazon SageMaker AI")),L("Alert",W("Amazon CloudWatch","Threshold breach")),L("Retrain",P("MLOps pipeline","Trigger review / retraining","app")))
],
"Amazon SageMaker Model Registry":[
 A("Governed model promotion","Training produces a model package that is versioned in Model Registry, evaluated/approved, then promoted into deployment stages.","SageMaker Model Registry MLOps pattern",L("Build",W("Amazon SageMaker AI","Training job"),W("Amazon S3","Model artifact")),L("Register",W("Amazon SageMaker Model Registry","Model package group","Amazon SageMaker AI")),L("Approval",P("Model owner / policy","Approve / reject","user")),L("Deploy",W("AWS CodePipeline","Promotion"),W("Amazon SageMaker AI","Endpoint")),L("Observe",W("Amazon CloudWatch","Runtime metrics"))),
 A("Cross-environment release control","One immutable model version is promoted from experiment to staging and production with explicit metadata and approval status.","SageMaker governed model lifecycle",L("Experiment",P("Data scientist","Candidate model","user")),L("Registry",W("Amazon SageMaker Model Registry","Version + lineage","Amazon SageMaker AI")),L("Staging",P("Pre-production endpoint","Validation","ai")),L("Approval gate",P("Risk / QA","Sign-off","security")),L("Production",W("Amazon SageMaker AI","Production endpoint")))
],
"Amazon SageMaker JumpStart":[
 A("Deploy a pretrained model","A model is selected from JumpStart, configured in Studio/SDK and deployed to a managed SageMaker endpoint for application inference.","SageMaker JumpStart pretrained model deployment",L("Model catalog",W("Amazon SageMaker JumpStart","Pretrained / foundation model","Amazon SageMaker AI")),L("Configure",P("Studio / Python SDK","Instance + model settings","user")),L("Deploy",W("Amazon SageMaker AI","Managed endpoint")),L("Application",P("API / app","Inference request","app")),L("Observe",W("Amazon CloudWatch","Endpoint metrics"))),
 A("Asynchronous foundation-model endpoint","Large requests are staged in S3, processed by a JumpStart-backed async endpoint, and completion notifications drive downstream post-processing.","Generative AI deployments using SageMaker JumpStart",L("Request",W("Amazon S3","Input payload")),L("Endpoint",W("Amazon SageMaker JumpStart","Model package","Amazon SageMaker AI"),W("Amazon SageMaker AI","Async endpoint")),L("Result",W("Amazon S3","Raw output")),L("Completion",W("Amazon SNS","Success / error")),L("Post-process",W("AWS Lambda","Transform / publish")))
],
"Amazon SageMaker Neo":[
 A("Optimize once, deploy to edge","A trained model artifact is compiled by Neo for a target hardware/runtime, then the optimized artifact is packaged for edge deployment.","SageMaker Neo model compilation workflow",L("Model",W("Amazon S3","Trained model artifact")),L("Compile",W("Amazon SageMaker Neo","Target hardware optimization","Amazon SageMaker AI")),L("Optimized artifact",W("Amazon S3","Compiled model")),L("Edge runtime",P("Device / edge host","Low-latency inference","compute")),L("Telemetry",P("Device metrics","Operations feedback","monitor"))),
 A("Cloud inference optimization","Neo compilation targets supported EC2/inference hardware so applications can serve optimized models with lower runtime overhead.","SageMaker Neo cloud deployment pattern",L("Training",W("Amazon SageMaker AI","Model training")),L("Compilation",W("Amazon SageMaker Neo","Framework + target compile","Amazon SageMaker AI")),L("Deployment",W("Amazon SageMaker AI","Endpoint")),L("Clients",P("Application","Inference","app")),ops)
],
"Amazon SageMaker Unified Studio":[
 A("Governed analytics and ML workspace","Users discover governed data/assets, develop analytics or ML work, and publish outputs through one managed workspace tied to enterprise permissions.","SageMaker Unified Studio governed data and AI workspace",L("Users",P("Analyst / data scientist","Workspace session","user")),L("Identity",W("IAM Identity Center","Workforce access")),L("Unified workspace",W("Amazon SageMaker Unified Studio","Projects / assets / tools","Amazon SageMaker AI")),L("Data",W("Amazon S3","Lake data"),W("AWS Glue","Catalog / governance")),L("Compute / AI",W("Amazon Athena","SQL"),W("Amazon SageMaker AI","ML")),ops),
 A("Project-based data product workflow","A project groups members, governed data access and compute so teams can build analytics/ML outputs without broad account-level access.","SageMaker Unified Studio project architecture",L("Team",P("Project members","Role-based access","user")),L("Project",W("Amazon SageMaker Unified Studio","Project boundary","Amazon SageMaker AI")),L("Governed assets",P("Cataloged datasets","Approved data","data")),L("Work",W("Amazon Athena","Queries"),W("Amazon SageMaker AI","Models")),L("Publish",P("Data / model product","Shared output","app")))
],
"AWS Auto Scaling":[
 A("Target-tracking application scaling","CloudWatch metrics drive scaling policies that add/remove EC2 capacity behind a load balancer while health checks protect availability.","AWS Auto Scaling target-tracking pattern",L("Users",P("Clients","Requests","user")),L("Ingress",W("Elastic Load Balancing","ALB")),L("Fleet",W("AWS Auto Scaling","Scaling policy"),W("Amazon EC2","Auto Scaling group")),L("Signals",W("Amazon CloudWatch","CPU / request count")),L("State",W("Amazon RDS","Persistent data")),ops),
 A("Multi-service scaling plan","A scaling plan coordinates supported scalable resources from workload demand instead of scaling every service independently by hand.","AWS Auto Scaling scaling-plan architecture",L("Workload",P("Application stack","Changing demand","app")),L("Metrics",W("Amazon CloudWatch","Demand signals")),L("Scaling control",W("AWS Auto Scaling","Scaling plan")),L("Targets",W("Amazon EC2","Fleet"),W("Amazon ECS","Services"),W("Amazon DynamoDB","Capacity")),ops)
],
"AWS Chatbot":[
 A("ChatOps notifications","Operational alarms and events publish through SNS into chat channels so engineers can receive context without leaving collaboration tools.","AWS Chatbot / Amazon Q Developer in chat applications notification pattern",L("AWS signals",W("Amazon CloudWatch","Alarm"),W("Amazon EventBridge","Operational event")),L("Notification",W("Amazon SNS","Topic")),L("Chat integration",W("AWS Chatbot","Chat channel integration")),L("Collaboration",P("Slack / Teams channel","Alert context","user")),L("Response",P("Engineer","Investigate / run approved command","user"))),
 A("Guarded ChatOps command workflow","A chat user invokes approved AWS operations under configured IAM guardrails; API activity remains auditable.","AWS Chatbot guarded command execution pattern",L("Engineer",P("Chat user","Command / question","user")),L("Chat integration",W("AWS Chatbot","Channel configuration")),L("Permissions",P("IAM role + guardrails","Allowed actions","security")),L("AWS APIs",W("Amazon CloudWatch","Inspect"),W("AWS Systems Manager","Operate")),L("Audit",W("AWS CloudTrail","API history")))
],
"Amazon CloudWatch Logs":[
 A("Central application logging","Workloads emit logs into log groups where retention, queries, metric filters and subscriptions support operations and downstream analytics.","CloudWatch Logs centralized logging architecture",L("Workloads",W("AWS Lambda","Function logs"),W("Amazon ECS","Container logs"),W("Amazon EC2","Agent logs")),L("Log store",W("Amazon CloudWatch Logs","Log groups / streams")),L("Analyze",P("Logs Insights","Interactive query","monitor"),P("Metric filters","Derived metrics","monitor")),L("Route",P("Subscription filter","Streaming export","message"),W("Amazon Kinesis","Downstream stream")),ops),
 A("Security log archive","Sensitive log groups stream copies into a durable central archive for longer retention and independent investigation.","CloudWatch Logs subscription and archive pattern",L("Accounts",P("Workload log groups","Application / security logs","app")),L("Subscription",W("Amazon CloudWatch Logs","Subscription filters")),L("Delivery",W("Amazon Kinesis","Central stream")),L("Archive",W("Amazon S3","Long-term log archive")),L("Investigation",W("Amazon Athena","Historical query"),P("SOC","Forensics","user")))
],
"Amazon CloudWatch Synthetics":[
 A("External canary monitoring","Scheduled canaries exercise public endpoints like a real user and publish availability/latency artifacts and metrics for alerting.","CloudWatch Synthetics canary monitoring",L("Scheduler",W("Amazon CloudWatch Synthetics","Canary schedule")),L("Test path",P("Browser / API script","Synthetic transaction","app")),L("Target",W("Amazon CloudFront","Web endpoint"),W("Amazon API Gateway","API")),L("Evidence",W("Amazon S3","Screenshots / HAR / artifacts"),W("Amazon CloudWatch","Metrics / logs")),L("Alert",W("Amazon SNS","Notify on failure"))),
 A("Private endpoint synthetic test","A canary runs with VPC access to test internal APIs or services that are not reachable from the public internet.","CloudWatch Synthetics VPC canary pattern",L("Canary",W("Amazon CloudWatch Synthetics","VPC-enabled runtime")),L("Private network",P("Private subnets","Security groups / routes","network")),L("Targets",P("Internal ALB","Private app","app"),W("Amazon RDS","Optional dependency")),L("Observe",W("Amazon CloudWatch","Latency / success"),W("Amazon SNS","Alarm notification")))
],
"AWS Cost Anomaly Detection":[
 A("Automated spend anomaly alerting","Cost and usage history is analyzed against monitors; anomalies above configured impact thresholds produce subscription alerts.","AWS Cost Anomaly Detection monitor and subscription pattern",L("Cost data",P("AWS cost and usage","Historical spend","data")),L("Detection",W("AWS Cost Anomaly Detection","Cost monitor + ML baseline")),L("Anomaly",P("Unexpected spend","Impact / root contributors","monitor")),L("Subscription",P("Alert threshold","Daily / immediate","message")),L("Notify",W("Amazon SNS","Automation / email path"),P("FinOps team","Investigate","user"))),
 A("FinOps response workflow","An anomaly event drives investigation and optional automated tagging/containment while billing data remains the source of truth.","Cost anomaly FinOps workflow",L("Signal",W("AWS Cost Anomaly Detection","Anomaly")),L("Route",W("Amazon SNS","Notify")),L("Triage",P("FinOps / owner","Review contributors","user")),L("Automation",W("AWS Lambda","Tag / ticket / guardrail")),L("Evidence",W("AWS Cost Explorer","Analyze spend"),W("AWS CloudTrail","Change history")))
],
"AWS Cost Explorer":[
 A("Interactive FinOps analysis","Cost Explorer groups and filters cost/usage history so teams can identify service, account, tag and usage-type drivers.","AWS Cost Explorer cost analysis workflow",L("Billing data",P("AWS cost and usage","Historical charges","data")),L("Analysis",W("AWS Cost Explorer","Filter / group / forecast")),L("Dimensions",P("Account / service / tag","Cost drivers","data")),L("Users",P("FinOps / owners","Investigate trends","user")),L("Action",P("Budget / optimization decision","Govern spend","app"))),
 A("Cost investigation after an anomaly","Teams pivot from an anomaly or budget signal into Cost Explorer to isolate which service/usage dimension changed.","Cost Explorer anomaly investigation pattern",L("Alert",W("AWS Cost Anomaly Detection","Unexpected spend")),L("Investigate",W("AWS Cost Explorer","Time range + grouping")),L("Correlate",W("AWS CloudTrail","Resource/config changes"),P("Tags / accounts","Ownership","data")),L("Remediate",P("Service owner","Right-size / stop / redesign","user")),ops)
],
"Amazon Managed Grafana":[
 A("Unified operations dashboards","Managed Grafana queries CloudWatch, Prometheus and other approved data sources to give SRE teams one dashboard layer without moving all telemetry into one database.","Amazon Managed Grafana multi-source observability",L("Telemetry",W("Amazon CloudWatch","Metrics / logs"),P("Prometheus workspace","Metrics","monitor"),P("OpenSearch data","Logs / traces","monitor")),L("Workspace",W("Amazon Managed Grafana","Dashboards + alerts")),L("Identity",W("IAM Identity Center","Workspace users")),L("Consumers",P("SRE / platform teams","Visualize / investigate","user")),ops),
 A("Cross-account observability workspace","A central Grafana workspace uses IAM-authorized data-source access to visualize telemetry across multiple workload accounts.","Managed Grafana cross-account data-source pattern",L("Accounts",P("App account A","CloudWatch metrics","app"),P("App account B","Prometheus metrics","app")),L("Access",P("Workspace IAM role","Cross-account read","security")),L("Visualization",W("Amazon Managed Grafana","Central dashboards")),L("Response",P("On-call team","Incident analysis","user"),W("Amazon SNS","Alert channel")))
],
"AWS Service Catalog":[
 A("Governed self-service product","Platform teams publish approved CloudFormation products; end users provision them through portfolios without broad infrastructure permissions.","AWS Service Catalog portfolio and product architecture",L("Platform team",P("Cloud team","Approved template","user"),W("AWS CloudFormation","Product template")),L("Catalog",W("AWS Service Catalog","Portfolio + product")),L("Constraints",P("Launch role / rules","Governance boundary","security")),L("Consumers",P("Application teams","Self-service provision","user")),L("Provisioned product",P("AWS resources","Standardized stack","app")),ops),
 A("Multi-account product distribution","A central portfolio is shared across organization accounts so teams receive consistent approved products while provisioning stays local.","Service Catalog multi-account sharing pattern",L("Central platform",W("AWS Service Catalog","Master portfolio")),L("Organization",P("Shared portfolio","Account distribution","network")),L("Workload account",W("AWS Service Catalog","Local portfolio view")),L("Provision",W("AWS CloudFormation","Launch product")),L("Govern",W("AWS CloudTrail","Audit"),P("Tag / constraint policy","Compliance","security")))
],
"AWS Well-Architected Tool":[
 A("Architecture review workflow","A team records a workload, answers pillar questions, reviews high-risk items and turns improvement items into an action plan.","AWS Well-Architected Tool workload review",L("Architecture",P("Workload design","Current state","app")),L("Review",W("AWS Well-Architected Tool","Pillar questions")),L("Findings",P("High-risk issues","Improvement opportunities","monitor")),L("Plan",P("Owners / milestones","Improvement plan","user")),L("Change",P("Backlog / architecture work","Remediation","app"))),
 A("Continuous architecture governance","Reviews are repeated after material changes so risk status and improvement history stay tied to the evolving workload.","Well-Architected continuous review pattern",L("Delivery change",W("AWS CodePipeline","New release / infra change")),L("Architecture owner",P("Architect / team","Review trigger","user")),L("Assessment",W("AWS Well-Architected Tool","Updated workload answers")),L("Risk backlog",P("High / medium risk","Prioritized work","monitor")),L("Evidence",P("Milestones","Track progress","data")))
],
"IAM":[
 A("Workload role with temporary credentials","An application assumes an IAM role and receives temporary credentials instead of embedding long-lived access keys.","IAM role temporary credential pattern",L("Workload",W("Amazon EC2","Application"),W("AWS Lambda","Function")),L("Identity",P("IAM role","Trust + permissions","security")),L("Credentials",P("STS session","Temporary keys","security")),L("AWS APIs",W("Amazon S3","Objects"),W("Amazon DynamoDB","Data")),L("Audit",W("AWS CloudTrail","Principal + action"))),
 A("Cross-account delegated access","A principal in one account assumes a role in another account through a trust policy and receives only the target role permissions.","IAM cross-account role assumption",L("Source account",P("User / workload","Authenticated principal","user")),L("Trust",P("Role trust policy","Who may assume","security")),L("STS",P("AssumeRole","Temporary session","security")),L("Target account",P("IAM role","Permission policy","security")),L("Resources",W("Amazon S3","Authorized target")),ops)
],
"IAM Access Analyzer":[
 A("External-access analysis","Access Analyzer evaluates resource policies and identifies resources shared outside the zone of trust so security teams can review unintended exposure.","IAM Access Analyzer external access findings",L("Policies",W("Amazon S3","Bucket policy"),W("AWS KMS","Key policy"),P("IAM role","Trust policy","security")),L("Analyzer",W("IAM Access Analyzer","Zone of trust analysis")),L("Finding",P("External access","Public / cross-account","monitor")),L("Review",P("Security engineer","Archive / remediate","user")),L("Fix",W("AWS CloudFormation","Policy update"),ops.nodes[0])),
 A("Policy validation and least privilege","Teams validate IAM policy syntax/security warnings before deployment and refine permissions from observed access.","IAM Access Analyzer policy validation workflow",L("Policy author",P("Developer / platform","IAM policy","user")),L("Validate",W("IAM Access Analyzer","Policy checks")),L("Delivery",W("AWS CloudFormation","Deploy policy")),L("Usage",W("AWS CloudTrail","Observed API calls")),L("Refine",P("Least-privilege policy","Reduce permissions","security")))
],
"IAM Identity Center":[
 A("Workforce access to multiple accounts","Employees authenticate through a corporate IdP and receive permission sets that map to temporary roles in selected AWS accounts.","IAM Identity Center multi-account workforce access",L("Workforce",P("Employees","Sign in","user"),P("Corporate IdP","SAML / directory","internet")),L("Identity Center",W("IAM Identity Center","Users / groups / assignments")),L("Permission sets",P("Role definitions","Account access","security")),L("AWS accounts",P("Dev account","Temporary role","app"),P("Prod account","Restricted role","app")),L("Audit",W("AWS CloudTrail","Role sessions"))),
 A("Workforce access to AWS applications","One workforce identity is assigned to supported AWS applications such as Amazon Q Business without duplicating user stores in each service.","IAM Identity Center application assignment pattern",L("User",P("Employee","SSO","user")),L("Identity source",P("Corporate directory","Groups","internet")),L("Identity Center",W("IAM Identity Center","Application assignment")),L("AWS application",W("Amazon Q Business","Permission-aware experience")),L("Activity",W("AWS CloudTrail","Administrative events"),W("Amazon CloudWatch","Application telemetry")))
],
"Amazon S3 Intelligent-Tiering":[
 A("Automatic access-tier optimization","Objects stay in one S3 bucket while Intelligent-Tiering moves eligible objects among access tiers as observed access patterns change.","S3 Intelligent-Tiering storage-class workflow",L("Applications",P("Producers / consumers","Object access","app")),L("Bucket",W("Amazon S3 Intelligent-Tiering","Objects + monitoring")),L("Access tiers",P("Frequent access","Active objects","storage"),P("Infrequent / archive tiers","Colder objects","storage")),L("Policy",P("Optional archive configuration","Deeper tiers","monitor")),L("Security",W("AWS KMS","Encryption"),ops.nodes[0])),
 A("Unknown-access-pattern data lake","New datasets land directly in Intelligent-Tiering so teams avoid predicting future access frequency while analytics continues against the same S3 keys.","S3 Intelligent-Tiering data-lake pattern",L("Ingest",W("AWS DataSync","Files"),P("Applications","Objects","app")),L("Storage",W("Amazon S3 Intelligent-Tiering","Automatic tiers")),L("Catalog",W("AWS Glue","Metadata")),L("Analytics",W("Amazon Athena","Queries")),L("Observe",P("S3 Storage Lens / metrics","Access trends","monitor")))
],
"Amazon S3 Lifecycle policies":[
 A("Age-based storage lifecycle","Lifecycle rules transition objects to lower-cost classes and expire data according to retention policy without application code moving each object.","S3 Lifecycle transition and expiration workflow",L("Bucket",W("Amazon S3","New objects")),L("Lifecycle engine",P("Lifecycle policy","Age / prefix / tag rules","monitor")),L("Transition",P("Infrequent / archive class","Lower-cost storage","storage")),L("Expire",P("Expiration / version cleanup","Retention end","storage")),L("Govern",P("Records policy","Retention requirement","security"),ops.nodes[0])),
 A("Backup-retention lifecycle","Backup objects keep recent copies in warmer storage and automatically archive or expire older generations.","S3 Lifecycle backup retention pattern",L("Backup producer",P("Database / application","Backup objects","app")),L("Primary bucket",W("Amazon S3","Recent backups")),L("Lifecycle",P("30/90/365-day rules","Example retention stages","monitor")),L("Archive",P("Glacier tiers","Long-term retention","storage")),L("Recovery",P("Restore workflow","Rehydrate when needed","app")))
],
"Amazon S3 Cross-Region Replication":[
 A("Cross-Region resilience copy","Versioned objects written to a source bucket are asynchronously replicated to a destination Region under a replication role and policy.","S3 Cross-Region Replication architecture",L("Application",P("Producer","Put object","app")),L("Source",W("Amazon S3","Versioned source bucket")),L("Replication",P("CRR rule + IAM role","Asynchronous copy","network")),L("Destination",W("Amazon S3","Replica bucket in another Region")),L("Encryption",W("AWS KMS","Source / replica keys"),ops.nodes[0])),
 A("Compliance-owned replica","Replication changes object ownership / encryption in the destination account so a security or compliance account controls the replica copy.","S3 replication cross-account pattern",L("Workload account",W("Amazon S3","Source data")),L("Replication policy",P("Cross-account CRR","Role + bucket policy","security")),L("Compliance account",W("Amazon S3","Owned replica"),W("AWS KMS","Destination key")),L("Consumers",P("DR / audit team","Recovery / evidence","user")),L("Audit",W("AWS CloudTrail","Replication config changes")))
]
};

export function getAipArchitectureOverrides(service:string,_category:string):AipArchitecture[]|undefined{return overrides[service];}
