"use client";

import { Cloud, Database, Globe2, Laptop, Server, Users } from "lucide-react";
import { aipScope, guideAliases } from "../course-data";
import { awsArchitectureIcons, awsIconFallbackSrc, awsIconSrc, findAwsArchitectureIcon } from "../../lib/aws-architecture-icons";
import "./AthenaLearningDetails.css";
import "./AthenaAwsIcons.css";
import "./AipServiceLearningDetails.css";

type Profile={role:string;concepts:string[];integrations:string[];useCases:string[];security:string[];optimize:string[];cost:{name:string;best:string;driver:string}[];compare:string[]};
const profiles:Record<string,Profile>={
"Application Integration":{role:"connect applications without tight coupling",concepts:["Events, messages and workflow state are separate concerns","Producers and consumers should scale independently","Retries, failure handling and idempotency matter","Choose push, pull or orchestration deliberately"],integrations:["AWS Lambda","Amazon S3","Amazon DynamoDB"],useCases:["Decouple application components","Coordinate asynchronous GenAI workflows","Route events to multiple consumers"],security:["Use least-privilege IAM for producers and consumers","Encrypt sensitive payloads and protect downstream targets","Design dead-letter and retry paths for failures","Avoid placing secrets directly in messages or configuration"],optimize:["Batch where the service supports it","Control retries and backoff","Monitor age, failures and throttling","Choose the simplest integration primitive that fits"],cost:[{name:"Requests / events",best:"Variable workloads",driver:"Number and size of operations"},{name:"Workflow / delivery",best:"Multi-step processing",driver:"Transitions, deliveries or execution duration"},{name:"Downstream",best:"End-to-end estimate",driver:"Lambda, storage, logs and target-service usage"}],compare:["Event-driven routing","Queue/buffer","Workflow orchestration"]},
"Compute":{role:"run application or model-supporting compute",concepts:["Choose serverless, managed or instance-based compute","Scale compute separately from durable state","Availability design depends on the execution model","Startup time, runtime duration and concurrency shape design"],integrations:["Amazon S3","Amazon DynamoDB","AWS Lambda"],useCases:["Host inference-supporting APIs","Run background processing","Scale event-driven application logic"],security:["Use workload IAM roles instead of embedded credentials","Keep private workloads in controlled network paths","Patch/manage hosts when the model requires it","Encrypt attached and external data stores"],optimize:["Match compute model to workload duration","Autoscale instead of permanently overprovisioning","Use caching and concurrency controls","Measure CPU, memory, latency and throttling"],cost:[{name:"On-demand",best:"Variable demand",driver:"Runtime or instance usage"},{name:"Committed capacity",best:"Steady workloads",driver:"Longer-term usage commitment"},{name:"Data + operations",best:"Full application",driver:"Storage, transfer, logging and requests"}],compare:["Serverless compute","Containers","Virtual machines"]},
"Containers":{role:"package and operate portable application workloads",concepts:["Images package code and dependencies","Scheduler/orchestrator and runtime are separate layers","Registries store images; compute runs them","Tasks, pods and services are disposable; state should be externalized"],integrations:["Amazon S3","Amazon DynamoDB","AWS Lambda"],useCases:["Run containerized GenAI APIs","Deploy workers and agents","Standardize CI/CD runtime artifacts"],security:["Scan and control container images","Use workload identities/roles","Restrict network paths and security groups","Keep secrets outside images"],optimize:["Right-size CPU and memory","Autoscale services and workers","Keep images small and cache layers","Choose managed/serverless container compute when operations add little value"],cost:[{name:"Control plane",best:"Managed orchestration",driver:"Cluster/service charges where applicable"},{name:"Compute",best:"Running workloads",driver:"vCPU, memory or instances"},{name:"Registry + transfer",best:"Image lifecycle",driver:"Stored images and data movement"}],compare:["ECS","EKS","Fargate"]},
"Customer Engagement":{role:"connect customer interactions with applications and AI",concepts:["Customer channels feed workflows","Routing and automation should preserve context","AI assistance needs governance and human escalation","Operational metrics matter for experience quality"],integrations:["Amazon S3","AWS Lambda","Amazon DynamoDB"],useCases:["AI-assisted customer service","Automated contact workflows","Capture interaction data for analytics"],security:["Protect customer data and recordings","Use least-privilege roles","Define retention and redaction controls","Audit access to sensitive interaction data"],optimize:["Automate repeatable interactions","Measure latency and containment","Cache/reference shared knowledge efficiently","Keep human handoff paths explicit"],cost:[{name:"Usage",best:"Customer interactions",driver:"Channel/minute/request consumption"},{name:"AI features",best:"Assistance",driver:"Model and feature usage"},{name:"Storage/analytics",best:"History",driver:"Recordings, logs and downstream analysis"}],compare:["Human-assisted","Automated","Hybrid"]},
"Database":{role:"store operational state with a fit-for-purpose data model",concepts:["Choose relational, key-value, document, graph or cache by access pattern","Availability and consistency choices affect architecture","Indexes improve reads but add storage/write work","Backups and recovery are part of database design"],integrations:["AWS Lambda","Amazon S3","Amazon DynamoDB"],useCases:["Persist application and agent state","Store metadata and session context","Serve low-latency application reads"],security:["Encrypt at rest and in transit","Use IAM or managed credentials where supported","Keep databases private unless public access is required","Control backup and snapshot access"],optimize:["Design keys/indexes around access patterns","Use caching for repeated hot reads","Monitor connections, latency and capacity","Use serverless/on-demand modes for unpredictable demand where appropriate"],cost:[{name:"Provisioned",best:"Predictable demand",driver:"Instances/capacity + storage"},{name:"Serverless/on-demand",best:"Variable demand",driver:"Consumed capacity/runtime"},{name:"Data lifecycle",best:"Long-lived systems",driver:"Backups, replicas, transfer and indexes"}],compare:["Relational","NoSQL/document/graph","Cache"]},
"Developer Tools":{role:"build, package, deploy and troubleshoot software safely",concepts:["Source/build/deploy are distinct pipeline stages","Infrastructure as code makes environments repeatable","Artifacts should be versioned and immutable","Observability closes the feedback loop"],integrations:["Amazon S3","AWS Lambda","Amazon DynamoDB"],useCases:["Automate GenAI application delivery","Build repeatable cloud environments","Trace and troubleshoot distributed applications"],security:["Protect pipeline roles and credentials","Sign/scan artifacts where appropriate","Separate deployment permissions by environment","Audit changes to build and deployment systems"],optimize:["Cache dependencies and build outputs","Parallelize independent stages","Fail fast on tests/security checks","Keep infrastructure definitions modular"],cost:[{name:"Build/execution",best:"CI/CD activity",driver:"Build minutes, compute and executions"},{name:"Artifacts",best:"Packages",driver:"Storage and transfer"},{name:"Observability",best:"Troubleshooting",driver:"Trace/log ingestion and retention"}],compare:["Build","Deploy","Infrastructure as code"]},
"Machine Learning":{role:"build, customize, govern or consume AI/ML capabilities",concepts:["Separate model capability from application orchestration","Prompt/context, retrieval and model inference are different layers","Evaluation and guardrails belong in the delivery lifecycle","Managed foundation models and custom ML have different operating models"],integrations:["Amazon S3","AWS Lambda","Amazon DynamoDB"],useCases:["Build generative AI applications","Ground models with enterprise data","Evaluate, monitor and operationalize AI workloads"],security:["Control model and data access with IAM","Encrypt training, retrieval and inference data","Treat prompts, retrieved context and outputs as sensitive data","Apply governance, evaluation and human review where risk requires it"],optimize:["Choose the smallest capable model/workload option","Cache reusable results/context when safe","Batch offline workloads","Measure quality, latency and token/compute consumption together"],cost:[{name:"Inference",best:"Online GenAI",driver:"Tokens, requests or provisioned throughput"},{name:"Training/customization",best:"Custom models",driver:"Accelerator/compute time and data processing"},{name:"Retrieval/agents",best:"RAG and orchestration",driver:"Vector/search, tool calls, storage and model calls"}],compare:["Managed foundation models","Custom ML lifecycle","Specialized AI APIs"]},
"Management and Governance":{role:"observe, govern and operate AWS workloads",concepts:["Telemetry, configuration and audit history solve different problems","Governance should be automated where possible","Operational data needs retention and access controls","Alerts should lead to actionable remediation"],integrations:["Amazon S3","AWS Lambda","Amazon DynamoDB"],useCases:["Monitor GenAI applications","Audit configuration and API activity","Automate operational remediation"],security:["Protect logs from alteration","Separate operator and workload permissions","Encrypt operational data","Centralize audit evidence where appropriate"],optimize:["Collect useful signals rather than everything forever","Set retention intentionally","Use metric filters/alarms for actionable conditions","Automate repeatable remediation"],cost:[{name:"Ingestion",best:"Telemetry",driver:"Metrics, logs, traces and events"},{name:"Retention",best:"Audit/history",driver:"Stored operational data"},{name:"Automation",best:"Operations",driver:"Executions plus downstream service usage"}],compare:["Metrics/logs","Audit/configuration","Operations automation"]},
"Migration and Transfer":{role:"move data reliably between environments and AWS",concepts:["Online and offline transfer have different constraints","Bandwidth, change rate and cutover window drive design","Validation matters as much as transfer speed","Incremental synchronization reduces cutover risk"],integrations:["Amazon S3","Amazon RDS","Amazon DynamoDB"],useCases:["Move datasets for AI workloads","Synchronize on-premises and cloud storage","Build managed file-transfer entry points"],security:["Encrypt data in transit","Use scoped service roles","Restrict endpoints and network paths","Validate destination permissions and ownership"],optimize:["Parallelize transfers safely","Compress/filter unnecessary data","Schedule around network constraints","Use incremental sync before final cutover"],cost:[{name:"Transfer service",best:"Managed movement",driver:"Data processed/transferred"},{name:"Network",best:"Hybrid transfer",driver:"Connectivity and egress"},{name:"Destination",best:"After migration",driver:"Storage and requests"}],compare:["Online sync","Managed file transfer","Database/data movement"]},
"Networking and Content Delivery":{role:"connect users, services and networks with controlled traffic paths",concepts:["Routing decides path; security controls decide permission","Public and private connectivity are separate design choices","Edge services reduce latency and protect origins","DNS, load balancing and API entry points solve different layers"],integrations:["AWS Lambda","Amazon S3","Amazon DynamoDB"],useCases:["Expose GenAI APIs securely","Connect private application tiers","Accelerate global application delivery"],security:["Minimize public exposure","Layer network controls with identity","Use TLS and managed certificates","Log and inspect traffic where risk requires it"],optimize:["Cache at the edge where safe","Keep traffic regional when possible","Choose private connectivity for internal dependencies","Design health checks and failover paths"],cost:[{name:"Data transfer",best:"Traffic-heavy apps",driver:"Direction, Region and internet transfer"},{name:"Hourly/capacity",best:"Managed network services",driver:"Endpoints, load balancers or accelerators"},{name:"Requests",best:"Edge/API",driver:"Request count and processing features"}],compare:["Edge delivery","Application entry","Private networking"]},
"Security, Identity, and Compliance":{role:"control identity, secrets, encryption and application protection",concepts:["Authentication and authorization are different","Identity policies and resource policies can combine","Encryption needs key-policy design, not just a checkbox","Preventive, detective and responsive controls complement each other"],integrations:["Amazon S3","AWS Lambda","Amazon DynamoDB"],useCases:["Protect GenAI APIs and data","Manage application identities and secrets","Detect unintended sensitive-data exposure"],security:["Apply least privilege and short-lived credentials","Separate administrative and workload identities","Rotate secrets/keys according to policy","Log security-relevant access and changes"],optimize:["Prefer managed identities over static keys","Centralize reusable guardrails","Automate findings/remediation carefully","Reduce policy sprawl with clear boundaries"],cost:[{name:"Requests/evaluations",best:"Security controls",driver:"API calls, rules or evaluations"},{name:"Protected resources",best:"Managed protection",driver:"Resources/data inspected or protected"},{name:"Logging",best:"Evidence",driver:"Security telemetry retention and analysis"}],compare:["Identity/access","Encryption/secrets","Detection/protection"]},
"Storage":{role:"store application, model and data-lake content durably",concepts:["Object, block and file storage have different access semantics","Durability, availability and performance are separate properties","Lifecycle and replication should match recovery requirements","Request patterns can matter as much as stored capacity"],integrations:["AWS Lambda","Amazon DynamoDB","Amazon S3"],useCases:["Store prompts, documents and model artifacts","Build retrieval/data-lake repositories","Persist application files and shared datasets"],security:["Block unintended public access","Encrypt sensitive data","Use least-privilege bucket/file/volume permissions","Protect replicas and backups too"],optimize:["Choose the correct storage class/tier","Use lifecycle automation","Avoid unnecessary cross-Region transfer","Design object/key layout for workload access"],cost:[{name:"Capacity",best:"Stored data",driver:"GB-month by storage class/tier"},{name:"Requests",best:"Active workloads",driver:"Reads, writes and retrieval operations"},{name:"Lifecycle/transfer",best:"Long-term data",driver:"Retrieval, replication and network movement"}],compare:["Object","Block","File"]}
};

const normalize=(v:string)=>v.toLowerCase().replace(/\([^)]*\)/g," ").replace(/\b(amazon|aws)\b/g," ").replace(/[^a-z0-9]+/g," ").trim();
const entries=aipScope.flatMap(category=>category.services.map(service=>({service,category:category.title,alias:guideAliases[service]})));
const resolveEntry=(name:string)=>entries.find(x=>normalize(x.service)===normalize(name)||!!x.alias&&normalize(x.alias)===normalize(name));
export const aipDetailServices=new Set(entries.flatMap(x=>[x.service,x.alias].filter(Boolean) as string[]));
export const hasAipLearningDetails=(name:string)=>!!resolveEntry(name);
export const getAipLearningMeta=(name:string)=>{const e=resolveEntry(name);return e?{service:e.service,category:e.category,sections:["overview","concepts","architectures","use-cases","security","optimization","cost-models","comparison","memory-hook"]}:null};

const awsIcon=(label:string)=>findAwsArchitectureIcon(label)||awsArchitectureIcons.awsCloud;
const AwsNode=({label,sub,featured=false}:{label:string;sub:string;featured?:boolean})=>{const icon=awsIcon(label);return <div className={`dynamic-node aws ${featured?"featured":""}`}><div className="aws-icon-disc"><img src={awsIconSrc(icon)} data-fallback={awsIconFallbackSrc(icon)} onError={e=>{const f=e.currentTarget.dataset.fallback;if(f&&e.currentTarget.src!==f)e.currentTarget.src=f;else e.currentTarget.onerror=null}} alt={`${label} AWS architecture icon`}/></div><strong>{label}</strong><small>{sub}</small></div>};
const PublicNode=({kind,label,sub}:{kind:"user"|"internet"|"app"|"data";label:string;sub:string})=>{const Icon=kind==="user"?Users:kind==="internet"?Globe2:kind==="data"?Database:Laptop;return <div className="dynamic-node public"><div className="public-icon-disc"><Icon size={34}/></div><strong>{label}</strong><small>{sub}</small></div>};
const Architecture=({n,title,note,service,integrations,variant}:{n:number;title:string;note:string;service:string;integrations:string[];variant:1|2})=><section className="architecture-stage dynamic-architecture"><div className="section-cap"><div><p>ARCHITECTURE {String(n).padStart(2,"0")}</p><h3>{title}</h3></div><span>{note}</span></div><div className={`dynamic-map variant-${variant}`}><div className="map-left">{variant===1?<><PublicNode kind="user" label="Users / applications" sub="Requests • events • jobs"/><PublicNode kind="data" label="Enterprise data" sub="Documents • state • context"/></>:<><PublicNode kind="internet" label="External / hybrid" sub="Users • SaaS • on-prem"/><PublicNode kind="app" label="Application tier" sub="API • worker • agent"/></>}</div><div className="map-arrow">→</div><AwsNode label={service} sub={variant===1?"Primary service capability":"Production workload boundary"} featured/><div className="map-branches">{integrations.map((x,i)=><div className="branch" key={`${x}-${i}`}><span>↗</span><AwsNode label={x} sub={i===0?"Data / integration":i===1?"Processing / state":"Supporting AWS service"}/></div>)}</div></div></section>;

export default function AipServiceLearningDetails({serviceName,summary}:{serviceName:string;summary?:string}){const entry=resolveEntry(serviceName);if(!entry)return null;const p=profiles[entry.category]||profiles["Management and Governance"];const service=entry.service;const slug=normalize(service).replace(/\s+/g,"-");const related=p.integrations.filter(x=>normalize(x)!==normalize(service)).slice(0,3);while(related.length<3)related.push(["Amazon S3","AWS Lambda","Amazon DynamoDB"][related.length]);return <div className="service-knowledge aip-shared-learning" id={`${slug}-learning-details`} data-service={service} data-category={entry.category} data-search-scope="aws-service-learning">
<div className="knowledge-intro"><div><p className="knowledge-kicker">VISUAL DEEP DIVE • {entry.category.toUpperCase()}</p><h2>{service}</h2><p>{summary||`${service} helps AWS workloads ${p.role}.`} This page uses one reusable service definition across certification courses and service search.</p></div><div className="knowledge-facts"><span><b>01</b>{entry.category}</span><span><b>02</b>Architecture</span><span><b>03</b>Practical use</span><span><b>04</b>Cost lens</span></div></div>
<nav className="knowledge-jumps"><a href={`#${slug}-concepts`}>Concepts</a><a href={`#${slug}-architecture`}>Architectures</a><a href={`#${slug}-use-cases`}>Use cases</a><a href={`#${slug}-security`}>Security</a><a href={`#${slug}-cost`}>Cost</a><a href={`#${slug}-memory`}>Exam hook</a></nav>
<div className="knowledge-grid" id={`${slug}-concepts`}>{p.concepts.map((x,i)=><section className="knowledge-card" key={x}><div className="knowledge-card-title"><span>{["◎","⌁","◆","⚡"][i]}</span><h3>{["Service role","Architecture decision","Operational behavior","Certification lens"][i]}</h3></div><div className="knowledge-card-body"><p>{x}</p>{i===0&&<p><b>{service}</b> is primarily used to {p.role}.</p>}</div></section>)}</div>
<div id={`${slug}-architecture`}><Architecture n={1} title={`${service}: application integration map`} note="Branching view: callers, data and AWS integrations are independent paths." service={service} integrations={related} variant={1}/><Architecture n={2} title="Production workload pattern" note="Not a single pipeline: external access, application logic and supporting AWS services can scale independently." service={service} integrations={[related[1],related[0],related[2]]} variant={2}/></div>
<p className="use-case-label" id={`${slug}-use-cases`}>PRACTICAL USE CASES</p><div className="practical-grid">{p.useCases.map((x,i)=><article className="practical-card" key={x}><h4>{String(i+1).padStart(2,"0")} • {x}</h4><p>Use {service} as the {i===0?"primary capability":i===1?"managed building block":"supporting service"} while keeping data, identity, observability and failure handling explicit.</p></article>)}</div>
<div className="knowledge-grid"><section className="knowledge-card" id={`${slug}-security`}><div className="knowledge-card-title"><span>◆</span><h3>Security & governance</h3></div><div className="knowledge-card-body"><ol className="rank-list">{p.security.map(x=><li key={x}>{x}</li>)}</ol></div></section><section className="knowledge-card"><div className="knowledge-card-title"><span>⚡</span><h3>Design & optimization</h3></div><div className="knowledge-card-body"><ol className="rank-list">{p.optimize.map(x=><li key={x}>{x}</li>)}</ol></div></section></div>
<section className="cost-board" id={`${slug}-cost`}><div className="section-cap"><div><p>COST MODEL</p><h3>How to reason about the bill</h3></div><span>Use cost drivers for certification decisions • verify exact regional prices separately</span></div><div className="cost-model-grid">{p.cost.map((x,i)=><div className={`cost-model ${i===0?"recommended":""}`} key={x.name}><b>{x.name}</b><strong>{x.best}</strong><span>{x.driver}</span></div>)}</div></section>
<section className="compare-board"><div className="section-cap"><div><p>CHOOSE THE RIGHT MODEL</p><h3>What to compare before selecting {service}</h3></div></div><div className="compare-columns">{p.compare.map((x,i)=><div className={i===0?"recommended":""} key={x}><b>{i===0?service:`ALTERNATIVE ${i}`}</b><strong>{x}</strong></div>)}</div></section>
<section className="exam-strip" id={`${slug}-memory`}><div><p>MEMORY HOOK</p><h3>{service} = {p.role}</h3></div><div className="exam-tips"><span><b>01</b>Know the service's primary responsibility.</span><span><b>02</b>Recognize the integrations around it, not only a linear pipeline.</span><span><b>03</b>Separate security, scaling and durability decisions.</span><span><b>04</b>Choose by workload pattern and cost driver.</span></div></section></div>}
