"use client";

import { Activity, BrainCircuit, Cloud, Database, FileText, Globe2, HardDrive, KeyRound, Laptop, MessageSquare, Network, Server, Shield, Users } from "lucide-react";
import { aipScope, guideAliases } from "../course-data";
import { awsArchitectureIcons, awsIconFallbackSrc, awsIconSrc, findAwsArchitectureIcon } from "../../lib/aws-architecture-icons";
import "./AthenaLearningDetails.css";
import "./AthenaAwsIcons.css";
import "./AipServiceLearningDetails.css";

type Kind="user"|"internet"|"app"|"data"|"security"|"file"|"network"|"storage"|"ai"|"message"|"monitor";
type Node={label:string;sub:string;kind?:Kind};
type Arch={title:string;note:string;left:Node[];center:Node;right:Node[]};
type Entry={service:string;category:string;alias?:string};

const normalize=(v:string)=>v.toLowerCase().replace(/\([^)]*\)/g," ").replace(/\b(amazon|aws)\b/g," ").replace(/[^a-z0-9]+/g," ").trim();
const entries:Entry[]=aipScope.flatMap(category=>category.services.map(service=>({service,category:category.title,alias:guideAliases[service]})));
const resolveEntry=(name:string)=>entries.find(x=>normalize(x.service)===normalize(name)||!!x.alias&&normalize(x.alias)===normalize(name));
export const aipDetailServices=new Set(entries.flatMap(x=>[x.service,x.alias].filter(Boolean) as string[]));
export const hasAipLearningDetails=(name:string)=>!!resolveEntry(name);
export const getAipLearningMeta=(name:string)=>{const e=resolveEntry(name);return e?{service:e.service,category:e.category,sections:["overview","concepts","architectures","use-cases","security","optimization","cost-models","comparison","memory-hook"]}:null};

const aws=(label:string,sub:string):Node=>({label,sub});
const pub=(kind:Kind,label:string,sub:string):Node=>({kind,label,sub});
const A=(title:string,note:string,left:Node[],center:Node,right:Node[]):Arch=>({title,note,left,center,right});

function architectureFor(service:string,category:string):Arch[]{
 const s=service.toLowerCase();
 if(service==="Amazon AppFlow")return[
  A("SaaS-to-lake ingestion","AppFlow moves selected SaaS data into AWS without custom transfer code.",[pub("internet","SaaS applications","Salesforce • SAP • other sources")],aws("Amazon AppFlow","Managed flow + field mapping"),[aws("Amazon S3","Analytics landing zone"),aws("Amazon Redshift","Warehouse target")]),
  A("Bidirectional business integration","Flows can be scheduled or event-driven and can transform fields in transit.",[pub("app","Business application","Source records"),pub("security","OAuth / connection","Credential boundary")],aws("Amazon AppFlow","Connector + mapping"),[pub("data","Destination system","CRM / analytics"),pub("monitor","Flow metrics","Failures + throughput")])];
 if(service==="AWS AppConfig")return[
  A("Safe runtime configuration","Applications retrieve configuration independently from code deployment.",[pub("user","Platform team","Create config"),pub("file","Hosted / S3 config","Parameters + feature flags")],aws("AWS AppConfig","Validate + deploy configuration"),[aws("AWS Lambda","Runtime consumer"),aws("Amazon EC2","Application fleet"),pub("monitor","Deployment alarms","Automatic rollback")]),
  A("Feature-flag rollout","Gradual deployments reduce blast radius when behavior changes.",[pub("user","Release owner","Flag change")],aws("AWS AppConfig","Deployment strategy"),[pub("app","5% canary","Early cohort"),pub("app","50% rollout","Expanded cohort"),pub("app","100% rollout","Steady state")])];
 if(service==="Amazon EventBridge")return[
  A("Event-bus routing","Rules select matching events and independently route them to targets.",[pub("app","AWS / custom producers","Domain events"),pub("internet","SaaS source","Partner events")],aws("Amazon EventBridge","Event bus + rules"),[aws("AWS Lambda","Function target"),aws("Amazon SQS","Buffered target"),aws("AWS Step Functions","Workflow target")]),
  A("Scheduled GenAI automation","Scheduler/event rules can trigger asynchronous workflows without polling.",[pub("monitor","Schedule / event","Trigger")],aws("Amazon EventBridge","Route by pattern"),[aws("AWS Step Functions","Orchestrate"),aws("Amazon S3","Store output"),pub("monitor","DLQ / retry","Failure handling")])];
 if(service==="Amazon SNS")return[
  A("Pub/sub fan-out","One publication fans out to independent subscribers.",[pub("app","Publisher","Business event")],aws("Amazon SNS","Topic"),[aws("Amazon SQS","Queue subscriber"),aws("AWS Lambda","Function subscriber"),pub("message","Email / HTTPS","Human or external endpoint")]),
  A("Durable fan-out","SNS plus SQS isolates consumers that run at different speeds.",[aws("Amazon S3","Object event"),pub("app","Application","Domain event")],aws("Amazon SNS","Fan-out"),[aws("Amazon SQS","Consumer A buffer"),aws("Amazon SQS","Consumer B buffer"),pub("monitor","Delivery status","Retries / failures")])];
 if(service==="Amazon SQS")return[
  A("Buffered worker queue","The queue absorbs traffic bursts and lets workers scale independently.",[pub("app","Producers","Jobs / requests")],aws("Amazon SQS","Standard or FIFO queue"),[aws("AWS Lambda","Elastic consumers"),pub("message","Dead-letter queue","Poison messages"),pub("monitor","Queue age","Backlog signal")]),
  A("Ordered GenAI job processing","FIFO queues preserve ordering inside message groups while deduplication reduces repeats.",[pub("user","GenAI application","Queued work")],aws("Amazon SQS","FIFO queue"),[aws("AWS Lambda","Controlled workers"),aws("Amazon DynamoDB","Job status"),aws("Amazon S3","Generated artifacts")])];
 if(service==="AWS Step Functions")return[
  A("GenAI workflow orchestration","A state machine coordinates model calls, tools, branches and retries.",[pub("app","API / event","Start execution")],aws("AWS Step Functions","State machine"),[aws("AWS Lambda","Tool execution"),aws("Amazon Bedrock","Model inference"),aws("Amazon DynamoDB","Workflow state")]),
  A("Human approval workflow","Long-running state can pause for callbacks instead of holding compute open.",[pub("user","Requester","Submit task")],aws("AWS Step Functions","Wait + choice states"),[pub("message","Approval notification","Send token"),pub("user","Human reviewer","Callback"),pub("app","Final action","Continue / reject")])];
 if(service==="AWS App Runner")return[
  A("Managed web application","App Runner builds or pulls an image and exposes an autoscaled HTTPS service.",[pub("file","Source repository","Application code"),aws("Amazon ECR","Container image")],aws("AWS App Runner","Build + deploy + autoscale"),[pub("user","Internet clients","HTTPS"),aws("Amazon RDS","Application data"),pub("monitor","Service metrics","Latency + instances")]),
  A("GenAI API service","A stateless container can call managed AI and data services while App Runner handles the web tier.",[pub("user","Client application","REST request")],aws("AWS App Runner","API container"),[aws("Amazon Bedrock","Model call"),aws("Amazon S3","Documents"),aws("AWS Secrets Manager","API secrets")])];
 if(service==="Amazon EC2")return[
  A("Stateful application tier","EC2 gives OS-level control while load balancing and durable storage remain separate.",[pub("user","Users","HTTPS"),aws("Elastic Load Balancing","Distribute traffic")],aws("Amazon EC2","Application instances"),[aws("Amazon EBS","Block storage"),aws("Amazon RDS","Database"),pub("monitor","CloudWatch","Host + app metrics")]),
  A("GPU/self-managed model host","Choose EC2 when the workload needs instance, accelerator or OS control.",[aws("Amazon S3","Model artifacts"),pub("network","Private VPC","Controlled access")],aws("Amazon EC2","GPU / custom runtime"),[pub("app","Inference endpoint","Application traffic"),aws("Amazon EBS","Local model data"),pub("security","IAM role","AWS API access")])];
 if(service==="AWS Lambda")return[
  A("Event-driven serverless function","Multiple AWS event sources invoke short-lived stateless compute.",[aws("Amazon API Gateway","Synchronous request"),aws("Amazon S3","Object event")],aws("AWS Lambda","Function"),[aws("Amazon DynamoDB","State"),aws("Amazon SQS","Async work"),pub("monitor","CloudWatch","Logs + metrics")]),
  A("GenAI tool function","Lambda works well as small agent tools and integration glue.",[aws("Amazon Bedrock","Agent / model"),pub("app","Application","Tool request")],aws("AWS Lambda","Business action"),[pub("app","Enterprise API","Action target"),aws("AWS Secrets Manager","Credentials"),pub("monitor","X-Ray","Trace")])];
 if(service==="AWS Lambda@Edge")return[
  A("Viewer-request edge logic","Lambda@Edge executes on CloudFront events close to viewers.",[pub("user","Global viewers","HTTPS")],aws("Amazon CloudFront","Distribution"),[aws("AWS Lambda","Lambda@Edge event"),aws("Amazon S3","Origin"),pub("security","Header / auth logic","Request mutation")]),
  A("Origin-selection pattern","Edge code can rewrite requests or choose origins before regional traffic begins.",[aws("Amazon Route 53","DNS"),pub("user","Users","Request")],aws("Amazon CloudFront","Edge entry"),[aws("AWS Lambda","Origin-request logic"),pub("app","Origin A","Primary"),pub("app","Origin B","Alternate")])];
 if(service==="AWS Outposts")return[
  A("AWS infrastructure on premises","Outposts extends AWS compute/storage APIs into a customer site with a Region control plane.",[pub("app","Local workloads","Low-latency / residency"),pub("network","Customer network","LAN")],aws("AWS Outposts","On-prem AWS capacity"),[aws("Amazon EC2","Local instances"),aws("Amazon EBS","Local block storage"),pub("internet","AWS Region","Control plane + services")]),
  A("Hybrid application tier","Keep latency-sensitive compute local while consuming regional managed services where appropriate.",[pub("user","Site users","Local traffic")],aws("AWS Outposts","Local application tier"),[pub("data","On-prem systems","Local dependency"),aws("Amazon S3","Regional object data"),pub("monitor","Regional operations","Management + monitoring")])];
 if(service==="AWS Wavelength")return[
  A("Ultra-low-latency mobile edge","Wavelength places AWS compute inside telecom 5G networks.",[pub("user","5G device","Mobile request"),pub("network","Carrier 5G network","Low-latency path")],aws("AWS Wavelength","Wavelength Zone"),[aws("Amazon EC2","Edge compute"),pub("internet","AWS Region","Regional services")]),
  A("Edge inference","Latency-sensitive preprocessing/inference can run near users while durable data remains regional.",[pub("user","Camera / device","Realtime data")],aws("AWS Wavelength","Edge application"),[pub("ai","Inference runtime","Immediate response"),aws("Amazon S3","Regional archive"),pub("monitor","Telemetry","Operations")])];
 if(service==="Amazon ECR")return[
  A("Container image supply chain","CI builds an image, scans it and pushes immutable versions to ECR.",[pub("file","Source code","Commit"),aws("AWS CodeBuild","Build image")],aws("Amazon ECR","Private registry"),[aws("Amazon ECS","Pull image"),aws("Amazon EKS","Pull image"),pub("security","Image scanning","Vulnerability findings")]),
  A("Cross-account deployment","Repository policies and replication distribute approved images to runtime accounts/Regions.",[pub("app","Build account","Signed image")],aws("Amazon ECR","Versioned repository"),[pub("app","Prod account","Deployment"),pub("storage","Replication","Other Region"),pub("monitor","Lifecycle policy","Expire old images")])];
 if(service==="Amazon ECS")return[
  A("ECS service architecture","ECS schedules tasks while the compute layer can be Fargate or EC2.",[aws("Elastic Load Balancing","Application entry"),aws("Amazon ECR","Container image")],aws("Amazon ECS","Service + task scheduler"),[aws("AWS Fargate","Serverless tasks"),aws("Amazon EC2","EC2 capacity"),pub("monitor","CloudWatch","Task metrics/logs")]),
  A("Asynchronous worker service","Queue depth can drive ECS task scaling for long-running container workers.",[aws("Amazon SQS","Work backlog")],aws("Amazon ECS","Worker service"),[aws("Amazon S3","Input/output"),aws("Amazon DynamoDB","Job state"),pub("security","Task role","Least privilege")])];
 if(service==="Amazon EKS")return[
  A("Managed Kubernetes cluster","EKS manages the Kubernetes control plane while nodes/pods remain your workload boundary.",[aws("Amazon ECR","Images"),pub("user","Platform team","kubectl / GitOps")],aws("Amazon EKS","Kubernetes control plane"),[aws("Amazon EC2","Managed node groups"),aws("AWS Fargate","Fargate pods"),pub("monitor","Observability","Pod / cluster telemetry")]),
  A("GenAI microservices on Kubernetes","Independent pods can host gateways, agents and workers with Kubernetes-native scaling.",[pub("user","API clients","HTTPS")],aws("Amazon EKS","Ingress + services"),[pub("ai","Agent pods","Orchestration"),pub("app","Worker pods","Tools"),aws("Amazon Bedrock","Managed model API")])];
 if(service==="AWS Fargate")return[
  A("Serverless container tasks","Fargate supplies task/pod compute so you do not manage worker instances.",[aws("Amazon ECR","Container image"),pub("app","ECS / EKS scheduler","Task specification")],aws("AWS Fargate","vCPU + memory runtime"),[pub("app","Application task","Stateless workload"),aws("Amazon S3","Durable data"),pub("monitor","CloudWatch","Logs/metrics")]),
  A("Burst worker fleet","Queue-backed Fargate tasks fit jobs that need containers but not persistent hosts.",[aws("Amazon SQS","Queued jobs")],aws("AWS Fargate","Autoscaled workers"),[aws("Amazon S3","Artifacts"),aws("Amazon DynamoDB","Status"),pub("security","Task role","AWS access")])];
 if(service==="Amazon Connect")return[
  A("AI-enabled contact center","Connect handles voice/chat sessions and can invoke bots/functions during customer journeys.",[pub("user","Customer","Voice / chat")],aws("Amazon Connect","Contact flows"),[aws("Amazon Lex","Conversational bot"),aws("AWS Lambda","Business lookup"),pub("app","Agent desktop","Human support")]),
  A("Conversation analytics","Contact recordings/transcripts can feed downstream analytics and quality workflows.",[aws("Amazon Connect","Contact event"),pub("message","Transcript / recording","Interaction data")],aws("Amazon S3","Durable contact data"),[aws("Amazon Transcribe","Speech to text"),pub("ai","Analytics / QA","Insights")])];
 if(service==="Amazon Aurora")return[
  A("Highly available relational application","Aurora separates distributed storage from DB instances and replicates across AZs.",[pub("app","Application tier","SQL")],aws("Amazon Aurora","Writer + reader instances"),[pub("data","Aurora cluster storage","Multi-AZ copies"),pub("monitor","Reader endpoint","Scale reads"),pub("storage","Backups","Point-in-time recovery")]),
  A("GenAI application metadata","Keep transactional user/session metadata relational while documents and model inference remain separate.",[pub("app","GenAI API","Transactions")],aws("Amazon Aurora","Relational metadata"),[aws("Amazon S3","Documents"),aws("Amazon Bedrock","Inference"),pub("security","Secrets Manager","DB credentials")])];
 if(service==="Amazon DocumentDB")return[
  A("Document application store","Applications use MongoDB-compatible APIs against managed document clusters.",[pub("app","Application","JSON-like documents")],aws("Amazon DocumentDB","Document cluster"),[pub("data","Cluster storage","Replicated data"),pub("monitor","Read replicas","Scale reads"),pub("security","VPC + TLS","Private access")]),
  A("Conversation/document metadata","Flexible nested records can hold application metadata while large objects remain in S3.",[pub("app","Agent service","Session/document metadata")],aws("Amazon DocumentDB","Document records"),[aws("Amazon S3","Large objects"),aws("AWS Lambda","Event processing")])];
 if(service==="Amazon DynamoDB"||service==="Amazon DynamoDB Streams")return[
  A(service.includes("Streams")?"Change-data event stream":"Serverless key-value state","Partition-key design drives scale; Streams exposes item-level changes for event processing.",[pub("app","Application","Key-based reads/writes")],aws("Amazon DynamoDB",service.includes("Streams")?"Table + change stream":"Table + indexes"),[aws("AWS Lambda","Stream consumer"),pub("data","Global tables","Multi-Region option"),pub("monitor","On-demand / provisioned","Capacity model")]),
  A("GenAI session + job state","Low-latency state is kept separate from documents and model inference.",[pub("user","GenAI application","Session/job updates")],aws("Amazon DynamoDB","Session and status table"),[aws("Amazon S3","Documents/results"),aws("Amazon Bedrock","Model calls"),aws("Amazon EventBridge","State-change events")])];
 if(service==="Amazon ElastiCache")return[
  A("Low-latency cache-aside","Applications check the cache before reading the database and populate misses.",[pub("app","Application","Read request")],aws("Amazon ElastiCache","Redis / Valkey / Memcached cache"),[aws("Amazon RDS","System of record"),pub("monitor","TTL / eviction","Freshness"),pub("monitor","Hit ratio","Performance")]),
  A("GenAI response/session cache","Cache reusable or short-lived data while keeping durable truth elsewhere.",[pub("app","GenAI API","Repeated request")],aws("Amazon ElastiCache","Hot context / response cache"),[aws("Amazon Bedrock","Avoidable inference"),aws("Amazon DynamoDB","Durable session state")])];
 if(service==="Amazon Neptune")return[
  A("Knowledge graph","Applications traverse connected entities using graph query languages.",[pub("data","Entities + relationships","Graph load")],aws("Amazon Neptune","Graph database"),[pub("app","Graph query API","Traversals"),pub("ai","RAG / reasoning","Relationship context"),pub("monitor","Read replicas","Scale queries")]),
  A("Fraud / recommendation graph","Graph traversal discovers multi-hop relationships that are awkward in relational joins.",[pub("app","Accounts / devices","Relationship events")],aws("Amazon Neptune","Connected graph"),[pub("ai","Path analysis","Suspicious chains"),pub("app","Recommendation service","Related entities")])];
 if(service==="Amazon RDS")return[
  A("Managed relational database","RDS manages database infrastructure while applications retain schema/query design responsibility.",[pub("app","Application tier","SQL")],aws("Amazon RDS","Managed DB instance"),[pub("data","Multi-AZ standby","Availability"),pub("data","Read replica","Read scaling"),pub("storage","Automated backups","Recovery")]),
  A("Private application database","Keep database endpoints private and provide credentials through managed secrets.",[pub("network","Private subnets","Application path")],aws("Amazon RDS","Private endpoint"),[aws("AWS Secrets Manager","Rotated credentials"),pub("monitor","CloudWatch","DB metrics"),pub("storage","Snapshots","Backup")])];

 // Developer tools: each service gets a workflow matching its real boundary.
 if(service==="AWS Amplify")return[A("Full-stack web delivery","Amplify connects source control to build/hosting and managed app backends.",[pub("file","Git repository","Frontend/full-stack code")],aws("AWS Cloud","Amplify build + hosting"),[aws("Amazon CloudFront","Edge delivery"),aws("Amazon Cognito","Authentication"),aws("AWS AppSync","GraphQL/data API")]),A("GenAI web app","The UI can call a secured API while AI/data services stay behind the application boundary.",[pub("user","Web user","Browser")],aws("AWS Cloud","Amplify hosted app"),[aws("Amazon API Gateway","API"),aws("Amazon Bedrock","Inference"),aws("Amazon S3","User documents")])];
 if(service==="AWS CDK")return[A("Infrastructure as code synthesis","Developers define constructs in code; CDK synthesizes a CloudFormation template.",[pub("user","Developer","TypeScript/Python/etc."),pub("file","CDK app","Constructs")],aws("AWS CDK","Synthesize"),[aws("AWS CloudFormation","Deploy stack"),aws("AWS Cloud","AWS resources")]),A("Reusable platform constructs","Teams package approved architecture patterns as constructs and deploy them consistently.",[pub("user","Platform team","Construct library")],aws("AWS CDK","Reusable L2/L3 constructs"),[pub("file","Application stacks","Consume constructs"),aws("AWS CloudFormation","Change sets"),pub("monitor","CI pipeline","Validate/deploy")])];
 if(service==="AWS CLI")return[A("Operator-to-AWS API path","CLI is a signed API client; it does not host workloads or store application data.",[pub("user","Engineer / automation","Shell command"),pub("file","CLI profile/config","Region + output settings")],aws("AWS CLI","AWS API client"),[aws("AWS IAM","Credentials / authorization"),aws("AWS Cloud","Target service API"),aws("AWS CloudTrail","API audit")]),A("CI/CD automation with temporary credentials","Automation should use short-lived role credentials rather than long-lived keys.",[pub("app","CI runner","aws ... command"),pub("security","OIDC / role session","Temporary credentials")],aws("AWS CLI","Scripted API calls"),[aws("Amazon S3","Artifact operations"),aws("AWS CloudFormation","Deploy stack"),aws("Amazon ECR","Push/pull images")])];
 if(service==="AWS CloudFormation")return[A("Declarative stack deployment","A template defines desired state; CloudFormation creates resources in dependency order.",[pub("file","YAML / JSON template","Resources + parameters")],aws("AWS CloudFormation","Stack engine"),[aws("AWS Cloud","AWS resources"),pub("monitor","Stack events","Create/update status"),pub("security","Execution role","Deployment permissions")]),A("Change-controlled infrastructure","Change sets preview modifications before production stack updates.",[pub("user","Engineer","Template update")],aws("AWS CloudFormation","Change set"),[pub("file","Diff / preview","Review"),aws("AWS Cloud","Updated stack"),pub("monitor","Drift detection","Out-of-band change")])];
 if(service==="AWS CodeArtifact")return[A("Private package repository","Builds resolve approved dependencies from a managed package domain/repository.",[pub("user","Developers","npm/pip/maven clients"),pub("internet","Upstream public repo","External packages")],aws("AWS CodeArtifact","Private package repository"),[aws("AWS CodeBuild","CI dependency restore"),pub("app","Internal packages","Versioned artifacts")]),A("Controlled package supply chain","Upstream connections and repository policies create a governed dependency boundary.",[pub("file","Internal library","Publish package")],aws("AWS CodeArtifact","Domain + repositories"),[pub("app","Dev teams","Consume package"),pub("security","IAM policies","Publish/read controls"),pub("monitor","Package versions","Retention/governance")])];
 if(service==="AWS CodeBuild")return[A("Managed build pipeline","CodeBuild provisions ephemeral build environments and emits artifacts/images.",[pub("file","Source repository","Commit"),pub("file","buildspec.yml","Build steps")],aws("AWS CodeBuild","Ephemeral build environment"),[aws("Amazon S3","Build artifact"),aws("Amazon ECR","Container image"),pub("monitor","Build logs","CloudWatch")]),A("GenAI application CI","Tests, dependency checks and image builds happen before deployment.",[pub("app","Pull request","Trigger")],aws("AWS CodeBuild","Test + package"),[pub("security","Secrets Manager","Build secrets"),aws("AWS CodePipeline","Next stage"),pub("monitor","Reports","Test results")])];
 if(service==="AWS CodeDeploy")return[A("Automated deployment","CodeDeploy coordinates application revisions onto supported compute targets.",[aws("Amazon S3","Revision bundle"),pub("file","AppSpec","Lifecycle hooks")],aws("AWS CodeDeploy","Deployment controller"),[aws("Amazon EC2","In-place / blue-green"),aws("AWS Lambda","Traffic shifting"),aws("Amazon ECS","Blue/green service")]),A("Safe production rollout","Health validation and rollback policies limit deployment blast radius.",[pub("app","Approved release","Revision")],aws("AWS CodeDeploy","Canary / linear / blue-green"),[pub("monitor","Health checks","Validate"),pub("app","New version","Promote"),pub("app","Old version","Rollback target")])];
 if(service==="AWS CodePipeline")return[A("Continuous delivery orchestration","Pipeline stages connect source, build, test and deployment services.",[pub("file","Source control","Commit")],aws("AWS CodePipeline","Stage orchestration"),[aws("AWS CodeBuild","Build/test"),aws("AWS CodeDeploy","Deploy"),pub("user","Manual approval","Governed promotion")]),A("Infrastructure + application pipeline","One pipeline can validate IaC and application artifacts before separate deployments.",[pub("file","App + IaC repository","Change")],aws("AWS CodePipeline","Promotion flow"),[aws("AWS CloudFormation","Infrastructure"),aws("Amazon ECR","Container artifact"),pub("monitor","Release events","Audit/notification")])];
 if(service==="Kiro")return[A("Spec-driven development","Kiro turns requirements/specifications into implementation work inside the developer workflow.",[pub("user","Developer","Intent / requirements"),pub("file","Specs","Requirements + design")],pub("app","Kiro","AI-assisted IDE workflow"),[pub("file","Application code","Implementation"),pub("file","Tests / tasks","Verification")]),A("Repository-to-delivery workflow","AI assistance remains upstream of normal source control and CI/CD controls.",[pub("user","Developer","Code change")],pub("app","Kiro","Generate / refactor / review"),[pub("file","Git repository","Version control"),aws("AWS CodeBuild","CI validation"),aws("AWS CodePipeline","Delivery")])];
 if(service==="AWS Tools and SDKs")return[A("Application-to-service API calls","SDKs handle request signing, retries and service clients inside application code.",[pub("app","Application code","SDK client")],pub("security","Credential provider chain","Role/session")],aws("AWS Cloud","AWS SDK request"),[aws("Amazon S3","Example service"),aws("Amazon DynamoDB","Example service"),pub("monitor","CloudTrail","API audit")]),A("Local developer tooling","Language SDKs, IDE tools and credential providers connect development workflows to AWS APIs.",[pub("user","Developer","IDE / terminal")],pub("app","AWS SDK / toolkit","Authenticated client"),[aws("AWS IAM","Authorization"),aws("AWS Cloud","Target API")])];
 if(service==="AWS X-Ray")return[A("Distributed trace","Instrumented services emit trace segments that X-Ray assembles into end-to-end requests.",[pub("user","Client request","Trace context"),aws("Amazon API Gateway","Entry span")],aws("AWS X-Ray","Trace + service map"),[aws("AWS Lambda","Downstream segment"),pub("app","Microservice","Downstream segment"),pub("monitor","Latency/errors","Root-cause analysis")]),A("GenAI request observability","Trace application/tool latency around managed model calls without treating the model service as your code.",[pub("app","GenAI API","Request")],aws("AWS X-Ray","Distributed trace"),[aws("AWS Lambda","Tool span"),aws("Amazon Bedrock","Model dependency"),pub("monitor","CloudWatch","Metrics/log correlation")])];

 // AI/ML sub-services receive capability-specific architectures instead of one Bedrock/SageMaker diagram.
 if(service==="Amazon Bedrock Knowledge Bases")return[A("Managed RAG","Documents are chunked/embedded into a retrieval store and grounding is supplied to model inference.",[aws("Amazon S3","Source documents")],aws("Amazon Bedrock","Knowledge Bases"),[pub("data","Vector store","Embeddings + chunks"),pub("ai","Foundation model","Grounded response"),pub("app","RAG application","RetrieveAndGenerate")]),A("Governed enterprise grounding","Access to source data, retrieval and model invocation can be separated by role and data boundary.",[pub("user","Enterprise user","Question")],aws("Amazon Bedrock","Knowledge Base retrieval"),[pub("security","IAM / KMS","Access + encryption"),pub("data","Enterprise corpus","Authorized context"),pub("ai","Model response","Grounded answer")])];
 if(service==="Amazon Bedrock AgentCore")return[A("Agent runtime + tools","AgentCore provides production agent runtime capabilities around tool use and enterprise integrations.",[pub("user","Application user","Goal")],aws("Amazon Bedrock","AgentCore runtime"),[aws("AWS Lambda","Tool/action"),pub("app","Enterprise API","Business system"),pub("data","Agent memory/context","State")]),A("Observable agent execution","Separate identity, tool authorization and telemetry around autonomous steps.",[pub("app","Agent application","Task")],aws("Amazon Bedrock","AgentCore"),[pub("security","Identity / policy","Tool permissions"),pub("monitor","Observability","Agent traces"),pub("app","External tools","Actions")])];
 if(service==="Amazon Bedrock Prompt Management")return[A("Prompt lifecycle","Teams version reusable prompt templates independently from application code.",[pub("user","Prompt engineer","Template + variables")],aws("Amazon Bedrock","Prompt Management"),[pub("file","Prompt versions","Draft / saved versions"),pub("app","Application","Invoke selected prompt"),pub("ai","Foundation model","Inference")]),A("Controlled prompt promotion","Evaluate prompt versions before promoting them into application workflows.",[pub("file","Prompt v1 / v2","Candidates")],aws("Amazon Bedrock","Managed prompt"),[pub("ai","Evaluation","Compare responses"),pub("app","Production app","Approved version")])];
 if(service==="Amazon Bedrock Prompt Flows")return[A("Visual GenAI workflow","Prompt Flows links prompts, model calls, conditions and data nodes into a managed flow.",[pub("app","Input","Request/data")],aws("Amazon Bedrock","Prompt Flow"),[pub("ai","Prompt/model node","Inference"),pub("data","Knowledge/data node","Context"),pub("app","Flow output","Response")]),A("Branching AI workflow","Conditions can route different inputs to different prompts/tools rather than forcing a linear chain.",[pub("app","Request","Classify")],aws("Amazon Bedrock","Prompt Flow branching"),[pub("ai","Path A","Prompt/model"),pub("ai","Path B","Prompt/model"),pub("app","Merged result","Output")])];
 if(service.includes("Bedrock")||service==="Amazon Titan"||service==="Amazon Nova")return[A("Managed foundation-model application","Application code invokes a selected model while data and guardrails remain separate controls.",[pub("user","User","Prompt"),pub("data","Application context","Optional grounding")],aws("Amazon Bedrock","Model inference"),[pub("ai",service.includes("Nova")?"Amazon Nova":"Foundation model","Text / multimodal output"),pub("security","Guardrails","Safety controls"),pub("monitor","Model metrics","Latency / usage")]),A("Tool-using GenAI workload","A model can participate in a broader workflow with retrieval and deterministic tools.",[pub("app","GenAI application","Task")],aws("Amazon Bedrock","Model / agent layer"),[aws("AWS Lambda","Tool function"),aws("Amazon S3","Knowledge documents"),pub("data","Enterprise API","Grounded action")])];
 if(service==="Amazon Augmented AI")return[A("Human review loop","Low-confidence or policy-sensitive ML results are routed to human reviewers.",[pub("ai","ML prediction","Needs review")],pub("app","Amazon Augmented AI","Human review workflow"),[pub("user","Reviewer workforce","Approve/correct"),pub("data","Reviewed result","Downstream use")]),A("Human-in-the-loop document processing","Automation handles routine items while exceptions become review tasks.",[aws("Amazon Textract","Extracted fields")],pub("app","Amazon Augmented AI","Review condition"),[pub("user","Human reviewer","Exception handling"),pub("app","Business workflow","Accepted result")])];
 if(service==="Amazon Comprehend"||service==="Amazon Comprehend Medical")return[A("Text understanding pipeline","Raw text is submitted for entities, sentiment, classification or medical NLP outputs.",[pub("file","Documents / notes","Text")],aws("Amazon Comprehend",service.includes("Medical")?"Medical NLP":"NLP analysis"),[pub("data","Entities / labels","Structured output"),aws("Amazon S3","Batch results"),pub("app","Downstream workflow","Search / routing")]),A("Document enrichment","NLP-derived metadata can enrich search or analytics without replacing the source document.",[aws("Amazon S3","Document corpus")],aws("Amazon Comprehend","Entity/classification job"),[aws("Amazon OpenSearch Service","Search index"),pub("data","Analytics metadata","Tags/features")])];
 if(service==="Amazon Kendra")return[A("Enterprise semantic search","Kendra indexes enterprise repositories and retrieves ranked answers/documents for users.",[pub("data","Enterprise repositories","Documents")],aws("AWS Cloud","Amazon Kendra index"),[pub("user","Search user","Natural-language query"),pub("data","Ranked results","Relevant passages"),pub("security","Source ACLs","Permission-aware access")]),A("Retrieval layer for assistants","A conversational application can use enterprise search results as grounded context.",[pub("user","Assistant user","Question")],aws("AWS Cloud","Amazon Kendra retrieval"),[pub("ai","LLM/application","Grounded answer"),pub("data","Cited enterprise docs","Evidence")])];
 if(service==="Amazon Lex")return[A("Conversational bot","Lex handles speech/text intent recognition and slot filling before fulfillment.",[pub("user","Customer","Voice / text")],aws("AWS Cloud","Amazon Lex bot"),[aws("AWS Lambda","Fulfillment"),pub("app","Business API","Action"),pub("message","Response","Conversation")]),A("Contact-center bot","Lex can sit inside a Connect contact flow before escalation to an agent.",[pub("user","Caller","Voice")],aws("Amazon Connect","Contact flow"),[aws("AWS Cloud","Amazon Lex","Intent/slots"),pub("user","Human agent","Escalation")])];
 if(service==="Amazon PartyRock")return[A("No-code GenAI prototyping","Builders compose widgets and prompts to prototype generative applications quickly.",[pub("user","Builder","Idea / prompt")],pub("app","Amazon PartyRock","No-code app builder"),[pub("ai","Generated app widgets","Text/image interactions"),pub("user","Shared users","Prototype testing")]),A("Prototype-before-production","Use the prototype to validate UX/ideas, then implement governed production architecture separately.",[pub("app","PartyRock prototype","Validate concept")],pub("user","Product team","Learn from users"),[aws("Amazon Bedrock","Production model layer"),pub("app","Production application","Engineered controls")])];
 if(service==="Amazon Personalize")return[A("Recommendation pipeline","Interaction/item/user data trains recommendation models used by applications.",[pub("data","Users/items/events","Dataset groups")],aws("AWS Cloud","Amazon Personalize"),[pub("ai","Recommendations","Ranked items"),pub("app","Application","Personalized experience")]),A("Realtime personalization","Live interaction events update personalization while recommendations are requested independently.",[pub("app","Web/mobile app","Interaction events")],aws("AWS Cloud","Amazon Personalize"),[pub("data","Event tracker","Behavior"),pub("ai","Realtime recommendation","Next-best items")])];
 if(service==="Amazon Polly")return[A("Text-to-speech","Applications submit text/SSML and receive synthesized speech.",[pub("app","Application","Text / SSML")],aws("AWS Cloud","Amazon Polly"),[pub("message","Audio stream/file","Speech"),aws("Amazon S3","Optional audio storage")]),A("Accessible content generation","Batch narration can convert stored content into reusable audio assets.",[aws("Amazon S3","Text content")],aws("AWS Cloud","Amazon Polly"),[aws("Amazon S3","Narrated audio"),pub("user","End users","Playback")])];
 if(service==="Amazon Rekognition")return[A("Image/video analysis","Media is analyzed for labels, faces, moderation or custom visual signals.",[aws("Amazon S3","Images / video")],aws("AWS Cloud","Amazon Rekognition"),[pub("data","Labels / detections","Structured metadata"),pub("app","Application workflow","Moderation/search")]),A("Upload moderation","An object event can trigger visual moderation before content becomes visible.",[pub("user","User upload","Image")],aws("Amazon S3","Landing bucket"),[aws("AWS Cloud","Amazon Rekognition","Moderation"),aws("AWS Lambda","Decision logic"),pub("app","Approved/quarantine","Outcome")])];
 if(service==="Amazon Textract")return[A("Document extraction","Textract turns document images/PDFs into structured text, forms and tables.",[aws("Amazon S3","Scanned document")],aws("Amazon Textract","OCR + structure extraction"),[pub("data","Text/forms/tables","Structured result"),pub("app","Business workflow","Validate/store")]),A("RAG document preparation","Extraction can normalize scanned documents before chunking/indexing for retrieval.",[pub("file","PDF/image corpus","Scanned content")],aws("Amazon Textract","Extract text/layout"),[aws("Amazon S3","Normalized text"),aws("Amazon Bedrock","Knowledge ingestion")])];
 if(service==="Amazon Transcribe")return[A("Speech-to-text","Audio is converted to timed transcript text and optional speaker/channel metadata.",[pub("message","Audio stream/file","Speech")],aws("Amazon Transcribe","ASR"),[pub("file","Transcript","Text"),aws("Amazon S3","Batch output"),pub("app","Downstream NLP","Search/summarize")]),A("Contact analytics preparation","Voice interactions become text that can feed summarization, classification or compliance analysis.",[aws("Amazon Connect","Contact audio")],aws("Amazon Transcribe","Transcript"),[aws("Amazon Comprehend","NLP enrichment"),pub("ai","Summary / QA","GenAI analysis")])];
 if(service.startsWith("Amazon SageMaker")){
  const capability=service.replace("Amazon SageMaker ","");
  if(capability==="Ground Truth")return[A("Managed data labeling","Raw datasets become labeled training data through automated/human labeling workflows.",[aws("Amazon S3","Unlabeled dataset")],aws("Amazon SageMaker AI","Ground Truth labeling"),[pub("user","Labeling workforce","Human labels"),aws("Amazon S3","Labeled manifest")]),A("Active-learning loop","Automatic labeling can handle confident examples while uncertain samples go to humans.",[pub("data","Unlabeled samples","Input")],aws("Amazon SageMaker AI","Ground Truth"),[pub("ai","Auto labels","High confidence"),pub("user","Human labels","Low confidence")])];
  if(capability==="Model Monitor")return[A("Production model monitoring","Captured inference data is compared against baselines for drift and quality issues.",[pub("app","Endpoint traffic","Requests/predictions")],aws("Amazon SageMaker AI","Model Monitor"),[pub("monitor","Drift / quality reports","Violations"),aws("Amazon S3","Captured data"),pub("message","Alerts","Operational response")]),A("Continuous ML feedback","Monitoring findings trigger investigation or retraining workflows rather than silently degrading.",[pub("monitor","Detected drift","Signal")],aws("Amazon SageMaker AI","Monitoring schedule"),[pub("user","ML team","Investigate"),pub("ai","Retraining pipeline","Remediate")])];
  if(capability==="Model Registry")return[A("Model version governance","Candidate models are versioned, reviewed and promoted through approval states.",[pub("ai","Training job","Model artifact")],aws("Amazon SageMaker AI","Model Registry"),[pub("user","Approver","Approve/reject"),pub("app","Deployment pipeline","Deploy approved model")]),A("Cross-stage model promotion","Registry metadata separates experimentation from governed production deployment.",[pub("ai","Experiment outputs","Candidate versions")],aws("Amazon SageMaker AI","Model package group"),[pub("app","Staging endpoint","Validate"),pub("app","Production endpoint","Promote")])];
  if(capability==="Processing")return[A("Managed data processing job","Ephemeral containers process data for preprocessing, postprocessing or evaluation.",[aws("Amazon S3","Raw input")],aws("Amazon SageMaker AI","Processing job"),[aws("Amazon S3","Processed output"),pub("monitor","Job metrics/logs","Operations")]),A("ML pipeline preparation","Processing jobs create repeatable dataset transformation steps before training/evaluation.",[pub("data","Dataset","Input")],aws("Amazon SageMaker AI","Processing"),[pub("ai","Training step","Next"),pub("data","Evaluation report","Output")])];
  if(capability==="Clarify")return[A("Bias and explainability analysis","Clarify analyzes datasets/models for bias metrics and feature attribution.",[pub("data","Dataset","Features/labels"),pub("ai","Model","Predictions")],aws("Amazon SageMaker AI","Clarify analysis"),[pub("data","Bias report","Fairness metrics"),pub("data","SHAP explanations","Feature attribution")]),A("Governed model review","Explainability artifacts support model-risk and responsible-AI review before/after deployment.",[pub("ai","Candidate model","Review")],aws("Amazon SageMaker AI","Clarify"),[pub("user","Model reviewer","Inspect findings"),pub("file","Governance evidence","Reports")])];
  if(capability==="Data Wrangler")return[A("Visual data preparation","Data Wrangler profiles and transforms tabular data before training.",[aws("Amazon S3","Raw dataset")],aws("Amazon SageMaker AI","Data Wrangler flow"),[pub("data","Transforms/features","Prepared data"),pub("ai","Training job","Consume output")]),A("Reusable preprocessing","Exported transformation flows/jobs keep experimentation and production preprocessing aligned.",[pub("user","Data scientist","Visual transforms")],aws("Amazon SageMaker AI","Data Wrangler"),[pub("file","Processing flow","Reusable recipe"),aws("Amazon S3","Prepared dataset")])];
  if(capability==="JumpStart")return[A("Prebuilt model starting point","JumpStart provides curated models/solutions that can be evaluated and deployed in SageMaker.",[pub("user","ML developer","Select model")],aws("Amazon SageMaker AI","JumpStart catalog"),[pub("ai","Pretrained model","Evaluate/fine-tune"),pub("app","SageMaker endpoint","Deploy")]),A("Fine-tune then deploy","Start from a pretrained model, customize with your data and publish a governed endpoint.",[aws("Amazon S3","Training data")],aws("Amazon SageMaker AI","JumpStart fine-tuning"),[pub("ai","Customized model","Artifact"),pub("app","Inference endpoint","Production")])];
  if(capability==="Neo")return[A("Model optimization for target hardware","Neo compiles trained models for efficient execution on supported edge/cloud hardware.",[pub("ai","Trained model","Framework artifact"),aws("Amazon SageMaker AI","Neo compiler"),[pub("file","Optimized artifact","Target-specific"),pub("app","Edge/cloud runtime","Inference")]),A("Deployment optimization","Compilation is a post-training optimization step, not a training service.",[pub("ai","Approved model","Input")],aws("Amazon SageMaker AI","Neo"),[pub("monitor","Benchmark","Latency/size"),pub("app","Deployment target","Optimized runtime")])];
  if(capability==="Unified Studio")return[A("Unified analytics/AI workspace","Teams discover governed data and build analytics/AI assets from one workspace.",[pub("user","Data / ML teams","Projects"),pub("data","Enterprise data","Governed assets")],aws("Amazon SageMaker AI","Unified Studio"),[pub("ai","ML / GenAI work","Build"),pub("data","Analytics work","Query/process"),pub("security","Governance","Permissions")]),A("Project-based collaboration","Projects isolate resources, access and artifacts for teams working on shared data products.",[pub("user","Project members","Workspace")],aws("Amazon SageMaker AI","Unified Studio project"),[pub("file","Notebooks/assets","Development"),pub("app","Published outputs","Consumers")])];
  return[A("Managed ML lifecycle","SageMaker separates data preparation, training, model governance and deployment.",[aws("Amazon S3","Training data"),pub("user","ML team","Experiment")],aws("Amazon SageMaker AI",capability==="AI"?"Build / train / deploy":capability),[pub("ai","Training / model artifact","Model lifecycle"),pub("app","Endpoint / batch","Inference"),pub("monitor","Monitoring","Quality + drift")]),A("Governed production ML","Registry, deployment and monitoring controls keep experimentation separate from production serving.",[pub("ai","Candidate model","Version")],aws("Amazon SageMaker AI",service),[pub("user","Approval","Governance"),pub("app","Production endpoint","Serving"),pub("monitor","Model quality","Operate")])];
 }
 if(service.startsWith("Amazon Q")||service==="Amazon Quick")return[A("Enterprise AI assistant","The assistant answers or acts using authenticated enterprise context rather than an open generic prompt alone.",[pub("user","Enterprise user","Question/task"),pub("data","Enterprise content","Authorized context")],pub("ai",service,"Assistant capability"),[pub("app","Business action","If supported"),pub("data","Grounded response","Citations/context"),pub("security","Enterprise identity","Access filtering")]),A("Governed productivity workflow","Identity and source permissions constrain what the assistant can retrieve or act on.",[pub("user","Employee / developer","Intent")],pub("ai",service,"AI assistant"),[pub("security","IAM / IdP","Who can access"),pub("app","Connected tool","Action"),pub("monitor","Audit / feedback","Operate")])];

 // Management, migration, network, security and storage get exact service-aligned operating models.
 if(service==="AWS CloudTrail")return[A("AWS API audit trail","Control-plane API activity is recorded for investigation and governance.",[pub("user","Users / roles","API activity"),aws("AWS Cloud","AWS service APIs")],aws("AWS CloudTrail","Management/data events"),[aws("Amazon S3","Durable trail"),pub("monitor","Security analytics","Detection/investigation")]),A("Centralized account audit","Organization trails centralize activity from multiple accounts into a protected logging account.",[pub("app","Member accounts","CloudTrail events")],aws("AWS CloudTrail","Organization trail"),[aws("Amazon S3","Central log archive"),pub("security","KMS / bucket policy","Protect evidence")])];
 if(service==="Amazon CloudWatch"||service==="Amazon CloudWatch Logs"||service==="Amazon CloudWatch Synthetics")return[A("Operational telemetry","Metrics, logs and synthetic checks feed alarms and dashboards for workloads.",[aws("AWS Lambda","Application telemetry"),aws("Amazon EC2","Host telemetry")],aws("Amazon CloudWatch",service.replace("Amazon ","")),[pub("monitor","Alarms","Threshold/anomaly"),pub("monitor","Dashboards","Visualization"),pub("app","Automation target","Respond")]),A("GenAI application observability","Monitor latency, errors and usage across the application and its downstream model dependencies.",[pub("app","GenAI application","Logs/metrics")],aws("Amazon CloudWatch","Observability"),[aws("AWS X-Ray","Trace correlation"),pub("monitor","SLO dashboard","Operate"),pub("message","Alarm action","Notify/remediate")])];
 if(service==="AWS Systems Manager")return[A("Fleet operations","Systems Manager manages instances/nodes through an agent/control channel without requiring inbound admin access.",[pub("user","Operator","Automation / session"),aws("AWS Cloud","Managed instances")],aws("AWS Systems Manager","Fleet control plane"),[aws("Amazon EC2","Managed nodes"),pub("file","Run Command / Automation","Operational actions"),pub("security","Parameter Store","Configuration/secrets")]),A("Patch and configuration workflow","Inventory, patching and automation keep fleets in a known operating state.",[pub("monitor","Inventory / compliance","Current state")],aws("AWS Systems Manager","Patch/automation"),[pub("app","Maintenance window","Schedule"),pub("monitor","Compliance results","Evidence")])];
 if(service==="AWS Cost Explorer"||service==="AWS Cost Anomaly Detection")return[A("Cost visibility","Billing usage is aggregated into trends, dimensions and forecasts/anomaly signals.",[aws("AWS Cloud","AWS usage + billing data")],pub("app",service,"Cost analytics"),[pub("data","Service/account/tag views","Allocation"),pub("monitor","Trend/anomaly","Signal"),pub("user","FinOps team","Action")]),A("FinOps feedback loop","Cost signals become owner actions rather than passive dashboards.",[pub("monitor","Unexpected spend","Detection")],pub("app",service,"Analyze cause"),[pub("user","Workload owner","Investigate"),pub("app","Optimization action","Rightsize/stop/redesign")])];
 if(service==="Amazon Managed Grafana")return[A("Managed dashboards","Grafana queries approved observability/data sources and presents shared dashboards.",[aws("Amazon CloudWatch","Metrics/logs"),pub("data","Other data source","Prometheus/OpenSearch")],pub("monitor","Amazon Managed Grafana","Visualization workspace"),[pub("user","Operators","Dashboards"),pub("monitor","Alerts","Operational signal")]),A("Cross-account observability view","Central workspaces can visualize data from multiple environments while permissions stay explicit.",[pub("app","Account A","Telemetry"),pub("app","Account B","Telemetry")],pub("monitor","Amazon Managed Grafana","Central dashboards"),[pub("user","Platform team","Shared view")])];
 if(service==="AWS Service Catalog")return[A("Governed self-service products","Platform teams publish approved CloudFormation-based products for controlled self-service provisioning.",[pub("user","Platform team","Portfolio/products")],aws("AWS Service Catalog","Governed catalog"),[pub("user","Application team","Launch product"),aws("AWS CloudFormation","Provision resources"),pub("security","Constraints/roles","Guardrails")]),A("Standardized GenAI environment","Reusable products can package approved networking, IAM and AI-service integrations.",[pub("file","Approved product","Architecture template")],aws("AWS Service Catalog","Portfolio"),[pub("app","Team environment","Provisioned stack"),pub("monitor","Product versions","Lifecycle")])];
 if(service==="AWS Well-Architected Tool")return[A("Architecture review workflow","Teams assess a workload against Well-Architected pillars and record improvement items.",[pub("user","Architecture team","Workload answers")],pub("app","AWS Well-Architected Tool","Review"),[pub("file","Risks","HRI/MRI findings"),pub("file","Improvement plan","Remediation")]),A("Continuous architecture governance","Reviews are repeated as workloads change rather than treated as one-time certification paperwork.",[pub("app","Workload change","New design")],pub("app","AWS Well-Architected Tool","Milestone review"),[pub("user","Owners","Prioritize improvements"),pub("monitor","Milestones","Track progress")])];
 if(service==="AWS DataSync")return[A("Accelerated data transfer","A DataSync task moves files/objects between supported on-prem and AWS storage with verification.",[pub("storage","On-prem NAS/object","Source"),pub("network","DataSync agent","Where required")],aws("AWS DataSync","Managed transfer task"),[aws("Amazon S3","Object destination"),aws("Amazon EFS","File destination"),pub("monitor","Task metrics","Transfer status")]),A("Recurring migration/sync","Scheduled tasks incrementally synchronize changed data instead of rebuilding transfer logic.",[pub("storage","Source dataset","Changed files")],aws("AWS DataSync","Schedule + filters"),[aws("Amazon S3","Cloud copy"),pub("monitor","Verification","Integrity")])];
 if(service==="AWS Transfer Family")return[A("Managed SFTP/FTPS/FTP entry","External partners use familiar file-transfer protocols while files land directly in AWS storage.",[pub("internet","Partner client","SFTP / FTPS / FTP")],aws("AWS Transfer Family","Managed protocol endpoint"),[aws("Amazon S3","Object storage"),aws("Amazon EFS","File storage"),pub("security","Identity provider","Users/roles")]),A("Business file exchange","Protocol endpoint, identity and storage are separate layers that can be governed independently.",[pub("user","B2B partner","Upload/download")],aws("AWS Transfer Family","Server / connector"),[aws("Amazon S3","Landing zone"),aws("AWS Lambda","Post-upload processing")])];
 if(service==="Amazon API Gateway")return[A("Serverless API front door","API Gateway provides HTTP API management while compute/data remain independent backends.",[pub("user","Web/mobile client","HTTPS")],aws("Amazon API Gateway","Routes + auth + throttling"),[aws("AWS Lambda","Business logic"),aws("Amazon DynamoDB","State"),pub("monitor","CloudWatch","Access/execution logs")]),A("GenAI API boundary","Authentication, quotas and request policy sit before model orchestration.",[pub("user","GenAI client","Request")],aws("Amazon API Gateway","Secured API"),[aws("AWS Lambda","Prompt/orchestration"),aws("Amazon Bedrock","Model inference"),aws("AWS WAF","Request protection")])];
 if(service==="AWS AppSync")return[A("Managed GraphQL API","Clients request graph fields while resolvers compose data from multiple backends.",[pub("user","Web/mobile clients","GraphQL / subscriptions")],aws("AWS AppSync","Schema + resolvers"),[aws("Amazon DynamoDB","Data source"),aws("AWS Lambda","Custom resolver"),pub("message","Realtime subscriptions","Push updates")]),A("GenAI application data API","GraphQL can expose session/data operations while model calls remain behind controlled resolvers.",[pub("app","Frontend","Query/mutation")],aws("AWS AppSync","GraphQL boundary"),[aws("AWS Lambda","Resolver logic"),aws("Amazon Bedrock","Inference"),aws("Amazon Cognito","User auth")])];
 if(service==="Amazon CloudFront")return[A("Global content delivery","CloudFront caches content at edge locations and forwards misses to origins.",[pub("user","Global viewers","HTTPS")],aws("Amazon CloudFront","Edge cache/distribution"),[aws("Amazon S3","Static origin"),pub("app","Application origin","Dynamic content"),aws("AWS WAF","Edge protection")]),A("Protected GenAI web delivery","Static UI and dynamic API traffic can share an edge front door with distinct origins.",[pub("user","Users","Web + API")],aws("Amazon CloudFront","Path-based origins"),[aws("Amazon S3","Web assets"),aws("Amazon API Gateway","API origin"),aws("AWS WAF","Filtering")])];
 if(service.startsWith("Elastic Load Balancing"))return[A("Highly available application entry","A load balancer distributes traffic across healthy targets in multiple AZs.",[pub("user","Clients","HTTP/TCP")],aws("Elastic Load Balancing","ALB/NLB"),[aws("Amazon EC2","Instance targets"),aws("Amazon ECS","Container targets"),pub("monitor","Health checks","Remove unhealthy targets")]),A("Private service tier","An internal load balancer can expose services only inside a VPC.",[pub("network","Private clients","VPC traffic")],aws("Elastic Load Balancing","Internal ALB/NLB"),[pub("app","Private targets","Services"),pub("security","Security groups","Traffic policy")])];
 if(service==="AWS Global Accelerator")return[A("Anycast global entry","Static anycast IPs steer users onto the AWS global network toward healthy regional endpoints.",[pub("user","Global users","TCP/UDP")],aws("AWS Global Accelerator","Anycast edge entry"),[aws("Elastic Load Balancing","Region A endpoint"),aws("Elastic Load Balancing","Region B endpoint"),pub("monitor","Health checks","Traffic shift")]),A("Multi-Region failover","Endpoint weights and health checks support fast regional traffic steering.",[pub("user","Clients","Static IPs")],aws("AWS Global Accelerator","Listener + endpoint groups"),[pub("app","Primary Region","Healthy"),pub("app","Secondary Region","Failover")])];
 if(service==="AWS PrivateLink")return[A("Private service consumption","Interface endpoints connect consumers to services without public IPs or internet routing.",[pub("app","Consumer VPC","Private client")],aws("AWS PrivateLink","Interface endpoint"),[pub("app","Endpoint service","Provider"),pub("network","Private AWS network","No internet/NAT")]),A("Private SaaS / shared service","Many consumer VPCs can privately access a centrally published service.",[pub("app","Consumer VPC A","Endpoint"),pub("app","Consumer VPC B","Endpoint")],aws("AWS PrivateLink","Private connectivity"),[aws("Elastic Load Balancing","Provider NLB"),pub("app","Shared service","Targets")])];
 if(service==="Amazon Route 53")return[A("DNS routing","Route 53 answers DNS with records/policies that point clients to healthy application endpoints.",[pub("user","Internet user","DNS query")],aws("Amazon Route 53","Hosted zone + routing policy"),[aws("Amazon CloudFront","Global web"),aws("Elastic Load Balancing","Regional app"),pub("monitor","Health checks","Failover")]),A("Multi-Region DNS failover","Health checks and failover/latency policies select the appropriate regional endpoint.",[pub("user","Client","Resolve name")],aws("Amazon Route 53","Routing policy"),[pub("app","Region A","Primary/low latency"),pub("app","Region B","Secondary/low latency")])];
 if(service==="Amazon VPC")return[A("Private network segmentation","Subnets, route tables and gateways define network reachability; security controls define permission.",[pub("internet","Internet","External traffic")],aws("Amazon VPC","CIDR + subnets + routes"),[pub("network","Public subnet","Internet-facing tier"),pub("network","Private subnet","Application/data tier"),pub("security","Security groups/NACLs","Traffic controls")]),A("Private GenAI workload","Applications can stay in private subnets and reach supported AWS services using controlled private paths.",[pub("app","Private application","No public IP")],aws("Amazon VPC","Private subnets"),[aws("AWS PrivateLink","Interface endpoints"),pub("network","NAT / egress","Controlled outbound"),pub("data","Private data tier","RDS/cache")])];
 if(service==="Amazon Cognito")return[A("Application user identity","Cognito handles sign-up/sign-in and issues tokens consumed by application APIs.",[pub("user","Web/mobile user","Sign in")],aws("Amazon Cognito","User pool"),[pub("security","JWT tokens","Identity claims"),aws("Amazon API Gateway","Protected API"),pub("app","Application","Authorized session")]),A("Federated identity","External identity providers can federate into Cognito before the application receives tokens.",[pub("user","Enterprise/social user","Authenticate")],pub("security","External IdP","OIDC/SAML/social"),aws("Amazon Cognito","Federation + tokens"),[pub("app","Application","Use token")])];
 if(service==="AWS KMS"||service==="AWS Encryption SDK")return[A("Envelope encryption","KMS protects data keys; applications/services use data keys for bulk encryption.",[pub("app","Application","Encrypt request"),pub("data","Plaintext data","Input")],aws("AWS KMS","KMS key + GenerateDataKey"),[pub("security","Encrypted data key","Stored with ciphertext"),pub("data","Ciphertext","Protected data"),pub("monitor","CloudTrail","Key API audit")]),A("Service-integrated encryption","AWS services can use KMS keys without exposing key material to the workload.",[aws("Amazon S3","Encrypted objects"),aws("Amazon RDS","Encrypted storage")],aws("AWS KMS","Key policy boundary"),[pub("security","IAM + key policy","Authorization"),pub("monitor","Key rotation/audit","Governance")])];
 if(service==="IAM"||service==="IAM Access Analyzer"||service==="IAM Identity Center")return[A("Human and workload authorization","Identities obtain credentials/tokens and policies determine allowed AWS API actions.",[pub("user","Human / workload","Identity")],aws("AWS IAM",service),[aws("AWS Cloud","AWS service API"),pub("security","Policies / roles","Authorization"),aws("AWS CloudTrail","Audit")]),A("Least-privilege governance","Analyze access and prefer temporary role sessions over long-lived credentials.",[pub("security","Identity Center / federation","Workforce access"),aws("AWS IAM","Roles + policies"),[pub("security","Access Analyzer","External/unused access"),pub("monitor","CloudTrail","Verify usage")])];
 if(service==="Amazon Macie")return[A("Sensitive-data discovery","Macie evaluates S3 object content/metadata to identify sensitive data exposure.",[aws("Amazon S3","Buckets/objects")],aws("Amazon Macie","Sensitive data discovery"),[pub("security","Findings","PII/secrets patterns"),pub("user","Security team","Investigate/remediate")]),A("Data-lake governance signal","Discovery findings feed security workflows while S3 remains the data store.",[aws("Amazon S3","Data lake")],aws("Amazon Macie","Classification jobs"),[pub("monitor","Security workflow","Prioritize findings"),pub("security","Bucket policy/KMS","Remediation")])];
 if(service==="AWS Secrets Manager")return[A("Runtime secret retrieval","Applications retrieve database/API secrets at runtime instead of embedding credentials in code/images.",[pub("app","Application","GetSecretValue")],aws("AWS Secrets Manager","Encrypted secret"),[aws("AWS KMS","Encryption key"),aws("Amazon RDS","Example target"),pub("monitor","Rotation/audit","Lifecycle")]),A("Automatic credential rotation","A rotation workflow changes the secret and target credential together while applications keep using the secret reference.",[pub("monitor","Rotation schedule","Trigger")],aws("AWS Secrets Manager","Rotate secret"),[aws("AWS Lambda","Rotation function"),aws("Amazon RDS","Update credential"),pub("app","Applications","Read current version")])];
 if(service==="AWS WAF")return[A("Layer-7 web filtering","WAF evaluates HTTP(S) requests before protected web endpoints.",[pub("internet","Internet clients","HTTP requests")],aws("AWS WAF","Web ACL + rules"),[aws("Amazon CloudFront","Edge protected resource"),aws("Amazon API Gateway","API protected resource"),aws("Elastic Load Balancing","ALB protected resource")]),A("Managed + application-specific rules","Combine managed rule groups, rate controls and custom rules around the application's actual threats.",[pub("internet","Requests","Good + malicious")],aws("AWS WAF","Rule evaluation"),[pub("security","Allow","Application traffic"),pub("security","Block / CAPTCHA","Threat response"),pub("monitor","WAF logs","Tune rules")])];
 if(service==="Amazon EBS")return[A("EC2 block storage","EBS volumes attach to EC2 instances as persistent block devices within an AZ.",[aws("Amazon EC2","Instance")],aws("Amazon EBS","Block volume"),[pub("storage","Snapshot","S3-backed backup"),pub("monitor","IOPS/throughput","Performance")]),A("Data-volume lifecycle","Snapshots create durable recovery points and can seed replacement volumes.",[aws("Amazon EBS","Production volume")],pub("storage","EBS snapshot","Recovery point"),[aws("Amazon EBS","Restored volume"),aws("Amazon EC2","Replacement instance")])];
 if(service==="Amazon EFS")return[A("Shared Linux file system","Multiple compute clients mount the same elastic NFS file system across AZs.",[aws("Amazon EC2","Client A"),aws("AWS Lambda","Client B")],aws("Amazon EFS","Managed NFS file system"),[pub("storage","Mount targets","VPC/AZ access"),pub("monitor","Throughput mode","Performance")]),A("Shared container content","ECS/EKS workloads can share files that must outlive individual tasks/pods.",[aws("Amazon ECS","Container tasks"),aws("Amazon EKS","Pods")],aws("Amazon EFS","Shared persistent files"),[pub("security","Access points","POSIX/app isolation"),pub("storage","Lifecycle","Archive infrequent files")])];
 if(service.startsWith("Amazon S3"))return[A("Object-storage data layer","Producers write objects while independent analytics/AI consumers read the same durable data.",[pub("app","Applications","Put/Get objects"),pub("data","Data ingestion","Files/events")],aws("Amazon S3",service),[aws("AWS Glue","Catalog/ETL"),aws("Amazon Athena","SQL analytics"),aws("Amazon Bedrock","RAG source")]),A(service.includes("Cross-Region")?"Cross-Region replication":"Lifecycle and access optimization",service.includes("Cross-Region")?"Replication asynchronously copies selected objects to a destination bucket in another Region.":"Storage class/lifecycle choices follow access frequency and retention requirements.",[aws("Amazon S3","Source bucket")],aws("Amazon S3",service),[pub("storage",service.includes("Cross-Region")?"Destination Region bucket":"Frequent tier","Hot data"),pub("storage",service.includes("Intelligent")?"Automatic access tiers":"Archive tiers","Cold data"),pub("monitor","Lifecycle / replication metrics","Operate")])];

 // Remaining named services use a category-aware architecture that still names real service boundaries rather than the old generic workload/data/security diagram.
 const categoryPattern:Record<string,Arch[]>={
  "Management and Governance":[A("Control-plane operating model",`${service} participates in governance/operations around AWS resources, not in the application data path.`,[pub("user","Cloud/platform team","Policy / operation"),aws("AWS Cloud","Managed resources")],aws("AWS Cloud",service),[pub("monitor","Findings / state","Operational output"),pub("app","Automation / remediation","Action")]),A("Multi-account governance",`Use ${service} with centralized ownership and workload-account execution where the service supports it.`,[pub("app","Workload accounts","Resources/events")],aws("AWS Cloud",service),[pub("user","Central platform team","Governance"),pub("monitor","Reports / actions","Operate")])],
  "Machine Learning":[A("AI capability in an application",`${service} performs its specialized AI task while application, source data and downstream actions remain separate.`,[pub("user","Application user","Request"),pub("data","Domain data","Input/context")],pub("ai",service,"Specialized AI capability"),[pub("app","Application workflow","Use result"),pub("monitor","Quality/usage","Operate")]),A("Batch or asynchronous AI processing",`${service} can be placed in a governed processing path with durable inputs and outputs.`,[aws("Amazon S3","Input dataset")],pub("ai",service,"Process/analyze"),[aws("Amazon S3","Output/results"),pub("monitor","Evaluation","Quality")])],
  "Security, Identity, and Compliance":[A("Security control placement",`${service} applies a specific identity/data/protection control around AWS workloads rather than carrying application traffic by itself.`,[pub("user","Identity / workload","Request or resource"),aws("AWS Cloud","Protected AWS resource")],aws("AWS Cloud",service),[pub("security","Decision / finding","Security outcome"),pub("monitor","Audit / response","Operate")]),A("Centralized security operations",`Security teams consume ${service} findings/policies and drive remediation in workload accounts.`,[pub("app","Workload accounts","Resources/activity")],aws("AWS Cloud",service),[pub("user","Security team","Review"),pub("app","Remediation","Policy/change")])],
  "Developer Tools":[A("Developer workflow",`${service} belongs in the software/infrastructure delivery lifecycle rather than the runtime request path.`,[pub("user","Developer","Change"),pub("file","Source / configuration","Input")],aws("AWS Cloud",service),[pub("file","Build/deploy artifact","Output"),pub("monitor","CI/CD feedback","Status")]),A("Governed delivery",`${service} integrates with source control, IAM and deployment automation to make changes repeatable.`,[pub("app","Repository / pipeline","Trigger")],aws("AWS Cloud",service),[pub("security","IAM role","Permissions"),aws("AWS Cloud","Target AWS resources")])]
 };
 return categoryPattern[category]||[A("Service operating model",`${service} is shown in its control/data boundary with concrete inputs and consumers.`,[pub("app","Client / source","Service input")],aws("AWS Cloud",service),[pub("app","Primary consumer","Service output"),pub("monitor","Operations","Metrics/audit")]),A("Production integration",`${service} integrates with independently governed application, security and data layers.`,[pub("app","Application","Request")],aws("AWS Cloud",service),[pub("data","Data/service dependency","Integration"),pub("security","Security controls","Governance")])];
}

const serviceRoles:Record<string,string>={
 "AWS CLI":"a command-line client for authenticated AWS API calls and automation; it is not a runtime hosting service",
 "AWS CDK":"an infrastructure-as-code framework that defines reusable constructs in programming languages and synthesizes CloudFormation",
 "AWS CloudFormation":"a declarative infrastructure provisioning engine that manages AWS resources as stacks",
 "Amazon EventBridge":"an event-routing service for decoupling producers from rule-based targets",
 "Amazon SQS":"a durable message queue for buffering asynchronous work and decoupling producers from consumers",
 "Amazon SNS":"a publish/subscribe fan-out service that pushes one message to multiple subscribers",
 "AWS Step Functions":"a state-machine orchestration service for branching, retries, waits and long-running workflows",
 "AWS Lambda":"event-driven serverless function compute for short-lived stateless execution",
 "AWS Lambda@Edge":"CloudFront-triggered Lambda execution at edge locations for request/response customization",
 "Amazon ECR":"a managed container image registry",
 "Amazon ECS":"AWS-native container orchestration for services and tasks",
 "Amazon EKS":"managed Kubernetes control planes for Kubernetes workloads",
 "AWS Fargate":"serverless compute capacity for ECS tasks and EKS pods",
 "Amazon Bedrock":"managed access to foundation models and GenAI building blocks",
 "Amazon S3":"durable object storage used for application content, data lakes and AI document corpora",
 "Amazon VPC":"the network isolation, subnet and routing boundary for AWS resources"
};
const categoryRole:Record<string,string>={"Application Integration":"decouple applications and coordinate events/messages/workflows","Compute":"run application code with the execution model appropriate to the workload","Containers":"package and orchestrate portable container workloads","Customer Engagement":"deliver managed customer communication/contact experiences","Database":"persist operational state using a managed data model","Developer Tools":"support repeatable software and infrastructure delivery","Machine Learning":"build or consume managed AI/ML capabilities","Management and Governance":"observe, govern and operate AWS environments","Migration and Transfer":"move data between on-premises, partners and AWS","Networking and Content Delivery":"connect and expose workloads through controlled network paths","Security, Identity, and Compliance":"apply identity, encryption, data protection and application security controls","Storage":"store durable application and data assets"};

const categoryConcepts:Record<string,string[]>={
 "Application Integration":["Know whether the service routes events, queues work, fans out messages or orchestrates state.","Retries, delivery semantics, ordering and idempotency are application design decisions.","DLQs or explicit failure branches prevent poison work from disappearing."],
 "Compute":["Separate stateless compute from durable state.","Choose based on runtime duration, OS/container control, scaling and latency.","Concurrency, startup behavior and network placement affect production design."],
 "Containers":["Registry, orchestrator and compute capacity are separate layers.","Images should be immutable; runtime state and secrets belong outside the image.","Task/pod identity and autoscaling should match workload boundaries."],
 "Database":["Start from access patterns and consistency requirements, not from a favorite database.","Indexes/replicas improve reads but introduce cost and operational tradeoffs.","Backup, recovery and encryption are part of the design."],
 "Developer Tools":["Developer tools live in build/deploy/operator workflows, not usually in the runtime request path.","Prefer repeatable automation and temporary credentials.","Artifacts, source, deployment targets and audit controls are separate concerns."],
 "Machine Learning":["Separate source data, model/AI capability, orchestration and evaluation.","Quality, latency, safety and cost must be measured together.","Grounding and retrieval are different from model inference."],
 "Management and Governance":["These are primarily control-plane/operations services, not application data-plane hops.","Centralized governance often spans multiple accounts and workloads.","Metrics, logs, audit records, findings and automation each solve different operational problems."],
 "Migration and Transfer":["The source, transfer mechanism and durable destination are distinct.","Throughput, scheduling, verification and protocol compatibility determine the right service."],
 "Networking and Content Delivery":["Routing determines path; security determines permission.","DNS, edge, load balancing and private connectivity operate at different layers.","Availability requires health checks and multiple failure domains where appropriate."],
 "Security, Identity, and Compliance":["Authentication, authorization, encryption and detection are different controls.","Use least privilege and temporary credentials where possible.","Security findings need an ownership and remediation path."],
 "Storage":["Object, block and file storage expose different semantics.","Lifecycle and storage class should follow access frequency.","Replication and backup solve different recovery requirements."]
};

function PublicIcon({kind}:{kind:Kind}){const C=kind==="user"?Users:kind==="internet"?Globe2:kind==="data"?Database:kind==="security"?Shield:kind==="file"?FileText:kind==="network"?Network:kind==="storage"?HardDrive:kind==="ai"?BrainCircuit:kind==="message"?MessageSquare:kind==="monitor"?Activity:kind==="app"?Laptop:Server;return <div className="public-icon-disc"><C size={36}/></div>}
function iconFor(label:string){const direct=findAwsArchitectureIcon(label);if(direct)return direct;const q=label.toLowerCase();if(q.includes("cloudwatch"))return awsArchitectureIcons.cloudWatch;if(q.includes("cloudtrail"))return awsArchitectureIcons.cloudTrail;if(q.includes("cloudformation"))return awsArchitectureIcons.cloudFormation;if(q.includes("cli"))return awsArchitectureIcons.cli;if(q.includes("bedrock")||q.includes("titan")||q.includes("nova"))return awsArchitectureIcons.bedrock;if(q.includes("sagemaker"))return awsArchitectureIcons.sagemaker;if(q.includes("s3"))return awsArchitectureIcons.s3;if(q.includes("lambda"))return awsArchitectureIcons.lambda;if(q.includes("dynamodb"))return awsArchitectureIcons.dynamodb;if(q.includes("iam"))return awsArchitectureIcons.iam;if(q.includes("kms"))return awsArchitectureIcons.kms;return awsArchitectureIcons.awsCloud}
function NodeView({node,featured=false}:{node:Node;featured?:boolean}){if(node.kind)return <div className={`dynamic-node public ${featured?"featured":""}`}><PublicIcon kind={node.kind}/><strong>{node.label}</strong><small>{node.sub}</small></div>;const icon=iconFor(node.label);return <div className={`dynamic-node ${featured?"featured":""}`}><div className="aws-icon-disc"><img src={awsIconSrc(icon)} data-primary-fallback={awsIconFallbackSrc(icon)} data-cloud-fallback={awsIconFallbackSrc(awsArchitectureIcons.awsCloud)} onError={e=>{const img=e.currentTarget;const first=img.dataset.primaryFallback;const cloud=img.dataset.cloudFallback;if(first&&img.src!==first){img.src=first;return}if(cloud&&img.src!==cloud){img.src=cloud;return}img.onerror=null}} alt={`${node.label} architecture icon`}/></div><strong>{node.label}</strong><small>{node.sub}</small></div>}
function Architecture({arch,index}:{arch:Arch;index:number}){return <section className="architecture-stage dynamic-architecture" id={`architecture-${index}`}><div className="section-cap"><div><p>ARCHITECTURE {String(index).padStart(2,"0")}</p><h3>{arch.title}</h3></div><span>{arch.note}</span></div><div className="dynamic-map"><div className="map-left">{arch.left.map((x,i)=><NodeView key={i} node={x}/>)}</div><div className="map-arrow">→</div><NodeView node={arch.center} featured/><div className="map-arrow">→</div><div className="map-branches">{arch.right.map((x,i)=><NodeView key={i} node={x}/>)}</div></div></section>}
function Cards({title,items,id}:{title:string;items:string[];id?:string}){return <section className="knowledge-card" id={id}><div className="knowledge-card-title"><span>◆</span><h3>{title}</h3></div><div className="knowledge-card-body"><div className="concept-stack">{items.map((x,i)=><p key={i}><b>{String(i+1).padStart(2,"0")}</b>{x}</p>)}</div></div></section>}

export default function AipServiceLearningDetails({serviceName}:{serviceName:string}){const e=resolveEntry(serviceName);if(!e)return null;const role=serviceRoles[e.service]||`${categoryRole[e.category]||"provide a managed AWS capability"}; understand the service-specific boundary shown in the architectures below`;const arches=architectureFor(e.service,e.category);const concepts=categoryConcepts[e.category]||["Know the service boundary and primary input/output.","Understand security, scaling and availability responsibilities.","Know when it is preferred over adjacent AWS services."];
 const useCases=arches.map(a=>`${a.title}: ${a.note}`);
 const security=[`Apply least-privilege access to ${e.service}; use workload roles or federated identities instead of embedded long-lived keys.`,`Encrypt sensitive data in transit and at rest where ${e.service} supports or integrates with encryption.`,`Log the relevant API, workload or security events so the service can be operated and audited in production.`];
 const optimize=[`Optimize the dimension ${e.service} actually scales on—requests, concurrency, capacity, storage, transfer, model usage or managed resource size.`,`Use metrics and service limits to identify saturation before simply adding capacity.`,`Keep application data, security and operational dependencies separate unless the service specifically owns that responsibility.`];
 const cost=[`Primary ${e.service} usage or capacity is the first cost driver.`,`Supporting data transfer, storage, logs, requests or downstream compute can become material.`,`Compare on-demand/serverless, provisioned and committed models only when this service offers those choices; avoid assuming every AWS service prices the same way.`];
 const comparison=[`Choose ${e.service} when its specific role—${role}—matches the requirement.`,`Do not substitute a neighboring AWS service merely because it appears in the same category; compare the actual execution/data/control-plane boundary.`,`In exam scenarios, eliminate options that place ${e.service} in a role it does not perform.`];
 return <div className="service-knowledge aip-shared-learning"><div className="knowledge-intro"><div><p className="knowledge-kicker">VISUAL DEEP DIVE • {e.category.toUpperCase()}</p><h2>{e.service}</h2><p><b>What it is:</b> {role}.</p></div><div className="knowledge-facts"><span><b>01</b>Purpose</span><span><b>02</b>Architecture</span><span><b>03</b>Operations</span><span><b>04</b>Exam fit</span></div></div><nav className="knowledge-jumps"><a href="#concepts">Concepts</a><a href="#architecture-1">Architectures</a><a href="#use-cases">Use cases</a><a href="#security">Security</a><a href="#cost-models">Cost</a><a href="#memory-hook">Exam hook</a></nav><div className="knowledge-grid" id="concepts"><Cards title="Core service concepts" items={concepts}/><Cards title="Where it fits" items={[`Primary role: ${role}.`,`Architecture 01 shows a common service-specific usage pattern.`,`Architecture 02 shows a second production pattern so the service is not taught as a single pipeline.`]}/></div>{arches.map((a,i)=><Architecture key={i} arch={a} index={i+1}/>)}<div className="knowledge-grid"><Cards id="use-cases" title="Practical use cases" items={useCases}/><Cards id="security" title="Security & governance" items={security}/><Cards title="Design & optimization" items={optimize}/><Cards id="cost-models" title="Cost model & drivers" items={cost}/><Cards title="Service comparison" items={comparison}/><Cards id="memory-hook" title="Certification memory hook" items={[`Remember the service by its boundary: ${role}.`,`Read the architecture arrows before reading the product name in an exam question; the required role often reveals the answer.`,`If an answer option makes ${e.service} own a responsibility outside this boundary, treat it as a warning sign.`]}/></div></div>}
