"use client";

import V3, { aipDetailServices, getAipLearningMeta, hasAipLearningDetails } from "./AipServiceLearningDetailsV3";
import { Activity, BrainCircuit, FileText, Laptop, MessageSquare, Server, Shield, Users } from "lucide-react";
import { awsArchitectureIcons, awsIconFallbackSrc, awsIconSrc } from "../../lib/aws-architecture-icons";
import "./AthenaLearningDetails.css";
import "./AthenaAwsIcons.css";
import "./AipServiceLearningDetails.css";

export { aipDetailServices, getAipLearningMeta, hasAipLearningDetails };

type Node={label:string;sub:string;icon?:"user"|"app"|"file"|"ai"|"message"|"monitor"|"security";awsIcon?:keyof typeof awsArchitectureIcons};
type Arch={title:string;note:string;left:Node[];center:Node;right:Node[]};
type Override={role:string;concepts:string[];useCases:string[];cost:string[];architectures:Arch[]};
const n=(label:string,sub:string,icon?:Node["icon"],awsIcon?:Node["awsIcon"]):Node=>({label,sub,icon,awsIcon});
const a=(title:string,note:string,left:Node[],center:Node,right:Node[]):Arch=>({title,note,left,center,right});

const overrides:Record<string,Override>={
 "AWS Auto Scaling":{role:"coordinates scaling across supported AWS resources using scaling plans and policies rather than serving application requests itself",concepts:["Scaling policy chooses when capacity changes; the target service still owns the workload.","Dynamic, scheduled and predictive approaches solve different demand patterns.","Good scaling requires the right metric, sensible min/max bounds and warm-up/cooldown behavior."],useCases:["Scale EC2/application capacity from demand metrics.","Coordinate scaling across multiple resource types.","Prepare known capacity before predictable peaks."],cost:["Auto Scaling control logic is not the main bill; scaled resources are.","Over-aggressive scaling increases compute cost; under-scaling hurts SLOs.","Metric/alarm and downstream service costs remain separate."],architectures:[a("Metric-driven capacity scaling","The control loop observes demand and changes target capacity; traffic never flows through Auto Scaling.",[n("Application demand","Requests / backlog","app"),n("CloudWatch metric","CPU / ALB / custom","monitor")],n("AWS Auto Scaling","Scaling policy","monitor","awsCloud"),[n("Amazon EC2","Scale instances",undefined,"ec2"),n("Amazon ECS","Scale tasks",undefined,"ecs"),n("Capacity bounds","Min / desired / max","security")]),a("Predictable peak preparation","Scheduled or predictive scaling adds capacity before a known or forecasted demand window.",[n("Historical demand","Forecast input","file"),n("Known event","Scheduled window","monitor")],n("AWS Auto Scaling","Predictive / scheduled action","monitor","awsCloud"),[n("Warm capacity","Ready before peak","app"),n("CloudWatch","Validate demand","monitor","cloudWatch")])]},
 "AWS Chatbot":{role:"delivers AWS operational notifications into chat channels and enables governed chat-initiated AWS actions; it is now associated with Amazon Q Developer in chat applications",concepts:["Chat is the operator interface, not the source of monitoring truth.","Notifications normally originate from services such as CloudWatch or SNS.","Channel roles and guardrail policies constrain which AWS actions can be run from chat."],useCases:["Send CloudWatch alarms to Slack/Teams.","Surface security or deployment notifications to operators.","Run approved diagnostic commands from a chat channel."],cost:["The chat integration itself is usually not the dominant cost driver.","SNS, CloudWatch and queried/acted-on AWS services keep their own pricing.","Operational value comes from reducing response time, not routing application traffic."],architectures:[a("Operations notification to chat","AWS events are produced elsewhere, routed to the chat integration and displayed to humans.",[n("CloudWatch alarm","Operational signal","monitor","cloudWatch"),n("Amazon SNS","Notification topic","message","sns")],n("AWS Chatbot","Chat integration","message","awsCloud"),[n("Slack / Teams","Operator channel","user"),n("On-call engineer","Investigate","user")]),a("Governed chat operations","A human request from chat is authorized before calling AWS APIs; Chatbot is not an unrestricted admin shell.",[n("Engineer","Chat command","user"),n("Channel guardrail","Allowed actions","security")],n("AWS Chatbot","Authorized command","message","awsCloud"),[n("AWS IAM","Role permissions","security","iam"),n("AWS service API","Diagnostic/action",undefined,"awsCloud"),n("CloudTrail","Audit","monitor","cloudTrail")])]},
 "Amazon Q Business":{role:"an enterprise generative-AI assistant that answers questions from connected, permission-aware business content",concepts:["Enterprise connectors/indexes supply grounded content.","User identity and document permissions affect what can be retrieved.","The assistant layer is separate from the source systems it searches."],useCases:["Enterprise knowledge assistant.","Policy/process Q&A with grounded sources.","Employee self-service across multiple repositories."],cost:["User/subscription or capacity model drives assistant cost depending on edition.","Index/connectors and source-system costs remain separate.","More content and usage increase retrieval/assistant consumption."],architectures:[a("Permission-aware enterprise assistant","The user asks Q Business; retrieval respects connected enterprise sources and access controls.",[n("Employee","Question","user"),n("Enterprise identity","SSO / permissions","security")],n("Amazon Q Business","Assistant + retrieval","ai","awsCloud"),[n("Knowledge sources","SharePoint / S3 / SaaS","file"),n("Grounded answer","Citations / context","file")]),a("Multi-source knowledge experience","Multiple repositories remain systems of record while Q Business provides one conversational access layer.",[n("Document repository","Policies / docs","file"),n("Business SaaS","Enterprise records","app")],n("Amazon Q Business","Connectors + index","ai","awsCloud"),[n("Employee portal","Assistant UI","app"),n("Access filters","Per-user results","security")])]},
 "Amazon Q Business Apps":{role:"builds task-focused business applications on top of enterprise Q capabilities without turning the assistant itself into the system of record",concepts:["The app captures a repeatable business task or workflow.","Enterprise identity and source permissions still apply.","Generated experiences should call governed data/actions rather than duplicating business data."],useCases:["Department-specific knowledge apps.","Repeatable document or decision workflows.","No/low-code AI productivity experiences."],cost:["Underlying Q Business access remains a core cost component.","Connected services/actions retain their own charges.","Evaluate per-user value rather than raw model calls alone."],architectures:[a("Business app on enterprise knowledge","A focused app sits above enterprise Q and its permission-aware data connections.",[n("Business user","Task","user"),n("App definition","Prompts / workflow","file")],n("Amazon Q Business Apps","Task-focused AI app","ai","awsCloud"),[n("Amazon Q Business","Enterprise assistant","ai","awsCloud"),n("Enterprise sources","Governed context","file")]),a("Action-enabled productivity app","The AI app can guide a task while external business systems remain authoritative.",[n("Employee","Business request","user")],n("Amazon Q Business Apps","Guided workflow","ai","awsCloud"),[n("Business API","Approved action","app"),n("Identity controls","User permissions","security"),n("Audit / feedback","Operate safely","monitor")])]},
 "Amazon Q Developer":{role:"an AI assistant for software development and AWS engineering workflows across IDE, command-line and cloud operations contexts",concepts:["It assists developers; source control and CI remain the authoritative change process.","Generated code or infrastructure changes still require review and testing.","Developer identity and repository/account permissions define what context/actions are available."],useCases:["Explain or generate application code.","Assist with AWS implementation and troubleshooting.","Refactor, test and document code before normal CI/CD."],cost:["Developer subscription/entitlement is distinct from deployed AWS workload cost.","Generated suggestions do not remove CI/test/build charges.","Track developer productivity and quality outcomes, not only token-style usage."],architectures:[a("IDE-assisted development","Q Developer helps create/review code before it enters the normal repository and CI path.",[n("Developer","Intent / question","user"),n("IDE + repository context","Code","file")],n("Amazon Q Developer","Coding assistant","ai","awsCloud"),[n("Source repository","Reviewed change","file"),n("AWS CodeBuild","Tests/build",undefined,"codeBuild"),n("AWS CodePipeline","Delivery",undefined,"codePipeline")]),a("AWS troubleshooting assistant","Operational context can guide investigation, but actual telemetry and AWS APIs remain separate sources of truth.",[n("Engineer","Troubleshooting question","user"),n("CloudWatch / logs","Evidence","monitor","cloudWatch")],n("Amazon Q Developer","Assist investigation","ai","awsCloud"),[n("Suggested diagnosis","Human review","file"),n("AWS CLI / console","Approved action","app")])]},
 "Amazon Quick":{role:"provides an AI-assisted business intelligence and analysis experience for turning governed data into questions, insights and consumable business outputs",concepts:["Keep governed datasets separate from the conversational/analysis experience.","BI semantics and data permissions still matter when natural language is used.","The visual/AI layer should not become a duplicate system of record."],useCases:["Natural-language business analysis.","Executive or operational insight generation.","Reusable dashboards/analysis experiences over governed data."],cost:["User/reader/author or capacity-style BI economics should be evaluated against audience size.","Direct-query versus cached/in-memory data choices can shift downstream query cost.","Data-source and refresh costs remain separate."],architectures:[a("AI-assisted business analysis","Governed datasets feed an analysis layer used by business users for questions and visual insight.",[n("Governed dataset","Curated business data","file"),n("Analyst","Question / analysis","user")],n("Amazon Quick","AI-assisted BI","ai","awsCloud"),[n("Visual insight","Charts / narrative","file"),n("Business consumer","Decision","user")]),a("Enterprise analytics consumption","Multiple data sources are modeled and governed before users consume reusable analyses.",[n("Amazon S3","Data lake",undefined,"s3"),n("Amazon RDS","Operational data",undefined,"rds")],n("Amazon Quick","Semantic/analysis layer","ai","awsCloud"),[n("Dashboard / app","Published insight","app"),n("Access policy","Row/user controls","security")])]},
 "Amazon Nova":{role:"an Amazon foundation-model family available through Amazon Bedrock for multimodal and generative AI workloads",concepts:["Nova is a model choice inside the Bedrock inference boundary, not a standalone data store or orchestration service.","Model capability, latency and price should be matched to the task.","Grounding, agents and guardrails are separate Bedrock/application capabilities."],useCases:["Text and multimodal generation.","Reasoning/agent workloads through Bedrock.","Model selection based on task, latency and cost."],cost:["Inference input/output consumption depends on the selected Nova model.","Provisioned/batch/caching options, where available, change economics.","RAG, agents and storage are separate cost layers."],architectures:[a("Nova model inference through Bedrock","Applications invoke Nova through Bedrock; Nova does not replace the application or its data layer.",[n("GenAI application","Prompt / media","app"),n("Enterprise context","Optional grounding","file")],n("Amazon Bedrock","Amazon Nova model","ai","bedrock"),[n("Generated response","Text / multimodal","file"),n("Guardrails","Safety policy","security")]),a("Nova in a grounded application","Retrieval happens before model generation so source documents remain independently governed.",[n("User","Question","user"),n("Amazon S3","Documents",undefined,"s3")],n("Amazon Bedrock","Nova + grounded context","ai","bedrock"),[n("AWS Lambda","Application/tool logic",undefined,"lambda"),n("Grounded answer","Response","file")])]},
 "Amazon Titan":{role:"an Amazon model family delivered through Amazon Bedrock, commonly used for supported text, image or embedding capabilities depending on model",concepts:["Titan is a model family inside Bedrock, not the retrieval store itself.","Embedding models create vectors; generation models produce content—do not confuse the two roles.","Application code chooses the model and owns how outputs are used."],useCases:["Generate embeddings for semantic retrieval.","Supported generative workloads through Bedrock.","Create a model layer inside a larger RAG/AI application."],cost:["Inference usage depends on the selected Titan model and modality.","Embedding generation has a different access pattern from generative inference.","Vector storage/retrieval and application compute are separate costs."],architectures:[a("Titan embedding workflow","Documents are chunked and embedded; the vectors are stored separately for later retrieval.",[n("Documents","Chunks","file"),n("Application","Embedding request","app")],n("Amazon Bedrock","Titan Embeddings","ai","bedrock"),[n("Vector store","Embeddings","file"),n("Semantic search","Nearest matches","app")]),a("Titan model inside RAG","Retrieval supplies relevant context to the model; the model does not search the corpus by itself.",[n("User","Question","user"),n("Vector retrieval","Relevant chunks","file")],n("Amazon Bedrock","Titan model","ai","bedrock"),[n("Grounded response","Generated answer","file"),n("Application","Present/cite","app")])]},
};

function PIcon({kind}:{kind:NonNullable<Node["icon"]>}){const C=kind==="user"?Users:kind==="file"?FileText:kind==="ai"?BrainCircuit:kind==="message"?MessageSquare:kind==="monitor"?Activity:kind==="security"?Shield:kind==="app"?Laptop:Server;return <div className="public-icon-disc"><C size={36}/></div>}
function N({node,featured=false}:{node:Node;featured?:boolean}){if(node.awsIcon){const icon=awsArchitectureIcons[node.awsIcon]||awsArchitectureIcons.awsCloud;return <div className={`dynamic-node ${featured?"featured":""}`}><div className="aws-icon-disc"><img src={awsIconSrc(icon)} data-fallback={awsIconFallbackSrc(icon)} data-cloud={awsIconFallbackSrc(awsArchitectureIcons.awsCloud)} onError={e=>{const i=e.currentTarget;const f=i.dataset.fallback,c=i.dataset.cloud;if(f&&i.src!==f){i.src=f;return}if(c&&i.src!==c){i.src=c;return}i.onerror=null}} alt={`${node.label} architecture icon`}/></div><strong>{node.label}</strong><small>{node.sub}</small></div>}return <div className={`dynamic-node public ${featured?"featured":""}`}><PIcon kind={node.icon||"app"}/><strong>{node.label}</strong><small>{node.sub}</small></div>}
function ArchView({arch,index}:{arch:Arch;index:number}){return <section className="architecture-stage dynamic-architecture"><div className="section-cap"><div><p>ARCHITECTURE {String(index).padStart(2,"0")}</p><h3>{arch.title}</h3></div><span>{arch.note}</span></div><div className="dynamic-map"><div className="map-left">{arch.left.map((x,i)=><N key={i} node={x}/>)}</div><div className="map-arrow">→</div><N node={arch.center} featured/><div className="map-arrow">→</div><div className="map-branches">{arch.right.map((x,i)=><N key={i} node={x}/>)}</div></div></section>}
function Cards({title,items,id}:{title:string;items:string[];id?:string}){return <section className="knowledge-card" id={id}><div className="knowledge-card-title"><span>◆</span><h3>{title}</h3></div><div className="knowledge-card-body"><div className="concept-stack">{items.map((x,i)=><p key={i}><b>{String(i+1).padStart(2,"0")}</b>{x}</p>)}</div></div></section>}
function OverridePage({serviceName,data}:{serviceName:string;data:Override}){const security=[`Grant ${serviceName} only the identities and resources it actually needs.`,`Keep identity, data protection and audit controls separate from the service's functional role.`,`Review logs/findings/changes through the AWS service that is authoritative for that telemetry.`];return <div className="service-knowledge aip-shared-learning"><div className="knowledge-intro"><div><p className="knowledge-kicker">VISUAL DEEP DIVE • SERVICE-SPECIFIC</p><h2>{serviceName}</h2><p><b>What it is:</b> {data.role}.</p></div></div><div className="knowledge-grid"><Cards title="Core service concepts" items={data.concepts}/><Cards title="Where it fits" items={[data.role,"The diagrams below show two different real production patterns rather than a generic service-in-the-middle pipeline."]}/></div>{data.architectures.map((x,i)=><ArchView key={i} arch={x} index={i+1}/>)}<div className="knowledge-grid"><Cards title="Practical use cases" items={data.useCases}/><Cards title="Security & governance" items={security}/><Cards title="Cost model & drivers" items={data.cost}/><Cards title="Certification memory hook" items={[`Remember the boundary: ${data.role}.`,`If an exam option makes ${serviceName} perform a role outside that boundary, eliminate it.`,`Trace the arrows in the architecture before choosing between adjacent AWS services.`]}/></div></div>}

export default function AipServiceLearningDetailsV4({serviceName}:{serviceName:string}){const data=overrides[serviceName];return data?<OverridePage serviceName={serviceName} data={data}/>:<V3 serviceName={serviceName}/>}
