"use client";

import { Activity, BrainCircuit, Database, FileText, Globe2, HardDrive, Laptop, MessageSquare, Network, Server, Shield, Users } from "lucide-react";
import { aipScope, guideAliases } from "../course-data";
import { awsArchitectureIcons, awsIconFallbackSrc, awsIconSrc, findAwsArchitectureIcon } from "../../lib/aws-architecture-icons";
import "./AthenaLearningDetails.css";
import "./AthenaAwsIcons.css";
import "./AipServiceLearningDetails.css";

type Kind="user"|"internet"|"app"|"data"|"security"|"file"|"network"|"storage"|"ai"|"message"|"monitor";
type Node={label:string;sub:string;kind?:Kind;icon?:string};
type Arch={title:string;note:string;left:Node[];center:Node;right:Node[]};
type Entry={service:string;category:string;alias?:string};
const N=(label:string,sub:string,kind?:Kind,icon?:string):Node=>({label,sub,kind,icon});
const A=(title:string,note:string,left:Node[],center:Node,right:Node[]):Arch=>({title,note,left,center,right});
const AWS=(label:string,sub:string,icon?:string)=>N(label,sub,undefined,icon);
const PUB=(label:string,sub:string,kind:Kind)=>N(label,sub,kind);
const C=(service:string,sub:string,icon?:string)=>AWS(service,sub,icon);

const entries:Entry[]=aipScope.flatMap(category=>category.services.map(service=>({service,category:category.title,alias:guideAliases[service]})));
const normalize=(v:string)=>v.toLowerCase().replace(/\([^)]*\)/g," ").replace(/\b(amazon|aws)\b/g," ").replace(/[^a-z0-9]+/g," ").trim();
const resolveEntry=(name:string)=>entries.find(x=>normalize(x.service)===normalize(name)||!!x.alias&&normalize(x.alias)===normalize(name));
export const aipDetailServices=new Set(entries.flatMap(x=>[x.service,x.alias].filter(Boolean) as string[]));
export const hasAipLearningDetails=(name:string)=>!!resolveEntry(name);
export const getAipLearningMeta=(name:string)=>{const e=resolveEntry(name);return e?{service:e.service,category:e.category,sections:["overview","concepts","architectures","use-cases","security","optimization","cost-models","comparison","memory-hook"]}:null};

const parentIcon=(service:string)=>{
 if(service.startsWith("Amazon Bedrock")||service==="Amazon Titan")return "Amazon Bedrock";
 if(service.startsWith("Amazon SageMaker"))return "Amazon SageMaker AI";
 if(service.startsWith("Amazon S3"))return "Amazon S3";
 if(service.startsWith("Amazon CloudWatch"))return "Amazon CloudWatch";
 if(service.startsWith("IAM")||service==="AWS IAM")return "AWS IAM";
 if(service==="AWS Lambda@Edge")return "AWS Lambda";
 if(service==="Elastic Load Balancing (ELB)")return "Elastic Load Balancing";
 return service;
};

function architectures(service:string,category:string):Arch[]{
 const icon=parentIcon(service);
 const center=(sub:string)=>C(service,sub,icon);
 switch(service){
 case "Amazon AppFlow": return [A("SaaS data ingestion","Salesforce and other supported SaaS data lands in an AWS data lake without custom connector code.",[PUB("Salesforce / SaaS","Business records","internet")],center("Managed connector + mapping"),[AWS("Amazon S3","Lake landing zone"),AWS("AWS Glue","Catalog / ETL")]),A("Event-driven SaaS integration","Flow execution and change events feed downstream processing and monitoring.",[PUB("SaaS change","Source event","internet")],center("Transfer + transform"),[AWS("Amazon EventBridge","Route events"),AWS("AWS Lambda","Post-process"),PUB("Flow metrics","Failures / volume","monitor")])];
 case "AWS AppConfig": return [A("Safe feature rollout","Configuration is deployed independently from application binaries and guarded by validation and alarms.",[PUB("Platform team","Config / flag","user")],center("Validate + deploy config"),[AWS("AWS Lambda","Runtime consumer"),AWS("Amazon EC2","Fleet consumer"),PUB("Rollback alarm","Guardrail","monitor")]),A("Configuration automation","Deployment lifecycle events drive notifications and automated response.",[PUB("Release pipeline","Versioned config","app")],center("Deployment strategy"),[AWS("Amazon EventBridge","Deployment events"),AWS("Amazon SNS","Notify operators"),PUB("CloudWatch alarm","Rollback signal","monitor")])];
 case "Amazon EventBridge": return [A("Event bus routing","Rules match AWS, custom and SaaS events and route each event to the right target.",[PUB("Custom app","Domain event","app"),PUB("SaaS partner","Partner event","internet")],center("Event bus + rules"),[AWS("AWS Lambda","Function target"),AWS("Amazon SQS","Buffered target"),AWS("AWS Step Functions","Workflow target")]),A("Cross-account event backbone","Producer accounts send events to a central or domain event bus for decoupled consumers.",[PUB("Workload account A","Events","app"),PUB("Workload account B","Events","app")],center("Cross-account bus"),[PUB("Consumer account","Rules + targets","app"),AWS("Amazon SQS","Central processing"),PUB("Archive / replay","Recovery","monitor")])];
 case "Amazon SNS": return [A("Pub/sub fan-out","One event is pushed to multiple independent subscribers.",[PUB("Publisher","Business event","app")],center("Topic"),[AWS("Amazon SQS","Durable subscriber"),AWS("AWS Lambda","Function subscriber"),PUB("Email / HTTPS","External subscriber","message")]),A("Durable fan-out","SNS plus separate SQS queues isolates consumer speed and failure domains.",[PUB("Application","Event","app")],center("Fan-out topic"),[AWS("Amazon SQS","Consumer A queue"),AWS("Amazon SQS","Consumer B queue"),PUB("Delivery status","Failures / retries","monitor")])];
 case "Amazon SQS": return [A("Buffered worker queue","The queue absorbs bursts while workers process messages at an independent rate.",[PUB("Producers","Jobs / requests","app")],center("Standard queue"),[AWS("AWS Lambda","Elastic workers"),PUB("DLQ","Poison messages","message"),PUB("Queue age","Backlog signal","monitor")]),A("Ordered workflow","FIFO queues preserve order within message groups and support deduplication.",[PUB("Ordered jobs","Sequenced work","app")],center("FIFO queue"),[AWS("AWS Lambda","Controlled consumer"),AWS("Amazon DynamoDB","Job state"),AWS("Amazon S3","Artifacts")])];
 case "AWS Step Functions": return [A("GenAI orchestration","A state machine coordinates model calls, tools, retries, choices and durable workflow state.",[PUB("API / event","Start execution","app")],center("State machine"),[AWS("Amazon Bedrock","Model step"),AWS("AWS Lambda","Tool step"),AWS("Amazon DynamoDB","Workflow state")]),A("Human approval callback","Long-running executions wait for external approval using callback/task-token patterns.",[PUB("Requester","Submit task","user")],center("Wait + choice"),[PUB("Reviewer","Approve / reject","user"),PUB("Task token","Callback","message"),PUB("Final action","Continue workflow","app")])];
 case "AWS App Runner": return [A("Managed web service from source","Source is built and deployed as an autoscaled HTTPS service.",[PUB("Git repository","Source code","file")],center("Build + deploy service"),[PUB("Internet clients","HTTPS","user"),AWS("Amazon RDS","Application data"),PUB("Service metrics","Latency / instances","monitor")]),A("Container image deployment","A tested ECR image becomes a managed App Runner service with runtime integrations.",[AWS("Amazon ECR","Container image")],center("Managed runtime"),[AWS("AWS Secrets Manager","Runtime secrets"),AWS("Amazon Bedrock","GenAI API"),PUB("Deployment events","Operate","monitor")])];
 case "Amazon EC2": return [A("Multi-AZ application tier","Load balancing distributes requests across instances while durable state stays outside compute.",[PUB("Clients","HTTPS","user"),AWS("Elastic Load Balancing","Distribute traffic")],center("Application instances"),[AWS("Amazon EBS","Block storage"),AWS("Amazon RDS","Database"),PUB("CloudWatch","Host / app metrics","monitor")]),A("GPU model host","EC2 is appropriate when accelerator, OS, driver or runtime control is required.",[AWS("Amazon S3","Model artifacts"),PUB("Private VPC","Controlled access","network")],center("GPU / custom runtime"),[PUB("Inference endpoint","Application traffic","app"),AWS("Amazon EBS","Model data"),PUB("IAM role","AWS API access","security")])];
 case "AWS Lambda": return [A("Event-driven function","Push events and event-source mappings invoke stateless serverless compute.",[AWS("Amazon API Gateway","HTTP request"),AWS("Amazon S3","Object event"),AWS("Amazon SQS","Pulled messages")],center("Function"),[AWS("Amazon DynamoDB","State"),AWS("Amazon Bedrock","Model call"),PUB("CloudWatch","Logs + metrics","monitor")]),A("Bedrock agent tool","Lambda implements deterministic actions and enterprise API calls around managed models.",[AWS("Amazon Bedrock","Agent action"),PUB("Application","Tool request","app")],center("Business action"),[PUB("Enterprise API","Action target","app"),AWS("AWS Secrets Manager","Credentials"),PUB("AWS X-Ray","Trace","monitor")])];
 case "AWS Lambda@Edge": return [A("Viewer request customization","CloudFront invokes Lambda@Edge near viewers to customize requests and responses.",[PUB("Global viewers","HTTPS","user")],AWS("Amazon CloudFront","Distribution"),[center("Viewer request / response"),AWS("Amazon S3","Origin"),PUB("Auth / header logic","Edge mutation","security")]),A("Origin request routing","Edge logic can rewrite paths, headers or origin selection before regional processing.",[PUB("Users","Request","user"),AWS("Amazon Route 53","DNS")],AWS("Amazon CloudFront","Edge entry"),[center("Origin request logic"),PUB("Primary origin","Origin A","app"),PUB("Alternate origin","Origin B","app")])];
 case "AWS Outposts": return [A("AWS infrastructure on premises","Outposts runs AWS compute/storage at the customer site while remaining connected to the parent Region.",[PUB("Customer LAN","Local apps","network")],center("On-prem AWS capacity"),[AWS("Amazon EC2","Local instances"),AWS("Amazon EBS","Local storage"),PUB("AWS Region","Control plane","internet")]),A("Hybrid low-latency tier","Latency-sensitive processing stays on premises while regional managed services provide durable capabilities.",[PUB("Site users","Local traffic","user"),PUB("On-prem systems","Local dependency","data")],center("Local application tier"),[AWS("Amazon S3","Regional objects"),AWS("Amazon RDS","Regional database"),PUB("Regional operations","Management","monitor")])];
 case "AWS Wavelength": return [A("5G edge application","Carrier-network devices reach compute in a Wavelength Zone with a short latency path.",[PUB("5G device","Mobile traffic","user"),PUB("Carrier network","5G path","network")],center("Wavelength Zone"),[AWS("Amazon EC2","Edge compute"),PUB("AWS Region","Regional services","internet"),PUB("Latency metrics","Operate","monitor")]),A("Regional hub with edge spokes","Regional durable state supports multiple edge locations serving latency-sensitive requests.",[PUB("Mobile users","Nearest edge","user")],center("Edge application"),[AWS("Amazon S3","Durable objects"),AWS("Amazon DynamoDB","Regional state"),PUB("Carrier gateway","Connectivity","network")])];
 case "Amazon ECR": return [A("Container image supply chain","CI builds, scans and stores immutable images for runtime platforms.",[PUB("Source code","Commit","file"),AWS("AWS CodeBuild","Build image")],center("Private registry"),[AWS("Amazon ECS","Pull image"),AWS("Amazon EKS","Pull image"),PUB("Image scanning","Findings","security")]),A("Image replication","Approved images replicate to other accounts or Regions and lifecycle policies remove stale versions.",[PUB("Build account","Signed image","app")],center("Versioned repository"),[PUB("Production account","Deployment","app"),PUB("Cross-Region replica","Distribution","storage"),PUB("Lifecycle policy","Retention","monitor")])];
 case "Amazon ECS": return [A("ECS service on Fargate","ECS owns service/task scheduling while Fargate supplies serverless container compute.",[AWS("Elastic Load Balancing","Application entry"),AWS("Amazon ECR","Image")],center("Service + scheduler"),[AWS("AWS Fargate","Tasks"),AWS("Amazon S3","Object data"),PUB("CloudWatch","Task telemetry","monitor")]),A("Queue-backed workers","A worker service scales from queue depth for asynchronous jobs.",[AWS("Amazon SQS","Work backlog")],center("Worker service"),[AWS("Amazon S3","Input / output"),AWS("Amazon DynamoDB","Job state"),PUB("Task role","Least privilege","security")])];
 case "Amazon EKS": return [A("Managed Kubernetes cluster","EKS manages the Kubernetes control plane while workloads run on managed nodes or Fargate.",[AWS("Amazon ECR","Images"),PUB("Platform team","GitOps / kubectl","user")],center("Kubernetes control plane"),[AWS("Amazon EC2","Managed node groups"),AWS("AWS Fargate","Serverless pods"),PUB("Cluster telemetry","Observe","monitor")]),A("GenAI microservices","Kubernetes services host gateways, agents and workers while Bedrock stays a managed model API.",[PUB("API clients","HTTPS","user")],center("Ingress + services"),[PUB("Agent pods","Orchestration","ai"),PUB("Worker pods","Tools","app"),AWS("Amazon Bedrock","Model API")])];
 case "AWS Fargate": return [A("Serverless ECS tasks","ECS schedules tasks while Fargate provides isolated vCPU and memory without EC2 worker management.",[AWS("Amazon ECR","Image"),AWS("Amazon ECS","Task definition")],center("Task compute"),[PUB("Application task","Stateless workload","app"),AWS("Amazon S3","Durable data"),PUB("CloudWatch","Logs / metrics","monitor")]),A("Serverless EKS pods","EKS Fargate profiles schedule selected pods onto serverless compute.",[AWS("Amazon EKS","Pod scheduling"),PUB("Fargate profile","Namespace selector","app")],center("Pod compute"),[PUB("Application pods","Workload","app"),AWS("AWS Secrets Manager","Secrets"),PUB("Observability","Pod telemetry","monitor")])];
 case "Amazon Connect": return [A("AI-assisted contact center","Voice/chat contacts enter managed flows that can invoke bots and business logic before human escalation.",[PUB("Customer","Voice / chat","user")],center("Contact flow"),[AWS("Amazon Lex","Self service"),AWS("AWS Lambda","Business lookup"),PUB("Human agent","Escalation","user")]),A("Contact analytics pipeline","Recordings and transcripts feed durable storage and analytics while sensitive data is governed separately.",[PUB("Conversation","Audio / chat","message")],center("Contact handling"),[AWS("Amazon S3","Recordings"),AWS("Amazon Kinesis","Streaming events"),PUB("Analytics / QA","Insights","monitor")])];
 case "Amazon Aurora": return [A("Highly available relational application","Applications connect to a clustered relational database with replicas across Availability Zones.",[PUB("Application tier","SQL traffic","app")],center("Aurora cluster"),[PUB("Writer instance","Writes","data"),PUB("Reader replicas","Scale reads","data"),AWS("Amazon S3","Backups / exports")]),A("Serverless relational backend","Elastic database capacity supports variable application demand while integrations remain managed.",[AWS("AWS Lambda","Application logic"),PUB("API layer","Requests","app")],center("Elastic SQL database"),[AWS("AWS Secrets Manager","Credentials"),PUB("Read replicas","Read scaling","data"),PUB("Monitoring","DB metrics","monitor")])];
 case "Amazon DocumentDB": return [A("Document application backend","JSON-like document workloads connect to a managed MongoDB-compatible cluster.",[PUB("Application services","Document queries","app")],center("Document cluster"),[PUB("Primary","Writes","data"),PUB("Replicas","Read scaling","data"),PUB("CloudWatch","DB metrics","monitor")]),A("Private document service","Applications inside a VPC use TLS and secrets while backups protect the cluster.",[PUB("Private app tier","TLS connection","network")],center("Document database"),[AWS("AWS Secrets Manager","Credentials"),PUB("Automated backups","Recovery","storage"),PUB("Audit logs","Governance","monitor")])];
 case "Amazon DynamoDB": return [A("Serverless key-value application","API or Lambda functions use partition-key access patterns against serverless tables.",[AWS("Amazon API Gateway","Requests"),AWS("AWS Lambda","Business logic")],center("Table"),[PUB("GSIs","Alternate access","data"),AWS("Amazon DynamoDB Streams","Change events"),PUB("CloudWatch","Capacity / latency","monitor")]),A("Global low-latency state","Global tables replicate items across Regions for multi-Region applications.",[PUB("Region A app","Reads / writes","app")],center("Global table"),[PUB("Region B replica","Multi-Region state","data"),AWS("AWS Lambda","Stream processor"),PUB("PITR / backup","Recovery","storage")])];
 case "Amazon DynamoDB Streams": return [A("Change-data processing","Item mutations appear on a time-ordered stream consumed by Lambda.",[AWS("Amazon DynamoDB","Table writes")],center("Change stream"),[AWS("AWS Lambda","Event source mapping"),AWS("Amazon OpenSearch Service","Search index"),PUB("Audit projection","Derived state","data")]),A("Event-driven materialized views","Stream consumers build secondary projections without coupling them to the write request path.",[PUB("Application","Table update","app"),AWS("Amazon DynamoDB","Source table")],center("Ordered item changes"),[AWS("AWS Lambda","Projection worker"),AWS("Amazon S3","History archive"),PUB("Metrics / retries","Operate","monitor")])];
 case "Amazon ElastiCache": return [A("Cache-aside application","Applications check an in-memory cache before going to the durable database.",[PUB("Application tier","Read / write","app")],center("Redis / Valkey cache"),[AWS("Amazon RDS","Source of truth"),PUB("TTL / eviction","Cache lifecycle","data"),PUB("Cache metrics","Hit rate / memory","monitor")]),A("Session and low-latency state","Distributed application instances share short-lived state in a replicated cache cluster.",[PUB("Web fleet","Sessions","app")],center("Replicated cache"),[PUB("Multi-AZ replica","Availability","data"),PUB("Failover","Resilience","monitor"),PUB("Durable store","Long-term state","storage")])];
 case "Amazon Neptune": return [A("Knowledge graph for GenAI","Entities and relationships are stored as a graph and queried for connected context.",[PUB("Enterprise entities","Nodes / edges","data")],center("Graph database"),[AWS("Amazon Bedrock","Grounded generation"),PUB("Graph query app","Gremlin / SPARQL","app"),PUB("Graph analytics","Relationships","ai")]),A("Graph-backed recommendation/fraud","Applications traverse relationships to score connected behavior and return explainable paths.",[PUB("Events / profiles","Relationship data","data")],center("Graph cluster"),[PUB("Recommendation service","Connected items","app"),PUB("Fraud analysis","Suspicious paths","security"),PUB("Snapshots","Recovery","storage")])];
 case "Amazon RDS": return [A("Multi-AZ relational backend","Application traffic uses a managed relational database with standby/failover and automated backups.",[PUB("Application tier","SQL traffic","app")],center("RDS database"),[PUB("Multi-AZ standby","Failover","data"),PUB("Read replica","Read scaling","data"),AWS("AWS Secrets Manager","Credentials")]),A("Analytics offload","Operational data is replicated or extracted so analytical work does not overload the primary database.",[PUB("OLTP application","Transactions","app")],center("Managed SQL"),[AWS("AWS DMS","Change replication"),AWS("Amazon S3","Lake destination"),PUB("CloudWatch","DB metrics","monitor")])];
 case "AWS Amplify": return [A("Full-stack web application","Frontend hosting, authentication and API/data backends combine into a managed web delivery workflow.",[PUB("Git repository","Frontend source","file")],center("Build + host web app"),[AWS("Amazon CloudFront","Global delivery"),AWS("Amazon Cognito","Authentication"),AWS("AWS AppSync","GraphQL API")]),A("GenAI web experience","A hosted frontend authenticates users and calls a protected backend that invokes Bedrock.",[PUB("Browser / mobile","User interface","user")],center("Frontend hosting"),[AWS("Amazon Cognito","Identity"),AWS("AWS Lambda","Backend logic"),AWS("Amazon Bedrock","Model inference")])];
 case "AWS CDK": return [A("Infrastructure as code pipeline","Developers define constructs that synthesize CloudFormation templates and deploy stacks.",[PUB("Developer","CDK code","user"),PUB("Source repository","Version control","file")],center("Synthesize infrastructure"),[AWS("AWS CloudFormation","Deploy stacks"),PUB("AWS resources","Provisioned estate","app"),PUB("CI checks","Validate","monitor")]),A("Reusable platform constructs","Platform teams package approved constructs for product teams to consume consistently.",[PUB("Platform team","Construct library","user")],center("Reusable CDK app"),[AWS("AWS CodeArtifact","Package distribution"),AWS("AWS CodePipeline","Delivery"),AWS("AWS CloudFormation","Environment deployment")])];
 case "AWS CLI": return [A("Operator to AWS APIs","The CLI signs requests with temporary credentials and invokes AWS service APIs rather than hosting workload traffic.",[PUB("Engineer / script","Commands","user"),PUB("IAM credentials","Temporary session","security")],center("Command-line client"),[PUB("AWS service APIs","Control plane","app"),AWS("AWS CloudTrail","API audit"),PUB("Shell / CI","Automation","app")]),A("CI/CD administration","Pipeline jobs use the CLI for repeatable deployment and operational actions with scoped roles.",[PUB("CI runner","aws commands","app")],center("Authenticated API calls"),[AWS("AWS CloudFormation","Stack actions"),AWS("Amazon S3","Artifact actions"),AWS("Amazon ECR","Registry actions")])];
 case "AWS CloudFormation": return [A("Infrastructure stack deployment","Templates declare resources and CloudFormation creates them in dependency order.",[PUB("Template","YAML / JSON","file"),PUB("Pipeline / operator","Deploy stack","user")],center("Stack engine"),[PUB("AWS resources","Create / update","app"),PUB("Change set","Review delta","monitor"),AWS("AWS CloudTrail","Audit API calls")]),A("Multi-account deployment","Reusable templates and StackSets roll governed infrastructure across accounts and Regions.",[PUB("Platform account","StackSet admin","app")],center("Governed IaC"),[PUB("Account A","Stack instance","app"),PUB("Account B","Stack instance","app"),PUB("Drift detection","Configuration variance","monitor")])];
 case "AWS CodeArtifact": return [A("Private package repository","Build systems fetch approved dependencies and publish internal packages through a managed artifact domain.",[PUB("Developers","npm / pip / Maven","user"),PUB("Public package repo","Upstream source","internet")],center("Package domain / repository"),[AWS("AWS CodeBuild","Build consumer"),PUB("Internal packages","Versioned artifacts","file"),PUB("Repository policy","Access control","security")]),A("Controlled dependency supply chain","An upstream repository caches external dependencies before they reach production builds.",[PUB("Public registries","External packages","internet")],center("Upstream + private repos"),[AWS("AWS CodeBuild","Validated build"),AWS("AWS CodePipeline","Release flow"),PUB("Audit / versions","Traceability","monitor")])];
 case "AWS CodeBuild": return [A("Containerized CI build","A source change triggers an isolated build environment that produces tested artifacts.",[PUB("Source repository","Commit","file"),AWS("AWS CodePipeline","Build stage")],center("Build environment"),[AWS("Amazon ECR","Container image"),AWS("Amazon S3","Build artifact"),PUB("Test reports","Quality gate","monitor")]),A("GenAI application build","CI packages Lambda/container code and promotes artifacts into deployment stages.",[PUB("Application source","Code + tests","file")],center("Compile / test / package"),[AWS("AWS Lambda","Deployment package"),AWS("Amazon ECR","Image artifact"),AWS("AWS CodeDeploy","Release")])];
 case "AWS CodeDeploy": return [A("Blue/green application deployment","Deployment groups shift traffic between old and new versions with health checks and rollback.",[PUB("Release artifact","New version","file")],center("Deployment controller"),[AWS("Amazon EC2","Instance fleet"),AWS("AWS Lambda","Function version"),PUB("Traffic shift","Blue / green","network")]),A("Automated rollback","Alarms stop or roll back a release when deployment health degrades.",[AWS("AWS CodePipeline","Release trigger")],center("Deployment lifecycle"),[PUB("CloudWatch alarm","Rollback signal","monitor"),PUB("Healthy target","Promoted version","app"),PUB("Failed target","Rollback","security")])];
 case "AWS CodePipeline": return [A("Continuous delivery pipeline","Source, build, test and deploy stages promote a version through controlled gates.",[PUB("Source repository","Commit","file")],center("Delivery pipeline"),[AWS("AWS CodeBuild","Build / test"),AWS("AWS CodeDeploy","Deploy"),PUB("Approval gate","Manual / automated","user")]),A("Infrastructure delivery","A pipeline synthesizes and validates infrastructure before controlled CloudFormation deployment.",[PUB("IaC repository","Template / CDK","file")],center("Release orchestration"),[AWS("AWS CodeBuild","Validate"),AWS("AWS CloudFormation","Deploy stack"),PUB("Production account","Target environment","app")])];
 case "Kiro": return [A("AI-assisted development workflow","A developer uses the coding assistant against a local/project codebase, then normal source-control and CI systems validate the result.",[PUB("Developer","Prompt / edit","user"),PUB("Project code","Repository context","file")],center("AI coding workflow"),[PUB("Git repository","Reviewed changes","file"),AWS("AWS CodeBuild","Build / test"),PUB("Code review","Human gate","user")]),A("AWS application implementation","Generated implementation is grounded in project context and deployed through standard AWS delivery tooling.",[PUB("Architecture / spec","Requirements","file")],center("Implementation assistant"),[AWS("AWS CDK","Infrastructure code"),AWS("AWS Lambda","Application code"),AWS("AWS CodePipeline","Delivery")])];
 case "AWS Tools and SDKs": return [A("Application SDK integration","Application code uses an AWS SDK with a credential provider chain to call service APIs.",[PUB("Application code","SDK client","app"),PUB("IAM role / identity","Temporary credentials","security")],center("AWS SDK / tool"),[PUB("AWS service API","Signed request","app"),AWS("AWS CloudTrail","API audit"),PUB("Retry / telemetry","Client behavior","monitor")]),A("Local-to-production development","The same service APIs are invoked from developer tooling and production runtimes with environment-appropriate identities.",[PUB("Developer workstation","Local tools","user"),PUB("Production runtime","App role","app")],center("SDK abstraction"),[AWS("Amazon S3","Example API"),AWS("Amazon Bedrock","Model API"),AWS("Amazon DynamoDB","Data API")])];
 case "AWS X-Ray": return [A("Distributed request tracing","Instrumented services emit trace segments so a request can be followed across dependencies.",[PUB("Client request","Trace root","user"),AWS("Amazon API Gateway","Entry")],center("Trace collection"),[AWS("AWS Lambda","Function segment"),PUB("Downstream service","Dependency span","app"),PUB("Service map","Latency / errors","monitor")]),A("GenAI latency investigation","Tracing separates application, tool and downstream latency around a model request.",[PUB("GenAI application","Request","app")],center("Trace analysis"),[AWS("AWS Lambda","Tool latency"),AWS("Amazon Bedrock","Model call"),PUB("Error hotspots","Troubleshoot","monitor")])];
 default: break;
 }

 // Service-family specific patterns ensure every remaining AIP service has diagrams even when it is a capability rather than a standalone runtime service.
 if(service.startsWith("Amazon Bedrock")||service==="Amazon Titan"){
  if(service.includes("Knowledge Bases"))return [A("RAG ingestion","Documents are parsed, chunked and embedded before vectors are stored for retrieval.",[AWS("Amazon S3","Source documents")],center("Managed RAG ingestion"),[AWS("Amazon OpenSearch Service","Vector index"),PUB("Embeddings","Vector representation","ai")]),A("RAG runtime","The user query retrieves relevant chunks that are supplied as context to a foundation model.",[PUB("User query","Question","user")],center("Retrieve context"),[PUB("Vector store","Nearest chunks","data"),AWS("Amazon Bedrock","Foundation model"),PUB("Grounded answer","Response","ai")])];
  if(service.includes("AgentCore"))return [A("Agent runtime with tools","AgentCore provides managed runtime capabilities around an agent that invokes models and enterprise tools.",[PUB("User / application","Agent request","user")],center("Agent runtime"),[AWS("Amazon Bedrock","Model reasoning"),AWS("AWS Lambda","Tool action"),PUB("Enterprise API","Business action","app")]),A("Agent operations","Identity, memory/observability and governed tool access are separated from the agent business logic.",[PUB("Agent developer","Deploy / configure","user")],center("Managed agent services"),[PUB("Identity controls","Authenticate","security"),PUB("Agent telemetry","Observe","monitor"),PUB("Memory / state","Conversation context","data")])];
  if(service.includes("Prompt Management"))return [A("Versioned prompt lifecycle","Prompt templates are created, tested and versioned before applications consume approved variants.",[PUB("Prompt engineer","Template + variables","user")],center("Prompt versions"),[AWS("Amazon Bedrock","Model testing"),PUB("Approved variant","Application use","file"),PUB("Evaluation results","Quality evidence","monitor")]),A("Runtime prompt invocation","An application resolves the approved prompt and invokes a model with runtime variables.",[PUB("Application","Prompt variables","app")],center("Managed prompt"),[AWS("Amazon Bedrock","Model inference"),PUB("Response","Generated output","ai"),PUB("Telemetry","Latency / quality","monitor")])];
  if(service.includes("Prompt Flows"))return [A("Visual GenAI workflow","Flow nodes connect prompts, model calls and deterministic functions into an executable graph.",[PUB("Input","User / event","user")],center("Prompt flow"),[AWS("Amazon Bedrock","Model node"),AWS("AWS Lambda","Function node"),PUB("Flow output","Result","ai")]),A("RAG flow","A flow combines retrieval, prompt construction and generation as separate steps.",[PUB("Question","Runtime input","user")],center("Flow orchestration"),[AWS("Amazon Bedrock Knowledge Bases","Retrieval","Amazon Bedrock"),AWS("Amazon Bedrock","Generation"),PUB("Grounded response","Output","ai")])];
  return [A("Foundation model application","A protected application invokes Bedrock models while prompts and application state stay outside the model endpoint.",[PUB("Application / user","Prompt","app")],center("Managed foundation models"),[PUB("Model response","Generated output","ai"),AWS("AWS Lambda","Tool / business logic"),PUB("Telemetry","Latency / tokens","monitor")]),A("Grounded enterprise assistant","Private documents are retrieved and supplied as context before model generation.",[AWS("Amazon S3","Enterprise documents")],AWS("Amazon Bedrock Knowledge Bases","Retrieve context","Amazon Bedrock"),[center("Generate answer"),PUB("User","Grounded response","user"),PUB("Guardrails / policy","Safety controls","security")])];
 }
 if(service.startsWith("Amazon SageMaker")){
  const capability=service.replace("Amazon SageMaker ","");
  if(capability==="Ground Truth")return [A("Managed data labeling","Raw datasets are distributed to human or automated labeling workflows and returned as labeled training data.",[AWS("Amazon S3","Unlabeled dataset")],center("Labeling job","Amazon SageMaker AI"),[PUB("Human workforce","Labels","user"),PUB("Labeled manifest","Training input","file")]),A("Active learning loop","Model-assisted labeling reduces human work by selecting uncertain examples for review.",[PUB("Pre-label model","Suggested labels","ai")],center("Human-in-the-loop labeling","Amazon SageMaker AI"),[PUB("Reviewer","Correct uncertain items","user"),AWS("Amazon S3","Final labeled data")])];
  if(capability==="Model Registry")return [A("Model promotion workflow","Training outputs and metrics are registered as versioned model packages before approval.",[AWS("Amazon S3","Model artifact"),PUB("Training metrics","Evaluation","monitor")],center("Model package group","Amazon SageMaker AI"),[PUB("Approval gate","Approve / reject","user"),PUB("Model versions","Lineage","data")]),A("Approved model deployment","An approved registry version is promoted through CI/CD to a production endpoint.",[PUB("Approved version","Release candidate","file")],center("Model Registry","Amazon SageMaker AI"),[AWS("AWS CodePipeline","Deployment automation"),PUB("SageMaker endpoint","Production inference","ai"),PUB("Monitoring","Post-deploy quality","monitor")])];
  if(capability==="Model Monitor")return [A("Production model monitoring","Inference data and predictions are analyzed for drift, bias or data-quality deviation.",[PUB("Inference endpoint","Predictions","ai"),AWS("Amazon S3","Baseline / captures")],center("Monitoring schedule","Amazon SageMaker AI"),[PUB("Violation report","Drift / quality","monitor"),PUB("CloudWatch alarm","Notify / automate","monitor")]),A("Retraining trigger","Monitoring findings can feed an automated retraining or review workflow.",[PUB("Drift finding","Threshold breached","monitor")],center("Model quality control","Amazon SageMaker AI"),[AWS("AWS Step Functions","Retraining workflow"),PUB("Data scientist","Review","user"),PUB("New model version","Candidate","ai")])];
  if(capability==="Clarify")return [A("Bias analysis before training","Dataset statistics are analyzed for potential bias before model training.",[AWS("Amazon S3","Training dataset")],center("Bias analysis","Amazon SageMaker AI"),[PUB("Bias metrics","Pre-training report","monitor"),PUB("Data scientist","Review / remediate","user")]),A("Explainability for predictions","Feature attribution explains model predictions for evaluation and governance.",[PUB("Model endpoint","Prediction","ai"),PUB("Evaluation dataset","Examples","data")],center("Explainability job","Amazon SageMaker AI"),[PUB("Feature attribution","Explanation","monitor"),AWS("Amazon S3","Reports")])];
  if(capability==="Data Wrangler")return [A("Interactive data preparation","Data scientists import datasets, profile them and define repeatable transformations.",[AWS("Amazon S3","Raw data"),PUB("Data sources","Tables / files","data")],center("Data preparation flow","Amazon SageMaker AI"),[PUB("Transforms","Clean / encode","data"),AWS("Amazon S3","Prepared dataset")]),A("Operationalize preparation","A tested preparation flow becomes repeatable processing for training pipelines.",[PUB("Saved flow","Transformation graph","file")],center("Data Wrangler processing","Amazon SageMaker AI"),[PUB("Training dataset","Curated data","data"),PUB("SageMaker pipeline","ML workflow","ai")])];
  if(capability==="JumpStart")return [A("Start from pretrained model","A practitioner selects a pretrained model or solution and deploys or fine-tunes it in SageMaker.",[PUB("Model catalog","Pretrained model","ai")],center("JumpStart","Amazon SageMaker AI"),[PUB("Fine-tuning job","Adapt model","ai"),PUB("SageMaker endpoint","Deploy","ai")]),A("Private fine-tuning","Enterprise data in S3 adapts a selected foundation/model artifact before governed deployment.",[AWS("Amazon S3","Training data"),PUB("Selected model","Base weights","ai")],center("Fine-tune workflow","Amazon SageMaker AI"),[PUB("Model artifact","Versioned output","file"),PUB("Endpoint","Inference","ai")])];
  if(capability==="Neo")return [A("Optimize model for target hardware","A trained model is compiled for a chosen edge or inference target.",[AWS("Amazon S3","Trained model"),PUB("Target hardware","CPU / accelerator","app")],center("Neo compilation","Amazon SageMaker AI"),[PUB("Optimized artifact","Compiled model","file"),PUB("Edge / device runtime","Deployment target","app")]),A("Portable optimized inference","Compiled artifacts are distributed to constrained targets while model versions remain centrally governed.",[PUB("Approved model","Version","ai")],center("Hardware optimization","Amazon SageMaker AI"),[AWS("Amazon S3","Artifact distribution"),PUB("Edge fleet","Inference","network"),PUB("Latency metrics","Validate gain","monitor")])];
  if(capability==="Processing")return [A("Managed preprocessing job","Ephemeral managed compute transforms raw datasets before training.",[AWS("Amazon S3","Raw dataset"),PUB("Processing image","Transformation code","file")],center("Processing job","Amazon SageMaker AI"),[AWS("Amazon S3","Processed data"),PUB("Training job","Next ML stage","ai")]),A("Model evaluation job","Batch processing evaluates candidate predictions and produces quality reports.",[PUB("Candidate model","Model artifact","ai"),PUB("Evaluation dataset","Holdout data","data")],center("Evaluation processing","Amazon SageMaker AI"),[PUB("Metrics report","Quality gate","monitor"),PUB("Model Registry","Promotion decision","data")])];
  if(capability==="Unified Studio")return [A("Governed AI/data workspace","Teams discover governed data and build analytics/ML assets inside a shared project workspace.",[PUB("Data / AI team","Project members","user"),PUB("Governed datasets","Cataloged assets","data")],center("Unified Studio project","Amazon SageMaker AI"),[PUB("Notebooks / tools","Build","app"),PUB("Models / analytics","Project assets","ai"),PUB("Governance","Access policies","security")]),A("Project-to-production workflow","Workspace assets are developed collaboratively then promoted through governed delivery paths.",[PUB("Project code","Notebook / source","file")],center("Collaborative workspace","Amazon SageMaker AI"),[PUB("ML pipeline","Automate","ai"),PUB("Production endpoint","Serve","app"),PUB("Lineage / audit","Govern","monitor")])];
  return [A("End-to-end ML lifecycle","Data is prepared and training jobs create versioned model artifacts for deployment.",[AWS("Amazon S3","Training data"),PUB("Data scientist","Experiment / code","user")],center("Managed ML workflow","Amazon SageMaker AI"),[PUB("Training job","Fit model","ai"),PUB("Model Registry","Version / approve","data"),PUB("Endpoint","Real-time inference","ai")]),A("Production MLOps","Approved model versions are deployed through automation and monitored for quality and drift.",[PUB("Approved model","Registry version","ai")],center("Production ML platform","Amazon SageMaker AI"),[AWS("AWS CodePipeline","Promotion"),PUB("Inference endpoint","Serve traffic","app"),PUB("Model Monitor","Quality / drift","monitor")])];
 }

 // Remaining services receive category-aware, service-role-specific patterns rather than an empty architecture section.
 const fallbackByCategory:Record<string,()=>Arch[]>={
  "Database":()=>[A(`${service} application pattern`,`Application traffic uses the database according to its native data model while state, security and observability remain explicit.`,[PUB("Application tier","Reads / writes","app")],center("Managed data service"),[PUB("Primary data path","Native data model","data"),PUB("Backup / recovery","Durability","storage"),PUB("Database metrics","Operate","monitor")]),A(`${service} production pattern`,`Production access is private, authenticated and decoupled from analytics or downstream processing.`,[PUB("Private workload","Authenticated access","network")],center("Production database"),[AWS("AWS Secrets Manager","Credentials"),PUB("Replica / scale path","Performance","data"),PUB("Audit / monitoring","Governance","monitor")])],
  "Machine Learning":()=>[A(`${service} core AI workflow`,`The service receives the input type it is designed for and emits a model or AI result to the consuming application.`,[PUB("Application / dataset","Service-specific input","app")],center("Managed AI capability"),[PUB("AI result","Prediction / generation","ai"),AWS("Amazon S3","Input / output data"),PUB("Quality telemetry","Evaluate","monitor")]),A(`${service} production integration`,`A protected application integrates the AI capability with enterprise data, policy and operations.`,[PUB("Authenticated app","Request","user"),PUB("Enterprise context","Grounding / features","data")],center("Production AI service"),[PUB("Business workflow","Consume result","app"),PUB("Safety / access","Controls","security"),PUB("Observability","Latency / quality","monitor")])],
  "Management and Governance":()=>[A(`${service} governance pattern`,`The service observes or controls AWS resources through the management plane rather than sitting in the application data path.`,[PUB("AWS accounts / resources","Managed estate","app")],center("Control-plane capability"),[PUB("Findings / state","Governance output","monitor"),PUB("Operators","Review / action","user"),AWS("AWS CloudTrail","API evidence")]),A(`${service} multi-account operations`,`Central operations applies the capability consistently across workload accounts and automates response where appropriate.`,[PUB("Workload accounts","Signals / configuration","app")],center("Central governance"),[PUB("Operations team","Investigate","user"),AWS("Amazon EventBridge","Automation event"),AWS("AWS Lambda","Remediation action")])],
  "Migration and Transfer":()=>[A(`${service} transfer pattern`,`Source data moves through the managed transfer service into durable AWS storage.`,[PUB("On-prem / external source","Files / data","data")],center("Managed transfer"),[AWS("Amazon S3","AWS destination"),PUB("Transfer metrics","Throughput / errors","monitor")]),A(`${service} cutover pattern`,`Incremental synchronization reduces downtime before final cutover to the AWS-hosted destination.`,[PUB("Source system","Initial + delta data","data")],center("Incremental sync"),[PUB("AWS target","Cutover destination","app"),PUB("Verification","Integrity / status","monitor"),PUB("Network path","Private / secure","network")])],
  "Networking and Content Delivery":()=>[A(`${service} traffic path`,`The service is placed at the network layer it actually controls, with clients and target resources shown separately.`,[PUB("Clients / networks","Traffic source","network")],center("Network capability"),[PUB("Application targets","Destination","app"),PUB("Routing / policy","Traffic decision","network"),PUB("Flow telemetry","Observe","monitor")]),A(`${service} resilient pattern`,`Multiple targets or paths improve availability while security and health controls remain independent.`,[PUB("Users / source networks","Requests","user")],center("Resilient network layer"),[PUB("Healthy target A","Failure domain A","app"),PUB("Healthy target B","Failure domain B","app"),PUB("Health / policy","Failover control","monitor")])],
  "Security, Identity, and Compliance":()=>[A(`${service} security-control pattern`,`The service protects identities, secrets, data or traffic at its native control point.`,[PUB("Principal / workload","Request","user"),PUB("Protected resource","Security boundary","app")],center("Security capability"),[PUB("Allow / deny / protect","Control outcome","security"),PUB("Security finding / log","Evidence","monitor")]),A(`${service} governed production pattern`,`Central policy, auditable events and automated remediation connect the security control to operations.`,[PUB("Accounts / workloads","Protected estate","app")],center("Policy enforcement"),[AWS("AWS CloudTrail","Audit events"),AWS("Amazon EventBridge","Finding route"),PUB("Security team","Investigate / remediate","user")])],
  "Storage":()=>[A(`${service} storage pattern`,`Applications use the storage semantics appropriate to the service while lifecycle and access controls remain explicit.`,[PUB("Application / workload","Read / write","app")],center("Storage service"),[PUB("Stored data","Durable state","storage"),PUB("Access policy","Authorization","security"),PUB("Storage metrics","Capacity / access","monitor")]),A(`${service} resilience pattern`,`Replication, lifecycle or backup protects data independently from the workload using it.`,[PUB("Primary workload","Data producer","app")],center("Durable storage"),[PUB("Replica / archive","Recovery copy","storage"),PUB("Lifecycle policy","Tier / retain","monitor"),PUB("Recovery consumer","Restore / read","app")])],
  "Developer Tools":()=>[A(`${service} developer workflow`,`The tool participates in build, deployment or developer operations rather than the runtime request path.`,[PUB("Developer / source","Change","user")],center("Developer tool"),[PUB("Build / artifact","Output","file"),PUB("Deployment target","AWS workload","app"),PUB("Audit / status","Feedback","monitor")]),A(`${service} automated delivery`,`CI/CD uses the tool with temporary credentials and explicit promotion gates.`,[PUB("CI runner","Automated action","app"),PUB("IAM role","Temporary access","security")],center("Automation step"),[PUB("Validated output","Artifact / change","file"),PUB("Production environment","Promoted target","app"),PUB("Pipeline status","Operate","monitor")])],
  "Customer Engagement":()=>[A(`${service} customer interaction`,`Customer channels enter the managed engagement service and branch to automation or human handling.`,[PUB("Customer","Voice / chat / event","user")],center("Engagement service"),[PUB("Automation","Self service","ai"),PUB("Human agent","Escalation","user"),PUB("Conversation data","Record / transcript","data")]),A(`${service} enterprise integration`,`The engagement workflow invokes business systems and captures governed analytics.`,[PUB("Customer session","Interaction","user")],center("Managed engagement"),[PUB("CRM / enterprise API","Business context","app"),AWS("AWS Lambda","Integration logic"),PUB("Analytics","Quality / operations","monitor")])],
  "Containers":()=>[A(`${service} container platform`,`Images, orchestration and runtime capacity remain separate layers.`,[AWS("Amazon ECR","Container image")],center("Container capability"),[PUB("Running workload","Task / pod","app"),PUB("Service networking","Traffic","network"),PUB("Container telemetry","Operate","monitor")]),A(`${service} production platform`,`A production container stack combines immutable images, workload identity and durable external state.`,[PUB("CI/CD","Promote image","app")],center("Container runtime / control"),[AWS("AWS Secrets Manager","Runtime secrets"),AWS("Amazon S3","Durable data"),PUB("Autoscaling","Capacity response","monitor")])],
  "Compute":()=>[A(`${service} compute pattern`,`Requests or jobs reach the compute service while durable state is kept in managed data/storage services.`,[PUB("Users / events","Work input","user")],center("Compute service"),[AWS("Amazon S3","Durable objects"),AWS("Amazon DynamoDB","Application state"),PUB("CloudWatch","Runtime telemetry","monitor")]),A(`${service} production scaling`,`Independent scaling and explicit security controls keep compute replaceable and observable.`,[PUB("Application traffic","Demand","app")],center("Scaled compute"),[PUB("Downstream API","Business dependency","app"),PUB("IAM role","AWS access","security"),PUB("Metrics / alarms","Scale signal","monitor")])],
  "Application Integration":()=>[A(`${service} integration pattern`,`Producers and consumers are decoupled through the integration capability.`,[PUB("Producer","Event / message","app")],center("Integration service"),[PUB("Consumer A","Independent processing","app"),PUB("Consumer B","Independent processing","app"),PUB("Failure path","Retry / DLQ","monitor")]),A(`${service} production integration`,`A production topology makes delivery semantics, retries and observability explicit.`,[PUB("Domain service","Publish / send","app")],center("Managed integration"),[AWS("AWS Lambda","Processor"),AWS("Amazon S3","Durable output"),PUB("Delivery metrics","Operate","monitor")])]
 };
 return (fallbackByCategory[category]||fallbackByCategory["Compute"])();
}

const categoryConcepts:Record<string,string[]>={
 "Application Integration":["Know whether the service queues work, routes events, fans out messages, transfers data, or orchestrates state.","Ordering, retries, delivery semantics and idempotency are architecture decisions.","Failure paths and observability must be explicit."],
 "Compute":["Separate stateless compute from durable state.","Choose compute based on runtime duration, control, scaling, placement and latency.","Identity, networking and observability belong in the production design."],
 "Containers":["Registry, orchestrator and runtime capacity are different layers.","Images should be immutable and runtime state should stay external.","Task/pod identity and autoscaling should match workload boundaries."],
 "Database":["Start with data model and access patterns.","Replication/indexing can improve scale but changes cost and consistency tradeoffs.","Backup, encryption and private access are part of the architecture."],
 "Developer Tools":["Developer tools belong in build/deploy/operator workflows, not usually the request path.","Prefer repeatable automation and temporary credentials.","Source, artifacts, deployment and audit are separate concerns."],
 "Machine Learning":["Separate source data, AI/model capability, orchestration and evaluation.","Quality, latency, safety and cost must be measured together.","Grounding, inference, tools and human review are distinct concerns."],
 "Management and Governance":["These capabilities primarily operate in the control or operations plane.","Central governance often spans multiple accounts and workloads.","Metrics, logs, findings and automation solve different problems."],
 "Networking and Content Delivery":["Routing determines path; security determines permission.","DNS, edge, load balancing, APIs and private connectivity work at different layers.","Resilience requires independent failure domains and health decisions."],
 "Security, Identity, and Compliance":["Authentication, authorization, encryption, secret management and detection are different controls.","Use least privilege and temporary credentials where possible.","Security evidence needs an owner and remediation path."],
 "Storage":["Object, block and file storage expose different semantics.","Lifecycle and storage class should follow access patterns.","Replication, versioning and backup solve different recovery requirements."]
};

function PublicIcon({kind}:{kind:Kind}){const Cmp=kind==="user"?Users:kind==="internet"?Globe2:kind==="data"?Database:kind==="security"?Shield:kind==="file"?FileText:kind==="network"?Network:kind==="storage"?HardDrive:kind==="ai"?BrainCircuit:kind==="message"?MessageSquare:kind==="monitor"?Activity:kind==="app"?Laptop:Server;return <div className={`public-icon-disc public-${kind}`}><Cmp size={36}/></div>}
function iconFor(node:Node){return findAwsArchitectureIcon(node.icon||node.label)||awsArchitectureIcons.awsCloud}
function NodeView({node,featured=false}:{node:Node;featured?:boolean}){if(node.kind)return <div className={`dynamic-node public ${featured?"featured":""}`}><PublicIcon kind={node.kind}/><strong>{node.label}</strong><small>{node.sub}</small></div>;const icon=iconFor(node);return <div className={`dynamic-node ${featured?"featured":""}`}><div className="aws-icon-disc"><img src={awsIconSrc(icon)} data-fallback={awsIconFallbackSrc(icon)} onError={e=>{const img=e.currentTarget;const fallback=img.dataset.fallback;if(fallback&&img.src!==fallback){img.src=fallback;return}img.onerror=null}} alt={`${node.label} AWS architecture icon`}/></div><strong>{node.label}</strong><small>{node.sub}</small></div>}
function Architecture({arch,index}:{arch:Arch;index:number}){return <section className="architecture-stage dynamic-architecture" id={`architecture-${index}`}><div className="section-cap"><div><p>ARCHITECTURE {String(index).padStart(2,"0")}</p><h3>{arch.title}</h3></div><span>{arch.note}</span></div><div className="dynamic-map"><div className="map-left">{arch.left.map((x,i)=><NodeView key={i} node={x}/>)}</div><div className="map-arrow">→</div><NodeView node={arch.center} featured/><div className="map-arrow">→</div><div className="map-branches">{arch.right.map((x,i)=><NodeView key={i} node={x}/>)}</div></div></section>}
function Cards({title,items,id}:{title:string;items:string[];id?:string}){return <section className="knowledge-card" id={id}><div className="knowledge-card-title"><span>◆</span><h3>{title}</h3></div><div className="knowledge-card-body"><div className="concept-stack">{items.map((x,i)=><p key={i}><b>{String(i+1).padStart(2,"0")}</b>{x}</p>)}</div></div></section>}

export default function AipServiceLearningDetails({serviceName,summary}:{serviceName:string;summary?:string}){
 const e=resolveEntry(serviceName);if(!e)return null;
 const arches=architectures(e.service,e.category);
 const concepts=categoryConcepts[e.category]||["Understand the service boundary and its native inputs/outputs.","Know its security, availability and scaling responsibilities.","Compare it with adjacent AWS options by operating model, not product name."];
 const useCases=arches.map(a=>`${a.title}: ${a.note}`);
 return <div className="service-knowledge aip-shared-learning" data-service={e.service} data-search-scope="aws-service-learning">
  <div className="knowledge-intro"><div><p className="knowledge-kicker">VISUAL DEEP DIVE • {e.category.toUpperCase()}</p><h2>{e.service}</h2><p><b>What it is:</b> {summary||`An AWS capability in ${e.category}.`}</p></div><div className="knowledge-facts"><span><b>01</b>Purpose</span><span><b>02</b>Architecture</span><span><b>03</b>Operations</span><span><b>04</b>Exam fit</span></div></div>
  <nav className="knowledge-jumps"><a href="#concepts">Concepts</a><a href="#architecture-1">Architectures</a><a href="#use-cases">Use cases</a><a href="#security">Security</a><a href="#cost-models">Cost</a><a href="#memory-hook">Exam hook</a></nav>
  <div className="knowledge-grid" id="concepts"><Cards title="Core service concepts" items={concepts}/><Cards title="Where it fits" items={[`${e.service} has ${arches.length} architecture examples on this page.`,`Architecture diagrams use AWS service icons where AWS publishes/resolves them; non-AWS actors use colored diagram icons.`,`The examples focus on the real service role rather than using one generic pipeline for every service.`]}/></div>
  {arches.map((a,i)=><Architecture key={i} arch={a} index={i+1}/>)}
  <div className="knowledge-grid"><Cards id="use-cases" title="Practical use cases" items={useCases}/><Cards id="security" title="Security & governance" items={[`Apply least-privilege access to ${e.service} and each connected resource.`,`Encrypt sensitive data in transit and at rest where supported or integrated.`,`Capture the service's authoritative audit, workload or security telemetry.`]}/><Cards title="Design & optimization" items={[`Scale ${e.service} on the dimension it actually owns—requests, concurrency, capacity, storage, transfer, model usage or managed resource size.`,`Use native metrics and quotas to identify saturation before simply adding capacity.`,`Keep application, data, security and observability responsibilities separate unless the service explicitly owns them.`]}/><Cards id="cost-models" title="Cost model & drivers" items={[`Start with ${e.service}'s native usage or provisioned-capacity dimension.`,`Include transfer, storage, logs, requests and downstream compute where they are separate charges.`,`Do not assume every AWS service offers the same on-demand, provisioned or commitment model.`]}/><Cards title="Service comparison" items={[`Choose ${e.service} when the architecture needs the role shown above.`,`Compare service boundaries and operational responsibility, not only feature names.`,`Reject exam options that make ${e.service} perform a responsibility outside its documented operating model.`]}/><Cards id="memory-hook" title="Certification memory hook" items={[`Remember ${e.service} by where it sits in these architectures and what crosses its boundary.`,`Architecture 01 shows the core/reference use; Architecture 02 shows a production or alternate pattern.`,`If an exam answer places the service somewhere these relationships do not make sense, re-check the choice.`]}/></div>
 </div>;
}
