import "./AthenaLearningDetails.css";
import "./AthenaAwsIcons.css";
import { awsArchitectureIcons, awsIconSrc, awsIconFallbackSrc } from "../../lib/aws-architecture-icons";

type Key="Amazon Athena"|"Amazon EMR"|"AWS Glue"|"Amazon Kinesis"|"Amazon OpenSearch Service"|"Amazon QuickSight"|"Amazon Managed Streaming for Apache Kafka (Amazon MSK)";
type Step={icon:string;label:string;sub:string};
type Extra={architecture:{number:string;title:string;note:string;steps:Step[]};cost:{label:string;title:string;body:string}[];costNote:string};
const S=(icon:string,label:string,sub:string):Step=>({icon,label,sub});
const extras:Record<Key,Extra>={
"Amazon Athena":{architecture:{number:"03",title:"Production lake analytics pattern",note:"Separate storage, metadata, transformation and query responsibilities.",steps:[S("s3","S3 raw zone","Logs / source files"),S("glue","AWS Glue","ETL / preparation"),S("s3","S3 curated zone","Parquet / partitions"),S("glueDataCatalog","Glue Data Catalog","Governed metadata"),S("athena","Amazon Athena","Workgroups / SQL"),S("quicksight","Amazon QuickSight","BI consumers")]},cost:[{label:"ON-DEMAND",title:"Data scanned",body:"Best for variable/ad-hoc SQL. Partition pruning, compression and Parquet/ORC reduce scanned bytes."},{label:"PROVISIONED CAPACITY",title:"Reserved processing capacity",body:"Useful for predictable workloads that need dedicated capacity assigned to workgroups."},{label:"FEDERATED",title:"Query + connector resources",body:"Include connector compute and source-service costs as well as Athena query usage."}],costNote:"Certification + practical rule: optimize the amount of data read first; then choose on-demand or provisioned capacity based on workload predictability."},
"Amazon EMR":{architecture:{number:"02",title:"Production Spark data-lake pipeline",note:"Keep durable data in S3 and make EMR an elastic processing layer.",steps:[S("s3","Raw S3","Source data"),S("emr","Amazon EMR","Spark transforms"),S("s3","Curated S3","Parquet output"),S("glueDataCatalog","Glue Catalog","Shared metadata"),S("athena","Amazon Athena","Interactive SQL")]},cost:[{label:"EMR ON EC2",title:"Cluster capacity",body:"EC2, EMR and storage costs; best when instance choice and deep cluster control matter."},{label:"EMR SERVERLESS",title:"Job resources",body:"Good for intermittent jobs where paying for idle cluster capacity is undesirable."},{label:"EMR ON EKS",title:"Analytics on Kubernetes",body:"Include EMR workload usage and the underlying EKS compute platform."}],costNote:"Choose EC2, Serverless or EKS based on operating model first; then right-size runtime, workers and storage."},
"AWS Glue":{architecture:{number:"02",title:"Governed serverless ETL pipeline",note:"Discovery and metadata remain separate from transformation compute.",steps:[S("s3","S3 source","Raw data"),S("glue","Glue Crawler","Discover schema"),S("glueDataCatalog","Data Catalog","Tables / partitions"),S("glue","Glue ETL Job","Clean / join / convert"),S("s3","Curated S3","Parquet / ORC"),S("athena","Amazon Athena","Analytics") ]},cost:[{label:"ETL JOBS",title:"Worker / DPU runtime",body:"Processing capacity and job duration are major cost drivers; right-size workers and avoid unnecessary reruns."},{label:"CRAWLERS",title:"Discovery runtime",body:"Schedule crawlers intentionally instead of repeatedly scanning unchanged sources."},{label:"DOWNSTREAM",title:"Data layout matters",body:"Efficient partitions and columnar output can reduce later Athena and processing costs."}],costNote:"Optimize the whole pipeline: Glue compute, crawler frequency, incremental processing and the format/layout written for downstream consumers."},
"Amazon Kinesis":{architecture:{number:"02",title:"Real-time fan-out processing",note:"One durable stream can feed independent processing and persistence paths.",steps:[S("user","Applications","Event producers"),S("kinesis","Kinesis Data Streams","Partition keys / shards"),S("lambda","AWS Lambda","Real-time processing"),S("dynamodb","Amazon DynamoDB","Operational state"),S("s3","Amazon S3","Long-term archive")]},cost:[{label:"PROVISIONED",title:"Shard capacity",body:"Useful when throughput is understood and shard capacity can be managed efficiently."},{label:"ON-DEMAND",title:"Managed capacity",body:"Useful for unpredictable traffic when you do not want to plan shard counts."},{label:"CONSUMPTION",title:"Retention / fan-out",body:"Include optional retention and consumer patterns such as enhanced fan-out in total cost."}],costNote:"For exams know provisioned versus on-demand; in practice also model retention, consumers and traffic distribution."},
"Amazon OpenSearch Service":{architecture:{number:"02",title:"Centralized operational analytics",note:"Ingest operational data, index it once, then search, visualize and investigate.",steps:[S("user","Applications","Logs / events"),S("kinesis","Kinesis","Streaming ingestion"),S("opensearch","Amazon OpenSearch","Indexes / shards"),S("user","Dashboards / API","Search / visualize / alert")]},cost:[{label:"MANAGED DOMAIN",title:"Instances + storage",body:"You size nodes and storage; suitable when predictable workloads justify direct capacity control."},{label:"SERVERLESS",title:"OCU compute + storage",body:"Removes cluster sizing but compute and retained data still drive cost."},{label:"LIFECYCLE",title:"Hot data retention",body:"Shard design, ingestion rate, query rate and how long data remains hot materially affect economics."}],costNote:"Search cost is workload-shaped: indexing, querying, shard design, replicas, retention and storage tier all matter."},
"Amazon QuickSight":{architecture:{number:"02",title:"Governed BI delivery pattern",note:"Separate source/query concerns from BI consumption.",steps:[S("s3","Amazon S3","Curated lake"),S("glueDataCatalog","Glue Catalog","Governed metadata"),S("athena","Amazon Athena","SQL datasets"),S("quicksight","Amazon QuickSight","SPICE / analysis"),S("user","Business users","Dashboard / embedded BI")]},cost:[{label:"SPICE",title:"Import and reuse data",body:"Repeated dashboard interactions can avoid repeatedly querying the source."},{label:"DIRECT QUERY",title:"Live source queries",body:"Useful for freshness, but source-engine cost and latency also become part of the design."},{label:"CONSUMPTION",title:"Authors / readers / embedding",body:"Model BI consumption together with SPICE capacity and connected source costs."}],costNote:"Do not price BI in isolation: include refresh frequency, source-query cost, SPICE capacity and consumption model."},
"Amazon Managed Streaming for Apache Kafka (Amazon MSK)":{architecture:{number:"02",title:"Kafka event backbone",note:"Kafka decouples producers from independently scaling consumer groups.",steps:[S("user","Microservices","Kafka producers"),S("msk","Amazon MSK","Topics / partitions"),S("lambda","Stream consumers","Processing"),S("s3","Amazon S3","Archive / lake"),S("opensearch","Amazon OpenSearch","Operational analytics")]},cost:[{label:"PROVISIONED",title:"Broker + storage capacity",body:"Best when Kafka workload and broker-control requirements are understood."},{label:"SERVERLESS",title:"Usage-oriented Kafka",body:"AWS manages broker capacity for variable workloads and teams that do not want broker sizing."},{label:"ECOSYSTEM",title:"Transfer + consumers",body:"Include retention, transfer and connected compute/connector services in platform cost."}],costNote:"Architecture drives economics: provisioned rewards deliberate sizing; Serverless trades broker management for a usage-oriented model."}
};
const AwsStep=({step}:{step:Step})=>{const icon=awsArchitectureIcons[step.icon];if(!icon)throw new Error(`Missing AWS architecture icon: ${step.icon}`);return <div className="aws-arch-node"><div className="aws-icon-disc"><img src={awsIconSrc(icon)} data-fallback={awsIconFallbackSrc(icon)} onError={e=>{const f=e.currentTarget.dataset.fallback;if(f&&e.currentTarget.src!==f)e.currentTarget.src=f;else e.currentTarget.onerror=null}} alt={`${step.label} AWS architecture icon`} loading="lazy"/></div><strong>{step.label}</strong><small>{step.sub}</small></div>};
export function AnalyticsArchitectureEnhancement({serviceName}:{serviceName:string}){const d=extras[serviceName as Key];if(!d)return null;return <section className="architecture-stage secondary-architecture" data-search-section="architecture-example"><div className="section-cap"><div><p>ARCHITECTURE {d.architecture.number}</p><h3>{d.architecture.title}</h3></div><span>{d.architecture.note}</span></div><div className="analytics-service-flow">{d.architecture.steps.map((step,i)=><div className="analytics-flow-piece" key={`${step.label}-${i}`}><AwsStep step={step}/>{i<d.architecture.steps.length-1&&<div className="big-arrow">→</div>}</div>)}</div></section>}
export function AnalyticsCostEnhancement({serviceName}:{serviceName:string}){const d=extras[serviceName as Key];if(!d)return null;return <section className="compare-board" data-search-section="cost-models"><div className="section-cap"><div><p>COST MODEL</p><h3>How the bill behaves</h3></div><span>Learn the pricing shape, not a price that goes stale.</span></div><div className="compare-columns">{d.cost.map((x,i)=><div className={i===0?"recommended":""} key={x.label}><b>{x.label}</b><strong>{x.title}</strong><span>{x.body}</span></div>)}</div><div className="callout"><b>Cost decision rule</b><span>{d.costNote}</span></div></section>}
