import type { ExamGuide, ExamTask } from "./AwsExamTaskGuide";

const T = (id: string, title: string, focus: string, watch: string, services: string[], flow: [string, string, string, string]): ExamTask => ({ id, title, ask: focus, focus: [focus, watch], services, flow });

export const cloudOpsGuide: ExamGuide = {
  code: "SOA", examCode: "SOA-C03", title: "AWS Certified CloudOps Engineer – Associate", headline: "Operate, automate, secure, and recover AWS workloads", intro: "Follow every SOA-C03 task from the official exam guide, then connect operational decisions to the services in this course.", domains: [
    { title: "Monitoring, Logging, Analysis, Remediation, and Performance Optimization", weight: 22, tasks: [
      T("1-1", "Implement metrics, alarms, and filters by using AWS monitoring and logging services", "Collect workload metrics and logs with CloudWatch, CloudTrail, agents, alarms, and dashboards; notify operators when conditions change.", "Distinguish operational metrics and log filters from the API activity recorded by CloudTrail.", ["Amazon CloudWatch", "AWS CloudTrail", "Amazon SNS"], ["Collect signals", "Filter and alarm", "Notify responders", "Verify recovery"]),
      T("1-2", "Identify and remediate issues by using monitoring and availability metrics", "Investigate metrics, events, and health signals; route events and run Systems Manager Automation for repeatable remediation.", "Tie a remediation action to a measured condition and verify the outcome after the automation runs.", ["Amazon CloudWatch", "Amazon EventBridge", "AWS Systems Manager", "AWS Health Dashboard"], ["Detect anomaly", "Correlate events", "Run automation", "Confirm health"]),
      T("1-3", "Implement performance optimization strategies for compute, storage, and database resources", "Use EC2, EBS, S3, RDS, and shared-storage metrics to isolate performance bottlenecks before changing capacity or configuration.", "A slow request can be caused by storage throughput, database connections, or compute saturation; inspect the right metric first.", ["Amazon EC2", "Amazon EBS", "Amazon RDS", "AWS Compute Optimizer"], ["Measure demand", "Locate bottleneck", "Tune resource", "Recheck latency"]),
    ] },
    { title: "Reliability and Business Continuity", weight: 22, tasks: [
      T("2-1", "Implement scalability and elasticity", "Configure scaling policies and load distribution from workload demand, target metrics, health checks, and capacity limits.", "Scaling adds or removes capacity; it does not replace a multi-AZ availability design.", ["AWS Auto Scaling", "Amazon EC2", "Amazon CloudWatch", "Elastic Load Balancing (ELB)"], ["Set target", "Observe demand", "Scale capacity", "Validate health"]),
      T("2-2", "Implement highly available and resilient environments", "Distribute workloads across Availability Zones, check endpoints, and design failover for application and data tiers.", "Identify the failure boundary before choosing load balancing, database replicas, or regional recovery.", ["Elastic Load Balancing (ELB)", "Amazon Route 53", "Amazon RDS", "Amazon Application Recovery Controller"], ["Define outage", "Spread workload", "Route healthy traffic", "Test failover"]),
      T("2-3", "Implement backup and restore strategies", "Choose backups, retention, replication, and restore procedures according to recovery time and recovery point objectives.", "A backup plan is incomplete until a restore is tested against the required RTO and RPO.", ["AWS Backup", "Amazon S3", "Amazon EBS", "Amazon RDS"], ["Set RTO/RPO", "Protect data", "Restore copy", "Test objective"]),
    ] },
    { title: "Deployment, Provisioning, and Automation", weight: 22, tasks: [
      T("3-1", "Provision and maintain cloud resources", "Provision repeatable infrastructure through CloudFormation or CDK and manage approved resources and changes over time.", "Compare desired state with deployed state; address drift before assuming a stack update is safe.", ["AWS CloudFormation", "AWS CDK", "AWS Service Catalog", "AWS Config"], ["Define template", "Review change", "Provision stack", "Detect drift"]),
      T("3-2", "Automate the management of existing resources", "Use Systems Manager operations, EventBridge schedules, and automation runbooks to patch and maintain existing fleets.", "Separate routine automation from infrastructure provisioning and ensure actions can be observed and audited.", ["AWS Systems Manager", "Amazon EventBridge", "AWS CloudTrail"], ["Find fleet", "Select runbook", "Execute safely", "Audit result"]),
    ] },
    { title: "Security and Compliance", weight: 16, tasks: [
      T("4-1", "Implement and manage security and compliance tools and policies", "Evaluate resource configuration, identity permissions, threat findings, and organizational controls against required policies.", "A finding is a signal; connect it to the affected resource, its policy, and an accountable remediation step.", ["AWS Config", "Amazon GuardDuty", "AWS Security Hub", "IAM"], ["Define rule", "Collect finding", "Prioritize risk", "Verify fix"]),
      T("4-2", "Implement strategies to protect data and infrastructure", "Protect data with key management, network controls, secrets management, and appropriate edge or application defenses.", "Encryption at rest, network access, and application-layer protection address different threats.", ["AWS KMS", "AWS Secrets Manager", "AWS WAF", "AWS Network Firewall"], ["Classify data", "Enforce access", "Encrypt and filter", "Inspect evidence"]),
    ] },
    { title: "Networking and Content Delivery", weight: 18, tasks: [
      T("5-1", "Implement and optimize networking features and connectivity", "Configure VPC routing, gateways, endpoints, hybrid connections, and network topology to satisfy reachability and performance.", "Trace the packet path and route tables before changing security rules or connectivity services.", ["Amazon VPC", "AWS Transit Gateway", "AWS PrivateLink", "AWS Site-to-Site VPN"], ["Map endpoints", "Choose connection", "Set routes", "Test path"]),
      T("5-2", "Configure domains, DNS services, and content delivery", "Configure Route 53 records and health-aware routing, CloudFront delivery, certificates, and edge behavior.", "DNS directs clients to an endpoint; a CDN caches and serves content at the edge.", ["Amazon Route 53", "Amazon CloudFront", "AWS Certificate Manager (ACM)"], ["Resolve name", "Choose origin", "Cache at edge", "Check health"]),
      T("5-3", "Troubleshoot network connectivity issues", "Inspect VPC Flow Logs, route tables, security groups, network ACLs, DNS resolution, and reachability analysis to isolate failed connections.", "Security groups are stateful; network ACLs are stateless. Check both directions and the actual route.", ["VPC Flow Logs", "VPC Reachability Analyzer", "Amazon VPC", "Network ACLs"], ["Trace source", "Inspect route", "Check controls", "Retest traffic"]),
    ] },
  ]
};

export const dataEngineerGuide: ExamGuide = {
  code: "DEA", examCode: "DEA-C01", title: "AWS Certified Data Engineer – Associate", headline: "Build reliable data pipelines, stores, and governance controls", intro: "Explore all four DEA-C01 domains through practical data engineering decisions and related AWS services.", domains: [
    { title: "Data Ingestion and Transformation", weight: 34, tasks: [
      T("1-1", "Perform data ingestion", "Ingest batch, streaming, and change-data-capture sources into a durable landing zone while choosing suitable throughput and latency.", "A streaming source needs ordering, replay, and backpressure considerations that a one-time batch transfer may not need.", ["Amazon Kinesis Data Streams", "Amazon Managed Streaming for Apache Kafka (Amazon MSK)", "AWS DMS", "Amazon S3"], ["Identify source", "Choose ingestion", "Land data", "Check delivery"]),
      T("1-2", "Transform and process data", "Prepare, clean, and transform data with Glue, EMR, containers, or serverless compute according to processing shape and scale.", "Choose ETL compute from data size, latency, transformation complexity, and operational ownership.", ["AWS Glue", "Amazon EMR", "AWS Lambda", "Amazon ECS"], ["Profile input", "Select engine", "Transform records", "Validate output"]),
      T("1-3", "Orchestrate data pipelines", "Coordinate ETL stages, retries, dependencies, and schedules with Step Functions, MWAA, Glue workflows, or EventBridge.", "An orchestrator manages dependencies and failure paths; it is not itself the processing engine.", ["AWS Step Functions", "Amazon EventBridge", "AWS Glue"], ["Trigger run", "Order stages", "Handle retry", "Publish result"]),
      T("1-4", "Apply programming concepts", "Write maintainable ingestion and transformation code with appropriate data structures, error handling, testing, and runtime optimization.", "Idempotency, partitioning, serialization, and error handling affect correctness as much as raw speed.", ["AWS Glue", "AWS Lambda", "AWS CodeBuild"], ["Model inputs", "Implement logic", "Test edge cases", "Tune runtime"]),
    ] },
    { title: "Data Store Management", weight: 26, tasks: [
      T("2-1", "Choose a data store", "Select S3, Redshift, DynamoDB, RDS, or other data stores by access pattern, storage format, query shape, scale, and cost.", "Object storage, relational OLTP, key-value lookups, and columnar analytics solve different requirements.", ["Amazon S3", "Amazon Redshift", "Amazon DynamoDB", "Amazon RDS"], ["Define queries", "Choose model", "Test scale", "Plan retention"]),
      T("2-2", "Understand data cataloging systems", "Discover and maintain data schemas, partitions, metadata, and permissions so consumers can locate and query datasets.", "A data catalog describes datasets; it does not replace the underlying storage or query engine.", ["AWS Glue", "AWS Lake Formation", "Amazon Athena"], ["Discover data", "Catalog schema", "Set access", "Query safely"]),
      T("2-3", "Manage the lifecycle of data", "Load and unload datasets, apply S3 lifecycle and retention policies, and keep storage cost aligned with access frequency.", "Distinguish archival or tier transition from a pipeline that transforms data into a new analytical format.", ["Amazon S3", "Amazon S3 Glacier", "Amazon Redshift", "AWS DataSync"], ["Classify access", "Load dataset", "Set lifecycle", "Verify restore"]),
      T("2-4", "Design data models and schema evolution", "Design Redshift, DynamoDB, and lake schemas around queries, keys, partitions, and safe changes over time.", "A schema change can break producers or consumers; assess compatibility before promoting it.", ["Amazon Redshift", "Amazon DynamoDB", "AWS Lake Formation", "AWS Glue"], ["Identify access", "Model schema", "Plan evolution", "Test consumers"]),
    ] },
    { title: "Data Operations and Support", weight: 22, tasks: [
      T("3-1", "Automate data processing by using AWS services", "Schedule and automate pipeline work with event triggers, orchestration, infrastructure automation, and controlled retries.", "Automation should be replayable and observable after partial failures.", ["AWS Step Functions", "Amazon EventBridge", "AWS CloudFormation", "AWS Glue"], ["Schedule trigger", "Run workflow", "Recover error", "Record result"]),
      T("3-2", "Analyze data by using AWS services", "Query datasets and present useful results through Athena, Redshift, and visual analytics tools.", "Choose interactive SQL over S3, warehouse workloads, and BI presentation by their distinct query and serving roles.", ["Amazon Athena", "Amazon Redshift", "Amazon Quick"], ["Select dataset", "Choose query", "Analyze result", "Share insight"]),
      T("3-3", "Maintain and monitor data pipelines", "Monitor pipeline metrics and logs, detect failed stages, and coordinate retries or incident response.", "Distinguish data arriving late from a transformation failure and alert on the right signal.", ["Amazon CloudWatch", "Amazon CloudWatch Logs", "Amazon EventBridge", "AWS CloudTrail"], ["Collect telemetry", "Detect failure", "Repair pipeline", "Verify freshness"]),
      T("3-4", "Ensure data quality", "Validate completeness, uniqueness, formats, and business rules throughout ingestion and transformation.", "A successful ETL job can still produce invalid data; add explicit quality checks and quarantine bad records.", ["AWS Glue", "AWS Glue DataBrew", "Amazon S3"], ["Define rules", "Test records", "Quarantine bad", "Publish score"]),
    ] },
    { title: "Data Security and Governance", weight: 18, tasks: [
      T("4-1", "Apply authentication mechanisms", "Authenticate pipeline identities and users with IAM credentials, roles, and appropriate network or federated access controls.", "Authentication proves identity; it does not by itself authorize access to a table or object.", ["IAM", "Amazon VPC", "AWS Secrets Manager"], ["Identify caller", "Authenticate", "Limit network", "Audit login"]),
      T("4-2", "Apply authorization mechanisms", "Apply least-privilege IAM, Lake Formation, bucket, and data-sharing permissions to producers and consumers.", "Trace both identity policy and data resource permissions when access is denied.", ["IAM", "AWS Lake Formation", "Amazon S3", "Amazon Redshift"], ["Define role", "Grant dataset", "Test denial", "Review access"]),
      T("4-3", "Ensure data encryption and masking", "Encrypt data in transit and at rest, manage keys, and mask or anonymize sensitive attributes when sharing datasets.", "Encryption protects storage and transport; masking changes what a consumer can see.", ["AWS KMS", "Amazon S3", "Amazon Macie"], ["Classify fields", "Encrypt data", "Mask values", "Test access"]),
      T("4-4", "Prepare logs for audit", "Record API actions, pipeline activity, and data access evidence with retention and integrity appropriate to audit requirements.", "CloudTrail captures AWS API activity; CloudWatch captures application and operational logs.", ["AWS CloudTrail", "Amazon CloudWatch Logs", "Amazon S3"], ["Define evidence", "Collect logs", "Retain safely", "Review events"]),
      T("4-5", "Understand data privacy and governance", "Control discovery, classification, retention, and cross-team data sharing according to privacy policies.", "Ownership and row- or column-level access must travel with shared datasets.", ["AWS Lake Formation", "Amazon Macie", "Amazon Redshift", "AWS Data Exchange"], ["Classify data", "Set policy", "Share safely", "Audit usage"]),
    ] },
  ]
};

export const machineLearningGuide: ExamGuide = {
  code: "MLA", examCode: "MLA-C01", title: "AWS Certified Machine Learning Engineer – Associate", headline: "Prepare data, develop models, deploy, and monitor ML solutions", intro: "Move through the twelve official MLA-C01 tasks with concrete model lifecycle and operations decisions.", domains: [
    { title: "Data Preparation for Machine Learning (ML)", weight: 28, tasks: [
      T("1-1", "Ingest and store data", "Choose batch or streaming ingestion and durable storage based on source format, volume, latency, and downstream model access.", "Maintain lineage, access control, and a repeatable training snapshot rather than overwriting the only source data.", ["Amazon S3", "Amazon Kinesis", "AWS Glue", "Amazon SageMaker"], ["Identify source", "Ingest reliably", "Store version", "Validate access"]),
      T("1-2", "Transform data and perform feature engineering", "Clean, encode, normalize, and join raw data; create reusable features while preventing training-serving skew.", "Fit transformations on training data and apply the same logic to validation and inference inputs.", ["AWS Glue", "AWS Glue DataBrew", "Amazon SageMaker", "Amazon S3"], ["Profile data", "Build features", "Version logic", "Check skew"]),
      T("1-3", "Ensure data integrity and prepare data for modeling", "Inspect missing values, duplicates, labels, distribution, and sensitive attributes before splitting datasets for modeling.", "Avoid leakage: transformations and feature selection must not learn from the holdout test set.", ["AWS Glue Data Quality", "Amazon SageMaker", "Amazon S3"], ["Validate rows", "Check labels", "Split datasets", "Record lineage"]),
    ] },
    { title: "ML Model Development", weight: 26, tasks: [
      T("2-1", "Choose a modeling approach", "Match the objective and labeled data to supervised, unsupervised, pre-trained, or foundation-model approaches and a suitable evaluation metric.", "Choose a metric that reflects the business cost of false positives, false negatives, or numeric error.", ["Amazon SageMaker", "Amazon Bedrock", "Amazon Rekognition"], ["Frame problem", "Inspect labels", "Choose model", "Select metric"]),
      T("2-2", "Train and refine models", "Configure training jobs, hyperparameters, compute, data splits, and experiments; refine the model without leaking test results.", "Compare runs on consistent validation data and keep the training artifact reproducible.", ["Amazon SageMaker", "Amazon S3", "Amazon EC2"], ["Train baseline", "Tune parameters", "Compare runs", "Register model"]),
      T("2-3", "Analyze model performance", "Assess classification, regression, or ranking quality using suitable metrics, error analysis, and data slices.", "A high aggregate score may hide poor performance for a rare class or user segment.", ["Amazon SageMaker", "Amazon CloudWatch", "Amazon Quick"], ["Measure holdout", "Inspect errors", "Compare segments", "Decide release"]),
    ] },
    { title: "Deployment and Orchestration of ML Workflows", weight: 22, tasks: [
      T("3-1", "Select deployment infrastructure based on existing architecture and requirements", "Choose real-time endpoints, serverless inference, asynchronous inference, or batch processing from latency, throughput, and cost needs.", "A batch job does not satisfy interactive latency; an always-on endpoint can waste capacity for rare requests.", ["Amazon SageMaker", "AWS Lambda", "Amazon ECS", "Amazon S3"], ["Set SLO", "Choose inference", "Plan scaling", "Test load"]),
      T("3-2", "Create and script infrastructure based on existing architecture and requirements", "Provision model-serving infrastructure, permissions, networking, and deployment configuration reproducibly through infrastructure as code.", "Keep model artifact version and infrastructure change visible in the deployment record.", ["AWS CloudFormation", "AWS CDK", "Amazon SageMaker", "IAM"], ["Define resources", "Set identity", "Deploy version", "Verify endpoint"]),
      T("3-3", "Use automated orchestration tools to set up continuous integration and continuous delivery (CI/CD) pipelines", "Automate data preparation, training, validation gates, artifact promotion, and model deployment with explicit rollback paths.", "A model pipeline needs data and evaluation gates in addition to ordinary code build and deployment stages.", ["Amazon SageMaker", "AWS Step Functions", "AWS CodePipeline", "AWS CodeBuild"], ["Trigger change", "Run pipeline", "Gate quality", "Promote model"]),
    ] },
    { title: "ML Solution Monitoring, Maintenance, and Security", weight: 24, tasks: [
      T("4-1", "Monitor model inference", "Observe inference latency, errors, model quality, input drift, and data or concept changes after deployment.", "Infrastructure health and model quality are different signals; monitor both.", ["Amazon SageMaker", "Amazon CloudWatch", "Amazon S3"], ["Collect requests", "Watch drift", "Alert owner", "Retrain safely"]),
      T("4-2", "Monitor and optimize infrastructure and costs", "Right-size training and inference capacity, track utilization and spend, and choose scaling or batch patterns when suitable.", "Cost optimization must preserve the required latency and model quality targets.", ["Amazon CloudWatch", "AWS Cost Explorer", "AWS Compute Optimizer", "Amazon SageMaker"], ["Measure cost", "Profile demand", "Tune capacity", "Recheck SLO"]),
      T("4-3", "Secure AWS resources", "Apply least-privilege identities, encryption, private network paths, and auditable access to ML data and model artifacts.", "Protect training data, model artifacts, and inference input/output independently.", ["IAM", "AWS KMS", "AWS Secrets Manager", "Amazon VPC"], ["Classify assets", "Restrict access", "Encrypt paths", "Audit calls"]),
    ] },
  ]
};

export const devOpsGuide: ExamGuide = {
  code: "DOP", examCode: "DOP-C02", title: "AWS Certified DevOps Engineer – Professional", headline: "Automate delivery, resilience, observability, and security", intro: "Study all nineteen DOP-C02 task statements across six domains with service-specific implementation and operational checks.", domains: [
    { title: "SDLC Automation", weight: 22, tasks: [
      T("1-1", "Implement CI/CD pipelines", "Design source, build, test, approval, and deployment stages for single- or multi-account application environments.", "Protect cross-account roles, artifact integrity, and promotion boundaries throughout the pipeline.", ["AWS CodePipeline", "AWS CodeBuild", "AWS CodeDeploy", "AWS Secrets Manager"], ["Commit source", "Build and test", "Approve artifact", "Deploy safely"]),
      T("1-2", "Integrate automated testing into CI/CD pipelines", "Run unit, integration, security, acceptance, and performance tests at appropriate pipeline gates.", "A passing build only proves compilation; include tests for behavior, security, and deployment health.", ["AWS CodeBuild", "AWS CodePipeline", "AWS Lambda"], ["Define test", "Run gate", "Report failure", "Promote safely"]),
      T("1-3", "Build and manage artifacts", "Produce versioned deployable packages, images, and templates; store and promote them through controlled repositories.", "Build once and promote an immutable artifact to avoid environment drift.", ["AWS CodeArtifact", "Amazon S3", "Amazon Elastic Container Registry (Amazon ECR)", "AWS CodeBuild"], ["Build package", "Scan content", "Version artifact", "Promote digest"]),
      T("1-4", "Implement deployment strategies for instance, container, and serverless environments", "Choose rolling, blue/green, canary, or immutable releases based on EC2, ECS, EKS, and Lambda workload behavior.", "Plan traffic shifting, health checks, rollback triggers, and data compatibility before release.", ["AWS CodeDeploy", "Amazon EC2", "Amazon Elastic Container Service (Amazon ECS)", "AWS Lambda"], ["Choose strategy", "Shift traffic", "Observe health", "Roll back"]),
    ] },
    { title: "Configuration Management and IaC", weight: 17, tasks: [
      T("2-1", "Define cloud infrastructure and reusable components to provision and manage systems throughout their lifecycle", "Model infrastructure as reusable templates or constructs with parameters, dependencies, review, and drift control.", "A reusable module needs versioning, safe defaults, and a controlled update path.", ["AWS CloudFormation", "AWS Service Catalog", "AWS Systems Manager"], ["Define module", "Review change", "Deploy stack", "Detect drift"]),
      T("2-2", "Deploy automation to create, onboard, and secure AWS accounts in a multi-account or multi-Region environment", "Automate account vending, organizational guardrails, baseline logging, and identity configuration across accounts.", "Account guardrails and workload IAM permissions operate at different policy layers.", ["AWS Organizations", "AWS Control Tower", "AWS IAM Identity Center", "AWS CloudTrail"], ["Create account", "Apply guardrail", "Enable logging", "Audit baseline"]),
      T("2-3", "Design and build automated solutions for complex tasks and large-scale environments", "Orchestrate large-scale maintenance and configuration workflows with managed runbooks and event triggers.", "Design retries, limits, failure isolation, and rollback before running automation across a fleet.", ["AWS Systems Manager", "AWS Step Functions", "Amazon EventBridge", "AWS CloudFormation"], ["Identify fleet", "Sequence work", "Bound failure", "Verify state"]),
    ] },
    { title: "Resilient Cloud Solutions", weight: 15, tasks: [
      T("3-1", "Implement highly available solutions to meet resilience and business requirements", "Spread compute and stateful components across failure zones with health-aware routing and resilient data choices.", "Availability Zones, Regions, and individual nodes are different failure boundaries.", ["Elastic Load Balancing (ELB)", "Amazon Route 53", "Amazon Aurora", "AWS Resilience Hub"], ["Define SLA", "Spread tiers", "Route healthy", "Test outage"]),
      T("3-2", "Implement solutions that are scalable to meet business requirements", "Scale stateless application capacity and supporting databases based on demand, service limits, and performance indicators.", "Autoscaling a frontend does not automatically remove bottlenecks in storage, queues, or database connections.", ["Amazon EC2 Auto Scaling", "AWS Auto Scaling", "Amazon CloudWatch", "Amazon DynamoDB"], ["Measure load", "Set policy", "Scale tier", "Load test"]),
      T("3-3", "Implement automated recovery processes to meet RTO and RPO requirements", "Automate backup, replication, failover, and restore tests against explicitly defined recovery objectives.", "RTO is time to restore service; RPO is the maximum tolerable data loss window.", ["AWS Backup", "AWS Elastic Disaster Recovery", "Amazon Route 53", "AWS Resilience Hub"], ["Set RTO/RPO", "Protect state", "Fail over", "Rehearse restore"]),
    ] },
    { title: "Monitoring and Logging", weight: 15, tasks: [
      T("4-1", "Configure the collection, aggregation, and storage of logs and metrics", "Collect workload metrics, application logs, and audit events into appropriate stores with retention and access controls.", "Metrics, application logs, traces, and API audit records answer different operational questions.", ["Amazon CloudWatch", "Amazon CloudWatch Logs", "AWS CloudTrail", "Amazon S3"], ["Instrument app", "Aggregate signals", "Set retention", "Control access"]),
      T("4-2", "Audit, monitor, and analyze logs and metrics to detect issues", "Correlate alarms, log patterns, traces, and configuration changes to detect performance or security issues.", "Choose evidence from the component that observed the failure, then trace upstream and downstream dependencies.", ["Amazon CloudWatch", "AWS X-Ray", "AWS Config", "AWS CloudTrail"], ["Detect symptom", "Correlate logs", "Trace cause", "Confirm fix"]),
      T("4-3", "Automate monitoring and event management of complex environments", "Build cross-service alarms and event routing that notify or initiate bounded remediation workflows.", "Suppress duplicate alerts and verify automation outcomes to avoid repeated or unsafe actions.", ["Amazon EventBridge", "Amazon CloudWatch", "AWS Systems Manager", "Amazon Simple Notification Service (Amazon SNS)"], ["Define signal", "Route event", "Run response", "Close incident"]),
    ] },
    { title: "Incident and Event Response", weight: 14, tasks: [
      T("5-1", "Manage event sources to process, notify, and take action in response to events", "Ingest service and application events, filter rules, queue work, and notify responders or downstream consumers.", "EventBridge routes events, SNS fans out messages, and SQS buffers work for consumers.", ["Amazon EventBridge", "Amazon Simple Notification Service (Amazon SNS)", "Amazon Simple Queue Service (Amazon SQS)", "AWS Lambda"], ["Receive event", "Match rule", "Notify or queue", "Track outcome"]),
      T("5-2", "Implement configuration changes in response to events", "Translate a qualifying event into a controlled infrastructure or configuration change with auditing and rollback.", "Constrain the execution role and make the change idempotent so duplicate events do not multiply actions.", ["Amazon EventBridge", "AWS Systems Manager", "AWS Config", "AWS CloudFormation"], ["Match condition", "Approve policy", "Apply change", "Verify drift"]),
      T("5-3", "Troubleshoot system and application failures", "Diagnose failed deployments, unhealthy targets, runtime exceptions, and performance regressions from correlated telemetry.", "Find the first failing dependency rather than restarting healthy components indiscriminately.", ["Amazon CloudWatch Logs", "AWS X-Ray", "AWS CodeDeploy", "AWS Health"], ["Reproduce issue", "Inspect signals", "Isolate cause", "Verify recovery"]),
    ] },
    { title: "Security and Compliance", weight: 17, tasks: [
      T("6-1", "Implement techniques for identity and access management at scale", "Manage roles, federation, permission boundaries, cross-account access, and organizational controls with automation.", "Identity policy, resource policy, and organization restrictions all affect the final authorization decision.", ["AWS Identity and Access Management (IAM)", "AWS IAM Identity Center", "AWS Organizations", "AWS Security Token Service (AWS STS)"], ["Define principal", "Set policies", "Assume role", "Test denial"]),
      T("6-2", "Apply automation for security controls and data protection", "Automate encryption, secrets rotation, configuration enforcement, and data protection across the deployment lifecycle.", "A passing template scan does not prove that runtime resources remain compliant; detect and remediate drift.", ["AWS Key Management Service (AWS KMS)", "AWS Secrets Manager", "AWS Config", "AWS CloudFormation"], ["Define baseline", "Deploy controls", "Detect drift", "Remediate"]),
      T("6-3", "Implement security monitoring and auditing solutions", "Centralize API activity, configuration history, threat findings, and actionable security alerts for investigation.", "Audit events document actions; threat detections and posture findings require separate triage.", ["AWS CloudTrail", "AWS Config", "Amazon GuardDuty", "AWS Security Hub"], ["Collect evidence", "Correlate finding", "Investigate", "Prove closure"]),
    ] },
  ]
};
