"use client";

import { useState } from "react";
import SharedServiceWalkthrough from "./SharedServiceWalkthrough";
import "./AwsSaaCourseGuide.css";

type VisualKind = "flow" | "layers" | "matrix" | "cycle" | "decision" | "timeline";
type SAAObjective = { title: string; ask: string; focus: string[]; visual?: { kind: VisualKind; title: string; subtitle: string; nodes: string[]; explanation: string; cue: string }; services?: string[] };
type SAADomain = { number: string; title: string; weight: string; outcome: string; flow: string[]; tasks: SAAObjective[] };

const V = (kind: VisualKind, title: string, subtitle: string, nodes: string[], explanation: string, cue: string) => ({ kind, title, subtitle, nodes, explanation, cue });

const saaTaskWalkthroughs: Record<string, string> = {
  "1.1": "task-1-1-secure-access",
  "1.2": "task-1-2-secure-workloads",
  "1.3": "task-1-3-data-security-controls",
  "2.1": "task-2-1-scalable-loosely-coupled",
  "2.2": "task-2-2-highly-available-fault-tolerant",
  "3.1": "task-3-1-high-performing-storage",
  "3.2": "task-3-2-high-performing-elastic-compute",
  "3.3": "task-3-3-high-performing-databases",
  "3.4": "task-3-4-high-performing-network",
  "3.5": "task-3-5-data-ingestion-transformation",
  "4.1": "task-4-1-cost-optimized-storage",
  "4.2": "task-4-2-cost-optimized-compute",
  "4.3": "task-4-3-cost-optimized-databases",
  "4.4": "task-4-4-cost-optimized-network",
};
const saaTaskAsset = (title: string) => saaTaskWalkthroughs[title.match(/^Task ([0-9.]+)/)?.[1] || ""];
const saaTaskCompanionWalkthroughs: Record<string, string> = {
  "1.1": "task-1-1-access-companion",
  "1.2": "task-1-2-workloads-companion",
  "1.3": "task-1-3-data-companion",
  "2.1": "task-2-1-loose-coupling-companion",
  "2.2": "task-2-2-resilience-companion",
  "3.1": "task-3-1-storage-companion",
  "3.2": "task-3-2-compute-companion",
  "3.3": "task-3-3-databases-companion",
  "3.4": "task-3-4-network-companion",
  "3.5": "task-3-5-ingestion-companion",
  "4.1": "task-4-1-storage-companion",
  "4.2": "task-4-2-compute-companion",
  "4.3": "task-4-3-database-companion",
  "4.4": "task-4-4-network-companion",
};
const saaTaskCompanionAsset = (title: string) => saaTaskCompanionWalkthroughs[title.match(/^Task ([0-9.]+)/)?.[1] || ""];

function AwsSaaTaskWalkthrough({ asset, companionAsset, title }: { asset: string; companionAsset?: string; title: string }) {
  const [openAsset, setOpenAsset] = useState<string | null>(null);
  const [failedAssets, setFailedAssets] = useState<Record<string, boolean>>({});
  const items = [
    { asset, label: "PRIMARY WALKTHROUGH" },
    ...(companionAsset ? [{ asset: companionAsset, label: "COMPANION COVERAGE" }] : []),
  ];
  const source = (item: string) => `https://pub-a5e11688cacf4195a0d3c6afe384eb56.r2.dev/aws-certification-walkthroughs/saa-c03-tasks/${item}.webp`;
  const markFailed = (item: string) => setFailedAssets((current) => ({ ...current, [item]: true }));
  return <>
    <div className="aws-saa-task-walkthrough-pair">
      {items.map((item) => failedAssets[item.asset] ? (
        <div className="aws-saa-task-walkthrough-fallback" key={item.asset}><b>{item.label} pending</b><span>Upload <code>{item.asset}.webp</code> to <code>aws-certification-walkthroughs/saa-c03-tasks/</code>.</span></div>
      ) : (
        <button type="button" className="aws-saa-task-walkthrough" onClick={() => setOpenAsset(item.asset)} aria-label={`Open ${title} ${item.label.toLowerCase()} full screen`}>
          <small>{item.label}</small>
          <img src={source(item.asset)} alt={`${title} AWS ${item.label.toLowerCase()}`} loading="lazy" onError={() => markFailed(item.asset)} />
          <span>Open selected walkthrough full screen ↗</span>
        </button>
      ))}
    </div>
    {openAsset && <div className="aws-saa-task-walkthrough-modal" role="dialog" aria-modal="true" aria-label={`${title} walkthrough`} onClick={() => setOpenAsset(null)}>
      <button type="button" onClick={() => setOpenAsset(null)}>Close ×</button>
      <img src={source(openAsset)} alt={`${title} AWS console walkthrough full view`} onClick={(event) => event.stopPropagation()} />
    </div>}
  </>;
}

const saaDomains: SAADomain[] = [
  {
    number: "01", title: "Design Secure Architectures", weight: "30%", outcome: "Build identity, network, application, and data controls around the workload boundary.", flow: ["Identity", "Network", "Application", "Data"],
    tasks: [
      { title: "Task 1.1 · Design secure access to AWS resources", ask: "Choose identity, authorization, account, and resource-policy controls that give the right principal the right access at the right scope.", focus: ["IAM users, groups, roles, policies, MFA, root-user protection, and least privilege", "Federated access, IAM Identity Center, STS, role switching, and cross-account access", "Organizations, Control Tower, service control policies, resource policies, and multi-account boundaries", "AWS Regions, Availability Zones, shared responsibility, and secure access patterns"], services: ["AWS IAM", "AWS IAM Identity Center", "AWS Security Token Service", "AWS Organizations"], visual: V("decision", "Access is a policy decision", "Identity proves who; policy decides what", ["Principal", "Action", "Resource", "Condition", "Allow / deny"], "Evaluate the principal, requested action, target resource, and conditions at the policy boundary. Then apply the narrowest scope that satisfies the workload.", "A role is temporary identity; a policy is the permission statement; an SCP is a maximum boundary, not an allow grant.") },
      { title: "Task 1.2 · Design secure workloads and applications", ask: "Combine segmentation, traffic controls, application security services, and protected connectivity to reduce workload attack paths.", focus: ["VPC subnet tiers, route tables, security groups, network ACLs, NAT gateways, and port/protocol control", "Cognito, GuardDuty, Macie, Shield, WAF, Secrets Manager, and IAM Identity Center by use case", "Public and private subnet segmentation, secure service endpoints, VPN, and Direct Connect", "External threats such as DDoS and SQL injection, and the control that addresses each threat"], services: ["Amazon VPC", "AWS WAF", "AWS Secrets Manager", "Amazon GuardDuty"], visual: V("layers", "Security follows the request path", "Layer the controls around the application", ["Internet edge", "WAF / Shield", "Public entry", "Private tiers", "Secrets + data"], "A secure workload separates internet-facing entry from private application and data tiers, then applies identity, network, and data controls at each boundary.", "WAF understands HTTP attacks; security groups filter stateful traffic; NACLs filter subnet traffic; Secrets Manager protects application credentials.") },
      { title: "Task 1.3 · Determine appropriate data security controls", ask: "Protect data through encryption, key policy, access, retention, backup, recovery, and lifecycle controls that match its classification and compliance needs.", focus: ["Data governance, classification, access policies, retention, lifecycle, backups, and replication", "KMS encryption at rest, ACM/TLS encryption in transit, key policies, rotation, and certificate renewal", "Compliance alignment and separation of data-plane access from key-management access", "Backup and replication choices that preserve confidentiality, durability, and recoverability"], services: ["AWS KMS", "AWS Certificate Manager", "AWS Backup"], visual: V("flow", "Data protection is a lifecycle", "Protect the value before, during, and after use", ["Classify", "Authorize", "Encrypt", "Replicate", "Retain / recover"], "Data controls are connected: classification influences access and retention; keys protect content; backups and replicas protect availability; evidence proves the controls operate.", "KMS protects keys and encrypted data; ACM manages certificates for TLS; backups are not a substitute for access control.") },
    ]
  },
  {
    number: "02", title: "Design Resilient Architectures", weight: "26%", outcome: "Remove single points of failure and design for scale, loose coupling, availability, and recoverability.", flow: ["Decouple", "Scale", "Fail over", "Recover"],
    tasks: [
      { title: "Task 2.1 · Design scalable and loosely coupled architectures", ask: "Select the right compute, storage, networking, messaging, caching, container, serverless, and orchestration patterns for changing demand.", focus: ["Event-driven, microservice, multi-tier, stateless, serverless, and container architectures", "API creation and management, managed services such as Transfer Family and Secrets Manager, and ALB load balancing", "SQS, SNS, EventBridge, API Gateway, Step Functions, caching, read replicas, and publish/subscribe", "Horizontal versus vertical scaling, CDN/edge acceleration, object/file/block storage, and future growth", "ECS, EKS, Fargate, Lambda, purpose-built compute/storage/network/database services, and migration into containers"], services: ["Amazon SQS", "Amazon EventBridge", "AWS Lambda", "Amazon ECS"], visual: V("flow", "Loose coupling absorbs change", "Producers do not wait on every consumer", ["Producer", "Event / queue", "Independent workers", "State store", "Consumer"], "Queues buffer work, events route intent, and independently scaling consumers process at their own pace. This reduces timing and failure dependencies between components.", "Use a queue for work distribution, pub/sub for fan-out, and a workflow service when stateful orchestration is the requirement.") },
      { title: "Task 2.2 · Design highly available and/or fault-tolerant architectures", ask: "Design across failure domains and choose an RTO/RPO-aligned recovery strategy with automation, visibility, and no single point of failure.", focus: ["Regions, Availability Zones, Route 53, route tables, load balancing, distributed design, immutable infrastructure, and service quotas/throttling", "Backup and restore, pilot light, warm standby, active-active, RPO, and RTO", "Automation, health metrics, failover, durable storage, replication, and legacy-workload reliability using managed services", "X-Ray, RDS Proxy, storage durability/availability, and purpose-built services such as Comprehend or Polly where appropriate", "Remove single points of failure and select the least complex recovery strategy that meets the business requirement"], services: ["Amazon Route 53", "Elastic Load Balancing", "AWS Backup", "AWS X-Ray"], visual: V("timeline", "Recovery strategy follows business loss", "RPO and RTO narrow the design", ["Failure", "Detect", "Fail over", "Restore / replay", "Validate"], "Start with how much data may be lost and how quickly service must return. Then choose the least complex strategy that meets those limits and test it.", "Backup and restore is cheaper but slower; active-active is faster but more complex and costly.") },
    ]
  },
  {
    number: "03", title: "Design High-Performing Architectures", weight: "24%", outcome: "Match workload access patterns, throughput, latency, and growth to the right AWS technology.", flow: ["Workload", "Data path", "Capacity", "Latency"],
    tasks: [
      { title: "Task 3.1 · Determine high-performing and/or scalable storage solutions", ask: "Choose object, file, block, or hybrid storage and configure it for the workload's throughput, latency, access pattern, and future growth.", focus: ["S3, EFS, EBS, FSx, hybrid storage, object/file/block characteristics, and business requirements", "Throughput, IOPS, latency, durability, access patterns, and scaling limits", "Data transfer and hybrid integration with DataSync, Storage Gateway, or Transfer Family", "Determine the storage service and configuration for performance demands and future capacity, not only today's size"], services: ["Amazon S3", "Amazon EBS", "Amazon EFS", "AWS Storage Gateway"], visual: V("matrix", "Storage follows access shape", "Choose by data behavior, not product familiarity", ["Object\nlarge durable objects", "File\nshared hierarchy", "Block\nlow-latency volume", "Hybrid\non-prem + cloud"], "Object storage scales for independent objects, file storage shares a hierarchy, block storage attaches to compute, and hybrid services bridge existing environments.", "Ask whether the workload needs a filesystem, a mounted volume, or durable object access before comparing performance tiers.") },
      { title: "Task 3.2 · Design high-performing and elastic compute solutions", ask: "Select compute types, sizes, scaling signals, and decoupling patterns that meet performance and elasticity requirements.", focus: ["EC2 instance families and sizes, Lambda memory, Batch, EMR, Fargate, ECS, and EKS", "Global infrastructure, edge processing, queues, messaging, and publish/subscribe for distributed workloads", "EC2 Auto Scaling, AWS Auto Scaling, queue depth, utilization metrics, horizontal/vertical scaling, and hibernation", "Serverless patterns and container orchestration, with components decoupled so they scale independently", "Resource type and size selection based on workload requirements rather than habit"], services: ["Amazon EC2", "Amazon EC2 Auto Scaling", "AWS Lambda", "AWS Fargate"], visual: V("decision", "Elastic compute is a feedback loop", "Measure demand, then change capacity", ["Demand signal", "Metric", "Scaling policy", "Capacity", "Health check"], "A scaling policy connects workload demand to a capacity change and then checks whether the new fleet is healthy and sufficient.", "Scale on the metric that represents demand: queue depth, requests, concurrency, or throughput—not CPU by default.") },
      { title: "Task 3.3 · Determine high-performing database solutions", ask: "Match database engine, type, capacity, caching, replication, and connection strategy to access patterns and performance needs.", focus: ["Regions and Availability Zones, relational/non-relational/serverless/in-memory types, Aurora, RDS, DynamoDB, and purpose-built engines", "Read-intensive versus write-intensive access, capacity units, instance types, and Provisioned IOPS", "Read replicas, database connections, RDS Proxy, caching with ElastiCache, and replication", "Engine selection such as MySQL versus PostgreSQL, including homogeneous/heterogeneous migration implications", "Design the database architecture around access pattern, capacity, consistency, and connection behavior"], services: ["Amazon RDS", "Amazon Aurora", "Amazon DynamoDB", "Amazon ElastiCache"], visual: V("matrix", "Database choice starts with access pattern", "Shape the data path before choosing the engine", ["Relational\njoins + transactions", "Key-value\nknown access keys", "Cache\nhot reads", "Replica\nread scale", "Proxy\nconnection control"], "Performance comes from matching consistency, query shape, read/write ratio, connection behavior, and data model to the engine and its scaling model.", "Read replicas scale reads; they do not replace a multi-writer design or solve every write bottleneck.") },
      { title: "Task 3.4 · Determine high-performing and/or scalable network architectures", ask: "Design network topology, addressing, edge, connection, routing, and load-balancing choices that meet latency and scale requirements.", focus: ["Global, hybrid, and multi-tier topology, subnet tiers, routing, IP addressing, and resource placement", "CloudFront, Global Accelerator, ALB, VPN, Direct Connect, and PrivateLink use cases", "Scaling network configurations and selecting the load balancer at the right layer", "Future address space and network growth rather than only today's topology"], services: ["Amazon CloudFront", "AWS Global Accelerator", "Elastic Load Balancing", "Amazon VPC"], visual: V("flow", "Traffic should enter at the right edge", "Placement controls latency and scale", ["Client", "Edge / accelerator", "Load balancer", "Service tier", "Data tier"], "Use edge caching for content, acceleration for global TCP/UDP entry, and load balancing for distributing application traffic across healthy targets.", "CloudFront caches content; Global Accelerator improves global entry; ALB understands HTTP; NLB handles high-performance transport traffic.") },
      { title: "Task 3.5 · Determine high-performing data ingestion and transformation solutions", ask: "Design secure ingestion, streaming, transfer, transformation, processing, and visualization paths for the required volume and frequency.", focus: ["Data lakes, Kinesis streaming, Firehose delivery, Glue transformation, Athena/Lake Formation, and visualization", "Batch versus streaming ingestion, data transfer with DataSync and Storage Gateway, and secure endpoints", "EMR and other processing choices, throughput, sizes, speeds, and ingestion configuration", "Transforming formats such as CSV to Parquet and securing the ingestion access point"], services: ["Amazon Kinesis", "Amazon Data Firehose", "AWS Glue", "Amazon Athena"], visual: V("pipeline", "The data path has distinct jobs", "Ingest, transform, govern, and query", ["Sources", "Ingest", "Transform", "Lake / catalog", "Query / visualize"], "Separate ingestion from transformation and consumption so each stage can scale and use the right format, security boundary, and processing engine.", "Firehose simplifies delivery; Glue transforms/catalogs; Athena queries data in place; Lake Formation governs the lake.") },
    ]
  },
  {
    number: "04", title: "Design Cost-Optimized Architectures", weight: "20%", outcome: "Reduce total cost while preserving the availability, performance, security, and recovery requirement.", flow: ["Measure", "Right-size", "Tier", "Review"],
    tasks: [
      { title: "Task 4.1 · Design cost-optimized storage solutions", ask: "Choose the lowest-cost storage, transfer, tier, lifecycle, backup, and access strategy that still meets the workload requirement.", focus: ["S3 access patterns, Requester Pays, lifecycle, tiering, EFS, EBS, FSx, and object/file/block choices", "Cost allocation tags, multi-account billing, Cost Explorer, Budgets, and Cost and Usage Report", "HDD versus SSD block options, data transfer, DataSync, Transfer Family, Storage Gateway, and backup/archive choices", "Storage size, auto scaling, access patterns, retention, tier selection, lifecycle timing, and the lowest-cost migration path"], services: ["Amazon S3", "AWS Cost Explorer", "AWS Budgets", "AWS Backup"], visual: V("cycle", "Storage cost follows the lifecycle", "Move data as its value and access change", ["Hot", "Warm", "Cold", "Archive", "Delete"], "Measure access patterns, transition data to an appropriate tier, retain only as long as required, and review the resulting cost and retrieval trade-off.", "The cheapest tier is not always cheapest overall when retrieval frequency, latency, and transfer are included.") },
      { title: "Task 4.2 · Design cost-optimized compute solutions", ask: "Choose compute service, instance family, size, purchase model, scaling, and availability level that fit the workload economics.", focus: ["On-Demand, Spot, Reserved Instances, Savings Plans, cost allocation, and Cost Explorer/Budgets/CUR", "Regions and Availability Zones, EC2 families and sizes, Lambda, Fargate, containers, Outposts, and edge processing", "Horizontal/vertical scaling, hibernation, ALB versus NLB versus GWLB, and production versus non-production availability", "Right-size utilization, select the correct instance family and size, and choose the least expensive service that meets the requirement"], services: ["Amazon EC2", "AWS Lambda", "AWS Fargate", "Savings Plans"], visual: V("decision", "Compute cost is a commitment decision", "Match certainty and interruption tolerance", ["Variable demand", "Steady baseline", "Interruptible work", "Container / function", "Purchase model"], "Use serverless or elastic capacity for uncertain demand, commitments for stable baseline, and Spot for interruptible work with retryable processing.", "Do not choose Spot when interruption breaks the workload; do not buy commitments before measuring the baseline.") },
      { title: "Task 4.3 · Design cost-optimized database solutions", ask: "Choose database type, engine, capacity, caching, retention, backup, and migration approach that meets the requirement at the lowest sustainable cost.", focus: ["RDS, Aurora, DynamoDB, serverless, relational/non-relational, time-series and columnar patterns", "Capacity units, read replicas, connection proxies, caching, and access patterns", "Backup frequency, retention, snapshots, and data lifecycle", "Engine selection, schema/data migration, and Cost Explorer/Budgets/CUR visibility"], services: ["Amazon DynamoDB", "Amazon Aurora Serverless", "Amazon ElastiCache", "AWS Cost Explorer"], visual: V("matrix", "Database cost follows workload shape", "Pay for the capacity model you actually need", ["Provisioned", "On-demand", "Serverless", "Cache", "Retention"], "Compare steady capacity, bursty demand, connection overhead, read duplication, cache hit rate, and retention before selecting the database model.", "Cost optimization is not just a smaller instance; it is the right capacity and lifecycle model.") },
      { title: "Task 4.4 · Design cost-optimized network architectures", ask: "Reduce network transfer, connection, NAT, routing, bandwidth, and edge delivery cost without violating the architecture requirement.", focus: ["NAT gateway choices, shared versus per-AZ gateways, VPC endpoints, routes, peering, and Transit Gateway", "VPN versus Direct Connect versus internet, bandwidth allocation, and private connectivity", "CloudFront, Global Accelerator, DNS, ALB, throttling, and edge caching", "Cost Explorer/Budgets/CUR and reviewing existing workloads for transfer optimization"], services: ["Amazon VPC", "AWS Transit Gateway", "Amazon CloudFront", "AWS PrivateLink"], visual: V("layers", "Network cost is a path problem", "The route determines the bill", ["Workload", "AZ / Region path", "NAT / endpoint", "Internet / private link", "User"], "Place traffic on the shortest appropriate path, avoid unnecessary cross-AZ or cross-Region movement, and use endpoints or edge caching when they reduce repeated transfer.", "NAT gateways, data transfer, and bandwidth are architecture decisions—not afterthoughts in the cost review.") },
    ]
  }
];

function ObjectiveVisual({ visual }: { visual: NonNullable<SAAObjective["visual"]> }) {
  return <div className={`aws-saa-visual aws-saa-visual-${visual.kind}`} role="img" aria-label={visual.title}>
    <p className="aws-saa-visual-kicker">VISUAL EXPLAINER · {visual.kind.toUpperCase()}</p><h4>{visual.title}</h4><p className="aws-saa-visual-subtitle">{visual.subtitle}</p>
    <div className="aws-saa-diagram">{visual.nodes.map((node) => <span key={node}>{node}</span>)}</div>
    <div className="aws-saa-visual-note"><b>HOW IT WORKS</b><p>{visual.explanation}</p></div><div className="aws-saa-visual-cue"><b>EXAM CUE</b><p>{visual.cue}</p></div>
  </div>;
}

export default function AwsSaaCourseGuide() {
  const [domainIndex, setDomainIndex] = useState(0); const [taskIndex, setTaskIndex] = useState(0);
  const domain = saaDomains[domainIndex]; const task = domain.tasks[taskIndex] || domain.tasks[0];
  return <section className="aws-saa-guide" id="exam-guide">
    <div className="aws-saa-guide-head"><div><p className="aws-saa-eyebrow">SAA-C03 · EXAM GUIDE LEARNING PATH</p><h2>Design the architecture, not just the service.</h2><p>Follow the four official domains in exam order. Select one domain, then one exact task statement to see what AWS expects, what to practise, and which visual or console route fits the objective.</p><a href="https://docs.aws.amazon.com/aws-certification/latest/solutions-architect-associate-03/saa-03-exam-guide.html" target="_blank" rel="noreferrer">Open the official AWS SAA-C03 exam guide ↗</a></div><div className="aws-saa-stats"><strong>04</strong><span>exam domains</span><strong>14</strong><span>official tasks</span><strong>720</strong><span>passing scaled score</span></div></div>
    <div className="aws-saa-study-loop">{["Read the requirement", "Choose the boundary", "Trace the architecture", "Practise the console", "Explain the trade-off"].map((item, index) => <div key={item}><b>{String(index + 1).padStart(2, "0")}</b><span>{item}</span>{index < 4 && <i>→</i>}</div>)}</div>
    <div className="aws-saa-domain-tabs" role="tablist" aria-label="SAA-C03 exam domains">{saaDomains.map((item, index) => <button type="button" role="tab" aria-selected={index === domainIndex} className={index === domainIndex ? "is-selected" : ""} key={item.number} onClick={() => { setDomainIndex(index); setTaskIndex(0); }}><b>{item.number}</b><span>{item.title}</span><small>{item.weight}</small><em>{item.tasks.length} tasks</em></button>)}</div>
    <article className="aws-saa-domain"><header><div className="aws-saa-domain-number">{domain.number}</div><div><p>{domain.weight} · EXAM DOMAIN</p><h3>{domain.title}</h3><span>{domain.outcome}</span></div></header><div className="aws-saa-flow">{domain.flow.map((item, index) => <div key={item}><b>{item}</b>{index < domain.flow.length - 1 && <i>→</i>}</div>)}</div>
      <div className="aws-saa-task-tabs" role="tablist" aria-label={`${domain.title} tasks`}>{domain.tasks.map((item, index) => <button type="button" role="tab" aria-selected={index === taskIndex} className={index === taskIndex ? "is-selected" : ""} key={item.title} onClick={() => setTaskIndex(index)}><b>{String(index + 1).padStart(2, "0")}</b><span>{item.title}</span></button>)}</div>
      <section className="aws-saa-task"><div className="aws-saa-task-head"><div><p>OFFICIAL TASK STATEMENT</p><h4>{task.title}</h4></div><span>{task.services?.length ? "SERVICE PRACTICE + DESIGN DECISION" : "ARCHITECTURE VISUAL + DESIGN DECISION"}</span></div><div className="aws-saa-ask"><b>WHAT THIS TASK ASKS</b><span>{task.ask}</span></div><div className="aws-saa-task-grid"><div>{task.visual ? <ObjectiveVisual visual={task.visual} /> : null}</div><div className="aws-saa-focus"><p>GUIDE-ALIGNED FOCUS</p><ul>{task.focus.map((item) => <li key={item}>{item}</li>)}</ul>{task.services?.length ? <div className="aws-saa-console"><b>CONSOLE ROUTE</b><span>Open the matching service walkthrough, trace the setting shown, then explain why that service and configuration satisfy the requirement.</span><div>{task.services.map((service) => <span key={service}>{service}</span>)}</div>{saaTaskAsset(task.title) ? <AwsSaaTaskWalkthrough asset={saaTaskAsset(task.title)!} companionAsset={saaTaskCompanionAsset(task.title)} title={task.title} /> : <SharedServiceWalkthrough serviceName={task.services[0]} />}</div> : <div className="aws-saa-console aws-saa-no-console"><b>WHY A VISUAL FITS BETTER</b><span>This task is primarily an architecture selection problem. Use the visual to compare boundaries, failure modes, scaling signals, or cost trade-offs before opening a service console.</span></div>}</div></div></section><div className="aws-saa-memory"><b>EXAM MEMORY HOOK</b><span>Start with the business requirement, identify the constraint, then choose the AWS service and configuration that best satisfies it with the fewest unnecessary trade-offs.</span></div></article>
  </section>;
}
