"use client";

import { useEffect, useState } from "react";
import SharedServiceWalkthrough from "./SharedServiceWalkthrough";
import "./AwsSapCourseGuide.css";

type SapVisual = { kind: string; title: string; subtitle: string; nodes: string[]; explanation: string; cue: string };
type SapTask = { title: string; ask: string; focus: string[]; services: string[]; flow: string[]; visual: SapVisual };
type SapDomain = { number: string; title: string; weight: string; outcome: string; flow: string[]; tasks: SapTask[] };

const V = (kind: string, title: string, subtitle: string, nodes: string[], explanation: string, cue: string): SapVisual => ({ kind, title, subtitle, nodes, explanation, cue });

const sapDomains: SapDomain[] = [
  {
    number: "01", title: "Design Solutions for Organizational Complexity", weight: "26%", outcome: "Design governance, connectivity, security, resilience, and cost visibility across a complex AWS organization.", flow: ["Connect", "Control", "Recover", "Govern", "Measure"],
    tasks: [
      { title: "Task 1.1: Architect network connectivity strategies", ask: "Select a connectivity architecture that joins VPCs, on-premises networks, colocation, and AWS services with the required latency, routing, segmentation, and observability.", focus: ["Multi-VPC connectivity, transitive routing, hybrid DNS, subnetting, IP addressing, and traffic monitoring", "Direct Connect, VPN, Transit Gateway, VPC peering, service endpoints, and container networking", "Region and Availability Zone selection based on latency, resilience, and data locality"], services: ["Amazon VPC", "AWS Direct Connect", "AWS Transit Gateway", "Amazon Route 53"], flow: ["Classify the network participants and latency requirement.", "Choose hub, peering, hybrid, or endpoint connectivity.", "Trace routes, DNS, segmentation, and failure domains.", "Verify traffic with flow logs, metrics, and reachability evidence."], visual: V("topology", "Connectivity is a routing graph", "Every boundary needs a deliberate path", ["VPCs", "Transit hub", "Hybrid link", "DNS", "Service endpoint"], "Professional questions test whether the proposed topology supports growth, transitive routing, hybrid name resolution, and controlled service access—not merely whether two networks can connect.", "Transit Gateway simplifies many-to-many connectivity; endpoints keep service traffic private; DNS and route propagation are part of the design.") },
      { title: "Task 1.2: Prescribe security controls", ask: "Prescribe layered identity, network, encryption, detection, auditing, and centralized notification controls for an organization with cross-account and third-party access.", focus: ["Cross-account IAM and Identity Center access, federation, least privilege, resource policies, and permission boundaries", "Route tables, security groups, NACLs, KMS, ACM, CloudTrail, Access Analyzer, Security Hub, and Inspector", "Centralized security events, encryption at rest and in transit, and identity-provider integration"], services: ["AWS IAM", "AWS IAM Identity Center", "AWS KMS", "AWS Security Hub"], flow: ["Define identities, trust boundaries, and data sensitivity.", "Layer preventive, detective, and responsive controls.", "Centralize findings and audit evidence across accounts.", "Test effective permissions, encryption, and notification paths."], visual: V("layers", "Security is an organization-wide control plane", "Prevent, detect, investigate, respond", ["Identity", "Network", "Data", "Detection", "Response"], "SAP scenarios combine controls across accounts and layers. The correct answer normally preserves separation of duties while giving security teams centralized visibility and application teams delegated access.", "SCPs limit the maximum permission boundary; they do not grant permissions. CloudTrail records activity; Security Hub aggregates findings.") },
      { title: "Task 1.3: Design reliable and resilient architectures", ask: "Design disaster recovery and automatic recovery architectures that meet RTO, RPO, scale, backup, restoration, and failure-domain requirements.", focus: ["RTO/RPO, backup and restoration, pilot light, warm standby, multi-site, and Elastic Disaster Recovery", "Scale-up versus scale-out, automated recovery, data replication, and multi-Region design", "Recovery testing, durable backups, failover orchestration, and operational evidence"], services: ["AWS Elastic Disaster Recovery", "AWS Backup", "Amazon Route 53", "Amazon CloudWatch"], flow: ["Translate business loss into RTO and RPO.", "Select the least complex recovery pattern that meets both.", "Automate replication, detection, failover, and restore.", "Exercise the failure and measure recovery evidence."], visual: V("recovery", "Recovery follows the loss boundary", "RTO and RPO drive architecture", ["Failure", "Detect", "Replicate", "Fail over", "Prove"], "The professional-level decision is not simply backup versus replication. It is a trade-off among recovery time, recoverable data, operating complexity, testing effort, and cost.", "Backup and restore is slower and cheaper; warm standby reduces recovery time; multi-site provides faster recovery at higher operating cost.") },
      { title: "Task 1.4: Design a multi-account AWS environment", ask: "Design account structure, governance, resource sharing, central logging, and event notification patterns that fit organizational boundaries and operating models.", focus: ["Organizations, Control Tower, organizational units, account vending, SCPs, and delegated administration", "Central logging, multi-account event notifications, resource sharing, and security-account separation", "Governance models that balance central guardrails with application-team autonomy"], services: ["AWS Organizations", "AWS Control Tower", "AWS Resource Access Manager", "AWS CloudTrail"], flow: ["Separate workloads by security, billing, and operating boundary.", "Apply organization-wide guardrails and delegated administration.", "Share only required resources across accounts.", "Centralize logs, events, and governance evidence."], visual: V("hierarchy", "Accounts are control boundaries", "Organize first, automate second", ["Organization", "OU guardrails", "Workload accounts", "Shared services", "Central logs"], "A mature multi-account design makes ownership, blast radius, billing, security, and deployment boundaries explicit. Shared services should be intentional rather than an accidental central dependency.", "Use SCPs as guardrails, RAM for controlled sharing, and a dedicated log/archive account for evidence.") },
      { title: "Task 1.5: Determine cost optimization and visibility strategies", ask: "Create cost allocation, monitoring, rightsizing, purchasing, and reporting strategies that make spend visible and align it to business ownership.", focus: ["Cost Explorer, Budgets, Trusted Advisor, Pricing Calculator, Compute Optimizer, and S3 Storage Lens", "Tags, accounts, cost categories, chargeback/showback, and Cost and Usage Report analysis", "Reserved Instances, Savings Plans, Spot Instances, rightsizing, and utilization evidence"], services: ["AWS Cost Explorer", "AWS Budgets", "AWS Trusted Advisor", "AWS Compute Optimizer"], flow: ["Make ownership and usage measurable.", "Find waste and underutilized resources.", "Choose rightsizing and purchasing commitments.", "Alert, report, and continuously review the result."], visual: V("cycle", "Cost optimization is a feedback loop", "Measure before committing", ["Tag", "Measure", "Right-size", "Commit", "Review"], "Professional cost questions connect technical architecture to business accountability. The strongest strategy combines allocation, visibility, waste removal, purchase options, and ongoing review.", "Do not commit before establishing a stable baseline; Spot fits interruptible work, not critical stateful workloads.") }
    ]
  },
  {
    number: "02", title: "Design for New Solutions", weight: "29%", outcome: "Design new workloads for deployment, continuity, security, reliability, performance, and cost objectives.", flow: ["Deploy", "Continue", "Secure", "Scale", "Optimize"],
    tasks: [
      { title: "Task 2.1: Design a deployment strategy to meet business requirements", ask: "Choose deployment, IaC, CI/CD, change-management, configuration, upgrade, and rollback patterns that meet business risk and delivery requirements.", focus: ["CloudFormation, CI/CD, blue/green, canary, rolling, all-at-once, and rollback strategies", "Systems Manager configuration and patch management, managed services, and reducing provisioning overhead", "Upgrade paths for new services/features and delegation of complex operations to AWS"], services: ["AWS CloudFormation", "AWS CodePipeline", "AWS CodeDeploy", "AWS Systems Manager"], flow: ["Classify change risk and release constraints.", "Select IaC and deployment strategy.", "Add validation, health checks, approval, and rollback.", "Measure the release and improve the delivery path."], visual: V("pipeline", "Deployment is controlled change", "Release safely, then recover quickly", ["Commit", "Build", "Validate", "Release", "Rollback"], "A professional deployment strategy connects business requirements to blast radius, approval, automation, observability, and rollback. The fastest deployment is not always the safest deployment.", "Blue/green reduces cutover risk; canary limits exposure; CloudFormation and Systems Manager establish repeatability.") },
      { title: "Task 2.2: Design a solution to ensure business continuity", ask: "Design an automated, tested, and cost-effective continuity architecture across Availability Zones or Regions with appropriate replication, monitoring, and recovery.", focus: ["RTO/RPO, global infrastructure, Route 53 routing, backup and restore, pilot light, warm standby, and multi-site", "Database and data replication, automated backups, recovery testing, and centralized monitoring", "Application and infrastructure availability during disruption, including failover validation"], services: ["Amazon Route 53", "AWS Backup", "Amazon Aurora", "AWS Elastic Disaster Recovery"], flow: ["Define the disruption and business continuity target.", "Choose replication and recovery topology.", "Automate detection, failover, and restoration.", "Test the runbook and record recovery evidence."], visual: V("recovery", "Continuity is a tested operating capability", "A diagram is not a recovery plan", ["Primary", "Replica", "Health", "Failover", "Test"], "Continuity is complete only when data, application dependencies, DNS, operations, and people can recover together. Testing exposes hidden coupling and stale assumptions.", "A multi-Region design without tested failover is only theoretical resilience.") },
      { title: "Task 2.3: Determine security controls based on requirements", ask: "Select identity, network, encryption, endpoint, credential, managed security, patch, and attack-mitigation controls for a new workload.", focus: ["Least privilege IAM, security groups, NACLs, service endpoints, credentials, encryption, WAF, Shield, GuardDuty, and Security Hub", "Inbound and outbound flow control, web attack mitigation, patch compliance, and data protection", "Private integrations and control selection based on threat, exposure, and operational requirement"], services: ["AWS WAF", "AWS Shield", "Amazon GuardDuty", "AWS Secrets Manager"], flow: ["Identify asset, threat, and exposure.", "Place preventive controls at each boundary.", "Detect, aggregate, and prioritize findings.", "Automate patching, response, and evidence collection."], visual: V("layers", "Threats map to control layers", "Use the narrowest effective control", ["Threat", "Edge", "Network", "Identity", "Data"], "Security answers should connect the threat to the control: WAF for HTTP attacks, Shield for DDoS, security groups for stateful traffic, endpoints for private access, and secrets services for credentials.", "A security group is not a web application firewall; encryption does not replace authorization.") },
      { title: "Task 2.4: Design a strategy to meet reliability requirements", ask: "Design highly available, loosely coupled, self-healing architectures using replication, scaling, quotas, integration services, and DNS routing.", focus: ["Multi-AZ and multi-Region design, S3/RDS/ElastiCache replication, Auto Scaling, quotas, and limits", "SNS, SQS, Step Functions, Route 53 routing policies, load balancing, and failover", "Design for failure, managed service availability, seamless recovery, and operational maintenance"], services: ["Amazon Route 53", "Amazon SQS", "AWS Auto Scaling", "AWS Step Functions"], flow: ["Identify failure domains and dependency coupling.", "Add buffering, replication, health checks, and scaling.", "Automate failover and stateful recovery.", "Validate quotas, limits, and operational behavior."], visual: V("flow", "Reliability removes dependency chains", "Buffer, replicate, heal", ["Request", "Buffer", "Worker", "Replica", "Health"], "Reliable systems isolate failures and prevent one slow or unavailable dependency from cascading across the workload. Managed services reduce operational burden but still require limits and failure testing.", "Use queues for pressure relief, replicas for data availability, and Route 53 policies for controlled traffic steering.") },
      { title: "Task 2.5: Design a solution to meet performance objectives", ask: "Translate business objectives into measurable performance targets and choose elastic, cached, buffered, replicated, rightsized, and purpose-built services.", focus: ["Performance monitoring, storage options, instance families, purpose-built databases, caching, buffering, and replicas", "Large-scale access patterns, elasticity, rightsizing, and managed service adoption", "KPIs, SLAs, bottleneck analysis, testing remediation, and technology selection methodology"], services: ["Amazon CloudWatch", "Amazon CloudFront", "Amazon ElastiCache", "Amazon DynamoDB"], flow: ["Turn the requirement into KPI and SLA.", "Locate the bottleneck and access pattern.", "Test cache, buffer, replica, or scaling changes.", "Rightsize and verify the measured outcome."], visual: V("feedback", "Performance is measurable behavior", "Observe, change, validate", ["KPI", "Bottleneck", "Pattern", "Test", "Result"], "SAP performance scenarios reward a disciplined method: define the metric, find the limiting resource, select an appropriate pattern, test it, and compare the result to the requirement.", "Do not add a faster instance when the bottleneck is connection count, data transfer, query shape, or an unbounded queue.") },
      { title: "Task 2.6: Determine a cost optimization strategy to meet solution goals and objectives", ask: "Choose service, capacity, pricing, storage, transfer, and expenditure controls that meet solution goals at sustainable cost.", focus: ["Cost Explorer, Trusted Advisor, Pricing Calculator, Savings Plans, Reserved Instances, and storage tiering", "Data transfer modeling, managed services, rightsizing, and service selection", "Usage awareness, budgets, alerts, reporting, and expenditure controls"], services: ["AWS Cost Explorer", "AWS Pricing Calculator", "AWS Savings Plans", "AWS Budgets"], flow: ["Model the workload and cost drivers.", "Compare managed, elastic, and committed capacity.", "Reduce transfer, storage, and idle resource cost.", "Add budgets and review actual usage."], visual: V("matrix", "Cost is a design constraint", "Optimize the whole workload", ["Capacity", "Storage", "Transfer", "Commitment", "Control"], "The lowest unit price can lose when it increases transfer, operations, idle capacity, or recovery cost. Compare total cost against the business objective and operating model.", "Cost optimization must preserve the required performance, availability, security, and recovery outcome.") }
    ]
  },
  {
    number: "03", title: "Continuous Improvement for Existing Solutions", weight: "25%", outcome: "Diagnose existing workloads and prioritize operational, security, performance, reliability, and cost improvements.", flow: ["Observe", "Diagnose", "Prioritize", "Remediate", "Prove"],
    tasks: [
      { title: "Task 3.1: Determine a strategy to improve overall operational excellence", ask: "Improve monitoring, logging, deployment, configuration management, automation, remediation, and failure-exercise practices for an existing solution.", focus: ["Alerting, automatic remediation, disaster recovery planning, CloudWatch, CI/CD, deployment strategies, and Systems Manager", "Logging and monitoring strategy, deployment improvement, automation priority, and configuration management", "Failure scenario exercises and recovery-action validation"], services: ["Amazon CloudWatch", "AWS Systems Manager", "AWS CodeDeploy", "AWS Fault Injection Service"], flow: ["Observe signals, logs, and operational toil.", "Prioritize the highest-risk manual or blind spot.", "Automate configuration, deployment, and remediation.", "Exercise failure and prove the runbook."], visual: V("cycle", "Operational excellence closes the loop", "Detect, automate, learn", ["Observe", "Alert", "Act", "Recover", "Improve"], "Improvement is not adding dashboards. It is turning signals into reliable action, reducing manual work, testing recovery, and learning from operational outcomes.", "A useful alert has an owner and an action; a runbook is incomplete until it is exercised.") },
      { title: "Task 3.2: Determine a strategy to improve security", ask: "Improve an existing environment through least privilege, traceability, secrets, patching, backups, automated detection, remediation, and layered review.", focus: ["Data sensitivity, retention, regulation, Config rules, secrets management, least privilege, patching, and backups", "Security at every layer, user/service traceability, vulnerability prioritization, and automated response", "Remediation techniques and evidence that controls remain effective over time"], services: ["AWS Config", "AWS Security Hub", "Amazon Inspector", "AWS Secrets Manager"], flow: ["Discover drift, exposure, and control gaps.", "Prioritize by risk, sensitivity, and exploitability.", "Automate patching, secrets, detection, and remediation.", "Audit the result and preserve traceability."], visual: V("layers", "Security improvement is continuous control", "Find drift before attackers do", ["Inventory", "Assess", "Protect", "Remediate", "Audit"], "Existing environments decay through drift, stale permissions, unpatched software, unmanaged secrets, and incomplete evidence. Improvement strategies make those conditions visible and actionable.", "Config detects configuration drift; Inspector identifies vulnerabilities; Security Hub prioritizes findings.") },
      { title: "Task 3.3: Determine a strategy to improve performance", ask: "Identify bottlenecks and use measurable KPIs, rightsizing, global services, managed services, and tested remediation to improve an existing workload.", focus: ["Auto Scaling, instance fleets, placement groups, Global Accelerator, CloudFront, edge computing, and CloudWatch", "SLAs, KPIs, business-to-metric translation, remediation testing, and managed service adoption", "Rightsizing, bottleneck analysis, and performance trend evaluation"], services: ["Amazon CloudWatch", "AWS Global Accelerator", "Amazon CloudFront", "AWS Compute Optimizer"], flow: ["Translate user experience into measurable KPI.", "Correlate traces, metrics, and resource saturation.", "Test a targeted remediation or managed-service change.", "Rightsize and confirm the improvement against the SLA."], visual: V("feedback", "Performance improvement needs evidence", "A faster component is not always a faster system", ["SLA", "Metric", "Bottleneck", "Change", "Proof"], "A professional architect distinguishes symptoms from constraints. Measure the full request path, test the smallest useful change, and prove the result under representative load.", "CloudFront and Global Accelerator solve different edge problems; Compute Optimizer supports rightsizing, not architecture judgment.") },
      { title: "Task 3.4: Determine a strategy to improve reliability", ask: "Improve an existing architecture by removing single points of failure, enabling replication, self-healing, elastic scaling, and disaster recovery.", focus: ["Global infrastructure, replication, load balancing, Auto Scaling, high availability, resiliency, quotas, and disaster recovery", "Application growth and usage trends, reliability gap analysis, and failure-domain review", "Self-healing, elastic features, data replication, and remediation of single points of failure"], services: ["Elastic Load Balancing", "Amazon EC2 Auto Scaling", "Amazon RDS", "AWS Elastic Disaster Recovery"], flow: ["Map dependencies and failure domains.", "Find the single point and quantify its impact.", "Add redundancy, health checks, replication, or elasticity.", "Run failure tests and verify recovery behavior."], visual: V("topology", "Reliability is a dependency graph", "Remove the one point that can stop everything", ["Dependency", "Failure", "Replica", "Health", "Recovery"], "Reliability improvement starts with the current architecture, not a preferred service. Trace the dependency graph, identify concentration risk, and remediate the failure mode that matters most.", "Multi-AZ improves availability; multi-Region improves regional recovery; neither removes every application-level dependency.") },
      { title: "Task 3.5: Identify opportunities for cost optimizations", ask: "Use usage reports, rightsizing, pricing models, transfer analysis, alarms, CUR detail, and tagging to reduce waste in an existing solution.", focus: ["Spot, scaling policies, rightsizing, Reserved Instances, Savings Plans, networking and data transfer costs", "Cost management, alerting, reporting, unused-resource discovery, and granular CUR analysis", "Tagging for allocation, billing alarms, and underutilized/overutilized resource analysis"], services: ["AWS Cost and Usage Reports", "AWS Cost Explorer", "AWS Budgets", "AWS Compute Optimizer"], flow: ["Collect usage, ownership, and transfer evidence.", "Separate waste from intentional capacity.", "Apply rightsizing, schedule, tier, or purchase changes.", "Alert and report so savings persist."], visual: V("cycle", "Cost improvement is an operating practice", "Find waste without breaking the workload", ["Usage", "Owner", "Waste", "Change", "Savings"], "Existing workloads contain both waste and purposeful headroom. Cost improvement requires context, tags, workload criticality, and a measured change—not indiscriminate downsizing.", "CUR provides granular evidence; Cost Explorer shows trends; Budgets creates control; Compute Optimizer suggests rightsizing.") }
    ]
  },
  {
    number: "04", title: "Accelerate Workload Migration and Modernization", weight: "20%", outcome: "Assess, migrate, rearchitect, and modernize existing workloads using the right migration path and AWS services.", flow: ["Assess", "Choose 7R", "Migrate", "Rearchitect", "Modernize"],
    tasks: [
      { title: "Task 4.1: Select existing workloads and processes for potential migration", ask: "Assess applications and portfolios, prioritize migration waves, evaluate the seven migration strategies, and compare total cost of ownership.", focus: ["Migration Hub, Application Discovery, portfolio assessment, asset planning, wave planning, and TCO", "Application dependencies, business value, readiness, risk, and migration sequencing", "Rehost, replatform, refactor, repurchase, retain, retire, and relocate decisions"], services: ["AWS Migration Hub", "AWS Application Discovery Service", "AWS Migration Evaluator", "AWS Pricing Calculator"], flow: ["Discover assets and dependencies.", "Score business value, risk, and readiness.", "Select a 7R strategy and migration wave.", "Validate TCO and migration outcomes."], visual: V("matrix", "Migration starts with portfolio evidence", "Do not choose the 7R before understanding the workload", ["Discover", "Assess", "Prioritize", "7R", "Wave"], "Portfolio migration is a sequencing problem. A workload's business criticality, dependencies, technical debt, cost, and modernization value determine when and how it should move.", "Rehost is not automatically the best first move; retain and retire are valid decisions when evidence supports them.") },
      { title: "Task 4.2: Determine the optimal migration approach for existing workloads", ask: "Select data, application, database, network, identity, and governance migration mechanisms that fit security, downtime, dependency, and operating requirements.", focus: ["DataSync, Transfer Family, Snow Family, S3 Transfer Acceleration, Application Discovery, and Application Migration Service", "DMS, SCT, Direct Connect, VPN, Route 53, Identity Center, Directory Service, Control Tower, and Organizations", "Database, application, and data transfer strategy with secure tooling and appropriate governance"], services: ["AWS Database Migration Service", "AWS DataSync", "AWS Application Migration Service", "AWS Control Tower"], flow: ["Classify the migration object and downtime tolerance.", "Choose the transfer mechanism and security path.", "Sequence dependencies and validate cutover.", "Govern, monitor, and roll back when required."], visual: V("pipeline", "Migration is a coordinated transfer", "Move dependencies in the right order", ["Source", "Transfer", "Transform", "Validate", "Cutover"], "The optimal migration approach depends on data volume, change rate, downtime, compatibility, security, dependency order, and rollback. A tool choice without a cutover strategy is incomplete.", "DMS handles database replication; SCT handles schema conversion; DataSync moves file/object data; MGN moves servers.") },
      { title: "Task 4.3: Determine a new architecture for existing workloads", ask: "Select the appropriate compute, container, storage, and database platforms when redesigning an existing workload for AWS.", focus: ["EC2, Elastic Beanstalk, ECS, EKS, Fargate, ECR, EBS, EFS, FSx, S3, and Storage Gateway", "DynamoDB, OpenSearch, RDS, self-managed databases on EC2, and purpose-built platform choices", "Compute, container hosting, storage, and database selection based on workload constraints"], services: ["Amazon EC2", "Amazon ECS", "AWS Fargate", "Amazon RDS"], flow: ["Extract workload constraints from the current system.", "Choose the target compute and hosting model.", "Map storage semantics and database behavior.", "Prove compatibility, operations, and migration effort."], visual: V("matrix", "Rearchitecture preserves behavior intentionally", "Change the platform without losing the requirement", ["Compute", "Containers", "Storage", "Database", "Operations"], "A new architecture is successful when it preserves required behavior while improving operations, scale, cost, resilience, or delivery. Platform novelty alone is not modernization value.", "ECS, EKS, and Fargate solve different control and operating-model needs; database selection follows access pattern and compatibility.") },
      { title: "Task 4.4: Determine opportunities for modernization and enhancements", ask: "Identify where decoupling, serverless, containers, purpose-built databases, and integration services can improve an existing workload.", focus: ["Lambda, ECS, EKS, Fargate, S3, EFS, DynamoDB, Aurora Serverless, ElastiCache, and integration services", "Decoupling with SQS, SNS, EventBridge, and Step Functions", "Serverless opportunities, container selection, purpose-built data stores, and application integration"], services: ["AWS Lambda", "Amazon EventBridge", "Amazon SQS", "Amazon Aurora Serverless"], flow: ["Find coupling, manual operations, and scaling friction.", "Select the smallest modernization seam.", "Introduce managed, serverless, or purpose-built capability.", "Measure value and expand modernization safely."], visual: V("flow", "Modernization removes unnecessary ownership", "Delegate undifferentiated work", ["Legacy", "Seam", "Managed service", "Event", "Outcome"], "Modernization is a sequence of valuable changes: decouple a dependency, delegate operations, choose a purpose-built service, and preserve a controlled path to expand.", "Use events for intent and fan-out, queues for work distribution, Lambda for event-driven execution, and Step Functions for stateful orchestration.") }
    ]
  }
];

const SAP_TASK_R2_BASE = "https://pub-a5e11688cacf4195a0d3c6afe384eb56.r2.dev/aws-certification-walkthroughs/sap-c02-tasks";

function SapTaskWalkthrough({ task }: { task: SapTask }) {
  const [fullscreenSrc, setFullscreenSrc] = useState<string | null>(null);
  const [missing, setMissing] = useState<string[]>([]);
  useEffect(() => {
    if (!fullscreenSrc) return;
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") setFullscreenSrc(null);
    };
    document.addEventListener("keydown", onKeyDown);
    return () => document.removeEventListener("keydown", onKeyDown);
  }, [fullscreenSrc]);
  const match = task.title.match(/Task (\d+)\.(\d+)/);
  const taskId = match ? `${match[1]}-${match[2]}` : "";
  const primary = taskId ? `${SAP_TASK_R2_BASE}/sap-c02-task-${taskId}-primary.png` : "";
  const companion = taskId ? `${SAP_TASK_R2_BASE}/sap-c02-task-${taskId}-companion.png` : "";
  const alternate = taskId === "1-2" ? `${SAP_TASK_R2_BASE}/sap-c02-task-1-2-alternate.png` : "";
  return <div className="aws-sap-task-walkthrough">
    <div className="aws-sap-task-walkthrough-head"><b>CONSOLE WALKTHROUGH · {taskId.replace("-", ".")}</b><span>Click any board to open full screen</span></div>
    <div className="aws-sap-task-walkthrough-grid">
      <figure><figcaption>PRIMARY WALKTHROUGH</figcaption><button type="button" className="aws-sap-task-image-button" onClick={() => setFullscreenSrc(primary)}><img src={primary} alt={`${task.title} primary walkthrough`} loading="lazy" onError={event => { event.currentTarget.style.display = "none"; setMissing(items => items.includes(event.currentTarget.src) ? items : [...items, event.currentTarget.src]); }} /></button></figure>
      <figure><figcaption>COMPANION COVERAGE</figcaption><button type="button" className="aws-sap-task-image-button" onClick={() => setFullscreenSrc(companion)}><img src={companion} alt={`${task.title} companion walkthrough`} loading="lazy" /></button></figure>
      {alternate && <figure><figcaption>ALTERNATE TASK BOARD</figcaption><button type="button" className="aws-sap-task-image-button" onClick={() => setFullscreenSrc(alternate)}><img src={alternate} alt={`${task.title} alternate walkthrough`} loading="lazy" /></button></figure>}
    </div>
    {missing.length > 0 && <p className="aws-sap-task-walkthrough-note">Upload matching files to <code>aws-certification-walkthroughs/sap-c02-tasks/</code>. The page uses the exact task number, so Task {taskId.replace("-", ".")} cannot resolve to another task or shared service image.</p>}
    {fullscreenSrc && <div className="aws-sap-lightbox" role="dialog" aria-modal="true" aria-label={`${task.title} full-screen walkthrough`} onClick={() => setFullscreenSrc(null)}>
      <button type="button" className="aws-sap-lightbox-close" aria-label="Close full-screen walkthrough" onClick={() => setFullscreenSrc(null)}>×</button>
      <img src={fullscreenSrc} alt={`${task.title} full-screen walkthrough`} onClick={(event) => event.stopPropagation()} />
    </div>}
  </div>;
}

const openSapCourseService = (name: string) => {
  window.dispatchEvent(new CustomEvent("aws-course-service", { detail: { name, courseCode: "SAP" } }));
  requestAnimationFrame(() => document.getElementById("curriculum")?.scrollIntoView({ behavior: "smooth", block: "start" }));
};

function SapVisual({ task }: { task: SapTask }) {
  return <div className={"aws-sap-visual aws-sap-visual-" + task.visual.kind}>
    <p className="aws-sap-kicker">VISUAL EXPLAINER · {task.visual.kind.toUpperCase()}</p>
    <h4>{task.visual.title}</h4>
    <p className="aws-sap-subtitle">{task.visual.subtitle}</p>
    <div className="aws-sap-diagram">{task.visual.nodes.map((node) => <span key={node}>{node}</span>)}</div>
    <div className="aws-sap-flow-map"><div><b>TASK-TO-DESIGN FLOW</b><span>Translate the exam requirement into an architecture decision.</span></div><div className="aws-sap-flow-steps">{task.flow.map((step, index) => <div className="aws-sap-flow-step" key={step}><strong>{String(index + 1).padStart(2, "0")}</strong><div><b>{["READ THE ASK", "CHOOSE THE PATTERN", "APPLY THE CONTROL", "PROVE THE OUTCOME"][index] || "PROVE THE OUTCOME"}</b><span>{step}</span></div>{index < task.flow.length - 1 && <i>→</i>}</div>)}</div></div>
    <div className="aws-sap-visual-checks"><div><b>EXAM REQUIREMENT</b><span>{task.ask}</span></div><div><b>GUIDE-ALIGNED COVERAGE</b><span>{task.focus.slice(0, 2).join(" · ")}</span></div></div>
    <div className="aws-sap-note"><b>HOW IT WORKS</b><p>{task.visual.explanation}</p></div>
    <div className="aws-sap-cue"><b>EXAM CUE</b><p>{task.visual.cue}</p></div>
    <div className="aws-sap-services"><b>REVIEW THESE SERVICES IN THIS SAP COURSE</b><div>{task.services.map((service) => <button type="button" key={service} onClick={() => openSapCourseService(service)}>{service} ↗</button>)}</div></div>
  </div>;
}

export default function AwsSapCourseGuide() {
  const [domainIndex, setDomainIndex] = useState(0);
  const [taskIndex, setTaskIndex] = useState(0);
  const domain = sapDomains[domainIndex];
  const task = domain.tasks[taskIndex] || domain.tasks[0];
  return <section className="aws-sap-guide" id="sap-exam-guide">
    <div className="aws-sap-head"><div><p className="aws-sap-eyebrow">SAP-C02 · EXAM GUIDE LEARNING PATH</p><h2>Design for organizational scale, change, and modernization.</h2><p>Follow all four official domains and all 20 exact SAP-C02 tasks. Select a domain and task to study the exam ask, architecture flow, service route, and verification decision.</p><div className="aws-sap-coverage"><b>20 GUIDE TASKS CONNECTED</b><span>Every task combines the official AWS ask, a task-specific visual model, guide-aligned coverage, and related services from this SAP course.</span></div><a href="https://docs.aws.amazon.com/aws-certification/latest/solutions-architect-professional-02/solutions-architect-professional-02.html" target="_blank" rel="noreferrer">Open the official AWS SAP-C02 exam guide ↗</a></div><div className="aws-sap-stats"><strong>04</strong><span>exam domains</span><strong>20</strong><span>official tasks</span><strong>750</strong><span>passing scaled score</span></div></div>
    <div className="aws-sap-tabs" role="tablist" aria-label="SAP-C02 exam domains">{sapDomains.map((item, index) => <button type="button" role="tab" aria-selected={index === domainIndex} className={index === domainIndex ? "is-selected" : ""} key={item.number} onClick={() => { setDomainIndex(index); setTaskIndex(0); }}><b>{item.number}</b><span>{item.title}</span><small>{item.weight}</small><em>{item.tasks.length} tasks</em></button>)}</div>
    <article className="aws-sap-domain"><header><div className="aws-sap-domain-number">{domain.number}</div><div><p>{domain.weight} · EXAM DOMAIN</p><h3>{domain.title}</h3><span>{domain.outcome}</span></div></header><div className="aws-sap-domain-flow">{domain.flow.map((item, index) => <div key={item}><b>{item}</b>{index < domain.flow.length - 1 && <i>→</i>}</div>)}</div>
      <div className="aws-sap-task-tabs" role="tablist" aria-label={domain.title + " tasks"}>{domain.tasks.map((item, index) => <button type="button" role="tab" aria-selected={index === taskIndex} className={index === taskIndex ? "is-selected" : ""} key={item.title} onClick={() => setTaskIndex(index)}><b>{String(index + 1).padStart(2, "0")}</b><span>{item.title}</span></button>)}</div>
      <section className="aws-sap-task"><div className="aws-sap-task-head"><div><p>OFFICIAL TASK STATEMENT</p><h4>{task.title}</h4></div><span>SERVICE PRACTICE + DESIGN DECISION</span></div><div className="aws-sap-ask"><b>WHAT THIS TASK ASKS</b><span>{task.ask}</span></div><div className="aws-sap-task-grid"><SapVisual task={task}/><div className="aws-sap-focus"><p>GUIDE-ALIGNED FOCUS</p><ul>{task.focus.map((item) => <li key={item}>{item}</li>)}</ul><div className="aws-sap-console"><b>CONSOLE ROUTE + RELATED SERVICES</b><span>Review the matching service walkthrough, trace the configuration, and explain why it satisfies the SAP-C02 requirement.</span><div className="aws-sap-related"><b>REVIEW RELATED SERVICES IN THIS SAP COURSE</b><div>{task.services.map((service) => <button type="button" key={service} onClick={() => openSapCourseService(service)}>{service} ↗</button>)}</div></div><SapTaskWalkthrough task={task} /><SharedServiceWalkthrough serviceName={task.services[0]} /></div></div></div></section><div className="aws-sap-memory"><b>EXAM MEMORY HOOK</b><span>Start with the organizational or workload requirement, identify the constraint, choose the architecture pattern, and justify the trade-off with measurable evidence.</span></div></article>
  </section>;
}
