"use client";

import { useState } from "react";
import { Activity, BrainCircuit, Cloud, Database, FileText, Globe2, HardDrive, Laptop, Network, Server, Shield, Sparkles, Users } from "lucide-react";
import { assetUrl } from "../../lib/asset-url";
import "./AzureServiceLearning.css";
import "./AipServiceLearningDetails.css";
import "./AipServiceLearningDetailsV8.css";
import {architectureNodeDetail as describeArchitectureNode} from "../../lib/architecture-node-detail";
import "./ServiceLearningShowcase.css";

type Kind="user"|"data"|"security"|"network"|"storage"|"ai"|"monitor"|"app"|"compute"|"file"|"internet";
type Node={label:string;sub:string;kind?:Kind};
type Layer={title:string;nodes:Node[]};
type Architecture={title:string;note:string;reference:string;layers:Layer[]};
type Detail={
  category?:string;
  summary:string; concepts:string[]; fit:string[]; architectures:Architecture[];
  security:string[]; optimization:string[]; watch:string[]; cost:string[];
  choices:{name:string;when:string}[]; hook:string[];
};

const N=(label:string,sub:string,kind?:Kind):Node=>({label,sub,kind});
const L=(title:string,...nodes:Node[]):Layer=>({title,nodes});
const A=(title:string,note:string,reference:string,...layers:Layer[]):Architecture=>({title,note,reference,layers});

const D:Record<string,Detail>={
"Microsoft Foundry":{
 summary:"A unified Azure platform for building, evaluating, deploying and operating generative AI applications, agents and models.",
 concepts:["Projects organize model, agent, evaluation and connected-resource work; the project boundary is also an important identity and governance boundary.","The model catalog, prompt flow, evaluations, tracing and agent tooling address different lifecycle stages; selecting a model alone does not create a production system.","Foundry can connect models to Azure AI Search, data, tools and monitoring, but each connected resource keeps its own permissions, network and retention controls."],
 fit:["Use it as the team workspace when application developers, data scientists and AI governance owners need a shared lifecycle for model-backed applications.","Use projects to separate environments and ownership, then promote tested prompts, agents and evaluations through controlled deployment paths.","Choose a focused Azure service when the workload only needs one capability, such as OCR, translation or vector search without the broader AI lifecycle."],
 architectures:[A("Governed generative AI application","Foundry coordinates model selection, grounding, evaluation and deployment while data, identity and observability remain explicit.","Microsoft Foundry architecture and project guidance",L("Users",N("Employees / customers","Prompt or task","user")),L("Application",N("Web or API","Session and policy","app")),L("Foundry project",N("Microsoft Foundry","Models, agents, evaluations","ai"),N("Prompt flow","Test and trace","ai")),L("Grounding",N("Azure AI Search","Enterprise retrieval","data"),N("Azure Storage","Source documents","storage")),L("Operations",N("Azure Monitor","Traces and alerts","monitor"),N("Microsoft Entra ID","Project access","security"))),A("Agent with governed actions","An agent reasons over approved knowledge and invokes bounded tools; human approval and audit remain outside the model response.","Microsoft Foundry agent architecture",L("Requester",N("User","Intent","user")),L("Agent runtime",N("Foundry Agent Service","Orchestration","ai"),N("Model deployment","Reasoning","ai")),L("Tools",N("Azure Functions","Deterministic action","compute"),N("Enterprise APIs","Business systems","app")),L("Controls",N("Content Safety","Input/output checks","security"),N("Entra ID","Identity and RBAC","security")),L("Evidence",N("Foundry evaluations","Quality signal","monitor"),N("Azure Monitor","Operational telemetry","monitor")))],
 security:["Use project-level RBAC and managed identities for connected resources; do not treat a Foundry project role as permission to every data source.","Apply Content Safety, prompt shields, groundedness evaluation and output validation according to the risk of the application.","Keep prompts, traces, uploaded files and evaluation data within the intended region and retention boundary; scrub regulated data before logging."],
 optimization:["Use evaluations and tracing to identify retrieval, prompt, model or tool-call bottlenecks before changing the model.","Separate interactive agent paths from batch evaluation and indexing workloads so experimentation does not compete with production traffic.","Select model deployments by quality, latency, context window and quota behavior; a larger model is not automatically the best fit."],
 watch:["Foundry is the lifecycle and workspace layer; it does not make Azure AI Search, storage, functions or APIs implicitly private.","Agent tool calls are application actions: enforce authorization and idempotency in the tool, not only in the prompt.","Evaluation scores describe the test set; they do not prove safe behavior for unseen prompts or adversarial inputs."],
 cost:["Budget for model tokens, agent/tool calls, evaluations, indexing and the Azure resources connected to the project.","Tracing, stored datasets and repeated evaluation runs can become material cost drivers during development.","Compare the complete request path, including retrieval, content filtering, functions and storage, rather than only model price."],
 choices:[{name:"Microsoft Foundry",when:"Shared lifecycle for models, agents, evaluation and governed AI application delivery."},{name:"Azure OpenAI",when:"Direct managed model API access with application-owned orchestration."},{name:"Azure Machine Learning",when:"Custom ML training, registry, endpoints and deeper model operations are primary."}],
 hook:["Foundry is the AI lifecycle workspace; the model, data, tool and monitoring planes remain separate.","Exam clue: choose Foundry when the question emphasizes governed build, evaluation, agents and project collaboration."]},
"Azure AI Bot Service":{
 summary:"A bot-development and channel-integration service for conversational applications, commonly paired with Azure Bot resources and language/model back ends.",
 concepts:["The bot endpoint handles conversation turns while channels, authentication, state and the conversational engine are separate concerns.","Bot Framework activities carry messages and events; conversation state must be persisted if a bot must resume context across turns or instances.","Channel adapters and webhooks create external trust boundaries, so channel configuration is part of the security design."],
 fit:["Use it when one conversational application must reach multiple channels such as web chat, Teams or other supported connectors.","Keep business transactions in APIs or functions and let the bot manage turn handling, dialog state and channel adaptation.","For a search-only assistant, combine the bot with Azure AI Search; for rich generative orchestration, place the bot in front of Foundry or Azure OpenAI."],
 architectures:[A("Multi-channel support bot","One bot endpoint handles activities from different channels and calls a protected business API for answers or actions.","Azure Bot Service channel architecture",L("Channels",N("Web Chat","Customer messages","user"),N("Teams","Workforce messages","user")),L("Bot ingress",N("Azure Bot","Channel routing","ai")),L("Conversation",N("Bot endpoint","Activities and dialogs","app"),N("Conversation state","Resume context","data")),L("Business layer",N("Azure Functions","Validated actions","compute"),N("Azure AI Search","Knowledge answers","data")),L("Operations",N("Application Insights","Turn telemetry","monitor"),N("Entra ID","User identity","security"))),A("Authenticated employee assistant","The bot authenticates employees, retrieves governed knowledge and sends only approved actions to enterprise systems.","Azure Bot Service authentication pattern",L("Employee",N("Teams / web","Signed-in user","user")),L("Identity",N("Microsoft Entra ID","OAuth / claims","security")),L("Bot",N("Azure Bot","Conversation turn","ai")),L("Knowledge",N("Azure AI Search","Access-filtered content","data"),N("Microsoft Foundry","Grounded response","ai")),L("Action",N("API Management","Policy boundary","security"),N("Enterprise API","Business operation","app")))],
 security:["Validate channel tokens, OAuth claims and user identity before exposing personal or tenant data.","Keep bot credentials, channel secrets and downstream API tokens in Key Vault or managed identity paths; never embed them in dialog code.","Apply content filtering and redact conversation transcripts when messages can contain personal, financial or health information."],
 optimization:["Keep turn handlers short and move long work to asynchronous functions or queues so channel timeouts do not become duplicate actions.","Persist only the state needed to resume a conversation; avoid storing full transcripts in hot session state.","Use channel-specific cards and adaptive responses without duplicating core business logic in every adapter."],
 watch:["A bot channel is not the same as an authenticated application session; verify identity again at sensitive business APIs.","Conversation state can be lost or duplicated during scale-out unless storage and concurrency behavior are designed.","Generative answers do not replace deterministic dialog validation for payments, bookings or account changes."],
 cost:["Account for bot/channel usage, model or search calls, state storage, functions and telemetry.","Long conversational history increases token or storage consumption; summarize context intentionally.","Load tests should include channel concurrency and downstream calls, not only message count."],
 choices:[{name:"Azure AI Bot Service",when:"Multi-channel conversational endpoint and channel adaptation."},{name:"Microsoft Foundry",when:"Agent lifecycle, evaluation and tool orchestration dominate."},{name:"Azure Communication Services",when:"The primary requirement is programmable voice, SMS or chat transport."}],
 hook:["Bot Service is the conversation and channel boundary; it is not the knowledge store or business system.","Exam clue: multi-channel bot plus dialog/channel integration points to Azure AI Bot Service."]},
"Azure AI Search":{
 summary:"A managed search platform for full-text, vector and hybrid retrieval over indexed content, with enrichment and semantic ranking options.",
 concepts:["An index stores searchable fields and vectors; indexers can pull and enrich supported data sources, while push APIs support application-controlled ingestion.","Hybrid retrieval combines keyword and vector signals, and semantic ranking can rerank results; these are retrieval stages, not interchangeable storage features.","Security trimming, partitions/replicas, analyzers and index schema determine result quality and scale."],
 fit:["Use it for enterprise search, retrieval-augmented generation and applications that need filtered, ranked access to documents or structured records.","Use vector fields for semantic similarity and keep filters for tenant, ACL, geography or document state so retrieval does not leak data.","Choose a database query when the application needs transactional predicates and updates rather than relevance-ranked discovery."],
 architectures:[A("RAG over governed documents","Documents are chunked and indexed with vectors and ACL metadata; the application retrieves filtered passages before calling a model.","Azure AI Search RAG architecture",L("Users",N("Employee","Question","user")),L("Application",N("RAG API","Auth, rewrite, filters","app")),L("Retrieval",N("Azure AI Search","Hybrid/vector query","data")),L("Grounding",N("Azure OpenAI","Answer from passages","ai"),N("Content Safety","Prompt/output checks","security")),L("Sources",N("Blob Storage","Documents","storage"),N("Document Intelligence","Extract text","ai"))),A("Multi-tenant search","A shared service can support tenants when every document and query carries enforceable tenant/ACL filters.","Azure AI Search security trimming pattern",L("Tenant user",N("Application","Tenant context","user")),L("Query policy",N("API layer","Authorize and build filter","security")),L("Search index",N("Azure AI Search","Partitioned logical corpus","data")),L("Results",N("Semantic ranker","Relevance rerank","ai"),N("ACL metadata","Filter before return","security")),L("Operations",N("Azure Monitor","Query latency","monitor"),N("Indexers","Incremental refresh","data")))],
 security:["Enforce document-level security trimming in the query path; hiding a result in the UI is not an access control.","Protect admin keys and prefer Entra-based authentication or managed identities where supported; separate query and administration permissions.","Treat vector embeddings and indexed text as sensitive copies with their own retention, encryption and deletion lifecycle."],
 optimization:["Use replicas for query throughput and partitions for index size/ingestion scale; increasing both changes cost and topology differently.","Tune chunk size, searchable fields, vector dimensions, filters and semantic configuration against a representative relevance set.","Avoid reindexing unchanged content; use change detection, incremental indexers or push updates with deterministic document keys."],
 watch:["The index is a derived copy: source deletion, ACL change and schema migration need explicit propagation.","Vector similarity alone can return semantically close but unauthorized or factually weak passages; filter and evaluate before generation.","Replica availability does not repair a bad index schema or stale enrichment pipeline."],
 cost:["Service tier, partitions, replicas, semantic ranking, storage and enrichment/model calls all influence the bill.","Embedding generation and document extraction may cost more than the search query; include ingestion in lifecycle estimates.","Right-size query and indexing capacity independently when batch ingestion and interactive search have different peaks."],
 choices:[{name:"Azure AI Search",when:"Relevance-ranked full-text, vector or hybrid retrieval with filters and indexing."},{name:"Azure Cosmos DB",when:"Operational JSON access patterns and globally distributed transactional state are primary."},{name:"Azure Data Explorer",when:"Time-series/log analytics and exploratory telemetry queries dominate."}],
 hook:["AI Search retrieves; it does not become the system of record for source documents or permissions.","Exam clue: hybrid/vector retrieval plus semantic ranking and indexers points to Azure AI Search."]},
"Azure Databricks":{
 summary:"A managed analytics and data/AI platform built around collaborative workspaces, Spark processing, Delta Lake and governed data products.",
 concepts:["Workspaces provide notebooks, jobs and collaboration, while clusters or serverless compute execute data and ML workloads.","Delta Lake adds transactional tables, schema enforcement and time-travel semantics over cloud object storage; it is a storage/table layer, not just a notebook feature.","Unity Catalog governs data, models and lineage across workspaces when the deployment is configured for centralized governance."],
 fit:["Use it for large-scale transformation, streaming, feature engineering and collaborative data science where Spark and lakehouse patterns fit.","Keep raw and curated data in storage with explicit table ownership, and use jobs/workflows for repeatable production pipelines.","Choose Azure Synapse when the dominant need is integrated SQL warehousing; choose Azure Machine Learning for model lifecycle without Spark-centric engineering."],
 architectures:[A("Governed lakehouse pipeline","Streaming and batch data land in Delta tables, are transformed by jobs and exposed to analytics or ML consumers.","Azure Databricks lakehouse architecture",L("Sources",N("Event Hubs","Streaming events","app"),N("Data Factory","Batch ingestion","data")),L("Lake",N("ADLS Gen2","Bronze / silver / gold","storage")),L("Processing",N("Databricks jobs","Spark transforms","compute"),N("Delta Lake","ACID tables","data")),L("Governance",N("Unity Catalog","Permissions and lineage","security")),L("Consumers",N("Power BI","Dashboards","user"),N("Azure Machine Learning","Features / models","ai"))),A("Real-time feature pipeline","Streaming stateful transformations create fresh features for a model endpoint while preserving replayable source data.","Azure Databricks streaming and ML pattern",L("Events",N("IoT / Event Hubs","Telemetry","app")),L("Stream compute",N("Structured Streaming","Windows and state","compute")),L("Feature data",N("Delta tables","Versioned features","data")),L("Serving",N("Model endpoint","Online inference","ai"),N("Feature store","Consistent features","data")),L("Monitoring",N("Azure Monitor","Job and endpoint health","monitor"),N("Unity Catalog","Lineage","security")))],
 security:["Use Unity Catalog permissions, storage credentials and managed identities so notebook users do not receive broad storage keys.","Separate interactive clusters from production jobs and restrict cluster policies, libraries, init scripts and outbound network access.","Protect secrets and redact notebook outputs/logs; data copied into DBFS, caches or checkpoints needs a retention plan."],
 optimization:["Use Delta partitioning, file compaction and optimized layouts based on actual predicates rather than partitioning every column.","Choose job clusters or serverless compute for repeatable work; terminate idle interactive clusters and control autoscaling bounds.","Tune streaming trigger, state store and checkpoint placement; replayability is more important than hiding late-data behavior."],
 watch:["Delta tables depend on object storage and transaction logs; storage lifecycle or manual file deletion can corrupt table assumptions.","Notebook success does not guarantee production reproducibility—pin runtimes, libraries, schemas and job parameters.","Cluster autoscaling manages compute capacity; it does not solve skew, small files or inefficient joins."],
 cost:["DBUs, VM/serverless compute, storage, transactions, networking and downstream services contribute to total cost.","Interactive exploration can dominate spend when clusters remain warm; schedule shutdown and use workload-specific policies.","Measure cost per pipeline run or feature set, not only cluster hourly price."],
 choices:[{name:"Azure Databricks",when:"Spark/lakehouse engineering, streaming and collaborative data/AI workloads."},{name:"Azure Synapse Analytics",when:"Integrated SQL warehouse and analytics workspace is the center of gravity."},{name:"Azure Machine Learning",when:"Experiment, registry, endpoint and model governance are primary."}],
 hook:["Databricks combines workspace, Spark compute and Delta/Unity Catalog governance around a lakehouse.","Exam clue: Spark + Delta Lake + collaborative notebooks and jobs points to Azure Databricks."]},
"Azure Machine Learning":{
 summary:"A managed ML platform for data preparation, experiments, training, registries, endpoints, pipelines and model monitoring.",
 concepts:["Workspaces organize jobs, assets, compute and registries; data, environments, models and components should be versioned rather than hidden in notebooks.","Managed online endpoints serve low-latency requests, while batch endpoints process large inputs asynchronously; they have different scaling and operational models.","Pipelines and components turn experimentation into repeatable training or scoring graphs with explicit inputs, outputs and environments."],
 fit:["Use it when a team needs governed custom model development and deployment rather than only calling a hosted foundation model.","Use managed endpoints for controlled inference and registries for promotion; keep application authentication and input validation at the API boundary.","Choose Microsoft Foundry or Azure OpenAI for managed generative model application delivery when custom training is not required."],
 architectures:[A("MLOps training-to-endpoint path","Versioned data and environments feed a pipeline, a registered model is promoted, and an online endpoint serves applications.","Azure Machine Learning MLOps architecture",L("Data",N("ADLS Gen2","Training data","storage"),N("Azure Data Explorer","Features / telemetry","data")),L("Workspace",N("Azure ML","Jobs, assets, experiments","ai")),L("Training",N("Compute cluster","Distributed training","compute"),N("Pipeline","Repeatable graph","ai")),L("Promotion",N("Model registry","Version and approval","security"),N("Responsible AI","Evaluate and document","security")),L("Serving",N("Managed online endpoint","Low-latency inference","ai"),N("Azure Monitor","Drift and latency","monitor"))),A("Batch scoring at scale","A batch endpoint reads partitioned files, scores them asynchronously and writes versioned outputs for downstream consumption.","Azure Machine Learning batch endpoint pattern",L("Input",N("Blob / ADLS","Scoring files","storage")),L("Endpoint",N("Batch endpoint","Async job submission","ai")),L("Compute",N("Managed compute","Parallel scoring","compute")),L("Output",N("ADLS Gen2","Predictions","storage"),N("Data Factory","Pipeline handoff","data")),L("Control",N("Entra ID","Endpoint authorization","security"),N("Azure Monitor","Run status","monitor")))],
 security:["Use workspace RBAC, managed identities, private networking and scoped storage access; avoid embedding datastore keys in jobs.","Treat models, training data, environments and registered components as supply-chain artifacts and scan or approve them before promotion.","Enable responsible AI assessment, endpoint authentication, input validation and output monitoring for high-impact models."],
 optimization:["Choose compute clusters, serverless jobs or managed endpoints according to lifecycle; do not keep training compute alive between jobs.","Use pipeline caching, incremental data preparation and early stopping where they preserve reproducibility and reduce repeated work.","Separate online endpoint scaling from batch scoring capacity; optimize model format and concurrency against measured latency."],
 watch:["A model registered in a workspace is not automatically production-approved or safe for every population.","Online endpoint autoscaling responds to request load; it does not fix slow feature retrieval or oversized model packages.","Training reproducibility depends on data snapshot, code, environment, seed and dependency versions."],
 cost:["Compute duration, endpoint instance-hours, managed storage, registry artifacts, data movement and monitoring drive cost.","Idle compute and over-provisioned online instances are common avoidable drivers; batch inference may be cheaper for non-interactive workloads.","Include feature generation and data preparation when comparing custom ML with a managed model API."],
 choices:[{name:"Azure Machine Learning",when:"Custom training, MLOps, model registry, endpoints and monitoring."},{name:"Microsoft Foundry",when:"Generative AI application lifecycle and agent evaluation are primary."},{name:"Azure AI Search",when:"The problem is retrieval and ranking, not model training or serving."}],
 hook:["Azure ML owns the custom-model lifecycle from data and experiment through registry and endpoint.","Exam clue: pipelines, managed compute, model registry and online/batch endpoints point to Azure Machine Learning."]},
"Azure Open Datasets":{
 summary:"A curated catalog of public datasets that can be accessed for analytics and machine-learning experimentation without building the source ingestion first.",
 concepts:["Datasets are shared public data assets with documented scope and licensing; they are inputs to a workload, not a governed private data lake.","Access patterns may use Azure storage or SDK integrations, so network, caching and reproducibility still belong to the consuming project.","Dataset version, update cadence and geographic/time coverage affect whether an experiment can be reproduced."],
 fit:["Use it to bootstrap prototypes, benchmark models or enrich spatial/weather/health-related analysis when the dataset terms fit.","Copy and version the subset needed for production experiments; do not make a public dataset dependency invisible in the model lineage.","Use private ADLS or governed data products when the data is confidential, contractual or operationally authoritative."],
 architectures:[A("Reproducible ML experiment","A public dataset is pinned into a controlled workspace, transformed and evaluated before a model is promoted.","Azure Open Datasets ML pattern",L("Discovery",N("Open Datasets","Catalog and documentation","data"),N("Data scientist","Select subset","user")),L("Landing",N("ADLS Gen2","Pinned snapshot","storage")),L("Preparation",N("Azure Databricks","Clean and join","compute")),L("Experiment",N("Azure Machine Learning","Train and evaluate","ai")),L("Evidence",N("Dataset manifest","Version and license","file"),N("Azure Monitor","Run telemetry","monitor"))),A("Geospatial analytics prototype","A public geospatial dataset is joined with customer-owned observations while provenance and access boundaries remain separate.","Azure Open Datasets geospatial pattern",L("Public source",N("Open dataset","Weather / maps / demographics","data")),L("Private source",N("Customer data","Protected observations","security")),L("Join",N("Databricks / Synapse","Spatial transformation","compute")),L("Store",N("ADLS Gen2","Curated analytical table","storage")),L("Consumer",N("Power BI","Exploration","user"),N("Azure ML","Predictive model","ai")))],
 security:["Review license, attribution, permitted use and update provenance before using a public dataset in a product.","Keep joins with private customer data in a governed subscription and prevent the public source from becoming an unintended data export path.","Record source URL, retrieval date, version and transformations for model and audit traceability."],
 optimization:["Download only required partitions or time windows and cache stable snapshots rather than repeatedly fetching the same public data.","Precompute reusable curated tables for multiple experiments while retaining the original manifest.","Use the dataset for discovery and benchmarking; move production pipelines to a source and update process you can operate."],
 watch:["Public availability does not mean the data is complete, current, accurate or suitable for a regulated decision.","Dataset schema and update cadence may change; pin and validate before each pipeline run.","A public dataset can be combined with sensitive data in memory or output; enforce classification at the joined dataset."],
 cost:["Data transfer, storage snapshots, transformation compute and downstream ML/analytics dominate cost more than catalog discovery.","Repeated downloads and full-table transformations are avoidable; cache and partition by the workload’s access pattern.","Estimate the cost of refreshing the data when update cadence is part of the product requirement."],
 choices:[{name:"Azure Open Datasets",when:"Rapid access to curated public datasets for prototyping and benchmarking."},{name:"ADLS Gen2",when:"Owned, governed enterprise data lake storage is required."},{name:"Azure Data Share",when:"Controlled sharing of data products between organizations is the main need."}],
 hook:["Open Datasets accelerates discovery; it is not a replacement for production data governance.","Exam clue: curated public data for experimentation points to Azure Open Datasets."]},
"Foundry Tools":{
 summary:"The Foundry Tools family exposes focused Azure AI capabilities such as language, speech, vision, document and content services through managed APIs.",
 concepts:["Each tool has a distinct input/output contract, model lifecycle and quota behavior even when accessed through a common Foundry experience.","Prebuilt APIs can be composed with search, storage, functions and model orchestration; the tool response is not automatically a complete business workflow.","Regional availability, supported languages/modalities and data-processing commitments must be checked per tool."],
 fit:["Use the focused tool that matches a deterministic capability—OCR, translation, speech, vision or language analysis—before adding a generative model.","Compose tools behind an application API when a workflow needs extraction, classification and routing with predictable outputs.","Choose Foundry as the lifecycle workspace when multiple tools, models, evaluations and agents need shared governance."],
 architectures:[A("Document-to-decision pipeline","A document is extracted, analyzed and routed through deterministic APIs before a human or business system receives the result.","Azure AI Foundry Tools composition pattern",L("Input",N("Blob Storage","Uploaded file","storage"),N("Application","Submission metadata","app")),L("Extraction",N("Document Intelligence","Layout and fields","ai")),L("Analysis",N("Language","Entities / classification","ai"),N("Content Safety","Risk screening","security")),L("Workflow",N("Azure Functions","Rules and validation","compute"),N("Service Bus","Durable handoff","data")),L("Outcome",N("Business API","Approved action","app"),N("Application Insights","Trace","monitor"))),A("Multimodal assistant foundation","Speech or vision inputs are normalized by focused tools before a model or search layer uses the structured result.","Azure AI Foundry Tools multimodal pattern",L("User",N("Voice / image","Request","user")),L("Input tool",N("Speech or Vision","Transcribe / describe","ai")),L("Grounding",N("Azure AI Search","Retrieve context","data")),L("Reasoning",N("Azure OpenAI","Generate response","ai")),L("Controls",N("Entra ID","Access","security"),N("Monitor","Latency and quality","monitor")))],
 security:["Assign permissions to each underlying tool and data source; a common Foundry project does not eliminate service-specific authorization.","Use private endpoints, managed identities and Key Vault-backed secrets where the selected tool supports them.","Classify uploaded audio, images and documents before retaining request payloads or diagnostic logs."],
 optimization:["Use deterministic extraction/classification for stable fields and reserve generative calls for ambiguity or synthesis.","Batch documents or media when latency permits; interactive calls and bulk processing have different quota and cost shapes.","Measure each tool stage separately so a slow OCR, translation or model call is not hidden behind one end-to-end timer."],
 watch:["Foundry Tools is a family, not one uniform service contract; quotas, models, pricing and regional support differ by tool.","Tool outputs can be probabilistic or confidence-scored; validate critical fields before downstream actions.","A successful API response means processing completed, not that the result is accurate or authorized for a decision."],
 cost:["The chosen tool’s transaction, page, character, minute or image unit is the main driver; storage, functions, model and monitoring add to it.","Do not price a composite workflow as one API call; count every extraction, translation, search and model stage.","Use confidence thresholds and human review to reduce expensive downstream processing of low-value inputs."],
 choices:[{name:"Foundry Tools",when:"Focused managed AI APIs composed into an application workflow."},{name:"Microsoft Foundry",when:"Shared project lifecycle, evaluation and agent governance are needed."},{name:"Azure Machine Learning",when:"Custom training or model lifecycle control is the central requirement."}],
 hook:["Foundry Tools are focused capability APIs; choose the tool by modality and contract.","Exam clue: OCR, speech, language, vision or translation as a managed API points to the corresponding Foundry Tool."]},
"Azure AI Video Indexer":{
 summary:"A media intelligence service that extracts insights such as transcription, speakers, faces, topics and scenes from video and audio.",
 concepts:["Indexing produces time-aligned insights over media; the original video remains in storage and the generated metadata has its own retention and access boundary.","Video processing is asynchronous, and insight quality depends on language, audio quality, visual content and configured account settings.","Search, editing and downstream applications consume the insight metadata rather than treating the service as a general-purpose video CDN."],
 fit:["Use it to make training, broadcast, meeting or archive media searchable and to build workflows around transcripts and detected scenes.","Keep source media in Blob Storage and expose only authorized insight ranges or thumbnails to the application.","Choose Speech directly for audio-only transcription whe