"use client";

import { Activity, Cloud, Database, FileText, Globe2, HardDrive, Laptop, MessageSquare, Network, Server, Shield, Users } from "lucide-react";
import { awsIconFallbackSrc, awsIconSrc, findAwsArchitectureIcon } from "../../lib/aws-architecture-icons";
import { getAipDecisionGuide } from "./AipDecisionGuides";
import { getServiceMemoryHook } from "./ServiceMemoryHooks";
import { getServiceLearningInsights } from "./ServiceLearningInsights";
import ServiceLearningShowcase from "./ServiceLearningShowcase";
import "./AthenaLearningDetails.css";
import "./AthenaAwsIcons.css";
import "./AipServiceLearningDetails.css";
import "./AipServiceLearningDetailsV8.css";
import "./AipDecisionGuides.css";

type Kind="user"|"internet"|"app"|"data"|"security"|"file"|"network"|"storage"|"message"|"monitor"|"compute";
type Node={label:string;sub:string;kind?:Kind;icon?:string};
type Layer={title:string;nodes:Node[]};
type Arch={title:string;note:string;reference:string;layers:Layer[]};
const P=(label:string,sub:string,kind:Kind):Node=>({label,sub,kind});
const W=(label:string,sub:string,icon?:string):Node=>({label,sub,icon});
const L=(title:string,...nodes:Node[]):Layer=>({title,nodes});
const A=(title:string,note:string,reference:string,...layers:Layer[]):Arch=>({title,note,reference,layers});

function serviceArchitectures(service:string,category:string):Arch[]{
 const s=service.toLowerCase(); const c=(sub:string)=>W(service,sub);
 if(/direct connect|site-to-site vpn|client vpn|transit gateway|vpc peering|private link|vpc endpoint|ip address manager|ipam|route 53 resolver/.test(s)) return [
  A("Hybrid and multi-VPC connectivity",`${service} is placed where it actually controls or carries private connectivity, with routing and security kept explicit.`,"AWS hybrid and multi-VPC networking reference patterns",L("Enterprise / users",P("On-premises network","Corporate routes","network"),P("Remote users","Private access","user")),L("Connectivity edge",c("Private connectivity / routing role")),L("AWS network",W("Amazon VPC","Workload VPCs"),P("Route tables","Path selection","network")),L("Workloads",W("Amazon EC2","Applications"),W("Amazon RDS","Private data")),L("Operations",W("Amazon CloudWatch","Health / metrics"),W("AWS CloudTrail","API audit"))),
  A("Resilient routed topology",`Use ${service} with explicit route domains, redundant paths and failure handling instead of treating networking as a single hop.`,"AWS resilient network architecture guidance",L("Region / site A",P("Primary path","Production traffic","network")),L("Network control",c("Routing / attachment policy")),L("Region / site B",P("Alternate path","Failover traffic","network")),L("Security",P("Security groups / NACLs","Traffic controls","security"),W("AWS Network Firewall","Inspection")),L("Observability",P("Flow logs","Traffic evidence","monitor"),W("Amazon CloudWatch","Alarms")))];
 if(/guardduty|inspector|security hub|detective|audit manager|artifact|firewall manager|network firewall|shield|certificate manager|cloudhsm/.test(s)) return [
  A("Detect, protect and respond",`${service} participates in a layered security design with workload signals, findings/evidence and a response path.`,"AWS security reference architecture",L("Workloads",W("Amazon EC2","Compute"),W("Amazon S3","Data"),W("Amazon VPC","Network")),L("Security capability",c("Primary control / analysis")),L("Findings / evidence",P("Security finding","Prioritized signal","security"),W("AWS CloudTrail","Audit trail")),L("Response",W("Amazon EventBridge","Route finding"),W("AWS Lambda","Automate response"),P("Security team","Investigate","user"))),
  A("Central multi-account security",`${service} is operated centrally while workload accounts retain their own resources and telemetry.`,"AWS Security Reference Architecture multi-account pattern",L("Workload accounts",P("Account A","Resources + telemetry","app"),P("Account B","Resources + telemetry","app")),L("Central security",c("Organization-wide capability")),L("Archive",W("Amazon S3","Security evidence"),W("AWS KMS","Encryption")),L("Operations",P("SOC / security account","Triage + remediation","user"),W("Amazon CloudWatch","Operational visibility")))];
 if(/config|control tower|organizations|trusted advisor|compute optimizer|health dashboard|service quotas|license manager|proton|managed service for prometheus/.test(s)) return [
  A("Central governance and operations",`${service} works across accounts/resources as a control-plane capability, not in the application data path.`,"AWS multi-account governance and operations pattern",L("AWS estate",P("Accounts / resources","Managed environment","app")),L("Inventory / telemetry",W("AWS CloudTrail","Audit"),W("Amazon CloudWatch","Metrics / logs")),L("Governance service",c("Assess / organize / control")),L("Action",W("Amazon EventBridge","Route signal"),W("AWS Systems Manager","Automation")),L("Operators",P("Platform team","Govern + remediate","user"))),
  A("Policy-to-remediation loop",`A useful ${service} deployment connects evaluation to ownership and remediation instead of stopping at a dashboard.`,"AWS operational excellence automation pattern",L("Policy / target",P("Standards","Desired state","file")),L("Evaluation",c("Analyze current state")),L("Exception",P("Finding / drift","Action required","monitor")),L("Remediation",W("AWS Lambda","Automate"),P("Human approval","Controlled change","user")),L("Evidence",W("Amazon S3","Reports / history"),W("AWS CloudTrail","Change audit")))];
 if(/dms|migration|snow|schema conversion|datasync|transfer family/.test(s)) return [
  A("Migration with validation and cutover",`${service} is part of a complete source → connectivity → migration → validation → target design.`,"AWS migration reference architecture",L("Source",P("On-prem / legacy system","Files / database / workload","data")),L("Connectivity",P("VPN / Direct Connect / internet","Transfer path","network")),L("Migration service",c("Move / replicate / convert")),L("AWS target",W("Amazon S3","Landing / backup"),W("Amazon RDS","Managed database"),W("Amazon EC2","Application target")),L("Cutover",P("Validation + reconciliation","Quality gate","monitor"),P("Application switch","Production move","app"))),
  A("Incremental migration",`Use ${service} to reduce downtime by separating initial bulk movement from ongoing changes and final cutover.`,"AWS migration incremental replication pattern",L("Initial source",P("Existing platform","Current production","app")),L("Bulk load",c("Initial transfer")),L("Change sync",P("Incremental / CDC","Keep target current","message")),L("Target validation",P("Checksums / test traffic","Verify","monitor")),L("Go-live",P("DNS / application cutover","Switch consumers","network")))];
 if(/redshift|athena|emr|glue|firehose|kinesis|flink|lake formation|data exchange|quicksight|quick sight|opensearch/.test(s)) return [
  A("Governed analytics pipeline",`${service} is placed in a realistic ingestion, storage/catalog, processing and consumption path.`,"AWS modern data analytics architecture",L("Sources",P("Applications / partners","Events + datasets","data")),L("Ingest",W("Amazon Kinesis","Streaming"),W("Amazon S3","Batch landing")),L("Analytics capability",c("Service-specific analytics role")),L("Govern / catalog",W("AWS Glue","Catalog / ETL"),P("Lake permissions","Governance","security")),L("Consume",P("BI / SQL / ML users","Insights","user"),W("Amazon QuickSight","Dashboards"))),
  A("Operational analytics",`Use ${service} with purpose-built storage and query patterns rather than forcing every analytics workload through the same engine.`,"AWS analytics workload selection pattern",L("Operational data",P("Logs / events / records","Continuous input","data")),L("Processing",c("Transform / query / search")),L("Durable data",W("Amazon S3","Historical data"),P("Index / warehouse","Optimized serving","storage")),L("Consumers",P("Analyst","Explore","user"),P("Application","Operational insight","app")),L("Observe",W("Amazon CloudWatch","Pipeline health"),P("Data quality","Freshness / failures","monitor")))];
 if(/mq|mwaa|eventbridge|sns|sqs|step functions|appflow|appsync|ses/.test(s)) return [
  A("Decoupled application integration",`${service} is used according to its real role—broker, workflow, event routing, notification or API integration—with failure boundaries kept explicit.`,"AWS application integration reference patterns",L("Producers",P("Applications / SaaS","Events / requests","app")),L("Integration",c("Routing / orchestration / messaging")),L("Buffer / workflow",W("Amazon SQS","Durable backlog"),W("AWS Step Functions","Workflow state")),L("Consumers",W("AWS Lambda","Processing"),P("External system","Partner / SaaS","internet")),L("Operations",W("Amazon CloudWatch","Metrics / alarms"),P("DLQ / retry","Failure handling","monitor"))),
  A("Event-driven business workflow",`${service} coordinates independent business capabilities without coupling producer availability to every consumer.`,"AWS event-driven architecture pattern",L("Business event",P("Order / file / user action","Domain change","message")),L("Integration service",c("Service-specific coordination")),L("Parallel outcomes",P("Billing","Consumer A","app"),P("Notification","Consumer B","app"),P("Analytics","Consumer C","data")),L("Audit",W("AWS CloudTrail","API activity"),W("Amazon S3","Durable evidence")))];
 if(/batch|elastic beanstalk|lightsail|ec2 auto scaling|serverless application repository|ec2 image builder/.test(s)) return [
  A("Highly available compute platform",`${service} is surrounded by ingress, scaling, state and observability appropriate to production compute.`,"AWS highly available compute architecture",L("Users",P("Web / API clients","Requests","user")),L("Ingress",W("Amazon Route 53","DNS"),W("Elastic Load Balancing","Traffic distribution")),L("Compute",c("Runtime / fleet capability")),L("State",W("Amazon RDS","Relational data"),W("Amazon S3","Objects")),L("Operations",W("Amazon CloudWatch","Metrics / logs"),W("AWS Systems Manager","Fleet operations"))),
  A("Asynchronous compute",`Use ${service} for work that can be queued, scheduled or scaled independently from the request path.`,"AWS asynchronous processing architecture",L("Jobs",P("API / scheduler","Submit work","app")),L("Queue",W("Amazon SQS","Back-pressure")),L("Compute",c("Workers / jobs")),L("Results",W("Amazon S3","Artifacts"),W("Amazon DynamoDB","Job state")),L("Notify",W("Amazon SNS","Completion"),P("User / system","Consume result","user")))];
 if(/ecs anywhere|eks anywhere|eks distro|ecr|ecs|eks|fargate/.test(s)) return [
  A("Container delivery and runtime",`${service} sits in a supply-chain and runtime architecture with registry, orchestration, compute, networking and state separated.`,"AWS container reference architecture",L("Source",P("Git repository","Application code","file")),L("Build / registry",W("AWS CodeBuild","Build + scan"),W("Amazon ECR","Images")),L("Container platform",c("Orchestrate / run containers")),L("Ingress + data",W("Elastic Load Balancing","Traffic"),W("Amazon RDS","State")),L("Operations",W("Amazon CloudWatch","Logs / metrics"),P("IAM role","Workload identity","security"))),
  A("Hybrid container platform",`${service} can participate in hybrid/on-prem placement while image, identity and operations remain centrally governed.`,"AWS hybrid containers pattern",L("Central AWS",W("Amazon ECR","Images"),P("IAM / control plane","Governance","security")),L("Connectivity",P("Private WAN / internet","Control + image pull","network")),L("Runtime location",c("AWS / edge / on-prem runtime")),L("Applications",P("Container workloads","Services / jobs","compute")),L("Telemetry",W("Amazon CloudWatch","Observability")))];
 if(/dynamodb accelerator|dax|rds proxy|keyspaces|timestream|memorydb|aurora serverless|database/.test(s)) return [
  A("Production application data tier",`${service} is used with stateless application compute, credentials, private networking and recovery controls.`,"AWS managed database application architecture",L("Users",P("Clients","Requests","user")),L("Application",W("Amazon ECS","Service"),W("AWS Secrets Manager","Credentials")),L("Data capability",c("Primary data role")),L("Resilience",P("Replica / cache / backup","Availability + recovery","storage")),L("Operations",W("Amazon CloudWatch","Performance / alarms"),W("AWS KMS","Encryption"))),
  A("Scale the correct data path",`Use ${service} where its access pattern—cache, proxy, time-series, wide-column or serverless SQL—matches the bottleneck.`,"AWS database purpose-built selection guidance",L("Application",P("Read / write workload","Access pattern","app")),L("Data access layer",c("Service-specific access model")),L("System of record",W("Amazon RDS","Relational state"),W("Amazon DynamoDB","Key-value state")),L("Downstream",P("Analytics / events","Secondary use","data")),L("Observe",W("Amazon CloudWatch","Latency / capacity")))];
 if(/backup|fsx|storage gateway|glacier|elastic disaster recovery/.test(s)) return [
  A("Protected storage and recovery",`${service} is used with workload storage, encryption, policy and a tested recovery path.`,"AWS storage and backup reference pattern",L("Workloads",W("Amazon EC2","Compute"),P("On-prem applications","Hybrid source","app")),L("Primary storage",W("Amazon EBS","Block"),W("Amazon EFS","File"),W("Amazon S3","Object")),L("Protection service",c("Backup / file / recovery role")),L("Recovery",P("Restore target","Alternate copy / site","storage"),P("Recovery test","RTO / RPO validation","monitor")),L("Govern",W("AWS KMS","Encryption"),W("AWS CloudTrail","Audit"))),
  A("Lifecycle and hybrid access",`Use ${service} when storage placement, protocol, retention or recovery requirements differ from ordinary hot object storage.`,"AWS storage lifecycle and hybrid architecture",L("Applications",P("Files / volumes / archives","Data","data")),L("Access layer",c("Protocol / lifecycle capability")),L("AWS storage",W("Amazon S3","Durable object store"),P("Archive / backup tier","Lower-cost retention","storage")),L("Consumers",P("Restore / analytics / applications","Use data","app")),L("Operations",W("Amazon CloudWatch","Capacity / health")))];
 if(/iot/.test(s)) return [
  A("Secure IoT ingestion",`${service} is used with device identity, messaging, rules and downstream analytics rather than as an isolated device endpoint.`,"AWS IoT reference architecture",L("Devices",P("Sensors / gateways","Telemetry","internet")),L("Identity",P("Device certificate","Mutual authentication","security")),L("IoT service",c("Connect / manage / analyze devices")),L("Rules + streaming",P("Rules engine","Route messages","message"),W("Amazon Kinesis","Stream")),L("Data / apps",W("Amazon S3","History"),W("AWS Lambda","Automation"))),
  A("Edge-to-cloud IoT operations",`Keep local processing, cloud control and fleet observability distinct when using ${service}.`,"AWS IoT edge-to-cloud pattern",L("Edge",P("Industrial / remote site","Local devices","compute")),L("Local gateway",P("Edge runtime","Filter / buffer","compute")),L("Cloud IoT",c("Fleet capability")),L("Operations",W("Amazon CloudWatch","Telemetry"),P("Fleet operator","Monitor / update","user")),L("Business systems",P("Analytics / application","Consume events","app")))];
 return [
  A("Production workload integration",`${service} is placed inside a complete workload with identity, application, data and operations boundaries.`,"AWS Well-Architected service integration pattern",L("Users / systems",P("Client / producer","Request / event","user")),L("Identity / ingress",P("IAM / authentication","Authorized access","security")),L("Service capability",c("Managed AWS capability")),L("State / result",W("Amazon S3","Durable data"),W("Amazon DynamoDB","Application state")),L("Operate",W("Amazon CloudWatch","Metrics / logs"),W("AWS CloudTrail","Audit"))),
  A("Automated operational pattern",`${service} is integrated with events, automation and monitoring so failures and changes are observable and recoverable.`,"AWS operational excellence pattern",L("Trigger",P("User / event / schedule","Start work","message")),L("Service",c("Primary capability")),L("Automation",W("AWS Lambda","Glue logic"),W("Amazon EventBridge","Event routing")),L("Evidence",W("Amazon S3","Outputs / history"),P("Alert / finding","Operational signal","monitor")),L("Owner",P("Operator","Review / respond","user")))];
}

function PublicIcon({kind}:{kind:Kind}){const C=kind==="user"?Users:kind==="internet"?Globe2:kind==="data"?Database:kind==="security"?Shield:kind==="file"?FileText:kind==="network"?Network:kind==="storage"?HardDrive:kind==="message"?MessageSquare:kind==="monitor"?Activity:kind==="compute"?Server:Laptop;return <div className={`public-icon-disc public-${kind}`}><C size={32}/></div>}
function NodeView({node}:{node:Node}){if(node.kind)return <div className="v8-node public"><PublicIcon kind={node.kind}/><strong>{node.label}</strong><small>{node.sub}</small></div>;const icon=findAwsArchitectureIcon(node.icon||node.label);return <div className="v8-node aws">{icon?<div className="aws-icon-disc"><img src={awsIconSrc(icon)} data-fallback={awsIconFallbackSrc(icon)} onError={e=>{const el=e.currentTarget;const f=el.dataset.fallback;if(f&&el.src!==f){el.src=f;return}el.style.display="none"}} alt={`${node.label} AWS architecture icon`}/></div>:<div className="public-icon-disc public-internet aws-safe-fallback"><Cloud size={32}/></div>}<strong>{node.label}</strong><small>{node.sub}</small></div>}
function Architecture({arch,index}:{arch:Arch;index:number}){return <section className="v8-architecture"><div className="section-cap"><div><p>ARCHITECTURE {String(index).padStart(2,"0")}</p><h3>{arch.title}</h3></div><span>{arch.note}</span></div><div className="v8-reference">Reference pattern: {arch.reference}</div><div className="v8-layers">{arch.layers.map((layer,i)=><div className="v8-layer-wrap" key={i}><div className="v8-layer"><b className="v8-layer-title">{layer.title}</b><div className="v8-layer-nodes">{layer.nodes.map((n,j)=><NodeView key={j} node={n}/>)}</div></div>{i<arch.layers.length-1&&<div className="v8-connector">→</div>}</div>)}</div></section>}
function Cards({title,items,id}:{title:string;items:string[];id?:string}){return <section className="knowledge-card" id={id}><div className="knowledge-card-title"><span>◆</span><h3>{title}</h3></div><div className="knowledge-card-body"><div className="concept-stack">{items.map((x,i)=><p key={i}><b>{String(i+1).padStart(2,"0")}</b>{x}</p>)}</div></div></section>}

function serviceContent(service:string,category:string,summary?:string,decision?:{choices?:Array<{name:string;when:string}>},arches?:Arch[]){
 const s=service.toLowerCase();
 const primary=decision?.choices?.[0]; const alternative=decision?.choices?.[1]; const arch=arches?.[0]; const secondArch=arches?.[1];
 if(primary&&arch) return {concepts:[`${service} is primarily used for ${primary.when.toLowerCase()}`,`${service} is distinct from ${alternative?.name||"neighboring services"}: ${alternative?.when||"the adjacent service owns a different responsibility."}`,`Architecture boundary: ${arch.title}. ${arch.note}`],fit:[`Primary fit — ${primary.when}`,`Alternative boundary — ${secondArch?.title||alternative?.name||"A neighboring service"}: ${secondArch?.note||alternative?.when||"Use it when the workload requires a different operating model."}`,`Implementation clue — place ${service} where its own control, data and scaling responsibility is visible; keep surrounding services focused on their separate roles.`]};
 if(s.includes("sns")) return {concepts:["SNS is push-based pub/sub: publishers send to a topic and SNS delivers to independent subscribers.","Subscriptions can target SQS, Lambda, HTTP/S and other endpoints, each with its own delivery behavior.","SNS provides fan-out notification; it is not a durable worker queue or replayable event stream."],fit:["Use SNS when one event must reach multiple consumers quickly.","Pair SNS with separate SQS queues when consumers need buffering, retries and failure isolation.","Choose EventBridge for content-based routing across AWS, SaaS and custom event producers."]};
 if(s.includes("sqs")) return {concepts:["SQS is a durable pull-based queue that decouples producers from workers and absorbs bursts.","Standard queues maximize throughput; FIFO queues add ordering and deduplication within message groups.","Visibility timeout, retries and dead-letter queues define the processing contract."],fit:["Use SQS for asynchronous work, back-pressure and independent worker scaling.","Use separate queues when consumers need different retry, throughput or failure boundaries.","Choose SNS for push fan-out and Kinesis for ordered replayable streams."]};
 if(/eventbridge/.test(s)) return {concepts:["EventBridge routes events by content from AWS services, custom applications and SaaS partners.","Event buses, rules, event patterns, targets, archives and replay form the routing and recovery model.","EventBridge decouples producers from consumers; it is not a durable work queue or a stateful workflow engine."],fit:["Use EventBridge for loosely coupled event routing, schedules and cross-account or SaaS integrations.","Use rules to keep consumers independent and route only the events each target needs.","Choose SQS for durable worker backlogs and Step Functions for stateful orchestration."]};
 if(/step functions/.test(s)) return {concepts:["Step Functions provides durable workflow state, branching, retries, waits, callbacks and service integrations.","Standard and Express workflows have different duration, execution-history and throughput characteristics.","Each step needs a clear idempotency, timeout and retry boundary."],fit:["Use Step Functions when a process spans multiple steps and needs durable orchestration.","Keep compute tasks stateless and let the state machine coordinate retries, compensation and approval.","Choose EventBridge for event routing without workflow state and Lambda for one short-lived function."]};
 if(/appsync/.test(s)) return {concepts:["AppSync provides managed GraphQL APIs with schemas, resolvers, data sources, authorization and subscriptions.","The schema is the client contract; resolvers connect fields to DynamoDB, Lambda, HTTP or other data sources.","Authorization, caching and subscriptions affect the runtime data-access model."],fit:["Use AppSync when clients need a flexible GraphQL data graph or real-time subscriptions.","Design the schema around client data needs and keep resolver access least-privileged.","Choose API Gateway for REST/HTTP contracts and EventBridge for asynchronous event distribution."]};
 if(/aurora|rds|documentdb|dynamodb|elasticache|neptune|timestream|keyspaces|memorydb/.test(s)) return {concepts:[`${service} has a specific data model, consistency behavior, access pattern and durability boundary.`,`Capacity, partitioning or connection behavior determines its scaling path; backups and replicas solve different resilience problems.`,`Identity, encryption, network reachability, credentials and observability must be designed around the data tier.`],fit:[`Use ${service} when the workload data model and access pattern match its operating model.`,`Keep the system of record, cache, analytics copy and backup target distinct.`,`Choose another database only when its query model, consistency or scaling boundary is a better fit.`]};
 if(/cloudshell|codeartifact|codebuild|codedeploy|codepipeline|x-ray|cdk|developer/.test(s)) return {concepts:[`${service} owns a specific software lifecycle responsibility: author, package, build, deploy, orchestrate or observe.`,`Artifacts, credentials, environment separation and auditability connect the tool to the workload it changes.`,`Evaluate the service by its lifecycle boundary, not by the broad developer-tools category.`],fit:[`Use ${service} at the lifecycle stage it owns and pass versioned outputs to the next stage.`,`Keep build and deployment identities least-privileged and preserve logs, approvals and rollback evidence.`,`Choose an adjacent tool only when the requirement belongs to a different lifecycle stage.`]};
 if(/ecr/.test(s)) return {concepts:["ECR is an OCI-compatible container image registry with repositories, scanning, lifecycle policies and replication.","Image immutability, provenance and access control connect the registry to the deployment pipeline.","ECR stores and distributes images; it does not schedule containers or provide runtime capacity."],fit:["Use ECR as the controlled image source for ECS, EKS and other container runtimes.","Separate build, scan, promotion and production repositories when release isolation matters.","Choose CodeArtifact for language packages and S3 for generic artifacts."]};
 if(/ecs/.test(s)) return {concepts:["ECS is AWS-native container orchestration built around task definitions, services, tasks, clusters and deployments.","ECS can run on Fargate or EC2; networking, task roles, service discovery and load balancing shape the runtime.","The scheduler maintains desired task state while application state remains in managed data services."],fit:["Use ECS for AWS-native containerized services when Kubernetes compatibility is not required.","Use Fargate to remove worker-node management or EC2 when host control is important.","Choose EKS for Kubernetes APIs and App Runner for simpler web-service hosting."]};
 if(/eks/.test(s)) return {concepts:["EKS provides a managed Kubernetes control plane while workloads use Kubernetes APIs, objects, controllers and add-ons.","Worker capacity, networking, IAM integration, ingress and observability remain architecture decisions.","The control plane is managed, but cluster configuration and workload operations remain responsibilities."],fit:["Use EKS when Kubernetes compatibility, portability or ecosystem tooling is required.","Separate cluster platform concerns from namespaces, workload identity, ingress and data services.","Choose ECS for simpler AWS-native orchestration and Fargate for serverless container capacity."]};
 if(/fargate/.test(s)) return {concepts:["Fargate provides serverless capacity for ECS tasks and selected EKS pods without managing worker instances.","Task or pod definitions still determine CPU, memory, networking, IAM identity, logs and storage integration.","Fargate removes host administration but not application, network or workload-security responsibilities."],fit:["Use Fargate for long-running or packaged containers where host management is unnecessary.","Choose capacity and networking per service, with durable state in managed storage.","Choose EC2 for host or hardware control and Lambda for short-lived functions."]};
 if(/ec2 auto scaling|auto scaling/.test(s)) return {concepts:["EC2 Auto Scaling maintains fleet capacity using launch templates, health checks, scaling policies and lifecycle hooks.","Capacity, health and demand signals determine when instances are launched, replaced or terminated.","Stateless design, load balancing and externalized state enable safe horizontal scaling."],fit:["Use EC2 Auto Scaling for resilient fleets that respond to demand or health.","Pair it with Elastic Load Balancing and CloudWatch metrics for traffic and scaling control.","Choose ECS/EKS when the unit of scale is a container workload rather than an instance fleet."]};
 if(/^aws lambda$|^lambda$/.test(s)) return {concepts:["Lambda runs short-lived event-driven functions without server management and scales through invocation concurrency.","Invocation type, timeout, concurrency, retries, idempotency and destinations define execution behavior.","Cold starts, permissions and downstream throttling affect real application performance."],fit:["Use Lambda for event processing, APIs and automation where execution is bounded and stateless.","Use queues and event sources to control bursts and downstream pressure.","Choose Fargate for longer-running containers and EC2 for host or hardware control."]};
 if(/iam|identity|cognito|sts/.test(s)) return {concepts:[`${service} defines an identity or authorization boundary: identify the caller, policy evaluation and protected resource.`,`Temporary credentials, federation, roles and least privilege reduce long-lived credential exposure.`,`Cross-account access depends on both trust and permission relationships.`],fit:[`Use ${service} for its exact identity boundary—workforce access, workload permissions, customer sign-in or temporary federation.`,`Scope permissions to actions, resources and conditions, then review effective access.`,`Use IAM for AWS permissions, Cognito for application users and STS for temporary credentials.`]};
 if(/kms|key management/.test(s)) return {concepts:["KMS controls cryptographic keys and authorization around encryption operations.","Key policies, IAM policies, grants, rotation and deletion controls determine key use and administration.","Encryption at rest is only one part of the design: protect plaintext paths, key access and audit events."],fit:["Use KMS when workloads need governed encryption keys with centralized authorization and auditability.","Choose customer-managed keys when lifecycle, cross-account use or policy control matters.","Keep secrets in Secrets Manager and certificates in ACM; KMS is cryptographic control, not a secret database."]};
 if(/network|vpc|route 53|cloudfront|private|direct connect|vpn|load balancing|api gateway|app mesh|cloud map|transit gateway|global accelerator|firewall|waf/.test(s)) return {concepts:[`${service} owns a defined network or delivery layer such as routing, DNS, private connectivity, traffic distribution, API entry, edge delivery or inspection.`,`Separate the data path from the control path: routes, listeners, endpoints, policies, health checks and identities each affect the result.`,`Availability comes from redundant paths and healthy targets; security comes from explicit network and application controls.`],fit:[`Use ${service} when the requirement matches its exact protocol and network layer.`,`Place it in the request path, identify its failure domain and define health, failover and observability behavior.`,`Choose DNS, CDN, anycast, load balancing, private access or routing according to the problem being solved.`]};
 if(/ebs|efs|s3|fsx|storage|glacier|backup/.test(s)) return {concepts:[`${service} provides a particular storage model—block, shared file, object, archive or recovery copy—with distinct access semantics.`,`Performance, durability, lifecycle, encryption and recovery are separate decisions; storage class alone is not a backup strategy.`,`The workload determines protocol, consistency, concurrency and network placement requirements.`],fit:[`Use ${service} when its storage protocol and durability boundary match the workload.`,`Keep primary data, snapshots/backups, replicas and archives distinct so recovery objectives are testable.`,`Choose EBS for block, EFS/FSx for shared files, S3 for objects and Glacier classes for archive.`]};
 return {concepts:[`${service} has a specific responsibility within the ${category.toLowerCase()} layer; define what it owns and what remains outside it.`,`Understand its request/data/control path, scaling model, identity boundary and failure behavior.`,`Use limits, integrations and operational signals to validate the design.`],fit:[`Use ${service} when the workload requirement matches its documented operating model.`,summary||`Place ${service} in its real architecture and compare it with neighboring services by responsibility.`,`Choose alternatives based on invocation, state, network placement, scaling and recovery behavior.`]};
}

export default function CrossCourseLearningDetails({serviceName,category,summary}:{serviceName:string;category:string;summary?:string}){
 const arches=serviceArchitectures(serviceName,category);const decision=getAipDecisionGuide(serviceName,category,summary);const content=serviceContent(serviceName,category,summary,decision,arches);const concepts=content.concepts;const appFit=content.fit;const useCases=arches.map(a=>`${a.title}: ${a.note}`);const memoryHook=getServiceMemoryHook(serviceName,category,decision,arches);const insights=getServiceLearningInsights(serviceName,category);
 return <div className="service-knowledge aip-shared-learning aip-v8" data-service={serviceName}><div className="knowledge-intro"><div><p className="knowledge-kicker">VISUAL DEEP DIVE • {category.toUpperCase()}</p><h2>{serviceName}</h2><p><b>What it is:</b> {summary||`An AWS capability used in ${category}.`}</p></div><div className="knowledge-facts"><span><b>01</b>Purpose</span><span><b>02</b>Architecture</span><span><b>03</b>Operations</span><span><b>04</b>Exam fit</span></div></div><nav className="knowledge-jumps"><a href="#cross-concepts">Concepts</a><a href="#cross-use-cases">Use cases</a><a href="#cross-security">Security</a><a href="#cross-cost">Cost</a><a href="#memory-hook">Exam hook</a></nav><div className="knowledge-grid aip-intro-grid" id="cross-concepts"><Cards title="Core service concepts" items={concepts}/><Cards title="Application fit" items={appFit}/></div>{arches.map((a,i)=><Architecture key={i} arch={a} index={i+1}/>)}<div className="knowledge-grid"><ServiceLearningShowcase serviceName={serviceName} architectures={arches} security={insights.security} optimization={insights.optimization} cost={insights.cost} watchPoints={insights.watchPoints} examplesId="cross-use-cases" securityId="cross-security" costId="cross-cost"/><section className="knowledge-card aip-decision-card"><div className="knowledge-card-title"><span>◆</span><h3>Service comparison</h3></div><p className="aip-decision-headline">{decision.headline}</p><div className="aip-choice-grid">{decision.choices.map((choice,i)=><div className={`aip-choice ${i===0?"current":""}`} key={`${choice.name}-${i}`}><b>{choice.name}</b><span>{choice.when}</span></div>)}</div></section><Cards id="memory-hook" title="Certification memory hook" items={memoryHook}/></div></div>;
}
