export type ServiceLearningInsights={
  security:string[];
  optimization:string[];
  cost:string[];
  watchPoints:string[];
};

type Rule={match:RegExp;security:string[];optimization:string[];cost:string[];watchPoints:string[]};

const r=(match:RegExp,security:string[],optimization:string[],cost:string[],watchPoints:string[]):Rule=>({match,security,optimization,cost,watchPoints});

const rules:Rule[]=[
  r(/appsync/i,
    ["Authorize at the GraphQL field and resolver boundary: use Cognito, IAM, OIDC or Lambda authorizers deliberately instead of treating the API as one all-or-nothing permission surface.","Protect downstream data sources independently—AppSync authorization does not replace DynamoDB, Lambda, OpenSearch or HTTP endpoint permissions.","Use CloudTrail for control-plane changes and AppSync/CloudWatch logging selectively for resolver troubleshooting; avoid logging sensitive arguments or response data."],
    ["Choose direct data-source resolvers when possible; add Lambda only when business logic truly needs code, because it adds another scaling, latency and failure boundary.","Use pipeline resolvers for multi-step GraphQL logic, caching for repeatedly requested data, and subscriptions only for workloads that benefit from server-pushed updates.","Model GraphQL schemas around client access patterns so one request does useful work without creating resolver fan-out or N+1 access patterns downstream."],
    ["The important dimensions are GraphQL/API operations, real-time connection/update usage, caching where enabled, and the downstream services each resolver invokes.","A cheap AppSync request can still trigger expensive Lambda, DynamoDB, OpenSearch or cross-Region work; include those resolver-side costs in the design.","Reduce duplicate resolver work with better schema design, batching/caching and direct integrations before trying to optimize only the AppSync request charge."],
    ["Know the resolver chain: request mapping → resolver/pipeline functions → data source → response mapping.","Subscriptions use persistent real-time connections and are architecturally different from normal query/mutation request-response traffic.","When troubleshooting, first decide whether the failure is authorization, resolver logic, mapping, data-source permissions or the downstream service itself."]
  ),
  r(/\b(sqs|simple queue)\b/i,
    ["Grant producers SendMessage and consumers Receive/Delete permissions separately; queue policies matter when publishers or consumers are cross-account or service principals.","Encrypt queues with SSE when message bodies are sensitive and restrict KMS use to the principals that actually send or consume.","Monitor DLQ depth, age of oldest message and receive/delete behavior so poison messages and stalled consumers are visible."],
    ["Tune visibility timeout to exceed normal processing time and extend it for long jobs; an undersized timeout creates duplicate in-flight work.","Use long polling and sensible batch sizes to reduce empty receives and improve consumer efficiency.","Choose FIFO only when ordering/deduplication is required; Standard queues give broader throughput and at-least-once delivery semantics."],
    ["Requests are driven by API actions and payload chunks; batching can reduce request count substantially.","Include DLQ traffic, KMS requests, Lambda/ECS consumers and inter-Region or internet transfer where applicable.","Long polling and batching usually improve both efficiency and cost because they reduce empty or overly granular receive/send calls."],
    ["A message is not complete until the consumer deletes it; visibility timeout is temporary invisibility, not acknowledgement.","Standard queues can deliver duplicates and out of order, so consumers should be idempotent.","FIFO ordering is scoped by message group; use multiple groups when ordered streams can be processed independently."]
  ),
  r(/\b(sns|simple notification)\b/i,
    ["Restrict Publish separately from subscription administration, and use topic policies for service or cross-account publishers.","Use subscription filter policies to reduce unnecessary data exposure as well as unnecessary downstream processing.","Protect sensitive payloads with encryption where appropriate and remember that each subscriber must also secure its own destination."],
    ["Use one SQS queue per durable consumer when subscriber speed or failure should be isolated.","Filter at the topic/subscription instead of making every consumer receive and discard irrelevant messages.","Prefer event buses or queues when you need replay, durable backlog or workflow state; SNS is optimized for fan-out notification."],
    ["Cost follows publishes, deliveries and delivery protocol; one publish can multiply into many billed deliveries across subscribers.","Include SQS, Lambda, HTTP egress, SMS/email or other destination charges rather than counting only topic publishes.","Filtering before delivery can lower both SNS delivery volume and downstream compute/request cost."],
    ["SNS pushes; SQS is polled. That difference is often the quickest exam clue.","Fan-out is strongest when each independent consumer gets its own queue.","A topic does not hold a backlog for an unavailable HTTP/Lambda consumer in the same way a queue does—design retry/DLQ behavior explicitly."]
  ),
  r(/eventbridge/i,
    ["Use event-bus resource policies and least-privilege target roles so producers cannot publish to unintended buses and rules cannot invoke unintended targets.","Treat event payloads as shared contracts: avoid putting secrets or unnecessary regulated data into broadly routed events.","Audit rule, bus, schema, archive and target changes; failed target delivery should be observable through retries and DLQs where supported."],
    ["Filter on the bus so targets receive only relevant events; broad catch-all rules create needless invocations and coupling.","Use archives/replay for recoverability and testing instead of building custom event retention when the pattern fits.","Use Scheduler for time-based invocation and event buses for event routing; do not force cron semantics into domain-event rules."],
    ["Primary drivers include event ingestion, custom/partner events, archive storage/replay and target-side services.","A single event routed to many targets multiplies downstream Lambda, Step Functions, API or queue cost.","Precise event patterns reduce both unnecessary target invocations and operational noise."],
    ["EventBridge routes events; it does not provide a queue-like consumer backlog.","Rules are evaluated independently, so one event can match multiple rules and trigger multiple targets.","Archive/replay is a recovery tool, not a replacement for application idempotency."]
  ),
  r(/step functions/i,
    ["The state-machine execution role should be able to call only the services/actions used by the workflow.","Keep secrets out of execution input/history; pass references to Secrets Manager or Parameter Store instead of raw credentials.","Execution history can contain business data, so choose logging level and retention with data sensitivity in mind."],
    ["Use Standard workflows for durable, auditable long-running orchestration and Express for high-volume short-duration workloads where its execution model fits.","Prefer native service integrations over Lambda wrappers when the workflow only needs to call an AWS API.","Use retries with backoff, Catch paths, timeouts, Map/Parallel concurrency controls and callback tokens deliberately rather than relying on implicit application behavior."],
    ["Standard pricing is strongly tied to state transitions; Express follows executions, duration and memory usage.","Native integrations can remove Lambda runtime cost and an extra failure hop.","High-cardinality loops can multiply transitions quickly, so Map/Distributed Map design and item count matter to both performance and cost."],
    ["Step Functions stores workflow state; SQS stores messages and EventBridge routes events—do not treat them as interchangeable.","A retry repeats a state unless you design idempotency in the invoked operation.","Callbacks let workflows wait without holding compute, which is ideal for approvals and external asynchronous work."]
  ),
  r(/\blambda\b/i,
    ["Use a narrowly scoped execution role per function or workload boundary; do not give functions broad account permissions for convenience.","Keep secrets in managed secret stores and encrypt environment variables where needed; never bake credentials into deployment packages.","Control who can invoke the function with resource policies/API authorization and monitor asynchronous failures, destinations and DLQs."],
    ["Tune memory by measuring both duration and throughput because CPU/network scale with memory allocation.","Reuse SDK clients/connections outside the handler, control concurrency to protect downstream systems, and use provisioned concurrency only for latency-sensitive paths.","For streams/queues, tune batch size, partial-batch failure and event-source concurrency instead of scaling the function in isolation."],
    ["Core dimensions are invocations and GB-seconds; architecture can also add provisioned concurrency, ephemeral storage, logs, data transfer and downstream service calls.","More memory can cost more per millisecond but finish faster, so optimize measured total cost rather than choosing the smallest memory size.","Avoid chatty architectures where many tiny functions create extra requests, logs and orchestration overhead without a clear isolation benefit."],
    ["The 15-minute maximum duration is a design boundary, not merely a quota to raise.","Concurrency is shared capacity unless reserved; a hot function can affect others without deliberate concurrency controls.","Asynchronous invocation, event-source mapping and synchronous API invocation have different retry and failure semantics."]
  ),
  r(/api gateway/i,
    ["Authenticate and authorize at the API boundary with IAM, JWT/Cognito or Lambda authorizers as appropriate; combine that with least-privilege backend permissions.","Use throttling, quotas/WAF where appropriate and request validation to reduce abusive or malformed traffic before it reaches compute.","Do not expose backend credentials to clients; integration roles and private integrations should keep backend trust on the server side."],
    ["Choose HTTP APIs when their feature set is sufficient; use REST APIs when you need capabilities that HTTP APIs do not provide.","Cache only read-heavy responses with safe cache keys; incorrect cache-key design can leak data between callers.","Prefer direct AWS service integrations when they remove unnecessary Lambda code and latency."],
    ["Requests are a primary driver, with differences across REST, HTTP and WebSocket APIs; caching, data transfer and logging can add cost.","Backend Lambda/Step Functions/service calls are separate charges and often exceed the API front-door charge in complex workloads.","Select the API type from required features first, then optimize request volume, caching and payload size."],
    ["REST API, HTTP API and WebSocket API are different products with different capabilities and pricing models.","API Gateway throttling protects the API; it does not automatically make downstream databases safe from every burst.","Private APIs/private integrations solve network reachability, while authorization still controls who may perform an operation."]
  ),
  r(/cloudfront|lambda@edge/i,
    ["Keep origins private where possible using Origin Access Control for S3 and tightly scoped origin security controls for custom origins.","Use TLS, signed URLs/cookies or application authorization where content is restricted; caching must not bypass identity boundaries.","WAF and edge logs provide complementary protection/visibility—WAF filters requests while CloudFront controls delivery and caching."],
    ["Optimize cache keys so headers/cookies/query strings vary the cache only when the origin response truly changes.","Use origin request policies and compression to reduce origin traffic and transferred bytes.","For Lambda@Edge/CloudFront Functions, place only latency-sensitive lightweight logic at the edge and keep regional business logic regional."],
    ["Data transfer out and request volume dominate many distributions; invalidations, real-time logs and edge compute may add cost.","A higher cache-hit ratio reduces origin requests and can reduce both origin compute and data-transfer cost.","Forwarding unnecessary headers/cookies/query strings fragments the cache and can indirectly increase origin-side cost."],
    ["Cache policy controls the cache key; origin request policy controls what reaches the origin—those are related but not identical.","Viewer and origin request/response events occur at different phases; choose the edge trigger from the behavior you need.","A CDN improves delivery and origin protection, but it does not replace application authorization or origin resilience."]
  ),
  r(/\b(s3|simple storage service)\b/i,
    ["Block public access by default, use bucket/access-point policies deliberately and prefer temporary role-based access or presigned URLs over shared credentials.","Use SSE-S3 or KMS encryption according to key-control needs, and protect destructive operations with versioning/Object Lock where the requirement warrants it.","Use CloudTrail data events or S3 server access logs selectively when object-level audit is required; control access to the logs themselves."],
    ["Design prefixes/objects for the workload rather than emulating a filesystem; use multipart upload for large objects and lifecycle rules for aging data.","Use Intelligent-Tiering when access patterns are unknown or change, but use explicit classes/lifecycle when access and retention are predictable.","Keep analytics formats columnar/compressed and partitioned so Athena/Glue/Spark scan less data."],
    ["Storage GB-month, requests, retrievals, lifecycle transitions and data transfer vary by storage class.","Archive classes trade lower storage price for retrieval delay/fees; transition tiny short-lived objects only when the economics make sense.","Reducing scanned bytes, unnecessary GET/LIST activity and cross-Region/internet transfer can matter as much as raw storage size."],
    ["S3 is object storage: updates replace objects; there is no in-place block update semantics.","Versioning protects against overwrite/delete but still needs lifecycle management or old versions can accumulate indefinitely.","Replication is not backup by itself—replicated mistakes or deletions depend on the replication/versioning configuration."]
  ),
  r(/\b(ebs|elastic block store)\b/i,
    ["Encrypt volumes/snapshots with KMS and control snapshot sharing because snapshots can expose the full data set.","Restrict instance and backup roles; attach volumes only to workloads that require the block device.","Use CloudTrail plus EC2/EBS metrics to track administrative changes and performance saturation."],
    ["Choose gp3/io2 from required IOPS, throughput, latency and durability rather than only capacity.","Separate performance-intensive data/log workloads when independent IOPS/throughput tuning helps.","Use snapshots for recovery and AMIs for reusable boot images; they solve different lifecycle needs."],
    ["Provisioned GB-month is only one dimension; some volume types separately charge provisioned IOPS and throughput.","Unused oversized volumes and old snapshots are common hidden cost sources.","Right-size capacity/performance independently on gp3 instead of paying for excess capacity only to gain IOPS."],
    ["EBS is AZ-scoped block storage normally attached to EC2; it is not a regional shared filesystem.","Snapshots are incremental from a billing/storage perspective but each snapshot can restore a complete volume.","Multi-AZ database availability is an application/database architecture concern, not something EBS alone provides."]
  ),
  r(/\b(efs|elastic file system)\b/i,
    ["Use security groups plus IAM authorization/access points where appropriate; POSIX permissions remain part of the file-access model.","Encrypt data at rest/in transit and use access points to give applications isolated roots and identities.","Backups and filesystem policies should match the shared nature of the data because one mount can affect many clients."],
    ["Pick Regional vs One Zone and performance/throughput modes from availability and workload behavior.","Use lifecycle/tiering for cold files and watch metadata-heavy workloads because millions of small operations can behave differently from large sequential I/O.","Access points simplify multi-application mounts and reduce custom mount-time permission logic."],
    ["Storage class capacity plus throughput mode/usage are the main design dimensions; backups and cross-AZ access can add cost.","Lifecycle policies can move cold files to lower-cost classes automatically.","Shared file convenience can become expensive when large inactive datasets stay in the primary class indefinitely."],
    ["EFS is shared NFS file storage; choose EBS for single-instance block semantics and S3 for object semantics.","Throughput scales differently by throughput mode, so performance troubleshooting should inspect both I/O pattern and configured mode.","A shared filesystem can become a shared failure/performance dependency—monitor it as a platform component."]
  ),
  r(/dynamodb/i,
    ["Use IAM condition keys and fine-grained access patterns where useful; keep application authorization separate from table permissions.","Encrypt by default and protect exports/backups/streams with the same data-classification controls as the table.","CloudTrail covers control-plane activity; operational debugging also needs table/stream metrics and application-level request context."],
    ["Design partition and sort keys from access patterns first; avoid scans and hot partitions by distributing traffic across keys.","Use GSIs/LSIs only for real query patterns and remember each secondary index adds write/storage cost and its own scaling behavior.","Choose on-demand for unpredictable traffic and provisioned/autoscaling when traffic is predictable enough to benefit."],
    ["Read/write request units or on-demand requests, storage, backups, streams, global tables and indexes all contribute.","Strongly consistent reads cost more capacity than eventually consistent reads; item size directly affects consumed capacity.","Poor key/index design can multiply both latency and cost through scans, retries and write amplification."],
    ["DynamoDB scales partitions, but a single hot partition key can still throttle.","Transactions, strong consistency and global tables provide stronger semantics at additional capacity/replication cost.","Streams are change records for downstream processing; they are not a general-purpose queue for arbitrary producers."]
  ),
  r(/aurora|\brds\b|database/i,
    ["Place databases in private subnets, restrict security groups to application tiers and use Secrets Manager/IAM authentication where supported.","Encrypt storage, snapshots and replicas with KMS and control who can create/restore/share snapshots.","Audit administrative changes and monitor slow queries, connections, replication/failover and storage pressure—not just CPU."],
    ["Use reader endpoints/read replicas for read scaling and Multi-AZ/cluster replicas for availability according to the engine model.","Pool connections or use RDS Proxy for bursty serverless workloads when connection storms are the bottleneck.","Tune queries/indexes before scaling instance size; compute cannot fully compensate for inefficient access patterns."],
    ["Instance/ACU capacity, storage, I/O/requests, backup retention and data transfer vary by engine/deployment model.","Read replicas and Multi-AZ copies improve capability but add compute/storage cost; they should map to a real read-scale or resilience need.","Serverless capacity can lower idle cost for variable workloads but minimum capacity and sustained load still matter."],
    ["Multi-AZ is primarily availability; read replicas are primarily read scale (with engine-specific failover options).","Backups give point-in-time recovery; replicas are live copies and can replicate bad data changes.","Connection count can be the limiting resource before CPU, especially with highly concurrent Lambda/serverless clients."]
  ),
  r(/bedrock|amazon q|sagemaker|comprehend|rekognition|textract|transcribe|translate|polly|personalize|kendra|lex|machine learning|ai/i,
    ["Separate user/application authorization from model or AI-service permissions, and scope model/data access to the exact resources the workload needs.","Treat prompts, retrieved context, transcripts, documents and model outputs as potentially sensitive data; apply encryption, retention and logging controls accordingly.","For RAG/enterprise assistants, preserve source permissions during retrieval so the model cannot expose content a user was not allowed to read."],
    ["Measure quality, latency and cost together; optimize prompt/context size, retrieval quality, model choice and concurrency instead of only model speed.","Use asynchronous/batch inference for non-interactive work and smaller/specialized models where they meet the quality target.","Add evaluation and guardrails around the model boundary; deterministic business actions should remain explicit tools/workflows rather than hidden inside prompts."],
    ["Model/token/inference usage or provisioned capacity is only part of cost; vector search, storage, orchestration, logging and data transfer can be significant.","Long prompts and large retrieved contexts increase both latency and inference cost, so relevance filtering is a cost control as well as a quality control.","Provisioned capacity is useful only when utilization/latency requirements justify paying for reserved throughput."],
    ["Know which part of the AI system the service owns: model inference, retrieval/indexing, orchestration, training, feature processing or end-user assistant experience.","A successful model call is not proof of a good application—evaluate groundedness, safety, latency and business-task success.","Keep deterministic authorization and transactional rules outside probabilistic model reasoning."]
  ),
  r(/kinesis|firehose|msk|kafka|flink|stream/i,
    ["Use producer/consumer IAM or broker authentication and encrypt streams in transit/at rest; separate administrative permissions from data-plane read/write permissions.","Restrict cross-account/cluster connectivity deliberately and keep sensitive event payloads out of broad shared streams where possible.","Monitor consumer lag, failed delivery, throttling and retention pressure so data loss or stale processing is visible."],
    ["Partition/shard by a key that distributes load while preserving only the ordering you truly require.","Batch records and tune consumer concurrency/checkpointing to increase throughput without overwhelming downstream systems.","Choose managed delivery (Firehose) when you mainly need buffered delivery/transformation, and a stream/broker when consumers need independent real-time reads."],
    ["Capacity units/shards or broker compute, retained data, enhanced fan-out, transformations and destination services all contribute.","Tiny unbatched records can create inefficient request overhead; batching generally improves throughput and cost.","Retention and replica/broker count should be tied to replay/recovery requirements, not left oversized by default."],
    ["Ordering is normally partition/shard scoped, not global.","Consumer lag is often a more useful production signal than producer throughput alone.","Delivery services, durable streams and Kafka-compatible brokers solve different operational problems even if all move events."]
  ),
  r(/athena|glue|redshift|quicksight|open ?search|analytics/i,
    ["Use Lake Formation/IAM/resource policies to keep data authorization separate from query or visualization access.","Encrypt datasets, query results and catalog/warehouse storage, and restrict broad analyst access to sensitive columns/data sets.","Audit administrative/query activity as appropriate and keep result buckets/log destinations governed because they can contain the same sensitive data as sources."],
    ["Partition, compress and use columnar formats so engines scan/process only useful data.","Match engine to workload: serverless ad-hoc SQL, ETL/catalog, search, warehouse and BI each have different performance shapes.","Pre-aggregate/materialize repeated expensive computations when it improves both latency and scanned/processed volume."],
    ["Data scanned/processed, compute capacity, storage and concurrency vary by analytics service; downstream visualization/export/storage also count.","Poor partitioning and repeated full scans are common avoidable cost multipliers.","Reserved/provisioned analytics capacity pays off only when utilization and concurrency justify continuous capacity."],
    ["Cataloging data is not the same as transforming it, and transforming is not the same as querying it.","Serverless does not mean costless at scale—bytes processed and repeated queries can dominate.","For BI, semantic/data-set design can matter more to user performance than simply increasing backend compute."]
  ),
  r(/iam|identity center|access analyzer/i,
    ["Prefer federation and temporary credentials; reserve long-lived IAM users/access keys for exceptional machine cases with rotation and monitoring.","Separate identity policy, resource policy, permissions boundary, SCP and session policy responsibilities instead of assuming one policy type controls everything.","Use Access Analyzer/CloudTrail to detect unintended trust and verify who actually used privileged APIs."],
    ["Design roles around job functions and workload identities, then use groups/permission sets and automation rather than duplicating policies principal by principal.","Use conditions, tags and scoped resources to reduce policy size while keeping authorization understandable.","Test effective permissions and trust paths before adding broader wildcard actions to fix AccessDenied errors."],
    ["IAM itself is generally not priced per policy/user, but identity design drives costs in connected services such as Identity Center applications, logging or third-party federation.","The real optimization target is operational overhead and blast radius: simpler reusable roles reduce both administration effort and security risk.","Avoid creating separate bespoke identities where federation, roles or permission sets can reuse a governed access model."],
    ["Authentication answers who you are; IAM authorization answers what the principal may do.","A role trust policy controls who may assume the role, while identity/resource policies control what actions are allowed after assumption.","SCPs set organization guardrails; they do not grant permissions by themselves."]
  ),
  r(/kms|encryption sdk|cloudhsm|certificate manager/i,
    ["Treat key administration and key usage as separate duties; key policy plus IAM permissions define who can use KMS keys.","Use grants/resource policies carefully for AWS-service integrations and cross-account encryption.","Log key-management activity and watch for disable/schedule-deletion/policy changes because they can make large amounts of data unavailable."],
    ["Use envelope encryption so KMS protects data keys rather than encrypting large payloads directly.","Reuse data keys only within an acceptable security boundary and use service-integrated encryption instead of building custom crypto when possible.","Choose multi-Region keys or custom key stores only when their operational requirement is real; they add complexity."],
    ["KMS cost follows key inventory and API requests; high-frequency Encrypt/Decrypt calls can be reduced with envelope encryption/data-key caching where appropriate.","Custom key stores/CloudHSM introduce dedicated capacity costs and operational ownership.","Service-side encryption may trigger KMS calls at object/request scale, so request volume can matter more than key count."],
    ["KMS keys do not leave KMS in plaintext; envelope encryption moves protected data keys with the ciphertext.","Deleting or disabling a key can make otherwise healthy encrypted data unusable.","Encryption controls confidentiality; it does not replace authorization, backups or integrity controls."]
  ),
  r(/secrets manager|parameter store/i,
    ["Grant GetSecretValue only to workloads that need a secret and separate secret administration/rotation permissions.","Encrypt with KMS and use resource policies carefully for cross-account access; never copy secrets into source code or images.","Audit reads/changes and rotate credentials when the target system supports it."],
    ["Cache secrets in the application/extension for a controlled period instead of calling the service on every request.","Use managed rotation patterns for supported databases or implement tested custom rotation when required.","Store configuration that is not secret in configuration services rather than paying/operating a secret lifecycle for every parameter."],
    ["Secret storage and API calls are primary dimensions; frequent uncached reads can create unnecessary cost and latency.","Rotation can invoke Lambda and target-system operations, which should be included in the operational cost model.","Consolidate only when lifecycle and access boundaries match—do not reduce secret count by combining unrelated credentials."],
    ["Version stages such as AWSCURRENT/AWSPENDING are central to rotation workflows.","A secret store removes hard-coded credentials but applications still need an IAM identity to retrieve the secret.","Rotation is a distributed change across the secret and target credential, so test failure/rollback paths."]
  ),
  r(/waf|shield|network firewall|firewall manager|guardduty|security hub|inspector|macie|detective|security/i,
    ["Centralize security administration across accounts where supported, while keeping workload-specific response ownership clear.","Restrict who can suppress findings, change protection rules or modify logging because those actions can hide or weaken controls.","Send findings/logs to durable central destinations and automate only well-understood remediations with bounded permissions."],
    ["Tune rules/detections using observed traffic and false-positive data instead of enabling every control at maximum sensitivity.","Filter and aggregate findings before paging humans; use EventBridge/automation for deterministic low-risk responses.","Place preventive controls at the correct traffic/resource boundary so they block threats before expensive downstream processing."],
    ["Charges may follow protected resources, rules, requests inspected, logs/data analyzed or findings—security architecture shape determines the driver.","Verbose logging can become a material CloudWatch/S3/SIEM cost at high request volumes.","Central policies can reduce duplicated rule management but should not create unnecessary inspection paths for traffic that does not require them."],
    ["Differentiate prevention (WAF/firewall), detection (GuardDuty/Inspector/Macie), aggregation (Security Hub) and investigation (Detective).","A finding is evidence to evaluate, not proof that automated destructive remediation is always safe.","Logging destinations and retention are part of the security design because post-incident evidence is only useful if it still exists and is trustworthy."]
  ),
  r(/vpc|route 53|direct connect|vpn|transit gateway|private ?link|load balanc|global accelerator|network/i,
    ["Use security groups/NACLs/firewalls for authorization/inspection and route tables for path selection; do not confuse routing with permission.","Prefer private connectivity/endpoints for internal service access when it reduces public exposure and matches the architecture.","Enable flow/DNS/load-balancer logs where investigation needs them and protect network-control-plane changes with least privilege."],
    ["Design subnets/routes around failure domains and traffic paths; avoid centralized bottlenecks that force every packet through unnecessary hops.","Use the correct connectivity primitive—peering, Transit Gateway, PrivateLink, VPN or Direct Connect—based on transitivity, scale and ownership boundaries.","For load balancing/DNS, use health checks and independent targets so failover responds to application health rather than only infrastructure presence."],
    ["Hourly attachment/gateway/load-balancer charges plus processed bytes/data transfer are common networking dimensions.","Cross-AZ, cross-Region, NAT and inspection paths can create large data-processing/transfer bills even when compute is modest.","Keep traffic local/private when practical and remove avoidable hairpin routes before optimizing small per-hour resource charges."],
    ["Routing decides where traffic goes; security controls decide whether it is allowed.","PrivateLink is service-oriented private access, while Transit Gateway/peering connect networks—different ownership and routing semantics.","Multi-AZ does not guarantee application failover unless health checks and routing/load-balancing actually stop sending traffic to unhealthy targets."]
  ),
  r(/ecs|eks|fargate|ecr|container/i,
    ["Use task roles/pod identities for workload permissions and separate them from node/agent permissions.","Keep secrets outside images and scan/sign images in the registry/supply chain before deployment.","Restrict cluster/service network paths with security groups/network policies and log both control-plane and workload activity where needed."],
    ["Scale services from workload signals such as CPU, memory, queue depth or request rate—not only node count.","Right-size task/pod requests and limits so schedulers can pack capacity efficiently without causing throttling/OOM churn.","Use Fargate for reduced infrastructure management and EC2 capacity when specialized instances/daemon workloads/cost optimization justify node ownership."],
    ["Runtime vCPU/memory or EC2 capacity, load balancers, logs, image storage/scanning and data transfer all contribute.","Poor bin-packing/oversized requests waste node capacity; Fargate avoids idle nodes but can cost more for steady dense fleets.","Lifecycle old images/logs and use Savings Plans/Spot where workload interruption characteristics allow."],
    ["ECR stores images; ECS/EKS orchestrate workloads; Fargate supplies compute capacity—these are separate layers.","A healthy container process is not necessarily a healthy service endpoint; configure meaningful readiness/health checks.","Persistent state should live in purpose-built data/storage services unless the workload explicitly requires attached persistent volumes."]
  ),
  r(/ec2|auto scaling|beanstalk|app runner|lightsail|batch|compute/i,
    ["Use instance/task roles instead of static access keys and restrict inbound management access; prefer Systems Manager over broadly open SSH/RDP.","Harden AMIs, encrypt attached storage and separate public ingress from private application/data subnets.","Track OS/application logs and patch posture in addition to EC2 control-plane events."],
    ["Scale horizontally with load balancing/Auto Scaling when the workload allows it and right-size instance families from measured CPU, memory, network and storage needs.","Use Spot for interruptible capacity and Savings Plans/commitments for stable baseline usage.","Automate immutable image/deployment pipelines so replacement is safer than repairing snowflake instances manually."],
    ["Instance runtime is only the baseline: EBS, snapshots, load balancers, public IPv4, data transfer and logging often add meaningful cost.","Idle or oversized instances are the largest avoidable waste; scheduling non-production capacity and rightsizing usually beat micro-optimizing unit prices.","Commit discounts are valuable only for a stable baseline; keep variable/burst capacity flexible."],
    ["An Auto Scaling Group replaces/scales instances but does not make a stateful application stateless.","Instance family choice affects CPU architecture, memory, network and local storage—not just price.","Multi-AZ placement plus health-aware load balancing is what turns multiple instances into an available service."]
  ),
  r(/cloudwatch|cloudtrail|config|systems manager|control tower|organizations|trusted advisor|compute optimizer|service catalog|well-architected|management|governance/i,
    ["Separate central observability/governance administration from workload roles and use organization-wide delegation only for approved security/platform accounts.","Protect log/audit stores from deletion or tampering and encrypt sensitive operational data.","Use CloudTrail for API audit, Config for resource configuration/compliance and CloudWatch for runtime telemetry instead of expecting one signal source to do all three jobs."],
    ["Collect high-value metrics/logs at the required resolution and retention; noisy telemetry without ownership creates cost without operational value.","Automate repetitive remediation with Systems Manager/EventBridge/Lambda but require approval for high-blast-radius actions.","Use organization policies/baselines to prevent drift, then exception workflows for workloads that truly need deviation."],
    ["Logs ingested/stored/queried, custom metrics, alarms, traces, configuration items and automation executions are common cost dimensions.","High-cardinality custom metrics and verbose debug logs can grow faster than workload compute cost.","Retention, sampling and metric-filter design should follow investigation/SLO requirements rather than keeping every signal forever."],
    ["Metrics, logs, traces, audit events and configuration history answer different questions—know which evidence source fits the incident.","A dashboard is not an operational control unless someone/automation acts on the signal.","Central governance should reduce repeated account-by-account work without removing local workload ownership."]
  ),
  r(/codebuild|codepipeline|codedeploy|codeartifact|cloudformation|cdk|cli|sdk|developer/i,
    ["Use temporary roles for CI/CD and developer tooling; separate build permissions from production deployment permissions.","Protect artifact/package repositories and signing/encryption keys because a compromised supply chain can bypass runtime controls.","Audit pipeline, stack, package and deployment changes so you can reconstruct exactly what code/infrastructure reached production."],
    ["Build once and promote immutable artifacts between environments instead of rebuilding differently for production.","Use change sets/diffs, automated tests and staged/canary/blue-green rollout to reduce deployment blast radius.","Cache dependencies and keep build environments ephemeral so CI is fast without accumulating configuration drift."],
    ["Build minutes/compute, artifact/package storage and requests, pipeline actions and downstream deployment resources are the main dimensions depending on the tool.","Dependency caching and reusable artifacts reduce repeated compute/downloads.","Infrastructure-as-code tools themselves may be low/no direct cost, but every provisioned resource and CI action they create still matters."],
    ["CDK synthesizes CloudFormation; CloudFormation owns the stack deployment lifecycle.","CodePipeline orchestrates stages; CodeBuild builds/tests; CodeDeploy performs supported deployment strategies—do not collapse them into one service.","The safest production pipeline crosses an explicit permission boundary rather than giving the build environment permanent production credentials."]
  ),
  r(/dms|datasync|transfer|migration|snow/i,
    ["Authenticate source and target independently and use private connectivity/encryption for migration traffic where required.","Limit migration roles to the source/target objects they must move and protect staging areas because they may contain full production datasets.","Log transfer errors and validation mismatches so cutover decisions are evidence-based."],
    ["Separate initial bulk load from incremental/CDC synchronization when downtime must be minimized.","Size network paths and parallelism from real source/target throughput; the slowest endpoint often limits migration, not the service itself.","Validate checksums/row counts/application behavior before final cutover and keep rollback criteria explicit."],
    ["Migration-instance/runtime, transferred bytes, accelerated transfer, storage and network egress can all contribute.","Repeated failed/restarted transfers can cost more than one well-sized validated migration window.","Use incremental sync to avoid re-copying unchanged datasets when the service supports it."],
    ["A completed copy is not a completed migration until data is validated and applications are cut over.","Source and target change rates determine how long CDC catch-up takes.","Network bandwidth, source read limits and target write limits should all be measured before scheduling the migration window."]
  ),
  r(/iot/i,
    ["Use per-device identities/certificates and tightly scoped policies; one shared credential across a fleet creates an enormous blast radius.","Rotate/revoke device credentials and secure provisioning/firmware update channels.","Treat device telemetry and commands separately: command authorization can be more sensitive than telemetry ingestion."],
    ["Filter/aggregate at the edge when raw telemetry does not need cloud processing.","Partition topics/rules by device or workload semantics and buffer downstream processing so cloud consumers can scale independently.","Use fleet-management jobs/shadows only where their state model matches device connectivity patterns."],
    ["Message volume, rules/actions, device-management operations and downstream storage/analytics dominate at fleet scale.","Reducing message frequency/payload size or aggregating at the edge can produce larger savings than tuning individual cloud functions.","Always include downstream time-series/storage/stream-processing cost in an IoT design."],
    ["Devices can be intermittently connected, so desired/reported state and retry semantics matter.","MQTT topic design is both an application-routing and authorization decision.","At fleet scale, credential lifecycle and observability are first-class architecture components."]
  ),
  r(/connect|ses|customer engagement/i,
    ["Protect customer/contact data, recordings and message content with role-based access, encryption and retention controls.","Keep agent/operator permissions separate from administrative configuration and integration roles.","Audit configuration changes and access to sensitive interaction records."],
    ["Automate predictable routing/notification steps, but keep human escalation paths for exceptions.","Integrate customer context from authoritative systems rather than duplicating stale data into contact flows.","Measure queue/contact/message success, latency and abandonment/bounce metrics to find the actual bottleneck."],
    ["Usage often follows contact minutes, messages, channels or add-on AI/analytics features; storage/recording and telecom charges can be significant.","Automation can lower human handling cost but may add Lambda, Lex, Bedrock or analytics charges.","Retention of recordings/transcripts/messages should follow business/compliance needs rather than indefinite storage."],
    ["Channel delivery is only one layer; routing, identity, business data lookup and human handling remain separate concerns.","Customer interaction records often contain regulated/sensitive information and need explicit lifecycle rules.","Successful automation should have a deterministic fallback when the customer or downstream system cannot complete the automated path."]
  )
];

const categoryFallback:Record<string,ServiceLearningInsights>={
  "Application Integration":{security:["Scope producer, consumer and orchestration permissions separately.","Protect message/event payloads according to their data classification.","Capture delivery failures, retries and control-plane changes."],optimization:["Choose push, queue, event routing or workflow orchestration from the delivery semantics the application needs.","Design retry, ordering, idempotency and back-pressure explicitly.","Decouple slow consumers so producer latency is not tied to every downstream system."],cost:["Model both integration-service operations and every downstream target invocation.","Batch/filter before delivery when supported to reduce requests and compute.","Retention, replay and failure-handling features should match a real recovery requirement."],watchPoints:["Know whether the service stores state/backlog or only routes/invokes.","Delivery semantics differ between services even when diagrams look similar.","Retries without idempotency can create duplicate business actions."]},
  "Storage":{security:["Control data-plane access separately from storage administration.","Encrypt data and backups/replicas with keys appropriate to the sensitivity.","Audit sharing, deletion and recovery-policy changes."],optimization:["Choose object, block or file semantics from the application access pattern.","Match performance and lifecycle tiers to actual access frequency.","Test recovery instead of assuming replication or snapshots alone meet the requirement."],cost:["Capacity, requests/I/O, performance tier and transfer are the main dimensions.","Cold tiers save storage cost only when retrieval/retention economics fit.","Lifecycle old versions/snapshots/replicas so protection data does not grow forever."],watchPoints:["Backup, replication and versioning protect against different failures.","Performance units and capacity are often independent design choices.","Recovery time is part of storage architecture, not an afterthought."]}
};

export function getServiceLearningInsights(service:string,category:string):ServiceLearningInsights{
  const rule=rules.find(x=>x.match.test(service));
  if(rule)return {security:rule.security,optimization:rule.optimization,cost:rule.cost,watchPoints:rule.watchPoints};
  const fallback=categoryFallback[category];
  if(fallback)return fallback;
  return {
    security:[`Identify the exact ${service} control-plane and data-plane permissions rather than granting broad category-level access.`,`Protect the data, credentials and integration points that pass through ${service}; use encryption and managed identities where the service supports them.`,`Collect the service-native audit/health signals that explain configuration changes, failed operations and downstream impact.`],
    optimization:[`Tune ${service} from its native throughput, concurrency, storage, connection or request model—not from a generic “scale everything” rule.`,`Use the architecture examples above to keep state, asynchronous work and failure isolation in the services designed to own them.`,`Measure the service-specific bottleneck before changing capacity, caching, batching or retry behavior.`],
    cost:[`Start with ${service}'s documented billing unit, then map how architecture volume turns into that unit.`,`Add the resources ${service} causes to run—storage, transfer, logs, encryption, compute and downstream API calls—so the estimate reflects the whole path.`,`Optimize the dominant measured driver first; removing unnecessary work usually matters more than small unit-price differences.`],
    watchPoints:[`Know what ${service} owns and what remains the responsibility of adjacent services in the architecture.`,`Identify its failure/retry boundary so an outage does not silently become duplicate work or data loss.`,`Remember the service-specific quota or scaling dimension most likely to constrain production before raw account-wide capacity.`]
  };
}
