export type AipC01Task = {
  id: string;
  title: string;
  focus: string[];
  services: string[];
  visual: "concept" | "console" | "mixed";
};

export type AipC01Domain = {
  id: string;
  number: string;
  title: string;
  weight: string;
  summary: string;
  tasks: AipC01Task[];
};

export const aipC01Domains: AipC01Domain[] = [
  { id: "foundation", number: "01", title: "Foundation Model Integration, Data Management, and Compliance", weight: "31%", summary: "Select, ground, govern, and prepare foundation-model solutions for production use.", tasks: [
    { id: "1-1", title: "Analyze requirements and design generative AI solutions", focus: ["Translate business and technical constraints into a GenAI architecture", "Build a technical proof of concept and apply the Well-Architected GenAI Lens", "Standardize reusable components without hiding workload-specific trade-offs"], services: ["Amazon Bedrock", "AWS Well-Architected Tool", "AWS Lambda", "Amazon SageMaker AI"], visual: "mixed" },
    { id: "1-2", title: "Select and configure foundation models", focus: ["Compare models by capability, modality, latency, context, and cost", "Switch providers or models through an abstraction layer", "Design resilience with fallback, cross-Region inference, and graceful degradation", "Customize, register, deploy, roll back, and retire models"], services: ["Amazon Bedrock", "Amazon SageMaker AI", "AWS Lambda", "AWS Step Functions", "AWS AppConfig"], visual: "console" },
    { id: "1-3", title: "Implement data validation and processing pipelines for foundation-model consumption", focus: ["Validate data quality and detect bad records before inference", "Process text, image, audio, and tabular inputs", "Format requests for Bedrock and SageMaker interfaces", "Normalize and enrich data before it becomes model context"], services: ["AWS Glue", "Amazon SageMaker Data Wrangler", "Amazon SageMaker Processing", "Amazon Transcribe", "Amazon Comprehend"], visual: "console" },
    { id: "1-4", title: "Design and implement vector store solutions", focus: ["Choose a vector-store architecture for retrieval augmentation", "Attach metadata and access context to embeddings", "Tune indexing and sharding for performance", "Integrate document systems and keep indexes synchronized"], services: ["Amazon Bedrock Knowledge Bases", "Amazon OpenSearch Service", "Amazon Aurora", "Amazon S3", "Amazon DynamoDB"], visual: "mixed" },
    { id: "1-5", title: "Design retrieval mechanisms for foundation-model augmentation", focus: ["Chunk and segment source content for retrieval", "Create embeddings and batch embedding work", "Select vector, hybrid, and reranked search", "Expand, decompose, and transform queries", "Expose retrieval through APIs, function calling, or MCP"], services: ["Amazon Bedrock", "Amazon Bedrock Knowledge Bases", "Amazon OpenSearch Service", "Amazon Aurora", "AWS Lambda"], visual: "mixed" },
    { id: "1-6", title: "Implement prompt engineering strategies and governance for foundation-model interactions", focus: ["Use instruction frameworks, templates, and guardrails", "Maintain conversational context and history", "Version, audit, test, and govern prompts", "Build regression tests and Prompt Flows with branching and reusable steps"], services: ["Amazon Bedrock Prompt Management", "Amazon Bedrock Prompt Flows", "Amazon Bedrock", "AWS Step Functions", "Amazon CloudWatch Logs", "AWS CloudTrail"], visual: "mixed" },
  ] },
  { id: "integration", number: "02", title: "Implementation and Integration", weight: "26%", summary: "Turn models and agents into resilient, observable application capabilities.", tasks: [
    { id: "2-1", title: "Implement agentic AI solutions and tool integrations", focus: ["Persist agent memory and state", "Coordinate reasoning, tools, and model ensembles", "Bound execution with timeouts, IAM, circuit breakers, and human approval", "Expose tools through functions, Lambda, or MCP"], services: ["Amazon Bedrock", "AWS Step Functions", "AWS Lambda", "Amazon DynamoDB", "Amazon ECS"], visual: "mixed" },
    { id: "2-2", title: "Implement model deployment strategies", focus: ["Deploy for application latency and performance needs", "Account for container, GPU, memory, and token-processing constraints", "Choose optimized models and cascading strategies"], services: ["Amazon Bedrock", "Amazon SageMaker AI", "AWS Lambda", "Amazon ECS"], visual: "console" },
    { id: "2-3", title: "Design and implement enterprise integration architectures", focus: ["Connect legacy systems, events, and synchronized data", "Expose AI capabilities through APIs and events", "Secure federation, RBAC, and least privilege", "Support hybrid jurisdictions and CI/CD with rollback and observability"], services: ["Amazon API Gateway", "AWS Lambda", "Amazon EventBridge", "AWS Outposts", "AWS CodePipeline", "AWS CodeBuild"], visual: "mixed" },
    { id: "2-4", title: "Implement foundation-model API integrations", focus: ["Build flexible synchronous and asynchronous model interactions", "Stream responses through WebSockets, SSE, or chunked APIs", "Apply retries, rate limits, fallback, and tracing", "Route requests across models with static or dynamic policy"], services: ["Amazon Bedrock", "Amazon API Gateway", "Amazon SQS", "AWS Step Functions", "AWS X-Ray"], visual: "console" },
    { id: "2-5", title: "Implement application integration patterns and development tools", focus: ["Build accessible streaming AI interfaces", "Embed AI into business workflows and document processes", "Use developer assistants and advanced agent frameworks", "Troubleshoot through logs, traces, and structured diagnostics"], services: ["AWS Amplify", "Amazon Bedrock", "Amazon Q Developer", "AWS Lambda", "Amazon Bedrock Data Automation", "AWS X-Ray"], visual: "mixed" },
  ] },
  { id: "safety", number: "03", title: "AI Safety, Security, and Governance", weight: "20%", summary: "Protect inputs, outputs, data, models, users, and the decisions made around them.", tasks: [
    { id: "3-1", title: "Implement input and output safety controls", focus: ["Detect harmful prompts and unsafe outputs", "Reduce hallucinations with grounding, confidence, and schema checks", "Layer prefilters, guardrails, postprocessing, and API controls", "Test against prompt injection, jailbreaks, and adversarial inputs"], services: ["Amazon Bedrock Guardrails", "Amazon Comprehend", "AWS Lambda", "Amazon API Gateway", "Amazon Bedrock"], visual: "mixed" },
    { id: "3-2", title: "Implement data security and privacy controls", focus: ["Isolate AI workloads with VPC endpoints and least privilege", "Discover, mask, anonymize, and retain sensitive information safely", "Protect data across S3, model calls, logs, and downstream stores"], services: ["Amazon VPC", "AWS IAM", "AWS Lake Formation", "Amazon Macie", "Amazon Comprehend", "AWS KMS"], visual: "console" },
    { id: "3-3", title: "Implement AI governance and compliance mechanisms", focus: ["Maintain model cards, lineage, metadata, and decision logs", "Track source data and changes", "Apply organizational governance frameworks", "Monitor misuse, drift, bias, policy violations, and remediation"], services: ["AWS Glue", "AWS CloudTrail", "Amazon CloudWatch", "Amazon SageMaker Model Monitor", "Amazon SageMaker Clarify"], visual: "mixed" },
    { id: "3-4", title: "Implement responsible AI principles", focus: ["Explain outputs with uncertainty, evidence, sources, and traces", "Evaluate fairness with repeatable metrics and experiments", "Enforce policy compliance in the model and application layers"], services: ["Amazon Bedrock Guardrails", "Amazon SageMaker Clarify", "Amazon Bedrock Prompt Management", "AWS Lambda"], visual: "concept" },
  ] },
  { id: "optimization", number: "04", title: "Operational Efficiency and Optimization for Generative AI Applications", weight: "12%", summary: "Control cost, latency, throughput, capacity, and operational visibility.", tasks: [
    { id: "4-1", title: "Implement cost optimization and resource efficiency strategies", focus: ["Reduce tokens and context without losing required meaning", "Match model tiers and usage modes to quality needs", "Batch and cache work while monitoring utilization", "Use semantic, deterministic, edge, or prompt caching appropriately"], services: ["Amazon Bedrock", "Amazon ElastiCache", "Amazon CloudWatch", "AWS Cost Explorer", "Amazon S3"], visual: "mixed" },
    { id: "4-2", title: "Optimize application performance", focus: ["Balance latency, cost, and user experience", "Tune retrieval indexes, queries, concurrency, and batching", "Use model parameters and capacity allocation deliberately", "Optimize workflow, API, vector, and downstream service paths"], services: ["Amazon Bedrock", "Amazon OpenSearch Service", "Amazon API Gateway", "AWS Lambda", "Amazon CloudWatch"], visual: "mixed" },
    { id: "4-3", title: "Implement monitoring systems for generative AI applications", focus: ["Observe operations, performance, model interactions, business, and compliance", "Track tokens, prompt effectiveness, hallucinations, quality, and cost anomalies", "Build actionable dashboards and troubleshoot vector stores and model behavior"], services: ["Amazon CloudWatch", "Amazon CloudWatch Logs", "AWS X-Ray", "Amazon OpenSearch Service", "Amazon SageMaker Model Monitor"], visual: "console" },
  ] },
  { id: "testing", number: "05", title: "Testing, Validation, and Troubleshooting", weight: "11%", summary: "Prove quality, catch regressions, and diagnose failures across models, retrieval, agents, and APIs.", tasks: [
    { id: "5-1", title: "Implement evaluation systems for generative AI", focus: ["Measure quality, relevance, factuality, consistency, and fluency", "Compare models with A/B, canary, cost, and performance evaluation", "Collect human feedback and annotations", "Gate releases with regression, RAG, agent, retrieval, and deployment validation"], services: ["Amazon Bedrock Model Evaluations", "Amazon Bedrock", "Amazon SageMaker Clarify", "Amazon CloudWatch", "AWS Step Functions"], visual: "mixed" },
    { id: "5-2", title: "Troubleshoot generative AI applications", focus: ["Resolve context overflow, truncation, and chunking failures", "Diagnose API integration, schema, retry, and rate-limit errors", "Compare prompt versions and refine regressions", "Investigate embeddings, drift, vectorization, preprocessing, and search performance"], services: ["Amazon CloudWatch Logs", "AWS X-Ray", "Amazon Bedrock", "Amazon OpenSearch Service", "AWS Lambda"], visual: "console" },
  ] },
];

export const aipC01TaskCount = aipC01Domains.reduce((count, domain) => count + domain.tasks.length, 0);
