export type ScopeCategory = { title: string; services: string[] };

export const saaScope: ScopeCategory[] = [
  { title: "Analytics", services: ["Amazon Athena", "AWS Data Exchange", "Amazon Data Firehose", "Amazon EMR", "AWS Glue", "Amazon Kinesis", "AWS Lake Formation", "Amazon Managed Streaming for Apache Kafka (Amazon MSK)", "Amazon OpenSearch Service", "Amazon Quick", "Amazon Redshift"] },
  { title: "Application Integration", services: ["Amazon AppFlow", "AWS AppSync", "Amazon EventBridge", "Amazon MQ", "Amazon SNS", "Amazon SQS", "AWS Step Functions"] },
  { title: "AWS Cost Management", services: ["AWS Budgets", "AWS Cost and Usage Report", "AWS Cost Explorer", "Savings Plans"] },
  { title: "Compute", services: ["AWS Batch", "Amazon EC2", "Amazon EC2 Auto Scaling", "AWS Elastic Beanstalk", "AWS Outposts", "AWS Serverless Application Repository", "VMware Cloud on AWS", "AWS Wavelength"] },
  { title: "Containers", services: ["Amazon ECR", "Amazon ECS", "Amazon ECS Anywhere", "Amazon EKS", "Amazon EKS Anywhere", "Amazon EKS Distro"] },
  { title: "Database", services: ["Amazon Aurora", "Amazon Aurora Serverless", "Amazon DocumentDB", "Amazon DynamoDB", "Amazon ElastiCache", "Amazon Keyspaces", "Amazon Neptune", "Amazon RDS", "Amazon Redshift"] },
  { title: "Developer Tools", services: ["AWS X-Ray"] },
  { title: "Front-End Web and Mobile", services: ["AWS Amplify", "Amazon API Gateway", "AWS Device Farm"] },
  { title: "Machine Learning", services: ["Amazon Augmented AI", "Amazon Comprehend", "Amazon Comprehend Medical", "Amazon Kendra", "Amazon Lex", "Amazon Nova", "Amazon PartyRock", "Amazon Personalize", "Amazon Polly", "Amazon Rekognition", "Amazon SageMaker AI", "Amazon Textract", "Amazon Transcribe", "Amazon Translate"] },
  { title: "Management and Governance", services: ["AWS Auto Scaling", "AWS CLI", "AWS CloudFormation", "AWS CloudTrail", "Amazon CloudWatch", "AWS Compute Optimizer", "AWS Config", "AWS Control Tower", "AWS Health Dashboard", "AWS License Manager", "Amazon Managed Grafana", "Amazon Managed Service for Prometheus", "AWS Management Console", "AWS Organizations", "AWS Service Catalog", "AWS Systems Manager", "AWS Trusted Advisor", "AWS Well-Architected Tool"] },
  { title: "Media Services", services: ["Amazon Elastic Transcoder", "Amazon Kinesis Video Streams"] },
  { title: "Migration and Transfer", services: ["AWS Application Migration Service", "AWS DataSync", "AWS DMS", "AWS Snow Family", "AWS Transfer Family"] },
  { title: "Networking and Content Delivery", services: ["AWS Client VPN", "Amazon CloudFront", "AWS Direct Connect", "Elastic Load Balancing", "AWS Global Accelerator", "AWS PrivateLink", "Amazon Route 53", "AWS Site-to-Site VPN", "AWS Transit Gateway", "Amazon VPC"] },
  { title: "Security, Identity, and Compliance", services: ["AWS Artifact", "AWS Audit Manager", "AWS Certificate Manager", "AWS CloudHSM", "Amazon Cognito", "Amazon Detective", "AWS Directory Service", "AWS Firewall Manager", "Amazon GuardDuty", "AWS IAM Identity Center", "Amazon Inspector", "AWS KMS", "Amazon Macie", "AWS Network Firewall", "AWS Resource Access Manager", "AWS Secrets Manager", "AWS Security Hub", "AWS Shield", "AWS WAF", "AWS IAM"] },
  { title: "Serverless", services: ["AWS AppSync", "AWS Fargate", "AWS Lambda"] },
  { title: "Storage", services: ["AWS Backup", "Amazon EBS", "Amazon EFS", "Amazon FSx", "Amazon S3", "Amazon S3 Glacier", "AWS Storage Gateway"] },
];

export const sapScope: ScopeCategory[] = [
  { title: "Analytics", services: ["Amazon Athena", "AWS Data Exchange", "Amazon Data Firehose", "Amazon EMR", "AWS Glue", "Amazon Kinesis Data Streams", "AWS Lake Formation", "Amazon Managed Service for Apache Flink", "Amazon Managed Streaming for Apache Kafka (Amazon MSK)", "Amazon OpenSearch Service", "Amazon QuickSight"] },
  { title: "Application Integration", services: ["Amazon AppFlow", "AWS AppSync", "Amazon EventBridge", "Amazon MQ", "Amazon SNS", "Amazon SQS", "AWS Step Functions"] },
  { title: "Blockchain", services: ["Amazon Managed Blockchain"] },
  { title: "Business Applications", services: ["Amazon SES"] },
  { title: "Cloud Financial Management", services: ["AWS Budgets", "AWS Cost and Usage Report", "AWS Cost Explorer", "Savings Plans"] },
  { title: "Compute", services: ["AWS App Runner", "AWS Auto Scaling", "AWS Batch", "AWS Elastic Beanstalk", "Amazon EC2", "Amazon EC2 Auto Scaling", "AWS Fargate", "AWS Lambda", "Amazon Lightsail", "AWS Outposts", "AWS Wavelength"] },
  { title: "Containers", services: ["Amazon ECR", "Amazon ECS", "Amazon ECS Anywhere", "Amazon EKS", "Amazon EKS Anywhere", "Amazon EKS Distro"] },
  { title: "Database", services: ["Amazon Aurora", "Amazon Aurora Serverless", "Amazon DocumentDB", "Amazon DynamoDB", "Amazon ElastiCache", "Amazon Keyspaces", "Amazon Neptune", "Amazon RDS", "Amazon Redshift", "Amazon Timestream"] },
  { title: "Developer Tools", services: ["AWS CDK", "AWS CodeArtifact", "AWS CodeBuild", "AWS CodeDeploy", "Amazon CodeGuru", "AWS CodePipeline", "AWS Tools and SDKs", "AWS X-Ray"] },
  { title: "End User Computing", services: ["Amazon AppStream 2.0", "Amazon WorkSpaces"] },
  { title: "Frontend Web and Mobile", services: ["AWS Amplify", "Amazon API Gateway", "AWS Device Farm", "Amazon Pinpoint"] },
  { title: "Internet of Things (IoT)", services: ["AWS IoT Core", "AWS IoT Device Defender", "AWS IoT Device Management", "AWS IoT Events", "AWS IoT Greengrass", "AWS IoT SiteWise", "AWS IoT Things Graph", "AWS IoT 1-Click"] },
  { title: "Machine Learning", services: ["Amazon Augmented AI", "Amazon Comprehend", "Amazon Comprehend Medical", "Amazon Fraud Detector", "Amazon Kendra", "Amazon Lex", "Amazon Nova", "Amazon PartyRock", "Amazon Personalize", "Amazon Polly", "Amazon Rekognition", "Amazon SageMaker AI", "Amazon Textract", "Amazon Transcribe", "Amazon Translate"] },
  { title: "Media Services", services: ["Amazon Elastic Transcoder", "Amazon Kinesis Video Streams"] },
  { title: "Management and Governance", services: ["AWS CloudFormation", "AWS CloudTrail", "Amazon CloudWatch", "Amazon CloudWatch Logs", "AWS CLI", "AWS Compute Optimizer", "AWS Config", "AWS Control Tower", "AWS Cost Anomaly Detection", "AWS Health Dashboard", "AWS License Manager", "Amazon Managed Grafana", "Amazon Managed Service for Prometheus", "AWS Management Console", "AWS Organizations", "AWS Proton", "AWS Service Catalog", "AWS Service Quotas", "AWS Systems Manager", "AWS Trusted Advisor", "AWS Well-Architected Tool"] },
  { title: "Migration and Transfer", services: ["AWS Application Discovery Service", "AWS Application Migration Service", "AWS DMS", "AWS DataSync", "AWS Migration Hub", "AWS Schema Conversion Tool", "AWS Snow Family", "AWS Transfer Family"] },
  { title: "Networking and Content Delivery", services: ["Amazon CloudFront", "AWS Direct Connect", "Elastic Load Balancing", "AWS Global Accelerator", "AWS PrivateLink", "Amazon Route 53", "AWS Transit Gateway", "Amazon VPC", "AWS VPN"] },
  { title: "Security, Identity, and Compliance", services: ["AWS Artifact", "AWS Audit Manager", "AWS Certificate Manager", "AWS CloudHSM", "Amazon Cognito", "Amazon Detective", "AWS Directory Service", "AWS Firewall Manager", "Amazon GuardDuty", "AWS IAM Identity Center", "AWS IAM", "Amazon Inspector", "AWS KMS", "Amazon Macie", "AWS Network Firewall", "AWS Resource Access Manager", "AWS Secrets Manager", "AWS Security Hub", "AWS Security Token Service", "AWS Shield", "AWS WAF"] },
  { title: "Storage", services: ["AWS Backup", "Amazon EBS", "AWS Elastic Disaster Recovery", "Amazon EFS", "Amazon FSx", "Amazon S3", "Amazon S3 Glacier", "AWS Storage Gateway"] },
];

export const aipScope: ScopeCategory[] = [
  { title: "Analytics", services: ["Amazon Athena", "Amazon EMR", "AWS Glue", "Amazon Kinesis", "Amazon OpenSearch Service", "Amazon Quick Sight", "Amazon Managed Streaming for Apache Kafka (Amazon MSK)"] },
  { title: "Application Integration", services: ["Amazon AppFlow", "AWS AppConfig", "Amazon EventBridge", "Amazon SNS", "Amazon SQS", "AWS Step Functions"] },
  { title: "Compute", services: ["AWS App Runner", "Amazon EC2", "AWS Lambda", "AWS Lambda@Edge", "AWS Outposts", "AWS Wavelength"] },
  { title: "Containers", services: ["Amazon ECR", "Amazon ECS", "Amazon EKS", "AWS Fargate"] },
  { title: "Customer Engagement", services: ["Amazon Connect"] },
  { title: "Database", services: ["Amazon Aurora", "Amazon DocumentDB", "Amazon DynamoDB", "Amazon DynamoDB Streams", "Amazon ElastiCache", "Amazon Neptune", "Amazon RDS"] },
  { title: "Developer Tools", services: ["AWS Amplify", "AWS CDK", "AWS CLI", "AWS CloudFormation", "AWS CodeArtifact", "AWS CodeBuild", "AWS CodeDeploy", "AWS CodePipeline", "Kiro", "AWS Tools and SDKs", "AWS X-Ray"] },
  { title: "Machine Learning", services: ["Amazon Augmented AI", "Amazon Bedrock", "Amazon Bedrock AgentCore", "Amazon Bedrock Knowledge Bases", "Amazon Bedrock Prompt Management", "Amazon Bedrock Prompt Flows", "Amazon Comprehend", "Amazon Comprehend Medical", "Amazon Kendra", "Amazon Lex", "Amazon Nova", "Amazon PartyRock", "Amazon Personalize", "Amazon Polly", "Amazon Q Business", "Amazon Q Business Apps", "Amazon Q Developer", "Amazon Quick", "Amazon Rekognition", "Amazon SageMaker AI", "Amazon SageMaker Clarify", "Amazon SageMaker Data Wrangler", "Amazon SageMaker Ground Truth", "Amazon SageMaker JumpStart", "Amazon SageMaker Model Monitor", "Amazon SageMaker Model Registry", "Amazon SageMaker Neo", "Amazon SageMaker Processing", "Amazon SageMaker Unified Studio", "Amazon Textract", "Amazon Titan", "Amazon Transcribe"] },
  { title: "Management and Governance", services: ["AWS Auto Scaling", "AWS Chatbot", "AWS CloudTrail", "Amazon CloudWatch", "Amazon CloudWatch Logs", "Amazon CloudWatch Synthetics", "AWS Cost Anomaly Detection", "AWS Cost Explorer", "Amazon Managed Grafana", "AWS Service Catalog", "AWS Systems Manager", "AWS Well-Architected Tool"] },
  { title: "Migration and Transfer", services: ["AWS DataSync", "AWS Transfer Family"] },
  { title: "Networking and Content Delivery", services: ["Amazon API Gateway", "AWS AppSync", "Amazon CloudFront", "Elastic Load Balancing (ELB)", "AWS Global Accelerator", "AWS PrivateLink", "Amazon Route 53", "Amazon VPC"] },
  { title: "Security, Identity, and Compliance", services: ["Amazon Cognito", "AWS Encryption SDK", "IAM", "IAM Access Analyzer", "IAM Identity Center", "AWS KMS", "Amazon Macie", "AWS Secrets Manager", "AWS WAF"] },
  { title: "Storage", services: ["Amazon EBS", "Amazon EFS", "Amazon S3", "Amazon S3 Intelligent-Tiering", "Amazon S3 Lifecycle policies", "Amazon S3 Cross-Region Replication"] },
];

export const guideAliases: Record<string, string> = {
  "AWS Shield Advanced": "AWS Shield Advanced",
  "AWS Private Certificate Authority": "AWS Private Certificate Authority",
  "VPC peering": "VPC peering",
  "Amazon EKS Distro": "Amazon EKS Distro",
  "VPC Reachability Analyzer": "VPC Reachability Analyzer",
  "Network ACLs": "Network ACLs",
  "AWS CloudTrail Lake": "AWS CloudTrail Lake",
  "Amazon Q Business Apps": "Amazon Q Business Apps",
  "Amazon CloudWatch Synthetics": "Amazon CloudWatch Synthetics",
  "AWS Fault Injection Simulator (AWS FIS)": "AWS Fault Injection Service",
  "AWS CloudFormation Guard": "AWS CloudFormation Guard",
  "AWS App Mesh": "AWS App Mesh",
  "Amazon EC2 security groups": "Amazon EC2 security groups",
  "Automated Forensics Orchestrator for Amazon EC2": "Automated Forensics Orchestrator for Amazon EC2",
  "Egress-only internet gateways": "Egress-only internet gateways",
  "Internet gateways": "Internet gateways",
  "NAT gateways": "NAT gateways",
  "AWS Network Access Analyzer": "AWS Network Access Analyzer",
  "Amazon MemoryDB for Redis": "Amazon MemoryDB for Redis",
  "Amazon CodeGuru Security": "Amazon CodeGuru Security",
  "Amazon Data Lifecycle Manager": "Amazon Data Lifecycle Manager",
  "Red Hat OpenShift Service on AWS (ROSA)": "Red Hat OpenShift Service on AWS (ROSA)",
  "AWS Serverless Application Model (AWS SAM)": "AWS SAM",
  "AWS SAM": "AWS SAM",
  "Elastic IP addresses": "Elastic IP Addresses",
  "Amazon VPC IP Address Manager (IPAM)": "Amazon VPC IP Address Manager (IPAM)",
  "Service control policies (SCPs)": "Service Control Policies",
  "Amazon Aurora Serverless v2": "Amazon Aurora Serverless v2",
  "AWS Strands Agents": "Strands Agents",
  "Migration Evaluator": "Migration Evaluator",
  "Amazon Simple Email Service (Amazon SES)": "Amazon SES",
  "Amazon SageMaker": "Amazon SageMaker AI",
  "AWS SDKs and Tools": "AWS Tools and SDKs",
  "AWS STS": "AWS Security Token Service",
  "Amazon Kinesis Data Firehose": "Amazon Data Firehose",
  "Amazon Managed Streaming for Apache Kafka (Amazon MSK)": "Amazon Managed Streaming for Apache Kafka",
  "Amazon QuickSight": "Amazon Quick Sight",
  "Amazon Quick Sight": "Amazon Quick Sight",
  "AWS Audit Manager": "Audit Manager",
  "AWS Systems Manager": "Systems Manager",
  "AWS Cost and Usage Report": "AWS Cost and Usage Reports",
  "Amazon EC2 Auto Scaling": "AWS Auto Scaling",
  "Amazon EKS Distro": "Amazon EKS",
  "Amazon Aurora Serverless": "Amazon Aurora Serverless",
  "Amazon AppStream 2.0": "Amazon AppStream 2.0",
  "Amazon CloudWatch Logs": "Amazon CloudWatch",
  "AWS Application Migration Service": "AWS Application Migration Service",
  "AWS DMS": "AWS Database Migration Service",
  "AWS Snow Family": "AWS Snowball Edge",
  "AWS VPN": "AWS Site-to-Site VPN",
  "AWS Resource Access Manager": "AWS Resource Access Manager (RAM)",
  "AWS Certificate Manager": "AWS Certificate Manager",
  "AWS Lambda@Edge": "AWS Lambda@Edge",
  "Amazon Connect": "Amazon Connect Customer",
  "Amazon DynamoDB Streams": "Amazon DynamoDB Streams",
  "Amazon Bedrock AgentCore": "Amazon Bedrock",
  "Amazon Bedrock Knowledge Bases": "Amazon Bedrock",
  "Amazon Bedrock Prompt Management": "Amazon Bedrock",
  "Amazon Bedrock Prompt Flows": "Amazon Bedrock",
  "Amazon Q Business Apps": "Amazon Q Business Apps",
  "Amazon SageMaker Clarify": "Amazon SageMaker AI",
  "Amazon SageMaker Data Wrangler": "Amazon SageMaker AI",
  "Amazon SageMaker Ground Truth": "Amazon SageMaker AI",
  "Amazon SageMaker JumpStart": "Amazon SageMaker AI",
  "Amazon SageMaker Model Monitor": "Amazon SageMaker AI",
  "Amazon SageMaker Model Registry": "Amazon SageMaker AI",
  "Amazon SageMaker Neo": "Amazon SageMaker AI",
  "Amazon SageMaker Processing": "Amazon SageMaker AI",
  "Amazon SageMaker Unified Studio": "Amazon SageMaker AI",
  "Amazon Titan": "Amazon Bedrock",
  "AWS Chatbot": "Amazon Q Developer in chat applications",
  "Amazon CloudWatch Synthetics": "Amazon CloudWatch Synthetics",
  "AWS Encryption SDK": "AWS KMS",
  "IAM": "AWS IAM",
  "IAM Identity Center": "AWS IAM Identity Center",
  "Amazon S3 Intelligent-Tiering": "Amazon S3",
  "Amazon S3 Lifecycle policies": "Amazon S3",
  "Amazon S3 Cross-Region Replication": "Amazon S3",
  "Elastic Load Balancing (ELB)": "Elastic Load Balancing",
  "AWS CodeStar": "AWS CodeStar (Legacy)",
};

export const pendingGuides = new Set([
]);
