/** Shared AWS service console images live directly under this prefix, never in task folders. */
export const AWS_CONSOLE_PREFIX="/aws-certification-walkthroughs";
export const normalizeConsoleService=(name:string)=>name.toLowerCase().replace(/\([^)]*\)/g,"").replace(/[^a-z0-9]+/g," ").trim();
export const awsConsoleAliases:Record<string,string>={
  "Amazon QuickSight": "amazon-quick-sight",
  "Amazon Quick Sight": "amazon-quick-sight",
  "Amazon Quick": "amazon-quick-sight",
  "Amazon Kinesis": "amazon-kinesis",
  "Amazon Kinesis Data Streams": "amazon-kinesis-data-streams",
  "Amazon Data Firehose": "amazon-data-firehose",
  "Amazon Managed Streaming for Apache Kafka (Amazon MSK)": "amazon-managed-streaming-for-apache-kafka",
  "Amazon Managed Streaming for Apache Kafka": "amazon-managed-streaming-for-apache-kafka",
  "AWS Marketplace": "aws-marketplace",
  "AWS Cost and Usage Reports": "aws-cost-and-usage-reports",
  "AWS Cost and Usage Report": "aws-cost-and-usage-report",
  "AWS Support": "aws-support",
  "AWS Audit Manager": "aws-audit-manager",
  "Audit Manager": "aws-audit-manager",
  "Amazon WorkSpaces Secure Browser": "amazon-workspaces-secure-browser",
  "Amazon Q": "amazon-q",
  "Service Quotas": "aws-service-quotas",
  "Migration Evaluator": "migration-evaluator",
  "AWS VPN": "aws-vpn",
  "AWS Identity and Access Management (IAM)": "iam",
  "AWS IAM": "iam",
  "IAM": "iam",
  "AWS IAM Identity Center": "aws-iam-identity-center",
  "IAM Identity Center": "aws-iam-identity-center",
  "AWS Key Management Service (AWS KMS)": "kms",
  "AWS KMS": "kms",
  "AWS Global Accelerator": "aws-global-accelerator",
  "AWS Auto Scaling": "aws-auto-scaling",
  "Amazon EC2 Auto Scaling": "amazon-ec2-auto-scaling",
  "Amazon Route 53": "amazon-route-53",
  "Route 53": "amazon-route-53",
  "AWS Serverless Application Repository": "aws-serverless-application-repository",
  "VMware Cloud on AWS": "vmware-cloud-on-aws",
  "AWS DMS": "aws-dms",
  "AWS Client VPN": "aws-client-vpn",
  "AWS Snow Family": "aws-snow-family",
  "Amazon SageMaker AI": "amazon-sagemaker-ai",
  "Amazon Elastic Container Registry (Amazon ECR)": "amazon-ecr",
  "Amazon Elastic Container Service (Amazon ECS)": "amazon-ecs",
  "Amazon Elastic Kubernetes Service (Amazon EKS)": "amazon-eks",
  "Amazon Elastic Block Store (Amazon EBS)": "amazon-ebs",
  "Amazon Elastic File System (Amazon EFS)": "amazon-efs",
  "AWS App Runner": "amazon-app-runner",
  "Amazon App Runner": "amazon-app-runner",
  "AWS HealthLake": "amazon-healthlake",
  "Amazon HealthLake": "amazon-healthlake",
  "Amazon FSx for NetApp ONTAP": "amazon-fsx-for-netapp",
  "Amazon MSK": "amazon-managed-streaming-for-apache-kafka",
  "Systems Manager": "aws-systems-manager",
  "AWS Health Dashboard": "aws-health",
  "CloudFormation StackSets": "aws-cloudformation-stacksets",
  "AWS Transform MGN": "aws-application-migration-service",
  "AWS Database Migration Service": "aws-dms",
  "Database Migration Service": "aws-dms",
  "AWS Migration Evaluator": "migration-evaluator",
  "Amazon Managed Workflows for Apache Airflow": "amazon-mwaa",
  "Amazon Aurora Serverless v2": "amazon-aurora-serverless",
  "Amazon MemoryDB for Redis": "amazon-memorydb",
  "Amazon DynamoDB Accelerator (DAX)": "amazon-dynamodb-accelerator",
  "AWS Private Certificate Authority": "aws-private-ca",
  "Amazon Q Business Apps": "amazon-q-business-apps",
  "AWS EC2": "amazon-ec2",
  "AWS S3": "amazon-s3",
  "AWS ECS": "amazon-ecs",
  "AWS EKS": "amazon-eks",
  "AWS ECR": "amazon-ecr",
  "AWS EBS": "amazon-ebs",
  "AWS EFS": "amazon-efs",
  "AWS GuardDuty": "amazon-guardduty",
  "GuardDuty": "amazon-guardduty",
  "AWS SecurityHub": "aws-security-hub",
  "Security Hub": "aws-security-hub",
  "AWS Inspector": "amazon-inspector",
  "AWS Macie": "amazon-macie",
  "AWS Route 53": "amazon-route-53",
  "AWS Kinesis": "amazon-kinesis",
  "AWS QuickSight": "amazon-quick-sight",
  "QuickSight": "amazon-quick-sight",
  "Amazon SageMaker": "amazon-sagemaker",
  "AWS SageMaker": "amazon-sagemaker-ai",
  "Amazon Elastic Compute Cloud (Amazon EC2)": "amazon-ec2",
  "Amazon Simple Storage Service (Amazon S3)": "amazon-s3",
  "Amazon Simple Queue Service (Amazon SQS)": "amazon-sqs",
  "Amazon Simple Notification Service (Amazon SNS)": "amazon-sns",
  "Amazon Simple Email Service (Amazon SES)": "amazon-ses",
  "Amazon Relational Database Service (Amazon RDS)": "amazon-rds"
};
export const observedAwsConsoleStems=[
  "amazon-s3",
  "amazon-sagemaker-ai",
  "amazon-sagemaker-canvas",
  "amazon-sagemaker-clarify",
  "amazon-sagemaker-data-wrangler",
  "amazon-sagemaker-experiments",
  "amazon-sagemaker-feature-store",
  "amazon-sagemaker-ground-truth",
  "amazon-sagemaker-inference-recommender",
  "amazon-sagemaker-jumpstart",
  "amazon-sagemaker-model-cards",
  "amazon-sagemaker-model-monitor",
  "amazon-sagemaker-model-registry",
  "amazon-sagemaker-neo",
  "amazon-sagemaker-pipelines",
  "amazon-sagemaker-studio-lab",
  "amazon-sagemaker",
  "amazon-ses",
  "amazon-sns",
  "amazon-sqs",
  "amazon-textract",
  "amazon-timestream",
  "amazon-transcribe",
  "amazon-translate",
  "amazon-vpc-lattice",
  "amazon-api-gateway",
  "amazon-app-runner",
  "amazon-appflow",
  "amazon-appstream-2-0",
  "amazon-athena",
  "amazon-augmented-ai",
  "amazon-aurora-serverless",
  "amazon-aurora",
  "amazon-bedrock",
  "amazon-braket",
  "amazon-cloudfront",
  "amazon-cloudwatch-application-signals",
  "amazon-cloudwatch-internet-monitor",
  "amazon-cloudwatch-logs",
  "amazon-cloudwatch-rum",
  "amazon-cloudwatch-synthetics",
  "amazon-cloudwatch",
  "amazon-codeguru-security",
  "amazon-codeguru",
  "amazon-cognito",
  "amazon-comprehend-medical",
  "amazon-comprehend",
  "amazon-connect",
  "amazon-data-firehose",
  "amazon-detective",
  "amazon-documentdb",
  "amazon-dynamodb",
  "amazon-ebs",
  "amazon-ec2-auto-scaling",
  "amazon-ec2",
  "amazon-ecr",
  "amazon-ecs-anywhere",
  "amazon-ecs",
  "amazon-efs",
  "amazon-eks-anywhere",
  "amazon-eks-distro",
  "amazon-eks",
  "amazon-elastic-transcoder",
  "amazon-elasticache",
  "amazon-emr",
  "amazon-eventbridge",
  "amazon-forecast",
  "amazon-fraud-detector",
  "amazon-fsx-for-lustre",
  "amazon-fsx-for-netapp",
  "amazon-fsx-for-openzfs",
  "amazon-fsx-for-windows-file-server",
  "amazon-fsx",
  "amazon-guardduty",
  "amazon-healthlake",
  "amazon-inspector",
  "amazon-kendra",
  "amazon-keyspaces",
  "amazon-kinesis-data-analytics",
  "amazon-kinesis-data-streams",
  "amazon-kinesis-video-streams",
  "amazon-kinesis",
  "amazon-lex",
  "amazon-lightsail",
  "amazon-lookout-for-equipment",
  "amazon-lookout-for-metrics",
  "amazon-lookout-for-vision",
  "amazon-macie",
  "amazon-managed-blockchain",
  "amazon-managed-grafana",
  "amazon-managed-service-for-apache-flink",
  "amazon-managed-service-for-prometheus",
  "amazon-managed-streaming-for-apache-kafka",
  "amazon-mq",
  "amazon-msk",
  "amazon-neptune",
  "amazon-nova",
  "amazon-omics",
  "amazon-opensearch-ingestion",
  "amazon-opensearch-serverless",
  "amazon-opensearch-service",
  "amazon-partyrock",
  "amazon-personalize",
  "amazon-pinpoint",
  "amazon-polly",
  "amazon-q-business",
  "amazon-q-developer",
  "amazon-q-in-connect",
  "amazon-q",
  "amazon-quick-sight",
  "amazon-quicksight",
  "amazon-rds",
  "amazon-redshift",
  "amazon-rekognition",
  "amazon-route-53",
  "amazon-s3-access-points",
  "amazon-s3-cross-region-replication",
  "amazon-s3-glacier-deep-archive",
  "amazon-s3-glacier",
  "amazon-s3-intelligent-tiering",
  "amazon-s3-lifecycle-policies",
  "amazon-s3-object-lambda"
] as const;
const variants:Record<string,string[]>={
  "amazon-quick-sight": [
    "amazon-quicksight"
  ],
  "amazon-managed-streaming-for-apache-kafka": [
    "amazon-msk"
  ],
  "amazon-ec2-auto-scaling": [
    "aws-auto-scaling"
  ],
  "amazon-aurora-serverless": [
    "amazon-aurora-serverless-v2"
  ],
  "amazon-memorydb": [
    "amazon-memorydb-for-redis"
  ],
  "aws-application-migration-service": [
    "aws-transform-mgn"
  ],
  "aws-dms": [
    "aws-database-migration-service"
  ],
  "aws-private-ca": [
    "aws-private-certificate-authority"
  ]
};
const aliasesByName=Object.fromEntries(Object.entries(awsConsoleAliases).map(([name,stem])=>[normalizeConsoleService(name),stem]));
export function awsConsoleStem(name:string){return awsConsoleAliases[name]||aliasesByName[normalizeConsoleService(name)]||normalizeConsoleService(name).replace(/\s+/g,"-")}
export function awsConsoleStems(name:string){
 const primary=awsConsoleStem(name),literal=normalizeConsoleService(name).replace(/\s+/g,"-");
 // These are same-service alternatives, not unrelated course/task images.
 return [...new Set([primary,...(variants[primary]||[]),literal])];
}
export function awsConsolePath(name:string){return `${AWS_CONSOLE_PREFIX}/${awsConsoleStem(name)}.webp`}
