export const AWS_ICON_ROOT = "/aws-icons";
export const AWS_ICON_FALLBACK_ROOT = "https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v23.0/dist";
export type AwsArchitectureIcon={id:string;name:string;category:string;file:string;aliases?:string[]};
export const awsArchitectureIcons:Record<string,AwsArchitectureIcon>={
awsCloud:{id:"aws-cloud",name:"AWS Cloud",category:"General",file:"General/AWSCloud.png",aliases:["AWS","AWS service","cloud"]},user:{id:"user",name:"User",category:"General",file:"General/User.png",aliases:["analyst","customer","client","producer","consumer"]},
athena:{id:"athena",name:"Amazon Athena",category:"Analytics",file:"Analytics/Athena.png",aliases:["Athena"]},glueDataCatalog:{id:"glue-data-catalog",name:"AWS Glue Data Catalog",category:"Analytics",file:"Analytics/GlueDataCatalog.png",aliases:["Glue Catalog","Data Catalog"]},glue:{id:"glue",name:"AWS Glue",category:"Analytics",file:"Analytics/Glue.png",aliases:["Glue","ETL"]},emr:{id:"emr",name:"Amazon EMR",category:"Analytics",file:"Analytics/EMR.png",aliases:["EMR"]},kinesis:{id:"kinesis",name:"Amazon Kinesis Data Streams",category:"Analytics",file:"Analytics/KinesisDataStreams.png",aliases:["Amazon Kinesis","Kinesis","KDS"]},opensearch:{id:"opensearch",name:"Amazon OpenSearch Service",category:"Analytics",file:"Analytics/OpenSearchService.png",aliases:["OpenSearch"]},quicksight:{id:"quicksight",name:"Amazon QuickSight",category:"Analytics",file:"Analytics/QuickSight.png",aliases:["Amazon Quick Sight","QuickSight"]},msk:{id:"msk",name:"Amazon Managed Streaming for Apache Kafka",category:"Analytics",file:"Analytics/ManagedStreamingForApacheKafka.png",aliases:["Amazon MSK","MSK"]},
lambda:{id:"lambda",name:"AWS Lambda",category:"Compute",file:"Compute/Lambda.png",aliases:["Lambda","AWS Lambda@Edge","Lambda@Edge"]},ec2:{id:"ec2",name:"Amazon EC2",category:"Compute",file:"Compute/EC2.png",aliases:["EC2"]},
s3:{id:"s3",name:"Amazon S3",category:"Storage",file:"Storage/SimpleStorageService.png",aliases:["S3"]},rds:{id:"rds",name:"Amazon RDS",category:"Database",file:"Database/RDS.png",aliases:["RDS"]},dynamodb:{id:"dynamodb",name:"Amazon DynamoDB",category:"Database",file:"Database/DynamoDB.png",aliases:["DynamoDB"]},
apiGateway:{id:"api-gateway",name:"Amazon API Gateway",category:"NetworkingContentDelivery",file:"NetworkingContentDelivery/APIGateway.png",aliases:["API Gateway"]},cloudfront:{id:"cloudfront",name:"Amazon CloudFront",category:"NetworkingContentDelivery",file:"NetworkingContentDelivery/CloudFront.png",aliases:["CloudFront"]},route53:{id:"route53",name:"Amazon Route 53",category:"NetworkingContentDelivery",file:"NetworkingContentDelivery/Route53.png",aliases:["Route 53"]},
sqs:{id:"sqs",name:"Amazon SQS",category:"ApplicationIntegration",file:"ApplicationIntegration/SimpleQueueService.png",aliases:["SQS"]},sns:{id:"sns",name:"Amazon SNS",category:"ApplicationIntegration",file:"ApplicationIntegration/SimpleNotificationService.png",aliases:["SNS"]},eventbridge:{id:"eventbridge",name:"Amazon EventBridge",category:"ApplicationIntegration",file:"ApplicationIntegration/EventBridge.png",aliases:["EventBridge"]},stepFunctions:{id:"step-functions",name:"AWS Step Functions",category:"ApplicationIntegration",file:"ApplicationIntegration/StepFunctions.png",aliases:["Step Functions"]},
bedrock:{id:"bedrock",name:"Amazon Bedrock",category:"MachineLearning",file:"MachineLearning/Bedrock.png",aliases:["Bedrock","Amazon Bedrock AgentCore","Amazon Bedrock Knowledge Bases","Amazon Bedrock Prompt Management","Amazon Bedrock Prompt Flows"]},sagemaker:{id:"sagemaker",name:"Amazon SageMaker AI",category:"MachineLearning",file:"MachineLearning/SageMaker.png",aliases:["Amazon SageMaker","SageMaker","Amazon SageMaker Clarify","Amazon SageMaker Data Wrangler","Amazon SageMaker Ground Truth","Amazon SageMaker JumpStart","Amazon SageMaker Model Monitor","Amazon SageMaker Model Registry","Amazon SageMaker Neo","Amazon SageMaker Processing","Amazon SageMaker Unified Studio"]},
ecr:{id:"ecr",name:"Amazon ECR",category:"Containers",file:"Containers/ElasticContainerRegistry.png",aliases:["ECR"]},ecs:{id:"ecs",name:"Amazon ECS",category:"Containers",file:"Containers/ElasticContainerService.png",aliases:["ECS"]},eks:{id:"eks",name:"Amazon EKS",category:"Containers",file:"Containers/ElasticKubernetesService.png",aliases:["EKS"]},fargate:{id:"fargate",name:"AWS Fargate",category:"Containers",file:"Containers/Fargate.png",aliases:["Fargate"]},
waf:{id:"waf",name:"AWS WAF",category:"SecurityIdentityCompliance",file:"SecurityIdentityCompliance/WAF.png",aliases:["WAF"]},kms:{id:"kms",name:"AWS KMS",category:"SecurityIdentityCompliance",file:"SecurityIdentityCompliance/KeyManagementService.png",aliases:["KMS"]},secrets:{id:"secrets",name:"AWS Secrets Manager",category:"SecurityIdentityCompliance",file:"SecurityIdentityCompliance/SecretsManager.png",aliases:["Secrets Manager"]},cognito:{id:"cognito",name:"Amazon Cognito",category:"SecurityIdentityCompliance",file:"SecurityIdentityCompliance/Cognito.png",aliases:["Cognito"]}
};
export const awsIconSrc=(icon:AwsArchitectureIcon)=>`${AWS_ICON_ROOT}/${icon.file}`;
export const awsIconFallbackSrc=(icon:AwsArchitectureIcon)=>`${AWS_ICON_FALLBACK_ROOT}/${icon.file}`;
export function findAwsArchitectureIcon(value:string){const q=value.trim().toLowerCase();return Object.values(awsArchitectureIcons).find(icon=>icon.id===q||icon.name.toLowerCase()===q||icon.aliases?.some(alias=>alias.toLowerCase()===q));}
