export const AWS_ICON_ROOT = "/aws-icons";
export const AWS_ICON_FALLBACK_ROOT = "https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/main/dist";
export type AwsArchitectureIcon={id:string;name:string;category:string;file:string;aliases?:string[]};
const icon=(id:string,name:string,category:string,file:string,aliases:string[]=[]):AwsArchitectureIcon=>({id,name,category,file,aliases});
export const awsArchitectureIcons:Record<string,AwsArchitectureIcon>={
awsCloud:icon("aws-cloud","AWS Cloud","General","General/AWSCloud.png",["AWS","AWS service","cloud"]),
user:icon("user","User","General","General/User.png",["analyst","customer","client","producer","consumer"]),
athena:icon("athena","Amazon Athena","Analytics","Analytics/Athena.png",["Athena"]),
glueDataCatalog:icon("glue-data-catalog","AWS Glue Data Catalog","Analytics","Analytics/GlueDataCatalog.png",["Glue Catalog","Data Catalog"]),
glue:icon("glue","AWS Glue","Analytics","Analytics/Glue.png",["Glue","ETL"]),
emr:icon("emr","Amazon EMR","Analytics","Analytics/EMR.png",["EMR"]),
kinesis:icon("kinesis","Amazon Kinesis Data Streams","Analytics","Analytics/KinesisDataStreams.png",["Amazon Kinesis","Kinesis","KDS"]),
opensearch:icon("opensearch","Amazon OpenSearch Service","Analytics","Analytics/OpenSearchService.png",["OpenSearch"]),
quicksight:icon("quicksight","Amazon QuickSight","Analytics","Analytics/QuickSight.png",["Amazon Quick Sight","QuickSight"]),
msk:icon("msk","Amazon Managed Streaming for Apache Kafka","Analytics","Analytics/ManagedStreamingForApacheKafka.png",["Amazon MSK","MSK","Amazon Managed Streaming for Apache Kafka (Amazon MSK)"]),
lambda:icon("lambda","AWS Lambda","Compute","Compute/Lambda.png",["Lambda","AWS Lambda@Edge","Lambda@Edge"]),
ec2:icon("ec2","Amazon EC2","Compute","Compute/EC2.png",["EC2"]),
appRunner:icon("app-runner","AWS App Runner","Compute","Compute/AppRunner.png"),
outposts:icon("outposts","AWS Outposts","Compute","Compute/Outposts.png"),
wavelength:icon("wavelength","AWS Wavelength","Compute","Compute/Wavelength.png"),
s3:icon("s3","Amazon S3","Storage","Storage/SimpleStorageService.png",["S3","Amazon S3 Intelligent-Tiering","Amazon S3 Lifecycle policies","Amazon S3 Cross-Region Replication"]),
ebs:icon("ebs","Amazon EBS","Storage","Storage/ElasticBlockStore.png",["EBS"]),
efs:icon("efs","Amazon EFS","Storage","Storage/ElasticFileSystem.png",["EFS"]),
rds:icon("rds","Amazon RDS","Database","Database/RDS.png",["RDS"]),
aurora:icon("aurora","Amazon Aurora","Database","Database/Aurora.png"),
documentdb:icon("documentdb","Amazon DocumentDB","Database","Database/DocumentDB.png"),
dynamodb:icon("dynamodb","Amazon DynamoDB","Database","Database/DynamoDB.png",["DynamoDB","Amazon DynamoDB Streams"]),
elasticache:icon("elasticache","Amazon ElastiCache","Database","Database/ElastiCache.png"),
neptune:icon("neptune","Amazon Neptune","Database","Database/Neptune.png"),
apiGateway:icon("api-gateway","Amazon API Gateway","NetworkingContentDelivery","NetworkingContentDelivery/APIGateway.png",["API Gateway"]),
cloudfront:icon("cloudfront","Amazon CloudFront","NetworkingContentDelivery","NetworkingContentDelivery/CloudFront.png",["CloudFront"]),
route53:icon("route53","Amazon Route 53","NetworkingContentDelivery","NetworkingContentDelivery/Route53.png",["Route 53"]),
vpc:icon("vpc","Amazon VPC","NetworkingContentDelivery","NetworkingContentDelivery/VPC.png",["VPC"]),
elb:icon("elb","Elastic Load Balancing","NetworkingContentDelivery","NetworkingContentDelivery/ElasticLoadBalancing.png",["ELB","Elastic Load Balancing (ELB)"]),
globalAccelerator:icon("global-accelerator","AWS Global Accelerator","NetworkingContentDelivery","NetworkingContentDelivery/GlobalAccelerator.png"),
privateLink:icon("privatelink","AWS PrivateLink","NetworkingContentDelivery","NetworkingContentDelivery/PrivateLink.png"),
appsync:icon("appsync","AWS AppSync","NetworkingContentDelivery","NetworkingContentDelivery/AppSync.png"),
sqs:icon("sqs","Amazon SQS","ApplicationIntegration","ApplicationIntegration/SimpleQueueService.png",["SQS"]),
sns:icon("sns","Amazon SNS","ApplicationIntegration","ApplicationIntegration/SimpleNotificationService.png",["SNS"]),
eventbridge:icon("eventbridge","Amazon EventBridge","ApplicationIntegration","ApplicationIntegration/EventBridge.png",["EventBridge"]),
stepFunctions:icon("step-functions","AWS Step Functions","ApplicationIntegration","ApplicationIntegration/StepFunctions.png",["Step Functions"]),
appflow:icon("appflow","Amazon AppFlow","ApplicationIntegration","ApplicationIntegration/AppFlow.png"),
appconfig:icon("appconfig","AWS AppConfig","ManagementGovernance","ManagementGovernance/AppConfig.png"),
bedrock:icon("bedrock","Amazon Bedrock","ArtificialIntelligence","ArtificialIntelligence/Bedrock.png",["Bedrock","Amazon Bedrock AgentCore","Amazon Bedrock Knowledge Bases","Amazon Bedrock Prompt Management","Amazon Bedrock Prompt Flows","Amazon Titan"]),
sagemaker:icon("sagemaker","Amazon SageMaker AI","ArtificialIntelligence","ArtificialIntelligence/SageMaker.png",["Amazon SageMaker","SageMaker","Amazon SageMaker Clarify","Amazon SageMaker Data Wrangler","Amazon SageMaker Ground Truth","Amazon SageMaker JumpStart","Amazon SageMaker Model Monitor","Amazon SageMaker Model Registry","Amazon SageMaker Neo","Amazon SageMaker Processing","Amazon SageMaker Unified Studio"]),
comprehend:icon("comprehend","Amazon Comprehend","ArtificialIntelligence","ArtificialIntelligence/Comprehend.png",["Amazon Comprehend Medical"]),
kendra:icon("kendra","Amazon Kendra","ArtificialIntelligence","ArtificialIntelligence/Kendra.png"),
lex:icon("lex","Amazon Lex","ArtificialIntelligence","ArtificialIntelligence/Lex.png"),
personalize:icon("personalize","Amazon Personalize","ArtificialIntelligence","ArtificialIntelligence/Personalize.png"),
polly:icon("polly","Amazon Polly","ArtificialIntelligence","ArtificialIntelligence/Polly.png"),
rekognition:icon("rekognition","Amazon Rekognition","ArtificialIntelligence","ArtificialIntelligence/Rekognition.png"),
textract:icon("textract","Amazon Textract","ArtificialIntelligence","ArtificialIntelligence/Textract.png"),
transcribe:icon("transcribe","Amazon Transcribe","ArtificialIntelligence","ArtificialIntelligence/Transcribe.png"),
ecr:icon("ecr","Amazon ECR","Containers","Containers/ElasticContainerRegistry.png",["ECR"]),
ecs:icon("ecs","Amazon ECS","Containers","Containers/ElasticContainerService.png",["ECS"]),
eks:icon("eks","Amazon EKS","Containers","Containers/ElasticKubernetesService.png",["EKS"]),
fargate:icon("fargate","AWS Fargate","Containers","Containers/Fargate.png",["Fargate"]),
connect:icon("connect","Amazon Connect","CustomerExperience","CustomerExperience/Connect.png",["Amazon Connect Customer"]),
cloudFormation:icon("cloudformation","AWS CloudFormation","ManagementGovernance","ManagementGovernance/CloudFormation.png"),
cloudTrail:icon("cloudtrail","AWS CloudTrail","ManagementGovernance","ManagementGovernance/CloudTrail.png"),
cloudWatch:icon("cloudwatch","Amazon CloudWatch","ManagementGovernance","ManagementGovernance/CloudWatch.png",["Amazon CloudWatch Logs","Amazon CloudWatch Synthetics"]),
systemsManager:icon("systems-manager","AWS Systems Manager","ManagementGovernance","ManagementGovernance/SystemsManager.png"),
serviceCatalog:icon("service-catalog","AWS Service Catalog","ManagementGovernance","ManagementGovernance/ServiceCatalog.png"),
cli:icon("cli","AWS CLI","DeveloperTools","DeveloperTools/CommandLineInterface.png",["Command Line Interface"]),
cdk:icon("cdk","AWS CDK","DeveloperTools","DeveloperTools/CloudDevelopmentKit.png"),
codeArtifact:icon("codeartifact","AWS CodeArtifact","DeveloperTools","DeveloperTools/CodeArtifact.png"),
codeBuild:icon("codebuild","AWS CodeBuild","DeveloperTools","DeveloperTools/CodeBuild.png"),
codeDeploy:icon("codedeploy","AWS CodeDeploy","DeveloperTools","DeveloperTools/CodeDeploy.png"),
codePipeline:icon("codepipeline","AWS CodePipeline","DeveloperTools","DeveloperTools/CodePipeline.png"),
xray:icon("xray","AWS X-Ray","DeveloperTools","DeveloperTools/XRay.png"),
dataSync:icon("datasync","AWS DataSync","MigrationModernization","MigrationModernization/DataSync.png"),
transferFamily:icon("transfer-family","AWS Transfer Family","MigrationModernization","MigrationModernization/TransferFamily.png"),
waf:icon("waf","AWS WAF","SecurityIdentityCompliance","SecurityIdentityCompliance/WAF.png",["WAF"]),
kms:icon("kms","AWS KMS","SecurityIdentityCompliance","SecurityIdentityCompliance/KeyManagementService.png",["KMS","AWS Encryption SDK"]),
secrets:icon("secrets","AWS Secrets Manager","SecurityIdentityCompliance","SecurityIdentityCompliance/SecretsManager.png",["Secrets Manager"]),
cognito:icon("cognito","Amazon Cognito","SecurityIdentityCompliance","SecurityIdentityCompliance/Cognito.png",["Cognito"]),
iam:icon("iam","AWS IAM","SecurityIdentityCompliance","SecurityIdentityCompliance/IdentityAndAccessManagement.png",["IAM","IAM Access Analyzer","IAM Identity Center"]),
macie:icon("macie","Amazon Macie","SecurityIdentityCompliance","SecurityIdentityCompliance/Macie.png")
};
export const awsIconSrc=(icon:AwsArchitectureIcon)=>`${AWS_ICON_ROOT}/${icon.file}`;
export const awsIconFallbackSrc=(icon:AwsArchitectureIcon)=>`${AWS_ICON_FALLBACK_ROOT}/${icon.file}`;
export function findAwsArchitectureIcon(value:string){const q=value.trim().toLowerCase();return Object.values(awsArchitectureIcons).find(icon=>icon.id===q||icon.name.toLowerCase()===q||icon.aliases?.some(alias=>alias.toLowerCase()===q));}
