import {n,l,a} from "./reviewed-architecture-builders";
import type {ReviewedArchitecture} from "./reviewed-workload-architectures";
const engine=a("GCP: release a customer API as an App Engine version","A tested version is deployed and traffic is deliberately migrated after application checks.","https://docs.cloud.google.com/appengine/docs/an-overview-of-app-engine",
 l("Build",n("Customer API release pipeline","Reviewed source and environment definition","The pipeline tests the customer API and builds the selected supported App Engine environment/runtime configuration. Service identity, data access and scaling settings are reviewed for the actual deployment rather than assumed from local tests.","app")),
 l("Version",n("App Engine","Deploy version and manage configured traffic","App Engine deploys the selected version and runs it under its configured environment and scaling behavior. The owner checks version readiness before changing traffic and respects the supported splitting/session behavior rather than assuming a deployment instantly replaces every request.")),
 l("Accept",n("Customer API release owner","Exercise authenticated endpoint and rollback route","The owner tests the customer request and data permissions against the new version, then migrates traffic under the approved release policy. The previous version and data compatibility support the chosen rollback procedure.","user")));
const batch=a("GCP: run parallel document conversions as Batch tasks","Batch provisions the configured task capacity; task containers read selected inputs and publish idempotent outputs.","https://docs.cloud.google.com/batch/docs/get-started",
 l("Submit",n("Document Batch submitter","Reviewed task spec and input partitions","The submitter validates the completed document inputs and submits the task group, resource requirements and service account. Each task receives a deterministic input/output identity and the runtime role permits only the required object access.","app")),
 l("Schedule",n("Batch","Provision capacity and schedule task group","Batch schedules the configured tasks onto the selected supported compute resources with the chosen allocation, retry and timeout settings. The scheduler coordinates execution; document parsing and conversion are performed by the task code.")),
 l("Convert",n("Conversion task container","Read original and publish validated output","The task reads its assigned original, checks the supported format and writes a validated result under its run identity. Failed/repeated task attempts do not expose a partial output as completed work, and aggregate acceptance checks confirm all required results.","app")));
const mesh=a("GCP: secure communication between order and inventory workloads","Mesh proxies apply the configured workload-to-workload traffic and identity policies while application code owns the business operation.","https://docs.cloud.google.com/service-mesh/docs/overview",
 l("Call",n("Order service workload","Authorized inventory operation and bounded retry","The order service sends the selected inventory request with its application-level transaction identity. Its configured service discovery and mesh interception path are verified; retries do not blindly repeat a non-idempotent stock reservation.","app")),
 l("Mesh policy",n("Cloud Service Mesh","Workload identity, mTLS and traffic policy","The configured data-plane proxies enforce the selected mutual TLS, authorization and traffic policies between these workloads under the supported mesh deployment. The control plane distributes configuration; it is not an inline executor of the inventory request.")),
 l("Serve",n("Inventory service workload","Validate stock scope and commit mutation","The inventory service validates the caller's application permission and requested warehouse operation, then commits the stock change idempotently. Mesh identity secures the service connection but does not replace record-level stock authorization.","app")));
const directory=a("GCP: discover a private supplier-service endpoint","Service Directory holds registered endpoint metadata; the client resolves and connects through its separately configured network path.","https://docs.cloud.google.com/service-directory/docs/overview",
 l("Register",n("Supplier service deployment","Approved endpoint and namespace registration","The deployment registers the supplier endpoint in the selected namespace/service with its reviewed address, port and metadata. Registration updates reflect actual rollout and removal; listing an address does not prove its listener is healthy.","app")),
 l("Discover",n("Service Directory","Authorized endpoint lookup and metadata","The client uses the permitted API or configured DNS integration to resolve the registered service endpoints. Discovery supplies addressing information rather than proxying the business request; IAM and DNS integration are configured explicitly.")),
 l("Connect",n("Supplier-service client","Permitted network and authenticated API request","The client connects directly to the chosen endpoint through the approved route/firewall path and verifies the supplier API identity. It handles stale endpoint information and failures with bounded retries rather than treating registration as a live health guarantee.","app")));
const vm=a("GCP: patch a private application VM under a maintenance policy","VM Manager uses configured guest management prerequisites to assess and install updates; the owner validates the application after patching.","https://docs.cloud.google.com/compute/vm-manager/docs",
 l("Select fleet",n("Application VM maintenance owner","Guest agent, OS support and patch scope","The owner verifies supported guests and management-agent prerequisites, selects the fleet and schedules the approved maintenance window. Application draining, reboot policy and a tested recovery path are included in the plan.","user")),
 l("Manage guest",n("VM Manager","Configured patch operation and per-VM evidence","The selected patch job assesses and installs the configured supported OS updates on eligible VMs. The operator checks per-machine status and guest prerequisites, and distinguishes patch-management operations from separate OS policy assignments.")),
 l("Verify",n("Application fleet validator","Guest update result and live service test","The owner confirms required package versions and reboot outcomes, then tests the private application path before returning each instance to service. Failed machines follow the approved repair or rollback process rather than being accepted solely because a job started.","user")));
const infra=a("GCP: provision a private API environment from reviewed Terraform","Infrastructure Manager executes the selected deployment configuration under a restricted identity; the owner reviews plan and resource results.","https://docs.cloud.google.com/infrastructure-manager/docs/overview",
 l("Review",n("Private API infrastructure author","Versioned Terraform and parameter scope","The author reviews the network, runtime and data-access definitions and selected deployment parameters. Source identity, provider configuration and secret references are controlled, and destructive changes receive the intended review.","user")),
 l("Execute",n("Infra Manager","Supported Terraform deployment and resource changes","The service runs the supported Terraform deployment under its configured service account and selected source configuration. The owner checks preview/plan behavior and deployment results; provisioning is a control-plane operation, not a customer request processor.")),
 l("Accept",n("Private API platform owner","Verify effective permissions and request path","The owner checks the created network/runtime resources and exercises the authenticated private API and data path. Resource creation success is reconciled with actual readiness and rollback expectations before handing the environment to the application team.","user")));
const assets=a("GCP: audit which projects expose a sensitive storage resource","Cloud Asset Inventory provides scoped asset evidence for a policy investigation; effective access is verified separately.","https://docs.cloud.google.com/asset-inventory/docs/overview",
 l("Scope",n("Cloud governance analyst","Permitted organization and resource query","The analyst defines the permitted organization/project scope and sensitive-resource question and selects the supported inventory/search/export method. The inventory time and available asset types are recorded for the review.","user")),
 l("Inventory",n("Cloud Asset Inventory","Resource and policy metadata evidence","The service returns the supported asset and policy metadata for the authorized scope under its selected history/search behavior. The result identifies configuration to review; it does not prove that every hypothetical API call would succeed or reveal all workload data.")),
 l("Validate",n("Sensitive-resource policy reviewer","Check effective access and approve repair","The reviewer examines the relevant policy bindings and service configuration, confirms the intended access boundary and approves changes. Live permission checks and follow-up inventory verify the repair without inferring customer-data ownership solely from a resource listing.","user")));
const recommender=a("GCP: test a VM rightsizing recommendation against warehouse load","The recommendation informs a reviewed capacity change; measured peak behavior governs acceptance.","https://docs.cloud.google.com/recommender/docs/overview",
 l("Observe",n("Warehouse VM capacity evidence","Representative utilization and workload interval","The owner checks the relevant machine usage interval, peak transactions and recovery requirements. Low average use is interpreted alongside seasonal load and dependency constraints before selecting a possible smaller configuration.","data")),
 l("Recommend",n("Recommender","Supported rightsizing insight and proposed change","The applicable recommender provides its supported insight and recommendation for the selected resource. Permissions, recommendation state and observed scope are checked; an optimization proposal is not an automatic guarantee of warehouse response time.")),
 l("Validate",n("Warehouse platform owner","Load test, approve and measure outcome","The owner tests the proposed machine shape under representative peak stock requests, approves any change and measures service health and savings. The rollback configuration is retained until the change satisfies the agreed capacity requirements.","user")));
const errors=a("GCP: group document-worker exceptions for incident triage","Error Reporting groups supported reported exceptions; the engineer checks the affected execution and fixes the actual application error.","https://docs.cloud.google.com/error-reporting/docs",
 l("Report",n("Document worker exception emitter","Supported exception and request identity","The worker emits its selected supported exception format through the configured logging or reporting integration without including secret or document contents. The request/run identifier allows correlation with durable processing status.","app")),
 l("Group",n("Error Reporting","Group supported exceptions and expose occurrence context","The service groups eligible reported errors and presents occurrence information under the configured project and access scope. Grouping highlights repeated exceptions; it does not retry jobs, repair the code or prove all failures are represented.")),
 l("Repair",n("Document on-call engineer","Reproduce, fix and replay approved failed work","The engineer correlates the error group with the affected run and input, reproduces the issue and deploys the reviewed fix. Failed work is replayed under its idempotency design only after checking whether an earlier attempt committed output.","user")));
const profiler=a("GCP: locate a CPU hotspot in the document conversion worker","Profiler samples the supported runtime; the engineer tests an optimization against representative inputs.","https://docs.cloud.google.com/profiler/docs/about-profiler",
 l("Sample",n("Instrumented document worker","Supported agent and representative conversion load","The worker runs the configured supported profiler agent during representative conversions under the required permissions. Sampling scope and overhead are reviewed, and sensitive document data is excluded from diagnostic labels.","app")),
 l("Analyze",n("Profiler","Aggregate sampled stack/resource profiles","Profiler collects and presents supported sampled profiles for the selected service/version interval. The engineer identifies the expensive conversion stack and considers sampling limitations; a profile is resource-use evidence rather than a trace of every request's business result.")),
 l("Optimize",n("Conversion performance engineer","Benchmark change and verify output correctness","The engineer changes the suspected hotspot, benchmarks representative document formats and validates the converted outputs before release. New profiles and end-to-end latency tests confirm the improvement without trading correctness for a lower CPU sample.","user")));
export const reviewedScale10:Record<string,ReviewedArchitecture[]>={
 "App Engine":[engine],"Batch":[batch],"Cloud Service Mesh":[mesh],"Service Directory":[directory],"VM Manager":[vm],
 "Infra Manager":[infra],"Cloud Asset Inventory":[assets],"Recommender":[recommender],"Error Reporting":[errors],"Profiler":[profiler]
};
