import {n,l,a} from "./reviewed-architecture-builders";
import type {ReviewedArchitecture} from "./reviewed-workload-architectures";
const interconnect=a("GCP: reach a private warehouse service over Interconnect","A selected VLAN attachment and BGP route path connect the corporate network to the private application.","https://docs.cloud.google.com/network-connectivity/docs/interconnect/concepts/overview",
 l("Corporate edge",n("Corporate Interconnect router","Redundant connectivity and selected prefixes","The corporate router establishes the configured provider/dedicated path and BGP routing for the approved prefixes. The availability design uses the required redundant connections; application TLS or configured additional encryption protects sensitive warehouse requests.","app")),
 l("Private connectivity",n("Cloud Interconnect","VLAN attachment to the chosen VPC","The selected attachment supplies private connectivity between the corporate network and Google Cloud. Cloud Router manages the configured route exchange; packets use the Interconnect/VPC data path rather than traversing Cloud Router as an application proxy.")),
 l("Route control",n("Interconnect Cloud Router","BGP advertisements and accepted routes","The router's BGP sessions learn approved corporate prefixes and advertise the configured VPC reachability. The operator checks effective routes and return routing, while firewall and application permissions still restrict the actual warehouse request.",undefined,"Cloud Router")));
const ncc=a("GCP: connect approved corporate sites through NCC routing","The hub coordinates supported spokes and route exchange; the configured spoke data paths carry application traffic.","https://docs.cloud.google.com/network-connectivity/docs/network-connectivity-center/concepts/overview",
 l("Spokes",n("Corporate connectivity spokes","Selected VPN or attachment resources","The network owner registers the intended supported spokes and their connectivity resources under the hub. Each spoke's underlying tunnel or attachment and routing are configured independently, with approved prefixes and site isolation.","app")),
 l("Hub configuration",n("Network Connectivity Center (NCC)","Supported spoke connectivity and route policy","NCC coordinates the supported hub/spoke connectivity and route exchange under the selected topology and settings. It is not a generic application gateway; traffic uses the configured networking resources, and propagation is verified rather than assumed across every spoke.")),
 l("Validate",n("Corporate network owner","Test intended site and application paths","The owner checks the effective advertisements and tests permitted site-to-application reachability and prohibited site access. Private connectivity remains subject to firewall and application authorization at the warehouse service.","user")));
const vpc=a("GCP: restrict warehouse backends to approved private callers","The VPC routes and firewall policy constrain access, while the application authenticates and authorizes stock operations.","https://docs.cloud.google.com/vpc/docs/overview",
 l("Source",n("Warehouse caller subnet","Approved source identity and private destination","The corporate workload uses the selected private destination and configured route to the warehouse backend. The network owner verifies the intended source ranges or service-account-based rule targets for the chosen firewall design.","app")),
 l("Network",n("Virtual Private Cloud (VPC)","Regional subnets, global network and firewall scope","The VPC supplies the configured subnets and routing and applies relevant firewall rules/policies to eligible interfaces. Explicit priorities and target scope determine admission; sharing a VPC does not grant stock permissions or bypass a deny rule.")),
 l("Backend check",n("Private warehouse listener","Application identity and stock scope","The backend listener accepts the admitted connection and verifies the requester before executing the stock operation. The database credentials, mutation identity and record ownership remain application controls separate from network reachability.","app")));
const ngfw=a("GCP: enforce an approved policy on warehouse network traffic","The selected NGFW policy and supported inspection configuration govern eligible workload traffic.","https://docs.cloud.google.com/firewall/docs/about-firewalls",
 l("Policy",n("Warehouse firewall administrator","Targeted rules and inspection association","The owner defines the intended organization/network policy scope and reviewed allow/deny rules. Any advanced inspection endpoints and associations follow their tier and regional prerequisites rather than being inferred from basic rule creation.","user")),
 l("Enforce",n("Cloud NGFW","Policy evaluation and configured inspection","The configured firewall controls evaluate eligible workload traffic under their supported policy order and inspection capability. Rule-based admission and advanced threat inspection are distinct configured behaviors; an allow decision does not validate the stock request's business meaning.")),
 l("Verify",n("Warehouse security operator","Check blocked path and legitimate request","The operator tests the intended blocked source and the authorized warehouse path, then reviews available rule/inspection evidence. Changes are approved and rollback-ready so a protection update does not silently isolate legitimate inventory clients.","user")));
const ids=a("GCP: detect suspicious warehouse traffic from mirrored packets","Cloud IDS analyzes the configured mirrored traffic and emits threat evidence; remediation follows a separate approved process.","https://docs.cloud.google.com/intrusion-detection-system/docs/overview",
 l("Mirror",n("Warehouse packet-mirroring policy","Selected traffic and IDS endpoint destination","The owner configures the supported packet-mirroring scope and IDS endpoint, selecting the intended warehouse interfaces and traffic filters. Visibility depends on that scope; traffic outside the mirrored sources is not assumed inspected.","security")),
 l("Detect",n("Cloud IDS","Analyze mirrored traffic for threats","Cloud IDS analyzes the mirrored packet copies for supported threats and emits its detection evidence. It is a detection path, not an inline firewall that automatically rejects the original warehouse connection or performs stock processing.")),
 l("Respond",n("Network incident responder","Validate detection before separate containment","The responder reviews the affected endpoints and threat context, correlates the finding with workload evidence and approves the appropriate firewall or host action. Containment effectiveness is tested independently of whether an IDS alert was delivered.","user")));
const perimeter=a("GCP: restrict document-data access across a service perimeter","VPC Service Controls evaluates supported API access boundaries in addition to IAM; the application still enforces customer ownership.","https://docs.cloud.google.com/vpc-service-controls/docs/overview",
 l("Access attempt",n("Document storage API caller","Identity and permitted access context","The caller requests the supported storage operation using its configured identity and access path. The security owner defines the protected project/service scope and any narrowly approved ingress or egress conditions.","app")),
 l("Perimeter",n("VPC Service Controls","Supported service API boundary evaluation","The configured perimeter evaluates eligible API requests and applicable ingress/egress or access-context rules. It adds a data-exfiltration boundary to IAM, not a replacement for IAM grants or a packet firewall for every service and protocol.")),
 l("Data authorization",n("Protected Cloud Storage service","IAM-permitted operation within allowed boundary","The storage operation must satisfy the relevant IAM and service controls as well as the perimeter. The document application separately checks customer ownership and verifies the supported API/interface limitations before accepting the access design.",undefined,"Cloud Storage")));
const binary=a("GCP: admit only an approved container digest to production","Release evidence produces an attestation; Binary Authorization enforces the configured deployment policy.","https://docs.cloud.google.com/binary-authorization/docs/overview",
 l("Attest",n("Trusted release attestor","Approved digest and signed release evidence","The trusted release process checks tests and relevant vulnerability findings, then creates the required attestation for the exact image digest using its permitted signing identity. Scanning alone does not create the attestation unless the pipeline explicitly does so.","security")),
 l("Deploy-time gate",n("Binary Authorization","Check selected attestation policy at deployment","The configured policy evaluates the proposed image against required attestations and enforcement settings on the supported target. Exceptions and breakglass behavior are separately controlled; policy evaluation is a deployment boundary rather than continuous application authorization.")),
 l("Run",n("Approved GKE workload","Pull admitted digest and serve validated requests","The cluster's permitted image-pull identity retrieves the admitted digest, and ready pods serve the application through their configured ingress. Workload data permissions are separate from registry pull and deployment attestation permissions.",undefined,"Google Kubernetes Engine (GKE)")));
const analysis=a("GCP: inspect an image's vulnerability report before release approval","Artifact Analysis supplies image findings; the release process reviews them before generating deployment evidence.","https://docs.cloud.google.com/artifact-analysis/docs/container-scanning-overview",
 l("Image",n("Candidate Artifact Registry digest","Published candidate and selected scanning configuration","The pipeline publishes the candidate container with an immutable digest and verifies the selected scanning capability and supported package coverage. The release review uses that exact digest rather than a moving tag.",undefined,"Artifact Registry")),
 l("Findings",n("Artifact Analysis","Supported package vulnerability metadata","The configured analysis records supported vulnerability findings associated with the image. The pipeline checks scan completion, severity and package relevance; the service does not patch dependencies or automatically certify that the application is safe.")),
 l("Approve or rebuild",n("Container release owner","Review findings and produce attestation only if approved","The owner applies the release policy, rebuilds affected dependencies where required and verifies the replacement digest. An approved release creates the required attestation through its controlled signing path; unresolved policy failures block that approval.","user")));
const dlp=a("GCP: remove sensitive identifiers from a document before publication","The worker submits selected content for configured inspection/de-identification and validates the sanitized output.","https://docs.cloud.google.com/sensitive-data-protection/docs/deidentify-sensitive-data",
 l("Read original",n("Document sanitization worker","Authorized bytes and selected transformation policy","The worker reads the permitted original and selects the approved content limits and transformation configuration. The data policy identifies sensitive fields and the intended redaction or replacement behavior before an output is published.","app")),
 l("Transform",n("Sensitive Data Protection","Configured sensitive-data identification and transformation","The supported API inspects the selected content under configured infoTypes and applies the specified de-identification transformations. Detection quality, format limits and any reversible-token key permissions are considered; transformation scope is not universal anonymization.")),
 l("Publish sanitized result",n("Sanitized document validator","Check transformed output before restricted publication","The worker checks the expected sensitive-field changes and output usability, then writes the approved sanitized result separately from the restricted original. Validation and owner policy determine whether that version can be shared.","app")));
const cert=a("GCP: publish an HTTPS hostname with a managed certificate","Certificate Manager prepares the selected certificate and map entry; the supported load-balancer frontend uses it for TLS.","https://docs.cloud.google.com/certificate-manager/docs/overview",
 l("Authorize domain",n("Portal certificate owner","Hostname, issuance method and validation","The owner configures the chosen supported issuance method and required domain authorization, then verifies issuance readiness. Certificate scope and renewal prerequisites match the intended load-balancer deployment and DNS ownership.","user")),
 l("Manage certificate",n("Certificate Manager","Issued certificate and selected map association","The service manages the configured certificate resource and certificate-map entry where required for the supported frontend. Its association and activation are checked explicitly; issuing a certificate does not route traffic or publish the application itself.")),
 l("TLS frontend",n("Portal HTTPS proxy","Present selected certificate and forward request","The supported HTTPS frontend presents the associated certificate during the client handshake and forwards the accepted request through its configured backend path. The backend still authenticates the customer and verifies access to document records.","app","Cloud Load Balancing")));
export const reviewedScale08:Record<string,ReviewedArchitecture[]>={
 "Cloud Interconnect":[interconnect],"Network Connectivity Center (NCC)":[ncc],"Virtual Private Cloud (VPC)":[vpc],"Cloud NGFW":[ngfw],
 "Cloud IDS":[ids],"VPC Service Controls":[perimeter],"Binary Authorization":[binary],"Artifact Analysis":[analysis],
 "Sensitive Data Protection":[dlp],"Certificate Manager":[cert]
};
