import type {ReviewedNode,ReviewedArchitecture} from "./reviewed-workload-architectures";
const n=(label:string,sub:string,detail:string,kind?:ReviewedNode["kind"],icon?:string):ReviewedNode=>({label,sub,detail,kind,icon});
const l=(title:string,...nodes:ReviewedNode[])=>({title,nodes});
const a=(title:string,note:string,reference:string,...layers:ReviewedArchitecture["layers"]):ReviewedArchitecture=>({title,note,reference,layers});

const rds=a("AWS: commit an order on an RDS Multi-AZ DB instance","The order handler commits its transaction on the primary. The single standby is an availability replica, and the client reconnects through the database endpoint after an applicable failover.","https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.MultiAZSingleStandby.html",
 l("Validate order",n("Order transaction handler","Business validation and request identifier","The handler verifies the customer's items and authorization and derives the stable order request identifier. It opens an authenticated database connection and uses that identifier to prevent a retry from creating a second order.","app")),
 l("Primary database",n("Amazon RDS","Primary SQL transaction","The primary executes the order insert and related stock update under the chosen transaction and database constraints. The application commits both changes atomically or returns the defined failure; the configured database user has only the required application privileges.")),
 l("Availability replication",n("Multi-AZ single standby","Synchronous standby for failover","This Multi-AZ DB instance deployment maintains its standby in another Availability Zone for failover. The standby is not a read-scaling endpoint. This availability copy and retained backups have separate purposes; application corruption requires an appropriate recovery point.","data","Amazon RDS")),
 l("Commit outcome",n("Order response handler","Confirm durable result or resolve uncertainty","The handler returns an accepted order only after the transaction's successful completion is established. If a connection fails around commit, it checks the stable request identifier after reconnecting so an uncertain outcome is not blindly replayed as a new order.","app")),
 l("Failure branch",n("Order database connection pool","Reconnect after applicable failover","When an applicable failure promotes the standby, the pool opens fresh connections through the database's configured endpoint and uses bounded retry for eligible failures. Outstanding transactions may fail or require outcome reconciliation; a stable endpoint does not preserve every existing connection.","app")));

const aurora=a("AWS: separate Aurora order writes from catalog reads","The application sends order transactions to the writer endpoint and eligible browsing reads to the reader endpoint, with connection-aware failover and freshness rules.","https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Overview.Endpoints.html",
 l("Choose operation",n("Storefront database router","Writer for transactions, reader for eligible reads","The application's database access code selects the writer for order transactions and read-after-write operations requiring current writer state. It uses the reader path only for browsing queries whose consistency contract permits replica reads.","app")),
 l("Choose writer or eligible reader",n("Aurora writer endpoint","Connect to current primary","The cluster writer endpoint directs new connections to the current primary DB instance. The primary executes authorized SQL writes and transactions; client pools refresh connections after failures or role changes rather than assuming a previously opened socket changes its target automatically.","data","Amazon Aurora"),n("Aurora reader endpoint","Balance eligible read connections","The reader endpoint balances new read-only connections across the eligible Aurora replicas in this cluster. The application sizes and refreshes its pools appropriately because this is connection balancing rather than per-query balancing; read freshness is considered before selecting the path.","data","Amazon Aurora")),
 l("Cluster storage",n("Amazon Aurora","Shared cluster data durability","Aurora maintains the cluster's durable storage for its database instances. The application still uses transactions and constraints for order correctness and a separate backup and recovery policy for accidental changes or corruption; replica availability is not a replacement for that policy.")),
 l("Business result",n("Storefront result handler","Return query or committed order outcome","The handler returns permitted catalog data or the confirmed order outcome from the selected branch. It reconciles ambiguous write outcomes using the order request identifier and keeps stale-tolerant browsing decisions separate from inventory reservation.","app")));

const azureSql=a("Azure: atomically create a ticket and its audit record","The ticket handler authenticates the caller, commits the ticket and audit row in one SQL transaction and resolves ambiguous retries using a unique request identifier.","https://learn.microsoft.com/en-us/azure/azure-sql/database/troubleshoot-common-connectivity-issues",
 l("API handler",n("Ticket creation API","Authorize caller and assign request identifier","The API checks the employee's right to create the ticket and validates its fields. It uses a stable request identifier and authenticated database connection so a repeated HTTP request cannot silently create multiple tickets.","app")),
 l("Transaction",n("Azure SQL Database","Commit ticket and audit rows together","The database executes the ticket insert and audit-row insert within the application's transaction under its constraints and permissions. Both records commit or the transaction rolls back; the application defines ticket rules while SQL enforces the specified transaction and schema constraints.")),
 l("Outcome",n("Ticket commit handler","Return confirmed ticket identifier","The handler returns the accepted ticket only after confirming the transaction result. If the connection is lost around commit, it queries the request identifier to reconcile whether the transaction succeeded before retrying the business operation.","app")),
 l("Transient-error branch",n("SQL retry policy","Bounded reconnect and transaction recovery","The configured client reconnects with backoff for eligible transient failures. Retrying a business transaction accounts for its whole outcome and idempotency rather than replaying only the statement that happened to fail or retrying validation and authorization errors indiscriminately.","app")),
 l("Read result",n("Employee ticket view","Retrieve committed ticket and allowed fields","The employee retrieves the resulting ticket through the authorized application read path. The handler checks ownership or role permissions and returns the allowed fields; possession of a ticket identifier is not treated as unrestricted record access.","app")));

const spanner=a("GCP: reserve a limited booking slot with a Spanner transaction","The booking backend checks remaining capacity and records a reservation atomically; aborted transaction attempts are retried without repeating external side effects.","https://docs.cloud.google.com/spanner/docs/transactions",
 l("Booking request",n("Booking backend","Validate customer and stable request key","The backend validates the authenticated customer's requested slot and derives a stable booking key. The data-access identity has the required Spanner database permissions; the customer does not receive direct database credentials.","app")),
 l("Transaction callback",n("Booking transaction function","Read capacity and construct reservation","The supported client transaction callback checks whether the booking key already exists, reads the slot capacity and constructs the reservation and capacity update only when allowed. It contains database work that is safe to rerun and performs no external payment or notification call.","app")),
 l("Commit",n("Spanner","Atomic reservation and capacity update","Spanner commits the supported read-write transaction atomically under the chosen isolation and concurrency configuration, or reports a conflict or abort. Its transaction guarantees enforce the specified operations together; the application chooses the capacity and ownership rules.")),
 l("Abort branch",n("Spanner client transaction runner","Retry eligible aborted attempts","The supported transaction runner retries eligible aborted attempts under its configured limits, rerunning the callback against a fresh attempt. The application avoids assuming a callback ran only once and treats validation failures and exhausted retries according to the booking contract.","app","Spanner")),
 l("After commit",n("Booking completion handler","Return durable reservation and trigger follow-up safely","Only after confirmed commit does the handler return the reservation or initiate its designed reliable follow-up process. Payment and notification use their own idempotency and delivery handling so a transaction retry cannot charge a customer or send a confirmation multiple times.","app")));

export const reviewedDatabaseArchitectures:Record<string,ReviewedArchitecture[]>={
 "Amazon RDS":[rds],"Amazon Aurora":[aurora],"Azure SQL Database":[azureSql],"Spanner":[spanner],
};
