import {n,l} from "./reviewed-architecture-builders";
import type {ReviewedArchitecture} from "./reviewed-workload-architectures";
const e=(from:string,to:string,label:string,control=false)=>({from,to,label,control});
export const practicalInspector:ReviewedArchitecture={
 title:"AWS: repair a vulnerable container image before its next release",
 note:"A container release starts with a built image, uses Inspector findings to select a repair, and deploys a replacement digest only after the release checks pass.",
 reference:"https://docs.aws.amazon.com/inspector/latest/user/scanning-ecr.html",
 layers:[
  l("Build candidate",n("Container build job","Build and test the proposed application image","The build job checks out the approved application revision, builds its container image and runs the required tests. It pushes the candidate to the release repository and records the immutable digest so vulnerability findings and deployment approval refer to the same artifact.",undefined,"AWS CodeBuild")),
  l("Store image",n("Amazon ECR release image","Candidate digest under enhanced scanning","ECR stores the candidate image under its immutable digest. The registry's enhanced scanning configuration selects the repository and supported image for Inspector assessment; storing or tagging an image does not by itself approve it for deployment.",undefined,"Amazon ECR")),
  l("Find vulnerability",n("Amazon Inspector","Package finding tied to the candidate digest","Inspector assesses the eligible candidate image and reports the vulnerable package, installed version and available remediation information. The release owner checks the finding against this exact digest and its coverage; Inspector supplies assessment results rather than editing the source or rebuilding the image.")),
  l("Repair and rebuild",n("Container release owner","Select and approve the dependency repair","The owner reviews the affected dependency and chooses the appropriate patched package or base image. The change is committed and tested before a rebuild; an exception follows the release policy instead of marking an unresolved finding as automatically safe.","user"),n("Patched container build","Rebuild from the approved dependency change","CodeBuild rebuilds the application from the patched source or base image and reruns the required tests. It publishes a new image digest, keeping the original vulnerable artifact distinct so the release process cannot accidentally deploy the old tag or finding result.",undefined,"AWS CodeBuild")),
  l("Verify replacement",n("Replacement ECR image","New digest and its own scan results","The replacement image is assessed under the configured enhanced scanning coverage. The release gate waits for the required assessment evidence for this new digest and checks the vulnerability policy again; a successful build is not proof that the replacement passed security review.",undefined,"Amazon ECR")),
  l("Release accepted digest",n("Container release gate","Tests, finding policy and explicit approval","The pipeline checks the replacement digest's required tests and assessment results and obtains any required approval. It updates the deployment specification only for the accepted digest; a failed or incomplete check leaves the current production release in place.",undefined,"AWS CodePipeline"),n("Amazon ECS application service","Roll out and health-check the accepted image","ECS starts replacement tasks from the approved image digest using the task definition and configured deployment behavior. The service verifies task readiness and application health before accepting the rollout, with rollback governed by the selected deployment policy.",undefined,"Amazon ECS"))
 ],
 connections:[e("Container build job","Amazon ECR release image","push candidate digest"),e("Amazon ECR release image","Amazon Inspector","enhanced image assessment",true),e("Amazon Inspector","Container release owner","review package finding",true),e("Container release owner","Patched container build","approved dependency change",true),e("Patched container build","Replacement ECR image","publish new digest"),e("Replacement ECR image","Container release gate","replacement scan and test evidence",true),e("Container release gate","Amazon ECS application service","deploy accepted digest",true)]
};
export const practicalReachability:ReviewedArchitecture={
 title:"AWS: locate a configuration barrier to a database connection",
 note:"An operator investigates a failed EC2-to-RDS connection, analyzes the selected network configuration, repairs the identified rule and verifies a live database query.",
 reference:"https://docs.aws.amazon.com/vpc/latest/reachability/how-reachability-analyzer-works.html",
 layers:[
  l("Identify failed connection",n("Inventory application on EC2","Private RDS connection fails","The inventory application tries its expected private database address and port and records the connection failure and request time. The incident identifies the actual source network interface and database destination rather than assuming that every path through the VPC is broken.",undefined,"Amazon EC2")),
  l("Select network path",n("Network operator","Source interface, destination and TCP port","The operator selects the application's source interface and the supported RDS destination for the database port, then starts the supported network path analysis. The question is whether the configured network permits this connection; the analysis is separate from checking database credentials.","user")),
  l("Analyze configuration",n("VPC Reachability Analyzer","Model routes and security controls","Reachability Analyzer evaluates the supported route, subnet and interface configuration for the selected path and reports reachability or a blocking component. It does not send database requests or test the running listener; the operator checks the analysis coverage before relying on its result.")),
  l("Review identified barrier",n("Database security group","Missing application-to-database permission","For this example the analysis identifies the database-side ingress rule as the barrier. The operator compares the intended application source and database port with the rule, then proposes a narrowly scoped repair rather than opening the database to every address.",undefined,"Amazon EC2 security groups"),n("Network change approval","Approve the scoped rule repair","The network owner reviews the source, target and database port and authorizes the restricted security-group change. The operator applies that change and reruns the same path analysis to confirm the modeled barrier is removed while unrelated access stays restricted.","security")),
  l("Verify real operation",n("Database connectivity test","Connect from the application and run a permitted query","The operator runs an authorized live database connection from the actual application host after the reviewed repair. The test verifies the listener, TLS and database credentials as well as the allowed network path; a modeled reachable result alone cannot prove that the application can authenticate.","app"),n("Inventory RDS database","Return the permitted inventory test result","RDS authenticates the configured database account and executes the bounded test query against its allowed inventory records. The operator compares the result with the expected data before closing the incident; the analysis tool never executes or repairs the database query itself.",undefined,"Amazon RDS"))
 ],
 connections:[e("Inventory application on EC2","Network operator","failed endpoint and port evidence",true),e("Network operator","VPC Reachability Analyzer","selected supported analysis path",true),e("VPC Reachability Analyzer","Database security group","identified ingress barrier",true),e("Database security group","Network change approval","review intended rule change",true),e("Network change approval","Database connectivity test","reanalysis and approved live verification",true),e("Database connectivity test","Inventory RDS database","authenticated test query")]
};
