import {n,l,a} from "./reviewed-architecture-builders";
import type {ReviewedArchitecture} from "./reviewed-workload-architectures";

const glue=a("AWS: transform daily order files into a curated Parquet dataset","Glue uses the selected input schema to run an explicit ETL job, validate order records and write a versioned Parquet output for analytical consumers.","https://docs.aws.amazon.com/glue/latest/dg/components-key-concepts.html",
 l("Source",n("Amazon S3 raw orders","Completed daily input batch","The producer uploads the completed order batch under the agreed input prefix and signals its readiness through the selected orchestration process. Files have the expected schema and run identity; the job does not read a partially uploaded business batch.",undefined,"Amazon S3")),
 l("Metadata",n("AWS Glue Data Catalog","Table schema and source location","The catalog holds the selected table definition and partition metadata used to locate and interpret the input. A configured crawler can discover metadata, but the catalog record is not a copied dataset and does not itself validate the business meaning of each order row.")),
 l("Transform",n("AWS Glue","Run reviewed order ETL script","The authorized Glue job reads the selected batch, parses fields, validates order identifiers and amounts, handles rejected rows and converts permitted records to the chosen Parquet layout. Its job role permits input reads and output writes; job bookmarks and rerun handling are chosen for this workload.")),
 l("Output",n("Amazon S3 curated orders","Run-scoped Parquet and rejected records","The job writes the curated dataset under the approved output and partition strategy and places rejected records in the configured separate location. The publishing procedure prevents a failed rerun from silently exposing partial or duplicate data to consumers.",undefined,"Amazon S3")),
 l("Accept",n("Order data owner","Reconcile counts and publish dataset","The owner checks input and output counts, rejection totals and representative transformed fields before publishing the batch for analysis. A successful job state is operational evidence; the dataset's business validation is an explicit acceptance step.","user")));

const kinesis=a("AWS: consume device readings with durable checkpoints","A producer publishes stable event identifiers to Kinesis Data Streams; a consumer writes accepted readings idempotently and checkpoints only after its durable processing boundary.","https://docs.aws.amazon.com/streams/latest/dev/kinesis-record-processor-duplicates.html",
 l("Producer",n("Device ingestion producer","Stable event ID and partition key","The producer validates device readings and publishes each with a stable event identifier and chosen partition key. It checks write results and retries appropriately; producer retries can create repeated delivery, so consumers do not infer uniqueness from a single publish attempt.","app")),
 l("Stream",n("Amazon Kinesis Data Streams","Partitioned retained device records","The stream retains records for configured consumers under its retention and partitioning model. Consumers read their shard positions, and ordering is handled within the relevant shard rather than assumed to be a global ordering of all devices.")),
 l("Process",n("Device record consumer","Validate and persist reading idempotently","The consumer validates each reading and writes its business result using the stable event identifier to handle replays. Only after the selected durable write succeeds does it advance its checkpoint; failed batches and restarts can cause records after an older checkpoint to be processed again.","app")),
 l("Durable state",n("Reading store and checkpoint store","Business records and restart position","The business store preserves the accepted reading and duplicate-detection state, while the configured consumer checkpoint store records its completed shard position. These states have separate roles and an explicitly designed failure boundary so a checkpoint cannot skip an uncommitted reading.","data")));

const adf=a("Azure: copy a completed daily file into SQL staging","Data Factory runs a configured Copy activity from Blob storage to a SQL staging table, then the data owner validates the batch before promoting it.","https://learn.microsoft.com/en-us/azure/data-factory/tutorial-copy-data-portal",
 l("Input",n("Daily batch in Blob storage","Completed source file and batch ID","The producer writes the completed daily file at the agreed location with its batch identifier. The pipeline selects that input using its configured dataset and trigger parameters rather than treating every unrelated storage write as a ready business batch.",undefined,"Azure Blob Storage")),
 l("Copy orchestration",n("Azure Data Factory","Pipeline, linked services and Copy activity","The pipeline's linked services define source and sink connectivity and authentication, and its datasets identify the file and staging table. The configured Copy activity executes through the chosen integration runtime using the specified mapping and write behavior; retries and reruns account for the batch identifier.")),
 l("SQL staging",n("SQL batch staging table","Mapped rows and run boundary","The copy writes the configured mapped records into the staging target under its approved data permissions. Staging isolates the incoming batch from published business tables; append, overwrite and duplicate behavior are explicitly selected for this load.","data","Azure SQL Database")),
 l("Validate and promote",n("Batch validation owner","Reconcile staged records before publication","The owner checks copy results, expected counts and validation queries, then performs the approved promotion to business tables. A completed copy establishes that its configured transfer finished; it does not by itself certify that every row satisfies the business rules.","user")));

const synapse=a("Azure: query curated Parquet files with serverless SQL","A permitted analyst submits a serverless SQL query against curated files in the data lake; storage access and SQL permissions are checked for the chosen identity path.","https://learn.microsoft.com/en-us/azure/synapse-analytics/sql/query-parquet-files",
 l("Request",n("Sales analyst SQL client","Filtered analytical query","The analyst submits the approved query through the workspace's serverless SQL endpoint, selecting the required columns and relevant file or partition path. The client authenticates under the configured SQL access model and avoids unrestricted scans of unrelated datasets.","user")),
 l("Execute",n("Azure Synapse Analytics","Serverless SQL over selected files","The serverless SQL engine resolves the configured OPENROWSET or external-table source, checks the SQL and storage access path and reads the selected files to execute the query. It queries lake files rather than automatically loading them into a dedicated SQL warehouse.")),
 l("File data",n("Azure Data Lake Storage","Curated Parquet source and access controls","The data lake supplies the curated files under the query's configured identity and access controls. File structure, schema compatibility and publication completeness are verified so the query reads the intended business dataset rather than a partially produced batch.")),
 l("Result",n("Sales analysis result","Authorized aggregation and interpretation","The client receives the query's returned rows or aggregates and the analyst checks their time range and dataset version. Query success confirms execution, while revenue interpretation and reconciliation remain the analyst's responsibility.","data")));

const hubs=a("Azure: process equipment events using partition checkpoints","Event Hubs retains partitioned equipment events; the consumer records business results and updates its partition checkpoint only after its durable processing boundary.","https://learn.microsoft.com/en-us/azure/event-hubs/event-processor-balance-partition-load",
 l("Publish",n("Equipment event producer","Event identifier and partition selection","The producer validates equipment events and publishes them with the selected partitioning strategy and stable event identifier. It checks send outcomes and treats retries as possible repeated business events, preserving identifiers for consumer deduplication.","app")),
 l("Event log",n("Event Hubs","Partitioned events and consumer-group view","Event Hubs retains the event sequence in each partition under its configured retention. The selected consumer group lets this processing application track its own progress; it is not a single globally ordered queue for all equipment events.")),
 l("Consumer",n("Equipment event processor","Process partition records and handle replays","The configured event processor coordinates partition ownership with its checkpoint store and reads from the applicable restart position. It validates events and writes results idempotently before advancing progress; a restart can replay events after the last completed checkpoint.","app")),
 l("Persist result then checkpoint",n("Equipment state store","Durable idempotent business update","The state store records the accepted equipment update using the stable identifier or supported conditional-write design. The processor confirms its chosen durable completion point before writing a newer checkpoint.","data"),n("Blob checkpoint store","Partition ownership and completed position","The configured checkpoint store retains the processor group's partition ownership and completed offsets. A checkpoint is a restart position for this consumer, not deletion of the event from Event Hubs and not a substitute for the business state's durability.","storage","Azure Blob Storage")));

const asa=a("Azure: aggregate sensor temperatures into event-time windows","Stream Analytics reads sensor events from Event Hubs, applies the configured timestamp and window query and writes completed aggregates to the selected Blob output.","https://learn.microsoft.com/en-us/azure/stream-analytics/stream-analytics-time-handling",
 l("Input",n("Sensor Event Hubs input","Temperature events with device timestamps","The configured stream input supplies the sensor identifiers, measurements and timestamp fields. The job's input identity and event format are prepared, and device timestamp quality is checked before relying on event-time windows.",undefined,"Event Hubs")),
 l("Window processing",n("Azure Stream Analytics","Timestamp selection and temperature aggregation","The configured query selects the event timestamp and computes the temperature aggregate over its declared window and grouping keys. Late-arrival and out-of-order policies govern how delayed measurements affect the result, rather than silently assuming arrival time equals observation time.")),
 l("Output",n("Temperature aggregate Blob output","Configured window result records","The selected output writes the emitted aggregate records under its configured format and storage permissions. The owner verifies the output naming and consumer contract so downstream readers interpret window timestamps and repeated or corrected results appropriately.","storage","Azure Blob Storage")),
 l("Use result",n("Equipment analyst","Interpret bounded window measurements","The analyst checks the aggregation interval, grouping and lateness policy and compares sample results with known sensor inputs. A windowed average informs analysis; equipment shutdown requires a separately authorized control workflow.","user")));

const dataflow=a("GCP: aggregate purchase events into analytical windows","A configured Dataflow pipeline reads Pub/Sub purchase events, validates and windows them and writes the selected results to BigQuery with explicit processing and sink semantics.","https://docs.cloud.google.com/dataflow/docs/concepts/streaming-with-cloud-pubsub",
 l("Events",n("Purchase Pub/Sub subscription","Retained events with stable purchase IDs","The subscription delivers purchase events to the authorized pipeline. Stable purchase identifiers and event timestamps support the business deduplication and window design; the producer and consumer contracts define replay handling and retention.",undefined,"Pub/Sub")),
 l("Transform",n("Dataflow","Validate, deduplicate and window purchase events","The Beam pipeline validates purchase records, applies its chosen deduplication and event-time window policy and calculates the required aggregates. Processing mode, watermarks and allowed lateness are configured; an exactly-once processing claim is not automatically a guarantee for arbitrary external side effects.")),
 l("Analytical sink",n("BigQuery purchase aggregates","Configured writer and output schema","The pipeline writes results through its selected supported BigQuery sink with defined schema and write semantics. The team verifies how emitted window updates and replays map to stored rows, and rejects incompatible records through the intended error path.","data","BigQuery")),
 l("Validate",n("Purchase analytics owner","Check totals, lateness and replay behavior","The owner checks known purchase samples, window totals, late-event handling and the configured sink's duplication behavior before publishing the dataset. A healthy worker job is checked separately from complete and correct analytical results.","user")));

const bigquery=a("GCP: load a completed Parquet batch and query sales totals","An authorized load job imports selected Cloud Storage files into a staged BigQuery table; a validated batch is then used for the approved sales query.","https://docs.cloud.google.com/bigquery/docs/loading-data-cloud-storage-parquet",
 l("Files",n("Sales Parquet batch","Completed Cloud Storage input set","The producer publishes the completed Parquet file set at the agreed Cloud Storage paths and records the batch identifier. The loader selects only the intended objects and checks compatible source and dataset locations before starting the load.","storage","Cloud Storage")),
 l("Load job",n("BigQuery","Authorized Parquet import to staging table","The load job reads the selected files using required job, storage and destination-table permissions and applies the chosen schema and write disposition. The caller checks the completed job result and handles retries under its batch and job-identity design to avoid accidental duplicate appends.")),
 l("Validate data",n("Sales staging validation","Counts, types and business totals","The validation query checks loaded row counts, required identifiers and representative totals against the source batch. Only the accepted batch is promoted or exposed under the defined table or view contract; load success alone does not validate revenue calculations.","data")),
 l("Analytical query",n("Sales query client","Filter authorized table and return aggregates","The authorized query reads the accepted sales data, uses the intended date filters and groups the required totals. Query permissions and any row or column controls limit the output, while the consumer interprets the recorded dataset version and time range.","app")));

export const reviewedDataArchitectures:Record<string,ReviewedArchitecture[]>={
 "AWS Glue":[glue],"Amazon Kinesis":[kinesis],"Amazon Kinesis Data Streams":[kinesis],
 "Azure Data Factory":[adf],"Azure Synapse Analytics":[synapse],"Azure Data Lake Storage":[synapse],"Event Hubs":[hubs],"Azure Stream Analytics":[asa],
 "Dataflow":[dataflow],"BigQuery":[bigquery,dataflow],
};
