import type {ReviewedNode,ReviewedArchitecture} from "./reviewed-workload-architectures";
const n=(label:string,sub:string,detail:string,kind?:ReviewedNode["kind"],icon?:string):ReviewedNode=>({label,sub,detail,kind,icon});
const l=(title:string,...nodes:ReviewedNode[])=>({title,nodes});
const a=(title:string,note:string,reference:string,...layers:ReviewedArchitecture["layers"]):ReviewedArchitecture=>({title,note,reference,layers});

const aws=a("AWS: privately consume a partner's invoice API","A consumer initiates calls through an accepted interface endpoint to a provider's NLB-backed API. Private connectivity and application authorization remain separate.","https://docs.aws.amazon.com/vpc/latest/privatelink/create-endpoint-service.html",
 l("Consumer",n("Invoice client","Authenticated partner API call","The client resolves the configured partner API hostname and opens a connection to the interface endpoint from the consumer VPC. It sends an application credential and invoice request; private reachability does not establish the caller's business authorization.","app")),
 l("Private entry",n("AWS PrivateLink","Consumer interface endpoint","The configured interface endpoint exposes private network interfaces in the consumer's selected subnets. Endpoint security groups permit the intended callers and the provider accepts the connection when required. The endpoint reaches the published service without connecting every resource in the two VPCs.")),
 l("Provider front end",n("Network Load Balancer","Route partner connections to healthy targets","The provider's endpoint service is associated with the Network Load Balancer. Its listener forwards accepted connections to registered healthy API targets; it balances connections and does not validate invoice ownership or execute the API's business code.",undefined,"Elastic Load Balancing")),
 l("Business service",n("Partner invoice API","Authorize and fetch invoice","The API verifies the client credential, checks that the caller may read the requested invoice, retrieves its authoritative record and returns the permitted fields. Network-level acceptance alone does not replace tenant isolation or record-level authorization.","app")),
 l("Response",n("Invoice client result","Use authorized response","The response returns over the established connection to the consumer. The client handles API errors and retries under the partner's contract; publishing the endpoint does not grant the provider a general path to initiate connections to consumer workloads.","app")));

const azure=a("Azure: read private Blob documents from a VM","The VM resolves the storage hostname to an approved Blob private endpoint and reads documents using a separately authorized identity.","https://learn.microsoft.com/en-us/azure/storage/common/storage-private-endpoints",
 l("Reader",n("Azure document VM","Request authorized blob read","The document application requests its storage account's normal Blob hostname using its configured identity or credential. It needs the appropriate data permission for the object; the private endpoint supplies connectivity rather than a blanket storage authorization.","app","Azure Virtual Machines")),
 l("Resolve name",n("Azure Private DNS","Blob hostname to private endpoint IP","The linked private DNS configuration resolves the account's Blob hostname through the private-link zone to the private endpoint address. The team verifies resolution from the actual VM and any hybrid clients; an approved endpoint alone does not change every client's DNS.","data","Azure DNS")),
 l("Private path",n("Azure Private Link","Approved Blob private endpoint","The private endpoint provides an IP in the consumer virtual network for the approved Blob storage subresource. Public network access is governed separately at the storage account, and other subresources require their own supported endpoint configuration.")),
 l("Object access",n("Azure Blob Storage","Check permission and return document","Blob Storage evaluates the caller's applicable data authorization and returns the requested document only when access is permitted. The private connection keeps this request on the configured private path without removing identity checks or granting access to other containers.")),
 l("Document use",n("Document application result","Parse and display permitted content","The application parses the retrieved object and displays the document according to its own user authorization rules. It handles permission errors and missing objects separately from connection failures.","app")));

const gcp=a("GCP: connect a consumer project to private Cloud SQL","A configured Private Service Connect endpoint and DNS provide database reachability; the application still authenticates and executes permitted SQL operations.","https://docs.cloud.google.com/sql/docs/postgres/configure-private-service-connect",
 l("Client",n("Database application","Open authenticated SQL connection","The application uses the approved database hostname or endpoint address from the consumer network and its configured database authentication. It requests a business query rather than treating a private network connection as permission to read every table.","app")),
 l("DNS",n("Cloud DNS private zone","Resolve database endpoint address","The configured private DNS record maps the database name to the consumer's Private Service Connect endpoint. The client network can resolve this zone; TLS settings and any proxy or connector configuration are checked against the selected connection method.")),
 l("Consumer endpoint",n("Private Service Connect","Accepted Cloud SQL service attachment","The consumer forwarding-rule endpoint targets the Cloud SQL service attachment under the configured allowed-consumer policy. It exposes the approved database service inside the consumer network; it is not general-purpose VPC peering or a mechanism that authenticates database users.","security")),
 l("Database",n("Cloud SQL","Execute authorized PostgreSQL query","Cloud SQL accepts the configured connection, checks database authentication and applies the user's SQL privileges. It executes the requested query against its stored records and returns the result; private reachability does not grant broad schema or administrative rights.")),
 l("Business result",n("Application query result","Use returned records","The application uses the authorized query result to complete its business response, handles database timeouts and releases the connection according to its pool policy. The private endpoint stays a connectivity boundary throughout this operation.","app")));

export const reviewedPrivateAccessArchitectures:Record<string,ReviewedArchitecture[]>={
 "AWS PrivateLink":[aws],"Azure Private Link":[azure],"Private Service Connect":[gcp],"Cloud SQL":[gcp],
};
