import {n,l,a} from "./reviewed-architecture-builders";
import type {ReviewedArchitecture} from "./reviewed-workload-architectures";

const ebs=a("AWS: keep a document index on an attached data volume","A single EC2 indexer stores its persistent index on EBS. The guest filesystem and application govern files and consistency; snapshots provide a separate recovery path.","https://docs.aws.amazon.com/ebs/latest/userguide/ebs-volumes.html",
 l("Attach",n("Amazon EBS","Same-AZ index data volume","The configured EBS volume attaches to the indexer's EC2 instance in the same Availability Zone. It supplies block storage, while disk encryption, volume performance and deletion behavior are selected for the index workload rather than inferred from the instance's lifetime.")),
 l("Mount",n("Indexer filesystem","Initialize new disk or mount existing index","The administrator identifies the correct device, formats only a new empty disk and mounts the filesystem using stable device identifiers. An existing index volume is mounted without destructive reformatting; ownership permits the index process to access its directory.","storage")),
 l("Index",n("Amazon EC2","Parse documents and persist index files","The running index process reads its authorized source documents, builds search structures and writes them to the mounted EBS filesystem. It uses its own flush and recovery protocol so a stopped process can reopen a consistent index; the volume does not parse the documents.")),
 l("Recovery path",n("Index backup operator","Quiesce and test snapshot restoration","The operator coordinates the snapshot with the application's consistency procedure and tests a restored volume on an isolated compatible instance. Reattaching persistent storage after a host failure and restoring an older snapshot after a bad index update solve different problems.","user")));

const efs=a("AWS: share uploaded documents across web instances","Two application instances use the same regional EFS filesystem through configured mount targets and a controlled POSIX access path.","https://docs.aws.amazon.com/efs/latest/ug/accessing-fs.html",
 l("Writers and readers",n("Document web instances","Store and read permitted upload files","Each application instance validates the upload or read request and uses the shared mount for document files. The application coordinates concurrent writes with its file naming and locking design and publishes a document only after the intended write is complete.","app")),
 l("Network entry",n("EFS mount targets","NFS access from approved clients","The clients reach the configured mount targets through their VPC routes and permitted NFS traffic. Regional mount targets are placed in the selected client Availability Zones, and security groups permit the intended client sources rather than opening the filesystem to every instance.","security","Amazon EFS")),
 l("Shared storage",n("Amazon EFS","Shared document namespace","EFS provides the filesystem namespace that the instances mount. Configured access-point, IAM and POSIX controls govern the chosen access design; the team distinguishes network reachability from file ownership and permissions. Every instance can see the authorized shared files without synchronizing separate local disks.")),
 l("Read result",n("Document download handler","Authorize and return committed document","The handler checks user access to the selected document and reads its completed file from the shared namespace. Filesystem sharing does not replace the application's document ownership checks, and accidental deletion is addressed through its separate backup policy.","app")));

const fsx=a("AWS: move a departmental Windows share to FSx","Domain-joined users access a managed SMB share with Active Directory identity and Windows file permissions.","https://docs.aws.amazon.com/fsx/latest/WindowsGuide/limit-access-file-folder.html",
 l("User access",n("Department Windows client","Domain identity and SMB share name","The employee uses the departmental share's DNS name from an approved domain-joined client. The network allows the required SMB and directory traffic, and the user identity is supplied through the configured Active Directory integration.","user")),
 l("Identity",n("Active Directory","Domain authentication and group membership","The configured directory establishes the user's identity and departmental groups for SMB authentication. Directory reachability and the filesystem's domain integration are prepared explicitly; membership in a cloud administrator role is not a substitute for file-share permissions.","security")),
 l("File service",n("Amazon FSx for Windows File Server","Managed SMB share and Windows ACLs","FSx hosts the Windows-compatible share and applies the configured share and file or folder permissions. The file owner scopes access to departmental groups and preserves the required SYSTEM permissions while migrating data and ACLs.")),
 l("Work with files",n("Department application","Open and update permitted documents","The application opens the permitted files over SMB and obeys the workload's locking and concurrency requirements. Operators test allowed and denied users and a file restore before retiring the old share, rather than accepting a successful mount as proof of correct access.","app")));

const azureDisk=a("Azure: keep processing state on a managed data disk","A Linux VM mounts a managed data disk for persistent processing state; temporary VM storage is not used as the sole durable copy.","https://learn.microsoft.com/en-us/azure/virtual-machines/linux/disks-format-mount-data-disks-linux",
 l("Attach",n("Azure Disk Storage","Managed data disk and selected VM attachment","The configured managed disk attaches to the supported VM under its zone and compatibility requirements. The owner selects capacity, performance, encryption and lifecycle settings for the processing state and confirms the disk is the intended persistent device.")),
 l("Mount",n("Linux data filesystem","Stable mount and application permissions","The administrator identifies the attached data disk, initializes an empty disk only when appropriate and configures a stable mount. Ownership and mount ordering allow the worker to start only after its persistent directory is available.","storage")),
 l("Process",n("Virtual Machines","Read jobs and persist checkpoints","The Linux VM runs the worker, reads authorized input jobs and writes its checkpoints and durable output into the mounted directory. The program distinguishes completed results from partial files so restarting the VM does not silently lose or duplicate work.")),
 l("Protect",n("Processing-state owner","Back up and exercise restart or restore","The owner backs up the persistent state through the approved consistency and recovery procedure and tests a restored worker. Disk persistence does not repair application-level corruption, and VM temporary storage remains unsuitable as the only copy of required state.","user")));

const azureFiles=a("Azure: give a department identity-controlled SMB documents","Clients authenticated through the configured AD DS integration mount Azure Files; share-level grants and directory or file ACLs restrict document access.","https://learn.microsoft.com/en-us/azure/storage/files/storage-files-active-directory-overview",
 l("Client",n("Department SMB client","Resolve and mount approved file share","The domain-connected client resolves the configured share endpoint and establishes SMB connectivity through the approved network path. It uses the user's supported Kerberos identity flow for this AD DS design rather than distributing the storage account key to every employee.","app")),
 l("Authenticate",n("AD DS integration","Configured directory identity","The configured directory integration supplies the supported Kerberos authentication context for Azure Files. Identity synchronization and share access prerequisites are verified for the chosen client population; other supported identity options require their own configuration.","security")),
 l("Authorize and store",n("Azure Files","Share-level permission and file ACLs","Azure Files provides the SMB share and applies the configured share-level authorization together with the directory and file permissions. Administrators grant the intended departmental access at both levels and test that unrelated users cannot read the documents.")),
 l("Application use",n("Department file workflow","Read or update allowed documents","The department's application reads and writes the permitted documents with its normal SMB locking and error handling. The owner protects the share using an appropriate backup and restore policy, since a valid user or application can still delete or overwrite an authorized file.","app")));

const filestore=a("GCP: share rendering assets among Linux workers","Render workers mount a Filestore NFS share, read the common assets and publish their completed frames under coordinated output names.","https://docs.cloud.google.com/filestore/docs/mounting-fileshares",
 l("Workers",n("Linux render workers","Mount configured NFS export","The workers resolve or use the approved Filestore endpoint, reach it over the configured VPC path and mount the selected export with supported NFS settings. Their local user and group identities are aligned with the selected filesystem permissions.","app")),
 l("Access controls",n("NFS export and file permissions","Restrict clients and asset writes","The configured export rules restrict the intended clients, while filesystem permissions distinguish asset readers and output writers. In this NFS design, a VM service account's cloud management role is not automatically the operating-system user's file permission.","security")),
 l("Shared filesystem",n("Filestore","Rendering assets and frame output","Filestore serves the mounted assets and output namespace to the authorized render workers. The application coordinates frame identifiers and publication so workers do not overwrite each other's output; the file service stores bytes rather than computing the rendered frame.")),
 l("Render and publish",n("Frame rendering process","Read assets and finish assigned frame","Each worker reads the required shared assets, performs its assigned rendering task and writes the completed frame using the workflow's safe publication procedure. Downstream assembly consumes only completed frames, and backups separately protect required assets.","app")));

const pd=a("GCP: persist a local search index on a VM data disk","A Compute Engine VM formats and mounts its supported persistent disk and runs an indexer against that filesystem.","https://docs.cloud.google.com/compute/docs/disks/format-mount-disk-linux",
 l("Attach storage",n("Persistent Disk","Configured non-boot disk attachment","The supported non-boot disk attaches to the selected VM using compatible location and attachment settings. The team chooses the disk type and performance limits for the index workload and records the intended deletion and backup lifecycle.","storage")),
 l("Prepare guest",n("Linux index mount","Detect existing data before formatting","The guest identifies the correct attached device, formats only a confirmed new empty disk and mounts it under a stable name. Startup configuration waits for the mount, and the application user has the required directory permissions.","storage")),
 l("Run indexer",n("Compute Engine","Parse source records and maintain index","The VM runs the search indexer, reads its authorized source records and writes the index to the mounted data filesystem. Process checkpoints and index integrity checks govern restart behavior; persistent block storage itself does not perform indexing or create a shared NFS service.")),
 l("Recover",n("Index operations owner","Test restart and restore","The owner tests index reopening after restart and the approved backup restoration path after corruption. Required index files stay on the persistent mount, while temporary scratch results can be regenerated under the application's documented recovery procedure.","user")));

export const reviewedStorageArchitectures:Record<string,ReviewedArchitecture[]>={
 "Amazon EBS":[ebs],"Amazon EC2":[ebs],"Amazon EFS":[efs],"Amazon FSx":[fsx],"Amazon FSx for Windows File Server":[fsx],
 "Azure Disk Storage":[azureDisk],"Virtual Machines":[azureDisk],"Linux Virtual Machines":[azureDisk],"Azure Files":[azureFiles],
 "Filestore":[filestore],"Compute Engine":[pd],
};
