import type {ReviewedNode,ReviewedArchitecture} from "./reviewed-workload-architectures";
const n=(label:string,sub:string,detail:string,kind?:ReviewedNode["kind"],icon?:string):ReviewedNode=>({label,sub,detail,kind,icon});
const l=(title:string,...nodes:ReviewedNode[])=>({title,nodes});
const a=(title:string,note:string,reference:string,...layers:ReviewedArchitecture["layers"]):ReviewedArchitecture=>({title,note,reference,layers});

const aws=a("AWS: migrate PostgreSQL orders with full load and CDC","DMS copies selected tables and replicates changes to a prepared RDS PostgreSQL target; a controlled write pause and validation precede cutover.","https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Task.CDC.html",
 l("Prepare source",n("PostgreSQL source","Orders and logical replication","The source database continues accepting orders while the migration runs. Its supported logical-replication settings, replication permissions and log retention are prepared for DMS; the operator monitors retained logs so a lagging consumer cannot exhaust source storage.","data")),
 l("Copy and catch up",n("AWS Database Migration Service","Selected tables and ongoing changes","The full-load-and-CDC task reads selected existing rows and applies captured changes to the target. Endpoints, network access and table mappings are explicitly configured. The team handles schema objects and unsupported features separately rather than assuming row replication migrates every database dependency.")),
 l("Destination",n("Amazon RDS PostgreSQL","Prepared target database","The target receives copied order rows and subsequent changes. The database team prepares required schema objects, permissions and application dependencies, checks task errors and uses supported validation to compare source and destination before enabling target writes.","data","Amazon RDS")),
 l("Cut over",n("Migration owner","Freeze writes and verify catch-up","The owner pauses source writes, allows the final changes to apply, checks validation results and completes the approved application connection switch. A running CDC task is not permission for applications to write independently to both databases.","user")),
 l("Resume business",n("Order application","Connect to migrated database","The application reconnects to the target with its configured credentials and executes verified read and write transactions. The team watches business errors and retains the agreed rollback evidence; writes after cutover require a deliberate rollback strategy.","app")));

const azure=a("Azure: move SQL Server using an online backup migration","Database Migration Service restores a SQL Server backup chain to a target Azure VM while the source remains active, followed by a final write pause and cutover.","https://learn.microsoft.com/en-us/data-migration/sql-server/virtual-machines/database-migration-service-online",
 l("Produce backup chain",n("Source SQL Server","Full and transaction-log backups","The source continues serving the business workload while the DBA produces a valid full backup and subsequent transaction-log backups. Recovery model, uninterrupted log chain and supported database versions are checked before attempting the online migration.","data")),
 l("Make backups accessible",n("Migration backup location","Configured file share or Blob storage","The configured backup location exposes the backup chain to the migration's authorized transfer and restore components. Required connectivity, credentials and integration-runtime configuration are verified; the location holds database backups rather than live application requests.","storage")),
 l("Restore sequence",n("Azure Database Migration Service","Coordinate online database migration","DMS coordinates the configured online migration and tracks restoration of the available backup sequence to SQL Server on the destination Azure VM. The operator checks migration errors and pending backups and migrates server-level objects and jobs through separate supported procedures.")),
 l("Destination",n("SQL Server on Azure VM","Database catching up from backups","The destination SQL Server restores the backup sequence and remains unavailable for normal application writes until recovery and cutover complete. Compute sizing, SQL configuration, logins and dependent jobs are prepared and validated independently of the database copy.","data","Azure Virtual Machines")),
 l("Cut over",n("Database migration team","Final log backup and application switch","The team stops source writes, captures and applies the final transaction-log backup, verifies all required backups are restored and completes migration cutover. It then redirects the application connection and runs business transaction checks before accepting the new database.","user")));

const gcp=a("GCP: promote a migrated PostgreSQL database","A continuous Database Migration Service job copies PostgreSQL into Cloud SQL and streams changes until the team pauses writes and promotes the destination.","https://docs.cloud.google.com/database-migration/docs/postgres/promote-migration",
 l("Source",n("PostgreSQL source database","Supported replication configuration","The source accepts business transactions while the migration is running. The team configures the supported replication extension, permissions, connectivity and retained-change capacity required by the chosen source and migration path, and inventories objects that need separate migration.","data")),
 l("Migrate",n("Database Migration Service","Initial copy and continuous replication","The migration job uses its configured source and destination profiles to load the supported database contents and replicate subsequent changes. The team monitors job health and replication delay, checks supported versions and resolves unsupported objects before planning promotion.")),
 l("Catch-up target",n("Cloud SQL","PostgreSQL destination","The Cloud SQL destination receives the migration's copied data and ongoing changes. Target capacity, private connectivity, user access and required application settings are tested while the migration remains connected to the source.")),
 l("Promote",n("Migration operator","Pause source writes and promote","The operator stops source application writes, verifies the destination has caught up and initiates promotion. Promotion disconnects the destination from the migration source and makes it independently writable; the operation is an intentional cutover boundary.","user")),
 l("Application switch",n("Business application","Use promoted Cloud SQL database","The application uses the approved Cloud SQL connection and credentials, validates business transactions and resumes writes against the promoted destination. Scheduled jobs, unsupported objects and rollback handling are verified separately instead of being inferred from successful promotion.","app")));

export const reviewedMigrationArchitectures:Record<string,ReviewedArchitecture[]>={
 "AWS Database Migration Service":[aws],"Azure Database Migration Service":[azure],"Database Migration Service":[gcp],
};
