import {n,l,a} from "./reviewed-architecture-builders";
import type {ReviewedArchitecture} from "./reviewed-workload-architectures";

const awsVpn=a("AWS: reach a private inventory API through a routed VPN hub","The branch network sends private inventory requests through a Site-to-Site VPN and Transit Gateway to the attached application VPC.","https://docs.aws.amazon.com/vpc/latest/tgw/how-transit-gateways-work.html",
 l("Branch",n("Branch inventory client","Request private API over approved routes","The branch client resolves the private API and sends its authenticated request toward the enterprise router. Nonoverlapping address ranges, branch routes and private DNS resolution are prepared for this connection; the private route does not authorize inventory operations.","app")),
 l("Encrypted connection",n("AWS Site-to-Site VPN","Configured IPsec tunnels to transit attachment","The enterprise VPN device and AWS VPN endpoints carry the permitted packets through the configured IPsec tunnels. BGP or the chosen static routes define reachability, and the team tests tunnel redundancy rather than assuming one healthy tunnel proves a resilient path.")),
 l("Hub routing",n("AWS Transit Gateway","Attachment route-table selection","The transit gateway uses the route table associated with the ingress attachment to select the application VPC attachment. Propagation and explicit routes supply the intended destinations; return routes and security controls are configured so traffic is not unintentionally shared with unrelated VPCs.")),
 l("Private API",n("Inventory API in application VPC","Authorize and execute inventory query","The VPC route tables and workload security controls allow the intended branch traffic to the API. The handler verifies the caller, executes the permitted inventory query and returns its result over the configured reverse path; VPN encryption and hub routing do not execute the query.","app")));

const dx=a("AWS: privately connect a data-center client to a VPC API","A private virtual interface on Direct Connect reaches the configured virtual private gateway. BGP carries reachability information; application TLS protects the API exchange.","https://docs.aws.amazon.com/directconnect/latest/UserGuide/Welcome.html",
 l("Data center",n("Enterprise API client","Private destination and protected application request","The client requests the permitted private API through the enterprise router using application TLS and its own API credential. The enterprise network advertises and accepts only the intended private prefixes, with DNS and return routing configured for this VPC.","app")),
 l("Connection",n("AWS Direct Connect","Provisioned link and private virtual interface","The provisioned connection and private virtual interface establish the selected private AWS reachability through the configured BGP session. The team separately selects appropriate encryption; a private connection is not automatically an end-to-end encrypted application channel.")),
 l("VPC entry",n("Virtual private gateway","Route private interface traffic to attached VPC","The configured gateway connects the selected private virtual interface path to the VPC. Route propagation or explicit VPC routes and the enterprise advertisements establish both directions; network security rules still restrict the API's permitted sources.","security")),
 l("Application",n("Private enterprise API","Validate caller and return permitted records","The API authenticates the enterprise client and executes its permitted record lookup. The network team verifies the separately designed redundant or backup connectivity path, while the application handles connection failures with its supported retry contract.","app")));

const azureVpn=a("Azure: connect a branch to a private case-management API","A route-based Azure VPN Gateway connects the branch through IPsec; configured BGP routes and VNet controls provide the case API's private path.","https://learn.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-bgp-overview",
 l("Branch client",n("Branch case client","Resolve private API and initiate request","The client sends its authenticated case request to the private API address using the enterprise routing and DNS design. The branch network has nonoverlapping prefixes and an approved VPN device configuration, and the API credential remains independent of the tunnel key.","app")),
 l("Tunnel",n("Azure VPN Gateway","IPsec termination and configured routing","The route-based gateway and branch device establish the configured IPsec connection. Where BGP is enabled, their peer configuration exchanges the intended prefixes; a functioning tunnel still requires usable forward and return routes for the actual client and API subnets.")),
 l("VNet path",n("Case API subnet controls","Routes and permitted network access","The VNet's effective routes, any intended peering gateway-transit configuration and network security rules permit the approved case traffic. A gateway does not automatically make every peered network transitive or bypass the application's subnet controls.","security")),
 l("Case operation",n("Case-management backend","Authorize employee and retrieve case","The handler verifies the employee and requested case permission, queries its authorized data store and returns only allowed fields. The VPN carries the request privately; case ownership and allowed actions are enforced by the backend.","app")));

const gcpVpn=a("GCP: use HA VPN to reach a private warehouse API","HA VPN carries encrypted branch traffic, while Cloud Router exchanges BGP routes used by the VPC routing system. The API validates the caller and executes its own lookup.","https://docs.cloud.google.com/network-connectivity/docs/vpn/how-to/creating-ha-vpn",
 l("Branch",n("Warehouse branch client","Private API request","The branch client resolves the warehouse API and sends its authenticated query toward the configured branch router. The branch advertises only approved private prefixes and has a return path for the API network; overlapping addresses are addressed before connection rollout.","app")),
 l("Connectivity and routing control",n("Cloud VPN","HA VPN encrypted packet path","The HA VPN gateways and configured tunnels carry packets through IPsec between the branch and VPC. Redundant tunnels and compatible peer design are configured and tested for the intended availability; the gateway carries the network exchange rather than executing warehouse business code."),n("Cloud Router","BGP route exchange","Cloud Router manages the configured BGP sessions and creates applicable dynamic routes from the accepted advertisements. It is routing control plane rather than a packet-processing hop; packets follow the VPC routing and VPN data path.")),
 l("VPC access",n("Warehouse VPC controls","Effective routes and firewall rules","The effective VPC route configuration selects the permitted destination and return path, and the workload's firewall controls allow the intended API traffic. Dynamic route availability depends on the configured routing mode and scope; receiving a prefix is not an application-access grant.","security")),
 l("Warehouse backend",n("Private warehouse API","Validate and retrieve stock records","The backend authenticates the client, checks warehouse access and reads its authorized stock records. It returns the result over the configured private path and handles connection failures independently of the Cloud Router configuration lifecycle.","app")));

const awsNat=a("AWS: let a private worker call an external package API","A private IPv4 worker initiates an HTTPS connection through a public NAT gateway and internet gateway; only replies to the established outbound flow return.","https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway.html",
 l("Initiate",n("Private package worker","HTTPS package lookup","The worker validates the package identifier and opens an HTTPS connection to the approved external API. Its subnet routes select the public NAT gateway for this destination, and workload security rules and DNS allow the intended outbound operation.","app")),
 l("Source translation",n("NAT gateways","Public NAT in configured subnet","The selected public NAT gateway translates the private IPv4 source for the outbound connection. Its public-subnet route reaches the internet gateway and its Elastic IP supplies the external source address. This NAT path does not provide unsolicited inbound access to the worker.")),
 l("Internet path",n("VPC internet gateway","Public-address internet connectivity","The attached internet gateway and the public-subnet route provide the configured NAT gateway's internet path. The gateway provides network reachability, while TLS authenticates the external API and protects the application's HTTP exchange.","security")),
 l("External operation",n("Package provider API","Authenticate lookup and return package state","The provider authenticates the worker's API credential and returns permitted package state through the established connection. Operators size and monitor the chosen NAT path and test their availability design; successful address translation is not proof of a successful provider transaction.","app")));

const azureNat=a("Azure: give private integration workers predictable outbound IPs","Workers initiate provider requests from a subnet associated with NAT Gateway. The provider allowlists the configured public egress addresses and still checks its API credential.","https://learn.microsoft.com/en-us/azure/nat-gateway/nat-overview",
 l("Worker",n("Integration worker subnet","Initiate authenticated provider call","The workers connect to the approved provider using HTTPS and their separately configured provider credentials. The subnet's selected routing supports internet egress through the associated NAT design; another next-hop path is not assumed to use this NAT gateway.","app")),
 l("Outbound connectivity",n("Azure NAT Gateway","Translate connections to configured public IPs","The subnet-associated NAT gateway provides the selected outbound source translation and configured public IP or prefix. Replies are associated with the established flow; it is not an inbound listener publishing the integration worker.")),
 l("Provider access",n("Allowlisted provider endpoint","Network allowlist and API authentication","The provider checks the observed source address against the agreed egress allowlist and authenticates the API credential. The allowlist and application authorization are separate checks, and the application handles rate limits and retryable errors under the provider's contract.","app")),
 l("Complete",n("Integration result handler","Persist provider result and manage connections","The handler validates and records the returned provider result, closes or reuses connections under its client policy and uses bounded retries. Operators check connection pressure and required public IP capacity without treating NAT as the application's security-inspection service.","app")));

const gcpNat=a("GCP: provide public egress for a private Compute Engine worker","The worker has no external IP and initiates a permitted public API request. Public NAT configuration controls source translation performed by Google's distributed network data plane.","https://docs.cloud.google.com/nat/docs/public-nat",
 l("Configure egress",n("Cloud NAT","Regional Public NAT source and address configuration","The NAT configuration selects the intended regional subnet ranges and public address allocation, using a Cloud Router resource for its control-plane configuration. Packets do not pass through a Cloud NAT VM or Cloud Router process; the distributed network implements the translation.")),
 l("Initiate request",n("Private Compute Engine worker","HTTPS connection without external VM IP","The worker resolves the public provider and initiates its HTTPS request using an applicable route to the default internet gateway and permitted egress firewall rules. Its source range is included in the selected NAT configuration; the application supplies its provider credential.","app","Compute Engine")),
 l("Packet path",n("Distributed Public NAT data plane","Translate source and match replies","The distributed network translates this eligible outgoing flow under the configured NAT address and port allocation and maps its replies back to the worker. Public NAT does not accept unsolicited inbound connections or replace the VM's network firewall controls.","security")),
 l("Provider response",n("External provider API","Execute permitted request","The provider validates the credential and performs the requested operation, returning the result over the outbound-established connection. The worker records the outcome and handles provider errors; NAT configuration success is checked separately from business request success.","app")));

export const reviewedHybridArchitectures:Record<string,ReviewedArchitecture[]>={
 "AWS Site-to-Site VPN":[awsVpn],"AWS Transit Gateway":[awsVpn],"AWS Direct Connect":[dx],"NAT gateways":[awsNat],
 "Azure VPN Gateway":[azureVpn],"Azure NAT Gateway":[azureNat],
 "Cloud VPN":[gcpVpn],"Cloud Router":[gcpVpn],"Cloud NAT":[gcpNat],
};
