import {n,l,a} from "./reviewed-architecture-builders";
import type {ReviewedArchitecture} from "./reviewed-workload-architectures";

const cfn=a("AWS: review and deploy a private API infrastructure change","A reviewed template and parameters produce a change set; approval executes the intended stack change and the owner verifies the deployed API's dependencies.","https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-stack-drift.html",
 l("Propose",n("Infrastructure repository","Template and environment parameters","The author changes the template for the API's network and compute resources and supplies reviewed environment parameters. Required stateful-resource retention and replacement effects are considered before creating a change set; secrets are not embedded in the template.","data")),
 l("Review",n("CloudFormation change set","Proposed create, modify or replace operations","The change set describes the proposed stack operations for the selected template and current stack. The owner inspects replacements and deletions and checks permissions, quotas and external dependencies; a proposed change is not proof that every operation will succeed.","data","AWS CloudFormation")),
 l("Execute",n("AWS CloudFormation","Dependency-ordered resource operations","After authorized approval, CloudFormation performs the stack operations using its configured execution role and dependency graph. Failure and rollback behavior follows the chosen stack and resource settings; the team checks event details rather than assuming an unsuccessful update erased every side effect.")),
 l("Verify",n("API infrastructure owner","Check resource state and application path","The owner tests the API's intended private access, identity and data dependencies and reviews supported drift checks for later out-of-band changes. A stack completion status describes infrastructure operations; business request validation is a separate acceptance check.","user")));

const stacksets=a("AWS: deploy a reviewed account baseline across an OU","Service-managed StackSets uses trusted Organizations access to deploy a baseline template to the selected member accounts and regions.","https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/stacksets-orgs-activate-trusted-access.html",
 l("Select scope",n("Baseline administrator","Approved template, OU and regions","The administrator selects the reviewed baseline, target OU and deployment regions and verifies the intended member accounts. Failure tolerance, concurrency and automatic-deployment settings are chosen deliberately, including whether new accounts should receive this baseline.","user")),
 l("Organization integration",n("Organizations trusted access","Service-managed deployment preparation","The authorized organization configuration enables the required StackSets trusted access and supported administration model. CloudFormation provisions the required deployment roles for member-account operations; this integration does not turn the baseline template into a universal permission grant.","security","AWS Organizations")),
 l("Deploy baseline",n("CloudFormation StackSets","Stack instances across target accounts","The service-managed StackSet creates or updates stack instances under the selected account and region scope. Each instance has its own operation state; configured concurrency and failure tolerance govern rollout without making every account update an atomic transaction.")),
 l("Review estate",n("Baseline rollout owner","Inspect failures and verify baseline resources","The owner inspects failed or outdated stack instances, checks actual baseline resources and remediates supported drift through the approved process. Automatic deployment to future accounts is verified under the selected OU rules and resource-retention policy.","user")));

const tower=a("AWS: provision a governed application account","Account Factory provisions the selected application account into a registered OU; landing-zone controls, identity assignments and application deployment are checked separately.","https://docs.aws.amazon.com/controltower/latest/userguide/what-is-control-tower.html",
 l("Account request",n("Application platform owner","Account identity and target OU","The owner provides the intended account details, environment purpose and registered target OU through the authorized provisioning path. Account names, contacts and ownership are checked before provisioning so the resulting environment has an accountable team.","user")),
 l("Provision and govern",n("AWS Control Tower","Account Factory and landing-zone controls","Control Tower coordinates the supported Account Factory provisioning and governance baseline within its configured landing zone. The enabled controls' preventive, detective or proactive behavior is distinguished; a compliant dashboard is not permission to deploy any workload.")),
 l("Account hierarchy",n("Application member account","OU policies and scoped team access","The new member account sits in the selected Organizations hierarchy and receives the applicable governance configuration. Administrators separately assign the team's permitted identity access and verify the account's baseline and logging integration before releasing it for use.","security")),
 l("Workload acceptance",n("Application account owner","Deploy approved workload and verify controls","The account owner deploys the approved application through its scoped role, checks required routes and data permissions and confirms relevant control results. Account provisioning creates a governed environment; it does not deploy or validate the team's application automatically.","user")));

const ssm=a("AWS: collect approved diagnostics from selected managed servers","Run Command delivers a reviewed diagnostic document to tagged managed nodes; the agent executes it and the operator checks each invocation result.","https://docs.aws.amazon.com/systems-manager/latest/userguide/run-command.html",
 l("Request",n("Operations engineer","Reviewed document and bounded target set","The engineer selects the approved diagnostic document version, inputs and specific managed-node targets with the intended concurrency and error limits. The calling role permits this document and target scope rather than arbitrary shell access to the entire estate.","user")),
 l("Distribute",n("Systems Manager","Run Command delivery and invocation tracking","Run Command sends the chosen document to reachable managed nodes through the configured agent channel. Node registration, permissions and service reachability are prerequisites, and command and invocation states are checked under the service's eventual-consistency behavior.")),
 l("Execute",n("SSM Agent on managed server","Run diagnostic and capture exit status","The agent executes the document's diagnostic steps under their operating-system context and returns status and configured output. The reviewed script propagates failures correctly so a failing internal check cannot be hidden by a later successful command.","app","Systems Manager")),
 l("Investigate",n("Diagnostic result reviewer","Check every node and protect output","The engineer checks individual invocation status, timeout and result content and follows up on unreachable or failed nodes. Output access and retention are scoped because diagnostics can contain sensitive configuration; one completed invocation does not prove every target succeeded.","user")));

const arm=a("Azure: deploy a reviewed private application resource group","A template deployment is reviewed with what-if and executed through Resource Manager using the intended resource scope and identity.","https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/deployment-modes",
 l("Definition",n("Azure Resource Manager templates","Application resources and parameters","The reviewed template defines the application's selected network, compute and related resource configuration with environment parameters. Dependencies and full intended properties are specified for managed resources, while secrets use approved references rather than plaintext template values.")),
 l("Preview",n("Deployment reviewer","Inspect what-if and permission scope","The reviewer inspects the supported what-if output, target subscription and resource group and checks replacements, permissions and policy effects. The chosen incremental deployment leaves omitted existing resources in place; it can still change properties of resources that are declared.","user")),
 l("Provision",n("Azure Resource Manager","Authorized resource-provider operations","Resource Manager validates the caller's authorization and applicable policy and coordinates the resource-provider operations under the deployment dependencies. Each resource's operation result is checked; the deployment is not assumed to be a database-style atomic transaction.")),
 l("Accept",n("Application infrastructure owner","Verify provisioned access and business request","The owner verifies the deployed resources, intended private route and identity settings and a representative application request. Partial failures are reconciled through the approved deployment procedure rather than treating a resource-group status alone as proof of a working application.","user")));

const automation=a("Azure: stop an approved nonproduction VM on schedule","An Automation runbook authenticates with managed identity, targets the approved VM and verifies the intended deallocated state.","https://learn.microsoft.com/en-us/azure/automation/learn/powershell-runbook-managed-identity",
 l("Schedule",n("Nonproduction shutdown schedule","Approved VM and time window","The schedule starts the reviewed runbook with bounded VM and environment parameters. The owner confirms the timezone, exclusion rules and current maintenance needs before enabling it so a naming error cannot target an unrelated production workload.","data")),
 l("Runbook",n("Automation","Execute reviewed VM shutdown code","The Automation job runs the reviewed stop-and-deallocate procedure with its configured managed identity and environment. The identity receives only the required management scope, and the runbook records the selected VM and operation result without storing a permanent Azure password.")),
 l("Management operation",n("Azure VM resource API","Authorize stop and deallocation","The VM API checks the runbook identity's applicable permissions and executes the requested supported deallocation operation. Deallocation releases the selected compute allocation; persistent disks and other associated resources retain their own lifecycle and charges.","app","Virtual Machines")),
 l("Verify",n("Nonproduction operations owner","Confirm power state and next startup plan","The owner checks terminal job status and the VM's actual power state and investigates failed operations. The application shutdown procedure handles its persistent work beforehand, and a separately approved start schedule restores service when needed.","user")));

const resourceMgr=a("GCP: create a governed development project","An authorized owner creates a project under the intended folder, associates billing through the required billing permissions and verifies inherited policy before application setup.","https://docs.cloud.google.com/resource-manager/docs/creating-managing-projects",
 l("Request",n("Development platform owner","Project identifier and intended parent","The owner requests a unique project identifier and selects the approved organization or folder. Project creation permission is checked on the intended parent, with ownership and lifecycle recorded before the project is handed to a development team.","user")),
 l("Create hierarchy resource",n("Resource Manager","Project parent and policy inheritance","Resource Manager creates and manages the project within its configured hierarchy. The project inherits applicable ancestor policies and IAM controls; the team verifies effective access and constraints instead of assuming the project begins with unrestricted permissions.")),
 l("Billing association",n("Project billing administrator","Approved billing-account linkage","The administrator links the project to the approved billing account using the required project and billing-account permissions. Creating a hierarchy resource and funding its billable services are separate operations, and the owner verifies their status before enabling workload services.","user")),
 l("Team handoff",n("Development project owner","Scoped access and service enablement","The owner grants the intended team and workload identities only their required access, enables the approved APIs under proper permissions and tests a constrained deployment. Project creation itself does not create application compute, networks or databases.","user")));

const monitoring=a("GCP: notify an owner when API latency stays elevated","A metric-threshold policy evaluates the selected API latency series and configured retest window; the owner receives an incident notification and investigates before changing capacity.","https://docs.cloud.google.com/monitoring/alerts/concepts-indepth",
 l("Metric evidence",n("API latency measurements","Configured metric series and resource labels","The application or supported platform metric source records the latency series used by this policy. Units, resource labels and availability of measurements are verified so the alert evaluates the intended API rather than an unrelated aggregate.","data")),
 l("Evaluate",n("Monitoring","Aligned threshold and retest window","Monitoring evaluates the policy's selected series with its configured alignment, aggregation, threshold, retest window and missing-data behavior. When the condition meets the incident criteria, it creates the relevant incident; metric delay and policy settings affect notification timing.")),
 l("Notify",n("Configured notification channel","Deliver latency incident","The enabled notification channel routes the incident message to its verified destination under the selected policy. A delivered notification is diagnostic evidence and does not itself resize the API or execute an application's remediation procedure.","message")),
 l("Investigate",n("API operations owner","Correlate latency and validate fix","The owner checks traces, error patterns and dependency capacity to identify the cause, then applies an approved change and verifies the latency recovery. The incident's lifecycle is checked against fresh measurements rather than equating manual acknowledgment with a resolved performance issue.","user")));

const cloudwatch=a("AWS: alert when receipt jobs remain backlogged","CloudWatch evaluates the selected SQS backlog metric and configured alarm; SNS notifies the owner to investigate worker processing and delivery failures.","https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/AlarmThatSendsEmail.html",
 l("Queue evidence",n("Amazon SQS backlog metrics","Selected receipt queue observations","The supported queue metrics describe the selected receipt queue's backlog or age under their documented semantics. The alarm owner checks the correct queue dimensions, metric period and units before relying on its threshold.","data","Amazon SQS")),
 l("Alarm",n("Amazon CloudWatch","Evaluate queue metric over configured periods","CloudWatch evaluates the selected metric and alarm threshold over the configured periods, with explicit missing-data treatment. The alarm's state transition invokes the configured notification action; this alarm is not configured as an automatic worker-scaling policy.")),
 l("Notification",n("Receipt incident SNS topic","Notify confirmed response subscribers","The configured topic delivers the alarm notification to its authorized confirmed subscribers. Permissions and subscription delivery are verified so an alarm transition has an actual response destination.","message","Amazon SNS")),
 l("Response",n("Receipt worker owner","Inspect stalled jobs and dependency errors","The owner checks worker failures, poison messages, dependency latency and queue delivery before choosing an approved fix or replay. Queue metrics indicate an observed backlog; they do not prove whether insufficient workers or repeated application errors caused it.","user")));

export const reviewedOperationsArchitectures:Record<string,ReviewedArchitecture[]>={
 "AWS CloudFormation":[cfn],"CloudFormation StackSets":[stacksets],"AWS Control Tower":[tower],"Systems Manager":[ssm],"AWS Systems Manager":[ssm],
 "Azure Resource Manager templates":[arm],"Azure Resource Manager":[arm],"Automation":[automation],"Azure Automation":[automation],
 "Resource Manager":[resourceMgr],"Monitoring":[monitoring],"Cloud Monitoring":[monitoring],"Amazon CloudWatch":[cloudwatch],
};
