import {n,l} from "./reviewed-architecture-builders";
import type {ReviewedArchitecture} from "./reviewed-workload-architectures";
type Connection=NonNullable<ReviewedArchitecture["connections"]>[number];
type Context={layers:ReviewedArchitecture["layers"];connections:Connection[]};
const e=(from:string,to:string,label:string,control=false):Connection=>({from,to,label,control});
export const awsOrderSystem:Context={
 layers:[
  l("Client and edge",n("Order portal customer","HTTPS portal and authenticated API requests","The customer loads the portal through CloudFront and signs in through the configured Cognito user pool. The client sends an access token with the order request and a stable request ID for a retried submission.","user"),n("Portal CloudFront distribution","Static portal assets; API requests are not cached","CloudFront serves the portal's static assets from its private S3 origin using configured origin access controls. The portal calls the separate order API directly; personalized order responses are not cached as public static content.",undefined,"Amazon CloudFront")),
  l("Request boundary",n("Order API WAF and gateway","Web ACL plus authenticated REST API route","The regional WAF web ACL associated with the REST API stage evaluates request rules before the accepted request reaches the API integration. The gateway authorizer verifies the configured access token and scopes, then forwards the request context to the order handler.",undefined,"Amazon API Gateway"),n("Customer Cognito user pool","Sign-in and token issuance branch","The configured user pool authenticates the customer and issues tokens for the portal client. The order API validates the appropriate access token independently; token issuance does not grant access to another customer's order or cloud IAM credentials.",undefined,"Amazon Cognito")),
  l("Application and data",n("Order business handler","Validate items and customer ownership","The handler checks trusted customer identity, product data and item quantities, then performs the intended idempotent order transaction. It returns success after its durable completion boundary and reconciles an uncertain write before retrying.","app","AWS Lambda"),n("Order record table","Durable order and request identity","The table persists the order and idempotency record under the handler's restricted role. Conditional writes or a transaction protect repeated submissions, and every customer read is scoped to trusted identity rather than caller-provided ownership.","data","Amazon DynamoDB"))
 ],connections:[e("Order portal customer","Portal CloudFront distribution","static assets"),e("Order portal customer","Order API WAF and gateway","HTTPS + token"),e("Order portal customer","Customer Cognito user pool","sign in"),e("Order API WAF and gateway","Order business handler","authorized route"),e("Order business handler","Order record table","conditional commit")]
};
export const awsDocumentSystem:Context={
 layers:[
  l("User and ingress",n("Document portal client","Authorized upload and retrieval","The client signs in and requests an upload from the document API. The API checks the document scope and returns a restricted presigned upload; the browser then uploads the file directly to the selected S3 input location.","user"),n("Document API WAF and ALB","Inspect HTTPS then route to healthy API targets","The web ACL associated with the ALB evaluates request rules at the public application boundary. Its HTTPS listener terminates TLS using the selected certificate and forwards allowed requests to healthy document API targets, without processing the file contents.",undefined,"Elastic Load Balancing")),
  l("Application services",n("Document authorization API","Validate ownership and issue scoped object access","The backend validates the customer's application identity, records the document identity and issues the permitted upload or download path. Its role restricts bucket operations; a public API endpoint does not make the bucket or uploaded documents public.","app"),n("Document processing queue","Buffer work for committed object references","The application enqueues only a ready document reference using the configured completion notification or explicit confirmation path. Queue retries use the document/run identity and processing acknowledgements follow a durable result.","message","Amazon SQS")),
  l("Protected data",n("Document input bucket","Original customer files and ready-object event","S3 stores the uploaded file under the assigned key and policy. A configured object-created event identifies the object rather than carrying its bytes; processing workers must read the permitted original and avoid retriggering themselves with generated output.",undefined,"Amazon S3"),n("Document result bucket","Private validated outputs and owner-scoped access","The processing worker writes a versioned result to the separate output bucket and records its association with the original document. The API verifies ownership before making the result available through the approved restricted read mechanism.",undefined,"Amazon S3"))
 ],connections:[e("Document portal client","Document API WAF and ALB","HTTPS request"),e("Document API WAF and ALB","Document authorization API","allowed request"),e("Document portal client","Document input bucket","scoped upload"),e("Document input bucket","Document processing queue","ready object event"),e("Document authorization API","Document result bucket","authorized retrieval")]
};
export const awsPrivateSystem:Context={
 layers:[
  l("Private caller",n("Corporate inventory client","Private authenticated inventory request","The corporate client resolves the private inventory endpoint and starts the permitted request through the configured branch connectivity. Network reachability is verified independently from its application credentials and inventory access permissions.","app")),
  l("Network and ingress",n("Inventory VPC routing","Explicit branch and subnet route selection","The selected branch connection and VPC route tables carry the request toward the inventory subnet with a valid return path. Security groups and subnet ACLs restrict the intended port; no transitive connection is inferred from an unrelated peering relationship.",undefined,"Amazon VPC"),n("Internal inventory load balancer","Route to healthy inventory targets","The internal load balancer listens on the configured private endpoint and forwards eligible connections to healthy registered targets. It distributes traffic rather than querying inventory or turning the private backend into a public service.",undefined,"Elastic Load Balancing")),
  l("Inventory workload",n("Private inventory API","Authorize device and stock requests","The API authenticates the corporate requester, validates device and location scope and executes the requested inventory operation. Its database credentials and record authorization remain required even when the private network permits the connection.","app"),n("Inventory database","Durable stock and transaction records","The database checks the configured account permissions and executes the API's bounded transaction or lookup. The API records its idempotency identity for mutations and handles uncertain results before retrying stock changes.","data","Amazon RDS"))
 ],connections:[e("Corporate inventory client","Inventory VPC routing","private connection"),e("Inventory VPC routing","Internal inventory load balancer","routed request"),e("Internal inventory load balancer","Private inventory API","healthy target"),e("Private inventory API","Inventory database","authorized query")]
};
export const azurePortalSystem:Context={
 layers:[
  l("Customer and global ingress",n("Azure portal customer","HTTPS portal and authenticated API call","The customer signs in through the application's configured identity and submits the permitted portal request with its token. The client distinguishes static resources from personalized responses and uses stable request identity for retried changes.","user"),n("Portal Azure Front Door","Edge TLS, WAF and selected regional origin","Front Door terminates edge TLS, evaluates its associated WAF policy and forwards the allowed API request to the selected healthy origin. API responses are excluded from shared caching as configured; static portal assets use their separate cache behavior.",undefined,"Azure Front Door")),
  l("Regional application",n("Portal API Management","Validate token and apply API policies","The regional gateway validates the configured token and operation policies and calls the permitted backend endpoint. It propagates trusted identity context without treating a caller-supplied customer identifier as proof of ownership.",undefined,"API Management"),n("Portal application backend","Validate request and commit business outcome","The backend performs its customer ownership checks and business validation, then commits the accepted operation using its managed identity or approved database credential. Error handling reconciles a retried request rather than repeating a completed mutation.","app")),
  l("Data and background branch",n("Portal business database","Restricted durable records and request IDs","The selected database stores approved business records and request identities under the backend's restricted data permissions. A private access path controls network exposure, while database and row authorization enforce the requested record scope.","data","Azure SQL Database"),n("Portal Service Bus jobs","Background job identity and completion boundary","The backend enqueues a validated job for work that can continue outside the synchronous request. The worker handles redelivery using the job identity and settles the message only after its intended durable business result.",undefined,"Service Bus"))
 ],connections:[e("Azure portal customer","Portal Azure Front Door","HTTPS + token"),e("Portal Azure Front Door","Portal API Management","selected origin"),e("Portal API Management","Portal application backend","authorized operation"),e("Portal application backend","Portal business database","commit or lookup"),e("Portal application backend","Portal Service Bus jobs","background command")]
};
export const azurePrivateSystem:Context={
 layers:[
  l("Corporate caller",n("Azure corporate client","Private inventory request","The corporate client uses the configured private connectivity and DNS to reach the inventory service. Its application token or credential is checked by the backend; membership of a corporate network alone does not authorize stock changes.","app")),
  l("Routing and ingress",n("Inventory Azure Virtual Network","Subnet routes and restricted backend access","The VNet provides the intended subnet and route layout for the corporate request and reply. Selected NSG rules and private endpoints restrict reachability, and any route through an appliance is configured explicitly.",undefined,"Azure Virtual Network"),n("Internal Azure Load Balancer","Layer-four distribution to healthy targets","The internal load balancer receives the permitted private connection and distributes it to healthy backend targets under its configured rule and probe. TLS and inventory request authentication remain with the selected backend listener.",undefined,"Azure Load Balancer")),
  l("Inventory application",n("Azure inventory backend","Validate stock request and query database","The backend validates the caller and warehouse scope, then performs the permitted query or idempotent stock transaction. The owner tests its private dependencies and treats network availability separately from business correctness.","app"),n("Azure inventory data","Durable inventory and mutation identity","The database preserves warehouse records and mutation identities under the backend's restricted permissions. Transaction or conditional-write behavior prevents a replayed request from reserving the same stock twice.","data","Azure SQL Database"))
 ],connections:[e("Azure corporate client","Inventory Azure Virtual Network","private request"),e("Inventory Azure Virtual Network","Internal Azure Load Balancer","eligible connection"),e("Internal Azure Load Balancer","Azure inventory backend","healthy backend"),e("Azure inventory backend","Azure inventory data","restricted query")]
};
export const gcpPortalSystem:Context={
 layers:[
  l("Customer and edge",n("GCP document customer","Authenticated portal request","The customer signs in through the configured application identity and submits an authorized document request over HTTPS. Uploads use the API's restricted object access path; the client does not select another customer's object merely by changing a URL.","user"),n("Document HTTPS load balancer","Cloud Armor policy and backend routing","The external Application Load Balancer uses the configured Cloud Armor policy to evaluate requests before forwarding allowed traffic to its backend service. Static assets may use the separately configured CDN backend; personalized API responses are not assumed publicly cacheable.",undefined,"Cloud Load Balancing")),
  l("Application and asynchronous branch",n("Document Cloud Run API","Validate ownership and record document request","The API verifies the customer identity, validates the document scope and records a stable request ID. It issues restricted object access and publishes the configured work message after the selected completion boundary, instead of reading event metadata as file bytes.",undefined,"Cloud Run"),n("Document Pub/Sub work topic","Reference message and subscriber delivery","The publisher sends the ready document reference and request identity to the topic. The selected subscription delivers it to the worker with configured retry and dead-letter handling; acknowledgement follows the worker's durable completion.",undefined,"Pub/Sub")),
  l("Document data",n("Document Cloud Storage input","Private original objects and access policy","The input bucket stores original documents under restricted object identities. A worker reads the referenced original using its own service account and writes output separately; granting API invocation does not grant bucket reads.",undefined,"Cloud Storage"),n("Document Cloud Storage results","Published outputs and owner-scoped retrieval","The worker writes a versioned normalized output and records its association with the customer's request. The retrieval API checks ownership before supplying the approved download mechanism and avoids publishing partial processing results.",undefined,"Cloud Storage"))
 ],connections:[e("GCP document customer","Document HTTPS load balancer","HTTPS request"),e("Document HTTPS load balancer","Document Cloud Run API","allowed backend request"),e("GCP document customer","Document Cloud Storage input","authorized upload"),e("Document Cloud Run API","Document Pub/Sub work topic","ready document command"),e("Document Cloud Run API","Document Cloud Storage results","authorized read")]
};
export const gcpPrivateSystem:Context={
 layers:[
  l("Corporate caller",n("GCP corporate application","Private warehouse request","The corporate application resolves the private warehouse endpoint and sends an authenticated request over the configured branch connectivity. It carries a stable mutation ID when changing stock, accounting for uncertain replies and retried requests.","app")),
  l("Routing and balancing",n("Warehouse Google VPC","Explicit routes and ingress firewall policy","The VPC route and firewall configuration admits the intended corporate source and backend port with its tested return path. Private connectivity does not imply transitive access to every connected network or grant application data privileges.",undefined,"Virtual Private Cloud (VPC)"),n("Warehouse internal load balancer","Distribute connections to healthy services","The internal load balancer uses the selected forwarding rule, backend and health checks to distribute the permitted request. The configured backend protocol defines connection handling; the load balancer does not reserve stock or execute warehouse business rules.",undefined,"Cloud Load Balancing")),
  l("Warehouse service",n("Warehouse private backend","Validate request and execute stock operation","The backend authenticates the corporate application and validates location and item scope before accessing stock data. It uses bounded retries and the mutation identity to reconcile a completed operation after an interrupted response.","app"),n("Warehouse Cloud SQL records","Durable stock transaction and permitted query","The database executes the backend's authorized transaction and preserves its mutation identity alongside the stock change. Private network reachability and database credentials are checked separately, and replicas are not used as a substitute for backups.",undefined,"Cloud SQL"))
 ],connections:[e("GCP corporate application","Warehouse Google VPC","private connection"),e("Warehouse Google VPC","Warehouse internal load balancer","routed traffic"),e("Warehouse internal load balancer","Warehouse private backend","healthy target"),e("Warehouse private backend","Warehouse Cloud SQL records","stock transaction")]
};
export function completeSystem(focus:ReviewedArchitecture,context:Context,bridge:Connection,stepLabels:string[],control=false):ReviewedArchitecture{
 const connections=[...context.connections,bridge];
 for(let i=0;i<focus.layers.length-1;i++)for(const from of focus.layers[i].nodes)for(const to of focus.layers[i+1].nodes)connections.push(e(from.label,to.label,stepLabels[i]||"reviewed step",control));
 const layers:Array<ReviewedArchitecture["layers"][number]>=[];
 for(let i=0;i<Math.max(context.layers.length,focus.layers.length);i++){
  const runtime=context.layers[i],branch=focus.layers[i];
  layers.push({title:[runtime?.title,branch?.title].filter(Boolean).join(" · "),nodes:[...(runtime?.nodes||[]),...(branch?.nodes||[])].map(node=>node.icon?{...node,kind:undefined}:node)});
 }
 return {...focus,layers,connections};
}
export const connection=e;
export const azureSalesSystem:Context={
 layers:[
  l("Business source",n("Sales operational application","Commit sales and export a completed batch","The application commits accepted sales through its transactional data path. Its export worker selects the intended business interval, writes the complete batch and records its run identity before analytical processing starts.","app"),n("Sales lake source files","Completed raw files and restricted input scope","The selected lake container holds the completed sales files under restricted batch prefixes. File readiness is recorded explicitly so jobs do not read a partially produced business batch; analytical runtime access is separate from customer API invocation.","storage","Azure Data Lake Storage")),
  l("Data orchestration",n("Sales batch orchestration","Select ready batch and record execution state","The orchestrator selects a completed batch and starts the configured transform with its stable run identity. It records retries and errors and exposes the previous accepted dataset until the new version passes publication checks.","app","Azure Data Factory"),n("Sales dataset governance","Approved schema, owners and reader grants","The data owner reviews required fields, sensitive-data restrictions and permitted analytical consumers. Storage and catalog permissions are applied to the accepted data product, and a failed run is not represented as a published business dataset.","security")),
  l("Consumption",n("Sales reporting application","Query accepted dataset and expose permitted metrics","The reporting path uses the approved dataset version and governed measures for the selected business interval. Viewer access and row scope are checked separately from pipeline credentials, and the report exposes refresh/completeness information to its consumers.","app","Power BI"))
 ],connections:[e("Sales operational application","Sales lake source files","completed export"),e("Sales lake source files","Sales batch orchestration","ready batch"),e("Sales dataset governance","Sales reporting application","reader/measure policy",true)]
};
export const gcpSalesSystem:Context={
 layers:[
  l("Operational source",n("Sales source application","Committed transactions and completed extract","The operational application commits sales under its transaction and request-identity design. Its approved extract job selects the required interval and writes the completed batch with reconciliation totals, keeping extraction separate from live customer writes.","app"),n("Sales Cloud Storage landing","Complete files and stable batch manifest","The landing bucket contains the selected completed sales batch under restricted prefixes and its stable manifest or input selection. The processor's service account has only the required file and key permissions; dataset metadata does not itself grant object reads.",undefined,"Cloud Storage")),
  l("Run and governance",n("Sales workflow coordinator","Run identity, retry state and acceptance gate","The configured coordinator selects the completed batch and invokes the approved transformation or load step. It tracks the run and errors, then calls publication only after reconciliation; repeating a failed step preserves the same business batch identity.","app","Workflows"),n("Sales data access owner","Approved dataset readers and sensitive-field scope","The owner defines the permitted analytical consumers and sensitive-field controls for the published sales product. Runtime processing credentials and report-reader grants are distinct, and access is verified on the actual service and selected data scope.","security")),
  l("Consumer",n("Sales analytical consumer","Accepted dataset version and reconciled measures","The reporting application queries the accepted sales version under its governed access, checks the reporting interval and interprets refresh/completeness evidence. It avoids presenting a partial transformation or delayed replication as finalized sales totals.","app","Looker"))
 ],connections:[e("Sales source application","Sales Cloud Storage landing","completed extract"),e("Sales Cloud Storage landing","Sales workflow coordinator","ready input"),e("Sales data access owner","Sales analytical consumer","reader policy",true)]
};
export const awsGameSystem:Context={
 layers:[
  l("Player and edge",n("Authenticated game player","Signed-in score submission and ranking request","The player loads the game assets through the configured CDN and signs in before submitting a score. The score request carries its stable event identity, while anti-cheat and game rules validate whether the proposed result is acceptable.","user"),n("Game CloudFront assets","Static game content from restricted origin","The distribution serves approved static game resources from its restricted origin. Personalized score writes and rankings use the separate authenticated API path and are not accidentally cached as public game files.",undefined,"Amazon CloudFront")),
  l("API boundary",n("Game API WAF and gateway","Inspect request and validate configured player token","The configured WAF association inspects the REST API request and the gateway authorizer validates the selected player token/scopes. Accepted requests reach the game handlers; request admission does not prove the score is legitimate.",undefined,"Amazon API Gateway"),n("Player Cognito user pool","Authenticate player and issue application tokens","The configured user pool authenticates the player and issues the application's selected tokens. The API validates the appropriate access token independently and derives player ownership from trusted identity rather than a supplied player ID.",undefined,"Amazon Cognito"))
 ],connections:[e("Authenticated game player","Game CloudFront assets","static game assets"),e("Authenticated game player","Player Cognito user pool","sign in"),e("Authenticated game player","Game API WAF and gateway","score/ranking HTTPS")]
};
// Security controls are associated branches, not fake processing hops.
awsOrderSystem.layers[0].nodes.push(n("Portal static S3 origin","Private static objects and distribution access","The bucket contains the approved HTML, script and stylesheet release. Its origin-access policy permits the configured CloudFront distribution to fetch those static objects while blocking the selected direct public-read path; customer order data is stored separately.",undefined,"Amazon S3"));
awsOrderSystem.layers[1].nodes.push(n("Order API AWS WAF policy","Rules evaluated on the associated REST API stage","The web ACL evaluates requests for the associated order API stage using its configured managed/custom rules and actions. Allowed requests continue through the API's authorization and routing; WAF blocks or allows matching requests without executing the order handler.",undefined,"AWS WAF"));
awsOrderSystem.connections.push(e("Portal CloudFront distribution","Portal static S3 origin","restricted origin fetch"),e("Order API AWS WAF policy","Order API WAF and gateway","associated request rules",true));
awsDocumentSystem.layers[0].nodes.push(n("Document AWS WAF policy","Web ACL associated with the public ALB","The configured web ACL inspects the document API request at the ALB association and applies the selected actions. Upload permissions and file validation remain with the backend and worker; the WAF rule result is not a converted document or a stored business record.",undefined,"AWS WAF"));
awsDocumentSystem.connections.push(e("Document AWS WAF policy","Document API WAF and ALB","associated web ACL",true));
azurePortalSystem.layers[0].nodes.push(n("Portal Azure WAF policy","Front Door security-policy association","The associated Front Door WAF policy evaluates the configured request rules and applies its prevention/detection actions. It governs the portal's public request boundary while API token validation and customer ownership remain separate backend controls.",undefined,"Azure Web Application Firewall"));
azurePortalSystem.connections.push(e("Portal Azure WAF policy","Portal Azure Front Door","associated edge policy",true));
gcpPortalSystem.layers[0].nodes.push(n("Document Cloud Armor policy","Backend-associated request inspection and action","The selected security policy evaluates the supported incoming requests at its configured load-balancer/backend association. It allows, denies or applies the chosen supported action according to policy; allowed traffic continues to the backend, and Cloud Armor does not execute document conversion.",undefined,"Cloud Armor"));
gcpPortalSystem.connections.push(e("Document Cloud Armor policy","Document HTTPS load balancer","associated security policy",true));
export const gcpEquipmentSystem:Context={
 layers:[
  l("Equipment ingestion",n("Equipment GCP publisher","Device-scoped reading and stable event ID","The publisher uses its configured device credential to submit the selected timestamped reading with a stable event identity. The ingestion contract defines accepted units and device scope, and the publisher checks send outcomes before retrying.","app"),n("Equipment HTTPS ingestion","Load-balanced API with associated Cloud Armor policy","The configured HTTPS load balancer evaluates its associated security policy and forwards allowed ingestion requests to the selected backend. The backend verifies device credentials and fields; an edge allow action does not prove a reading is genuine.",undefined,"Cloud Load Balancing")),
  l("Backend and history",n("Equipment ingestion backend","Validate reading before its durable data path","The backend validates device scope, time and units and selects the intended stable storage key. Retried events preserve their identity so the data writer can prevent double-counting; invalid readings enter the approved rejection process.","app","Cloud Run"),n("Equipment history client","Authenticated bounded history request","The user requests a permitted device and time interval through the equipment application's authenticated query route. The query backend checks ownership and retention before returning the selected data; ingestion credentials do not grant user history access.","user"))
 ],connections:[e("Equipment GCP publisher","Equipment HTTPS ingestion","authenticated reading"),e("Equipment HTTPS ingestion","Equipment ingestion backend","allowed backend request")]
};
export const gcpBookingSystem:Context={
 layers:[
  l("Tenant and ingress",n("Tenant booking customer","Authenticated booking change and request ID","The tenant user signs in through the configured application identity and submits the requested booking change with a stable request identifier. The application derives tenant scope from trusted identity rather than an editable form field.","user"),n("Booking HTTPS frontend","Cloud Armor admission and backend routing","The external HTTPS load balancer uses its configured Cloud Armor association to admit or reject requests, then forwards allowed traffic to the booking service. TLS protects the selected request path while the backend owns booking permissions and concurrency.",undefined,"Cloud Load Balancing")),
  l("Identity and application",n("Booking Identity Platform","Configured tenant sign-in and application tokens","Identity Platform authenticates the user under the configured sign-in and tenant model. The booking API validates the selected token and derives the trusted tenant/user identity independently before accessing a booking entity.",undefined,"Identity Platform"),n("Booking request backend","Validate tenant ownership and accepted booking fields","The backend verifies the caller and the selected booking's tenant ownership, validates the requested changes and invokes the booking transaction under a stable request identity. It returns a confirmed outcome rather than retrying an uncertain mutation blindly.","app","Cloud Run"))
 ],connections:[e("Tenant booking customer","Booking Identity Platform","sign in"),e("Tenant booking customer","Booking HTTPS frontend","HTTPS + token"),e("Booking HTTPS frontend","Booking request backend","authorized route")]
};
export const azureEquipmentSystem:Context={
 layers:[
  l("Equipment source",n("Equipment Azure publisher","Validated reading and device credential","The producer sends the selected timestamped device reading through the approved authentication path with a stable event identity. Units, schema and device ownership are validated, and retries preserve that identity.","app"),n("Equipment Azure ingestion API","Authenticated device endpoint and selected admission rules","The configured API gateway verifies the device credential and operation policy and routes admitted readings to the ingestion handler. The handler validates schema and timestamp before publishing the approved event stream.",undefined,"API Management")),
  l("Processing and consumers",n("Equipment Azure event publisher","Send accepted reading to selected Event Hub","The backend publishes the validated event to the selected hub with the configured partitioning and producer error handling. Send acceptance is distinguished from later analytical ingestion, and the event ID supports downstream reconciliation.","app"),n("Equipment analytics viewer","Authorized device/time report","The analyst uses the permitted reporting path and selected device/time range. The report exposes ingestion freshness and device coverage so late or missing readings are not mistaken for a completed fleet observation.","user"))
 ],connections:[e("Equipment Azure publisher","Equipment Azure ingestion API","device reading"),e("Equipment Azure ingestion API","Equipment Azure event publisher","accepted event")]
};
awsDocumentSystem.layers[1].nodes.push(n("Document conversion worker","Receive ready reference, read original and persist result","The worker receives the ready document reference, checks its request identity and reads the permitted original object. It runs the selected validation/conversion, writes the completed output and records durable completion before acknowledging the queue message. Repeated deliveries reuse the recorded outcome.","app"));
awsDocumentSystem.connections.push(e("Document processing queue","Document conversion worker","ready reference"),e("Document conversion worker","Document input bucket","read original"),e("Document conversion worker","Document result bucket","write completed result"));
azurePortalSystem.layers[2].nodes.push(n("Portal background worker","Execute validated job and settle after durable completion","The worker receives the selected Service Bus job, validates its operation and request identity and performs the approved asynchronous work. It records the durable result before completing the message and handles redelivery without repeating a committed business effect.","app","Azure Functions"));
azurePortalSystem.connections.push(e("Portal Service Bus jobs","Portal background worker","validated job"),e("Portal background worker","Portal business database","idempotent completion"));
gcpPortalSystem.layers[1].nodes.push(n("Document Cloud Run worker","Read original, normalize document and commit output","The worker receives the ready document message and verifies its run identity before reading the original. It executes the selected validation/normalization, writes the accepted output and records completion before acknowledgement. Replayed messages check the existing outcome rather than publish duplicate documents.",undefined,"Cloud Run"));
gcpPortalSystem.connections.push(e("Document Pub/Sub work topic","Document Cloud Run worker","subscription delivery"),e("Document Cloud Run worker","Document Cloud Storage input","authorized original read"),e("Document Cloud Run worker","Document Cloud Storage results","completed output write"));
for(const [context,client,backend,label] of [
 [azurePrivateSystem,"Azure corporate client","Azure inventory backend","Corporate Azure application identity"],
 [gcpPrivateSystem,"GCP corporate application","Warehouse private backend","Corporate GCP application identity"]
] as const){
 context.layers[0].nodes.push(n(label,"Configured corporate OIDC issuer and API audience","The corporate identity provider authenticates the permitted application user or workload and issues the configured API token. The private backend checks issuer, audience, signature, expiration and application scope before authorizing inventory access; a private network connection is not a substitute for that verification.","security"));
 context.connections.push(e(client,label,"application authentication"),e(label,backend,"trusted token validation",true));
}
export const awsTelemetrySystem:Context={
 layers:[
  l("Device and entry",n("Equipment device publisher","Stable reading ID and permitted device credential","The publisher validates the selected equipment reading and sends its stable event identity through the configured authenticated ingestion path. Credentials and device scope are checked before the application accepts it for storage.","app"),n("Equipment ingestion API","WAF-protected API and device authorization","The configured REST API entry evaluates its associated WAF rules and device credential, then routes admitted records to the ingestion handler. The handler validates device scope and reading format before selecting the durable storage or event path.",undefined,"Amazon API Gateway")),
  l("History consumers",n("Equipment history user","Authorized device and time-range query","The user authenticates through the equipment history application's configured identity path and requests only permitted devices and intervals. The API applies device ownership checks independently from the ingestion credentials.","user"),n("Equipment history query backend","Validate access and execute bounded history lookup","The backend verifies the user's device scope and selects the permitted device/time keys or partitions. It pages results and interprets retention and update timestamps instead of treating a historical reading as proof that the equipment is currently online.","app"))
 ],connections:[e("Equipment device publisher","Equipment ingestion API","authenticated reading"),e("Equipment history user","Equipment history query backend","device/time query")]
};
