import {n,l,a} from "./reviewed-architecture-builders";
import type {ReviewedArchitecture} from "./reviewed-workload-architectures";

const tiers=a("AWS: isolate a public order frontend from its private database","Subnet routes define reachability; network ACLs and security groups enforce different traffic boundaries. Only the application executes order logic.","https://docs.aws.amazon.com/vpc/latest/userguide/vpc-security.html",
 l("Network layout",n("Amazon VPC","Public frontend and private database subnets","The VPC contains the frontend and database in separate subnet ranges. Their route tables select the intended destinations; the database subnet has no direct internet gateway route. The VPC establishes network isolation, while the application still authenticates each order.")),
 l("Public ingress",n("Internet gateways","Public IPv4 path to the frontend","The attached internet gateway supports the public subnet's internet route and the frontend's assigned public IPv4 address mapping. A route alone does not make a private address publicly reachable; the frontend also needs the intended address and permitted ingress.")),
 l("Traffic controls",n("Network ACLs","Stateless subnet allow and deny rules","The subnet ACL checks traffic entering or leaving its subnet using ordered rules. The chosen HTTPS and return ephemeral-port rules cover both directions because ACLs are stateless. An allowed packet still has to satisfy the frontend's security group."),n("Amazon EC2 security groups","Stateful frontend and database permissions","The frontend group permits the approved HTTPS callers, and the database group permits its database port only from the frontend's group. Stateful connection tracking admits applicable return traffic; these rules authorize network connections rather than execute or validate orders.")),
 l("Business request",n("Order frontend and private database","Validate order then commit record","The frontend authenticates the customer, validates item quantities and writes the order through its allowed database connection. Database credentials and row authorization remain application responsibilities even when the network permits the connection.","app")));

const ipv6=a("AWS: fetch updates from an IPv6 instance without public inbound access","An IPv6 route through an egress-only internet gateway permits an initiated update fetch and its replies.","https://docs.aws.amazon.com/vpc/latest/userguide/egress-only-internet-gateway.html",
 l("Initiate",n("Private update worker","HTTPS request to update repository","The IPv6-addressed worker starts a permitted HTTPS connection to its trusted package repository. Its subnet selects the egress-only gateway for the applicable IPv6 destination and its security group permits the outbound request.","app")),
 l("Outbound path",n("Egress-only internet gateways","Stateful IPv6 internet egress","The gateway carries the initiated IPv6 flow and its reply traffic while preventing unsolicited internet connections through that gateway. It does not perform IPv4 NAT or verify package signatures; those are separate networking and software checks.")),
 l("Verify package",n("Update installer","Check signature before installation","The installer receives the repository response and validates the package signature and expected version before installation. A successful network exchange is not evidence that the downloaded software is trusted or suitable for the host.","app")));

const peering=a("AWS: let an application query a database in a peered VPC","Nonoverlapping VPCs exchange private traffic through explicit peering routes and database ingress permissions.","https://docs.aws.amazon.com/vpc/latest/peering/what-is-vpc-peering.html",
 l("Query",n("Application VPC client","Private database connection","The client resolves the intended database endpoint and starts its authenticated database request. Its subnet route selects the accepted peering connection for the remote CIDR, with the return path configured in the database VPC.","app")),
 l("Private route",n("VPC peering","Direct connectivity between the two VPCs","The accepted connection carries eligible traffic between these nonoverlapping VPC address spaces. Both sides need the applicable routes and traffic controls. Peering is not transitive and does not let the client borrow the peer's internet gateway or unrelated network connections.")),
 l("Execute query",n("Database VPC service","Restricted database listener and account","The database's network rules admit the selected client path and its database account authorizes the requested query. The engine executes the query and returns the permitted rows; peering supplies connectivity without granting database access.","data")));

const logs=a("AWS: investigate rejected connections using VPC Flow Logs","Flow records provide network evidence for an incident investigation; they are not a packet capture or a traffic-blocking engine.","https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs.html",
 l("Observe",n("Application network interface","Failed database connection","The application attempts a database connection on the expected address and port. Its interface is within the configured flow-log scope; the operator records the request time and endpoint pair to correlate the failure with network observations.","app")),
 l("Record",n("VPC Flow Logs","Configured interface traffic metadata","Flow Logs records the available connection metadata and accept/reject observations under the selected format and aggregation settings. Its configured destination permissions permit delivery; records can be delayed and do not contain application payloads.")),
 l("Investigate",n("Network investigator","Correlate records and inspect controls","The operator compares source, destination, port and time with the application's error, then checks routes, ACLs and security groups. A rejected record narrows the investigation but is not a complete explanation of every firewall rule or application authentication failure.","user")));

const reach=a("AWS: locate a configuration barrier to a database connection","Reachability Analyzer models an identified network path; a subsequent permitted live test checks the actual endpoint.","https://docs.aws.amazon.com/vpc/latest/reachability/how-reachability-analyzer-works.html",
 l("Select path",n("Network operator","Source, destination and database port","The operator selects the application interface, database interface and supported protocol/port for the analysis. The question is whether the supported network configuration allows that path, not whether the database account can authenticate.","user")),
 l("Analyze configuration",n("VPC Reachability Analyzer","Model routes and network controls","The analyzer evaluates the supported resource configuration and identifies a reachable path or blocking component. It does not send test packets or verify that the database process is listening, and supported-component limitations are considered before relying on the result.")),
 l("Verify repair",n("Database connectivity test","Authorized live request after reviewed change","The operator applies the approved route or rule repair, reruns the analysis and executes a permitted database connection test. The live test verifies the listener and credentials as well as the repaired network path.","app")));

const access=a("AWS: find unintended internet paths to protected interfaces","A defined Network Access Scope describes prohibited paths; analysis findings guide reviewed network changes.","https://docs.aws.amazon.com/vpc/latest/network-access-analyzer/what-is-network-access-analyzer.html",
 l("Define prohibited path",n("Security network owner","Internet source to protected resource scope","The owner defines a Network Access Scope identifying the protected interfaces and the internet-originating paths to detect. Approved exceptions are narrow and reviewed, so an exclusion does not hide unrelated exposure.","user")),
 l("Model access",n("AWS Network Access Analyzer","Find matching potential network paths","The service evaluates supported network configurations against the scope and reports matching potential paths. Its findings describe modeled reachability, not observed exploit activity or packet inspection; the owner checks unsupported resource and protocol limitations.")),
 l("Remove exposure",n("Network change owner","Review path and restrict the entry point","The owner inspects each finding's route and control sequence, validates the intended service access and applies an approved repair. A repeat analysis checks the original prohibited path, and a permitted live test confirms required application access remains available.","user")));

const eip=a("AWS: retain a public IPv4 address during a reviewed host replacement","An Elastic IP association is moved to the prepared replacement interface; application health and existing sessions are managed separately.","https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/elastic-ip-addresses-eip.html",
 l("Prepare replacement",n("Replacement service host","Configured application and allowed public path","The operator deploys the replacement host with the required listener, data dependencies and security-group rules and verifies its readiness. Moving a public address does not copy application files or migrate established client sessions.","app")),
 l("Reassociate",n("Elastic IP Addresses","Allocated public IPv4 association","The authorized operator reassociates the allocated Elastic IP with the intended replacement interface in its supported scope. The public subnet still needs its internet route, and reassociation can interrupt existing connections while new connections reach the replacement.")),
 l("Validate",n("Service owner","Public endpoint and client retry check","The owner checks a new request through the retained address, confirms the response and verifies client retry behavior. The address remains stable but host replacement still requires an explicit application cutover and rollback procedure.","user")));

export const reviewedScale01:Record<string,ReviewedArchitecture[]>={
 "Amazon VPC":[tiers],"Amazon EC2 security groups":[tiers],"Network ACLs":[tiers],"Internet gateways":[tiers],
 "Egress-only internet gateways":[ipv6],"VPC peering":[peering],"VPC Flow Logs":[logs],
 "VPC Reachability Analyzer":[reach],"AWS Network Access Analyzer":[access],"Elastic IP Addresses":[eip]
};
