import type {ReviewedNode,ReviewedArchitecture} from "./reviewed-workload-architectures";
const n=(label:string,sub:string,detail:string,kind?:ReviewedNode["kind"],icon?:string):ReviewedNode=>({label,sub,detail,kind,icon});
const l=(title:string,...nodes:ReviewedNode[])=>({title,nodes});
const a=(title:string,note:string,reference:string,...layers:ReviewedArchitecture["layers"]):ReviewedArchitecture=>({title,note,reference,layers});

const awsSecret=a("AWS: retrieve a reporting database credential at runtime","A reporting worker retrieves its authorized database secret and uses it to run a read-only report. Secret retrieval, database login and credential rotation are separate operations.","https://docs.aws.amazon.com/secretsmanager/latest/userguide/best-practices.html",
 l("Runtime identity",n("Reporting worker","Task role and secret identifier","The worker uses its workload role to request only the configured reporting credential. The secret identifier is configuration, not the password itself; the worker avoids embedding credentials in its image and limits any in-memory caching to the chosen refresh policy.","app")),
 l("Retrieve",n("AWS Secrets Manager","Authorized secret version","Secrets Manager checks the caller's applicable permissions and returns the selected secret version over the authenticated API connection. The worker needs the required access to the secret and its customer-managed KMS key where applicable; retrieving a password does not grant database privileges.")),
 l("Connect and report",n("Reporting database client","Authenticate and execute bounded query","The client extracts the database endpoint and reporting credential, opens a protected database connection and executes the approved report query. It handles credential changes by refreshing and reconnecting according to its policy rather than logging the secret on authentication failures.","app")),
 l("Database",n("Reporting database","Read-only reporting permissions","The database authenticates the supplied reporting user and restricts its queries using database permissions. Its account is separately provisioned with the necessary read scope; Secrets Manager is the credential store, not the database's table-access enforcement mechanism.","data")),
 l("Credential lifecycle",n("Credential rotation owner","Configure and verify coordinated rotation","The owner configures a supported rotation workflow that changes the database credential and secret versions together, tests new connections and verifies consumer refresh behavior. Simply creating a secret or adding a version does not change the database password.","user")));

const azureSecret=a("Azure: obtain a payment-provider credential with managed identity","An App Service backend authenticates to Key Vault using its managed identity, retrieves the permitted provider secret and calls the payment provider using that credential.","https://learn.microsoft.com/en-us/azure/key-vault/general/authentication",
 l("Application identity",n("Azure App Service payment backend","Managed identity and vault request","The backend validates the customer's payment instruction and uses a configured managed identity to request an access token for Key Vault. The identity removes the need for an embedded Azure client secret; it does not remove the payment provider's separate credential requirement.")),
 l("Authenticate",n("Microsoft Entra ID","Token for the workload identity","Entra issues the Key Vault audience token through the supported managed-identity flow. The token represents the backend's Azure identity; vault data permissions and network reachability still determine whether the requested secret can be read.")),
 l("Secret read",n("Azure Key Vault","Permitted provider secret version","Key Vault checks the request's identity, configured data-access authorization and network controls and returns the permitted secret version. The backend caches it only under a defined refresh policy and does not expose it to the browser or include it in application logs.")),
 l("Provider operation",n("Payment provider API","Authorize and perform payment operation","The backend calls the provider using the retrieved credential and the validated payment instruction with the provider's idempotency mechanism. The provider applies its own account permissions and payment rules; Key Vault does not execute or approve the payment.","app")),
 l("Rotate",n("Payment credential owner","Change provider credential and update vault","The owner coordinates a provider-supported credential change with a new vault version and tests backend refresh and rollback. Vault versioning retains secret history; it does not automatically rotate every external provider's credentials.","user")));

const gcpSecret=a("GCP: access a shipping-provider token from Secret Manager","A shipping worker uses its runtime service identity to read a specific secret version and create a shipment through the provider's API.","https://docs.cloud.google.com/secret-manager/docs/access-secret-version",
 l("Runtime",n("Shipping worker","Workload identity and secret-version request","The worker validates the order's shipping request and calls Secret Manager with credentials supplied by its configured runtime identity. The requested secret version is controlled by deployment configuration; no downloaded service-account key or provider token is baked into the image.","app")),
 l("Authorize secret read",n("Secret Manager","Enabled version and secret-level access","Secret Manager verifies that the caller may access the selected enabled secret version and returns its payload. A narrowly scoped Secret Accessor grant allows payload access; administrative access and disabled or destroyed version behavior are separate concerns.")),
 l("Use credential",n("Shipping API client","Submit authorized shipment request","The client holds the token only for the required operation, submits the validated address and package details and uses the provider's retry and idempotency contract. Errors are recorded without leaking the token or customer data.","app")),
 l("Provider",n("Shipping provider","Create shipment and tracking identifier","The provider authenticates the submitted token, validates the shipment under the customer's provider account and returns its tracking identifier. Secret Manager supplies the credential but does not choose a carrier, calculate the shipment or grant provider-side permissions.","app")),
 l("Version rollout",n("Secret release owner","Coordinate token replacement","The owner changes the provider credential, adds the replacement secret version and deliberately updates or refreshes consumers after testing. A rotation schedule requires an implemented handler or operational process; a notification alone does not rotate the provider token.","user")));

const awsEnvelope=a("AWS: envelope-encrypt a confidential export","The export worker encrypts the document locally with a data key; KMS protects that data key and storage retains the encrypted document and wrapped key.","https://docs.aws.amazon.com/kms/latest/APIReference/API_GenerateDataKey.html",
 l("Prepare",n("Confidential export worker","Authorized export and encryption context","The worker creates the authorized export and chooses its authenticated encryption format and nonsecret encryption context. It requests a data key for the configured symmetric KMS key; context values must not contain confidential payloads.","app")),
 l("Protect data key",n("AWS KMS","GenerateDataKey for configured key","KMS evaluates the key policy and caller permissions and returns a plaintext data key and an encrypted copy protected by the KMS key. The wrapping key remains managed by KMS; the document's bulk encryption occurs in the application.")),
 l("Encrypt document",n("Local encryption library","Encrypt export and erase plaintext data key","A vetted authenticated-encryption library uses the plaintext data key to encrypt the export with the required nonce and metadata. The worker removes the plaintext key from use after encryption and retains the wrapped key with the encrypted message format.","security")),
 l("Store",n("Encrypted export object","Ciphertext and encrypted data key","Storage retains the encrypted document, encrypted data key and required nonsecret metadata. These items are sufficient for a properly authorized decryptor to reconstruct the encryption operation, but the plaintext data key is not written into the object.","storage")),
 l("Authorized read",n("Export decryptor","Unwrap key and decrypt locally","The reader first passes the application's export authorization, then requests KMS decryption of the wrapped key using the required context. It decrypts and verifies the message locally with the returned data key; access to stored ciphertext alone does not satisfy both authorization boundaries.","app")));

const gcpEnvelope=a("GCP: encrypt a confidential archive with a wrapped data key","A vetted application encryption library generates a data key, Cloud KMS wraps it, and an authorized reader later unwraps it to decrypt the archive locally.","https://docs.cloud.google.com/kms/docs/envelope-encryption",
 l("Create archive",n("Archive encryption worker","Generate fresh data key","The worker creates the permitted archive and uses a vetted cryptographic library to generate a fresh data-encryption key. It encrypts the archive locally with authenticated encryption and the required nonce and associated-data handling.","app")),
 l("Wrap key",n("Cloud KMS","Encrypt data key with wrapping key","The authorized worker calls Encrypt on the configured symmetric CryptoKey to protect the data key. Cloud KMS uses the applicable key version and permissions; it wraps the small key material rather than receiving the archive for bulk encryption.")),
 l("Retain ciphertext",n("Archive object store","Encrypted archive and wrapped key","The object store retains the encrypted archive, wrapped data key and required format metadata. The worker discards its plaintext key after completing the write; the storage record does not contain an unprotected copy of the data key.","storage")),
 l("Authorize read",n("Archive reader","Check archive access and request unwrap","The reader verifies that the user may access this archive and obtains the encrypted object. Its configured identity requests KMS Decrypt for the wrapped key under the applicable key-version and access rules.","app")),
 l("Decrypt",n("Local decryption library","Authenticate and recover archive bytes","The library uses the unwrapped data key to decrypt and authenticate the encrypted archive. It rejects an invalid authentication tag or mismatched associated data and releases plaintext only through the application's approved read path.","security")));

export const reviewedSecretsArchitectures:Record<string,ReviewedArchitecture[]>={
 "AWS Secrets Manager":[awsSecret],"Azure Key Vault":[azureSecret],"Secret Manager":[gcpSecret],
 "AWS KMS":[awsEnvelope],"Cloud KMS":[gcpEnvelope],
};
