import type {ReviewedNode,ReviewedArchitecture} from "./reviewed-workload-architectures";
const n=(label:string,sub:string,detail:string,kind?:ReviewedNode["kind"],icon?:string):ReviewedNode=>({label,sub,detail,kind,icon});
const l=(title:string,...nodes:ReviewedNode[])=>({title,nodes});
const a=(title:string,note:string,reference:string,...layers:ReviewedArchitecture["layers"]):ReviewedArchitecture=>({title,note,reference,layers});

const aws=a("AWS: cache frequently read catalog descriptions","The API checks ElastiCache first; a miss makes the API read the database and populate a short-lived cache entry. Checkout pricing remains authoritative.","https://docs.aws.amazon.com/AmazonElastiCache/latest/dg/Strategies.html",
 l("Request",n("Catalog API","Choose key and check cache","The handler derives the product-description cache key and performs a cache read. On a hit it returns the permitted cached description; on a miss it queries the authoritative database. The application implements this branching rather than asking the cache to fetch missing database rows.","app")),
 l("Cache lookup",n("Amazon ElastiCache","Shared expiring description entries","The configured Redis-compatible cache stores product descriptions under application-defined keys and returns the value or a cache miss. Expiration and eviction can remove entries, so the application tolerates misses and does not make this cache the only copy of catalog data.")),
 l("Miss branch",n("Catalog database","Authoritative product description","The application queries this database only when the cached description is unavailable or must be refreshed. The database returns the current record; cache population is a subsequent application operation rather than an automatic database-to-cache transfer.","data")),
 l("Fill cache",n("Catalog cache writer","Set value with bounded TTL","After a successful database read, the application writes the description and expiration to the cache. Product edits trigger the designed invalidation or versioning path, and concurrent fills are handled so stale data is bounded by the chosen cache policy.","app")),
 l("Return",n("Catalog response","Render description","The client receives the description from the hit or miss branch. This cache accelerates browsing; purchase authorization, inventory reservation and final pricing are checked against their authoritative business systems.","app")));

const azure=a("Azure: cache support knowledge articles","The portal reads a shared Redis cache and fetches the approved article from the content store only on a miss; article edits invalidate the relevant key.","https://learn.microsoft.com/en-us/azure/architecture/patterns/cache-aside",
 l("Read request",n("Support portal API","Look up article key","The portal validates the caller's access, selects a key incorporating the article and relevant audience or version, and reads the shared cache. A cache miss makes the portal query the content store; the application owns both operations.","app")),
 l("Shared cache",n("Azure Managed Redis","Expiring article content","Managed Redis holds the permitted article content for reuse across portal instances. The configured client authenticates and connects using the supported protected connection; the cache returns keys and values rather than authoring articles or enforcing the portal's user permissions.")),
 l("Miss branch",n("Article content store","Published authoritative article","The store returns the currently published article when the portal requests it after a cache miss. Drafts and restricted content remain governed by the store and application authorization; a cache key must not allow one audience to receive another audience's private article.","data")),
 l("Cache fill or edit invalidation",n("Portal content handler","Populate TTL or remove changed key","The read handler caches the authorized published article with a bounded TTL after a successful store read. The edit workflow commits the authoritative change and invalidates the corresponding key, accounting for races between reads and edits.","app")),
 l("Display",n("Support portal response","Render approved article","The portal returns the authorized article from the appropriate hit or miss branch. If Redis is temporarily unavailable, its configured fallback reads the content store within rate and timeout limits rather than treating the cache as the sole source.","app")));

const gcp=a("GCP: cache computed regional delivery estimates","The delivery API checks a Redis Cluster key; on a miss it reads route data, calculates an estimate and caches it briefly for matching requests.","https://docs.cloud.google.com/memorystore/docs/cluster/connect-cluster-instance",
 l("Request",n("Delivery estimate API","Select route and service-level key","The handler validates the requested destination and service level, derives their cache key and uses a cluster-aware client to read the estimate. A missing value triggers its route-data query and estimate calculation; the cache does not perform the delivery calculation.","app")),
 l("Cluster cache",n("Memorystore for Redis Cluster","Sharded estimate entries","The configured cluster stores short-lived estimate values across its shards. The application uses supported cluster discovery, authentication and TLS settings, handles redirections and tolerates expiry or eviction. Cluster connectivity does not make cached estimates authoritative delivery commitments.")),
 l("Miss branch",n("Delivery route data store","Current route and cutoff inputs","The API queries current route schedules and cutoff information when its cache key is missing. These inputs feed the application's estimate calculation; the store does not push every update directly into the cache.","data")),
 l("Compute and cache",n("Delivery calculation handler","Calculate estimate and set expiration","The handler computes the requested estimate from the route inputs and current cutoff context, then writes the result with a TTL that respects the next relevant cutoff. The key and invalidation design prevent reuse across incompatible destinations or service levels.","app")),
 l("Response",n("Delivery estimate response","Return bounded estimate","The client receives the calculated or cached estimate with the application's stated validity. Final booking and dispatch use current authoritative capacity and cutoff checks; the cache result alone does not reserve a delivery slot.","app")));

export const reviewedCacheArchitectures:Record<string,ReviewedArchitecture[]>={
 "Amazon ElastiCache":[aws],"Azure Managed Redis":[azure],"Memorystore for Redis Cluster":[gcp],
};
