import {n,l,a} from "./reviewed-architecture-builders";
import type {ReviewedArchitecture} from "./reviewed-workload-architectures";
const express=a("Azure: carry corporate inventory requests over ExpressRoute","Private peering supplies the corporate network path; the gateway and VNet routes deliver the request to the private application.","https://learn.microsoft.com/en-us/azure/expressroute/expressroute-introduction",
 l("Corporate edge",n("Corporate ExpressRoute router","Approved prefixes and redundant peering","The enterprise router advertises the selected corporate prefixes and receives permitted Azure private routes through the provider connection. Redundant links and BGP behavior are tested; private connectivity is supplemented by the required application encryption.","app")),
 l("Circuit",n("Azure ExpressRoute","Private peering to the chosen Azure network","The provisioned circuit and private peering connect the corporate network to Azure under the provider and routing configuration. The VNet connection uses its configured ExpressRoute gateway; a private circuit does not automatically encrypt every application packet.")),
 l("VNet delivery",n("Inventory ExpressRoute gateway","VNet connection and effective route checks","The gateway connects the circuit to the inventory VNet and supplies the configured private routing path. The owner verifies learned routes, return routing and NSG permissions before accepting a live inventory request.",undefined,"Azure ExpressRoute")));
const lb=a("Azure: distribute private inventory connections across backend instances","Layer-four balancing selects a healthy target while the backend owns TLS and inventory processing.","https://learn.microsoft.com/en-us/azure/load-balancer/load-balancer-overview",
 l("Connection",n("Corporate inventory connection","Private frontend IP and service port","The client opens a permitted connection to the internal load-balancer frontend and intended service port. Routes and NSG rules admit the connection and health probes while keeping unrelated listeners restricted.","app")),
 l("Balance",n("Azure Load Balancer","Frontend rule, backend pool and probe","The configured rule maps the incoming transport connection to a healthy backend from its pool under the selected distribution behavior. The probe tests the defined readiness signal; a successful probe is supplemented by application-specific inventory tests.")),
 l("Process",n("Inventory backend instances","Execute authorized stock request","The selected instance terminates the chosen application protocol, authenticates the corporate caller and executes the stock operation against shared durable state. Reconnecting to another instance does not duplicate a mutation because the request identity is checked.","app")));
const tm=a("Azure: select a healthy regional portal endpoint with DNS","Traffic Manager answers DNS based on the profile; clients connect directly to the returned regional endpoint.","https://learn.microsoft.com/en-us/azure/traffic-manager/traffic-manager-routing-methods",
 l("Resolve",n("Portal DNS resolver","Lookup before establishing HTTPS session","The customer's resolver queries the portal name and caches the answer under its applicable TTL behavior. DNS failover therefore affects later resolution and connections rather than moving an established HTTPS session instantly.","app")),
 l("Select region",n("Azure Traffic Manager","Priority policy and endpoint health","The profile evaluates its configured priority routing and endpoint health to return the intended eligible regional endpoint. Traffic Manager is a DNS decision service; the customer's application request does not flow through it.")),
 l("Serve region",n("Regional portal ingress","Direct TLS connection to selected endpoint","The client connects directly to the resolved regional ingress, where the configured WAF and application policies are enforced. The owner tests replication, failover readiness and client DNS behavior before relying on regional continuity.","app")));
const bastion=a("Azure: administer a private VM through Bastion","The administrator reaches the Bastion session endpoint; Bastion connects privately to the approved VM management port.","https://learn.microsoft.com/en-us/azure/bastion/bastion-overview",
 l("Authenticate",n("Authorized VM administrator","Reviewed portal session and VM credentials","The administrator uses the authorized Azure access path and the approved VM credential or supported sign-in method. Scope and session permissions restrict administration to the intended VM rather than exposing a public SSH or RDP listener.","user")),
 l("Connect privately",n("Azure Bastion","Managed session to VM private address","The configured Bastion deployment establishes the supported management session over the VM's private IP. Its subnet and VM NSGs allow the required path; supported SKU and client options determine the session method and related controls.")),
 l("Administer",n("Private application VM","Execute approved maintenance command","The VM verifies the management identity and executes the administrator's approved command under guest permissions. The operator checks the command result and application health before ending maintenance; session connectivity is not permission to make arbitrary production changes.","app")));
const firewall=a("Azure: restrict a private worker's outbound provider connection","A subnet route sends selected egress through Azure Firewall, which enforces the configured destination policy.","https://learn.microsoft.com/en-us/azure/firewall/overview",
 l("Outbound request",n("Private integration worker","HTTPS call to approved provider","The worker resolves the provider and initiates a permitted authenticated request. Its effective route directs the relevant destination through the firewall and its application validates the provider response; provider credentials remain separate from network allowlisting.","app")),
 l("Inspect and allow",n("Azure Firewall","Configured application/network rules and egress","The firewall evaluates the routed connection against the configured rules and supported inspection settings and applies the appropriate source translation. TLS inspection requires its explicit supported configuration; allowing a destination does not execute the provider operation.")),
 l("Provider",n("Approved external provider","Authenticate and answer business request","The provider checks the worker's credentials and performs the requested operation, returning its reply over the established connection. The worker handles errors and records its durable result independently of the firewall's allow decision.","app")));
const ddos=a("Azure: mitigate a flood against a protected public application IP","The selected DDoS protection scope mitigates supported network attacks while the ingress continues its application checks.","https://learn.microsoft.com/en-us/azure/ddos-protection/ddos-protection-overview",
 l("Protection scope",n("Protected Azure public IP","Supported endpoint and protection enrollment","The owner enables the chosen DDoS protection option for the supported public IP/resource scope and verifies its association. Alerting and incident contacts are tested so mitigation evidence can be interpreted during an availability incident.","security")),
 l("Mitigate flood",n("Azure DDoS Protection","Detect and mitigate network-layer attack traffic","The service detects and mitigates supported volumetric and protocol attacks affecting the enrolled resource. Application-layer abuse remains subject to WAF and backend controls; the owner distinguishes a network flood from legitimate load or credential misuse.")),
 l("Assess availability",n("Application availability owner","Check mitigation and customer request success","The owner correlates mitigation observations with customer endpoint health, checks origin capacity and follows the incident response plan. Protected resource enrollment is verified separately from the application recovery and regional continuity procedures.","user")));
const vnet=a("Azure: separate application and database network access","The VNet's subnets and NSGs restrict the application path while the database retains its own access controls.","https://learn.microsoft.com/en-us/azure/virtual-network/virtual-networks-overview",
 l("Application subnet",n("Inventory application subnet","Allowed service and database destinations","The subnet hosts the private application interfaces under the selected route table and NSG rules. Its egress path and database resolution are tested without assuming that placement in the same VNet authorizes all east-west traffic.","app")),
 l("Network boundary",n("Azure Virtual Network","Subnet addressing, routes and network controls","The VNet provides the configured address spaces and subnet connectivity, with route and NSG policy selecting permitted paths. The chosen private endpoint and DNS resolve the database's approved private access path; IAM and data permissions remain separate.")),
 l("Database access",n("Private inventory database connection","Private endpoint resolution and database login","The backend connects through the intended private path and authenticates with its approved database identity. It executes only the permitted stock query or transaction; private DNS and routing do not bypass database authorization.","data")));
const wan=a("Azure: connect two corporate branches through a Virtual WAN hub","Managed hub connectivity and routing connect selected branches to the inventory VNet under the chosen isolation policy.","https://learn.microsoft.com/en-us/azure/virtual-wan/virtual-wan-about",
 l("Branches",n("Corporate branch VPN peers","Redundant tunnels and advertised prefixes","The branch devices establish the configured site-to-site tunnels to the selected hub and advertise approved prefixes. Compatibility, redundancy and routing policy are tested before enabling production inventory traffic.","app")),
 l("Hub",n("Azure Virtual WAN","Hub gateway connections and route tables","The virtual hub's managed gateway connections and route-table associations/propagations select which branch and VNet prefixes can communicate. Secure-hub inspection requires its configured routing intent or policy; hub membership alone is not blanket access.")),
 l("Application VNet",n("Connected inventory VNet","Private route and backend permissions","The connected VNet supplies the intended backend subnet and return path. NSG and application permissions restrict inventory access, and the operator checks effective hub routes when validating branch isolation.",undefined,"Azure Virtual Network")));
const routes=a("Azure: exchange appliance routes without making Route Server a packet hop","BGP advertisements affect effective VNet routes; traffic follows the selected appliance path.","https://learn.microsoft.com/en-us/azure/route-server/overview",
 l("Advertise",n("Network virtual appliance","BGP peering and permitted network prefixes","The appliance peers with the configured Route Server instances and advertises the intended reachable prefixes. Its forwarding, health and redundancy are independently configured, since a BGP session alone does not validate packet processing.","app")),
 l("Routing control",n("Azure Route Server","Exchange dynamic routes with supported peers","Route Server exchanges BGP routes between the configured appliances and supported Azure networking components under its routing settings. It updates route knowledge rather than carrying application packets through its own process.")),
 l("Packet path",n("Inventory VM effective route","Forward traffic via selected next hop","The VM's effective route directs the inventory connection to the selected next hop, including the appliance where intended. The owner tests the actual packet path and return routing separately from the BGP control-plane state.","app")));
const watcher=a("Azure: diagnose a failed private inventory connection","Network Watcher tests the selected supported path and exposes evidence for a reviewed repair.","https://learn.microsoft.com/en-us/azure/network-watcher/network-watcher-overview",
 l("Capture failure",n("Inventory support engineer","Endpoint, protocol and incident time","The engineer records the client and backend endpoints and selects the appropriate supported troubleshooting tool. VM extension prerequisites and scope are checked before treating the diagnosis as valid for the failed connection.","user")),
 l("Diagnose",n("Azure Network Watcher","Connection and effective-rule investigation","The selected connection troubleshooting or IP flow verification operation evaluates the relevant connectivity or NSG-rule question. Packet capture is a distinct configured tool; the engineer interprets each result according to what that tool actually tests.")),
 l("Repair",n("Network change reviewer","Correct route/rule and verify live request","The reviewer validates the identified cause, applies the approved route or access-rule change and tests the authenticated inventory request. A network test cannot establish that an incorrect database password or application ownership check is fixed.","user")));
export const reviewedScale05:Record<string,ReviewedArchitecture[]>={
 "Azure ExpressRoute":[express],"Azure Load Balancer":[lb],"Azure Traffic Manager":[tm],"Azure Bastion":[bastion],
 "Azure Firewall":[firewall],"Azure DDoS Protection":[ddos],"Azure Virtual Network":[vnet],"Azure Virtual WAN":[wan],
 "Azure Route Server":[routes],"Azure Network Watcher":[watcher]
};
