import type {ReviewedNode,ReviewedArchitecture} from "./reviewed-workload-architectures";
const n=(label:string,sub:string,detail:string,kind?:ReviewedNode["kind"],icon?:string):ReviewedNode=>({label,sub,detail,kind,icon});
const l=(title:string,...nodes:ReviewedNode[])=>({title,nodes});
const a=(title:string,note:string,reference:string,...layers:ReviewedArchitecture["layers"]):ReviewedArchitecture=>({title,note,reference,layers});

const ecs=a("AWS: build and release a containerized order API","CodePipeline coordinates a tested image build, publication to ECR and a standard ECS service deployment. Fargate starts the image; the container implements the order API.","https://docs.aws.amazon.com/codepipeline/latest/userguide/ecs-cd-pipeline.html",
 l("Source",n("Order API repository","Reviewed source revision","The configured source action supplies the reviewed commit and build configuration to the pipeline. The commit identifies the code to test and package; a source event alone is not evidence that the image is safe or deployable.","data")),
 l("Coordinate release",n("AWS CodePipeline","Build, approval and ECS deploy actions","The configured pipeline starts the build action, checks its result, waits for the chosen approval gate and runs the standard ECS deploy action. That action uses the image-definitions artifact and existing service task definition to create the deployment's task-definition revision.")),
 l("Build and test",n("AWS CodeBuild","Produce tested image and image definitions","The build executes the project's tests, builds the container image and pushes it to the selected ECR repository using its build role. It emits imagedefinitions.json with the exact service container name and approved image URI; failed tests prevent the configured release from advancing.")),
 l("Image artifact",n("Amazon ECR","Versioned container image","The private repository stores the image manifest and layers under the release's immutable identifier. Deployment and runtime principals receive their required registry access separately; storing the image does not launch an order API or authorize its database calls.")),
 l("Service rollout",n("Amazon ECS","Maintain order API task count","ECS updates the service to the selected task-definition revision and replaces tasks under its deployment settings. Health checks and configured failure handling determine whether the rollout stabilizes; the task definition also specifies the application role, execution role and runtime resources.")),
 l("Run containers",n("AWS Fargate","Provision and start selected tasks","Fargate provisions the task runtime and pulls the image using the task execution role. The running container validates orders and accesses business data using its task role; the execution role used for image retrieval is not the application's data-access identity.")),
 l("Accept release",n("Release owner","Verify orders and retain rollback revision","The owner checks a representative order operation and service health before accepting the release. The previous task definition and image are retained under policy so an approved rollback can deploy a known earlier version.","user")));

const eks=a("AWS: release a receipt worker to managed EKS nodes","An approved Kubernetes Deployment references a private ECR image. Nodes pull it, EKS schedules the Pods and a workload-specific IAM role authorizes receipt storage.","https://docs.aws.amazon.com/eks/latest/userguide/pod-identities.html",
 l("Declare workload",n("Receipt-worker Deployment","Image digest and Kubernetes service account","The reviewed manifest pins the worker image and names its namespace, service account, replicas, resource requests and rollout settings. The worker consumes authorized receipt jobs and writes documents; manifest approval does not grant its Pods access to AWS APIs.","app")),
 l("Control plane",n("Amazon EKS","Kubernetes API and scheduling","The managed Kubernetes control plane accepts the authorized Deployment and reconciles its desired Pods. Scheduling places them on eligible managed nodes with sufficient resources; image-pull failures or readiness failures are handled through the actual workload state.")),
 l("Image pull",n("Amazon ECR worker image","Node-authorized image layers","The registry supplies the pinned image to the node's configured container runtime under its image-pull permissions. In this managed-node example the node role supplies required ECR access; the Pod's business IAM role has a separate purpose.",undefined,"Amazon ECR")),
 l("Runtime",n("Managed node and worker Pod","Start worker and process receipt jobs","The node starts the selected image and the worker parses authorized jobs, generates receipts and records completed outputs idempotently. Readiness and shutdown behavior are implemented for the worker so a rolling replacement does not silently lose claimed jobs.","app")),
 l("Workload AWS access",n("EKS Pod Identity","Service-account role association","The configured Pod Identity association maps this namespace and Kubernetes service account to the receipt role. With the required agent and supported SDK credential chain, the worker receives temporary role credentials for permitted AWS calls; this does not replace Kubernetes RBAC or node image-pull authorization.","security","Amazon EKS")),
 l("Persist receipts",n("Amazon S3 receipt objects","Role-scoped document writes","S3 authorizes the worker role's permitted bucket and object operations and stores completed receipt documents. The worker acknowledges its job only after its chosen durable completion checkpoint and handles duplicate jobs with stable object identifiers.",undefined,"Amazon S3")));

const aks=a("Azure: roll out a catalog API to AKS","Azure Pipelines tests and publishes a release image to ACR, then deploys its manifest to AKS. The kubelet identity pulls the image and ready Pods serve the catalog.","https://learn.microsoft.com/en-us/azure/aks/cluster-container-registry-integration",
 l("Build release",n("Azure Pipelines","Tests, image publication and manifest deployment","The configured pipeline runs the catalog tests, builds an image, pushes its versioned artifact to ACR and deploys the approved manifest using separately scoped build and cluster credentials. A production environment approval is applied where configured before the deployment step.")),
 l("Image",n("Azure Container Registry","Catalog image manifest and layers","ACR retains the release image identified by its immutable reference. The AKS kubelet identity has the repository-reader permission appropriate to this registry's authorization mode; build push permissions and container runtime business permissions are separate grants.")),
 l("Desired state",n("Azure Kubernetes Service (AKS)","Reconcile catalog Deployment","The authorized Kubernetes Deployment specifies image, replica count, resource requests and readiness probes. AKS reconciles those resources and schedules Pods on eligible nodes; it does not implement product selection or catalog authorization inside the API.")),
 l("Image pull and start",n("AKS kubelet","Pull pinned image and launch containers","The node's kubelet authenticates to ACR using its configured image-pull identity and starts the catalog container. It reports pull failures and probe results so the rollout can wait or fail instead of sending users to unready Pods.","app","Azure Kubernetes Service (AKS)")),
 l("Catalog requests",n("Kubernetes Service and catalog Pods","Route to ready application instances","The configured Service selects the catalog Pods and directs in-cluster requests to eligible endpoints. Each container validates the caller and retrieves permitted product records using its own configured workload access; Kubernetes routing does not grant data-store permissions.","app")),
 l("Release verification",n("Catalog release owner","Check rollout and product query","The owner checks rollout status and representative catalog reads under the approved access path. A failed release is handled by deploying the chosen prior manifest and image rather than changing a mutable tag without a controlled rollout.","user")));

const aca=a("Azure: deploy a shipping quote API as a Container App","A versioned image is published to ACR, an approved Container Apps revision pulls it using managed identity, and the revision calculates shipping quotes for incoming requests.","https://learn.microsoft.com/en-us/azure/container-apps/managed-identity-image-pull",
 l("Publish",n("Shipping quote build","Test and push approved image","The build tests the quote calculation and packages its runtime dependencies into an image, then pushes the approved version to ACR using its build identity. Required configuration and provider credentials are kept outside the image.","app")),
 l("Registry",n("Azure Container Registry quote image","Private release artifact","The private repository stores the selected quote image. The Container App's configured pull identity receives the required repository access under the registry's authorization mode, and the environment has the network reachability needed to retrieve its layers.",undefined,"Azure Container Registry")),
 l("Deploy revision",n("Azure Container Apps","Image configuration and ready revision","The deployment creates a revision with the selected image, resources, ingress and scale configuration. The platform pulls the private image through the explicitly configured managed identity and starts replicas; readiness is verified before assigning the intended production traffic.")),
 l("Quote operation",n("Shipping quote container","Calculate permitted shipping options","The request handler validates destination and package details, obtains the authorized provider rates and returns permitted quote options. Its runtime credential and network access to the provider are configured separately from the registry pull identity.","app")),
 l("Operate",n("Revision traffic owner","Verify quote behavior and adjust rollout","The owner checks representative quotes and configured revision traffic. When using multiple revisions, an approved traffic split can introduce the new revision gradually and return traffic to a known healthy revision if the quote behavior fails validation.","user")));

const aci=a("Azure: run a one-off reconciliation container","An operator creates a Container Instances group with a private reconciliation image, a user-assigned identity for image pull and a separate authorized path to reconciliation data.","https://learn.microsoft.com/en-us/azure/container-instances/using-azure-container-registry-mi",
 l("Launch request",n("Reconciliation scheduler","Container group specification","The scheduler submits an authorized container-group deployment with the approved image, CPU and memory limits, input parameters and intended restart policy. It supplies the selected user-assigned identity for the private ACR pull and tracks the run identifier.","app")),
 l("Artifact",n("Azure Container Registry reconciliation image","Versioned batch program","The repository stores the pinned reconciliation image and permits the configured user-assigned identity to pull it. The identity and network configuration are prepared before launch; image retrieval does not grant access to financial input or output records.",undefined,"Azure Container Registry")),
 l("Batch runtime",n("Azure Container Instances","Start the reconciliation container group","Container Instances provisions and runs the submitted container group. The program retrieves its authorized input records, compares the financial totals and produces a discrepancy report under the run identifier. The owner checks the exit state and handles failures deliberately.")),
 l("Output",n("Reconciliation report store","Durable run result","The program writes the completed report through its separately configured runtime data access before exiting. Consumers locate the result by the run identifier and distinguish a completed report from partial files left by a failed run.","storage")),
 l("Completion",n("Finance operations owner","Verify result and clean up run resources","The owner reviews completion status and discrepancy results, records the audit evidence and removes the ephemeral group according to policy. A successful container start is not treated as proof that reconciliation completed.","user")));

const gke=a("GCP: build and promote a catalog API to GKE","Cloud Build produces the tested image in Artifact Registry. Cloud Deploy renders and rolls out the release to configured GKE targets under separate build and deployment identities.","https://docs.cloud.google.com/deploy/docs/overview",
 l("Source and tests",n("Cloud Build","Build, test and publish selected revision","The build runs the repository's tests, creates the catalog image and pushes it to the chosen Artifact Registry repository using its configured build service account. It records the immutable image reference used to create the delivery release; a build failure stops the configured release step.")),
 l("Artifact",n("Artifact Registry","Immutable catalog release image","The repository retains the image manifest and layers. The build identity can publish the artifact and the target cluster's configured image-pull identity can read it. Those permissions are scoped independently from catalog database access.")),
 l("Release orchestration",n("Cloud Deploy","Render and promote release","The delivery pipeline creates the release using the recorded image and configured Skaffold deployment files, renders the target configuration and executes rollouts through its authorized execution environment. Promotion and approval policies decide when the release may reach each target.")),
 l("Cluster deployment",n("Google Kubernetes Engine (GKE)","Reconcile catalog Deployment","The target cluster accepts the authorized Kubernetes resources and reconciles the desired catalog Pods. Its nodes retrieve the approved image through configured registry access, while resource requests, readiness probes and rollout settings govern scheduling and availability.")),
 l("Serve",n("Catalog service Pods","Read permitted product data","The ready Pods handle catalog queries, validate user access and retrieve the permitted product records. Their workload identity and data permissions are configured for the catalog business operations rather than inherited from the build or delivery identity.","app")),
 l("Verify and promote",n("Release approver","Evaluate target verification and next rollout","The approver reviews rollout and verification results and checks the catalog's business behavior before permitting the next environment. A rollback uses the selected previous release and its image; a stored artifact alone does not restore application state changed by a deployment.","user")));

const gcpRun=a("GCP: build and deploy a document validation API","Cloud Build publishes a tested image to Artifact Registry and an authorized deployment creates a Cloud Run revision. The container validates documents and returns business errors or acceptance.","https://docs.cloud.google.com/build/docs/deploying-builds/deploy-cloud-run",
 l("Build",n("Cloud Build","Test and package document validator","The build runs format and business-rule tests, packages the validator and pushes the chosen image version to Artifact Registry. Its configured service identity has explicit build, registry and deployment permissions for the pipeline rather than broad application data access.")),
 l("Image",n("Artifact Registry","Validator image and release identity","The repository stores the validator's container artifact. The Cloud Run deployment uses the recorded version or digest, and required image-read permissions are granted to the relevant service identities, including any required cross-project access.")),
 l("Deploy",n("Cloud Run validator revision","Start approved validation code","The authorized deploy step creates a revision with the selected image, runtime service account, resources and invocation settings. The platform starts the container and routes the configured traffic; deployment permission and end-user invoke permission are distinct controls.",undefined,"Cloud Run")),
 l("Application operation",n("Document validation handler","Parse and validate submitted document","The handler checks the caller's authorization, bounds document size and supported formats, parses the content and applies the configured business validation rules. It returns specific acceptance or validation errors without treating build success as proof that an individual document is valid.","app")),
 l("Release acceptance",n("Document API owner","Verify behavior and traffic assignment","The owner tests accepted and rejected document examples and checks the revision's intended traffic. The runtime service account is scoped to any required business data access and remains separate from the identity that built and deployed the image.","user")));

export const reviewedContainerArchitectures:Record<string,ReviewedArchitecture[]>={
 "AWS CodePipeline":[ecs],"AWS CodeBuild":[ecs],"Amazon ECR":[ecs,eks],"Amazon ECS":[ecs],"AWS Fargate":[ecs],"Amazon EKS":[eks],
 "Azure Pipelines":[aks],"Azure DevOps":[aks],"Azure Container Registry":[aks,aca,aci],"Azure Kubernetes Service (AKS)":[aks],"Azure Container Apps":[aca],"Azure Container Instances":[aci],
 "Cloud Build":[gke,gcpRun],"Artifact Registry":[gke,gcpRun],"Cloud Deploy":[gke],"Google Kubernetes Engine (GKE)":[gke],
};
