import {author,type Recipe} from "./architecture-final/builders";
import b0 from "./architecture-final/aws-01.json";
import b1 from "./architecture-final/aws-02.json";
import b2 from "./architecture-final/aws-03.json";
import b3 from "./architecture-final/aws-04.json";
import b4 from "./architecture-final/aws-05.json";
import b5 from "./architecture-final/aws-06.json";
import b6 from "./architecture-final/aws-07.json";
import b7 from "./architecture-final/aws-08.json";
import b8 from "./architecture-final/aws-09.json";
import b9 from "./architecture-final/aws-10.json";
import b10 from "./architecture-final/aws-11.json";
import b11 from "./architecture-final/aws-12.json";
import b12 from "./architecture-final/azure-01.json";
import b13 from "./architecture-final/azure-02.json";
import b14 from "./architecture-final/azure-03.json";
import b15 from "./architecture-final/azure-04.json";
import b16 from "./architecture-final/azure-05.json";
import b17 from "./architecture-final/azure-06.json";
import b18 from "./architecture-final/azure-07.json";
import b19 from "./architecture-final/azure-08.json";
import b20 from "./architecture-final/azure-09.json";
import b21 from "./architecture-final/azure-10.json";
import b22 from "./architecture-final/azure-11.json";
import b23 from "./architecture-final/azure-12.json";
import b24 from "./architecture-final/azure-13.json";
import b25 from "./architecture-final/gcp-01.json";
import b26 from "./architecture-final/gcp-02.json";
import b27 from "./architecture-final/gcp-03.json";
import b28 from "./architecture-final/gcp-04.json";
import b29 from "./architecture-final/gcp-05.json";
import b30 from "./architecture-final/gcp-06.json";
import b31 from "./architecture-final/gcp-07.json";
import b32 from "./architecture-final/gcp-08.json";
import b33 from "./architecture-final/gcp-09.json";
import b34 from "./architecture-final/gcp-10.json";
import b35 from "./architecture-final/gcp-11.json";
export const finalArchitectureBatches=[b0,b1,b2,b3,b4,b5,b6,b7,b8,b9,b10,b11,b12,b13,b14,b15,b16,b17,b18,b19,b20,b21,b22,b23,b24,b25,b26,b27,b28,b29,b30,b31,b32,b33,b34,b35] as Recipe[][];
export const finalArchitectureRecipes=finalArchitectureBatches.flat();
export const reviewedFinalArchitectures=Object.fromEntries(finalArchitectureRecipes.map(r=>[r.cloud==="AWS"?r.service:r.cloud+":"+r.service,[author(r)]]));
