import type {ReviewedNode,ReviewedArchitecture} from "./reviewed-workload-architectures";
const n=(label:string,sub:string,detail:string,kind?:ReviewedNode["kind"],icon?:string):ReviewedNode=>({label,sub,detail,kind,icon});
const l=(title:string,...nodes:ReviewedNode[])=>({title,nodes});
const a=(title:string,note:string,reference:string,...layers:ReviewedArchitecture["layers"]):ReviewedArchitecture=>({title,note,reference,layers});

const guardDuty=a("AWS: investigate a suspicious workload connection","GuardDuty analyzes security data and emits a finding; an EventBridge notification starts an analyst investigation rather than blocking workload traffic automatically.","https://docs.aws.amazon.com/guardduty/latest/ug/guardduty_settingup.html",
 l("Security signals",n("Workload activity","API, network and DNS evidence","Workload API activity, network connections and DNS queries produce security signals. GuardDuty consumes its supported foundational data sources directly; customer-created CloudWatch log ingestion is not required to enable these foundational detections.","data")),
 l("Detect",n("Amazon GuardDuty","Threat finding","GuardDuty analyzes the relevant enabled data sources using its detection capabilities and generates a finding describing suspicious activity and affected resources. Additional protection features have their own coverage and enablement; a finding alone does not isolate the workload.")),
 l("Route finding",n("Amazon EventBridge","Finding-event filter","A rule matches the GuardDuty event type, severity and other configured conditions and sends matching finding details to its notification target. The rule routes security evidence, not the application's live network connection.")),
 l("Notify",n("Amazon SNS","Analyst notification","The topic delivers the finding notification to authorized confirmed subscriptions. It alerts the responders; receiving the message does not execute an EC2 isolation action or change a security group.")),
 l("Investigate",n("Security analyst","Validate and choose response","The analyst correlates the affected instance, principal, IP and event timestamps, checks whether the activity is expected, and chooses an authorized incident response. Isolation, credential revocation and evidence preservation are deliberate response operations.","user")));

const securityHub=a("AWS: track and remediate failed security controls","Security Hub CSPM aggregates posture and integrated findings; resource owners validate and correct the underlying configurations.","https://docs.aws.amazon.com/securityhub/latest/userguide/what-is-securityhub.html",
 l("Assess",n("AWS Config","Resource configuration for controls","Config records supported resource configurations needed by applicable Security Hub CSPM controls. Recording scope and required resource types must be enabled correctly; enabling a standard is not evidence that every resource has been assessed.")),
 l("Posture and findings",n("AWS Security Hub","Control findings and integrated evidence","Security Hub CSPM evaluates enabled controls using their required inputs and consolidates supported integrated findings. The responder examines control status, affected resources and finding workflow state; the service is not a firewall in the application's request path.")),
 l("Assign",n("Security triage team","Prioritize and assign findings","The team reviews severity, business exposure and ownership, then assigns a validated finding to the responsible resource owner. Suppressing a finding is an administrative disposition, not remediation of the vulnerable resource.","user")),
 l("Remediate",n("Resource owner","Correct configuration","The owner changes the affected resource through its authorized service API or approved infrastructure deployment. The remediation is bounded by ownership and change controls rather than assuming all failed checks can be safely fixed automatically.","user")),
 l("Reevaluate",n("Control reevaluation","Verify remediation evidence","After the underlying data is refreshed and the applicable control reruns, the team verifies the new control result and finding state. A manual workflow-status update does not prove that the failed security condition is gone.","data")));

const organizations=a("AWS: enforce a member-account service guardrail","Organizations attaches a tested SCP to the target OU; a member-account role still needs IAM grants and cannot perform actions denied by the applicable SCP.","https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scps.html",
 l("Define",n("Platform administrator","Test SCP in pilot OU","The administrator drafts a narrowly scoped SCP, tests its effect on representative member-account workloads, and reviews exceptions before attaching it broadly. This is a governance configuration operation, not application data processing.","user")),
 l("Hierarchy",n("AWS Organizations","Root, OU and member accounts","Organizations maintains the account hierarchy and SCP attachments. Applicable policies along the member account's ancestry limit its users and roles. SCPs do not grant permissions and do not constrain principals in the management account or service-linked roles.")),
 l("Request",n("Member-account IAM role","Authorized API attempt","The workload assumes a role with its own IAM permission grants and attempts an AWS API operation. An IAM allow does not override an applicable SCP deny; the principal must satisfy all relevant authorization controls.","security")),
 l("Enforce",n("AWS service authorization","Allow or deny requested action","The service authorization decision evaluates the caller's applicable policies and organization guardrails. Denied actions are rejected; allowed actions still require the correct identity and resource policies. The SCP is not a proxy carrying the request payload.","security")),
 l("Audit",n("AWS CloudTrail","Governance and API audit","Supported policy-management and service API events provide evidence of who changed the guardrail or attempted an operation. Administrators use this evidence to investigate unintended denials and revise the tested policy deliberately.")));

const defender=a("Azure: remediate an exposed-resource recommendation","Defender for Cloud assesses the configured resource scope and produces prioritized recommendations; the resource owner verifies and fixes the exposure.","https://learn.microsoft.com/en-us/azure/defender-for-cloud/review-security-recommendations",
 l("Assets",n("Connected cloud resources","Configuration and security context","The connected subscriptions or supported cloud accounts supply the assets and assessment context for the selected scope. Relevant Defender plans, connectors and required permissions determine which assessments and protection features are available.","data")),
 l("Assess",n("Microsoft Defender for Cloud","Recommendation and risk context","Defender for Cloud evaluates covered resource configurations against the applicable security policies and assessments. It presents the recommendation, affected resources and remediation guidance; threat alerts and posture recommendations are distinct signals.")),
 l("Prioritize",n("Security posture owner","Validate exposure and ownership","The posture owner checks the recommendation's applicability, resource reachability and business criticality, then assigns remediation to the team authorized to change the resource.","user")),
 l("Fix",n("Resource administrator","Apply approved resource change","The administrator uses the resource's management API or deployment process to correct the exposure. A recommendation does not automatically authorize a change or guarantee that every proposed setting is appropriate for the application.","user")),
 l("Verify",n("Assessment refresh","Confirm corrected posture","The team waits for the relevant assessment data to refresh and checks the resulting recommendation state. It also verifies the intended application behavior after the change instead of treating a dashboard score alone as proof of a safe fix.","data")));

const sentinel=a("Azure: investigate and enrich a security incident","Sentinel correlates ingested evidence into an incident; an authorized Logic Apps playbook enriches it for analyst review.","https://learn.microsoft.com/en-us/azure/sentinel/automation/logic-apps-playbooks",
 l("Collect",n("Security data connectors","Configured telemetry ingestion","Configured connectors ingest supported identity, security and application evidence into the selected Sentinel data platform. Permissions, connector health and retention determine the evidence available for analytics; not every log source is connected automatically.","data")),
 l("Detect",n("Microsoft Sentinel","Analytics and incident creation","The configured analytics rule queries or correlates the available evidence and generates an alert and incident under its rule settings. Entity mappings identify the user, IP or host the enrichment workflow will investigate.")),
 l("Automate",n("Sentinel automation rule","Choose enrichment playbook","The automation rule matches the incident conditions and invokes the selected playbook with the required permissions. It controls when enrichment runs; it does not itself query a threat-intelligence API or disable a user.","app")),
 l("Enrich",n("Azure Logic Apps","Look up incident entities","The playbook extracts the mapped entities, calls its configured authorized intelligence or ownership services, and appends the returned evidence to the incident. Only the actions explicitly configured in the workflow run; enrichment does not imply automatic containment.")),
 l("Investigate",n("SOC analyst","Triage enriched evidence","The analyst reviews the original alerts and enriched entity context, validates the incident, and decides the appropriate escalation or containment. High-impact response actions follow the team's approval and access controls.","user")));

const azurePolicy=a("Azure: audit and prevent an unsupported resource location","An assigned Azure Policy checks resource properties within its scope; audit reports noncompliance while deny rejects applicable disallowed changes.","https://learn.microsoft.com/en-us/azure/governance/policy/concepts/effect-basics",
 l("Policy author",n("Governance administrator","Define allowed-location assignment","The administrator chooses or creates the allowed-locations definition, supplies the approved locations, and assigns it at the intended management group, subscription or resource-group scope. Exemptions are documented rather than silently broadening the rule.","user")),
 l("Govern",n("Azure Policy","Scope, rule and effect","Azure Policy evaluates applicable resource properties against the assigned rule. The effect matters: audit records noncompliance, whereas a configured deny effect can block an applicable create or update. Policy governs resource configuration; Azure RBAC separately grants management permissions.")),
 l("Deployment",n("Resource deployment","Requested location","An authorized deployment requests a resource at a specific location. Authorization permits the caller to attempt the operation, while the applicable policy rule independently checks whether the resource properties satisfy the location guardrail.","app")),
 l("Outcome",n("Policy evaluation outcome","Allowed change or denial","A compliant applicable request may proceed; a matching deny condition rejects the change. Existing noncompliant resources are not automatically moved to another region simply because a policy assignment was created.","data")),
 l("Review",n("Compliance owner","Review exceptions and existing assets","The owner reviews the compliance results, investigates existing resources outside the allowed locations, and plans an approved migration or exemption. This policy does not turn a location change into a safe automatic remediation.","user")));

const scc=a("GCP: route a security finding to its owner","Security Command Center consolidates enabled-source findings; a filtered continuous export publishes selected evidence to Pub/Sub for ticket handling.","https://docs.cloud.google.com/security-command-center/docs/how-to-notifications",
 l("Evidence",n("Enabled security sources","Assessment and threat evidence","Configured Security Command Center sources assess covered assets or analyze supported threat evidence. Activation scope, tier and source enablement determine coverage; an asset inventory is not proof that every protection feature is active.","data")),
 l("Findings",n("Security Command Center","Finding details and resource context","Security Command Center presents findings from the enabled sources with affected-resource information and management state. Responders distinguish posture findings from threat detections and validate the reported condition before choosing a response.")),
 l("Export",n("Continuous finding export","Filter selected findings","The configured export matches the selected finding criteria and publishes matching finding changes to its Pub/Sub destination with the required service-agent permissions. Regional findings and export configuration must use compatible locations.","app")),
 l("Deliver",n("Pub/Sub","Finding subscription","The topic and subscription deliver finding messages to the authorized ticket consumer. Retry and acknowledgment behavior concerns delivery of security evidence, not blocking the affected workload's application traffic.")),
 l("Ticket",n("Finding ticket worker","Create or update owner ticket","The consumer parses the finding identifier and affected asset, maps it to an owner, and creates or updates a ticket idempotently. It acknowledges processed messages after the ticket operation succeeds; a ticket is not proof of resource remediation.","app")),
 l("Respond",n("Resource owner","Validate and remediate finding","The owner checks the resource and evidence, applies an authorized corrective change, and confirms the condition through refreshed findings and resource tests. Muting a finding controls its visibility; it does not fix the affected resource.","user")));

const orgPolicy=a("GCP: constrain permitted resource configurations","Organization Policy applies the configured constraint to applicable resource operations within its hierarchy; IAM remains the access-grant mechanism.","https://docs.cloud.google.com/resource-manager/docs/organization-policy/overview",
 l("Set policy",n("Organization policy administrator","Define constraint and scope","The administrator selects a supported constraint, specifies its permitted or denied values, and configures it at the intended organization, folder or project. Constraint behavior and exemptions are tested before broader enforcement.","user")),
 l("Govern",n("Organization Policy","Effective resource constraint","Organization Policy determines the applicable effective policy according to the constraint and hierarchy rules. It constrains supported resource behavior or configuration and does not grant a principal permission to create or administer that resource.")),
 l("Request",n("Project deployment identity","Authorized resource operation","The deployment identity has the required IAM permissions to attempt the service operation. Its requested configuration must also satisfy the applicable organization constraint; IAM authorization does not bypass that restriction.","security")),
 l("Enforce",n("Target service","Apply supported constraint","The target service enforces the constraint for the supported operation. Existing resources and retroactive effects depend on the specific constraint; do not assume every policy change automatically rewrites all existing configurations.","app")),
 l("Verify",n("Platform owner","Confirm permitted deployment","The platform owner checks allowed and denied test cases, inspects supported audit evidence and documents any required changes for existing assets. Successful enforcement is verified using the actual target service, not just the existence of a policy object.","user")));

const attackResponse=a("AWS: contain a confirmed malicious outbound destination","GuardDuty detects suspicious EC2 activity. Security Hub CSPM routes the integrated finding to an approval-controlled response; Network Firewall enforces the approved egress rule on traffic routed through its endpoints.","https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-cloudwatch-events.html",
 l("Detect",n("Amazon GuardDuty","Suspicious EC2 network activity","GuardDuty analyzes supported network and DNS evidence for the EC2 workload and emits a suspicious-connection finding. The destination address, affected instance and timestamps become investigation evidence; detection does not change the instance's routes or firewall rules.")),
 l("Consolidate",n("AWS Security Hub","Integrated GuardDuty finding","The enabled GuardDuty integration supplies the threat finding to Security Hub CSPM. Responders correlate the affected resource and finding details with posture evidence and ownership before choosing containment. Finding status is distinct from the state of the affected network connection.")),
 l("Route evidence",n("Amazon EventBridge","Select eligible imported finding","A rule matches the Security Hub CSPM imported-finding event and starts the configured response state machine. Filters exclude irrelevant products and finding types; the handler also checks current finding state so updates do not repeatedly apply the same change.")),
 l("Validate and approve",n("AWS Step Functions","Incident response orchestration","The state machine records the finding identifier, invokes validation steps and waits for an explicitly implemented analyst approval callback. It checks the destination against trusted exclusions and records a rollback plan before allowing a narrowly scoped firewall change."),n("SOC analyst","Confirm malicious destination","The analyst correlates the destination with the instance's application dependencies and incident evidence. Approval permits blocking the confirmed destination for the affected egress scope; a shared hosting address or legitimate dependency may instead require instance isolation.","user")),
 l("Apply approved change",n("Firewall remediation Lambda","Update named stateful rule group","The function reads the current customer-managed Network Firewall rule group and update token, merges the approved destination rule, and calls UpdateRuleGroup using a least-privilege role. It preserves existing rules, handles concurrent updates and records the incident-to-rule mapping for safe rollback.","app","AWS Lambda")),
 l("Enforce on routed traffic",n("AWS Network Firewall","Inspect and drop matching egress","The firewall policy references the updated stateful rule group. Packets routed through the firewall endpoints are evaluated under that policy and matching traffic is dropped. Symmetric routing and the intended VPC scope must be configured; an API update cannot protect traffic that bypasses the endpoints.")),
 l("Verify containment",n("Incident responder","Confirm drop and investigate host","The responder checks firewall evidence and controlled connectivity tests, confirms legitimate dependencies still work, and investigates the compromised host and credentials. Blocking one destination reduces exposure but does not remove malware; the incident retains separate eradication and recovery tasks.","user")));

export const reviewedSecurityArchitectures:Record<string,ReviewedArchitecture[]>={
 "Amazon GuardDuty":[guardDuty],"AWS GuardDuty":[guardDuty],
 "AWS Security Hub":[securityHub,attackResponse],"AWS Organizations":[organizations],
 "AWS Network Firewall":[attackResponse],"AWS Step Functions":[attackResponse],
 "AWS Config":[securityHub],"Amazon EventBridge":[guardDuty,attackResponse],"Amazon SNS":[guardDuty],"AWS CloudTrail":[organizations],
 "Microsoft Defender for Cloud":[defender],"Microsoft Sentinel":[sentinel],"Azure Policy":[azurePolicy],"Logic Apps":[sentinel],"Azure Logic Apps":[sentinel],
 "Security Command Center":[scc],"Organization Policy":[orgPolicy],"Organization Policy Service":[orgPolicy],
};
