import type {ReviewedNode,ReviewedArchitecture} from "./reviewed-workload-architectures";
const n=(label:string,sub:string,detail:string,kind?:ReviewedNode["kind"],icon?:string):ReviewedNode=>({label,sub,detail,kind,icon});
const l=(title:string,...nodes:ReviewedNode[])=>({title,nodes});
const a=(title:string,note:string,reference:string,...layers:ReviewedArchitecture["layers"]):ReviewedArchitecture=>({title,note,reference,layers});

const awsBackup=a("AWS: restore a protected business server","A scheduled backup protects an EC2 server; a separate restore and application test establish whether its recovery point is usable.","https://docs.aws.amazon.com/aws-backup/latest/devguide/restore-testing.html",
 l("Protect workload",n("Amazon EC2 business server","Application and attached volumes","The server runs the business application and writes its persistent state to the protected attached volumes. The owner identifies required disks, configuration and external dependencies so a server backup is not mistaken for protection of an external database.")),
 l("Schedule",n("AWS Backup","Plan and resource assignment","The backup plan defines the schedule and retention and selects the server through its resource assignment. AWS Backup creates supported recovery points using the configured role; the owner checks job success and consistency requirements for the application.")),
 l("Retain",n("AWS Backup vault","Recovery points and access controls","The vault holds the recovery points governed by the configured retention and access controls. The operator selects a known suitable recovery point for restoration; vault retention alone does not determine how quickly the application can return to service.","storage","AWS Backup")),
 l("Restore",n("Recovery operator","Launch approved restore job","The operator supplies the required EC2 restore metadata, role and isolated destination settings. A restore job creates recovery resources from the selected point; credentials, DNS, dependencies and application checks remain explicit recovery tasks.","user")),
 l("Validate",n("Restored EC2 server","Boot and business transaction test","The restored server boots in an isolated environment. The team checks required volumes, starts the application and executes a representative transaction against safe test dependencies, then records elapsed recovery time and the age of recovered data.","app","Amazon EC2")));

const awsDr=a("AWS: recover a failed on-premises application server","Continuous block replication feeds a staging area; recovery launches application instances and an approved traffic switch follows validation.","https://docs.aws.amazon.com/drs/latest/userguide/failback.html",
 l("Replicate source",n("Source server and replication agent","Changed disk blocks","The installed replication agent sends changed disk blocks from the source server to the target staging infrastructure. Network reachability, bandwidth and replication lag affect the recoverable state; this channel is separate from the application's client traffic.","app")),
 l("Stage",n("AWS Elastic Disaster Recovery","Replication and recovery configuration","Elastic Disaster Recovery manages replication state, recovery points and launch settings. The team monitors replication health and runs drills before relying on the configuration during an outage; a healthy staging area is not a running replacement application.")),
 l("Keep replica",n("Staging replication resources","Replicated disks","Configured replication servers and staging disks retain the replicated source state in the target region. These resources support recovery preparation rather than serving production application requests.","storage")),
 l("Launch",n("Amazon EC2 recovery instances","Boot recovered server state","An authorized recovery launch creates EC2 instances using the chosen recovery point and launch configuration. The owner verifies networking, required secrets, application startup and dependencies before declaring the recovered service ready.")),
 l("Switch clients",n("Recovery coordinator","Validate then change traffic routing","The coordinator checks application health and the recoverable data point, then makes the approved DNS or traffic-routing change. Elastic Disaster Recovery does not perform the traffic failover itself; returning to the source requires a separately planned failback procedure.","user")));

const azureBackup=a("Azure: restore a deleted business VM","A vault-backed VM backup retains recovery points; an operator restores disks and rebuilds the server in an isolated network.","https://learn.microsoft.com/en-us/azure/backup/backup-azure-arm-restore-vms",
 l("Protected server",n("Azure Virtual Machines","Business workload disks","The VM runs the business application on the disks included in its backup configuration. The owner checks disk eligibility and application consistency; external databases, secrets and third-party dependencies need their own recovery arrangements.")),
 l("Backup",n("Azure Backup","VM policy and backup jobs","The configured VM backup policy schedules protection and retains recovery points. The team checks completed jobs and the available consistency type instead of assuming a configured policy has produced a usable application backup.")),
 l("Retain",n("Recovery Services vault","Protected VM recovery points","The vault manages the protected VM's recovery points, policy and restore access. The operator selects the desired point and checks encryption permissions and restore prerequisites before starting recovery.","storage","Azure Backup")),
 l("Restore disks",n("Recovery administrator","Authorized disk restore","The administrator starts the restore-disks operation into the approved target resource group and storage settings. Once the job succeeds, the administrator uses the restored disks to create a replacement VM with the required compatible configuration.","user")),
 l("Validate replacement",n("Restored Azure VM","Isolated application checks","The replacement VM boots in a test network where it cannot conflict with the original application. The team verifies disk contents, application startup and representative business operations before approving any production routing change.","app","Azure Virtual Machines")));

const azureDr=a("Azure: rehearse regional VM recovery","Site Recovery replicates a protected VM to another region; a test failover exercises recovery in an isolated virtual network without switching production traffic.","https://learn.microsoft.com/en-us/azure/site-recovery/azure-to-azure-tutorial-dr-drill",
 l("Production",n("Azure production VM","Protected application server","The production VM continues serving users while its supported disk changes are replicated under the configured Site Recovery protection. Replication health and lag are monitored because the selected recovery point may precede the latest application writes.","app","Azure Virtual Machines")),
 l("Coordinate recovery",n("Azure Site Recovery","Replication and recovery plan","Site Recovery maintains the configured replica and recovery points and coordinates the selected failover operation. A recovery plan can order protected groups and configured actions; application dependencies must be deliberately included and tested.")),
 l("Target",n("Target-region replica","Recovery disks and launch settings","The destination holds replicated disk state and the configured target VM settings. Capacity, networking, permissions and dependent services are checked before the drill rather than assumed to be created correctly by replication alone.","storage")),
 l("Test failover",n("Isolated recovery virtual network","Drill environment","The test failover launches recovery VMs into the chosen isolated network. This avoids duplicate production identities and unintended customer access; external integrations are redirected or disabled so the drill cannot send real business transactions.","security")),
 l("Accept and clean up",n("Recovery team","Measure recovery and remove drill resources","The team validates application startup, dependencies and recovered data, records the measured recovery time and recovery-point age, then completes test-failover cleanup. A successful drill informs the separate approved production failover and failback runbooks.","user")));

const gcpBackup=a("GCP: recover a deleted Compute Engine server","A backup plan protects a Compute Engine instance in a backup vault; a selected backup is restored to a new instance and tested before cutover.","https://docs.cloud.google.com/backup-disaster-recovery/docs/cloud-console/compute/compute-instance-restore",
 l("Protect",n("Compute Engine source instance","Server and protected disks","The instance runs the business application and stores persistent data on the disks included in its protection configuration. The owner identifies external data services and startup dependencies that must be recovered separately from the instance backup.")),
 l("Schedule",n("Backup and DR Service","Backup plan association","The assigned backup plan defines protection frequency and retention for the supported Compute Engine workload. The team checks backup jobs and recovery-point age; creating the plan is not proof that the latest application writes are protected.")),
 l("Retain",n("Backup vault","Retained instance backups","The vault retains the instance backups under its configured protection and access settings. Restore permissions and the service agent's permissions in the destination project are verified before relying on cross-project recovery.","storage","Backup and DR Service")),
 l("Restore",n("Recovery operator","Select backup and target settings","The operator selects a retained backup and the supported destination project, zone and instance configuration, then launches restoration to a new Compute Engine instance. The recovery operation is separate from customer traffic routing.","user")),
 l("Validate",n("Compute Engine restored instance","Boot and application verification","The restored instance starts in an isolated destination. The owner verifies disk contents, startup configuration and a safe business transaction, then explicitly approves production access and records the achieved recovery time and recovered data age.","app","Compute Engine")));

export const reviewedRecoveryArchitectures:Record<string,ReviewedArchitecture[]>={
 "AWS Backup":[awsBackup],"AWS Elastic Disaster Recovery":[awsDr],
 "Azure Backup":[azureBackup],"Azure Site Recovery":[azureDr],
 "Backup and DR Service":[gcpBackup],
};
