import {n,l,a} from "./reviewed-architecture-builders";
import type {ReviewedArchitecture} from "./reviewed-workload-architectures";

const scheduler=a("GCP: reconcile yesterday's invoices on an authenticated schedule","A scheduled HTTP request starts an invoice reconciliation handler. The handler owns the business-date calculation and duplicate-run protection.","https://docs.cloud.google.com/scheduler/docs/http-target-auth",
 l("Schedule",n("Cloud Scheduler","Configured cron and time zone","The job evaluates its configured cron schedule and time zone, then invokes the reconciliation endpoint using the selected service account's OIDC token. That identity has permission to invoke the Cloud Run service. Retries and repeated delivery are accounted for by the handler's business-date key.")),
 l("Reconcile",n("Invoice reconciliation on Cloud Run","Compare settled payments with invoice records","The handler authenticates the invocation and claims a reconciliation run for the requested business date. It reads the relevant settled-payment and invoice records, compares amounts and identifiers, and records discrepancies for review. Repeated invocations reuse or safely resume the same run rather than duplicating adjustments.","app","Cloud Run")),
 l("Record",n("Reconciliation record store","Durable run and discrepancy records","The application persists the run identity, matched invoice outcomes and discrepancy records with its chosen transaction or conditional-write design. A completed run is committed before the handler acknowledges success; interrupted runs retain enough state for a controlled retry.","data")),
 l("Review",n("Accounts receivable owner","Investigate unmatched payments","The owner reviews missing invoices, mismatched amounts and unmatched payment references from the completed reconciliation. Corrections require the agreed accounting process; a scheduled request itself does not authorize an automatic change to a customer's balance.","user")));

const tasks=a("GCP: generate customer exports through a controlled task queue","The API enqueues an export request, Cloud Tasks dispatches authenticated HTTP attempts, and the worker publishes one durable export per business request.","https://docs.cloud.google.com/tasks/docs/creating-http-target-tasks",
 l("Enqueue",n("Export request API","Authorize export and assign request ID","The API verifies the customer's export permission, records the selected data scope and creates an HTTP task carrying the stable export request identifier. Its enqueue credentials are separate from the service account used to authenticate task delivery to the worker.","app")),
 l("Dispatch",n("Cloud Tasks","Rate-limited authenticated HTTP attempts","The queue dispatches the task to the configured worker URL under its rate, concurrency and retry settings. The selected service account's OIDC token authenticates the Cloud Run invocation. A failed attempt may be retried and duplicate execution is possible, so successful business processing is guarded by the request identifier.")),
 l("Build export",n("Export worker on Cloud Run","Read permitted records and build file","The worker validates the task request and claims the export identifier, reads only the authorized customer records and builds the requested export file. It stores the result and completion state before returning a successful HTTP response. A repeated attempt checks that durable state instead of producing a second business export.","app","Cloud Run")),
 l("Publish",n("Cloud Storage export object","Private result and authorized download","The worker writes the export to the selected private bucket and records its object identity against the request. The download API rechecks customer authorization or issues the approved short-lived access mechanism; possession of a task identifier alone does not grant access to the file.",undefined,"Cloud Storage")));

const workflows=a("GCP: validate and enrich a supplier document through service calls","Workflows coordinates two authenticated Cloud Run handlers and publishes the result only after validation and enrichment succeed.","https://docs.cloud.google.com/workflows/docs/authenticate-from-workflow",
 l("Start",n("Supplier document application","Document reference and request ID","The application records the uploaded document reference and starts a workflow execution with a stable business request identifier. It authenticates the execution API call and returns a trackable request to the user instead of claiming that enrichment has already completed.","app")),
 l("Orchestrate",n("Workflows","Validation, branching and enrichment calls","The execution calls the validator using OIDC authentication from its attached service account, checks the returned validation result and branches away from enrichment when the document is rejected. Accepted documents are sent to the enrichment handler; explicit retry rules avoid blindly repeating non-idempotent changes.")),
 l("Validate then enrich",n("Document validation handler","Check schema and supplier fields","This Cloud Run handler reads the permitted document, checks required supplier identifiers and field formats, and returns structured validation errors or an accepted record. It performs validation business logic; workflow coordination and deciding the next call remain with Workflows.","app","Cloud Run"),n("Supplier enrichment handler","Look up supplier reference information","Workflows calls this handler only after validation passes. The handler resolves the supplier identifier against the approved reference source and returns the permitted normalized supplier fields, using the request identity to handle retried enrichment safely.","app","Cloud Run")),
 l("Publish",n("Supplier document result","Approved normalized record or rejection","The application's result-publishing step persists the accepted normalized document or a structured rejection under the original request identity. Publication occurs after the selected workflow branch finishes, and failed executions remain visible for repair rather than being marked as successful supplier records.","data")));

const queue=a("Azure: process queued warehouse pick requests safely","Queue Storage holds pick requests while a worker performs an idempotent inventory reservation and deletes the message after durable completion.","https://learn.microsoft.com/en-us/rest/api/storageservices/get-messages",
 l("Submit",n("Warehouse order application","Stable pick-request identifier","The application authorizes the order and sends a pick request containing its stable identifier and permitted item quantities. Queue acceptance means that a message was stored; it does not confirm that inventory has been reserved or a worker has completed the pick.","app")),
 l("Queue",n("Queue Storage","Retrieve with a visibility timeout","The worker retrieves a message with its pop receipt, making it temporarily invisible to other workers under the selected visibility timeout. Retrieval does not delete the message. The application chooses message lifetime and a retry/poison-message handling policy rather than assuming a Service Bus dead-letter queue.")),
 l("Reserve",n("Warehouse pick worker","Idempotent reservation before message deletion","The worker validates the request, reserves stock using a transactional or conditional update and records the completed request identifier. It extends visibility when needed and deletes the message using the current pop receipt only after durable completion. A crash or timeout can expose the message again, so duplicate reservations are prevented.","app")),
 l("Durable outcome",n("Inventory reservation store","Stock reservation and completed request ID","The store preserves the inventory change and duplicate-detection record at the application's chosen durable boundary. The worker can recognize a previously completed request after a queue replay and acknowledge it without reserving the same stock a second time.","data")));

const grid=a("Azure: route committed document uploads to a validation queue","Event Grid filters committed BlobCreated notifications into Queue Storage; a consumer reads the referenced document and validates it.","https://learn.microsoft.com/en-us/azure/event-grid/handler-storage-queues",
 l("Upload",n("Azure Blob Storage","Committed supplier document","The uploader writes a document under the configured supplier prefix. The event subscription selects the applicable completed-write event for the upload method, including the appropriate commit operation where required; downstream validation reads the referenced blob rather than treating event metadata as the document's contents.")),
 l("Filter and deliver",n("Event Grid","BlobCreated filter and queue destination","The subscription filters the intended event type and document prefix and delivers matching event metadata to its configured Storage queue endpoint using the approved authorization setup. Delivery retries and possible duplicate events are handled by the consumer; the routing service does not validate supplier fields.")),
 l("Buffer",n("Document event queue","Buffered event metadata and blob reference","Queue Storage retains the delivered event record while the worker is unavailable. The worker retrieves it under a visibility timeout and keeps the current pop receipt for deletion after processing; the queue contains the reference event, not a second copy of the uploaded document.","message","Queue Storage")),
 l("Validate",n("Supplier document worker","Read blob, validate fields and record result","The worker uses its storage permissions to read the referenced committed document, validates its required supplier fields and persists an acceptance or rejection keyed by the event and blob identity. It deletes the queue message after durable completion and handles repeated events without publishing duplicate records.","app")));

const ses=a("AWS: send an order receipt and handle delivery feedback","An order application sends a receipt through SES and uses configured feedback to distinguish send acceptance from delivery or bounce outcomes.","https://docs.aws.amazon.com/ses/latest/dg/send-email-concepts-process.html",
 l("Prepare",n("Order receipt application","Committed order and permitted recipient","The application prepares the receipt for a committed order, checks the chosen recipient and records its business send identity. It uses an authorized sending identity and accounts for applicable SES sandbox restrictions and sending quotas before submitting the message.","app")),
 l("Send",n("Amazon SES","Accept and attempt receipt delivery","SES checks the authorized request and sending conditions, then accepts the message for its delivery attempt and returns a message identifier when successful. The application stores that identifier against the order. Acceptance is not proof of recipient delivery, and ambiguous failures require careful reconciliation before resending.")),
 l("Feedback",n("Configured Amazon SNS feedback topic","Delivery, bounce or complaint notification","The configured SES notification path publishes the selected delivery feedback to the subscribed handler. The handler verifies and correlates each notification using the stored message mapping, and handles repeated notifications safely. Feedback configuration is explicit rather than inferred from every send operation.",undefined,"Amazon SNS")),
 l("Update",n("Receipt feedback handler","Record outcome and manage recipient suppression","The handler updates the receipt's delivery status, records bounce or complaint details and applies the approved recipient suppression policy. It does not treat an SES acceptance response as delivery evidence or repeatedly resend to an address that produced a permanent failure.","app")));

const firehose=a("AWS: buffer application audit records into an S3 archive","The producer submits audit records to Firehose, which batches delivery to the configured S3 destination for later analytical reads.","https://docs.aws.amazon.com/firehose/latest/dev/basic-deliver.html",
 l("Produce",n("Application audit producer","Validated event and stable record ID","The application constructs each audit record with the business event identity, timestamp and required fields and checks Firehose write results. It retries failed records under the chosen producer policy, preserving identifiers so downstream analysis can identify repeated submissions.","app")),
 l("Buffer and deliver",n("Amazon Data Firehose","Configured buffering and S3 delivery","Firehose buffers accepted records under its configured delivery settings and writes them to the chosen S3 destination using its delivery role. This pattern does not configure a transformation Lambda or pretend that buffering performs business validation; concatenation, compression and output prefixes are selected for the archive.")),
 l("Archive",n("Amazon S3 audit archive","Delivered objects and access policy","S3 stores the delivered audit objects under the configured prefixes, encryption and access policy. Consumers account for the output record format and any repeat records; arrival in this archive is separate from the producer's original API acceptance.",undefined,"Amazon S3")),
 l("Analyze",n("Audit analysis application","Read selected archive and reconcile records","The analytical consumer reads the intended date range, parses the configured record format and reconciles event identifiers before counting business actions. It handles delivery delay and duplicates explicitly instead of interpreting every archived line as a unique completed action.","app")));

const cognito=a("AWS: authenticate a customer before returning their order history","Cognito user pools authenticate the customer; the order API validates the access token and enforces record ownership.","https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-verifying-a-jwt.html",
 l("Sign in",n("Customer application","Configured user-pool sign-in flow","The application starts its configured user-pool authentication flow and handles the required sign-in challenges. After successful authentication it sends the appropriate access token to the order API over HTTPS; an ID token is not substituted for the API's configured access-token authorization.","app")),
 l("Authenticate",n("Amazon Cognito","User-pool authentication and token issuance","The user pool checks the customer's authentication under its configured policies and issues the appropriate tokens after successful sign-in. It establishes the customer identity for the application; this pattern uses user-pool tokens and does not grant AWS credentials through an identity pool.")),
 l("Authorize and query",n("Order history API","Validate token and enforce customer ownership","The API verifies the access token's signature, issuer, expiration, token use, applicable client identifier and required scopes. It then uses the validated subject to select only that customer's orders, applying application authorization before querying data rather than trusting a customer ID supplied by the caller.","app")),
 l("Return",n("Customer order store","Ownership-filtered order records","The data query returns records scoped to the authenticated customer's identity under the API's database permissions. The response includes only the permitted order fields; successfully authenticating a user does not authorize reading another customer's history.","data")));

export const reviewedIntegrationArchitectures:Record<string,ReviewedArchitecture[]>={
 "Cloud Scheduler":[scheduler],"Cloud Tasks":[tasks],"Workflows":[workflows],
 "Queue Storage":[queue],"Event Grid":[grid],
 "Amazon SES":[ses],"Amazon Data Firehose":[firehose],"Amazon Cognito":[cognito]
};
