import {n,l,a} from "./reviewed-architecture-builders";
import type {ReviewedArchitecture} from "./reviewed-workload-architectures";
const acm=a("AWS: terminate customer HTTPS at an application load balancer","ACM manages the certificate; the listener uses it during TLS termination and forwards the permitted request.","https://docs.aws.amazon.com/acm/latest/userguide/acm-services.html",
 l("Certificate setup",n("AWS Certificate Manager","Validated hostname certificate","The owner requests the certificate for the customer-facing hostname, completes the required domain validation and associates the issued certificate with the regional ALB listener. Keeping the validation record and supported association permits eligible managed renewal.")),
 l("TLS ingress",n("HTTPS application load balancer","Present certificate and route request","The HTTPS listener presents the selected certificate during the client handshake and routes the accepted HTTP request to a healthy target. ACM supplies certificate management rather than intercepting requests; target-side encryption is configured separately.","app","Elastic Load Balancing")),
 l("Application",n("Customer portal target","Authenticate user and return account view","The portal receives the forwarded request, verifies the customer's application identity and returns the permitted account information. A trusted server certificate authenticates the endpoint, not the customer's right to read account records.","app")));
const ca=a("AWS: issue a private certificate for an internal TLS service","The private CA signs an approved certificate request; trust distribution and TLS termination belong to the service deployment.","https://docs.aws.amazon.com/privateca/latest/userguide/PcaIssueCert.html",
 l("Request",n("Internal service certificate owner","CSR with approved internal identity","The service owner generates and protects the private key and submits a CSR for the approved internal hostname. Issuance permissions and the selected certificate template restrict the authorized request; the key is not sent as part of the CSR.","user")),
 l("Issue",n("AWS Private CA","Sign certificate under private trust hierarchy","The authorized issuance request uses the selected private CA and permitted template to sign the service certificate. The operator manages the CA hierarchy, validity and revocation design; a private certificate is not automatically trusted by public browsers.")),
 l("Deploy",n("Internal TLS service and clients","Install certificate and distribute trusted CA","The service installs its certificate and protected key, while clients trust the approved CA chain and verify hostname and validity during TLS. Renewal and revocation checking are tested as explicit deployment responsibilities.","app")));
const macie=a("AWS: find customer identifiers in a document bucket","A scoped sensitive-data discovery job reports detected identifiers; the data owner decides the approved protection change.","https://docs.aws.amazon.com/macie/latest/user/what-is-macie.html",
 l("Select data",n("Customer document S3 bucket","Scoped objects and discovery access","The bucket contains uploaded customer documents. The discovery job selects the permitted objects under supported format and encryption-access conditions; its sampling and exclusions are recorded so unexamined objects are not treated as inspected.","storage","Amazon S3")),
 l("Discover",n("Amazon Macie","Inspect selected objects for sensitive data","Macie reads eligible selected objects and applies the configured managed and custom data identifiers, producing findings for detected customer information. A finding reports exposure evidence; it does not automatically redact documents or change bucket access.")),
 l("Protect",n("Customer data owner","Validate finding and restrict access","The owner verifies the finding's object and identifier context, checks the bucket's access policy and applies the approved restriction or data-retention action. Follow-up discovery and access checks confirm the intended protection without assuming discovery proves complete compliance.","user")));
const inspector=a("AWS: repair a vulnerable container image before its next release","Inspector findings identify a package issue; the release owner rebuilds and verifies a replacement image.","https://docs.aws.amazon.com/inspector/latest/user/scanning-ecr.html",
 l("Image inventory",n("Amazon ECR release image","Enhanced scanning scope and immutable digest","The repository is configured for the selected enhanced scanning scope. The release image's digest identifies the exact artifact under investigation, and supported image/package coverage is checked before relying on its vulnerability report.",undefined,"Amazon ECR")),
 l("Assess",n("Amazon Inspector","Package vulnerability findings for the image","Inspector evaluates the eligible image under the configured scanning behavior and reports vulnerable packages and relevant remediation information. It does not patch the image or establish that the application is exploitable; the owner reviews severity and usage.")),
 l("Rebuild",n("Container release owner","Upgrade dependency and verify new digest","The owner updates the affected dependency, rebuilds and tests the container and checks findings for the new digest before deploying it. Replacing the registry image alone does not replace running containers, so rollout and rollback are explicitly managed.","user")));
const detective=a("AWS: investigate a suspicious role session with behavioral context","Detective's behavior graph supports investigation of a finding; the analyst owns the incident decision.","https://docs.aws.amazon.com/detective/latest/userguide/what-is-detective.html",
 l("Lead",n("Suspicious role-session finding","Principal and incident time window","The analyst starts with a finding's principal, account and observed time window and selects the corresponding entity in the configured Detective graph. A finding is an investigation lead and is not itself proof that every action by the role was malicious.","security")),
 l("Investigate",n("Amazon Detective","Entity relationships and activity context","Detective presents the graph's supported activity and relationships for the selected role and time period. The analyst inspects associated IP activity and resources to test the suspected misuse, accounting for graph coverage and data availability rather than assuming universal log collection.")),
 l("Respond",n("Incident analyst","Corroborate evidence before containment","The analyst corroborates the graph observations with relevant raw evidence, establishes affected resources and chooses approved session containment or permission changes. Detective assists analysis; it does not execute an automatic firewall or account-blocking response.","user")));
const lake=a("AWS: query normalized security evidence from a configured lake","Security Lake collects selected sources; an authorized query subscriber investigates relevant records.","https://docs.aws.amazon.com/security-lake/latest/userguide/what-is-security-lake.html",
 l("Collect",n("Configured security log sources","Selected accounts, regions and supported events","The security owner enables the intended log sources and account/region scope, including supported CloudTrail or VPC sources as required. Collection scope and permissions are checked explicitly rather than assuming all application logs are automatically included.","data")),
 l("Normalize",n("Amazon Security Lake","OCSF-aligned records in managed S3 storage","Security Lake collects and normalizes supported source records into its lake storage under the configured retention and encryption controls. Custom sources follow their integration requirements; storing evidence does not itself establish an incident or block traffic.")),
 l("Query",n("Authorized security query subscriber","Read permitted evidence for an incident","The subscriber uses its configured query access to retrieve the permitted log scope and correlate the suspect principal and time range. The investigator checks event completeness and delayed arrival before drawing a conclusion or approving remediation.","user")));
const verified=a("AWS: authorize an employee's invoice approval","The application asks Verified Permissions for a Cedar policy decision and enforces that decision before the update.","https://docs.aws.amazon.com/verifiedpermissions/latest/userguide/what-is-avp.html",
 l("Request",n("Invoice approval API","Trusted identity and invoice attributes","The API authenticates the employee and builds the authorization request from trusted principal, invoice and approval-action data. Tenant and invoice attributes come from validated application state rather than unchecked values supplied by the employee.","app")),
 l("Policy decision",n("Amazon Verified Permissions","Evaluate Cedar invoice-approval policies","The policy store evaluates the supplied principal, action, resource and applicable context against its Cedar policies. It returns an authorization decision; it does not authenticate the employee, fetch arbitrary invoice attributes or execute the invoice update.")),
 l("Enforce",n("Invoice application transaction","Commit only an allowed approval","The API denies a disallowed or failed authorization according to its safe error policy. For an allowed decision it rechecks required transactional state and records the approval under the intended invoice identity, preventing stale or duplicate updates.","app")));
const shield=a("AWS: protect a public application from a network DDoS flood","Shield Advanced protects the enrolled endpoint while the operator separates network mitigation from application request controls.","https://docs.aws.amazon.com/waf/latest/developerguide/ddos-overview.html",
 l("Protected endpoint",n("Enrolled public application endpoint","Registered supported resource and response plan","The security owner registers the intended supported endpoint for Shield Advanced protection and verifies associated health and response settings. Protection scope is explicit; an unrelated resource in the account is not assumed enrolled.","security")),
 l("Mitigate",n("AWS Shield Advanced","DDoS detection and supported mitigation","Shield Advanced detects and mitigates supported DDoS activity affecting the protected endpoint. Application-layer protection uses its configured WAF integration and response options; the operator does not treat DDoS protection as authorization for normal customer requests.")),
 l("Operate",n("Application incident owner","Check availability and remaining request abuse","The owner checks customer request success and mitigation evidence, engages the configured response process and adjusts approved application-layer controls when needed. Legitimate load and credential abuse still require application capacity and security decisions.","user")));
const firewallMgr=a("AWS: roll out a managed WAF baseline to organization accounts","Firewall Manager applies an organization policy to matching resources; WAF enforces requests at the associated supported endpoints.","https://docs.aws.amazon.com/waf/latest/developerguide/fms-chapter.html",
 l("Policy scope",n("Organization security administrator","Member accounts, tags and WAF baseline","The delegated security administrator defines the policy's account, region and resource scope with reviewed exclusions and prerequisite organization/configuration setup. The WAF baseline is tested before enabling remediation across the selected endpoints.","user")),
 l("Distribute",n("AWS Firewall Manager","Evaluate scope and apply configured remediation","Firewall Manager identifies applicable resources and manages the selected WAF policy associations under its remediation settings. Compliance distribution is its responsibility; it is not an inline packet processor or a substitute for the WAF request engine.")),
 l("Enforce and verify",n("Managed WAF-protected endpoints","Inspect requests under the assigned web ACL","The associated WAF evaluates matching requests using the deployed rules and configured actions. The owner checks rule metrics, false positives and exceptions, then verifies Firewall Manager compliance; policy compliance alone does not prove every malicious request is blocked.","security","AWS WAF")));
const trailLake=a("AWS: reconstruct an administrative change with CloudTrail Lake","A selected event data store retains management-event evidence for an authorized SQL investigation.","https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-lake.html",
 l("Select events",n("Administrative API activity","Account and management-event selector scope","The configured event data store collects the selected supported management events for the intended account or organization scope. Retention and selectors are checked so absence of a query result is not mistaken for absence of an administrative action.","data")),
 l("Retain and query",n("AWS CloudTrail Lake","SQL over selected event data stores","The authorized investigator submits a bounded SQL query for the resource, actor and incident interval. Lake searches its retained event data and returns matching API evidence; it does not replay the API action or infer the human intent behind a role session.")),
 l("Assess change",n("Change investigator","Correlate API result with resource state","The investigator compares request identity, event time and API outcome with the approved change and resource configuration. Event evidence informs the incident decision, while any rollback is separately authorized and verified.","user")));
export const reviewedScale02:Record<string,ReviewedArchitecture[]>={
 "AWS Certificate Manager":[acm],"AWS Private CA":[ca],"Amazon Macie":[macie],"Amazon Inspector":[inspector],
 "Amazon Detective":[detective],"Amazon Security Lake":[lake],"Amazon Verified Permissions":[verified],
 "AWS Shield Advanced":[shield],"AWS Firewall Manager":[firewallMgr],"AWS CloudTrail Lake":[trailLake]
};
