import type {ReviewedNode,ReviewedArchitecture} from "./reviewed-workload-architectures";
const n=(label:string,sub:string,detail:string,kind?:ReviewedNode["kind"],icon?:string):ReviewedNode=>({label,sub,detail,kind,icon});
const l=(title:string,...nodes:ReviewedNode[])=>({title,nodes});
const a=(title:string,note:string,reference:string,...layers:ReviewedArchitecture["layers"]):ReviewedArchitecture=>({title,note,reference,layers});

const awsWeb=a("AWS: protected multi-AZ container web app","An ALB routes allowed HTTP requests to healthy ECS tasks; its associated WAF policy filters requests at the ingress boundary.","https://docs.aws.amazon.com/elasticloadbalancing/latest/application/introduction.html",
 l("Client",n("Web browser","HTTPS page request","The browser resolves the application's DNS name and opens an HTTPS connection to its public load-balancer endpoint. The subsequent HTTP request specifies the host and path used by the listener rules.","user")),
 l("DNS lookup",n("Amazon Route 53","Alias to application load balancer","The hosted zone returns the application load balancer endpoint through its configured alias record. Route 53 handles DNS resolution; it does not proxy the HTTP request or select an ECS task.")),
 l("Protected ingress",n("Elastic Load Balancing","ALB listener and target groups","The ALB terminates the configured TLS connection, evaluates listener rules, and forwards accepted HTTP requests to healthy registered ECS targets. Its target health checks keep unhealthy tasks out of normal traffic routing."),n("AWS WAF","Web ACL associated with ALB","The associated web ACL evaluates applicable HTTP requests against configured rules, such as managed WAF and rate-based rules. Its action allows, blocks or challenges the request at the protected boundary. WAF does not run application code or act as a separate downstream backend.")),
 l("Application",n("Amazon ECS","Tasks in multiple AZs","The ECS service maintains the desired application tasks and registers eligible targets with the ALB according to the service configuration. The code inside the selected task validates the request, applies business rules, and performs any required database operation.")),
 l("State",n("Amazon RDS","Application records","The application connects with authorized database credentials and performs the required SQL reads or writes. A properly configured Multi-AZ deployment supplies database availability; the ALB does not load-balance SQL traffic to this database.")));

const awsStatic=a("AWS: cache static assets from a private S3 origin","CloudFront serves cache hits at the edge and signs origin requests for misses; the S3 bucket permits the intended distribution.","https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html",
 l("Visitor",n("Web browser","Request static asset","The browser requests the site's HTML, stylesheet, script or image through the CloudFront hostname or custom domain. This path serves stored content and does not require an application container.","user")),
 l("DNS",n("Amazon Route 53","Alias to distribution","The public hosted zone resolves the custom domain to its CloudFront distribution. DNS identifies the distribution endpoint; cache and origin selection happen in CloudFront.")),
 l("Edge delivery",n("Amazon CloudFront","Cache lookup and origin fetch","The distribution applies its behavior and cache policy to the requested path. A usable cache hit is returned at the edge; a miss is fetched from the configured S3 origin and cached according to response and cache-policy settings."),n("AWS WAF","Distribution-associated web ACL","The web ACL applies request filtering to the associated distribution. Matching blocking rules stop the request before content is served; allowed requests continue under CloudFront's cache and origin behavior.")),
 l("Origin authorization",n("Origin access control","Sign CloudFront origin request","The distribution's OAC signs the origin request using the configured signing behavior. An S3 bucket policy allows the intended CloudFront distribution to read the object; this setup uses an S3 bucket origin, not an S3 website endpoint.","security")),
 l("Private origin",n("Amazon S3","Stored site assets","The bucket retains the static assets and checks the signed origin request against its bucket policy. Blocking unwanted public access prevents callers from bypassing the distribution to read the private origin directly.")));

const azureWeb=a("Azure: WAF-protected regional web application","Application Gateway routes permitted HTTP requests to the application backend; WAF policy is an attached ingress control.","https://learn.microsoft.com/en-us/azure/web-application-firewall/ag/ag-overview",
 l("Request",n("Web browser","HTTPS request","The client resolves the site's public DNS name and connects to the configured Application Gateway listener. Its request contains the host and path that the gateway's routing rules evaluate.","user")),
 l("Name resolution",n("Azure DNS","Application hostname","The DNS zone maps the application hostname to the gateway's public frontend address through the configured records. Azure DNS resolves the name; it does not forward application requests.")),
 l("Ingress controls",n("Azure Application Gateway","TLS, routing and backend health","The gateway terminates TLS as configured and selects an eligible backend from its pools using listener/routing rules and health probes. The selected backend receives the forwarded HTTP request; the gateway does not perform the site's business operation."),n("Azure Web Application Firewall","Policy on Application Gateway","The attached WAF policy evaluates applicable requests using its managed and custom rules. Detection mode records matches, while prevention actions can stop disallowed requests. This is a gateway security control, not another application processing hop.")),
 l("Web backend",n("Azure App Service","Application request handler","The app's code validates the request, checks its business authorization and retrieves or updates application data. Backend hostname, TLS and network restrictions must be configured consistently with the gateway rather than assuming WAF automatically makes the app origin private.")),
 l("Data",n("Azure SQL Database","Application SQL records","The app connects through its configured authorized database access and executes SQL operations for the request. Database permissions and networking constrain that connection independently of the public gateway's WAF policy.")));

const azureStatic=a("Azure: deliver blob assets through Front Door Premium","Front Door caches static content and uses an approved Private Link origin connection to a Blob Storage account.","https://learn.microsoft.com/en-us/azure/frontdoor/scenario-storage-blobs",
 l("Visitor",n("Web browser","Request stored asset","The visitor requests an image or other static asset through the Front Door hostname or custom domain. Access requirements for that content are still enforced by the application's selected authentication or storage access design.","user")),
 l("Edge",n("Azure Front Door","Route, cache and origin health","Front Door matches the incoming request to a route and serves a valid cached object when available. A cache miss uses the configured healthy blob origin. Cache keys and forwarded query strings must be chosen so private or SAS-protected responses are not exposed unintentionally."),n("Azure Web Application Firewall","Front Door security policy","The associated Front Door security policy binds the WAF policy to the intended domain/path. Applicable requests are inspected and handled according to configured mode and rule actions before content delivery continues.")),
 l("Origin connectivity",n("Front Door origin Private Link","Approved storage connection","Front Door Premium reaches the supported Blob Storage origin through its configured private connection after the storage owner approves the private endpoint request. This protects the origin network path; it does not replace blob authorization or make every container publicly readable.","security")),
 l("Storage",n("Azure Blob Storage","Origin asset object","The account stores the requested asset and applies its configured network and blob access policy. Front Door fetches the object using the correct origin host, path and access design; storage does not generate the asset dynamically.")));

const gcpWeb=a("GCP: protected Cloud Run web endpoint","A global external Application Load Balancer routes requests through a serverless NEG; Cloud Armor policy applies at its backend service.","https://docs.cloud.google.com/load-balancing/docs/https/setup-global-ext-https-serverless",
 l("Client",n("Web browser","HTTPS request","The visitor resolves the application's domain and sends its request to the load-balancer frontend. Authentication and business authorization remain explicit requirements for the application.","user")),
 l("DNS",n("Cloud DNS","Domain to frontend address","The managed zone returns the address of the load-balancer frontend for the site's configured record. It supplies name resolution rather than choosing a Cloud Run instance or carrying the HTTP payload.")),
 l("Protected frontend",n("Cloud Load Balancing","TLS, URL map and backend service","The global external Application Load Balancer accepts HTTPS traffic, applies the configured URL map and forwards allowed requests through the backend service's serverless NEG to Cloud Run. Serverless NEGs differ from VM backends; do not assume VM-style health checks on this path."),n("Cloud Armor","Policy on backend service","The attached security policy inspects applicable requests at the load-balancer boundary and applies its configured allow, deny, or rate-control action. Allowed requests continue to the chosen backend; Armor does not execute the booking or web application's code.")),
 l("Serverless attachment",n("Serverless NEG","Cloud Run service reference","The NEG identifies the target Cloud Run service used by the backend service. It is a load-balancer configuration attachment, not a worker that processes the request or a queue that stores application messages.","app")),
 l("Backend",n("Cloud Run","Handle authorized web request","The container executes the web application's route and business logic. The internal-and-cloud-load-balancing ingress setting can restrict direct internet bypass of the load balancer; invocation authentication must also be deliberately configured. The application performs its authorized Firestore reads or writes.")),
 l("Records",n("Firestore","Web application documents","Firestore stores the application's documents under its selected data model. The backend service account has the required database permissions, while application code enforces the end user's ownership and business rules.")));

const gcpStatic=a("GCP: cache public assets with Cloud CDN","Cloud CDN serves cached assets on the load-balancer path and retrieves misses from a Cloud Storage backend bucket.","https://docs.cloud.google.com/cdn/docs/setting-up-cdn-with-bucket",
 l("Client",n("Web browser","Request public static asset","The client requests an intentionally public static asset from the site's load-balancer hostname. This example does not assume a private authenticated document is safely cacheable for every viewer.","user")),
 l("DNS",n("Cloud DNS","Hostname to load balancer","The public managed zone maps the asset hostname to the load-balancer frontend. The browser uses this answer to establish HTTPS; DNS is not a content cache or origin proxy.")),
 l("Edge routing and cache",n("Cloud Load Balancing","URL map to backend bucket","The frontend terminates the configured HTTPS connection and maps the asset path to the Cloud Storage backend bucket with Cloud CDN enabled. The URL map selects the content origin rather than invoking a Cloud Run application."),n("Cloud CDN","Cache hits and origin misses","Cloud CDN returns a usable cached response near the client. On a miss it retrieves the asset through the backend bucket path and caches it according to configured cache mode, keys and response directives. Cache invalidation or versioned names control stale content after updates.")),
 l("Origin",n("Cloud Storage","Publicly readable site assets","The bucket stores the public assets and grants the read access required for this backend-bucket design. Private content needs a deliberately configured supported access mechanism; enabling CDN alone does not grant arbitrary readers access to a private bucket.")));

export const reviewedNetworkArchitectures:Record<string,ReviewedArchitecture[]>={
 "Elastic Load Balancing":[awsWeb],"Elastic Load Balancing (ELB)":[awsWeb],
 "AWS WAF":[awsWeb,awsStatic],"Amazon CloudFront":[awsStatic],"Amazon Route 53":[awsWeb,awsStatic],
 "Azure Application Gateway":[azureWeb],"Azure Web Application Firewall":[azureWeb,azureStatic],"Azure Front Door":[azureStatic],"Azure DNS":[azureWeb],
 "Cloud Armor":[gcpWeb],"Cloud Load Balancing":[gcpWeb,gcpStatic],"Cloud CDN":[gcpStatic],"Cloud DNS":[gcpWeb,gcpStatic],
};
