import {n,l,a} from "./reviewed-architecture-builders";
import type {ReviewedArchitecture} from "./reviewed-workload-architectures";
const mysql=a("Azure: commit a portal order in MySQL Flexible Server","The backend validates the order and executes a bounded transaction over the selected private database connection.","https://learn.microsoft.com/en-us/azure/mysql/flexible-server/overview",
 l("Prepare",n("MySQL order backend","Validated order and transaction parameters","The backend validates trusted customer identity, items and request ID and connects using the configured private networking, TLS and supported database authentication. It keeps the order update within the chosen transaction boundary.","app")),
 l("Commit",n("Azure Database for MySQL Flexible Server","Atomic order and request-identity write","The database executes the permitted SQL transaction and preserves the order and duplicate-request protection. The owner configures capacity, high availability and backups separately; an HA standby is not selected as an automatic read-scaling endpoint.")),
 l("Reconcile",n("MySQL order response","Check commit outcome before retry","The backend returns success after its confirmed commit. If the connection result is uncertain it queries the stored request identity before resubmission, preventing connection recovery from creating two orders.","app")));
const postgres=a("Azure: reserve warehouse stock in PostgreSQL Flexible Server","A transaction protects stock and the request identity; availability and read routing are configured separately.","https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/overview",
 l("Validate",n("Stock reservation API","Warehouse scope and stable mutation ID","The API authenticates the caller and checks the requested warehouse and quantity. It connects through the selected private/TLS path and builds a transaction that checks available stock under the intended concurrency design.","app")),
 l("Reserve",n("Azure Database for PostgreSQL Flexible Server","Transactional stock and mutation record","The database applies the bounded stock update and request record atomically under the selected SQL isolation/locking behavior. The application handles supported transaction retries and checks replica freshness when a read endpoint is used.")),
 l("Confirm",n("Reservation response handler","Reuse committed mutation on replay","The handler returns the committed reservation or the existing outcome for a repeated mutation ID. It distinguishes an insufficient-stock business rejection from a transient database error and avoids retrying a completed reservation blindly.","app")));
const mi=a("Azure: host a migrated line-of-business SQL application","SQL Managed Instance provides the selected instance-level SQL capabilities; application validation confirms the migrated workflow.","https://learn.microsoft.com/en-us/azure/azure-sql/managed-instance/sql-managed-instance-paas-overview",
 l("Connect",n("Migrated business application","Reviewed SQL connection and compatibility","The application uses its configured private endpoint/DNS and supported authentication to reach the instance. Migration review confirms the required SQL features and dependencies rather than assuming every on-premises server feature behaves identically.","app")),
 l("Execute",n("Azure SQL Managed Instance","Business stored procedure and transaction","The instance executes the approved stored procedure and database transaction under the application's restricted account. Instance-level configuration, jobs and external dependencies are tested within their supported behavior and access controls.")),
 l("Accept",n("Business migration owner","Reconcile results and operational dependencies","The owner compares representative transaction results, data totals and scheduled-job outcomes with the accepted migration baseline. Connectivity alone is insufficient sign-off, and rollback/readiness criteria remain explicit.","user")));
const table=a("Azure: store device status using partitioned table entities","Table Storage persists keyed status entities, with optimistic concurrency and a query designed for the device access path.","https://learn.microsoft.com/en-us/azure/storage/tables/table-storage-overview",
 l("Write",n("Device status backend","Validated partition and row key","The backend validates device ownership and derives a stable PartitionKey/RowKey for the status entity. It uses the supported authorization method and the selected ETag condition to protect concurrent updates.","app")),
 l("Entity store",n("Azure Table Storage","Keyed entity and conditional update","The table persists the entity through its supported operations and applies the requested concurrency condition. Queries use the selected partition/key access pattern; the application does not assume relational joins or arbitrary cross-partition transactions.")),
 l("Read",n("Device status API","Authorized keyed status lookup","The API checks the requester's permitted devices and reads the identified entity, handling missing and conflicting versions explicitly. The stored status and timestamp are interpreted as the last accepted update rather than a guarantee of current device connectivity.","app")));
const account=a("Azure: isolate customer uploads in a secured storage account","The storage account establishes service-level configuration; application identity and object permissions restrict the upload path.","https://learn.microsoft.com/en-us/azure/storage/common/storage-account-overview",
 l("Provision",n("Storage security owner","Account type, network scope and data policy","The owner selects the supported account type, redundancy, encryption and permitted network access for customer uploads. Private endpoints and DNS are configured where selected, and unnecessary shared-key/public access is restricted under the deployment's supported controls.","user")),
 l("Storage boundary",n("Storage Accounts","Blob service configuration and access boundary","The account hosts the selected Blob containers and their service configuration. Network policy and identity permissions govern access to those endpoints; account-level settings are verified alongside container/object access rather than assuming creation makes the data private.")),
 l("Use",n("Customer upload handler","Scoped upload and completion record","The handler authorizes the customer, issues the approved restricted upload mechanism and records the completed object identity. It verifies intended scope and avoids granting broad account access merely to upload one customer document.","app")));
const archive=a("Azure: restore a retained document from the archive tier","Archived blobs must be rehydrated under the selected process before the application can read their contents.","https://learn.microsoft.com/en-us/azure/storage/blobs/archive-rehydrate-overview",
 l("Request restore",n("Document retention owner","Authorized archived document request","The owner validates the customer's right to retrieve the retained document and selects the permitted rehydration method and priority. The application reports a pending restore rather than offering an immediately readable archived object.","user")),
 l("Rehydrate",n("Archive Storage","Move or copy to an online tier","The configured operation rehydrates the archived blob to an online tier under its supported behavior and delay. The owner tracks completion and tier state, accounting for retrieval costs, lifecycle rules and any original archive retention requirement.")),
 l("Retrieve",n("Document retrieval API","Read completed online copy after authorization","Once the online object is available, the API rechecks customer ownership and supplies the restricted download. It confirms the expected version and cleanup/retention policy rather than assuming the rehydration request itself completed the retrieval.","app")));
const netapp=a("Azure: share rendering assets over a managed NFS volume","NetApp Files supplies the shared volume; workers coordinate input reads and output names under the selected export policy.","https://learn.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-introduction",
 l("Mount",n("Render worker pool","NFS client and permitted subnet path","The workers mount the selected NFS volume using the intended network path and compatible client configuration. The operator checks export policy and UID/GID permissions, with capacity and performance sized for parallel asset reads.","app")),
 l("Shared volume",n("Azure NetApp Files","Exported rendering assets and output directories","The volume stores common assets and generated frames under the selected protocol, export policy and data protections. Workers use coordinated output names; the share does not serialize conflicting application writes or replace an explicit restore procedure.")),
 l("Publish",n("Render coordinator","Validate frames before final publication","The coordinator checks expected frame counts and formats, then publishes the completed render using its agreed run identity. Failed workers are retried without treating partial output directories as a finished customer deliverable.","app")));
const adx=a("Azure: ingest and query equipment telemetry in Data Explorer","A configured ingestion connection maps events into a table for bounded KQL analysis.","https://learn.microsoft.com/en-us/azure/data-explorer/ingest-data-overview",
 l("Telemetry input",n("Equipment Event Hubs stream","Selected consumer connection and event schema","The equipment producer publishes validated timestamped readings with stable identifiers. The ingestion connection uses the selected hub and consumer group, with access permissions and the expected record format checked explicitly.",undefined,"Event Hubs")),
 l("Ingest and query",n("Azure Data Explorer","Configured mapping and KQL telemetry table","Data Explorer ingests records through the chosen connection and mapping into the target table. The analyst uses a bounded KQL time/device query, while ingestion delays, failures and duplicate records are interpreted according to the selected ingestion design.")),
 l("Interpret",n("Equipment analyst","Review temperature trends and source completeness","The analyst validates the queried time range, ingestion status and device coverage before flagging abnormal temperatures. The query result informs maintenance decisions; a table aggregation is not itself an automatic device shutdown.","user")));
const bricks=a("Azure: transform landed sales files into validated Delta tables","A Databricks job reads the selected lake batch and writes governed outputs with explicit rerun and publication behavior.","https://learn.microsoft.com/en-us/azure/databricks/lakehouse/",
 l("Input batch",n("Sales lake landing area","Completed batch and approved storage access","The producer publishes the completed sales files under the agreed batch identity. The job's configured access to the lake is restricted to required inputs and outputs; catalog metadata and storage credentials are verified separately.","storage","Azure Data Lake Storage")),
 l("Transform",n("Azure Databricks","Spark job with explicit validation and Delta writes","The job parses the input, validates sales fields, handles rejected records and writes the selected Delta target using the intended append/merge strategy. Batch identity and stable keys govern reruns instead of assuming the platform automatically prevents duplicate business rows.")),
 l("Publish",n("Sales data product owner","Reconcile and expose accepted tables","The owner checks row counts, rejection totals and sales reconciliation before exposing the approved table version to consumers. Permissions and publication completeness are tested separately from the Spark job's operational success.","user")));
const fabric=a("Azure: publish a governed sales lakehouse for reporting","Fabric coordinates the selected data pipeline, lakehouse and semantic model; acceptance checks precede report publication.","https://learn.microsoft.com/en-us/fabric/get-started/microsoft-fabric-overview",
 l("Load",n("Sales Fabric pipeline","Selected source and completed load identity","The pipeline moves the approved sales batch through its configured source connection into the chosen lakehouse target. Credentials, workspace access and rerun behavior are explicit; unrelated source data is excluded from the data product.","app")),
 l("Data product",n("Microsoft Fabric","Lakehouse tables and governed semantic model","The configured Fabric workloads transform the batch into curated tables and refresh the selected semantic model. The owner verifies the model's measures, access rules and refresh result rather than treating one workspace as automatic governance for every data item.")),
 l("Report",n("Sales report consumer","Authorized measures and validated reporting date","The viewer receives the permitted report data under the selected sharing and row-security model. The report owner checks totals, refresh time and source coverage before representing the model as the accepted sales position.","user")));
export const reviewedScale06:Record<string,ReviewedArchitecture[]>={
 "Azure Database for MySQL Flexible Server":[mysql],"Azure Database for PostgreSQL Flexible Server":[postgres],"Azure SQL Managed Instance":[mi],
 "Azure Table Storage":[table],"Storage Accounts":[account],"Archive Storage":[archive],"Azure NetApp Files":[netapp],
 "Azure Data Explorer":[adx],"Azure Databricks":[bricks],"Microsoft Fabric":[fabric]
};
