import {n,l,a} from "./reviewed-architecture-builders";
import type {ReviewedArchitecture} from "./reviewed-workload-architectures";
const proxy=a("AWS: absorb a burst of order API database connections","RDS Proxy pools compatible database connections; the API still owns its order transaction and retry policy.","https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/rds-proxy.html",
 l("Request burst",n("Order Lambda handlers","Short-lived authorized database clients","Each handler validates its order request and connects to the proxy with the configured authentication. It uses bounded transactions and avoids unnecessary session state that pins connections, preserving the intended pooling benefit.","app")),
 l("Pool",n("Amazon RDS Proxy","Reuse connections to the chosen database","The proxy authenticates the client under its configured mode and manages a connection pool to the selected RDS database. Session state can require pinning; pool limits and failover behavior are tested without assuming every in-flight transaction automatically succeeds.")),
 l("Commit",n("Order RDS database","Atomic order and idempotency update","The engine executes the handler's transaction and commits the order and request identity. The handler reconciles an uncertain commit before retrying, because connection pooling is not duplicate-order protection.","data","Amazon RDS")));
const dax=a("AWS: accelerate repeated reads of a product table","DAX supplies a read-through cache for an eventually consistent catalog view, while authoritative updates remain in DynamoDB.","https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DAX.consistency.html",
 l("Read",n("Product catalog API","Cache-tolerant product lookup","The API selects the supported DAX client for repeated product reads where the agreed staleness is acceptable. Price-critical checkout uses its designated authoritative read path instead of silently trusting cached display values.","app")),
 l("Cache",n("Amazon DynamoDB Accelerator (DAX)","Return cached item or fetch cache miss","DAX returns eligible cached reads or reads DynamoDB to populate a missing item under its TTL behavior. Its item and query caches have distinct freshness behavior; strongly consistent requests do not gain the same cached-read benefit.")),
 l("Source",n("Product DynamoDB table","Durable product records and controlled updates","The table persists the catalog records and enforces conditional updates. Writes outside DAX and query-cache expiry are included in the freshness design, and checkout validates the current price through the approved authoritative path.","data","Amazon DynamoDB")));
const streams=a("AWS: update a search index after a product record changes","DynamoDB Streams carries change records to a consumer that maintains a derived search view idempotently.","https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.Lambda.BestPracticesWithDynamoDB.html",
 l("Commit product",n("Product DynamoDB table","Persist update with selected stream view","The application commits the product update to the table. Its enabled stream view supplies the selected keys and old/new images so the consumer has the fields required for the derived search update.","data","Amazon DynamoDB")),
 l("Change records",n("Amazon DynamoDB Streams","Ordered changes for each item","The stream exposes table change records to the configured Lambda event source mapping within its retention window. Ordering applies to changes for the same item; delivery to the handler can repeat and is not a global business transaction across all products.")),
 l("Project",n("Product search indexer","Idempotent insert, update or delete","The handler uses the product key and version to apply the corresponding search-index change and handles deletion records explicitly. It preserves replay protection and reports partial failures under the configured batch policy, so retries cannot resurrect an older product version.","app")));
const memory=a("AWS: retain a low-latency game leaderboard durably","MemoryDB stores the leaderboard as the application's primary in-memory database, with explicit read and retry behavior.","https://docs.aws.amazon.com/memorydb/latest/devguide/consistency.html",
 l("Score event",n("Game score API","Validate score and stable event identity","The API authenticates the player, validates the score event and selects an atomic update or script with the supported command set. Its event identity prevents a retried request from adding the score twice.","app")),
 l("Persist score",n("Amazon MemoryDB","Sorted-set score and durable write path","MemoryDB applies the chosen leaderboard update on the relevant primary shard and durably records writes through its transactional log. The application checks primary versus replica consistency and shard boundaries rather than treating a durable primary database as a disposable cache.")),
 l("Read leaderboard",n("Leaderboard reader","Chosen freshness and shard scope","The reader retrieves the permitted rankings from its chosen endpoint and reports the expected freshness. It accounts for replica consistency and key distribution, while failure retries reuse the original score-event identity.","app")));
const doc=a("AWS: save a customer profile as a document","A MongoDB-compatible client updates the profile in DocumentDB using supported operations and the application's retry design.","https://docs.aws.amazon.com/documentdb/latest/devguide/how-it-works.html",
 l("Validate",n("Customer profile API","Authenticated profile change","The API verifies customer ownership and validates the proposed profile fields. Its driver options and operations match DocumentDB's supported compatibility, with an explicit strategy for unsupported MongoDB features and ambiguous retries.","app")),
 l("Write document",n("Amazon DocumentDB","Primary update and selected read endpoint","The primary executes the supported profile update or selected transaction. The application chooses read routing for its freshness requirement, accounts for replica lag and does not assume MongoDB retryable-write behavior is available.")),
 l("Confirm",n("Profile response handler","Reconcile stored version before success","The handler checks the committed profile version and returns the allowed fields. A repeat request uses its update identity or version condition to avoid applying the same change again when the connection result was uncertain.","app")));
const keys=a("AWS: retrieve device telemetry by device and time bucket","Keyspaces stores Cassandra-compatible rows using keys designed for the telemetry access pattern.","https://docs.aws.amazon.com/keyspaces/latest/devguide/what-is-keyspaces.html",
 l("Ingest",n("Telemetry writer","Validated device reading and time bucket","The writer validates the reading, derives the device/time-bucket partition key and uses the configured Keyspaces authentication and supported consistency. Retry writes reuse the same event key so one reading is not counted as two events.","app")),
 l("Store",n("Amazon Keyspaces","CQL rows partitioned for bounded reads","Keyspaces persists rows through the supported Cassandra-compatible interface and configured capacity mode. The schema selects partition and clustering keys for the device/time query, with supported consistency and TTL behavior chosen explicitly.")),
 l("Query",n("Device history API","Bounded device and timestamp range","The API authorizes access to the device and queries the relevant partitions and timestamp range. It pages the result and interprets retention correctly rather than attempting an unbounded relational join across all devices.","app")));
const neptune=a("AWS: trace relationships between suspicious payment accounts","Neptune executes a graph traversal over loaded account relationships; the analyst decides whether the discovered paths merit investigation.","https://docs.aws.amazon.com/neptune/latest/userguide/intro.html",
 l("Load graph",n("Account relationship ingestion","Validated vertices and payment edges","The ingestion process maps account identities and approved payment relationships into the selected graph model. Stable identifiers and ingestion versions keep duplicate records from creating misleading extra relationships.","app")),
 l("Traverse",n("Amazon Neptune","Bounded relationship query","The authorized client submits a supported graph query to follow the selected relationships within its bounded depth and filters. Neptune returns connected vertices and edges under its query semantics; a relationship path is evidence to inspect, not an automatic fraud verdict.")),
 l("Investigate",n("Payment investigator","Review source evidence for returned paths","The analyst checks the transactions and identity evidence behind the graph results before escalating an account. Access to the graph is restricted to the investigation scope, and any account action follows the approved incident process.","user")));
const redshift=a("AWS: load a completed sales batch into warehouse staging","Redshift COPY loads selected S3 files; validation and publication keep incomplete batches out of business reports.","https://docs.aws.amazon.com/redshift/latest/dg/r_COPY.html",
 l("Batch source",n("Sales S3 batch","Completed files and selected manifest","The producer publishes the completed sales files and the chosen input selection for the batch. The warehouse role has access only to the required source objects and encryption keys; file format and schema match the load definition.","storage","Amazon S3")),
 l("Load",n("Amazon Redshift","COPY into isolated staging table","The authorized load runs COPY with the reviewed source, format and error handling into staging. The operator examines load results before promotion, and batch identity governs reruns so the same files are not silently appended twice.")),
 l("Publish",n("Warehouse sales owner","Validate counts and commit business tables","The owner checks counts, rejected records and totals, then promotes the accepted batch through the approved SQL transaction or publication procedure. Reports query the published dataset instead of treating an incomplete staging load as final revenue.","user")));
const search=a("AWS: index support articles for filtered full-text search","The indexer publishes documents to OpenSearch; the query API enforces tenant scope and returns relevant article matches.","https://docs.aws.amazon.com/opensearch-service/latest/developerguide/what-is.html",
 l("Index",n("Article ingestion worker","Stable document ID and tenant fields","The worker reads approved articles, normalizes searchable fields and sends bulk indexing operations with stable article IDs. It inspects per-item failures and retries only the appropriate operations, preserving deletion and version handling.","app")),
 l("Search engine",n("Amazon OpenSearch Service","Mapped fields, indexes and search queries","The domain stores the indexed search documents and executes the permitted full-text and filter query. Mapping and refresh behavior govern matching and visibility; the index is a derived view rather than the authoritative article approval record.")),
 l("Return",n("Support search API","Authorized tenant filter and ranked articles","The API authenticates the requester, builds the tenant filter from trusted identity and returns permitted matches. It avoids trusting a caller-provided tenant and rechecks access to sensitive article contents when retrieving a result.","app")));
const kafka=a("AWS: process warehouse events through a managed Kafka topic","MSK hosts the Kafka log; the producer and consumer own record identity and safe offset advancement.","https://docs.aws.amazon.com/msk/latest/developerguide/what-is-msk.html",
 l("Produce",n("Warehouse event producer","Keyed event and configured acknowledgements","The producer sends a stable event ID with its chosen partition key and acknowledgement/idempotence settings. It authenticates to the brokers and checks produce errors without assuming a request retry can never repeat a business event.","app")),
 l("Kafka log",n("Amazon Managed Streaming for Apache Kafka","Partitioned retained topic records","MSK operates the Kafka brokers under the selected networking, authentication and topic configuration. Records are ordered within a partition; retention and consumer-group offsets are separate from whether a downstream warehouse update has committed.")),
 l("Consume",n("Warehouse event consumer","Commit business state before advancing offset","The consumer validates the event and writes its business effect idempotently before advancing its completed position. Rebalances and restarts can replay records, so the chosen database/offset failure boundary prevents skipped or duplicated warehouse changes.","app")));
export const reviewedScale03:Record<string,ReviewedArchitecture[]>={
 "Amazon RDS Proxy":[proxy],"Amazon DynamoDB Accelerator (DAX)":[dax],"Amazon DynamoDB Streams":[streams],
 "Amazon MemoryDB":[memory],"Amazon DocumentDB":[doc],"Amazon Keyspaces":[keys],"Amazon Neptune":[neptune],
 "Amazon Redshift":[redshift],"Amazon OpenSearch Service":[search],"Amazon Managed Streaming for Apache Kafka":[kafka]
};
