import type {ReviewedNode,ReviewedArchitecture} from "./reviewed-workload-architectures";
const n=(label:string,sub:string,detail:string,kind?:ReviewedNode["kind"],icon?:string):ReviewedNode=>({label,sub,detail,kind,icon});
const l=(title:string,...nodes:ReviewedNode[])=>({title,nodes});
const a=(title:string,note:string,reference:string,...layers:ReviewedArchitecture["layers"]):ReviewedArchitecture=>({title,note,reference,layers});

const blueGreen=a("AWS: validate a replacement ECS checkout before shifting traffic","A CodeDeploy-managed ECS blue/green release starts a replacement task set, exercises it through a test listener and shifts production traffic under the configured deployment policy.","https://docs.aws.amazon.com/codedeploy/latest/userguide/deployment-steps-ecs.html",
 l("Release definition",n("Checkout release artifact","Task definition and AppSpec","The approved release provides the task-definition revision and AppSpec configuration naming the container and port. The image and task roles are reviewed before deployment; the existing service is explicitly configured for this CodeDeploy-managed blue/green approach.","data")),
 l("Coordinate",n("AWS CodeDeploy","Replacement task set and traffic plan","CodeDeploy uses its configured deployment group, service role, listener and target groups to coordinate the replacement ECS task set. The deployment's hooks, traffic-shift policy, alarms and rollback settings determine when it may proceed or stop.")),
 l("Replacement runtime",n("Green ECS task set","Run new checkout containers","ECS starts the replacement tasks using the selected image and task definition. The application executes checkout validation and order logic; its database changes must remain compatible with both versions while old and new task sets coexist.","app","Amazon ECS")),
 l("Test path",n("Application Load Balancer test listener","Route validation calls to green targets","The configured test listener directs the release's validation requests to the replacement target group. The load balancer routes requests and evaluates configured target health; it does not execute checkout business tests itself.",undefined,"Elastic Load Balancing")),
 l("Lifecycle validation",n("Checkout validation hook","Test response and report hook status","The configured Lambda hook runs safe checkout checks against the test path and reports its lifecycle-hook result to CodeDeploy through the required API. Test transactions use controlled data and credentials so a release check does not create real customer charges.","app","AWS Lambda")),
 l("Production shift",n("Production listener and release controller","Move traffic under approved policy","When the configured gates succeed, CodeDeploy changes production routing according to the selected deployment policy. The old task set remains available for the configured termination or rollback period; schema compatibility and external side effects still require an application rollback plan.","app")),
 l("Accept",n("Checkout release owner","Confirm customer path and rollback readiness","The owner verifies the customer checkout path, deployment status and relevant alarms. A configured rollback can restore the prior traffic target, while any business records or schema changes created by the new version are handled through their own recovery procedures.","user")));

const slots=a("Azure: warm a ticket portal in a staging slot before swap","A tested portal package runs in an App Service staging slot, receives safe validation and warm-up, then an authorized swap moves the release into the production endpoint.","https://learn.microsoft.com/en-us/azure/app-service/deploy-staging-slots",
 l("Deploy to staging",n("Portal release pipeline","Publish tested package to staging slot","The pipeline tests and publishes the selected portal package to the staging slot on a plan supporting deployment slots. Its deployment credential is scoped to the intended app and environment, and production traffic continues using the existing production slot.","app")),
 l("Stage runtime",n("App Service","Staging application and swap preparation","App Service runs the package in the configured staging slot and performs the supported swap preparation and warm-up behavior. Slot-specific settings are explicitly configured; managed identities remain associated with their slots rather than moving with the swapped code.")),
 l("Validate",n("Staging portal tests","Exercise safe ticket operations","The release tests call the staging endpoint and check authentication, rendering and representative ticket operations against approved safe dependencies. The team verifies how production settings will affect warm-up so validation cannot accidentally send live ticket notifications.","app")),
 l("Approve and swap",n("Portal release approver","Verify configuration and initiate slot swap","The approver checks staging results, slot-specific settings and target identity permissions, then initiates the approved swap. The procedure confirms application readiness and the intended production endpoint; it does not assume all configuration and identity objects swap with the package.","user")),
 l("Production requests",n("Production ticket portal","Serve employee ticket operations","The production endpoint serves the released code, authenticates employees and performs permitted ticket operations under its production identity and settings. The team checks the actual production user path after the swap.","app")),
 l("Rollback",n("Portal operations owner","Swap back when compatible and verify data","If the release fails, the owner uses the approved reverse-swap procedure when compatible with the configuration and database state. Returning the previous code does not undo ticket changes or schema migrations, which have their own rollback or recovery plan.","user")));

export const reviewedReleaseArchitectures:Record<string,ReviewedArchitecture[]>={
 "AWS CodeDeploy":[blueGreen],"App Service":[slots],"Azure App Service":[slots],
};
