import type {ReviewedNode,ReviewedArchitecture} from "./reviewed-workload-architectures";
const n=(label:string,sub:string,detail:string,kind?:ReviewedNode["kind"],icon?:string):ReviewedNode=>({label,sub,detail,kind,icon});
const l=(title:string,...nodes:ReviewedNode[])=>({title,nodes});
const a=(title:string,note:string,reference:string,...layers:ReviewedArchitecture["layers"]):ReviewedArchitecture=>({title,note,reference,layers});

const awsRole=a("AWS: read a finance export across accounts","A source-account job assumes a narrowly scoped destination-account role, then reads an approved S3 prefix using temporary credentials.","https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html",
 l("Caller",n("Finance import job","Request destination role session","The source-account job uses its existing workload identity and requests the approved destination role with a traceable session name. Its own policy permits the required AssumeRole operation; the role's trust policy and conditions determine which caller can obtain the session.","app")),
 l("Role configuration",n("AWS IAM","Trust and role permission boundaries","The destination role trusts the intended source principal under its configured conditions and grants only the finance export operations. Trust permits role assumption; the role's permission policy controls the resulting session's resource access, subject to applicable guardrails and explicit denies.")),
 l("Temporary credentials",n("AWS Security Token Service","AssumeRole session","STS evaluates the assumption request and issues time-limited credentials for the destination role when permitted. The job uses the session credentials for its S3 calls and refreshes them through the approved flow rather than storing a permanent destination-account access key.")),
 l("Read export",n("Amazon S3 finance prefix","Authorize session and return selected object","S3 evaluates the role session's applicable policies and bucket controls and returns the permitted finance object. Any required KMS decrypt access is configured separately; permission to assume the role is not permission to read every bucket in the destination account.",undefined,"Amazon S3")),
 l("Import",n("Finance import processor","Validate export and load approved records","The job validates the received export's schema and provenance and loads its authorized records into the finance system with duplicate-run handling. Session credentials provide AWS access; the application still enforces the finance import's business controls.","app")));

const sso=a("AWS: give an operator temporary staging-account access","An assigned operator signs in through IAM Identity Center and selects the staging account's approved permission set to obtain a bounded console or CLI role session.","https://docs.aws.amazon.com/singlesignon/latest/userguide/permissionsetsconcept.html",
 l("Sign in",n("Staging operator","Workforce authentication","The operator signs in through the organization's configured identity source and completes required authentication controls. The user chooses the staging account and operational role; a successful workforce sign-in alone does not assign access to every AWS account.","user")),
 l("Account assignment",n("AWS IAM Identity Center","User or group and permission-set assignment","Identity Center checks the user's account assignments, including applicable group membership, and exposes the permitted staging-account permission set. The permission set defines the intended session access and duration and is provisioned as the corresponding account role.")),
 l("Role session",n("Staging-account permission-set role","Temporary operational credentials","The console or configured CLI flow uses temporary credentials for the assigned account role. The role's policies and applicable account guardrails bound the operator's AWS actions; retrieving a session does not override explicit denies.","security")),
 l("Operate",n("Staging deployment API","Authorized staging change","The operator's requested deployment operation is evaluated under the role session and resource controls. Approved staging changes proceed, while production actions remain outside this account assignment and permission scope.","app")),
 l("Review access",n("Workforce access owner","Assignment review and session lifecycle","The owner reviews operator and group assignments, removes unnecessary access and follows the supported session-revocation procedures when needed. Future assignment changes and already issued credentials have distinct lifecycle effects that are verified during offboarding.","user")));

const analyzer=a("AWS: review an unintended external bucket grant","An external-access analyzer evaluates a finance bucket's supported resource policy against its trust zone. The owner validates the finding and corrects unintended sharing.","https://docs.aws.amazon.com/IAM/latest/UserGuide/access-analyzer-concepts.html",
 l("Resource permission",n("Finance bucket policy","External principal grant","The bucket policy contains a grant to a principal outside the configured trust zone. The team records the principal, actions and conditions being reviewed; an externally reachable permission is not itself evidence that data was accessed.","security","Amazon S3")),
 l("Analyze",n("IAM Access Analyzer","External-access finding","The configured analyzer evaluates supported resource permissions relative to its account or organization trust zone and generates an applicable external-access finding. The finding identifies policy-derived access, not a packet inspection result or a complete inventory of the external principal's own controls.")),
 l("Investigate",n("Finance data owner","Confirm sharing purpose and scope","The owner checks whether the external recipient and allowed actions match the approved data-sharing arrangement. Expected access can be documented; unintended access requires a resource-policy correction rather than merely hiding the finding.","user")),
 l("Correct policy",n("Bucket administrator","Remove or narrow unintended grant","The administrator applies an approved policy change that removes the unintended external principal or narrows the required actions and conditions. The team tests legitimate finance jobs so remediation does not silently break the approved import path.","user")),
 l("Verify",n("Finding reevaluation","Updated policy assessment","After the resource is reanalyzed, the owner checks the finding's updated state and confirms the actual policy and intended access tests. Archiving a finding records a decision but does not modify the bucket's permissions.","data")));

const entra=a("Azure: authorize an employee's support-ticket API request","An employee signs in with Entra ID and obtains an API access token; the support API validates the token and enforces ticket ownership separately.","https://learn.microsoft.com/en-us/entra/identity-platform/claims-validation",
 l("Client sign-in",n("Employee support client","Request API scope through supported OAuth flow","The registered client uses the supported authorization-code flow with PKCE where appropriate and requests the support API's delegated scope. The browser sign-in and token handling use a supported identity library rather than custom password or token parsing.","app")),
 l("Identity provider",n("Microsoft Entra ID (formerly Azure AD)","Authenticate employee and issue API token","Entra authenticates the employee under the tenant's applicable sign-in policies and issues a token for the registered support API when the requested grant is permitted. Token audience, tenant and scope are part of the API trust contract; an ID token used for client sign-in is not substituted for API authorization.")),
 l("API validation",n("Support API token validator","Verify signature, issuer, audience and claims","The backend's supported library validates token signature, expected issuer and tenant, audience and lifetime, then requires the delegated permission for the operation. It does not trust an arbitrary client-supplied user identifier or accept a token intended for a different API.","security")),
 l("Business authorization",n("Ticket application handler","Enforce employee ownership and operation","The handler maps the validated identity to the employee record, checks permission to read or change the requested ticket and executes the permitted operation. A valid token and API scope do not automatically authorize access to another employee's ticket.","app")),
 l("Result",n("Employee ticket response","Return only permitted ticket fields","The response contains the ticket data allowed for that employee and operation. Authorization failures return the configured denial behavior without revealing unrelated ticket content; the API retains appropriate audit evidence without recording bearer tokens.","app")));

const external=a("Azure: authenticate customers for an order-history portal","An External ID external tenant provides customer sign-in; the portal API validates its access token and returns only orders belonging to the authenticated customer.","https://learn.microsoft.com/en-us/entra/architecture/deployment-external-authentication-access-control",
 l("Customer client",n("Order-history portal","Configured customer sign-in flow","The portal uses its registered customer sign-in configuration and supported client library to request the order API's scope. Customer identity configuration and consent are established for the external tenant instead of reusing an employee-only sign-in assumption.","app")),
 l("Customer identity",n("Microsoft Entra External ID","External-tenant authentication and token issuance","The configured external tenant performs the customer sign-up or sign-in flow and issues the permitted API token. Its user-flow and identity-provider configuration determine the customer authentication experience; order ownership remains an application concern.")),
 l("Validate API token",n("Customer API validator","Trusted issuer, audience and permission","The API validates the access token using the external tenant's supported metadata and signing keys, expected audience and lifetime, and requires the appropriate operation permission. Tokens from another tenant or for another resource are rejected under its trust configuration.","security")),
 l("Read customer orders",n("Order-history handler","Map identity to customer and filter records","The handler maps the validated customer identity to its internal account and queries only that account's authorized orders. It checks any requested order identifier against ownership before returning fields, so authentication does not become unrestricted order lookup.","app")),
 l("Portal result",n("Customer order response","Display authorized purchase history","The client receives the permitted purchase history or the configured denial result. Provider credentials, database credentials and other customers' data stay outside the customer token and response.","app")));

const gcpIam=a("GCP: run a report using an impersonated service account","An approved automation identity obtains a short-lived token for a reporting service account and uses that account's narrowly scoped dataset access.","https://docs.cloud.google.com/iam/docs/create-short-lived-credentials-direct",
 l("Caller",n("Report automation identity","Request reporting account token","The authenticated automation identity requests a short-lived access token for the configured reporting service account. It has the required token-creation permission on that account and avoids downloading the reporting account's long-lived private key.","security")),
 l("Delegation policy",n("Identity and Access Management (IAM)","Token-creation and dataset grants","IAM policies separately control whether the caller may impersonate the reporting account and which resources that reporting account may access. A Token Creator grant on the account does not automatically assign dataset access to either identity.")),
 l("Token issuance",n("IAM Service Account Credentials API","Short-lived reporting access token","The API validates the caller's token-creation permission and issues the supported access token for the target service account. The automation uses it within its allowed lifetime and renews it through the same approved impersonation flow when required.","security")),
 l("Query",n("Reporting query job","Execute approved dataset query","The automation submits its approved query using the reporting account token and required query-job permissions. Dataset and table permissions bound the records it may read; impersonation changes the request identity but does not bypass resource authorization.","app")),
 l("Deliver",n("Reporting result consumer","Use scoped query output","The report consumer receives the approved output under the separate report-distribution controls. Audit evidence distinguishes the calling identity and impersonated account where supported, allowing reviewers to trace how the report access was obtained.","app")));

const platform=a("GCP: authenticate a customer before a booking change","Identity Platform authenticates the customer; the backend verifies the customer's ID token and checks booking ownership before modifying the reservation.","https://docs.cloud.google.com/run/docs/tutorials/identity-platform",
 l("Sign in",n("Booking web client","Configured provider authentication","The client signs in through the configured Identity Platform provider using its supported client integration. After sign-in it obtains the customer's ID token and includes that token in the application's booking-change request.","app")),
 l("Customer identity",n("Identity Platform","Authenticate user and issue ID token","Identity Platform validates the configured sign-in flow and issues an ID token for the project or configured tenant. The token represents the authenticated customer; Google Cloud resource IAM permissions and the application's booking permissions are separate authorization systems.")),
 l("Backend validation",n("Booking token verifier","Verify project or tenant token","The backend uses the supported Admin SDK or documented verification process to validate the token's signature, audience, issuer and expiry and the expected tenant where applicable. Runtime reachability is configured for this customer-authenticated application; a customer token is not automatically a Cloud Run IAM invocation token.","security")),
 l("Booking change",n("Booking application","Check ownership and apply change","The handler uses the verified customer identifier to locate the account, checks ownership and the booking's modification rules, then commits the permitted change using its backend data identity. The client cannot choose another customer's identity by changing the request body.","app")),
 l("Result",n("Booking change response","Return committed change or denial","The backend returns the updated permitted booking or a validation or authorization error. The user-facing identity establishes who requested the change; the backend's own data permissions establish how it accesses the database.","app")));

const iap=a("GCP: protect an employee operations dashboard with IAP","IAP authenticates and authorizes entry to the configured dashboard resource. The backend validates IAP's signed assertion and applies its own operational permissions.","https://docs.cloud.google.com/iap/docs/signed-headers-howto",
 l("Employee",n("Operations dashboard browser","Request protected dashboard","The employee opens the configured IAP-protected dashboard and completes the required sign-in. The application is deployed with the intended protected ingress so a direct backend URL cannot bypass the access design.","user")),
 l("Access gate",n("Identity-Aware Proxy","Check dashboard access policy","IAP verifies the caller's supported authentication and evaluates the configured IAP access policy for this resource before forwarding the permitted request. It provides identity-aware entry control; resource configuration and backend reachability are prepared explicitly.")),
 l("Verify assertion",n("Dashboard JWT validator","Validate IAP signed header","The backend verifies the x-goog-iap-jwt-assertion signature, issuer, expected resource audience and lifetime using the documented validation method. It derives the employee identity from the verified assertion rather than trusting unverified plain-text identity headers.","security")),
 l("Operations view",n("Dashboard application","Authorize operational data and actions","The dashboard checks the employee's application-level role before reading operational records or offering a change action. IAP permission to enter the application does not alone authorize every administrative operation within it.","app")),
 l("Response",n("Authorized dashboard view","Return permitted operational information","The backend returns only the view and action options appropriate to the employee's role. Any high-impact operation receives its own authorization and confirmation under the dashboard's workflow rather than inheriting blanket authority from sign-in.","app")));

export const reviewedIdentityArchitectures:Record<string,ReviewedArchitecture[]>={
 "AWS IAM":[awsRole],"AWS Security Token Service":[awsRole],"AWS IAM Identity Center":[sso],"IAM Access Analyzer":[analyzer],
 "Microsoft Entra ID (formerly Azure AD)":[entra],"Microsoft Entra External ID":[external],
 "Identity and Access Management (IAM)":[gcpIam],"Identity Platform":[platform],"Identity-Aware Proxy":[iap],
};
