import {n,l,a} from "./reviewed-architecture-builders";
import type {ReviewedArchitecture} from "./reviewed-workload-architectures";
const alloy=a("GCP: commit a warehouse reservation in AlloyDB","The application uses the primary instance for its stock transaction and chooses read pools only for appropriate read workloads.","https://docs.cloud.google.com/alloydb/docs/overview",
 l("Validate",n("Warehouse AlloyDB client","Authorized stock request and mutation ID","The client authenticates the corporate application, validates warehouse scope and opens the configured database connection. It uses the primary for the stock mutation and preserves a stable request identity for ambiguous outcomes.","app")),
 l("Commit",n("AlloyDB","Primary SQL transaction and stock state","The primary executes the permitted SQL transaction and commits the stock update and mutation record. Read-pool routing, supported connection authentication and high availability are configured separately; the application does not send arbitrary writes to a read pool.")),
 l("Confirm",n("Stock reservation responder","Reconcile commit before retry","The responder returns the committed reservation or looks up its existing mutation record after an uncertain connection result. It handles supported transaction retries without reserving the same stock twice.","app")));
const bigtable=a("GCP: retrieve equipment readings by device and time","Bigtable row keys support the selected telemetry access pattern while the application validates reading identity and scope.","https://docs.cloud.google.com/bigtable/docs/schema-design",
 l("Write",n("Equipment telemetry writer","Validated event and distributed row-key design","The writer validates device readings and uses the selected row key, column family and timestamp strategy. Key distribution avoids a monotonically increasing hot range, and stable event identity governs retries.","app")),
 l("Store",n("Bigtable","Wide-column rows for device/time reads","Bigtable stores the selected cells under the schema and application profile. The reader's range and filters match the row-key design; transaction assumptions follow supported row operations rather than unrestricted multi-row relational atomicity.")),
 l("Query",n("Equipment history API","Authorized device/time range and pagination","The API validates access to the device and reads only its intended row range and time window. It interprets cell versions and garbage-collection policy correctly and limits result size so a history request cannot become an unbounded fleet scan.","app")));
const datastore=a("GCP: update a tenant booking with an optimistic transaction","Datastore mode stores entities; the application transaction protects the booking's concurrent update and request identity.","https://docs.cloud.google.com/datastore/docs/concepts/transactions",
 l("Request",n("Tenant booking API","Validated tenant, entity and mutation identity","The API authenticates the caller and derives the permitted booking entity key from trusted tenant scope. It validates the proposed change and carries its stable mutation ID into the selected transaction.","app")),
 l("Entity transaction",n("Firestore in Datastore mode","Read/check/write under supported transaction limits","The database executes the application's transaction against the selected entities under Datastore mode's supported behavior. Contention can require retries, so the transaction code avoids irreversible external side effects and checks the request identity.")),
 l("Respond",n("Booking confirmation handler","Return committed booking version","The handler reports the committed booking state and reconciles a repeated request through its stored identity. A query result is interpreted under the applicable Datastore mode consistency rather than assuming every datastore or index behaves identically.","app")));
const datastream=a("GCP: replicate operational changes into a BigQuery landing dataset","Datastream reads supported database changes and delivers them through the configured destination path; analytical publication accounts for replication lag.","https://docs.cloud.google.com/datastream/docs/overview",
 l("Source",n("Operational database replication source","Supported change capture and least-privilege connection","The owner enables the selected supported source prerequisites, permissions and network connection. The initial backfill and ongoing change scope identify the intended tables, and source retention is sized for recovery from replication interruptions.","data")),
 l("Replicate",n("Datastream","Backfill and supported ongoing change delivery","The stream transfers the selected source data and change records through its configured BigQuery destination integration. The owner monitors source compatibility, lag and errors; replication is not an application write transaction or a promise that a query sees the latest source commit instantly.")),
 l("Analyze",n("BigQuery replication consumer","Check schema, lag and analytical readiness","The consumer validates the destination schema and selected change-handling behavior before exposing reports. It records the usable data interval and accounts for deletes, schema changes and incomplete backfill instead of counting partial replicated data as complete business totals.","data","BigQuery")));
const dataform=a("GCP: build tested sales marts from BigQuery landing tables","Dataform compiles declared dependencies and runs selected SQL transformations and assertions under an authorized execution identity.","https://docs.cloud.google.com/dataform/docs/overview",
 l("Define",n("Sales transformation author","Versioned SQLX and dependency declarations","The author defines the staging and mart queries, dependencies and assertions for the sales dataset. The code review checks incremental keys and rerun behavior as well as the intended execution environment and access scope.","user")),
 l("Execute",n("Dataform","Compile and run selected workflow actions","The compiled workflow executes its selected BigQuery SQL actions and assertions in dependency order using the configured service account. The owner checks action results and assertion failures; a completed compilation alone does not build or validate the sales mart.")),
 l("Publish",n("Sales mart reporting owner","Validate assertions and reporting measures","The owner verifies the completed mart and assertion outcomes, reconciles totals and refreshes the downstream reporting path only under the accepted publication procedure. Failed actions are repaired before partial results are presented as final sales data.","user")));
const spark=a("GCP: transform a completed batch with managed Spark","The configured Spark execution reads selected lake files and writes validated curated outputs under an explicit batch identity.","https://docs.cloud.google.com/dataproc/docs/concepts/overview",
 l("Submit batch",n("Lake batch orchestrator","Approved Spark job and completed input","The orchestrator identifies the completed source batch and submits the reviewed Spark code through the selected supported managed execution model. Its runtime identity and networking permit only the required source reads and output writes.","app")),
 l("Process",n("Managed Service for Apache Spark","Validate, transform and write curated records","The managed Spark execution parses the selected batch, validates required fields and applies the reviewed transformation. The configured append/merge/output strategy and run identity handle failed attempts and reruns; compute provisioning does not itself deduplicate business rows.")),
 l("Accept",n("Curated lake publisher","Reconcile rows and publish completed dataset","The publisher checks job results, output counts and rejected rows, then exposes the approved output version. Consumers avoid reading incomplete run paths, and retry recovery is verified before replacing the previous published dataset.","app")));
const metastore=a("GCP: resolve shared Hive table metadata for a Spark lake job","The metastore supplies table and partition metadata while the job reads the actual files through its own storage access.","https://docs.cloud.google.com/dataproc-metastore/docs/overview",
 l("Job",n("Hive-compatible lake client","Selected table and metastore connection","The configured Spark/Hive client requests the selected table definition and partitions through the supported metastore endpoint. Network access and compatible client configuration are tested independently from the job's object-storage role.","app")),
 l("Metadata",n("Dataproc Metastore","Shared schemas, locations and partition definitions","The service supplies the requested Hive-compatible metadata under the selected deployment and access model. Its table definition describes the data location; it does not contain the full dataset or automatically grant the client permission to read the objects.")),
 l("Read files",n("Lake job storage reader","Authorized table files and schema validation","The job uses its own runtime storage permissions to read the referenced files and execute its query or transform. It checks schema compatibility and published partition completeness so stale metadata cannot silently expose an incomplete batch.","app")));
const fusion=a("GCP: integrate a completed customer file into a curated dataset","Data Fusion defines and runs a configured integration pipeline with supported connectors and explicit runtime access.","https://docs.cloud.google.com/data-fusion/docs/concepts/overview",
 l("Design",n("Customer integration owner","Source connector, mapping and output contract","The owner designs the pipeline's supported source, transformations and destination schema and verifies its credentials and runtime prerequisites. Validation, rejection handling and rerun identity are part of the pipeline contract rather than inferred from a connector name.","user")),
 l("Run pipeline",n("Cloud Data Fusion","Execute configured customer-data integration","The configured pipeline reads the completed customer file, applies its selected field transformations and writes to the approved target through its execution runtime. The owner checks plugin compatibility, runtime data permissions and per-run results.")),
 l("Publish",n("Curated customer-data owner","Reconcile output and restrict consumer access","The owner reconciles input/output counts and rejected records, then exposes only the approved customer dataset under its data-access policy. Pipeline completion is verified against business acceptance before replacing an existing published version.","user")));
const looker=a("GCP: answer a governed sales metric through Looker","The semantic model defines the measure and approved data view; Looker queries the warehouse for the authorized user.","https://docs.cloud.google.com/looker/docs/looker-core-overview",
 l("Model",n("Sales analytics modeler","Reviewed measures, joins and access filters","The modeler defines the sales measures and relationships in the selected Looker model and tests fanout and row restrictions. Model and warehouse permissions are reviewed so a visually correct dashboard does not expose unauthorized customer records.","user")),
 l("Query",n("Looker","Authorized model query against warehouse connection","Looker applies the configured user/model access and generates the selected warehouse query through its connection. Cache and freshness settings are part of the report contract, while correctness of the defined sales measure remains a reviewed modeling decision.")),
 l("Interpret",n("Sales dashboard viewer","Measure definition and data freshness","The viewer reads the permitted metrics and checks the reporting interval and refresh evidence. Drill paths use the approved access model, and the analyst validates totals against the accepted source before drawing a business conclusion.","user")));
const logging=a("GCP: collect document-processing logs for an incident investigation","The application emits selected structured logs; Logging routes and stores them under explicit scope and access controls.","https://docs.cloud.google.com/logging/docs/routing/overview",
 l("Emit evidence",n("Document processing runtime","Structured request/run logs with sensitive fields excluded","The runtime emits the configured processing state, request identity and error details while excluding document contents and secrets. Its logging integration and permissions are verified, and log emission is kept separate from the job's durable business output.","app")),
 l("Route and store",n("Logging","Log Router sinks, filters and bucket retention","Logging receives supported entries and evaluates configured routing filters, exclusions and sinks. Bucket retention, destination access and sink identity are selected explicitly; retaining a log is evidence storage rather than automatically diagnosing or fixing the document worker.")),
 l("Investigate",n("Document incident engineer","Correlate request logs with actual job state","The engineer queries the permitted log scope and correlates the request/run identity with durable status and outputs. Delayed, excluded or missing logs are considered before concluding that an action did not occur.","user")));
export const reviewedScale09:Record<string,ReviewedArchitecture[]>={
 "AlloyDB":[alloy],"Bigtable":[bigtable],"Firestore in Datastore mode":[datastore],"Datastream":[datastream],"Dataform":[dataform],
 "Managed Service for Apache Spark":[spark],"Dataproc Metastore":[metastore],"Cloud Data Fusion":[fusion],"Looker":[looker],"Logging":[logging]
};
