import {n,l,a} from "./reviewed-architecture-builders";
import type {ReviewedArchitecture} from "./reviewed-workload-architectures";
const runner=a("AWS: deploy a containerized catalog API with App Runner","A reviewed ECR image becomes a managed web service; its runtime role reads the permitted catalog data.","https://docs.aws.amazon.com/apprunner/latest/dg/service-source-image.html",
 l("Release image",n("Catalog image in ECR","Tested container and source access role","The release pipeline tests and publishes the container under the selected image identity. App Runner's image access role permits the configured ECR pull; that deployment permission is separate from the running API's data permissions.","storage","Amazon ECR")),
 l("Deploy and serve",n("AWS App Runner","Run HTTP container with health checks","App Runner deploys the selected image, supplies the managed HTTPS entry point and scales under its configured settings. The container listens on its configured port and passes health checks; private outbound access uses the chosen VPC connector rather than being inferred from an ECR pull.")),
 l("Catalog request",n("Catalog API code","Authorize query and fetch catalog records","The running application validates the request, reads the permitted catalog data using its runtime credentials and formats the response. Deployment health verifies readiness; application tests check catalog behavior and the required data access.","app")));
const beanstalk=a("AWS: release a web application into a managed environment","Elastic Beanstalk coordinates the selected application version and environment resources; the owner validates the release.","https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/Welcome.html",
 l("Package",n("Web release owner","Tested application version and configuration","The owner publishes the tested application version and reviews environment variables, platform compatibility and secret handling. The selected deployment policy and database migration plan account for old and new application instances coexisting.","user")),
 l("Deploy",n("AWS Elastic Beanstalk","Environment rollout and instance health","Beanstalk coordinates deployment of the application version onto its configured environment resources and checks environment health. The chosen rolling or immutable policy defines how instances change; persistent business data is kept outside replaceable application instances.")),
 l("Verify",n("Web application checks","Exercise customer endpoint and rollback criteria","The owner tests the customer path, data dependencies and intended release version, then observes the agreed rollback criteria. An environment marked healthy is verified against application-specific behavior before the release is accepted.","app")));
const batch=a("AWS: convert a set of documents with container batch jobs","Batch schedules queued conversion jobs onto selected compute capacity, and each job writes its result using a stable document identity.","https://docs.aws.amazon.com/batch/latest/userguide/what-is-batch.html",
 l("Submit",n("Document conversion submitter","Input object and job parameters","The submitter validates the input object and sends a job referencing the reviewed container definition, resource requirements and output identity. The job role permits only the selected input reads and output writes.","app")),
 l("Schedule",n("AWS Batch","Job queue and compatible compute environment","Batch places the job on its configured queue and schedules it when compatible compute capacity is available. Queue priority, dependencies, timeout and retries are explicit; scheduling does not perform document conversion itself.")),
 l("Convert",n("Conversion container","Read document and write validated output","The job container reads the selected input, validates its supported format, performs the conversion and writes the deterministic output. It returns the appropriate exit status and handles repeated attempts without publishing conflicting results.","app")));
const scaling=a("AWS: scale order web instances from a request-load target","The scaling group changes instance capacity; the load balancer admits only ready application targets.","https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-scaling-target-tracking.html",
 l("Load signal",n("Order fleet scaling metric","Configured target and instance warmup","The operator selects a target-tracking metric suited to the fleet, such as the configured request rate per target. The target, minimum/maximum capacity and warmup reflect tested application capacity rather than arbitrary CPU assumptions.","data")),
 l("Capacity",n("Amazon EC2 Auto Scaling","Add or remove instances within limits","The group launches the reviewed template when its policy requires capacity and removes eligible instances when permitted. Health checks, lifecycle hooks and warmup govern readiness; changing fleet size does not guarantee the database can accept the extra load.")),
 l("Serve",n("Healthy order application targets","Register, drain and process customer requests","Ready instances register with the application load balancer and validate customer orders using shared durable state. Scale-in drains requests under the configured process, and capacity tests include database limits and session handling.","app")));
const config=a("AWS: release a safer checkout feature flag gradually","AppConfig validates and deploys a configuration version; the checkout application reads and applies it.","https://docs.aws.amazon.com/appconfig/latest/userguide/what-is-appconfig.html",
 l("Review flag",n("Checkout feature owner","Validated rollout configuration","The owner prepares the checkout flag and associated limits, runs the selected validators and chooses the deployment strategy. Alarm-based rollback is configured for relevant checkout health, with a known previous configuration for recovery.","user")),
 l("Roll out",n("AWS AppConfig","Controlled configuration deployment","AppConfig validates the selected configuration and deploys it using the configured gradual rollout and monitoring behavior. The application's agent or data client retrieves configuration under its polling/cache rules; deployment does not rewrite checkout code.")),
 l("Apply",n("Checkout application","Choose tested path using retrieved flag","The application reads the retrieved version and selects the tested checkout path or safe fallback. It validates payment and order rules independently and exposes release evidence so the owner can confirm the flag's actual effect.","app")));
const sync=a("AWS: serve an authenticated GraphQL product query","AppSync validates the configured authorization and executes a resolver that reads the permitted product data.","https://docs.aws.amazon.com/appsync/latest/devguide/resolver-reference-overview.html",
 l("Query",n("Catalog GraphQL client","Authenticated query and variables","The client sends its token and requested product fields to the GraphQL endpoint. The schema and configured authorization restrict allowable operations, while tenant or customer context is derived from trusted identity.","app")),
 l("Resolve",n("AWS AppSync","GraphQL field resolver and data-source request","AppSync applies the selected authorization mode and invokes the configured resolver for the query field. The resolver shapes the permitted request to its data source and response; a schema alone does not enforce ownership of every record.")),
 l("Data",n("Authorized product data source","Return permitted catalog record","The selected data-source integration performs the requested lookup under its configured access role. Resolver logic returns only approved fields and handles missing products and downstream errors without exposing unrelated customer data.","data")));
const map=a("AWS: discover a private inventory service endpoint","Cloud Map holds registered service endpoints; the client connects directly to a discovered healthy instance.","https://docs.aws.amazon.com/cloud-map/latest/dg/what-is-cloud-map.html",
 l("Register",n("Inventory service deployment","Instance endpoint and selected health model","The deployment registers the inventory instance's endpoint and attributes in the intended Cloud Map service. It updates or removes registrations as instances change and uses the supported health mechanism chosen for the namespace.","app")),
 l("Discover",n("AWS Cloud Map","Lookup registered matching endpoints","Cloud Map answers the configured API or DNS discovery path using registered instances and applicable health behavior. Discovery returns addressing information; it does not load-balance an already established request or run the inventory query.")),
 l("Connect",n("Order API client","Direct authenticated inventory request","The client chooses a discovered endpoint, establishes the permitted connection and authenticates its inventory request. It handles stale discovery responses and endpoint failures with bounded retries, respecting DNS or application cache behavior.","app")));
const artifact=a("AWS: build a release using an approved private package","CodeArtifact stores versioned packages; the build consumes a pinned dependency under authorized repository access.","https://docs.aws.amazon.com/codeartifact/latest/ug/welcome.html",
 l("Publish",n("Package maintainer","Tested package version and repository policy","The maintainer publishes the tested package to the intended repository under controlled write permissions. Approved upstream connections and package-origin policies reduce unintended dependency sources for the release build.","user")),
 l("Resolve package",n("AWS CodeArtifact","Authenticated package repository access","The build obtains its authorized repository access and downloads the pinned package version through the supported package manager. Repository policy, domain permissions and token lifetime are configured for the build identity; storage does not itself prove code is safe.")),
 l("Build",n("Release build worker","Verify lockfile and test application","The worker uses the approved lockfile and package integrity data, runs the application tests and records the consumed versions in release evidence. A successful package download is only an input to the controlled release process.","app")));
const signer=a("AWS: enforce signed code on a Lambda release","Signer creates a signature for the approved artifact; Lambda's configured code-signing policy checks deployment.","https://docs.aws.amazon.com/signer/latest/developerguide/Welcome.html",
 l("Build",n("Lambda release pipeline","Tested ZIP artifact and signing permissions","The pipeline builds and tests the function ZIP and submits the intended S3 artifact version under its permitted signing profile. Signing follows release review rather than treating any uploaded ZIP as approved code.","app")),
 l("Sign",n("AWS Signer","Sign selected artifact with the chosen profile","Signer produces the signed artifact using the supported signing platform and configured profile. The signature establishes the artifact's signing provenance and integrity; it does not establish that the code has no vulnerabilities.")),
 l("Enforce deployment",n("Lambda code-signing configuration","Permit approved signing profile","The function's configured code-signing policy checks the signed deployment against allowed profiles and its enforcement settings. The release owner verifies deployment and execution tests, and manages profile revocation or expiry under the supported behavior.","security","AWS Lambda")));
const sam=a("AWS: deploy an order API from a reviewed serverless template","SAM translates the reviewed serverless definition into a CloudFormation deployment; application code handles the order.","https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/what-is-sam.html",
 l("Define",n("Serverless release author","API, function and table template","The author defines the order API, function, table and least-privilege access in the SAM template. Local and release tests verify the handler, while environment parameters and secret references are reviewed before packaging.","user")),
 l("Transform and deploy",n("AWS SAM","Build, package and CloudFormation transform","The build packages the selected function artifact and the SAM deployment produces the transformed CloudFormation resources. The owner reviews deployment changes and stack results; SAM is a development and provisioning model rather than a runtime request processor.")),
 l("Operate",n("Deployed order API and function","Validate and commit customer orders","The deployed API routes an authenticated order request to the function, which validates it and performs its idempotent durable write. A post-deployment test verifies the actual endpoint and data permissions before accepting the release.","app")));
export const reviewedScale04:Record<string,ReviewedArchitecture[]>={
 "AWS App Runner":[runner],"AWS Elastic Beanstalk":[beanstalk],"AWS Batch":[batch],"Amazon EC2 Auto Scaling":[scaling],
 "AWS AppConfig":[config],"AWS AppSync":[sync],"AWS Cloud Map":[map],"AWS CodeArtifact":[artifact],"AWS Signer":[signer],"AWS SAM":[sam]
};
