import type {ReviewedNode,ReviewedArchitecture} from "./reviewed-workload-architectures";
const n=(label:string,sub:string,detail:string,kind?:ReviewedNode["kind"],icon?:string):ReviewedNode=>({label,sub,detail,kind,icon});
const l=(title:string,...nodes:ReviewedNode[])=>({title,nodes});
const a=(title:string,note:string,reference:string,...layers:ReviewedArchitecture["layers"]):ReviewedArchitecture=>({title,note,reference,layers});

const aws=a("AWS: locate the slow dependency in checkout","The checkout application processes orders; explicitly configured instrumentation exports sampled timing evidence to X-Ray on a separate telemetry path.","https://docs.aws.amazon.com/xray/latest/devguide/xray-concepts.html",
 l("Business request",n("Checkout application","Validate basket and call pricing API","The checkout handler validates the basket, retrieves a price from the configured pricing dependency and returns its order result. These operations serve the customer; instrumentation measures them without making X-Ray a destination for the order's business payload.","app"),n("Pricing API","Return validated product prices","The pricing endpoint reads its authoritative price records and returns the requested product prices. The caller's instrumented HTTP dependency span records duration and outcome; trace coverage inside this API requires its own compatible instrumentation and propagated context.","app")),
 l("Measure",n("OpenTelemetry instrumentation","Request and dependency spans","Configured server and HTTP-client instrumentation creates correlated spans for the checkout request and pricing call. Sampling controls which traces are exported. Sensitive request bodies and credentials are excluded from span attributes.","app")),
 l("Export telemetry",n("ADOT Collector","Batch and send trace evidence","The configured collector receives the application's spans, applies its processing and exports them through the X-Ray exporter using authorized credentials. Export errors affect diagnostic visibility and are monitored separately from checkout success.","app")),
 l("Investigate",n("AWS X-Ray","Compare request and dependency timings","X-Ray assembles the exported trace evidence and shows the timing and error relationships. The engineer opens a slow checkout trace, compares the pricing-call duration with the handler's own work and verifies whether the latency is inside the observed dependency boundary.")));

const azure=a("Azure: diagnose a slow support-ticket submission","The application writes the ticket and returns its identifier; Azure Monitor Application Insights analyzes correlated request and dependency telemetry.","https://learn.microsoft.com/en-us/azure/azure-monitor/app/dependencies",
 l("Business operation",n("Support ticket API","Validate and persist ticket","The API validates the customer's ticket, writes its durable record through the configured database client and returns the ticket identifier. Its business responsibility is ticket creation; telemetry export is a separately configured diagnostic capability.","app"),n("Ticket database","Store submitted ticket","The database executes the requested durable write and returns its result to the API. A client-side dependency span records the observed database-call duration and outcome; it does not automatically reveal every server-side query operation.","data")),
 l("Instrument",n("Azure Monitor OpenTelemetry Distro","Correlated request and dependency evidence","The configured supported-language instrumentation records the incoming request and supported outbound dependency calls with their correlation context. Additional custom spans cover business stages where needed; redaction and sampling are configured for the application.","app")),
 l("Analyze telemetry",n("Azure Monitor","Application Insights transaction diagnostics","Application Insights receives the exported request, dependency and exception telemetry through the configured connection. The engineer examines a slow transaction to identify whether time is spent in request handling or the observed database dependency, then tests the proposed fix against the application.")),
 l("Resolve",n("Application engineer","Verify query or handler improvement","The engineer investigates the implicated code or query with the appropriate database evidence, deploys an approved improvement and compares new transaction timings. A dependency graph identifies observed relationships; it does not itself rewrite the query or fix the application.","user")));

const gcp=a("GCP: investigate slow document translation","Cloud Run validates a document request and calls Translation; explicitly configured spans show request latency and the observed translation-call duration.","https://docs.cloud.google.com/run/docs/trace",
 l("Application request",n("Cloud Run translation handler","Validate document and request translation","The handler validates the submitted text and target language, calls the authorized Translation API and returns the translated result to the caller. It propagates trace context and creates a custom span for the translation call when the selected instrumentation requires one.","app","Cloud Run"),n("Translation API","Translate authorized text","The Translation API performs the requested supported text translation and returns the translated content. The handler's dependency span measures the caller-observed latency; internal Translation implementation details are not automatically exposed in the caller's trace.","app")),
 l("Capture spans",n("OpenTelemetry instrumentation","Request and translation-call timing","The application records the request and translation dependency under the appropriate trace context. It excludes document text and credentials from attributes, uses the configured sampling policy and closes spans when their measured operations finish.","app")),
 l("Export",n("OpenTelemetry Collector","Authorized OTLP telemetry export","The configured collector receives the spans and exports them through the supported Google Cloud telemetry path using its authorized service identity. Collector network access and export permissions are diagnostic prerequisites, not the mechanism that translates the document.","app")),
 l("Investigate",n("Trace","Latency breakdown for sampled request","Trace presents the ingested request and custom spans. The engineer compares total request duration with the translation span, checks gaps and sampling coverage and determines whether input handling, the observed API call or another measured stage deserves investigation.")));

export const reviewedTracingArchitectures:Record<string,ReviewedArchitecture[]>={
 "AWS X-Ray":[aws],"Azure Monitor":[azure],"Application Insights":[azure],"Trace":[gcp],"Cloud Trace":[gcp],
};
