import {n,l,a} from "./reviewed-architecture-builders";
import type {ReviewedArchitecture} from "./reviewed-workload-architectures";
const staticApp=a("Azure: release a static customer portal with an authenticated API","Static Web Apps publishes the frontend and configured API integration; backend authorization protects personalized records.","https://learn.microsoft.com/en-us/azure/static-web-apps/overview",
 l("Build",n("Portal source pipeline","Reviewed frontend and environment configuration","The pipeline builds the selected frontend source and deploys it through the supported Static Web Apps workflow. Preview environments and production settings are reviewed so test configuration does not expose production customer data.","app")),
 l("Serve",n("Static Web Apps","Static assets and configured API access path","The service publishes the portal assets and applies configured routes and authentication behavior. Its selected API integration forwards permitted API calls; hiding a frontend route alone does not enforce customer ownership in a backend query.")),
 l("Authorize",n("Customer portal API","Trusted identity and record filtering","The API verifies the request's configured identity path, validates the operation and filters records by trusted customer identity. It checks backend access directly and returns only the permitted personalized response.","app")));
const vmss=a("Azure: scale an application VM fleet behind a load balancer","Scale Sets manages the instance fleet while probes, warmup and shared state protect customer requests.","https://learn.microsoft.com/en-us/azure/virtual-machine-scale-sets/overview",
 l("Capacity signal",n("Application fleet capacity policy","Tested metric target and readiness budget","The owner chooses the scaling rule, minimum/maximum instances and tested readiness behavior. The load signal reflects backend capacity and dependency limits, so scaling frontend machines does not silently overload the database.","data")),
 l("Fleet management",n("Virtual Machine Scale Sets","Launch reviewed instances and manage upgrades","The scale set creates the configured VM instances and applies its selected scaling and upgrade policy. Image version, instance health and network/backend-pool associations are checked, with deliberate handling of unhealthy or upgrading instances.")),
 l("Serve",n("Healthy portal VM instances","Register, process and drain requests","Ready instances receive the load balancer's permitted connections and execute portal business logic against shared durable state. Maintenance and scale-in preserve the configured draining and retry behavior, while instance-local files are not the sole business record.","app")));
const repos=a("Azure: review an API code change before a release build","Repos holds the change and pull-request controls; the selected pipeline tests the approved revision.","https://learn.microsoft.com/en-us/azure/devops/repos/get-started/what-is-repos",
 l("Change",n("API developer","Branch and traceable source revision","The developer makes the API change on a reviewed branch with the relevant test and migration changes. Secrets remain outside source control and the intended release commit is identified explicitly.","user")),
 l("Review",n("Azure Repos","Pull request, policies and approved merge","The repository enforces the configured branch policies and required reviews/status checks before merge. These controls depend on repository permissions and bypass settings; source storage does not itself execute the application's release.")),
 l("Build",n("Approved source pipeline","Build and test the chosen commit","The pipeline checks out the approved revision, resolves controlled dependencies and runs its meaningful application tests. It records the commit and artifact identity for deployment, rather than rebuilding an unreviewed moving branch later.","app","Azure Pipelines")));
const artifacts=a("Azure: consume a pinned internal package in a portal build","Artifacts provides the authorized feed and selected package version; the build verifies and tests that dependency.","https://learn.microsoft.com/en-us/azure/devops/artifacts/start-using-azure-artifacts",
 l("Publish",n("Shared package maintainer","Reviewed immutable package version","The maintainer tests the shared portal package and publishes the approved version under controlled feed write permissions. Upstream sources and package promotion are configured to match the release's dependency policy.","user")),
 l("Feed",n("Azure Artifacts","Authenticated feed and package resolution","The build identity reads the permitted feed and requested version through its supported package manager. Feed permissions and upstream behavior restrict the package source; a downloaded dependency is still subject to release testing and integrity checks.")),
 l("Consume",n("Portal build pipeline","Lockfile, integrity check and release tests","The worker resolves the pinned version and verifies the dependency lock and applicable integrity information. It tests the portal and records consumed packages in release evidence before creating the deployable artifact.","app")));
const config=a("Azure: control a portal feature with centralized configuration","App Configuration supplies selected key values or flags; the application owns refresh and the feature behavior.","https://learn.microsoft.com/en-us/azure/azure-app-configuration/overview",
 l("Review",n("Portal configuration owner","Flag values and environment label","The owner reviews the feature values, environment labels and approved release audience. Secrets use the designated secret store and reference model instead of being treated as ordinary unrestricted configuration strings.","user")),
 l("Read configuration",n("Azure App Configuration","Authorized keys and feature-flag retrieval","The service provides the permitted keys and flags to the application's configured client identity. Refresh and cache behavior are implemented by the selected client/provider; changing a stored flag does not guarantee every running instance observes it instantly.")),
 l("Apply",n("Portal feature handler","Use refreshed flag and safe fallback","The backend selects the tested feature path from its retrieved flag version and uses the agreed fallback during configuration access failure. Application ownership and payment rules still apply regardless of whether the new feature is enabled.","app")));
const signal=a("Azure: deliver authenticated order-status updates over SignalR","The application negotiates a permitted connection and publishes status messages after the order update commits.","https://learn.microsoft.com/en-us/azure/azure-signalr/signalr-overview",
 l("Negotiate",n("Order update application","Validate identity and issue connection information","The backend authenticates the customer and supplies the supported SignalR negotiation response under its configured server mode. It assigns permitted user/group scope from trusted identity rather than allowing the customer to join any order group.","app")),
 l("Connections",n("Azure SignalR Service","Managed real-time client connections","SignalR manages the established client connections and routes the backend's selected hub messages under the chosen operating mode. It transports updates; it does not commit an order or decide whether an arbitrary customer owns that order.")),
 l("Publish status",n("Order status publisher","Send permitted update after durable state change","The publisher sends the approved status to the authorized user/group after the order's durable update. Clients reconcile missed or repeated messages with the order API rather than treating an ephemeral push as the authoritative order record.","app")));
const webpub=a("Azure: push warehouse-board updates through managed WebSockets","The backend authorizes the connection and broadcasts the accepted stock update to the permitted group.","https://learn.microsoft.com/en-us/azure/azure-web-pubsub/overview",
 l("Authorize connection",n("Warehouse board API","Issue token for permitted board group","The API authenticates the operator and issues the supported Web PubSub connection information with limited roles and groups. The operator's warehouse scope is derived from trusted application identity, not unchecked client parameters.","app")),
 l("WebSocket delivery",n("Azure Web PubSub","Managed connections and group message routing","The service maintains WebSocket connections and routes the authorized server-published message to its configured group. Connection/event handling follows the selected protocol and upstream settings; group transport does not provide durable inventory transactions.")),
 l("Reconcile board",n("Warehouse board client","Apply update and refresh authoritative state","The client applies the permitted stock notification and refreshes authoritative inventory state after disconnects or detected gaps. Versioning and event identity protect repeated messages and keep a stale board from making unverified stock decisions.","app")));
const updates=a("Azure: patch the application VM fleet in a reviewed maintenance window","Update management assesses and orchestrates supported guest updates; application checks and rollback remain explicit.","https://learn.microsoft.com/en-us/azure/update-manager/overview",
 l("Plan",n("Fleet maintenance owner","Supported VM scope and maintenance configuration","The owner selects eligible machines, approves update classifications and schedules the maintenance configuration. Application draining, dependency sequencing and a recovery plan are checked before patch installation.","user")),
 l("Assess and install",n("Update management center","Guest assessment and scheduled patch orchestration","Azure Update Manager assesses the supported guest OS and orchestrates the configured patch installation under the selected scope. The operator checks per-machine outcomes, reboot settings and prerequisites rather than interpreting one job start as successful fleet patching.")),
 l("Verify",n("Application operations owner","Post-reboot service and customer checks","The owner checks each machine's update result and the load-balanced application path after any reboot. Failed instances remain excluded from service or enter the approved repair plan; package installation success is not automatic application acceptance.","user")));
const arc=a("Azure: govern an on-premises application server through Arc","The connected-machine agent supplies an Azure management representation; policy and extension operations are configured separately.","https://learn.microsoft.com/en-us/azure/azure-arc/servers/overview",
 l("Connect",n("On-premises application server","Agent onboarding and required outbound access","The operator installs and authorizes the connected-machine agent under the intended tenant and resource scope, with required outbound endpoints. The physical server and guest remain operated by their owner rather than becoming an Azure VM.","app")),
 l("Manage",n("Azure Arc","Connected server resource and supported extensions","Arc exposes the connected server as an Azure resource for configured management integrations, policies and supported extension operations. Each integration needs its own permissions/prerequisites; registering the resource does not deploy every security or update capability automatically.")),
 l("Verify",n("Hybrid operations owner","Check extension result and actual guest state","The owner verifies agent connectivity, the selected policy/extension operation and the guest's real service state. Management evidence guides approved maintenance, with private application traffic kept on its separate network path.","user")));
const advisor=a("Azure: assess a cost recommendation for a portal VM fleet","Advisor surfaces a scoped recommendation; measured workload behavior and owner approval govern its application.","https://learn.microsoft.com/en-us/azure/advisor/advisor-overview",
 l("Evidence",n("Portal fleet resource observations","Selected resource and observed utilization","The owner reviews the workload interval, actual resource configuration and usage evidence behind a recommendation. Seasonal peaks and business recovery requirements are considered before deciding that observed low use proves spare capacity.","data")),
 l("Recommend",n("Azure Advisor","Supported resource optimization guidance","Advisor analyzes supported configuration/usage signals and presents the applicable recommendations. A recommendation is advisory evidence with its stated scope; it does not establish application performance under a proposed smaller instance.")),
 l("Validate change",n("Portal platform owner","Load test and approved capacity adjustment","The owner tests the proposed change against peak request and recovery requirements, approves any deployment and checks results. Realized savings and service health are measured after the change instead of assuming the estimate guarantees the outcome.","user")));
export const reviewedScale07:Record<string,ReviewedArchitecture[]>={
 "Static Web Apps":[staticApp],"Virtual Machine Scale Sets":[vmss],"Azure Repos":[repos],"Azure Artifacts":[artifacts],
 "Azure App Configuration":[config],"Azure SignalR Service":[signal],"Azure Web PubSub":[webpub],"Update management center":[updates],
 "Azure Arc":[arc],"Azure Advisor":[advisor]
};
